'use client';

import { useState, useEffect } from 'react';
import { motion } from 'framer-motion';
import { CalendarIcon, ChartBarIcon, Cog6ToothIcon, PlusIcon, ArrowPathIcon, TrashIcon, ArrowPathRoundedSquareIcon } from '@heroicons/react/24/outline';
import { StudyCalendar } from '../../features/study-planner/components/StudyCalendar';
import { LearningMetricsComponent } from '../../features/study-planner/components/LearningMetrics';
import { HabitConfigurator } from '../../features/study-planner/components/HabitConfigurator';
import { CalendarSyncSettings } from '../../features/study-planner/components/CalendarSyncSettings';
import { SessionModal } from '../../features/study-planner/components/SessionModal';
import { useStudyPlanner } from '../../features/study-planner/hooks/useStudyPlanner';
import { Button } from '@aprende-y-aplica/ui';
import type {
  StudyPreferencesInsert,
  StudyPreferencesUpdate,
  StudySession,
  StudySessionUpdate,
} from '@repo/shared/types';

export default function StudyPlannerPage() {
  const {
    sessions,
    metrics,
    habitStats,
    preferences,
    isLoading,
    updatePreferences,
    createSession,
    updateSession,
    deleteSession,
    deleteAutoGeneratedSessions,
    regenerateSessions,
  } = useStudyPlanner();

  const [showHabitConfig, setShowHabitConfig] = useState(false);
  const [showCalendarSync, setShowCalendarSync] = useState(false);
  const [showSessionModal, setShowSessionModal] = useState(false);
  const [selectedSession, setSelectedSession] = useState<StudySession | null>(null);
  const [view, setView] = useState<'calendar' | 'metrics'>('calendar');
  const [isDeleting, setIsDeleting] = useState(false);
  const [isRegenerating, setIsRegenerating] = useState(false);
  const [error, setError] = useState<string | null>(null);

  // Verificar y refrescar tokens de calendario automáticamente al cargar la página
  useEffect(() => {
    const verifyCalendarTokens = async () => {
      try {
        // Verificar y refrescar tokens automáticamente
        const response = await fetch('/api/study-planner/calendar-integrations/verify', {
          method: 'POST',
          credentials: 'include',
        });

        const data = await response.json();
        
        if (data.success) {
          // Si hay errores en alguna integración, registrarlos pero no bloquear la UI
          if (data.data?.errors && data.data.errors.length > 0) {
            console.warn('[CALENDAR] Algunas integraciones tienen problemas:', data.data.errors);
            // Solo mostrar error si todas las integraciones fallaron
            const allFailed = data.data.integrations.length === 0 && data.data.errors.length > 0;
            if (allFailed) {
              setError(
                `No se pudieron refrescar las integraciones de calendario: ${data.data.errors.map((e: { provider: string; error: string }) => `${e.provider}`).join(', ')}`
              );
            }
          } else {
            console.log('[CALENDAR] Tokens verificados y refrescados exitosamente');
          }
        }
      } catch (err) {
        // No mostrar error al usuario si falla la verificación automática
        // Solo loguear para debugging
        console.warn('[CALENDAR] Error verificando tokens al cargar la página:', err);
      }
    };

    // Ejecutar verificación al montar el componente
    verifyCalendarTokens();

    // También verificar periódicamente (cada 30 minutos) para tokens que puedan expirar
    const interval = setInterval(verifyCalendarTokens, 30 * 60 * 1000);

    return () => clearInterval(interval);
  }, []);

  const handleSavePreferences = async (
    prefs: StudyPreferencesInsert | StudyPreferencesUpdate
  ) => {
    await updatePreferences(prefs);
  };

  const handleEventClick = (session: StudySession) => {
    setSelectedSession(session);
    setShowSessionModal(true);
  };

  const handleUpdateSession = async (sessionId: string, updates: StudySessionUpdate) => {
    await updateSession(sessionId, updates);
  };

  const handleDeleteSession = async (sessionId: string) => {
    await deleteSession(sessionId);
    setShowSessionModal(false);
    setSelectedSession(null);
  };

  const handleDateSelect = async (start: Date, end: Date) => {
    // Crear nueva sesión cuando se selecciona una fecha
    const title = prompt('Título de la sesión:');
    if (title) {
      await createSession({
        title,
        start_time: start.toISOString(),
        end_time: end.toISOString(),
        status: 'planned',
      });
    }
  };

  const handleEventDrop = async (sessionId: string, newStart: Date, newEnd: Date) => {
    await updateSession(sessionId, {
      start_time: newStart.toISOString(),
      end_time: newEnd.toISOString(),
    });
  };

  const handleDeleteAutoGenerated = async () => {
    if (!confirm('¿Estás seguro de que quieres eliminar todas las sesiones generadas automáticamente? Esta acción no se puede deshacer.')) {
      return;
    }

    setIsDeleting(true);
    setError(null);
    try {
      const result = await deleteAutoGeneratedSessions();
      alert(`Se eliminaron ${result.deletedCount} sesiones generadas automáticamente.`);
    } catch (err) {
      setError(err instanceof Error ? err.message : 'Error al eliminar sesiones');
      console.error('Error deleting auto-generated sessions:', err);
    } finally {
      setIsDeleting(false);
    }
  };

  const handleRegenerateSessions = async () => {
    if (!preferences) {
      alert('Primero debes configurar tus hábitos de estudio.');
      setShowHabitConfig(true);
      return;
    }

    if (!confirm('¿Estás seguro de que quieres regenerar todas las sesiones? Esto eliminará las sesiones actuales generadas automáticamente y creará nuevas basadas en tus preferencias actuales.')) {
      return;
    }

    setIsRegenerating(true);
    setError(null);
    try {
      const result = await regenerateSessions();
      alert(`Se regeneraron las sesiones: ${result.createdCount} sesiones creadas.`);
    } catch (err) {
      setError(err instanceof Error ? err.message : 'Error al regenerar sesiones');
      console.error('Error regenerating sessions:', err);
    } finally {
      setIsRegenerating(false);
    }
  };

  return (
    <div className="min-h-screen bg-gray-50 dark:bg-carbon py-8 px-4 sm:px-6 lg:px-8">
      <div className="max-w-7xl mx-auto">
        {/* Header */}
        <motion.div
          initial={{ opacity: 0, y: -20 }}
          animate={{ opacity: 1, y: 0 }}
          className="mb-8"
        >
          <div className="flex items-center justify-between flex-wrap gap-4">
            <div>
              <h1 className="text-3xl font-bold text-gray-900 dark:text-white">
                Planificador de Estudio
              </h1>
              <p className="text-gray-500 dark:text-gray-400 mt-1">
                Organiza tu tiempo de aprendizaje y crea hábitos de estudio
              </p>
            </div>
            <div className="flex items-center gap-3 flex-wrap">
              <Button
                variant="ghost"
                onClick={() => setShowCalendarSync(true)}
                className="flex items-center gap-2"
              >
                <ArrowPathIcon className="w-5 h-5" />
                Sincronizar Calendarios
              </Button>
              <Button
                variant="ghost"
                onClick={() => setShowHabitConfig(true)}
                className="flex items-center gap-2"
              >
                <Cog6ToothIcon className="w-5 h-5" />
                Configurar Hábitos
              </Button>
              <Button
                variant="ghost"
                onClick={handleRegenerateSessions}
                disabled={isRegenerating || !preferences}
                className="flex items-center gap-2 text-orange-600 hover:text-orange-700 dark:text-orange-400 dark:hover:text-orange-300"
              >
                <ArrowPathRoundedSquareIcon className="w-5 h-5" />
                {isRegenerating ? 'Regenerando...' : 'Regenerar Sesiones'}
              </Button>
              <Button
                variant="ghost"
                onClick={handleDeleteAutoGenerated}
                disabled={isDeleting}
                className="flex items-center gap-2 text-red-600 hover:text-red-700 dark:text-red-400 dark:hover:text-red-300"
              >
                <TrashIcon className="w-5 h-5" />
                {isDeleting ? 'Eliminando...' : 'Eliminar Sesiones Auto'}
              </Button>
              <Button
                onClick={() => setView(view === 'calendar' ? 'metrics' : 'calendar')}
                className="flex items-center gap-2"
              >
                {view === 'calendar' ? (
                  <>
                    <ChartBarIcon className="w-5 h-5" />
                    Ver Métricas
                  </>
                ) : (
                  <>
                    <CalendarIcon className="w-5 h-5" />
                    Ver Calendario
                  </>
                )}
              </Button>
            </div>
          </div>
        </motion.div>

        {/* Error Message */}
        {error && (
          <motion.div
            initial={{ opacity: 0, y: -10 }}
            animate={{ opacity: 1, y: 0 }}
            className="mb-4 p-4 bg-red-50 dark:bg-red-900/20 border border-red-200 dark:border-red-800 rounded-lg"
          >
            <p className="text-red-800 dark:text-red-200">{error}</p>
            <button
              onClick={() => setError(null)}
              className="mt-2 text-sm text-red-600 dark:text-red-400 hover:underline"
            >
              Cerrar
            </button>
          </motion.div>
        )}

        {/* Main Content */}
        {isLoading ? (
          <div className="flex items-center justify-center h-96">
            <div className="animate-spin rounded-full h-12 w-12 border-b-2 border-primary"></div>
          </div>
        ) : (
          <motion.div
            initial={{ opacity: 0, y: 20 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ delay: 0.1 }}
          >
            {view === 'calendar' ? (
              <div className="space-y-6">
                <StudyCalendar
                  sessions={sessions}
                  onEventClick={handleEventClick}
                  onDateSelect={handleDateSelect}
                  onEventDrop={handleEventDrop}
                  loading={isLoading}
                />
                {metrics && (
                  <div className="grid grid-cols-1 md:grid-cols-4 gap-4">
                    <div className="bg-white dark:bg-gray-800 rounded-xl p-6 border border-gray-200 dark:border-gray-700">
                      <p className="text-sm text-gray-500 dark:text-gray-400">Sesiones Totales</p>
                      <p className="text-2xl font-bold text-gray-900 dark:text-white">
                        {metrics.totalSessions}
                      </p>
                    </div>
                    <div className="bg-white dark:bg-gray-800 rounded-xl p-6 border border-gray-200 dark:border-gray-700">
                      <p className="text-sm text-gray-500 dark:text-gray-400">Completadas</p>
                      <p className="text-2xl font-bold text-green-600 dark:text-green-400">
                        {metrics.completedSessions}
                      </p>
                    </div>
                    <div className="bg-white dark:bg-gray-800 rounded-xl p-6 border border-gray-200 dark:border-gray-700">
                      <p className="text-sm text-gray-500 dark:text-gray-400">Racha Actual</p>
                      <p className="text-2xl font-bold text-orange-600 dark:text-orange-400">
                        {metrics.currentStreak} días
                      </p>
                    </div>
                    <div className="bg-white dark:bg-gray-800 rounded-xl p-6 border border-gray-200 dark:border-gray-700">
                      <p className="text-sm text-gray-500 dark:text-gray-400">Horas Estudiadas</p>
                      <p className="text-2xl font-bold text-blue-600 dark:text-blue-400">
                        {metrics.actualHours.toFixed(1)}h
                      </p>
                    </div>
                  </div>
                )}
              </div>
            ) : (
              metrics && (
                <LearningMetricsComponent
                  metrics={metrics}
                  habitStats={habitStats}
                  loading={isLoading}
                />
              )
            )}
          </motion.div>
        )}

        {/* Habit Configurator Modal */}
        <HabitConfigurator
          isOpen={showHabitConfig}
          onClose={() => setShowHabitConfig(false)}
          onSave={handleSavePreferences}
          initialPreferences={preferences || undefined}
        />

        {/* Calendar Sync Settings Modal */}
        <CalendarSyncSettings
          isOpen={showCalendarSync}
          onClose={() => setShowCalendarSync(false)}
        />

        {/* Session Edit/Delete Modal */}
        <SessionModal
          isOpen={showSessionModal}
          onClose={() => {
            setShowSessionModal(false);
            setSelectedSession(null);
          }}
          session={selectedSession}
          onUpdate={handleUpdateSession}
          onDelete={handleDeleteSession}
        />
      </div>
    </div>
  );
}

