import { NextRequest, NextResponse } from 'next/server';
import { SessionService } from '../../../../../features/auth/services/session.service';
import { StudyPlannerService } from '../../../../../features/study-planner/services/studyPlannerService';
import { CalendarSyncService } from '../../../../../features/study-planner/services/calendarSyncService';

/**
 * DELETE /api/study-planner/sessions/bulk
 * Elimina todas las sesiones generadas automáticamente
 */
export async function DELETE(request: NextRequest) {
  try {
    const user = await SessionService.getCurrentUser();

    if (!user) {
      return NextResponse.json(
        { success: false, error: 'No autenticado' },
        { status: 401 }
      );
    }

    // Obtener sesiones que se van a eliminar para también eliminarlas de calendarios externos
    const existingSessions = await StudyPlannerService.getStudySessions(user.id, {
      startDate: new Date().toISOString(),
    });

    const autoGeneratedSessions = existingSessions.filter(
      session => session.status === 'planned' && 
      session.description?.includes('programada automáticamente')
    );

    console.log(`[BULK DELETE] Found ${autoGeneratedSessions.length} auto-generated sessions to delete`);

    // Eliminar de calendarios externos si están sincronizadas
    const integrations = await StudyPlannerService.getCalendarIntegrations(user.id);
    console.log(`[BULK DELETE] Found ${integrations.length} calendar integrations`);
    
    let deletedFromCalendar = 0;
    let failedDeletions = 0;
    
    for (const session of autoGeneratedSessions) {
      if (session.external_event_id && session.calendar_provider) {
        // Buscar la integración que coincide con el calendar_provider de la sesión
        const matchingIntegration = integrations.find(
          integration => integration.provider === session.calendar_provider && integration.access_token
        );
        
        if (matchingIntegration) {
          try {
            // deleteEvent ahora maneja automáticamente el refresh del token si está expirado
            const deleted = await CalendarSyncService.deleteEvent(session, matchingIntegration);
            if (deleted) {
              deletedFromCalendar++;
              console.log(`[BULK DELETE] Successfully deleted session ${session.id} from ${session.calendar_provider} calendar`);
            } else {
              failedDeletions++;
              console.error(`[BULK DELETE] Failed to delete session ${session.id} from ${session.calendar_provider} calendar`);
            }
          } catch (deleteError) {
            failedDeletions++;
            console.error(`[BULK DELETE] Error deleting session ${session.id} from calendar:`, deleteError);
          }
        } else {
          console.warn(`[BULK DELETE] No matching integration found for session ${session.id} with provider ${session.calendar_provider}`);
        }
      } else {
        console.log(`[BULK DELETE] Session ${session.id} has no external_event_id or calendar_provider, skipping calendar deletion`);
      }
    }

    // Eliminar de la base de datos
    const deletedCount = await StudyPlannerService.deleteAutoGeneratedSessions(user.id);

    console.log(`[BULK DELETE] Summary: ${deletedCount} sessions deleted from database, ${deletedFromCalendar} deleted from external calendars, ${failedDeletions} failed deletions`);

    return NextResponse.json({
      success: true,
      data: {
        deletedCount,
        deletedFromCalendar,
      },
    });
  } catch (error) {
    console.error('[BULK DELETE] Error deleting auto-generated sessions:', error);
    return NextResponse.json(
      {
        success: false,
        error: {
          message: error instanceof Error ? error.message : 'Error desconocido',
          code: 'DELETE_SESSIONS_ERROR',
        },
      },
      { status: 500 }
    );
  }
}

