import { NextRequest, NextResponse } from 'next/server';
import { SessionService } from '../../../../../features/auth/services/session.service';
import { StudyPlannerService } from '../../../../../features/study-planner/services/studyPlannerService';
import { CalendarSyncService } from '../../../../../features/study-planner/services/calendarSyncService';

/**
 * DELETE /api/study-planner/sessions/bulk
 * Elimina todas las sesiones generadas automáticamente
 */
export async function DELETE(request: NextRequest) {
  try {
    const user = await SessionService.getCurrentUser();

    if (!user) {
      return NextResponse.json(
        { success: false, error: 'No autenticado' },
        { status: 401 }
      );
    }

    // Obtener sesiones que se van a eliminar para también eliminarlas de calendarios externos
    const existingSessions = await StudyPlannerService.getStudySessions(user.id, {
      startDate: new Date().toISOString(),
    });

    const autoGeneratedSessions = existingSessions.filter(
      session => session.status === 'planned' && 
      session.description?.includes('programada automáticamente')
    );

    console.log(`[BULK DELETE] Found ${autoGeneratedSessions.length} auto-generated sessions to delete`);

    // Eliminar de calendarios externos si están sincronizadas
    const integrations = await StudyPlannerService.getCalendarIntegrations(user.id);
    console.log(`[BULK DELETE] Found ${integrations.length} calendar integrations`);
    
    const activeIntegrations = integrations.filter(integration => integration.access_token);
    
    let deletedFromCalendar = 0;
    let failedDeletions = 0;
    
    for (const session of autoGeneratedSessions) {
      // Eliminar de todos los calendarios externos activos
      if (session.external_event_id) {
        for (const integration of activeIntegrations) {
          try {
            // deleteEvent ahora maneja automáticamente el refresh del token si está expirado
            const deleted = await CalendarSyncService.deleteEvent(session, integration);
            if (deleted) {
              deletedFromCalendar++;
              console.log(`[BULK DELETE] Successfully deleted session ${session.id} from ${integration.provider} calendar`);
            } else {
              // No contar como fallo si el evento simplemente no existe en ese calendario
              console.log(`[BULK DELETE] Could not delete session ${session.id} from ${integration.provider} (may not exist there)`);
            }
          } catch (deleteError) {
            failedDeletions++;
            console.error(`[BULK DELETE] Error deleting session ${session.id} from ${integration.provider}:`, deleteError);
          }
        }
      } else {
        console.log(`[BULK DELETE] Session ${session.id} has no external_event_id, skipping calendar deletion`);
      }
    }

    // Eliminar de la base de datos
    const deletedCount = await StudyPlannerService.deleteAutoGeneratedSessions(user.id);

    console.log(`[BULK DELETE] Summary: ${deletedCount} sessions deleted from database, ${deletedFromCalendar} deleted from external calendars, ${failedDeletions} failed deletions`);

    return NextResponse.json({
      success: true,
      data: {
        deletedCount,
        deletedFromCalendar,
      },
    });
  } catch (error) {
    console.error('[BULK DELETE] Error deleting auto-generated sessions:', error);
    return NextResponse.json(
      {
        success: false,
        error: {
          message: error instanceof Error ? error.message : 'Error desconocido',
          code: 'DELETE_SESSIONS_ERROR',
        },
      },
      { status: 500 }
    );
  }
}

