// Mapeo de países con sus banderas (emojis)
export const COUNTRY_FLAGS: Record<string, string> = {
  'Argentina': '🇦🇷',
  'Belice': '🇧🇿',
  'Bolivia': '🇧🇴',
  'Brasil': '🇧🇷',
  'Canadá': '🇨🇦',
  'Chile': '🇨🇱',
  'Colombia': '🇨🇴',
  'Costa Rica': '🇨🇷',
  'Cuba': '🇨🇺',
  'Ecuador': '🇪🇨',
  'El Salvador': '🇸🇻',
  'España': '🇪🇸',
  'Estados Unidos': '🇺🇸',
  'Guatemala': '🇬🇹',
  'Honduras': '🇭🇳',
  'México': '🇲🇽',
  'Nicaragua': '🇳🇮',
  'Panamá': '🇵🇦',
  'Paraguay': '🇵🇾',
  'Perú': '🇵🇪',
  'Puerto Rico': '🇵🇷',
  'República Dominicana': '🇩🇴',
  'Uruguay': '🇺🇾',
  'Venezuela': '🇻🇪',
};

export const PAISES_WITH_FLAGS = [
  'Argentina',
  'Belice',
  'Bolivia',
  'Brasil',
  'Canadá',
  'Chile',
  'Colombia',
  'Costa Rica',
  'Cuba',
  'Ecuador',
  'El Salvador',
  'España',
  'Estados Unidos',
  'Guatemala',
  'Honduras',
  'México',
  'Nicaragua',
  'Panamá',
  'Paraguay',
  'Perú',
  'Puerto Rico',
  'República Dominicana',
  'Uruguay',
  'Venezuela'
].sort().map(pais => ({
  value: pais,
  label: pais,
  flag: COUNTRY_FLAGS[pais] || '🏳️'
}));

