-- ============================================================================
-- PREGUNTAS PARA MIEMBROS DE RRHH
-- ============================================================================
-- Rol incluido:
--   - Rol ID 21: Miembros de RRHH (area_id: 6, nivel_id: 4)
-- ============================================================================

-- ============================================================================
-- ROL 21: Miembros de RRHH
-- ============================================================================

-- ADOPCIÓN - Rol 21
INSERT INTO "public"."preguntas" ("codigo", "section", "bloque", "area_id", "exclusivo_rol_id", "texto", "tipo", "opciones", "locale", "peso", "escala", "scoring", "created_at", "respuesta_correcta", "dimension", "exclusivo_nivel_id", "dificultad") VALUES
('MRH-A1', 'Cuestionario', 'Adopción', '6', '21', 'En tu trabajo de RRHH, ¿con qué frecuencia utilizas alguna herramienta de IA (por ejemplo, asistente de texto o filtros inteligentes) para redactar correos o comunicados internos?', 'Multiple Choice (escala Likert A–E)', '["Nunca", "Rara vez (≤ 1/mes)", "Ocasional (2–3/mes)", "Frecuente (semanal)", "Muy frecuente (diaria)"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', now(), null, '["Aplicación"]'::jsonb, 4, 1),

('MRH-A2', 'Cuestionario', 'Adopción', '6', '21', '¿Con qué frecuencia utilizas funciones “inteligentes” en sistemas de RRHH (por ejemplo, sugerencias automáticas, filtros avanzados) para agilizar la búsqueda de información de colaboradores?', 'Multiple Choice (escala Likert A–E)', '["Nunca", "Rara vez (≤ 1/mes)", "Ocasional (2–3/mes)", "Frecuente (semanal)", "Muy frecuente (diaria)"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', now(), null, '["Aplicación"]'::jsonb, 4, 1),

('MRH-A3', 'Cuestionario', 'Adopción', '6', '21', '¿Con qué frecuencia revisas críticamente los resultados que te entrega una herramienta de IA antes de usarlos (por ejemplo, leer un correo sugerido y corregirlo)?', 'Multiple Choice (escala Likert A–E)', '["Nunca", "Rara vez (≤ 1/mes)", "Ocasional (2–3/mes)", "Frecuente (semanal)", "Muy frecuente (diaria)"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', now(), null, '["Productividad"]'::jsonb, 4, 1),

('MRH-A4', 'Cuestionario', 'Adopción', '6', '21', '¿Con qué frecuencia compartes con tu equipo ejemplos de cómo la IA te ayudó a ahorrar tiempo en una tarea de RRHH?', 'Multiple Choice (escala Likert A–E)', '["Nunca", "Rara vez (≤ 1/mes)", "Ocasional (2–3/mes)", "Frecuente (semanal)", "Muy frecuente (diaria)"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', now(), null, '["Productividad", "Aplicación"]'::jsonb, 4, 1),

('MRH-A5', 'Cuestionario', 'Adopción', '6', '21', '¿Con qué frecuencia utilizas IA para explorar nuevas formas de mejorar la experiencia de candidatos o colaboradores (por ejemplo, mensajes más claros, mejores instrucciones)?', 'Multiple Choice (escala Likert A–E)', '["Nunca", "Rara vez (≤ 1/mes)", "Ocasional (2–3/mes)", "Frecuente (semanal)", "Muy frecuente (diaria)"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', now(), null, '["Aplicación"]'::jsonb, 4, 1),

('MRH-A6', 'Cuestionario', 'Adopción', '6', '21', '¿Con qué frecuencia dedicas tiempo a aprender, por iniciativa propia, sobre nuevas herramientas de IA aplicables a RRHH (videos, cursos, tutoriales cortos)?', 'Multiple Choice (escala Likert A–E)', '["Nunca", "Rara vez (≤ 1/mes)", "Ocasional (2–3/mes)", "Frecuente (semanal)", "Muy frecuente (diaria)"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', now(), null, '["Productividad", "Aplicación"]'::jsonb, 4, 1),

('MRH-A7', 'Cuestionario', 'Adopción', '6', '21', '¿Con qué frecuencia usas IA para mejorar la redacción de descripciones de puesto (claridad, lenguaje inclusivo, estructura)?', 'Multiple Choice (escala Likert A–E)', '["Nunca", "Rara vez (≤ 1/mes)", "Ocasional (2–3/mes)", "Frecuente (semanal)", "Muy frecuente (diaria)"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', now(), null, '["Aplicación"]'::jsonb, 4, 2),

('MRH-A8', 'Cuestionario', 'Adopción', '6', '21', '¿Con qué frecuencia utilizas IA para generar borradores de preguntas de entrevista alineadas al perfil del puesto?', 'Multiple Choice (escala Likert A–E)', '["Nunca", "Rara vez (≤ 1/mes)", "Ocasional (2–3/mes)", "Frecuente (semanal)", "Muy frecuente (diaria)"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', now(), null, '["Aplicación"]'::jsonb, 4, 2),

('MRH-A9', 'Cuestionario', 'Adopción', '6', '21', '¿Con qué frecuencia comparas cómo era tu trabajo antes y después de usar IA (por ejemplo, midiendo tiempo o número de errores)?', 'Multiple Choice (escala Likert A–E)', '["Nunca", "Rara vez (≤ 1/mes)", "Ocasional (2–3/mes)", "Frecuente (semanal)", "Muy frecuente (diaria)"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', now(), null, '["Productividad"]'::jsonb, 4, 2),

('MRH-A10', 'Cuestionario', 'Adopción', '6', '21', '¿Con qué frecuencia coordinas con compañeros de RRHH para compartir buenas prácticas de prompts o plantillas generadas con IA?', 'Multiple Choice (escala Likert A–E)', '["Nunca", "Rara vez (≤ 1/mes)", "Ocasional (2–3/mes)", "Frecuente (semanal)", "Muy frecuente (diaria)"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', now(), null, '["Aplicación"]'::jsonb, 4, 2),

('MRH-A11', 'Cuestionario', 'Adopción', '6', '21', '¿Con qué frecuencia dedicas tiempo de tu jornada a probar de forma controlada nuevas funciones de IA en las herramientas de RRHH que ya usas (ATS, HRIS, encuestas)?', 'Multiple Choice (escala Likert A–E)', '["Nunca", "Rara vez (≤ 1/mes)", "Ocasional (2–3/mes)", "Frecuente (semanal)", "Muy frecuente (diaria)"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', now(), null, '["Productividad", "Aplicación"]'::jsonb, 4, 2),

('MRH-A12', 'Cuestionario', 'Adopción', '6', '21', '¿Con qué frecuencia revisas si el uso de IA está alineado con las políticas internas de datos y ética de tu organización?', 'Multiple Choice (escala Likert A–E)', '["Nunca", "Rara vez (≤ 1/mes)", "Ocasional (2–3/mes)", "Frecuente (semanal)", "Muy frecuente (diaria)"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', now(), null, '["Estrategia", "Aplicación"]'::jsonb, 4, 2),

('MRH-A13', 'Cuestionario', 'Adopción', '6', '21', '¿Con qué frecuencia usas IA para analizar comentarios de encuestas de clima o feedback de colaboradores (por ejemplo, resúmenes, agrupación por temas)?', 'Multiple Choice (escala Likert A–E)', '["Nunca", "Rara vez (≤ 1/mes)", "Ocasional (2–3/mes)", "Frecuente (semanal)", "Muy frecuente (diaria)"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', now(), null, '["Aplicación"]'::jsonb, 4, 3),

('MRH-A14', 'Cuestionario', 'Adopción', '6', '21', '¿Con qué frecuencia ajustas prompts o instrucciones que das a la IA hasta obtener un resultado que se adapte realmente al contexto de tu organización?', 'Multiple Choice (escala Likert A–E)', '["Nunca", "Rara vez (≤ 1/mes)", "Ocasional (2–3/mes)", "Frecuente (semanal)", "Muy frecuente (diaria)"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', now(), null, '["Aplicación"]'::jsonb, 4, 3),

('MRH-A15', 'Cuestionario', 'Adopción', '6', '21', '¿Con qué frecuencia comparas indicadores clave (tiempo de respuesta, satisfacción de candidatos/colaboradores) antes y después de introducir IA en un proceso?', 'Multiple Choice (escala Likert A–E)', '["Nunca", "Rara vez (≤ 1/mes)", "Ocasional (2–3/mes)", "Frecuente (semanal)", "Muy frecuente (diaria)"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', now(), null, '["Productividad", "Aplicación"]'::jsonb, 4, 3),

('MRH-A16', 'Cuestionario', 'Adopción', '6', '21', '¿Con qué frecuencia involucras a otros equipos (TI, datos, áreas usuarias) para mejorar el uso de IA en procesos de RRHH en los que participas?', 'Multiple Choice (escala Likert A–E)', '["Nunca", "Rara vez (≤ 1/mes)", "Ocasional (2–3/mes)", "Frecuente (semanal)", "Muy frecuente (diaria)"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', now(), null, '["Aplicación"]'::jsonb, 4, 3),

('MRH-A17', 'Cuestionario', 'Adopción', '6', '21', '¿Con qué frecuencia dedicas tiempo semanal a mantener organizados y actualizados los datos que usa la IA (por ejemplo, campos de CVs, catálogos depuestos, motivos de salida)?', 'Multiple Choice (escala Likert A–E)', '["Nunca", "Rara vez (≤ 1/mes)", "Ocasional (2–3/mes)", "Frecuente (semanal)", "Muy frecuente (diaria)"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', now(), null, '["Productividad", "Aplicación"]'::jsonb, 4, 3),

('MRH-A18', 'Cuestionario', 'Adopción', '6', '21', '¿Con qué frecuencia planteas dudas o banderas rojas cuando notas que la IA podría estar generando resultados injustos (por ejemplo, siempre favorece cierto tipo de perfil)?', 'Multiple Choice (escala Likert A–E)', '["Nunca", "Rara vez (≤ 1/mes)", "Ocasional (2–3/mes)", "Frecuente (semanal)", "Muy frecuente (diaria)"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', now(), null, '["Productividad"]'::jsonb, 4, 3),

('MRH-A19', 'Cuestionario', 'Adopción', '6', '21', '¿Con qué frecuencia documentas flujos de trabajo de RRHH donde interviene la IA (qué hace la herramienta y qué hace cada persona)?', 'Multiple Choice (escala Likert A–E)', '["Nunca", "Rara vez (≤ 1/mes)", "Ocasional (2–3/mes)", "Frecuente (semanal)", "Muy frecuente (diaria)"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', now(), null, '["Aplicación"]'::jsonb, 4, 4),

('MRH-A20', 'Cuestionario', 'Adopción', '6', '21', '¿Con qué frecuencia propones o ajustas experimentos (pilotos) de IA en procesos de RRHH, definiendo claramente objetivos e indicadores de éxito?', 'Multiple Choice (escala Likert A–E)', '["Nunca", "Rara vez (≤ 1/mes)", "Ocasional (2–3/mes)", "Frecuente (semanal)", "Muy frecuente (diaria)"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', now(), null, '["Aplicación"]'::jsonb, 4, 4),

('MRH-A21', 'Cuestionario', 'Adopción', '6', '21', '¿Con qué frecuencia colaboras con otras áreas (TI, Legal, Datos) para garantizar que el uso de IA en RRHH cumpla normativas y buenas prácticas?', 'Multiple Choice (escala Likert A–E)', '["Nunca", "Rara vez (≤ 1/mes)", "Ocasional (2–3/mes)", "Frecuente (semanal)", "Muy frecuente (diaria)"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', now(), null, '["Aplicación"]'::jsonb, 4, 4),

('MRH-A22', 'Cuestionario', 'Adopción', '6', '21', '¿Con qué frecuencia creas y compartes plantillas de prompts o guías de uso de IA para que otros miembros de RRHH trabajen de forma más eficiente?', 'Multiple Choice (escala Likert A–E)', '["Nunca", "Rara vez (≤ 1/mes)", "Ocasional (2–3/mes)", "Frecuente (semanal)", "Muy frecuente (diaria)"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', now(), null, '["Aplicación"]'::jsonb, 4, 4),

('MRH-A23', 'Cuestionario', 'Adopción', '6', '21', '¿Con qué frecuencia revisas el retorno de inversión (tiempo, calidad, errores) de las herramientas de IA que utilizas en comparación con otras alternativas manuales o tradicionales?', 'Multiple Choice (escala Likert A–E)', '["Nunca", "Rara vez (≤ 1/mes)", "Ocasional (2–3/mes)", "Frecuente (semanal)", "Muy frecuente (diaria)"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', now(), null, '["Productividad", "Aplicación", "Inversión"]'::jsonb, 4, 4),

('MRH-A24', 'Cuestionario', 'Adopción', '6', '21', '¿Con qué frecuencia propones ajustes o restricciones al uso de IA cuando detectas posibles impactos negativos en la experiencia humana (por ejemplo, procesos demasiado fríos o impersonales)?', 'Multiple Choice (escala Likert A–E)', '["Nunca", "Rara vez (≤ 1/mes)", "Ocasional (2–3/mes)", "Frecuente (semanal)", "Muy frecuente (diaria)"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', now(), null, '["Aplicación"]'::jsonb, 4, 4),

('MRH-A25', 'Cuestionario', 'Adopción', '6', '21', '¿Con qué frecuencia lideras o facilitas espacios (talleres, demos, sesiones informales) para que otros miembros de RRHH aprendan a usar IA en sus tareas?', 'Multiple Choice (escala Likert A–E)', '["Nunca", "Rara vez (≤ 1/mes)", "Ocasional (2–3/mes)", "Frecuente (semanal)", "Muy frecuente (diaria)"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', now(), null, '["Aplicación"]'::jsonb, 4, 5),

('MRH-A26', 'Cuestionario', 'Adopción', '6', '21', '¿Con qué frecuencia revisas datos segmentados (por ejemplo, por género, edad, área) para detectar posibles sesgos en los procesos donde interviene IA?', 'Multiple Choice (escala Likert A–E)', '["Nunca", "Rara vez (≤ 1/mes)", "Ocasional (2–3/mes)", "Frecuente (semanal)", "Muy frecuente (diaria)"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', now(), null, '["Estrategia", "Aplicación"]'::jsonb, 4, 5),

('MRH-A27', 'Cuestionario', 'Adopción', '6', '21', '¿Con qué frecuencia participas en decisiones sobre qué herramientas de IA vale la pena mantener, ampliar o descartar, aportando datos de uso e impacto desde RRHH?', 'Multiple Choice (escala Likert A–E)', '["Nunca", "Rara vez (≤ 1/mes)", "Ocasional (2–3/mes)", "Frecuente (semanal)", "Muy frecuente (diaria)"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', now(), null, '["Aplicación"]'::jsonb, 4, 5),

('MRH-A28', 'Cuestionario', 'Adopción', '6', '21', '¿Con qué frecuencia trabajas con líderes de otras áreas para diseñar iniciativas de personas que se apoyan explícitamente en IA (por ejemplo, analítica de rotación, desarrollo de talento)?', 'Multiple Choice (escala Likert A–E)', '["Nunca", "Rara vez (≤ 1/mes)", "Ocasional (2–3/mes)", "Frecuente (semanal)", "Muy frecuente (diaria)"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', now(), null, '["Estrategia", "Aplicación"]'::jsonb, 4, 5),

('MRH-A29', 'Cuestionario', 'Adopción', '6', '21', '¿Con qué frecuencia estableces y comunicas criterios claros sobre cuándo no usar IA en RRHH (casos altamente sensibles, decisiones críticas, etc.)?', 'Multiple Choice (escala Likert A–E)', '["Nunca", "Rara vez (≤ 1/mes)", "Ocasional (2–3/mes)", "Frecuente (semanal)", "Muy frecuente (diaria)"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', now(), null, '["Aplicación"]'::jsonb, 4, 5),

('MRH-A30', 'Cuestionario', 'Adopción', '6', '21', '¿Con qué frecuencia propones ajustes en la distribución de tiempo, presupuesto o personas para fortalecer las capacidades de IA del equipo de RRHH (formación, roles, herramientas)?', 'Multiple Choice (escala Likert A–E)', '["Nunca", "Rara vez (≤ 1/mes)", "Ocasional (2–3/mes)", "Frecuente (semanal)", "Muy frecuente (diaria)"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', now(), null, '["Productividad", "Aplicación", "Inversión"]'::jsonb, 4, 5);

-- CONOCIMIENTO - Rol 21
INSERT INTO "public"."preguntas" ("codigo", "section", "bloque", "area_id", "exclusivo_rol_id", "texto", "tipo", "opciones", "locale", "peso", "escala", "scoring", "created_at", "respuesta_correcta", "dimension", "exclusivo_nivel_id", "dificultad") VALUES
('MRH-C1', 'Cuestionario', 'Conocimiento', '6', '21', 'En tu trabajo de RRHH, ¿cuál de las siguientes opciones describe mejor qué es la inteligencia artificial (IA)?', 'Multiple Choice (una respuesta)', '["Un tipo de hoja de cálculo avanzada de Excel", "Cualquier programa de computadora que guarda archivos", "Sistemas que aprenden de datos para tomar decisiones o generar contenido", "Solo robots físicos que reemplazan personas"]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', now(), 'Sistemas que aprenden de datos para tomar decisiones o generar contenido', '["Conocimiento"]'::jsonb, 4, 1),

('MRH-C2', 'Cuestionario', 'Conocimiento', '6', '21', '¿Cuál es un ejemplo sencillo de IA aplicada a reclutamiento?', 'Multiple Choice (una respuesta)', '["Guardar CVs en carpetas compartidas", "Enviar correos manualmente a cada candidato", "Usar un sistema que ordena automáticamente CVs según requisitos del puesto", "Imprimir todos los CVs y revisarlos en papel"]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', now(), 'Usar un sistema que ordena automáticamente CVs según requisitos del puesto', '["Conocimiento", "Aplicación"]'::jsonb, 4, 1),

('MRH-C3', 'Cuestionario', 'Conocimiento', '6', '21', 'Al usar IA con información de colaboradores, ¿qué cuidado básico debes tener?', 'Multiple Choice (una respuesta)', '["Compartir libremente los datos para mejorar los modelos", "Subir datos sensibles sin avisar a nadie", "Proteger datos personales y seguir las políticas de privacidad de la empresa", "Evitar por completo usar datos en IA"]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', now(), 'Proteger datos personales y seguir las políticas de privacidad de la empresa', '["Conocimiento", "Aplicación"]'::jsonb, 4, 1),

('MRH-C4', 'Cuestionario', 'Conocimiento', '6', '21', '¿Cuál de estas tareas es más adecuada para automatizar con IA en RRHH?', 'Multiple Choice (una respuesta)', '["Decidir a quién despedir", "Hacer una primera propuesta de correo de bienvenida a nuevos ingresos", "Tener conversaciones sensibles de desempeño", "Firmar contratos en nombre de la empresa"]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', now(), 'Hacer una primera propuesta de correo de bienvenida a nuevos ingresos', '["Conocimiento", "Productividad"]'::jsonb, 4, 1),

('MRH-C5', 'Cuestionario', 'Conocimiento', '6', '21', '¿Cuál es la diferencia entre una macro simple de Excel y un sistema de IA?', 'Multiple Choice (una respuesta)', '["No hay ninguna diferencia", "La macro siempre aprende sola y mejora con el tiempo", "La IA puede aprender de datos nuevos; una macro solo sigue instrucciones fijas", "La macro usa muchos datos y la IA no"]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', now(), 'La IA puede aprender de datos nuevos; una macro solo sigue instrucciones fijas', '["Conocimiento"]'::jsonb, 4, 1),

('MRH-C6', 'Cuestionario', 'Conocimiento', '6', '21', 'Cuando un modelo de IA sugiere candidatos “ideales” y deja fuera casi solo a mujeres, podríamos estar frente a:', 'Multiple Choice (una respuesta)', '["Un error de Excel", "Un sesgo en los datos o en el modelo", "Una falla de conexión a internet", "Una práctica obligatoria en selección"]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', now(), 'Un sesgo en los datos o en el modelo', '["Conocimiento", "Aplicación"]'::jsonb, 4, 1),

('MRH-C7', 'Cuestionario', 'Conocimiento', '6', '21', '¿Cuál de estas acciones es más segura al usar un asistente de IA abierto (como ChatGPT) en RRHH?', 'Multiple Choice (una respuesta)', '["Pegar nóminas completas con nombres y salarios", "Describir el caso de forma anónima sin datos personales", "Compartir datos médicos específicos de un colaborador", "Subir copias de contratos con información sensible"]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', now(), 'Describir el caso de forma anónima sin datos personales', '["Conocimiento"]'::jsonb, 4, 2),

('MRH-C8', 'Cuestionario', 'Conocimiento', '6', '21', 'Un beneficio clave de usar IA en el filtrado inicial de CVs es:', 'Multiple Choice (una respuesta)', '["Aumentar la carga manual del equipo", "Reducir el tiempo para identificar candidatos que cumplen requisitos mínimos", "Eliminar por completo la necesidad de entrevistar candidatos", "Evitar cumplir las leyes laborales"]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', now(), 'Reducir el tiempo para identificar candidatos que cumplen requisitos mínimos', '["Conocimiento"]'::jsonb, 4, 2),

('MRH-C9', 'Cuestionario', 'Conocimiento', '6', '21', '¿Cuál de estas tareas es un uso adecuado de IA generativa en RRHH?', 'Multiple Choice (una respuesta)', '["Decidir automáticamente aumentos salariales sin revisión humana", "Crear borradores de preguntas para entrevistas de competencias", "Enviar rechazo automático sin supervisión en casos delicados", "Sustituir completamente al área legal"]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', now(), 'Crear borradores de preguntas para entrevistas de competencias', '["Conocimiento", "Aplicación"]'::jsonb, 4, 2),

('MRH-C10', 'Cuestionario', 'Conocimiento', '6', '21', 'Cuando una herramienta de IA explica cómo obtuvo un resultado y permite revisar los datos usados, hablamos de:', 'Multiple Choice (una respuesta)', '["Opacidad total", "Explicabilidad y transparencia", "Aleatoriedad", "Automatización ciega"]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', now(), 'Explicabilidad y transparencia', '["Conocimiento", "Aplicación"]'::jsonb, 4, 2),

('MRH-C11', 'Cuestionario', 'Conocimiento', '6', '21', 'En selección, una buena práctica al usar IA para revisar CVs es:', 'Multiple Choice (una respuesta)', '["Confiar 100% en el ranking que entrega la herramienta", "Combinar el ranking de IA con la revisión humana para evitar sesgos", "Dejar que la IA llame por teléfono a los candidatos", "Usar siempre el mismo modelo, aunque cambien los perfiles"]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', now(), 'Combinar el ranking de IA con la revisión humana para evitar sesgos', '["Conocimiento"]'::jsonb, 4, 2),

('MRH-C12', 'Cuestionario', 'Conocimiento', '6', '21', '¿Cuál indicador refleja mejor el aporte de IA a la productividad del equipo de RRHH?', 'Multiple Choice (una respuesta)', '["Número total de correos enviados", "Horas promedio ahorradas en tareas repetitivas", "Número de hojas impresas", "Cantidad de reuniones agendadas sin criterio"]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', now(), 'Horas promedio ahorradas en tareas repetitivas', '["Conocimiento", "Productividad", "Aplicación"]'::jsonb, 4, 2),

('MRH-C13', 'Cuestionario', 'Conocimiento', '6', '21', 'En un análisis de clima laboral, ¿cómo puede ayudar la IA a procesar respuestas abiertas de encuestas?', 'Multiple Choice (una respuesta)', '["Contando solo el número de respuestas", "Traduciendo automáticamente todas las respuestas a otro idioma y nada más", "Agrupando comentarios por temas (por ejemplo, liderazgo, carga de trabajo) y sentimiento", "Eliminando respuestas negativas para mejorar el índice"]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', now(), 'Agrupando comentarios por temas (por ejemplo, liderazgo, carga de trabajo) y sentimiento', '["Conocimiento"]'::jsonb, 4, 3),

('MRH-C14', 'Cuestionario', 'Conocimiento', '6', '21', 'Cuando usamos IA para priorizar candidatos, ¿qué práctica ayuda a reducir sesgos?', 'Multiple Choice (una respuesta)', '["No revisar el modelo si parece funcionar rápido", "Revisar periódicamente ejemplos de candidatos descartados y sus características", "Evitar registrar decisiones de selección", "Usar siempre los mismos criterios sin validarlos"]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', now(), 'Revisar periódicamente ejemplos de candidatos descartados y sus características', '["Estrategia", "Conocimiento", "Aplicación"]'::jsonb, 4, 3),

('MRH-C15', 'Cuestionario', 'Conocimiento', '6', '21', '¿Cuál es un buen uso de IA en procesos de capacitación?', 'Multiple Choice (una respuesta)', '["Asignar cursos sin considerar el rol o brecha de habilidades", "Generar propuestas de rutas de aprendizaje personalizadas según competencias y feedback", "Obligar a todos a tomar el mismo curso", "Reemplazar cualquier interacción con el jefe directo"]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', now(), 'Generar propuestas de rutas de aprendizaje personalizadas según competencias y feedback', '["Conocimiento", "Aplicación"]'::jsonb, 4, 3),

('MRH-C16', 'Cuestionario', 'Conocimiento', '6', '21', 'La diferencia entre un simple “autocompletar” de texto y un modelo de IA generativa más avanzado es que este último:', 'Multiple Choice (una respuesta)', '["Nunca comete errores", "Puede generar contenido nuevo y adaptado al contexto a partir de grandes volúmenes de datos", "Solo copia frases frecuentes sin contexto", "No necesita datos de entrenamiento"]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', now(), 'Puede generar contenido nuevo y adaptado al contexto a partir de grandes volúmenes de datos', '["Conocimiento"]'::jsonb, 4, 3),

('MRH-C17', 'Cuestionario', 'Conocimiento', '6', '21', 'Para evaluar el impacto de IA en el tiempo de cobertura de vacantes, ¿qué indicador es más relevante?', 'Multiple Choice (una respuesta)', '["Número de entrevistas presenciales realizadas", "Días promedio desde la apertura de la vacante hasta la aceptación de la oferta", "Número de publicaciones en redes sociales", "Cantidad de candidatos rechazados"]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', now(), 'Días promedio desde la apertura de la vacante hasta la aceptación de la oferta', '["Conocimiento", "Productividad"]'::jsonb, 4, 3),

('MRH-C18', 'Cuestionario', 'Conocimiento', '6', '21', 'Si una herramienta de IA se integra con el HRIS para generar reportes mensuales de rotación, esto es un ejemplo de:', 'Multiple Choice (una respuesta)', '["Uso aislado y manual de IA", "Integración operativa de IA en procesos existentes", "Sustitución total del área de RRHH", "Uso exclusivamente estratégico de IA"]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', now(), 'Integración operativa de IA en procesos existentes', '["Conocimiento", "Productividad"]'::jsonb, 4, 3),

('MRH-C19', 'Cuestionario', 'Conocimiento', '6', '21', 'En un flujo de reclutamiento con IA, ¿qué práctica favorece un uso responsable?', 'Multiple Choice (una respuesta)', '["No informar a candidatos que se utilizan herramientas automatizadas", "Probar el modelo solo con datos históricos sin actualizarlo", "Documentar el rol de la IA y de las personas en cada etapa (screening, entrevistas, decisión)", "Dejar todo el proceso en manos de la IA"]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', now(), 'Documentar el rol de la IA y de las personas en cada etapa (screening, entrevistas, decisión)', '["Conocimiento", "Aplicación"]'::jsonb, 4, 4),

('MRH-C20', 'Cuestionario', 'Conocimiento', '6', '21', 'Cuando se combinan varias fuentes de datos (ATS, HRIS, encuestas) para que la IA sugiera prioridades de acción de RRHH, estamos aplicando principalmente:', 'Multiple Choice (una respuesta)', '["Mejora aislada de una sola tarea", "Integración de datos para decisiones más estratégicas", "Un truco visual sin impacto real", "Únicamente automatización de nómina"]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', now(), 'Integración de datos para decisiones más estratégicas', '["Conocimiento", "Aplicación"]'::jsonb, 4, 4),

('MRH-C21', 'Cuestionario', 'Conocimiento', '6', '21', '¿Cuál de las siguientes métricas refleja mejor una buena inversión en IA en RRHH?', 'Multiple Choice (una respuesta)', '["Cantidad de herramientas distintas contratadas", "Horas de formación en IA sin relación con el trabajo", "Reducción de tiempos y errores en procesos clave, con costos controlados", "Número de reportes generados aunque no se usen"]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', now(), 'Reducción de tiempos y errores en procesos clave, con costos controlados', '["Conocimiento", "Productividad", "Inversión"]'::jsonb, 4, 4),

('MRH-C22', 'Cuestionario', 'Conocimiento', '6', '21', 'En la práctica, un “prompt” bien diseñado para IA en RRHH suele incluir:', 'Multiple Choice (una respuesta)', '["Mensajes muy generales sin contexto", "Solo la pregunta final, sin datos del puesto", "Contexto, objetivo, formato deseado y restricciones (por ejemplo, lenguaje inclusivo)", "Frases copiadas de internet sin adaptar"]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', now(), 'Contexto, objetivo, formato deseado y restricciones (por ejemplo, lenguaje inclusivo)', '["Conocimiento"]'::jsonb, 4, 4),

('MRH-C23', 'Cuestionario', 'Conocimiento', '6', '21', 'Si la IA se usa para priorizar vacantes según impacto en el negocio, esto se relaciona con:', 'Multiple Choice (una respuesta)', '["Solo automatización operativa", "Un uso estratégico de IA en la gestión de talento", "Tareas administrativas sin valor", "Exclusivamente análisis de clima"]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', now(), 'Un uso estratégico de IA en la gestión de talento', '["Estrategia", "Conocimiento"]'::jsonb, 4, 4),

('MRH-C24', 'Cuestionario', 'Conocimiento', '6', '21', 'Cuando se hace un pequeño piloto de IA antes de escalarlo, ¿qué elemento es más importante definir?', 'Multiple Choice (una respuesta)', '["El diseño del logo del proyecto", "Un conjunto claro de métricas antes/después para evaluar el piloto", "Solo el presupuesto de licencias", "El horario de almuerzo del equipo"]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', now(), 'Un conjunto claro de métricas antes/después para evaluar el piloto', '["Conocimiento"]'::jsonb, 4, 4),

('MRH-C25', 'Cuestionario', 'Conocimiento', '6', '21', 'Cuando revisas el desempeño de un modelo de IA en procesos de RRHH, ¿qué métrica es clave para evaluar su equidad?', 'Multiple Choice (una respuesta)', '["Solo el tiempo de respuesta", "Diferencias sistemáticas en recomendaciones entre grupos (por ejemplo, género, edad)", "El número de correos enviados", "La cantidad de datos almacenados"]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', now(), 'Diferencias sistemáticas en recomendaciones entre grupos (por ejemplo, género, edad)', '["Conocimiento"]'::jsonb, 4, 5),

('MRH-C26', 'Cuestionario', 'Conocimiento', '6', '21', '¿Cuál es una buena forma de usar IA para apoyar la planificación de talento?', 'Multiple Choice (una respuesta)', '["Dejar que la IA decida promociones automáticamente", "Utilizar IA para analizar tendencias de rotación, desempeño y habilidades, entregando insights a los líderes", "Sustituir por completo las conversaciones de desarrollo con los jefes", "Enviar mensajes genéricos a todos los colaboradores"]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', now(), 'Utilizar IA para analizar tendencias de rotación, desempeño y habilidades, entregando insights a los líderes', '["Estrategia", "Conocimiento", "Aplicación"]'::jsonb, 4, 5),

('MRH-C27', 'Cuestionario', 'Conocimiento', '6', '21', 'Diseñar una “política de uso de IA en RRHH” implica principalmente:', 'Multiple Choice (una respuesta)', '["Explicar cuál es la mejor marca de IA del mercado", "Definir reglas, responsabilidades, límites y principios éticos para el uso de IA", "Obligar a todo el mundo a usar la misma herramienta sin guía", "Centrar la política solo en TI"]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', now(), 'Definir reglas, responsabilidades, límites y principios éticos para el uso de IA', '["Conocimiento", "Aplicación"]'::jsonb, 4, 5),

('MRH-C28', 'Cuestionario', 'Conocimiento', '6', '21', '¿Cuál es un enfoque responsable para escalar un caso de éxito de IA en RRHH a toda la organización?', 'Multiple Choice (una respuesta)', '["Replicarlo en todas las áreas sin ajustes", "Hacer una evaluación de riesgos y beneficios, formar a los equipos y monitorear indicadores clave", "Imponer el uso sin explicar cambios", "Eliminar cualquier revisión humana del proceso"]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', now(), 'Hacer una evaluación de riesgos y beneficios, formar a los equipos y monitorear indicadores clave', '["Conocimiento"]'::jsonb, 4, 5),

('MRH-C29', 'Cuestionario', 'Conocimiento', '6', '21', 'Cuando acompañas a otros compañeros en el uso de IA, un enfoque efectivo de capacitación es:', 'Multiple Choice (una respuesta)', '["Mostrar solo teoría sin ejemplos", "Usar casos reales de su trabajo diario y practicar sobre ellos", "Enviar un manual largo por correo sin seguimiento", "Obligar a todos a aprender solos"]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', now(), 'Usar casos reales de su trabajo diario y practicar sobre ellos', '["Conocimiento", "Aplicación"]'::jsonb, 4, 5),

('MRH-C30', 'Cuestionario', 'Conocimiento', '6', '21', 'En términos de inversión, una señal de madurez en el uso de IA en RRHH es:', 'Multiple Choice (una respuesta)', '["Cambiar de herramienta cada mes", "Mantener una combinación equilibrada entre licencias, formación y tiempo dedicado a mejorar procesos con IA", "Gastar solo en licencias sin formación", "No destinar ningún presupuesto formal"]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', now(), 'Mantener una combinación equilibrada entre licencias, formación y tiempo dedicado a mejorar procesos con IA', '["Conocimiento", "Aplicación", "Inversión"]'::jsonb, 4, 5);
