-- ============================================================================
-- PREGUNTAS PARA MIEMBROS DE OPERACIONES
-- ============================================================================
-- Rol incluido:
--   - Rol ID 19: Miembros de Operaciones (area_id: 4, nivel_id: 4)
-- ============================================================================

-- ============================================================================
-- ROL 19: Miembros de Operaciones
-- ============================================================================

-- ADOPCIÓN - Rol 19
INSERT INTO "public"."preguntas" ("codigo", "section", "bloque", "area_id", "exclusivo_rol_id", "texto", "tipo", "opciones", "locale", "peso", "escala", "scoring", "created_at", "respuesta_correcta", "dimension", "exclusivo_nivel_id", "dificultad") VALUES
('MO-A1', 'Cuestionario', 'Adopción', '4', '19', 'En tu trabajo diario, ¿con qué frecuencia usas alguna herramienta digital que incluya IA (por ejemplo, recomendaciones automáticas, sistemas que sugieren rutas u horarios, asistentes tipo ChatGPT) para apoyar tus tareas de operaciones?', 'Multiple Choice (escala Likert A–E)', '["Nunca", "Rara vez (≤ 1/mes)", "Ocasional (2–3/mes)", "Frecuente (semanal)", "Casi siempre"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', now(), null, '["Aplicación"]'::jsonb, 4, 1),

('MO-A2', 'Cuestionario', 'Adopción', '4', '19', '¿Con qué frecuencia buscas aprender, por tu cuenta, qué es la IA y para qué sirve en operaciones (videos, cursos cortos, materiales internos)?', 'Multiple Choice (escala Likert A–E)', '["Nunca", "Rara vez (≤ 1/mes)", "Ocasional (2–3/mes)", "Frecuente (semanal)", "Casi siempre"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', now(), null, '["Aplicación"]'::jsonb, 4, 1),

('MO-A3', 'Cuestionario', 'Adopción', '4', '19', '¿Con qué frecuencia piensas que la IA podría ayudar a reducir errores o retrabajos en tu área (aunque todavía no la uses)?', 'Multiple Choice (escala Likert A–E)', '["Nunca", "Rara vez (≤ 1/mes)", "Ocasional (2–3/mes)", "Frecuente (semanal)", "Casi siempre"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', now(), null, '["Aplicación"]'::jsonb, 4, 1),

('MO-A4', 'Cuestionario', 'Adopción', '4', '19', '¿Con qué frecuencia comentas con tus compañeros o supervisor ideas sobre cómo la IA podría ayudar en alguna parte del proceso (recepción, almacén, producción, despacho, etc.)?', 'Multiple Choice (escala Likert A–E)', '["Nunca", "Rara vez (≤ 1/mes)", "Ocasional (2–3/mes)", "Frecuente (semanal)", "Casi siempre"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', now(), null, '["Aplicación"]'::jsonb, 4, 1),

('MO-A5', 'Cuestionario', 'Adopción', '4', '19', 'Cuando se menciona una nueva herramienta “inteligente” en la organización, ¿con qué frecuencia te ofreces a participar en pruebas piloto o capacitaciones básicas?', 'Multiple Choice (escala Likert A–E)', '["Nunca", "Rara vez (≤ 1/mes)", "Ocasional (2–3/mes)", "Frecuente (semanal)", "Casi siempre"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', now(), null, '["Aplicación"]'::jsonb, 4, 1),

('MO-A6', 'Cuestionario', 'Adopción', '4', '19', '¿Con qué frecuencia piensas en los posibles riesgos (errores, sesgos, uso de datos sensibles) cuando escuchas hablar de IA aplicada a tu área?', 'Multiple Choice (escala Likert A–E)', '["Nunca", "Rara vez (≤ 1/mes)", "Ocasional (2–3/mes)", "Frecuente (semanal)", "Casi siempre"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', now(), null, '["Aplicación", "Estrategia"]'::jsonb, 4, 1),

('MO-A7', 'Cuestionario', 'Adopción', '4', '19', '¿Con qué frecuencia usas IA generativa (como ChatGPT) para mejorar la redacción de correos, reportes de turno o instrucciones para el equipo?', 'Multiple Choice (escala Likert A–E)', '["Nunca", "Rara vez (≤ 1/mes)", "Ocasional (2–3/mes)", "Frecuente (semanal)", "Casi siempre"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', now(), null, '["Aplicación", "Productividad"]'::jsonb, 4, 2),

('MO-A8', 'Cuestionario', 'Adopción', '4', '19', '¿Con qué frecuencia pruebas, por iniciativa propia, nuevas funciones “inteligentes” en sistemas que ya usas (ERP, WMS, sistemas de monitoreo) cuando están disponibles?', 'Multiple Choice (escala Likert A–E)', '["Nunca", "Rara vez (≤ 1/mes)", "Ocasional (2–3/mes)", "Frecuente (semanal)", "Casi siempre"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', now(), null, '["Aplicación"]'::jsonb, 4, 2),

('MO-A9', 'Cuestionario', 'Adopción', '4', '19', '¿Con qué frecuencia revisas si las recomendaciones de IA (por ejemplo, rutas, secuencias de órdenes) realmente mejoran tiempos, costos o calidad?', 'Multiple Choice (escala Likert A–E)', '["Nunca", "Rara vez (≤ 1/mes)", "Ocasional (2–3/mes)", "Frecuente (semanal)", "Casi siempre"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', now(), null, '["Inversión", "Productividad"]'::jsonb, 4, 2),

('MO-A10', 'Cuestionario', 'Adopción', '4', '19', '¿Con qué frecuencia compartes con tu equipo ejemplos concretos de cómo una herramienta de IA te ayudó en una tarea específica?', 'Multiple Choice (escala Likert A–E)', '["Nunca", "Rara vez (≤ 1/mes)", "Ocasional (2–3/mes)", "Frecuente (semanal)", "Casi siempre"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', now(), null, '["Aplicación"]'::jsonb, 4, 2),

('MO-A11', 'Cuestionario', 'Adopción', '4', '19', 'Cuando usas IA, ¿con qué frecuencia verificas que no estás compartiendo datos sensibles (personas, precios, contratos) sin autorización?', 'Multiple Choice (escala Likert A–E)', '["Nunca", "Rara vez (≤ 1/mes)", "Ocasional (2–3/mes)", "Frecuente (semanal)", "Casi siempre"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', now(), null, '["Aplicación"]'::jsonb, 4, 2),

('MO-A12', 'Cuestionario', 'Adopción', '4', '19', '¿Con qué frecuencia dedicas tiempo (aunque sea corto) a aprender trucos o buenas prácticas de IA que te recomiendan compañeros o la empresa?', 'Multiple Choice (escala Likert A–E)', '["Nunca", "Rara vez (≤ 1/mes)", "Ocasional (2–3/mes)", "Frecuente (semanal)", "Casi siempre"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', now(), null, '["Productividad"]'::jsonb, 4, 2),

('MO-A13', 'Cuestionario', 'Adopción', '4', '19', '¿Con qué frecuencia revisas dashboards o reportes que usan IA (por ejemplo, indicadores de producción, mantenimiento, inventarios) antes de tu turno o durante él?', 'Multiple Choice (escala Likert A–E)', '["Nunca", "Rara vez (≤ 1/mes)", "Ocasional (2–3/mes)", "Frecuente (semanal)", "Casi siempre"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', now(), null, '["Productividad"]'::jsonb, 4, 3),

('MO-A14', 'Cuestionario', 'Adopción', '4', '19', '¿Con qué frecuencia ajustas tus decisiones (prioridad de tareas, rutas, órdenes) con base en recomendaciones de IA, combinándolas con tu experiencia?', 'Multiple Choice (escala Likert A–E)', '["Nunca", "Rara vez (≤ 1/mes)", "Ocasional (2–3/mes)", "Frecuente (semanal)", "Casi siempre"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', now(), null, '["Aplicación"]'::jsonb, 4, 3),

('MO-A15', 'Cuestionario', 'Adopción', '4', '19', '¿Con qué frecuencia propones mejoras en la captura de datos (campos, formatos, tiempos) para que la IA pueda dar mejores recomendaciones?', 'Multiple Choice (escala Likert A–E)', '["Nunca", "Rara vez (≤ 1/mes)", "Ocasional (2–3/mes)", "Frecuente (semanal)", "Casi siempre"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', now(), null, '["Aplicación", "Productividad"]'::jsonb, 4, 3),

('MO-A16', 'Cuestionario', 'Adopción', '4', '19', '¿Con qué frecuencia participas en reuniones breves (huddles, juntas de arranque) donde comentas hallazgos de IA y los comparas con lo observado en el piso?', 'Multiple Choice (escala Likert A–E)', '["Nunca", "Rara vez (≤ 1/mes)", "Ocasional (2–3/mes)", "Frecuente (semanal)", "Casi siempre"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', now(), null, '["Aplicación"]'::jsonb, 4, 3),

('MO-A17', 'Cuestionario', 'Adopción', '4', '19', 'Cuando detectas que la IA se equivoca por un dato mal capturado, ¿con qué frecuencia reportas el problema para corregirlo?', 'Multiple Choice (escala Likert A–E)', '["Nunca", "Rara vez (≤ 1/mes)", "Ocasional (2–3/mes)", "Frecuente (semanal)", "Casi siempre"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', now(), null, '["Aplicación"]'::jsonb, 4, 3),

('MO-A18', 'Cuestionario', 'Adopción', '4', '19', '¿Con qué frecuencia ayudas a compañeros que tienen menos experiencia con IA a interpretar un reporte o sugerencia automatizada?', 'Multiple Choice (escala Likert A–E)', '["Nunca", "Rara vez (≤ 1/mes)", "Ocasional (2–3/mes)", "Frecuente (semanal)", "Casi siempre"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', now(), null, '["Aplicación"]'::jsonb, 4, 3),

('MO-A19', 'Cuestionario', 'Adopción', '4', '19', '¿Con qué frecuencia usas resultados de modelos de IA (predicción de demanda, rutas, fallas) para proponer ajustes concretos al plan de producción o logística?', 'Multiple Choice (escala Likert A–E)', '["Nunca", "Rara vez (≤ 1/mes)", "Ocasional (2–3/mes)", "Frecuente (semanal)", "Casi siempre"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', now(), null, '["Productividad"]'::jsonb, 4, 4),

('MO-A20', 'Cuestionario', 'Adopción', '4', '19', '¿Con qué frecuencia impulsas pequeñas pruebas piloto (en una línea, ruta o turno) para validar ideas basadas en IA antes de escalarlas?', 'Multiple Choice (escala Likert A–E)', '["Nunca", "Rara vez (≤ 1/mes)", "Ocasional (2–3/mes)", "Frecuente (semanal)", "Casi siempre"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', now(), null, '["Aplicación"]'::jsonb, 4, 4),

('MO-A21', 'Cuestionario', 'Adopción', '4', '19', '¿Con qué frecuencia documentas y compartes con tu jefe casos donde la IA no funcionó bien y qué ajustes se hicieron?', 'Multiple Choice (escala Likert A–E)', '["Nunca", "Rara vez (≤ 1/mes)", "Ocasional (2–3/mes)", "Frecuente (semanal)", "Casi siempre"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', now(), null, '["Aplicación"]'::jsonb, 4, 4),

('MO-A22', 'Cuestionario', 'Adopción', '4', '19', '¿Con qué frecuencia colaboras con otras áreas (compras, ventas, planificación) para alinear el uso de IA en toda la cadena de operaciones?', 'Multiple Choice (escala Likert A–E)', '["Nunca", "Rara vez (≤ 1/mes)", "Ocasional (2–3/mes)", "Frecuente (semanal)", "Casi siempre"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', now(), null, '["Aplicación", "Estrategia"]'::jsonb, 4, 4),

('MO-A23', 'Cuestionario', 'Adopción', '4', '19', '¿Con qué frecuencia propones mejoras específicas en los datos que se capturan (campos nuevos, mejor calidad de registros) para que los modelos de IA sean más robustos?', 'Multiple Choice (escala Likert A–E)', '["Nunca", "Rara vez (≤ 1/mes)", "Ocasional (2–3/mes)", "Frecuente (semanal)", "Casi siempre"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', now(), null, '["Aplicación"]'::jsonb, 4, 4),

('MO-A24', 'Cuestionario', 'Adopción', '4', '19', '¿Con qué frecuencia utilizas IA para analizar incidentes de seguridad o calidad, buscando patrones que permitan prevenir futuros eventos?', 'Multiple Choice (escala Likert A–E)', '["Nunca", "Rara vez (≤ 1/mes)", "Ocasional (2–3/mes)", "Frecuente (semanal)", "Casi siempre"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', now(), null, '["Aplicación", "Estrategia"]'::jsonb, 4, 4),

('MO-A25', 'Cuestionario', 'Adopción', '4', '19', '¿Con qué frecuencia lideras o co-lideras iniciativas para identificar nuevos casos de uso de IA en tu área (p. ej., nuevas oportunidades de reducción de tiempos, mermas o riesgos)?', 'Multiple Choice (escala Likert A–E)', '["Nunca", "Rara vez (≤ 1/mes)", "Ocasional (2–3/mes)", "Frecuente (semanal)", "Casi siempre"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', now(), null, '["Productividad", "Aplicación", "Estrategia"]'::jsonb, 4, 5),

('MO-A26', 'Cuestionario', 'Adopción', '4', '19', '¿Con qué frecuencia facilitas sesiones de entrenamiento o demostración para que tus compañeros aprendan a usar herramientas de IA aplicadas a su trabajo diario?', 'Multiple Choice (escala Likert A–E)', '["Nunca", "Rara vez (≤ 1/mes)", "Ocasional (2–3/mes)", "Frecuente (semanal)", "Casi siempre"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', now(), null, '["Aplicación"]'::jsonb, 4, 5),

('MO-A27', 'Cuestionario', 'Adopción', '4', '19', '¿Con qué frecuencia trabajas con líderes de área para traducir resultados de IA (modelos, dashboards) en acciones concretas en el piso (cambios en secuencias, roles, turnos)?', 'Multiple Choice (escala Likert A–E)', '["Nunca", "Rara vez (≤ 1/mes)", "Ocasional (2–3/mes)", "Frecuente (semanal)", "Casi siempre"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', now(), null, '["Productividad"]'::jsonb, 4, 5),

('MO-A28', 'Cuestionario', 'Adopción', '4', '19', '¿Con qué frecuencia revisas y discutes con TI/Data los límites de los modelos (qué pueden y qué no pueden hacer) para comunicarlo de forma clara al equipo?', 'Multiple Choice (escala Likert A–E)', '["Nunca", "Rara vez (≤ 1/mes)", "Ocasional (2–3/mes)", "Frecuente (semanal)", "Casi siempre"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', now(), null, '["Aplicación"]'::jsonb, 4, 5),

('MO-A29', 'Cuestionario', 'Adopción', '4', '19', '¿Con qué frecuencia ayudas a priorizar, junto con tus líderes, en qué proyectos de IA vale más la pena invertir tiempo de tu equipo?', 'Multiple Choice (escala Likert A–E)', '["Nunca", "Rara vez (≤ 1/mes)", "Ocasional (2–3/mes)", "Frecuente (semanal)", "Casi siempre"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', now(), null, '["Productividad", "Aplicación", "Estrategia"]'::jsonb, 4, 5),

('MO-A30', 'Cuestionario', 'Adopción', '4', '19', '¿Con qué frecuencia capturas y compartes historias de éxito (antes/después) donde la IA generó mejoras claras en seguridad, calidad, tiempos o costo en operaciones?', 'Multiple Choice (escala Likert A–E)', '["Nunca", "Rara vez (≤ 1/mes)", "Ocasional (2–3/mes)", "Frecuente (semanal)", "Casi siempre"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', now(), null, '["Estrategia", "Inversión", "Productividad"]'::jsonb, 4, 5);

-- CONOCIMIENTO - Rol 19
INSERT INTO "public"."preguntas" ("codigo", "section", "bloque", "area_id", "exclusivo_rol_id", "texto", "tipo", "opciones", "locale", "peso", "escala", "scoring", "created_at", "respuesta_correcta", "dimension", "exclusivo_nivel_id", "dificultad") VALUES
('MO-C1', 'Cuestionario', 'Conocimiento', '4', '19', 'En tu trabajo, ¿cuál de las siguientes opciones describe mejor a la inteligencia artificial (IA)?', 'Multiple Choice (una respuesta)', '["Un tipo de archivo de Excel con muchas fórmulas", "Un robot físico que siempre reemplaza a las personas", "Sistemas que usan datos y algoritmos para tomar decisiones o hacer tareas de forma automática", "Cualquier máquina que tenga una pantalla táctil"]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', now(), 'Sistemas que usan datos y algoritmos para tomar decisiones o hacer tareas de forma automática', '["Conocimiento"]'::jsonb, 4, 1),

('MO-C2', 'Cuestionario', 'Conocimiento', '4', '19', '¿Cuál de estos ejemplos es un uso sencillo de IA en operaciones?', 'Multiple Choice (una respuesta)', '["Escribir a mano los reportes de turno en una libreta", "Un sistema que sugiere la mejor ruta de reparto según tráfico y distancia", "Imprimir las órdenes de trabajo en papel", "Guardar archivos en una carpeta compartida"]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', now(), 'Un sistema que sugiere la mejor ruta de reparto según tráfico y distancia', '["Conocimiento", "Aplicación"]'::jsonb, 4, 1),

('MO-C3', 'Cuestionario', 'Conocimiento', '4', '19', '¿Qué beneficio directo podría traer la IA a tu trabajo diario en operaciones?', 'Multiple Choice (una respuesta)', '["Hacer que todos los procesos sean más lentos", "Aumentar la cantidad de papeleo manual", "Reducir errores y retrabajos al detectar problemas antes", "Evitar que el equipo se comunique"]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', now(), 'Reducir errores y retrabajos al detectar problemas antes', '["Conocimiento"]'::jsonb, 4, 1),

('MO-C4', 'Cuestionario', 'Conocimiento', '4', '19', '¿Cuál de estas situaciones representa un riesgo al usar IA?', 'Multiple Choice (una respuesta)', '["Revisar críticamente las sugerencias y compararlas con tu experiencia", "Usar la IA como apoyo, pero siempre validar con datos reales", "Compartir información sensible de clientes o proveedores en una herramienta abierta sin autorización", "Preguntar a la IA cómo resumir un instructivo público"]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', now(), 'Compartir información sensible de clientes o proveedores en una herramienta abierta sin autorización', '["Conocimiento", "Estrategia"]'::jsonb, 4, 1),

('MO-C5', 'Cuestionario', 'Conocimiento', '4', '19', 'Si tu supervisor te pide “probar una herramienta de IA para reportes de turno”, ¿qué actitud es más adecuada?', 'Multiple Choice (una respuesta)', '["Negarse sin conocerla, porque “esas cosas son para TI”", "Probarla con mente abierta, respetando los procedimientos y reportando hallazgos", "Usarla para todo sin seguir procedimientos establecidos", "Compartir tu usuario y contraseña con compañeros para que también prueben"]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', now(), 'Probarla con mente abierta, respetando los procedimientos y reportando hallazgos', '["Conocimiento", "Productividad"]'::jsonb, 4, 1),

('MO-C6', 'Cuestionario', 'Conocimiento', '4', '19', 'Respecto a la inversión de tiempo en aprender IA, ¿qué enunciado es más correcto para un miembro de operaciones?', 'Multiple Choice (una respuesta)', '["No tiene sentido aprender IA; nunca se usará en operaciones", "Solo deben aprender IA los directores y gerentes", "Vale la pena invertir algo de tiempo en entender usos básicos que mejoren mi trabajo", "Solo el área de sistemas debe saber de IA"]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', now(), 'Vale la pena invertir algo de tiempo en entender usos básicos que mejoren mi trabajo', '["Inversión", "Conocimiento", "Productividad"]'::jsonb, 4, 1),

('MO-C7', 'Cuestionario', 'Conocimiento', '4', '19', '¿Cuál es un uso básico y apropiado de IA generativa para un miembro de operaciones?', 'Multiple Choice (una respuesta)', '["Inventar datos de producción cuando faltan registros", "Redactar un correo más claro para informar un retraso en una entrega", "Cambiar las fechas de entrega en el sistema sin avisar a nadie", "Firmar digitalmente un documento en nombre de otra persona"]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', now(), 'Redactar un correo más claro para informar un retraso en una entrega', '["Conocimiento", "Aplicación"]'::jsonb, 4, 2),

('MO-C8', 'Cuestionario', 'Conocimiento', '4', '19', 'Un sistema de IA que analiza lecturas de sensores en una máquina para avisar que “pronto puede fallar” se llama:', 'Multiple Choice (una respuesta)', '["IA creativa", "Mantenimiento preventivo tradicional", "Mantenimiento predictivo", "Análisis manual"]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', now(), 'Mantenimiento predictivo', '["Conocimiento"]'::jsonb, 4, 2),

('MO-C9', 'Cuestionario', 'Conocimiento', '4', '19', 'Si la IA te sugiere una ruta de reparto más corta pero sabes que hay una calle cerrada, ¿qué deberías hacer?', 'Multiple Choice (una respuesta)', '["Seguir la sugerencia de IA sin pensar", "Ignorar siempre a la IA", "Combinar tu conocimiento del terreno con la sugerencia y ajustar la ruta", "Apagar el sistema para que no vuelva a sugerir rutas"]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', now(), 'Combinar tu conocimiento del terreno con la sugerencia y ajustar la ruta', '["Conocimiento"]'::jsonb, 4, 2),

('MO-C10', 'Cuestionario', 'Conocimiento', '4', '19', '¿Cuál de estas prácticas es más segura al usar IA generativa (ChatGPT u otras) con información de la empresa?', 'Multiple Choice (una respuesta)', '["Copiar y pegar contratos o datos de clientes sin permiso", "Solo compartir información que ya es pública o está autorizada para uso externo", "Subir fotos de credenciales de empleados", "Compartir listas completas de precios confidenciales"]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', now(), 'Solo compartir información que ya es pública o está autorizada para uso externo', '["Conocimiento", "Aplicación"]'::jsonb, 4, 2),

('MO-C11', 'Cuestionario', 'Conocimiento', '4', '19', 'Desde el punto de vista de la estrategia de la empresa, ¿por qué es importante que miembros de operaciones entiendan usos básicos de IA?', 'Multiple Choice (una respuesta)', '["Porque así pueden hacer el trabajo de los directores", "Para contribuir a mejoras en seguridad, calidad y servicio que afectan resultados globales", "Solo para poder reemplazar a otros compañeros", "Para eliminar todos los procedimientos escritos"]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', now(), 'Para contribuir a mejoras en seguridad, calidad y servicio que afectan resultados globales', '["Aplicación", "Conocimiento", "Estrategia"]'::jsonb, 4, 2),

('MO-C12', 'Cuestionario', 'Conocimiento', '4', '19', 'Si la empresa invierte tiempo en capacitarte en IA, ¿qué se espera de ti?', 'Multiple Choice (una respuesta)', '["No aplicar nada “para no complicarse”", "Aplicar lo aprendido cuando tenga sentido y compartir dudas y mejoras observadas", "Guardar lo aprendido solo para ti", "Usar IA aunque vaya en contra de normas de seguridad"]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', now(), 'Aplicar lo aprendido cuando tenga sentido y compartir dudas y mejoras observadas', '["Conocimiento", "Productividad"]'::jsonb, 4, 2),

('MO-C13', 'Cuestionario', 'Conocimiento', '4', '19', 'Cuando un sistema de IA sugiere una secuencia de producción que reduce tiempos de cambio de máquina, eso impacta principalmente en:', 'Multiple Choice (una respuesta)', '["Solo en la apariencia de los reportes", "Productividad y uso del tiempo de máquina", "Únicamente en la rotación de personal", "Solo en la decoración del almacén"]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', now(), 'Productividad y uso del tiempo de máquina', '["Conocimiento", "Productividad"]'::jsonb, 4, 3),

('MO-C14', 'Cuestionario', 'Conocimiento', '4', '19', 'Si trabajas en almacén, ¿qué dato es clave para que un algoritmo de IA optimice la ubicación de productos?', 'Multiple Choice (una respuesta)', '["Color del empaque", "Nombre del supervisor", "Frecuencia de salida de cada producto y volumen", "Fecha de cumpleaños de los operadores"]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', now(), 'Frecuencia de salida de cada producto y volumen', '["Conocimiento"]'::jsonb, 4, 3),

('MO-C15', 'Cuestionario', 'Conocimiento', '4', '19', 'Un riesgo de depender demasiado de IA en decisiones operativas es:', 'Multiple Choice (una respuesta)', '["Perder capacidad de cuestionar recomendaciones que no tienen sentido en campo", "Reducir errores humanos", "Mejorar tiempos de respuesta", "Facilitar el análisis de grandes volúmenes de datos"]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', now(), 'Perder capacidad de cuestionar recomendaciones que no tienen sentido en campo', '["Conocimiento", "Estrategia"]'::jsonb, 4, 3),

('MO-C16', 'Cuestionario', 'Conocimiento', '4', '19', 'Cuando colaboras con planificación o ingeniería usando resultados de IA, ¿qué es lo más importante?', 'Multiple Choice (una respuesta)', '["Defender la IA aunque el dato real diga lo contrario", "Compartir evidencia de campo (fotos, tiempos, incidencias) para validar los modelos", "Ocultar información que contradiga al modelo", "Solo aceptar lo que se “ve bonito” en el dashboard"]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', now(), 'Compartir evidencia de campo (fotos, tiempos, incidencias) para validar los modelos', '["Productividad", "Conocimiento", "Estrategia"]'::jsonb, 4, 3),

('MO-C17', 'Cuestionario', 'Conocimiento', '4', '19', 'Respecto a la inversión de tiempo en ajustar datos (limpiar capturas, revisar incidencias) para IA:', 'Multiple Choice (una respuesta)', '["Es una pérdida de tiempo; la IA arregla todo sola", "Es clave, porque si los datos están mal, las recomendaciones serán poco confiables", "Solo es importante para directores", "Nunca se debe corregir datos históricos"]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', now(), 'Es clave, porque si los datos están mal, las recomendaciones serán poco confiables', '["Inversión", "Aplicación", "Conocimiento", "Productividad"]'::jsonb, 4, 3),

('MO-C18', 'Cuestionario', 'Conocimiento', '4', '19', 'Si la empresa quiere usar IA para reducir desperdicio de material, ¿qué aporte directo puede hacer un miembro de operaciones?', 'Multiple Choice (una respuesta)', '["No registrar desperdicios para que “no se vean”", "Registrar con precisión mermas y causas de rechazo en el sistema", "Apagar sensores para que no haya datos", "Cambiar indicadores sin avisar"]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', now(), 'Registrar con precisión mermas y causas de rechazo en el sistema', '["Conocimiento"]'::jsonb, 4, 3),

('MO-C19', 'Cuestionario', 'Conocimiento', '4', '19', 'Si un modelo de IA para mantenimiento predictivo reduce paros imprevistos en un 20%, ¿qué impacto clave tiene en operaciones?', 'Multiple Choice (una respuesta)', '["Aumenta tiempos muertos", "Reduce disponibilidad de equipos", "Mejora disponibilidad y productividad, y reduce costos de falla", "Solo mejora la estética del tablero de control"]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', now(), 'Mejora disponibilidad y productividad, y reduce costos de falla', '["Conocimiento"]'::jsonb, 4, 4),

('MO-C20', 'Cuestionario', 'Conocimiento', '4', '19', 'Para evaluar si un modelo de IA que sugiere rutas está funcionando bien, ¿qué indicador es más relevante?', 'Multiple Choice (una respuesta)', '["Número de colores en el mapa", "Tiempos promedio de entrega y retrasos", "Número de usuarios conectados al sistema", "Cantidad de correos enviados"]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', now(), 'Tiempos promedio de entrega y retrasos', '["Conocimiento"]'::jsonb, 4, 4),

('MO-C21', 'Cuestionario', 'Conocimiento', '4', '19', 'Un riesgo ético de automatizar decisiones de asignación de turnos con IA sin supervisión humana es:', 'Multiple Choice (una respuesta)', '["Que todos tengan siempre el mismo turno ideal", "Que se generen patrones injustos (siempre noches para las mismas personas) sin justificación clara", "Que se reduzcan tiempos de programación", "Que mejore la transparencia en la asignación"]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', now(), 'Que se generen patrones injustos (siempre noches para las mismas personas) sin justificación clara', '["Estrategia", "Conocimiento", "Productividad"]'::jsonb, 4, 4),

('MO-C22', 'Cuestionario', 'Conocimiento', '4', '19', 'Si quieres colaborar con TI para mejorar un modelo de IA que pronostica demanda, ¿qué tipo de información desde operaciones agrega más valor?', 'Multiple Choice (una respuesta)', '["Rumores sin datos sobre clientes", "Datos estructurados de órdenes reales, tiempos de surtido y restricciones de capacidad", "Opiniones sin ejemplos concretos", "Fotos de celebraciones internas"]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', now(), 'Datos estructurados de órdenes reales, tiempos de surtido y restricciones de capacidad', '["Conocimiento", "Aplicación"]'::jsonb, 4, 4),

('MO-C23', 'Cuestionario', 'Conocimiento', '4', '19', 'Desde el punto de vista de inversión, ¿qué criterio básico ayuda a priorizar casos de uso de IA en operaciones?', 'Multiple Choice (una respuesta)', '["Elegir lo que se vea más sofisticado aunque tenga poco impacto", "Priorizar casos con alto impacto en seguridad, calidad o costo y esfuerzo razonable de implementación", "Solo proyectos que no requieran cambios en el proceso", "Cualquier idea que proponga alguien de fuera del área"]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', now(), 'Priorizar casos con alto impacto en seguridad, calidad o costo y esfuerzo razonable de implementación', '["Inversión", "Aplicación", "Conocimiento", "Estrategia"]'::jsonb, 4, 4),

('MO-C24', 'Cuestionario', 'Conocimiento', '4', '19', '¿Cuál es una forma responsable de usar IA generativa para estandarizar instrucciones de trabajo?', 'Multiple Choice (una respuesta)', '["Dejar que la IA invente los procedimientos sin validación", "Usar IA para generar un primer borrador y luego validarlo con expertos de seguridad y calidad", "Ignorar completamente la IA para procedimientos", "Pedir a la IA que autorice cambios sin revisar en planta"]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', now(), 'Usar IA para generar un primer borrador y luego validarlo con expertos de seguridad y calidad', '["Conocimiento"]'::jsonb, 4, 4),

('MO-C25', 'Cuestionario', 'Conocimiento', '4', '19', 'Como referente de IA en operaciones, ¿qué enfoque es más adecuado para escalar un caso de uso exitoso?', 'Multiple Choice (una respuesta)', '["Imponer el cambio en todas las áreas sin explicar nada", "Documentar resultados, riesgos y lecciones aprendidas, y luego escalar con apoyo de líderes y usuarios clave", "Solo comentarlo informalmente en pasillos", "Mantener el caso en secreto para destacar individualmente"]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', now(), 'Documentar resultados, riesgos y lecciones aprendidas, y luego escalar con apoyo de líderes y usuarios clave', '["Conocimiento", "Aplicación"]'::jsonb, 4, 5),

('MO-C26', 'Cuestionario', 'Conocimiento', '4', '19', 'Si detectas que un modelo de IA genera recomendaciones que perjudican sistemáticamente a cierto grupo de colaboradores (por ejemplo, siempre los turnos más difíciles), eso se relaciona con:', 'Multiple Choice (una respuesta)', '["Un comportamiento normal de IA", "Un posible sesgo en los datos o en el modelo que debe revisarse", "Una mejora inevitable", "Un tema irrelevante"]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', now(), 'Un posible sesgo en los datos o en el modelo que debe revisarse', '["Conocimiento"]'::jsonb, 4, 5),

('MO-C27', 'Cuestionario', 'Conocimiento', '4', '19', 'En términos de inversión de tiempo y recursos, ¿cómo puedes ayudar a priorizar iniciativas de IA desde tu rol?', 'Multiple Choice (una respuesta)', '["Proponiendo muchos proyectos sin estimar impacto", "Identificando problemas concretos (tiempos muertos, mermas, accidentes) y estimando beneficios aproximados de resolverlos", "Pidiendo IA para todo aunque no haga falta", "Solo apoyando proyectos de moda"]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', now(), 'Identificando problemas concretos (tiempos muertos, mermas, accidentes) y estimando beneficios aproximados de resolverlos', '["Inversión", "Productividad", "Conocimiento", "Estrategia"]'::jsonb, 4, 5),

('MO-C28', 'Cuestionario', 'Conocimiento', '4', '19', '¿Cuál es el rol de un referente de IA respecto a sus compañeros en el piso de operaciones?', 'Multiple Choice (una respuesta)', '["Ser el único que sabe usar IA para mantener ventaja", "Compartir buenas prácticas, acompañar en el uso y canalizar dudas o riesgos hacia las áreas responsables", "Sustituir al jefe en todas las decisiones", "Revisar únicamente problemas de TI"]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', now(), 'Compartir buenas prácticas, acompañar en el uso y canalizar dudas o riesgos hacia las áreas responsables', '["Conocimiento"]'::jsonb, 4, 5),

('MO-C29', 'Cuestionario', 'Conocimiento', '4', '19', 'Si colaboras con TI o Data en el diseño de un modelo, ¿qué aportas desde operaciones que es difícil que vean desde oficina?', 'Multiple Choice (una respuesta)', '["Conocimiento profundo de la realidad del piso, excepciones y restricciones prácticas", "Diseño del algoritmo matemático completo", "Presupuesto global de la empresa", "Decisiones legales sobre datos personales"]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', now(), 'Conocimiento profundo de la realidad del piso, excepciones y restricciones prácticas', '["Conocimiento"]'::jsonb, 4, 5),

('MO-C30', 'Cuestionario', 'Conocimiento', '4', '19', 'Respecto a la comunicación de riesgos y límites de la IA hacia el equipo, ¿qué es más adecuado?', 'Multiple Choice (una respuesta)', '["Prometer que la IA nunca se equivoca", "Explicar ejemplos concretos de errores pasados y cómo mitigarlos", "Evitar hablar de riesgos para no generar dudas", "Dejar que cada quien se entere por su cuenta"]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', now(), 'Explicar ejemplos concretos de errores pasados y cómo mitigarlos', '["Aplicación", "Conocimiento", "Estrategia"]'::jsonb, 4, 5);
