-- ============================================================================
-- PREGUNTAS PARA DIRECCIÓN DE RRHH
-- ============================================================================
-- Rol incluido:
--   - Rol ID 14: Dirección de RRHH (area_id: 6, nivel_id: 2)
-- ============================================================================

-- ============================================================================
-- ROL 14: Dirección de RRHH
-- ============================================================================

-- ADOPCIÓN - Rol 14
INSERT INTO "public"."preguntas" ("codigo", "section", "bloque", "area_id", "exclusivo_rol_id", "texto", "tipo", "opciones", "locale", "peso", "escala", "scoring", "created_at", "respuesta_correcta", "dimension", "exclusivo_nivel_id", "dificultad") VALUES
('DRH-A1', 'Cuestionario', 'Adopción', '6', '14', 'En tus procesos de reclutamiento, ¿con qué frecuencia revisas si el ATS o bolsas de trabajo que usas tienen funciones de IA (filtros inteligentes, ranking automático de candidatos)?', 'Multiple Choice (escala Likert A–E)', '["Nunca", "Rara vez (≤ 1/mes)", "Ocasional (2–3/mes)", "Frecuente (semanal)", "Casi siempre/Siempre"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', now(), null, '["Aplicación"]'::jsonb, 2, 1),

('DRH-A2', 'Cuestionario', 'Adopción', '6', '14', '¿Con qué frecuencia recurres a herramientas de IA (por ejemplo asistentes de escritura) para preparar comunicados, descripciones de puestos o correos masivos de RRHH?', 'Multiple Choice (escala Likert A–E)', '["Nunca", "Rara vez (≤ 1/mes)", "Ocasional (2–3/mes)", "Frecuente (semanal)", "Casi siempre/Siempre"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', now(), null, '["Aplicación"]'::jsonb, 2, 1),

('DRH-A3', 'Cuestionario', 'Adopción', '6', '14', 'Al discutir iniciativas de RRHH con dirección general, ¿con qué frecuencia mencionas explícitamente oportunidades de usar IA (aunque aún no las implementes)?', 'Multiple Choice (escala Likert A–E)', '["Nunca", "Rara vez (≤ 1/mes)", "Ocasional (2–3/mes)", "Frecuente (semanal)", "Casi siempre/Siempre"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', now(), null, '["Estrategia"]'::jsonb, 2, 1),

('DRH-A4', 'Cuestionario', 'Adopción', '6', '14', '¿Con qué frecuencia revisas contenidos (artículos, webinars) sobre IA aplicada a RRHH para mantenerte actualizado/a?', 'Multiple Choice (escala Likert A–E)', '["Nunca", "Rara vez (≤ 1/mes)", "Ocasional (2–3/mes)", "Frecuente (semanal)", "Casi siempre/Siempre"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', now(), null, '["Aplicación"]'::jsonb, 2, 1),

('DRH-A5', 'Cuestionario', 'Adopción', '6', '14', 'Cuando evalúas el presupuesto anual de RRHH, ¿con qué frecuencia contemplas, aunque sea de forma exploratoria, una partida para pilotos de IA?', 'Multiple Choice (escala Likert A–E)', '["Nunca", "Rara vez (≤ 1/mes)", "Ocasional (2–3/mes)", "Frecuente (semanal)", "Casi siempre/Siempre"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', now(), null, '["Inversión"]'::jsonb, 2, 1),

('DRH-A6', 'Cuestionario', 'Adopción', '6', '14', '¿Con qué frecuencia conversas con tu equipo sobre posibles riesgos éticos de la IA (sesgos, privacidad de datos) aunque aún no tengan proyectos activos?', 'Multiple Choice (escala Likert A–E)', '["Nunca", "Rara vez (≤ 1/mes)", "Ocasional (2–3/mes)", "Frecuente (semanal)", "Casi siempre/Siempre"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', now(), null, '["Aplicación", "Estrategia"]'::jsonb, 2, 1),

('DRH-A7', 'Cuestionario', 'Adopción', '6', '14', 'En tus pilotos actuales, ¿con qué frecuencia defines indicadores específicos (tiempo de cobertura, calidad de contratación, satisfacción de candidatos) antes de iniciar el piloto de IA?', 'Multiple Choice (escala Likert A–E)', '["Nunca", "Rara vez (≤ 1/mes)", "Ocasional (2–3/mes)", "Frecuente (semanal)", "Casi siempre/Siempre"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', now(), null, '["Productividad", "Aplicación"]'::jsonb, 2, 2),

('DRH-A8', 'Cuestionario', 'Adopción', '6', '14', '¿Con qué frecuencia revisas con TI y Legal los riesgos de privacidad de datos en las pruebas de IA que realizas en RRHH?', 'Multiple Choice (escala Likert A–E)', '["Nunca", "Rara vez (≤ 1/mes)", "Ocasional (2–3/mes)", "Frecuente (semanal)", "Casi siempre/Siempre"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', now(), null, '["Aplicación", "Estrategia"]'::jsonb, 2, 2),

('DRH-A9', 'Cuestionario', 'Adopción', '6', '14', '¿Con qué frecuencia capacitas al equipo de RRHH para usar correctamente las herramientas de IA piloto (no solo darles acceso)?', 'Multiple Choice (escala Likert A–E)', '["Nunca", "Rara vez (≤ 1/mes)", "Ocasional (2–3/mes)", "Frecuente (semanal)", "Casi siempre/Siempre"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', now(), null, '["Aplicación"]'::jsonb, 2, 2),

('DRH-A10', 'Cuestionario', 'Adopción', '6', '14', '¿Con qué frecuencia utilizas IA para priorizar CV o candidatos en al menos un tipo de posición (por ejemplo, administrativos o comerciales)?', 'Multiple Choice (escala Likert A–E)', '["Nunca", "Rara vez (≤ 1/mes)", "Ocasional (2–3/mes)", "Frecuente (semanal)", "Casi siempre/Siempre"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', now(), null, '["Aplicación", "Estrategia"]'::jsonb, 2, 2),

('DRH-A11', 'Cuestionario', 'Adopción', '6', '14', '¿Con qué frecuencia compartes con tu comité de dirección los resultados (aunque sean preliminares) de los pilotos de IA en RRHH?', 'Multiple Choice (escala Likert A–E)', '["Nunca", "Rara vez (≤ 1/mes)", "Ocasional (2–3/mes)", "Frecuente (semanal)", "Casi siempre/Siempre"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', now(), null, '["Productividad"]'::jsonb, 2, 2),

('DRH-A12', 'Cuestionario', 'Adopción', '6', '14', '¿Con qué frecuencia involucras a líderes de negocio en la definición de qué problema de personas intentan resolver con IA (y no solo en la herramienta a comprar)?', 'Multiple Choice (escala Likert A–E)', '["Nunca", "Rara vez (≤ 1/mes)", "Ocasional (2–3/mes)", "Frecuente (semanal)", "Casi siempre/Siempre"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', now(), null, '["Aplicación"]'::jsonb, 2, 2),

('DRH-A13', 'Cuestionario', 'Adopción', '6', '14', '¿Con qué frecuencia revisas reportes o dashboards que incorporan modelos predictivos de personas (rotación, desempeño, riesgo de fuga de talento crítico) para tomar decisiones?', 'Multiple Choice (escala Likert A–E)', '["Nunca", "Rara vez (≤ 1/mes)", "Ocasional (2–3/mes)", "Frecuente (semanal)", "Casi siempre/Siempre"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', now(), null, '["Productividad", "Aplicación", "Estrategia"]'::jsonb, 2, 3),

('DRH-A14', 'Cuestionario', 'Adopción', '6', '14', '¿Con qué frecuencia ajustas procesos de reclutamiento, onboarding u otros a partir de insights generados por IA (por ejemplo, cambiar fuentes de talento, mejorar experiencia de candidato)?', 'Multiple Choice (escala Likert A–E)', '["Nunca", "Rara vez (≤ 1/mes)", "Ocasional (2–3/mes)", "Frecuente (semanal)", "Casi siempre/Siempre"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', now(), null, '["Productividad", "Aplicación"]'::jsonb, 2, 3),

('DRH-A15', 'Cuestionario', 'Adopción', '6', '14', '¿Con qué frecuencia integras a líderes de negocio en sesiones específicas para revisar hallazgos de modelos de IA de personas (y no solo presentar números)?', 'Multiple Choice (escala Likert A–E)', '["Nunca", "Rara vez (≤ 1/mes)", "Ocasional (2–3/mes)", "Frecuente (semanal)", "Casi siempre/Siempre"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', now(), null, '["Aplicación"]'::jsonb, 2, 3),

('DRH-A16', 'Cuestionario', 'Adopción', '6', '14', '¿Con qué frecuencia pides explicaciones o visualizaciones que aclaren cómo la IA llegó a determinadas recomendaciones en RRHH?', 'Multiple Choice (escala Likert A–E)', '["Nunca", "Rara vez (≤ 1/mes)", "Ocasional (2–3/mes)", "Frecuente (semanal)", "Casi siempre/Siempre"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', now(), null, '["Aplicación"]'::jsonb, 2, 3),

('DRH-A17', 'Cuestionario', 'Adopción', '6', '14', '¿Con qué frecuencia consideras explícitamente los riesgos éticos (por ejemplo discriminación indirecta) antes de escalar el uso de un modelo de IA en RRHH?', 'Multiple Choice (escala Likert A–E)', '["Nunca", "Rara vez (≤ 1/mes)", "Ocasional (2–3/mes)", "Frecuente (semanal)", "Casi siempre/Siempre"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', now(), null, '["Aplicación", "Estrategia"]'::jsonb, 2, 3),

('DRH-A18', 'Cuestionario', 'Adopción', '6', '14', '¿Con qué frecuencia revisas, junto con Finanzas, el ahorro de tiempo/costo o el impacto en resultados de negocio atribuible a iniciativas de IA en RRHH?', 'Multiple Choice (escala Likert A–E)', '["Nunca", "Rara vez (≤ 1/mes)", "Ocasional (2–3/mes)", "Frecuente (semanal)", "Casi siempre/Siempre"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', now(), null, '["Productividad", "Inversión", "Estrategia"]'::jsonb, 2, 3),

('DRH-A19', 'Cuestionario', 'Adopción', '6', '14', '¿Con qué frecuencia participas en la definición de la hoja de ruta global de datos y analítica de la organización, asegurando que RRHH esté integrado?', 'Multiple Choice (escala Likert A–E)', '["Nunca", "Rara vez (≤ 1/mes)", "Ocasional (2–3/mes)", "Frecuente (semanal)", "Casi siempre/Siempre"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', now(), null, '["Aplicación"]'::jsonb, 2, 4),

('DRH-A20', 'Cuestionario', 'Adopción', '6', '14', '¿Con qué frecuencia tomas decisiones de headcount, reorganización o estrategias de talento basadas en escenarios generados con IA (simulaciones de costo, rotación, productividad)?', 'Multiple Choice (escala Likert A–E)', '["Nunca", "Rara vez (≤ 1/mes)", "Ocasional (2–3/mes)", "Frecuente (semanal)", "Casi siempre/Siempre"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', now(), null, '["Productividad", "Aplicación", "Inversión", "Estrategia"]'::jsonb, 2, 4),

('DRH-A21', 'Cuestionario', 'Adopción', '6', '14', '¿Con qué frecuencia alineas tus iniciativas de IA en RRHH con objetivos estratégicos de negocio (crecimiento, eficiencia, experiencia de cliente) y reportas avances?', 'Multiple Choice (escala Likert A–E)', '["Nunca", "Rara vez (≤ 1/mes)", "Ocasional (2–3/mes)", "Frecuente (semanal)", "Casi siempre/Siempre"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', now(), null, '["Productividad", "Estrategia"]'::jsonb, 2, 4),

('DRH-A22', 'Cuestionario', 'Adopción', '6', '14', '¿Con qué frecuencia impulsas el desarrollo de capacidades internas en analítica de personas (por ejemplo, creando un pequeño equipo de people analytics o formando a HRBPs)?', 'Multiple Choice (escala Likert A–E)', '["Nunca", "Rara vez (≤ 1/mes)", "Ocasional (2–3/mes)", "Frecuente (semanal)", "Casi siempre/Siempre"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', now(), null, '["Aplicación"]'::jsonb, 2, 4),

('DRH-A23', 'Cuestionario', 'Adopción', '6', '14', '¿Con qué frecuencia revisas, junto con otras áreas (Legal, Compliance, TI), el marco de gobernanza y ética en el uso de IA en RRHH?', 'Multiple Choice (escala Likert A–E)', '["Nunca", "Rara vez (≤ 1/mes)", "Ocasional (2–3/mes)", "Frecuente (semanal)", "Casi siempre/Siempre"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', now(), null, '["Aplicación", "Estrategia"]'::jsonb, 2, 4),

('DRH-A24', 'Cuestionario', 'Adopción', '6', '14', '¿Con qué frecuencia colaboras con Finanzas para cuantificar el ROI de proyectos de IA en RRHH (ahorro de tiempo, reducción de rotación, mejora en desempeño)?', 'Multiple Choice (escala Likert A–E)', '["Nunca", "Rara vez (≤ 1/mes)", "Ocasional (2–3/mes)", "Frecuente (semanal)", "Casi siempre/Siempre"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', now(), null, '["Productividad", "Inversión"]'::jsonb, 2, 4),

('DRH-A25', 'Cuestionario', 'Adopción', '6', '14', '¿Con qué frecuencia lideras discusiones en el comité ejecutivo sobre la agenda global de IA de la organización, incluyendo implicaciones en talento, capacidades y cultura?', 'Multiple Choice (escala Likert A–E)', '["Nunca", "Rara vez (≤ 1/mes)", "Ocasional (2–3/mes)", "Frecuente (semanal)", "Casi siempre/Siempre"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', now(), null, '["Aplicación"]'::jsonb, 2, 5),

('DRH-A26', 'Cuestionario', 'Adopción', '6', '14', '¿Con qué frecuencia defines, para nuevos proyectos de IA en RRHH, un caso de negocio formal (beneficios esperados, costos, riesgos) que se alinea con la estrategia corporativa?', 'Multiple Choice (escala Likert A–E)', '["Nunca", "Rara vez (≤ 1/mes)", "Ocasional (2–3/mes)", "Frecuente (semanal)", "Casi siempre/Siempre"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', now(), null, '["Inversión", "Estrategia"]'::jsonb, 2, 5),

('DRH-A27', 'Cuestionario', 'Adopción', '6', '14', '¿Con qué frecuencia incluyes criterios de ética y equidad en los RFP o contratos con proveedores de IA para RRHH (por ejemplo, evaluaciones de sesgo, explicabilidad)?', 'Multiple Choice (escala Likert A–E)', '["Nunca", "Rara vez (≤ 1/mes)", "Ocasional (2–3/mes)", "Frecuente (semanal)", "Casi siempre/Siempre"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', now(), null, '["Estrategia"]'::jsonb, 2, 5),

('DRH-A28', 'Cuestionario', 'Adopción', '6', '14', '¿Con qué frecuencia impulsas iniciativas para desarrollar una cultura de uso responsable de IA en toda la organización (formaciones, guías, políticas) con foco en personas?', 'Multiple Choice (escala Likert A–E)', '["Nunca", "Rara vez (≤ 1/mes)", "Ocasional (2–3/mes)", "Frecuente (semanal)", "Casi siempre/Siempre"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', now(), null, '["Aplicación", "Estrategia"]'::jsonb, 2, 5),

('DRH-A29', 'Cuestionario', 'Adopción', '6', '14', '¿Con qué frecuencia revisas el portafolio total de casos de uso de IA (no solo de RRHH) para asegurar que la agenda de personas (skills, reskilling, impacto en roles) esté integrada?', 'Multiple Choice (escala Likert A–E)', '["Nunca", "Rara vez (≤ 1/mes)", "Ocasional (2–3/mes)", "Frecuente (semanal)", "Casi siempre/Siempre"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', now(), null, '["Aplicación"]'::jsonb, 2, 5),

('DRH-A30', 'Cuestionario', 'Adopción', '6', '14', '¿Con qué frecuencia reportas a los órganos de gobierno (Director General, Consejo, Comité de Ética) el estado y evolución de la IA en RRHH, incluyendo beneficios, riesgos y planes de mitigación?', 'Multiple Choice (escala Likert A–E)', '["Nunca", "Rara vez (≤ 1/mes)", "Ocasional (2–3/mes)", "Frecuente (semanal)", "Casi siempre/Siempre"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', now(), null, '["Estrategia"]'::jsonb, 2, 5);

-- CONOCIMIENTO - Rol 14
INSERT INTO "public"."preguntas" ("codigo", "section", "bloque", "area_id", "exclusivo_rol_id", "texto", "tipo", "opciones", "locale", "peso", "escala", "scoring", "created_at", "respuesta_correcta", "dimension", "exclusivo_nivel_id", "dificultad") VALUES
('DRH-C1', 'Cuestionario', 'Conocimiento', '6', '14', '¿Cuál de las siguientes es una definición más adecuada de inteligencia artificial aplicada a RRHH?', 'Multiple Choice (una respuesta)', '["a) Un sistema que reemplaza totalmente al área de RRHH.", "b) Un conjunto de reglas fijas usadas solo para pagar nómina.", "c) Tecnologías que permiten a las máquinas analizar datos de personas, aprender de patrones y apoyar decisiones de RRHH.", "d) Un software que guarda CV en formato digital sin analizarlos."]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', now(), 'c) Tecnologías que permiten a las máquinas analizar datos de personas, aprender de patrones y apoyar decisiones de RRHH.', '["Aplicación", "Conocimiento"]'::jsonb, 2, 1),

('DRH-C2', 'Cuestionario', 'Conocimiento', '6', '14', '¿Cuál es un ejemplo básico de IA en reclutamiento?', 'Multiple Choice (una respuesta)', '["a) Publicar vacantes en una red social sin segmentación.", "b) Un sistema que ordena CV alfabéticamente.", "c) Un algoritmo que analiza CV y los clasifica según afinidad al perfil requerido.", "d) Una entrevista presencial sin guía estructurada."]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', now(), 'c) Un algoritmo que analiza CV y los clasifica según afinidad al perfil requerido.', '["Conocimiento"]'::jsonb, 2, 1),

('DRH-C3', 'Cuestionario', 'Conocimiento', '6', '14', '¿Qué riesgo principal debe considerar un Director de RRHH al usar IA para tomar decisiones de personas?', 'Multiple Choice (una respuesta)', '["a) Reducir el número de correos que envía el área.", "b) Que los modelos puedan reproducir sesgos presentes en los datos históricos.", "c) Que el ATS deje de recibir nuevos CV.", "d) Que la IA impida hacer reuniones de equipo."]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', now(), 'b) Que los modelos puedan reproducir sesgos presentes en los datos históricos.', '["Estrategia", "Conocimiento"]'::jsonb, 2, 1),

('DRH-C4', 'Cuestionario', 'Conocimiento', '6', '14', '¿Qué describe mejor el concepto de analítica de personas (people analytics)?', 'Multiple Choice (una respuesta)', '["a) Medir únicamente cuántos colaboradores tiene la empresa.", "b) Uso de datos de personas para comprender y predecir comportamientos que impactan el negocio.", "c) Llevar el control de vacaciones en hojas de cálculo.", "d) Realizar focus groups sin registrar resultados."]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', now(), 'b) Uso de datos de personas para comprender y predecir comportamientos que impactan el negocio.', '["Aplicación", "Conocimiento"]'::jsonb, 2, 1),

('DRH-C5', 'Cuestionario', 'Conocimiento', '6', '14', '¿Cuál de las siguientes inversiones es más coherente como primer paso para adoptar IA en RRHH?', 'Multiple Choice (una respuesta)', '["a) Comprar la solución más costosa del mercado sin piloto.", "b) Capacitar al equipo de RRHH en conceptos básicos de IA y analítica de personas.", "c) Eliminar toda la infraestructura actual de RRHH.", "d) Externalizar completamente RRHH sin criterios claros."]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', now(), 'b) Capacitar al equipo de RRHH en conceptos básicos de IA y analítica de personas.', '["Conocimiento"]'::jsonb, 2, 1),

('DRH-C6', 'Cuestionario', 'Conocimiento', '6', '14', 'Un ejemplo de uso productivo de IA para RRHH sería:', 'Multiple Choice (una respuesta)', '["a) Pedir al equipo de RRHH que copie y pegue datos entre sistemas.", "b) Utilizar IA para generar borradores de políticas de RRHH y luego revisarlos.", "c) Imprimir los CV y archivarlos en físico.", "d) Prohibir el uso de cualquier herramienta digital."]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', now(), 'b) Utilizar IA para generar borradores de políticas de RRHH y luego revisarlos.', '["Aplicación", "Conocimiento"]'::jsonb, 2, 1),

('DRH-C7', 'Cuestionario', 'Conocimiento', '6', '14', '¿Qué describe mejor un piloto de IA en RRHH?', 'Multiple Choice (una respuesta)', '["a) Implementar la herramienta en toda la organización desde el primer día.", "b) Un experimento controlado con un proceso o segmento específico para evaluar valor y riesgos.", "c) Comprar licencias para todos los colaboradores sin monitoreo.", "d) Sustituir al equipo de RRHH por completo."]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', now(), 'b) Un experimento controlado con un proceso o segmento específico para evaluar valor y riesgos.', '["Conocimiento"]'::jsonb, 2, 2),

('DRH-C8', 'Cuestionario', 'Conocimiento', '6', '14', '¿Cuál de los siguientes es un uso adecuado de IA generativa en RRHH en etapa inicial?', 'Multiple Choice (una respuesta)', '["a) Dejar que la IA tome decisiones finales de despido.", "b) Usar IA para redactar versiones iniciales de job postings, revisadas por RRHH.", "c) Dar acceso irrestricto a datos sensibles de nómina a cualquier empleado.", "d) Permitir que la IA firme contratos en nombre de la empresa."]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', now(), 'b) Usar IA para redactar versiones iniciales de job postings, revisadas por RRHH.', '["Aplicación", "Conocimiento"]'::jsonb, 2, 2),

('DRH-C9', 'Cuestionario', 'Conocimiento', '6', '14', '¿Qué indicador es más relevante para evaluar un piloto de IA en reclutamiento?', 'Multiple Choice (una respuesta)', '["a) Número de correos enviados por RRHH.", "b) Tiempo promedio para cubrir vacantes y calidad de candidatos contratados.", "c) Tamaño de la oficina de RRHH.", "d) Número de impresiones de CV."]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', now(), 'b) Tiempo promedio para cubrir vacantes y calidad de candidatos contratados.', '["Conocimiento"]'::jsonb, 2, 2),

('DRH-C10', 'Cuestionario', 'Conocimiento', '6', '14', 'En términos de ética, ¿qué práctica es recomendable al usar IA para filtrar CV?', 'Multiple Choice (una respuesta)', '["a) Ocultar a candidatos que se usa IA.", "b) No revisar las recomendaciones y aceptar todo lo que diga la herramienta.", "c) Monitorizar regularmente los resultados para detectar posibles sesgos y ajustarlos.", "d) Usar datos personales irrelevantes (por ejemplo religión) para mejorar la predicción."]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', now(), 'c) Monitorizar regularmente los resultados para detectar posibles sesgos y ajustarlos.', '["Estrategia", "Conocimiento"]'::jsonb, 2, 2),

('DRH-C11', 'Cuestionario', 'Conocimiento', '6', '14', '¿Qué tipo de inversión es más adecuada en esta fase?', 'Multiple Choice (una respuesta)', '["a) Múltiples plataformas de IA diferentes sin criterios claros.", "b) Uno o dos pilotos con un proveedor, con métricas y evaluación de ROI básico.", "c) Suspender cualquier inversión en formación del equipo.", "d) Comprar un sistema complejo sin involucrar a TI ni Legal."]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', now(), 'b) Uno o dos pilotos con un proveedor, con métricas y evaluación de ROI básico.', '["Inversión", "Conocimiento"]'::jsonb, 2, 2),

('DRH-C12', 'Cuestionario', 'Conocimiento', '6', '14', '¿Qué ejemplo refleja mejor un enfoque de colaboración entre RRHH y otra área en IA?', 'Multiple Choice (una respuesta)', '["a) RRHH diseña el modelo de IA sin escuchar a TI.", "b) TI implementa la herramienta sin considerar procesos de RRHH.", "c) RRHH y TI co-definen alcance, datos y criterios de éxito de un piloto de IA.", "d) Negocio decide la herramienta sin informar a RRHH."]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', now(), 'c) RRHH y TI co-definen alcance, datos y criterios de éxito de un piloto de IA.', '["Conocimiento"]'::jsonb, 2, 2),

('DRH-C13', 'Cuestionario', 'Conocimiento', '6', '14', '¿Cuál es un ejemplo de modelo predictivo útil para Dirección de RRHH?', 'Multiple Choice (una respuesta)', '["a) Un modelo que calcula solo el número de empleados actuales.", "b) Un modelo que predice qué empleados tienen mayor riesgo de rotación según variables históricas.", "c) Un modelo que calcula el precio de las acciones de la empresa.", "d) Un modelo que cuenta la cantidad de correos enviados por RRHH."]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', now(), 'b) Un modelo que predice qué empleados tienen mayor riesgo de rotación según variables históricas.', '["Conocimiento"]'::jsonb, 2, 3),

('DRH-C14', 'Cuestionario', 'Conocimiento', '6', '14', '¿Qué práctica es recomendable al usar IA para recomendar planes de desarrollo individual (PDI)?', 'Multiple Choice (una respuesta)', '["a) Aceptar todas las recomendaciones sin consultar al colaborador.", "b) Usar las recomendaciones como insumo, validarlas con el líder y el colaborador.", "c) Obligar al colaborador a seguir solo lo que dice la IA.", "d) Compartir datos sensibles de desempeño con toda la organización."]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', now(), 'b) Usar las recomendaciones como insumo, validarlas con el líder y el colaborador.', '["Conocimiento"]'::jsonb, 2, 3),

('DRH-C15', 'Cuestionario', 'Conocimiento', '6', '14', '¿Qué tipo de dato es más relevante para modelos de rotación?', 'Multiple Choice (una respuesta)', '["a) Color favorito del colaborador.", "b) Historial de desempeño, antigüedad, cambios salariales y movimientos internos.", "c) Número de correos personales enviados desde su cuenta.", "d) Marca de dispositivo que usa."]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', now(), 'b) Historial de desempeño, antigüedad, cambios salariales y movimientos internos.', '["Conocimiento"]'::jsonb, 2, 3),

('DRH-C16', 'Cuestionario', 'Conocimiento', '6', '14', '¿Qué significa que un modelo de IA sea explicable (explainable)?', 'Multiple Choice (una respuesta)', '["a) Que nunca comete errores.", "b) Que solo TI entiende cómo funciona.", "c) Que es posible entender qué variables influyen en las recomendaciones para poder cuestionarlas.", "d) Que no necesita datos para funcionar."]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', now(), 'c) Que es posible entender qué variables influyen en las recomendaciones para poder cuestionarlas.', '["Conocimiento"]'::jsonb, 2, 3),

('DRH-C17', 'Cuestionario', 'Conocimiento', '6', '14', 'En términos de inversión, ¿qué enfoque es más sostenible para seguir escalando IA en RRHH?', 'Multiple Choice (una respuesta)', '["a) Depender exclusivamente de consultores externos.", "b) Desarrollar capacidades internas en people analytics y gobernanza de datos, además de usar proveedores.", "c) Cambiar de proveedor cada mes.", "d) Invertir solo en hardware sin formación."]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', now(), 'b) Desarrollar capacidades internas en people analytics y gobernanza de datos, además de usar proveedores.', '["Inversión", "Conocimiento"]'::jsonb, 2, 3),

('DRH-C18', 'Cuestionario', 'Conocimiento', '6', '14', '¿Qué práctica reduce riesgos de sesgo en modelos de IA de RRHH?', 'Multiple Choice (una respuesta)', '["a) Entrenar modelos solo con datos de un área o país.", "b) Revisar periódicamente resultados por género, edad u otros grupos para detectar diferencias injustificadas.", "c) Mantener el modelo sin cambios por años.", "d) No documentar el origen de los datos usados."]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', now(), 'b) Revisar periódicamente resultados por género, edad u otros grupos para detectar diferencias injustificadas.', '["Estrategia", "Conocimiento"]'::jsonb, 2, 3),

('DRH-C19', 'Cuestionario', 'Conocimiento', '6', '14', '¿Qué describe mejor el workforce planning apoyado en IA?', 'Multiple Choice (una respuesta)', '["a) Contar manualmente el número de empleados y hacer estimaciones subjetivas.", "b) Usar modelos que combinan datos de negocio (ventas, expansión) y de personas para proyectar necesidades de talento.", "c) Decidir contrataciones solo por presión de jefes de área.", "d) Congelar contrataciones sin análisis."]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', now(), 'b) Usar modelos que combinan datos de negocio (ventas, expansión) y de personas para proyectar necesidades de talento.', '["Conocimiento"]'::jsonb, 2, 4),

('DRH-C20', 'Cuestionario', 'Conocimiento', '6', '14', '¿Cuál es una buena práctica al priorizar proyectos de IA en el portafolio de RRHH?', 'Multiple Choice (una respuesta)', '["a) Seleccionar los proyectos más de moda.", "b) Evaluar impacto potencial en negocio, factibilidad técnica y riesgos éticos.", "c) Elegir solo proyectos que requieran grandes presupuestos.", "d) Priorizar solo lo que beneficie a RRHH, sin considerar negocio."]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', now(), 'b) Evaluar impacto potencial en negocio, factibilidad técnica y riesgos éticos.', '["Estrategia", "Conocimiento"]'::jsonb, 2, 4),

('DRH-C21', 'Cuestionario', 'Conocimiento', '6', '14', '¿Qué es una política de gobernanza de datos de personas?', 'Multiple Choice (una respuesta)', '["a) Un documento que define quién puede acceder a qué datos, con qué propósito y bajo qué controles.", "b) Un listado de todos los empleados.", "c) Una descripción del organigrama.", "d) Una política exclusiva de TI sin participación de RRHH."]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', now(), 'a) Un documento que define quién puede acceder a qué datos, con qué propósito y bajo qué controles.', '["Aplicación", "Estrategia", "Conocimiento"]'::jsonb, 2, 4),

('DRH-C22', 'Cuestionario', 'Conocimiento', '6', '14', '¿Qué significa que RRHH tenga una arquitectura de datos integrada?', 'Multiple Choice (una respuesta)', '["a) Cada sistema de RRHH funciona aislado y no comparte datos.", "b) Los datos de personas están conectados (ATS, LMS, desempeño, nómina) permitiendo modelos integrales.", "c) Todos los datos se guardan en hojas de cálculo personales.", "d) Solo se usan datos de encuestas de clima."]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', now(), 'b) Los datos de personas están conectados (ATS, LMS, desempeño, nómina) permitiendo modelos integrales.', '["Aplicación", "Conocimiento"]'::jsonb, 2, 4),

('DRH-C23', 'Cuestionario', 'Conocimiento', '6', '14', '¿Qué rol es clave para acompañar a Dirección de RRHH en la agenda de IA?', 'Multiple Choice (una respuesta)', '["a) Únicamente el área de Compras.", "b) TI / Datos, para asegurar viabilidad técnica, seguridad y arquitectura adecuada.", "c) Seguridad física.", "d) Marketing externo."]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', now(), 'b) TI / Datos, para asegurar viabilidad técnica, seguridad y arquitectura adecuada.', '["Conocimiento"]'::jsonb, 2, 4),

('DRH-C24', 'Cuestionario', 'Conocimiento', '6', '14', 'En términos de ética, ¿qué es una buena práctica de transparencia con colaboradores respecto a IA en RRHH?', 'Multiple Choice (una respuesta)', '["a) No informar sobre el uso de IA para evitar preocupaciones.", "b) Comunicar de forma clara qué modelos se usan, para qué decisiones y cómo se protege su información.", "c) Compartir el código fuente completo de todos los modelos.", "d) Solo informar a los mandos medios."]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', now(), 'b) Comunicar de forma clara qué modelos se usan, para qué decisiones y cómo se protege su información.', '["Estrategia", "Conocimiento"]'::jsonb, 2, 4),

('DRH-C25', 'Cuestionario', 'Conocimiento', '6', '14', '¿Qué describe mejor el rol de Dirección de RRHH en una arquitectura de IA empresarial?', 'Multiple Choice (una respuesta)', '["a) Ser solo usuario pasivo de herramientas definidas por TI.", "b) Co-liderar el diseño de casos de uso de personas, criterios éticos y métricas de éxito.", "c) Delegar completamente la responsabilidad de IA a proveedores.", "d) Limitarse a tareas administrativas."]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', now(), 'b) Co-liderar el diseño de casos de uso de personas, criterios éticos y métricas de éxito.', '["Conocimiento"]'::jsonb, 2, 5),

('DRH-C26', 'Cuestionario', 'Conocimiento', '6', '14', 'Al evaluar un portafolio de proyectos de IA en RRHH, ¿qué combinación de criterios es más robusta?', 'Multiple Choice (una respuesta)', '["a) Solo impacto en reducción de headcount de RRHH.", "b) Impacto en negocio, experiencia de colaborador, riesgos éticos y complejidad técnica.", "c) Exclusivamente costo de licencias.", "d) Opiniones subjetivas de un proveedor."]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', now(), 'b) Impacto en negocio, experiencia de colaborador, riesgos éticos y complejidad técnica.', '["Conocimiento"]'::jsonb, 2, 5),

('DRH-C27', 'Cuestionario', 'Conocimiento', '6', '14', '¿Qué es un marco de riesgos de IA aplicado a RRHH?', 'Multiple Choice (una respuesta)', '["a) Una lista de proveedores aprobados.", "b) Un conjunto de criterios para evaluar impacto, probabilidad y mitigaciones de riesgos (sesgos, privacidad, reputación) en cada caso de uso.", "c) Un contrato genérico de software.", "d) Una política que prohíbe cualquier uso de IA."]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', now(), 'b) Un conjunto de criterios para evaluar impacto, probabilidad y mitigaciones de riesgos (sesgos, privacidad, reputación) en cada caso de uso.', '["Estrategia", "Aplicación", "Conocimiento"]'::jsonb, 2, 5),

('DRH-C28', 'Cuestionario', 'Conocimiento', '6', '14', '¿Qué práctica favorece la escalabilidad de la IA en RRHH?', 'Multiple Choice (una respuesta)', '["a) Diseñar cada caso de uso con datos y modelos completamente independientes.", "b) Usar una base de datos de personas unificada y una capa común de servicios de IA.", "c) Cambiar de proveedor cada proyecto.", "d) Mantener todos los modelos en hojas de cálculo."]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', now(), 'b) Usar una base de datos de personas unificada y una capa común de servicios de IA.', '["Conocimiento"]'::jsonb, 2, 5),

('DRH-C29', 'Cuestionario', 'Conocimiento', '6', '14', '¿Qué enfoque es más coherente para integrar IA en la propuesta de valor al empleado (EVP)?', 'Multiple Choice (una respuesta)', '["a) Usar IA solo para aumentar el control y vigilancia.", "b) Diseñar experiencias personalizadas de desarrollo, carrera y bienestar, respetando privacidad y transparencia.", "c) No informar sobre el uso de IA en procesos de talento.", "d) Enfocar la IA solo en reducir costos."]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', now(), 'b) Diseñar experiencias personalizadas de desarrollo, carrera y bienestar, respetando privacidad y transparencia.', '["Conocimiento"]'::jsonb, 2, 5),

('DRH-C30', 'Cuestionario', 'Conocimiento', '6', '14', 'Desde la perspectiva de inversión, ¿qué combinación es más estratégica a largo plazo?', 'Multiple Choice (una respuesta)', '["a) Solo comprar tecnología sin formar a las personas.", "b) Equilibrar inversión en tecnología, datos, capacidades internas y gestión del cambio cultural.", "c) Invertir únicamente en campañas de marketing sobre IA.", "d) Delegar todos los proyectos de IA a terceros."]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', now(), 'b) Equilibrar inversión en tecnología, datos, capacidades internas y gestión del cambio cultural.', '["Inversión", "Conocimiento"]'::jsonb, 2, 5);
