-- ============================================================================
-- PREGUNTAS PARA GERENTE DE TI
-- ============================================================================
-- Rol incluido:
--   - Rol ID 5: Gerente de TI (area_id: 9, nivel_id: 3)
-- ============================================================================

-- ============================================================================
-- ROL 5: Gerente de TI
-- ============================================================================

-- ADOPCIÓN - Rol 5
INSERT INTO "public"."preguntas" ("codigo", "section", "bloque", "area_id", "exclusivo_rol_id", "texto", "tipo", "opciones", "locale", "peso", "escala", "scoring", "created_at", "respuesta_correcta", "dimension", "exclusivo_nivel_id", "dificultad") VALUES
('GTI-A1', 'Cuestionario', 'Adopción', '9', '5', 'Uso herramientas de IA (por ejemplo, chatbots o asistentes de texto) para redactar o mejorar comunicaciones relacionadas con TI (correos, avisos de mantenimiento, etc.).', 'Multiple Choice (escala Likert A–E)', '["Nunca", "Rara vez (≤ 1/mes)", "Ocasional (2–3/mes)", "Frecuente (semanal)", "Muy frecuente (diaria)"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', now(), null, '["Aplicación"]'::jsonb, 3, 1),

('GTI-A2', 'Cuestionario', 'Adopción', '9', '5', 'Uso funciones de IA o automatización en mi herramienta ITSM para clasificar o enrutar tickets.', 'Multiple Choice (escala Likert A–E)', '["Nunca", "Rara vez (≤ 1/mes)", "Ocasional (2–3/mes)", "Frecuente (semanal)", "Muy frecuente (diaria)"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', now(), null, '["Aplicación"]'::jsonb, 3, 1),

('GTI-A3', 'Cuestionario', 'Adopción', '9', '5', 'He liderado o co-liderado proyectos de IA en monitoreo, gestión de capacidad o soporte dentro del área de TI.', 'Multiple Choice (escala Likert A–E)', '["Nunca", "Rara vez (≤ 1/mes)", "Ocasional (2–3/mes)", "Frecuente (semanal)", "Muy frecuente (diaria)"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', now(), null, '["Aplicación"]'::jsonb, 3, 1),

('GTI-A4', 'Cuestionario', 'Adopción', '9', '5', 'Participo activamente en la definición o actualización del roadmap de IA de la organización, coordinado con la estrategia de TI.', 'Multiple Choice (escala Likert A–E)', '["Nunca", "Rara vez (≤ 1/mes)", "Ocasional (2–3/mes)", "Frecuente (semanal)", "Muy frecuente (diaria)"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', now(), null, '["Estrategia"]'::jsonb, 3, 1),

('GTI-A5', 'Cuestionario', 'Adopción', '9', '5', 'Lidero o co-lidero un programa de transformación donde IA es un pilar central (no solo proyectos aislados).', 'Multiple Choice (escala Likert A–E)', '["Nunca", "Rara vez (≤ 1/mes)", "Ocasional (2–3/mes)", "Frecuente (semanal)", "Muy frecuente (diaria)"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', now(), null, '["Aplicación"]'::jsonb, 3, 1),

('GTI-A6', 'Cuestionario', 'Adopción', '9', '5', 'He probado al menos una herramienta de IA para apoyar actividades de soporte (preguntas frecuentes, ayuda a la mesa de servicio, etc.).', 'Multiple Choice (escala Likert A–E)', '["Nunca", "Rara vez (≤ 1/mes)", "Ocasional (2–3/mes)", "Frecuente (semanal)", "Muy frecuente (diaria)"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', now(), null, '["Aplicación"]'::jsonb, 3, 1),

('GTI-A7', 'Cuestionario', 'Adopción', '9', '5', 'Reviso métricas como MTTR o volumen de tickets resueltos para evaluar el impacto de la IA en soporte.', 'Multiple Choice (escala Likert A–E)', '["Nunca", "Rara vez (≤ 1/mes)", "Ocasional (2–3/mes)", "Frecuente (semanal)", "Muy frecuente (diaria)"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', now(), null, '["Productividad"]'::jsonb, 3, 2),

('GTI-A8', 'Cuestionario', 'Adopción', '9', '5', 'Reviso regularmente indicadores de impacto (ej. reducción de incidentes, tiempo de indisponibilidad) para evaluar proyectos de IA en TI.', 'Multiple Choice (escala Likert A–E)', '["Nunca", "Rara vez (≤ 1/mes)", "Ocasional (2–3/mes)", "Frecuente (semanal)", "Muy frecuente (diaria)"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', now(), null, '["Productividad"]'::jsonb, 3, 2),

('GTI-A9', 'Cuestionario', 'Adopción', '9', '5', 'Co-lidero con otras áreas (Operaciones, Ventas, Finanzas, etc.) la priorización de casos de uso de IA según impacto en objetivos estratégicos.', 'Multiple Choice (escala Likert A–E)', '["Nunca", "Rara vez (≤ 1/mes)", "Ocasional (2–3/mes)", "Frecuente (semanal)", "Muy frecuente (diaria)"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', now(), null, '["Aplicación"]'::jsonb, 3, 2),

('GTI-A10', 'Cuestionario', 'Adopción', '9', '5', 'Impulso el diseño y evolución de plataformas corporativas de datos e IA (por ejemplo, data platform, MLOps) para reutilizar capacidades en múltiples casos de uso.', 'Multiple Choice (escala Likert A–E)', '["Nunca", "Rara vez (≤ 1/mes)", "Ocasional (2–3/mes)", "Frecuente (semanal)", "Muy frecuente (diaria)"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', now(), null, '["Aplicación"]'::jsonb, 3, 2),

('GTI-A11', 'Cuestionario', 'Adopción', '9', '5', 'Siento que la IA ya me ha ayudado a ahorrar tiempo en tareas administrativas o de comunicación de TI.', 'Multiple Choice (escala Likert A–E)', '["Nunca", "Rara vez (≤ 1/mes)", "Ocasional (2–3/mes)", "Frecuente (semanal)", "Muy frecuente (diaria)"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', now(), null, '["Productividad"]'::jsonb, 3, 2),

('GTI-A12', 'Cuestionario', 'Adopción', '9', '5', 'Promuevo que el equipo documente qué tareas repetitivas podrían ser candidatas a automatización con IA.', 'Multiple Choice (escala Likert A–E)', '["Nunca", "Rara vez (≤ 1/mes)", "Ocasional (2–3/mes)", "Frecuente (semanal)", "Muy frecuente (diaria)"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', now(), null, '["Aplicación"]'::jsonb, 3, 2),

('GTI-A13', 'Cuestionario', 'Adopción', '9', '5', 'Trabajo con mi equipo para mejorar la calidad de datos que alimenta a las soluciones de IA (por ejemplo, estandarizar categorías de incidentes o métricas de monitoreo).', 'Multiple Choice (escala Likert A–E)', '["Nunca", "Rara vez (≤ 1/mes)", "Ocasional (2–3/mes)", "Frecuente (semanal)", "Muy frecuente (diaria)"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', now(), null, '["Productividad", "Aplicación"]'::jsonb, 3, 3),

('GTI-A14', 'Cuestionario', 'Adopción', '9', '5', 'Impulso la creación o adopción de marcos de gobierno de IA (políticas, comités, lineamientos de datos y modelos).', 'Multiple Choice (escala Likert A–E)', '["Nunca", "Rara vez (≤ 1/mes)", "Ocasional (2–3/mes)", "Frecuente (semanal)", "Muy frecuente (diaria)"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', now(), null, '["Aplicación"]'::jsonb, 3, 3),

('GTI-A15', 'Cuestionario', 'Adopción', '9', '5', 'Promuevo y apoyo programas de formación en IA para distintas áreas de la organización (no solo TI).', 'Multiple Choice (escala Likert A–E)', '["Nunca", "Rara vez (≤ 1/mes)", "Ocasional (2–3/mes)", "Frecuente (semanal)", "Muy frecuente (diaria)"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', now(), null, '["Aplicación"]'::jsonb, 3, 3),

('GTI-A16', 'Cuestionario', 'Adopción', '9', '5', 'Antes de compartir información corporativa en una herramienta de IA, reviso si contiene datos sensibles o confidenciales.', 'Multiple Choice (escala Likert A–E)', '["Nunca", "Rara vez (≤ 1/mes)", "Ocasional (2–3/mes)", "Frecuente (semanal)", "Muy frecuente (diaria)"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', now(), null, '["Estrategia", "Aplicación"]'::jsonb, 3, 3),

('GTI-A17', 'Cuestionario', 'Adopción', '9', '5', 'Cuando pruebo una nueva función con IA en nuestras herramientas, establezco algún período de prueba controlado (piloto) antes de usarla en producción.', 'Multiple Choice (escala Likert A–E)', '["Nunca", "Rara vez (≤ 1/mes)", "Ocasional (2–3/mes)", "Frecuente (semanal)", "Muy frecuente (diaria)"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', now(), null, '["Aplicación"]'::jsonb, 3, 3),

('GTI-A18', 'Cuestionario', 'Adopción', '9', '5', 'Coordino con Finanzas u otras áreas para justificar inversiones en soluciones de IA para TI usando datos de impacto.', 'Multiple Choice (escala Likert A–E)', '["Nunca", "Rara vez (≤ 1/mes)", "Ocasional (2–3/mes)", "Frecuente (semanal)", "Muy frecuente (diaria)"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', now(), null, '["Aplicación"]'::jsonb, 3, 3),

('GTI-A19', 'Cuestionario', 'Adopción', '9', '5', 'Evalúo regularmente la cartera de proyectos de IA para ajustar inversiones, descontinuar pilotos o escalar soluciones probadas.', 'Multiple Choice (escala Likert A–E)', '["Nunca", "Rara vez (≤ 1/mes)", "Ocasional (2–3/mes)", "Frecuente (semanal)", "Muy frecuente (diaria)"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', now(), null, '["Aplicación"]'::jsonb, 3, 4),

('GTI-A20', 'Cuestionario', 'Adopción', '9', '5', 'Trabajo con Alta Dirección para incorporar la IA y el uso de datos en la estrategia corporativa y en la agenda de riesgos.', 'Multiple Choice (escala Likert A–E)', '["Nunca", "Rara vez (≤ 1/mes)", "Ocasional (2–3/mes)", "Frecuente (semanal)", "Muy frecuente (diaria)"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', now(), null, '["Estrategia", "Aplicación"]'::jsonb, 3, 4),

('GTI-A21', 'Cuestionario', 'Adopción', '9', '5', 'Converso con mi equipo de TI sobre qué herramientas de IA pueden probar y para qué tipos de tareas.', 'Multiple Choice (escala Likert A–E)', '["Nunca", "Rara vez (≤ 1/mes)", "Ocasional (2–3/mes)", "Frecuente (semanal)", "Muy frecuente (diaria)"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', now(), null, '["Aplicación"]'::jsonb, 3, 4),

('GTI-A22', 'Cuestionario', 'Adopción', '9', '5', 'Coordino con otras áreas (por ejemplo, Recursos Humanos o Comunicación interna) para que el uso de chatbots de TI esté alineado con la experiencia del colaborador.', 'Multiple Choice (escala Likert A–E)', '["Nunca", "Rara vez (≤ 1/mes)", "Ocasional (2–3/mes)", "Frecuente (semanal)", "Muy frecuente (diaria)"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', now(), null, '["Aplicación"]'::jsonb, 3, 4),

('GTI-A23', 'Cuestionario', 'Adopción', '9', '5', 'Estoy involucrado en la selección de proveedores de IA (RFP, evaluación técnica y de seguridad).', 'Multiple Choice (escala Likert A–E)', '["Nunca", "Rara vez (≤ 1/mes)", "Ocasional (2–3/mes)", "Frecuente (semanal)", "Muy frecuente (diaria)"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', now(), null, '["Estrategia"]'::jsonb, 3, 4),

('GTI-A24', 'Cuestionario', 'Adopción', '9', '5', 'Promuevo que el equipo de TI desarrolle capacidades internas (skills, herramientas) para reducir dependencia excesiva de proveedores en IA.', 'Multiple Choice (escala Likert A–E)', '["Nunca", "Rara vez (≤ 1/mes)", "Ocasional (2–3/mes)", "Frecuente (semanal)", "Muy frecuente (diaria)"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', now(), null, '["Aplicación"]'::jsonb, 3, 4),

('GTI-A25', 'Cuestionario', 'Adopción', '9', '5', 'Fomento que existan mecanismos de feedback (de clientes, colaboradores y stakeholders) sobre los sistemas con IA para mejorar y corregir sesgos o efectos no deseados.', 'Multiple Choice (escala Likert A–E)', '["Nunca", "Rara vez (≤ 1/mes)", "Ocasional (2–3/mes)", "Frecuente (semanal)", "Muy frecuente (diaria)"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', now(), null, '["Estrategia"]'::jsonb, 3, 5),

('GTI-A26', 'Cuestionario', 'Adopción', '9', '5', 'He buscado o considerado alguna capacitación básica para entender mejor qué puede y qué no puede hacer la IA en nuestro contexto.', 'Multiple Choice (escala Likert A–E)', '["Nunca", "Rara vez (≤ 1/mes)", "Ocasional (2–3/mes)", "Frecuente (semanal)", "Muy frecuente (diaria)"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', now(), null, '["Aplicación"]'::jsonb, 3, 5),

('GTI-A27', 'Cuestionario', 'Adopción', '9', '5', 'He propuesto o gestionado pequeños presupuestos para pilotos de IA (por ejemplo, licencias adicionales, módulos de IA en herramientas actuales).', 'Multiple Choice (escala Likert A–E)', '["Nunca", "Rara vez (≤ 1/mes)", "Ocasional (2–3/mes)", "Frecuente (semanal)", "Muy frecuente (diaria)"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', now(), null, '["Inversión", "Aplicación"]'::jsonb, 3, 5),

('GTI-A28', 'Cuestionario', 'Adopción', '9', '5', 'Aseguro que las soluciones de IA que usamos en TI tengan controles claros (auditoría, logs, permisos, revisión humana cuando aplica).', 'Multiple Choice (escala Likert A–E)', '["Nunca", "Rara vez (≤ 1/mes)", "Ocasional (2–3/mes)", "Frecuente (semanal)", "Muy frecuente (diaria)"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', now(), null, '["Estrategia", "Aplicación"]'::jsonb, 3, 5),

('GTI-A29', 'Cuestionario', 'Adopción', '9', '5', 'Integro indicadores de IA (por ejemplo, impacto en SLA, ingresos, reducción de riesgos) en los tableros de gestión que se reportan a Dirección.', 'Multiple Choice (escala Likert A–E)', '["Nunca", "Rara vez (≤ 1/mes)", "Ocasional (2–3/mes)", "Frecuente (semanal)", "Muy frecuente (diaria)"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', now(), null, '["Estrategia"]'::jsonb, 3, 5),

('GTI-A30', 'Cuestionario', 'Adopción', '9', '5', 'Integro los resultados de IA (insights, predicciones, automatizaciones) en los procesos y decisiones clave del negocio de manera sistemática, no solo en pilotos.', 'Multiple Choice (escala Likert A–E)', '["Nunca", "Rara vez (≤ 1/mes)", "Ocasional (2–3/mes)", "Frecuente (semanal)", "Muy frecuente (diaria)"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', now(), null, '["Productividad"]'::jsonb, 3, 5);

-- CONOCIMIENTO - Rol 5
INSERT INTO "public"."preguntas" ("codigo", "section", "bloque", "area_id", "exclusivo_rol_id", "texto", "tipo", "opciones", "locale", "peso", "escala", "scoring", "created_at", "respuesta_correcta", "dimension", "exclusivo_nivel_id", "dificultad") VALUES
('GTI-C1', 'Cuestionario', 'Conocimiento', '9', '5', 'En tu contexto como Gerente de TI, ¿qué describe mejor a la inteligencia artificial generativa?', 'Multiple Choice (una respuesta)', '["Un sistema de reporteo tradicional basado en reglas fijas", "Un tipo de IA que puede crear contenido nuevo (texto, código, imágenes) a partir de datos existentes", "Cualquier algoritmo de ordenamiento de datos", "Un servidor dedicado a copias de seguridad"]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', now(), 'Un tipo de IA que puede crear contenido nuevo (texto, código, imágenes) a partir de datos existentes', '["Conocimiento"]'::jsonb, 3, 1),

('GTI-C2', 'Cuestionario', 'Conocimiento', '9', '5', '¿Qué describe mejor a un chatbot de soporte de TI basado en IA?', 'Multiple Choice (una respuesta)', '["Un formulario estático de contacto", "Un sistema que responde siempre con mensajes pregrabados", "Un sistema que entiende lenguaje natural y puede responder o enrutar solicitudes automáticamente", "Una base de datos relacional"]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', now(), 'Un sistema que entiende lenguaje natural y puede responder o enrutar solicitudes automáticamente', '["Conocimiento"]'::jsonb, 3, 1),

('GTI-C3', 'Cuestionario', 'Conocimiento', '9', '5', '¿Qué es AIOps en el contexto de monitoreo de TI?', 'Multiple Choice (una respuesta)', '["Una metodología de desarrollo ágil", "Un enfoque que aplica IA y analítica avanzada para detectar, diagnosticar y resolver problemas en operaciones de TI", "Un tipo de firewall", "Un estándar de cableado estructurado"]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', now(), 'Un enfoque que aplica IA y analítica avanzada para detectar, diagnosticar y resolver problemas en operaciones de TI', '["Conocimiento"]'::jsonb, 3, 1),

('GTI-C4', 'Cuestionario', 'Conocimiento', '9', '5', '¿Cuál de las siguientes es una responsabilidad típica de un Gerente de TI que actúa como estratega de IA?', 'Multiple Choice (una respuesta)', '["Diseñar solo el cableado de red", "Alinear iniciativas de IA con los objetivos estratégicos del negocio y el roadmap de TI", "Aprobar únicamente compras de laptops", "Administrar la nómina de toda la empresa"]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', now(), 'Alinear iniciativas de IA con los objetivos estratégicos del negocio y el roadmap de TI', '["Conocimiento"]'::jsonb, 3, 1),

('GTI-C5', 'Cuestionario', 'Conocimiento', '9', '5', '¿Qué caracteriza a una transformación impulsada por IA a nivel organizacional?', 'Multiple Choice (una respuesta)', '["Comprar muchas herramientas de IA sin cambiar procesos", "Implementar un único chatbot", "Rediseñar procesos clave con IA como habilitador, gestionando cambio cultural, métricas de valor y gobierno robusto", "Externalizar todo a un proveedor"]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', now(), 'Rediseñar procesos clave con IA como habilitador, gestionando cambio cultural, métricas de valor y gobierno robusto', '["Conocimiento", "Aplicación"]'::jsonb, 3, 1),

('GTI-C6', 'Cuestionario', 'Conocimiento', '9', '5', '¿Cuál de los siguientes ejemplos es un caso sencillo de uso de IA en el área de TI?', 'Multiple Choice (una respuesta)', '["Configurar manualmente todas las reglas del firewall", "Usar un chatbot para responder preguntas frecuentes de los colaboradores sobre contraseñas y accesos", "Cambiar la contraseña de los usuarios cada 90 días", "Comprar más servidores para el data center"]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', now(), 'Usar un chatbot para responder preguntas frecuentes de los colaboradores sobre contraseñas y accesos', '["Conocimiento", "Aplicación"]'::jsonb, 3, 1),

('GTI-C7', 'Cuestionario', 'Conocimiento', '9', '5', 'En una herramienta ITSM con IA, ¿qué es un caso típico de uso?', 'Multiple Choice (una respuesta)', '["Cambiar la topología de red sin aprobación", "Clasificar y priorizar tickets de incidentes de forma automática según su texto", "Aumentar las cuotas de almacenamiento a todos los usuarios", "Desinstalar software sin registro"]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', now(), 'Clasificar y priorizar tickets de incidentes de forma automática según su texto', '["Conocimiento", "Aplicación"]'::jsonb, 3, 2),

('GTI-C8', 'Cuestionario', 'Conocimiento', '9', '5', 'Si quieres usar IA para predecir picos de carga en servidores, ¿qué tipo de modelo necesitas?', 'Multiple Choice (una respuesta)', '["Un modelo de clasificación binaria", "Un modelo de segmentación de clientes", "Un modelo de series de tiempo o regresión para demanda/capacidad", "Un modelo de generación de imágenes"]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', now(), 'Un modelo de series de tiempo o regresión para demanda/capacidad', '["Conocimiento"]'::jsonb, 3, 2),

('GTI-C9', 'Cuestionario', 'Conocimiento', '9', '5', 'Si estás priorizando proyectos de IA de distintas áreas, ¿qué criterio es más estratégico?', 'Multiple Choice (una respuesta)', '["El área que más insiste", "El proveedor que ofrece más descuentos", "El impacto en objetivos clave del negocio (ingresos, costos, riesgo, experiencia de cliente) frente a la complejidad de implementación", "El proyecto más fácil técnicamente"]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', now(), 'El impacto en objetivos clave del negocio (ingresos, costos, riesgo, experiencia de cliente) frente a la complejidad de implementación', '["Conocimiento"]'::jsonb, 3, 2),

('GTI-C10', 'Cuestionario', 'Conocimiento', '9', '5', 'En términos de arquitectura, ¿qué es crítico para escalar IA en la organización?', 'Multiple Choice (una respuesta)', '["Tener múltiples silos de datos sin integración", "Depender de scripts aislados hechos por individuos", "Contar con plataforma de datos e IA reusable, gobernada y segura (MLOps, DataOps)", "Usar solo hojas de cálculo locales"]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', now(), 'Contar con plataforma de datos e IA reusable, gobernada y segura (MLOps, DataOps)', '["Conocimiento"]'::jsonb, 3, 2),

('GTI-C11', 'Cuestionario', 'Conocimiento', '9', '5', 'Al usar un asistente de IA público (como ChatGPT u otros) desde tu cuenta corporativa, ¿cuál es el riesgo principal si pegas información sensible?', 'Multiple Choice (una respuesta)', '["Que el modelo funcione más lento", "Que la información pueda salir del control de la organización o ser usada para entrenar modelos externos", "Que los correos se envíen más rápido", "Que se pierdan las licencias de software"]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', now(), 'Que la información pueda salir del control de la organización o ser usada para entrenar modelos externos', '["Conocimiento", "Estrategia", "Aplicación"]'::jsonb, 3, 2),

('GTI-C12', 'Cuestionario', 'Conocimiento', '9', '5', '¿Qué métrica refleja mejor el impacto de IA en la productividad del soporte de TI?', 'Multiple Choice (una respuesta)', '["Número total de servidores", "Presupuesto de marketing", "Tiempo medio de resolución de incidentes (MTTR)", "Número de salas de juntas"]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', now(), 'Tiempo medio de resolución de incidentes (MTTR)', '["Productividad", "Conocimiento"]'::jsonb, 3, 2),

('GTI-C13', 'Cuestionario', 'Conocimiento', '9', '5', '¿Qué indicador refleja mejor el impacto de una solución de IA en monitoreo proactivo?', 'Multiple Choice (una respuesta)', '["Cantidad de correos enviados", "Reducción de incidentes críticos no detectados o tiempo de indisponibilidad", "Número de impresoras instaladas", "Espacio físico en oficinas"]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', now(), 'Reducción de incidentes críticos no detectados o tiempo de indisponibilidad', '["Conocimiento"]'::jsonb, 3, 3),

('GTI-C14', 'Cuestionario', 'Conocimiento', '9', '5', '¿Qué papel juega la arquitectura de datos en una estrategia de IA a nivel organizacional?', 'Multiple Choice (una respuesta)', '["Es irrelevante", "Solo sirve para backup", "Es fundamental para asegurar que los datos sean accesibles, de calidad y gobernados para entrenar y operar modelos de IA", "Sirve solo para comprar más hardware"]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', now(), 'Es fundamental para asegurar que los datos sean accesibles, de calidad y gobernados para entrenar y operar modelos de IA', '["Conocimiento", "Estrategia", "Aplicación"]'::jsonb, 3, 3),

('GTI-C15', 'Cuestionario', 'Conocimiento', '9', '5', '¿Qué enfoque refleja mejor una visión responsable y sostenible de IA?', 'Multiple Choice (una respuesta)', '["Optimizar solo métricas de corto plazo", "Ignorar impacto en empleo y habilidades", "Considerar impacto en personas, empleo, ética, cumplimiento y valor de largo plazo en el diseño de iniciativas de IA", "Dejar la responsabilidad únicamente al proveedor"]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', now(), 'Considerar impacto en personas, empleo, ética, cumplimiento y valor de largo plazo en el diseño de iniciativas de IA', '["Conocimiento"]'::jsonb, 3, 3),

('GTI-C16', 'Cuestionario', 'Conocimiento', '9', '5', '¿Cuál de estas tareas es más adecuada para un asistente de IA de productividad para Gerentes de TI?', 'Multiple Choice (una respuesta)', '["Aprobación automática de todas las compras de hardware", "Generar borradores de correos para comunicar cambios de TI a usuarios finales", "Cambiar configuraciones críticas de red sin supervisión", "Definir la estrategia de negocio de la empresa"]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', now(), 'Generar borradores de correos para comunicar cambios de TI a usuarios finales', '["Productividad", "Conocimiento"]'::jsonb, 3, 3),

('GTI-C17', 'Cuestionario', 'Conocimiento', '9', '5', 'Cuando automatizas con IA la categorización de tickets, ¿qué práctica es recomendable?', 'Multiple Choice (una respuesta)', '["Confiar ciegamente en la IA", "Revisar periódicamente muestras de tickets para ajustar el modelo y las reglas", "Eliminar el registro histórico de incidentes", "Desactivar todos los reportes manuales"]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', now(), 'Revisar periódicamente muestras de tickets para ajustar el modelo y las reglas', '["Conocimiento"]'::jsonb, 3, 3),

('GTI-C18', 'Cuestionario', 'Conocimiento', '9', '5', 'En la gestión de proyectos de IA, ¿qué es una buena práctica de gobernanza de datos?', 'Multiple Choice (una respuesta)', '["Permitir que cualquier área cree sus propios repositorios sin reglas", "No registrar los orígenes de los datos", "Definir propietarios de datos, controles de acceso y políticas de calidad de datos", "Borrar logs para ahorrar espacio"]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', now(), 'Definir propietarios de datos, controles de acceso y políticas de calidad de datos', '["Conocimiento", "Estrategia", "Aplicación"]'::jsonb, 3, 3),

('GTI-C19', 'Cuestionario', 'Conocimiento', '9', '5', '¿Qué enfoque es más adecuado para abordar el riesgo regulatorio y ético de la IA a nivel empresarial?', 'Multiple Choice (una respuesta)', '["Dejar que cada área defina sus propias reglas sin coordinación", "Tener una política corporativa de IA, con roles claros, comité de revisión y lineamientos de uso responsable", "Ignorar el tema mientras no haya multas", "Delegarlo únicamente al área legal"]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', now(), 'Tener una política corporativa de IA, con roles claros, comité de revisión y lineamientos de uso responsable', '["Conocimiento", "Estrategia"]'::jsonb, 3, 4),

('GTI-C20', 'Cuestionario', 'Conocimiento', '9', '5', 'En un programa de IA transversal, ¿qué rol debería tener TI?', 'Multiple Choice (una respuesta)', '["Solo proveedor de infraestructura", "Único dueño de todos los casos de uso", "Socio estratégico que habilita plataformas, estándares, seguridad y co-lidera con las áreas de negocio", "No participar"]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', now(), 'Socio estratégico que habilita plataformas, estándares, seguridad y co-lidera con las áreas de negocio', '["Conocimiento"]'::jsonb, 3, 4),

('GTI-C21', 'Cuestionario', 'Conocimiento', '9', '5', 'Cuando una organización comienza a usar IA, ¿qué suele ser una primera inversión razonable?', 'Multiple Choice (una respuesta)', '["Comprar un data center propio exclusivo para IA", "Contratar un gran equipo de científicos de datos de inmediato", "Explorar herramientas SaaS con IA integrada en procesos ya existentes (por ejemplo, ITSM)", "Migrar todos los sistemas a IA sin análisis previo"]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', now(), 'Explorar herramientas SaaS con IA integrada en procesos ya existentes (por ejemplo, ITSM)', '["Conocimiento", "Inversión"]'::jsonb, 3, 4),

('GTI-C22', 'Cuestionario', 'Conocimiento', '9', '5', 'Si quieres justificar una pequeña inversión adicional en IA para soporte, ¿qué argumento es más adecuado?', 'Multiple Choice (una respuesta)', '["Es una tecnología de moda", "Lo pide el proveedor", "Podemos reducir tiempos de respuesta y liberar horas del equipo de soporte para tareas de mayor valor", "Porque lo tiene la competencia"]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', now(), 'Podemos reducir tiempos de respuesta y liberar horas del equipo de soporte para tareas de mayor valor', '["Conocimiento", "Inversión"]'::jsonb, 3, 4),

('GTI-C23', 'Cuestionario', 'Conocimiento', '9', '5', 'Si evalúas invertir en una solución de IA de monitoreo, ¿qué enfoque de análisis de inversión es más adecuado?', 'Multiple Choice (una respuesta)', '["Mirar solo el costo de licencias", "Calcular también el costo de incidentes evitados, reducción de horas extra y mejoras en SLA", "Decidir únicamente por recomendación del proveedor", "Elegir la solución más cara"]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', now(), 'Calcular también el costo de incidentes evitados, reducción de horas extra y mejoras en SLA', '["Conocimiento", "Inversión"]'::jsonb, 3, 4),

('GTI-C24', 'Cuestionario', 'Conocimiento', '9', '5', 'Al armar el business case de un programa de IA empresarial, ¿qué debería incluirse?', 'Multiple Choice (una respuesta)', '["Solo el costo de licencias", "Solo beneficios cualitativos", "Costos (licencias, implementación, cambio cultural) y beneficios cuantitativos y cualitativos (eficiencias, ingresos adicionales, reducción de riesgos)", "Exclusivamente el benchmark de la competencia"]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', now(), 'Costos (licencias, implementación, cambio cultural) y beneficios cuantitativos y cualitativos (eficiencias, ingresos adicionales, reducción de riesgos)', '["Conocimiento"]'::jsonb, 3, 4),

('GTI-C25', 'Cuestionario', 'Conocimiento', '9', '5', '¿Cuál es una forma madura de gestionar la inversión en IA en el tiempo?', 'Multiple Choice (una respuesta)', '["Aprobar proyectos de IA caso por caso sin visión global", "Invertir fuerte solo el primer año y luego detenerse", "Gestionar un portafolio de IA con revisiones periódicas, realocando presupuesto según resultados y alineación estratégica", "Gastar todo el presupuesto anual en una sola iniciativa"]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', now(), 'Gestionar un portafolio de IA con revisiones periódicas, realocando presupuesto según resultados y alineación estratégica', '["Productividad", "Conocimiento", "Inversión"]'::jsonb, 3, 5),

('GTI-C26', 'Cuestionario', 'Conocimiento', '9', '5', 'Sobre la ética en IA, ¿cuál de las siguientes acciones es más apropiada para un Gerente de TI en una etapa inicial?', 'Multiple Choice (una respuesta)', '["Ignorar el tema y dejarlo al área legal", "Definir reglas básicas sobre qué tipo de datos se pueden compartir con herramientas de IA", "Permitir que cada usuario decida libremente", "Bloquear toda herramienta de IA sin análisis"]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', now(), 'Definir reglas básicas sobre qué tipo de datos se pueden compartir con herramientas de IA', '["Conocimiento", "Estrategia"]'::jsonb, 3, 5),

('GTI-C27', 'Cuestionario', 'Conocimiento', '9', '5', 'En términos de riesgos, ¿qué debes vigilar al introducir un chatbot de IA en soporte de TI?', 'Multiple Choice (una respuesta)', '["Que la interfaz sea colorida", "Que sea capaz de tomar decisiones financieras", "Que no entregue información sensible, ni decisiones críticas sin supervisión humana", "Que responda siempre ''No sé"]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', now(), 'Que no entregue información sensible, ni decisiones críticas sin supervisión humana', '["Conocimiento", "Estrategia"]'::jsonb, 3, 5),

('GTI-C28', 'Cuestionario', 'Conocimiento', '9', '5', 'Respecto a los riesgos, ¿qué es crítico al desplegar IA que toma acciones automáticas en infraestructura?', 'Multiple Choice (una respuesta)', '["Que el modelo tenga una interfaz atractiva", "Que no exista forma de desactivar la automatización", "Definir límites, revisiones humanas y mecanismos de rollback ante errores", "Permitir cambios irreversibles sin registro"]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', now(), 'Definir límites, revisiones humanas y mecanismos de rollback ante errores', '["Conocimiento", "Estrategia"]'::jsonb, 3, 5),

('GTI-C29', 'Cuestionario', 'Conocimiento', '9', '5', '¿Qué es importante en la colaboración TI–Negocio para iniciativas de IA?', 'Multiple Choice (una respuesta)', '["Que TI defina todo sin involucrar a las áreas usuarias", "Que solo participe el CEO", "Que haya co-diseño de casos de uso, métricas compartidas y responsables claros de valor de negocio", "Que cada área compre sus propias soluciones sin avisar"]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', now(), 'Que haya co-diseño de casos de uso, métricas compartidas y responsables claros de valor de negocio', '["Conocimiento", "Estrategia"]'::jsonb, 3, 5),

('GTI-C30', 'Cuestionario', 'Conocimiento', '9', '5', '¿Qué es un resultado clave de una estrategia de IA bien implementada en TI y el negocio?', 'Multiple Choice (una respuesta)', '["Aumento de incidencias por cambios no controlados", "Mayor opacidad en decisiones automatizadas", "Mejora medible en indicadores de negocio (costos, ingresos, riesgos) y en la experiencia de colaboradores y clientes", "Aumento de complejidad sin beneficios claros"]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', now(), 'Mejora medible en indicadores de negocio (costos, ingresos, riesgos) y en la experiencia de colaboradores y clientes', '["Conocimiento", "Estrategia"]'::jsonb, 3, 5);
