-- ============================================================================
-- PREGUNTAS PARA DIRECCIÓN DE OPERACIONES
-- ============================================================================
-- Rol incluido:
--   - Rol ID 12: Dirección de Operaciones (area_id: 4, nivel_id: 2)
-- ============================================================================

-- ============================================================================
-- ROL 12: Dirección de Operaciones
-- ============================================================================

-- ADOPCIÓN - Rol 12
INSERT INTO "public"."preguntas" ("codigo", "section", "bloque", "area_id", "exclusivo_rol_id", "texto", "tipo", "opciones", "locale", "peso", "escala", "scoring", "created_at", "respuesta_correcta", "dimension", "exclusivo_nivel_id", "dificultad") VALUES
('DO-A1', 'Cuestionario', 'Adopción', '4', '12', 'En tu rol, ¿con qué frecuencia revisas oportunidades de aplicar IA en procesos operativos (demanda, inventario, capacidad)?', 'Multiple Choice (escala Likert A–E)', '["Nunca", "Rara vez (≤ 1/mes)", "Ocasional (2–3/mes)", "Frecuente (semanal)", "Casi siempre/Siempre"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', now(), null, '["Aplicación"]'::jsonb, 2, 1),

('DO-A2', 'Cuestionario', 'Adopción', '4', '12', '¿Con qué frecuencia utilizas alguna herramienta (aunque sea básica) que incorpore IA o analítica avanzada en tus reuniones de seguimiento de KPIs operativos?', 'Multiple Choice (escala Likert A–E)', '["Nunca", "Rara vez (≤ 1/mes)", "Ocasional (2–3/mes)", "Frecuente (semanal)", "Casi siempre/Siempre"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', now(), null, '["Aplicación", "Productividad"]'::jsonb, 2, 1),

('DO-A3', 'Cuestionario', 'Adopción', '4', '12', '¿Qué tan frecuentemente impulsas pequeños pilotos de automatización o IA (por ejemplo, clasificación automática de incidencias o priorización de órdenes) en tu área?', 'Multiple Choice (escala Likert A–E)', '["Nunca", "Rara vez (≤ 1/mes)", "Ocasional (2–3/mes)", "Frecuente (semanal)", "Casi siempre/Siempre"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', now(), null, '["Aplicación"]'::jsonb, 2, 1),

('DO-A4', 'Cuestionario', 'Adopción', '4', '12', '¿Con qué frecuencia consultas a tu equipo de TI o datos para entender qué datos y soluciones de IA ya existen que puedan ayudar a operaciones?', 'Multiple Choice (escala Likert A–E)', '["Nunca", "Rara vez (≤ 1/mes)", "Ocasional (2–3/mes)", "Frecuente (semanal)", "Casi siempre/Siempre"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', now(), null, '["Aplicación"]'::jsonb, 2, 1),

('DO-A5', 'Cuestionario', 'Adopción', '4', '12', '¿Con qué frecuencia cuestionas decisiones operativas basadas sólo en intuición cuando no hay datos o modelos que las respalden?', 'Multiple Choice (escala Likert A–E)', '["Nunca", "Rara vez (≤ 1/mes)", "Ocasional (2–3/mes)", "Frecuente (semanal)", "Casi siempre/Siempre"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', now(), null, '["Aplicación"]'::jsonb, 2, 1),

('DO-A6', 'Cuestionario', 'Adopción', '4', '12', '¿Con qué frecuencia revisas los posibles riesgos (privacidad, sesgos, cumplimiento normativo) antes de aprobar un piloto de IA en operaciones?', 'Multiple Choice (escala Likert A–E)', '["Nunca", "Rara vez (≤ 1/mes)", "Ocasional (2–3/mes)", "Frecuente (semanal)", "Casi siempre/Siempre"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', now(), null, '["Estrategia"]'::jsonb, 2, 1),

('DO-A7', 'Cuestionario', 'Adopción', '4', '12', '¿Con qué frecuencia solicitas que los pilotos de IA en operaciones incluyan KPIs claros (OEE, lead time, porcentaje de entregas a tiempo) desde el diseño?', 'Multiple Choice (escala Likert A–E)', '["Nunca", "Rara vez (≤ 1/mes)", "Ocasional (2–3/mes)", "Frecuente (semanal)", "Casi siempre/Siempre"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', now(), null, '["Productividad"]'::jsonb, 2, 2),

('DO-A8', 'Cuestionario', 'Adopción', '4', '12', '¿Con qué frecuencia revisas con tu equipo lecciones aprendidas de pilotos de automatización o IA, aunque hayan sido poco exitosos?', 'Multiple Choice (escala Likert A–E)', '["Nunca", "Rara vez (≤ 1/mes)", "Ocasional (2–3/mes)", "Frecuente (semanal)", "Casi siempre/Siempre"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', now(), null, '["Aplicación"]'::jsonb, 2, 2),

('DO-A9', 'Cuestionario', 'Adopción', '4', '12', '¿Con qué frecuencia destinas tiempo en tu agenda para explorar nuevas herramientas de IA relevantes para tu operación (webinars, demos, benchmark)?', 'Multiple Choice (escala Likert A–E)', '["Nunca", "Rara vez (≤ 1/mes)", "Ocasional (2–3/mes)", "Frecuente (semanal)", "Casi siempre/Siempre"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', now(), null, '["Aplicación", "Productividad"]'::jsonb, 2, 2),

('DO-A10', 'Cuestionario', 'Adopción', '4', '12', '¿Con qué frecuencia involucras a equipos de planta u operativos en el diseño de pilotos de IA para asegurar que resuelvan problemas reales?', 'Multiple Choice (escala Likert A–E)', '["Nunca", "Rara vez (≤ 1/mes)", "Ocasional (2–3/mes)", "Frecuente (semanal)", "Casi siempre/Siempre"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', now(), null, '["Aplicación"]'::jsonb, 2, 2),

('DO-A11', 'Cuestionario', 'Adopción', '4', '12', '¿Con qué frecuencia pides a TI o datos explicaciones comprensibles de cómo funciona un modelo de IA antes de aprobar su uso operativo?', 'Multiple Choice (escala Likert A–E)', '["Nunca", "Rara vez (≤ 1/mes)", "Ocasional (2–3/mes)", "Frecuente (semanal)", "Casi siempre/Siempre"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', now(), null, '["Aplicación"]'::jsonb, 2, 2),

('DO-A12', 'Cuestionario', 'Adopción', '4', '12', '¿Con qué frecuencia priorizas presupuesto para pilotos de IA frente a otras inversiones menos estratégicas en operaciones?', 'Multiple Choice (escala Likert A–E)', '["Nunca", "Rara vez (≤ 1/mes)", "Ocasional (2–3/mes)", "Frecuente (semanal)", "Casi siempre/Siempre"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', now(), null, '["Inversión"]'::jsonb, 2, 2),

('DO-A13', 'Cuestionario', 'Adopción', '4', '12', '¿Con qué frecuencia revisas comparativamente la performance de modelos de IA frente a reglas tradicionales (baseline) antes de escalarlos?', 'Multiple Choice (escala Likert A–E)', '["Nunca", "Rara vez (≤ 1/mes)", "Ocasional (2–3/mes)", "Frecuente (semanal)", "Casi siempre/Siempre"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', now(), null, '["Aplicación"]'::jsonb, 2, 3),

('DO-A14', 'Cuestionario', 'Adopción', '4', '12', '¿Con qué frecuencia solicitas que las decisiones críticas (por ejemplo, asignación de capacidad o priorización de órdenes clave) incluyan la recomendación del modelo y el criterio del responsable humano?', 'Multiple Choice (escala Likert A–E)', '["Nunca", "Rara vez (≤ 1/mes)", "Ocasional (2–3/mes)", "Frecuente (semanal)", "Casi siempre/Siempre"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', now(), null, '["Aplicación"]'::jsonb, 2, 3),

('DO-A15', 'Cuestionario', 'Adopción', '4', '12', '¿Con qué frecuencia alineas con Finanzas y TI un caso de negocio para escalar un caso de uso de IA probado en un área a otras plantas o regiones?', 'Multiple Choice (escala Likert A–E)', '["Nunca", "Rara vez (≤ 1/mes)", "Ocasional (2–3/mes)", "Frecuente (semanal)", "Casi siempre/Siempre"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', now(), null, '["Aplicación"]'::jsonb, 2, 3),

('DO-A16', 'Cuestionario', 'Adopción', '4', '12', '¿Con qué frecuencia involucras a usuarios finales (jefes de planta, supervisores) en la mejora continua de herramientas de IA que ya usan?', 'Multiple Choice (escala Likert A–E)', '["Nunca", "Rara vez (≤ 1/mes)", "Ocasional (2–3/mes)", "Frecuente (semanal)", "Casi siempre/Siempre"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', now(), null, '["Aplicación"]'::jsonb, 2, 3),

('DO-A17', 'Cuestionario', 'Adopción', '4', '12', '¿Con qué frecuencia revisas alertas de drift o deterioro de modelos junto con el equipo técnico para decidir recalibraciones?', 'Multiple Choice (escala Likert A–E)', '["Nunca", "Rara vez (≤ 1/mes)", "Ocasional (2–3/mes)", "Frecuente (semanal)", "Casi siempre/Siempre"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', now(), null, '["Aplicación"]'::jsonb, 2, 3),

('DO-A18', 'Cuestionario', 'Adopción', '4', '12', '¿Con qué frecuencia evalúas riesgos reputacionales o regulatorios antes de liberar modelos de IA que afectan a clientes (tiempos de entrega, asignación de stock, etc.)?', 'Multiple Choice (escala Likert A–E)', '["Nunca", "Rara vez (≤ 1/mes)", "Ocasional (2–3/mes)", "Frecuente (semanal)", "Casi siempre/Siempre"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', now(), null, '["Estrategia", "Productividad"]'::jsonb, 2, 3),

('DO-A19', 'Cuestionario', 'Adopción', '4', '12', '¿Con qué frecuencia revisas el portafolio de casos de uso de IA en operaciones y reasignas recursos según impacto real y aprendizajes?', 'Multiple Choice (escala Likert A–E)', '["Nunca", "Rara vez (≤ 1/mes)", "Ocasional (2–3/mes)", "Frecuente (semanal)", "Casi siempre/Siempre"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', now(), null, '["Aplicación"]'::jsonb, 2, 4),

('DO-A20', 'Cuestionario', 'Adopción', '4', '12', '¿Con qué frecuencia integras recomendaciones de IA en tus rutinas de gestión (reuniones diarias o semanales de operaciones, S&OP, etc.) como parte estándar de la discusión?', 'Multiple Choice (escala Likert A–E)', '["Nunca", "Rara vez (≤ 1/mes)", "Ocasional (2–3/mes)", "Frecuente (semanal)", "Casi siempre/Siempre"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', now(), null, '["Aplicación"]'::jsonb, 2, 4),

('DO-A21', 'Cuestionario', 'Adopción', '4', '12', '¿Con qué frecuencia pides que las soluciones de IA incluyan explicaciones comprensibles para los usuarios clave (por qué recomienda cierto plan de producción, ruta, etc.)?', 'Multiple Choice (escala Likert A–E)', '["Nunca", "Rara vez (≤ 1/mes)", "Ocasional (2–3/mes)", "Frecuente (semanal)", "Casi siempre/Siempre"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', now(), null, '["Aplicación"]'::jsonb, 2, 4),

('DO-A22', 'Cuestionario', 'Adopción', '4', '12', '¿Con qué frecuencia promueves espacios de co-diseño (workshops) entre operaciones, TI o datos y otras áreas (comercial, finanzas) para nuevos casos de uso de IA?', 'Multiple Choice (escala Likert A–E)', '["Nunca", "Rara vez (≤ 1/mes)", "Ocasional (2–3/mes)", "Frecuente (semanal)", "Casi siempre/Siempre"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', now(), null, '["Aplicación"]'::jsonb, 2, 4),

('DO-A23', 'Cuestionario', 'Adopción', '4', '12', '¿Con qué frecuencia utilizas simulaciones con modelos de IA (por ejemplo, gemelo digital) para evaluar decisiones estratégicas de capacidad o red logística?', 'Multiple Choice (escala Likert A–E)', '["Nunca", "Rara vez (≤ 1/mes)", "Ocasional (2–3/mes)", "Frecuente (semanal)", "Casi siempre/Siempre"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', now(), null, '["Aplicación"]'::jsonb, 2, 4),

('DO-A24', 'Cuestionario', 'Adopción', '4', '12', '¿Con qué frecuencia revisas junto con RRHH y Legal los impactos de la IA en roles, competencias y posibles riesgos laborales en operaciones?', 'Multiple Choice (escala Likert A–E)', '["Nunca", "Rara vez (≤ 1/mes)", "Ocasional (2–3/mes)", "Frecuente (semanal)", "Casi siempre/Siempre"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', now(), null, '["Estrategia"]'::jsonb, 2, 4),

('DO-A25', 'Cuestionario', 'Adopción', '4', '12', '¿Con qué frecuencia impulsas rediseños completos de procesos (no sólo automatización) para aprovechar al máximo capacidades de IA (por ejemplo, planificación continua y decisiones en tiempo real)?', 'Multiple Choice (escala Likert A–E)', '["Nunca", "Rara vez (≤ 1/mes)", "Ocasional (2–3/mes)", "Frecuente (semanal)", "Casi siempre/Siempre"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', now(), null, '["Estrategia", "Productividad"]'::jsonb, 2, 5),

('DO-A26', 'Cuestionario', 'Adopción', '4', '12', '¿Con qué frecuencia integras métricas de valor de IA (ROI, payback, impacto en margen y capital de trabajo) en los tableros ejecutivos de operaciones?', 'Multiple Choice (escala Likert A–E)', '["Nunca", "Rara vez (≤ 1/mes)", "Ocasional (2–3/mes)", "Frecuente (semanal)", "Casi siempre/Siempre"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', now(), null, '["Inversión", "Productividad"]'::jsonb, 2, 5),

('DO-A27', 'Cuestionario', 'Adopción', '4', '12', '¿Con qué frecuencia participas en decisiones corporativas sobre el ecosistema de IA (proveedores, plataformas, talento crítico) más allá del ámbito puramente operativo?', 'Multiple Choice (escala Likert A–E)', '["Nunca", "Rara vez (≤ 1/mes)", "Ocasional (2–3/mes)", "Frecuente (semanal)", "Casi siempre/Siempre"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', now(), null, '["Aplicación"]'::jsonb, 2, 5),

('DO-A28', 'Cuestionario', 'Adopción', '4', '12', '¿Con qué frecuencia promueves programas de upskilling o reskilling en IA para mandos medios y equipos operativos bajo tu responsabilidad?', 'Multiple Choice (escala Likert A–E)', '["Nunca", "Rara vez (≤ 1/mes)", "Ocasional (2–3/mes)", "Frecuente (semanal)", "Casi siempre/Siempre"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', now(), null, '["Aplicación"]'::jsonb, 2, 5),

('DO-A29', 'Cuestionario', 'Adopción', '4', '12', '¿Con qué frecuencia haces revisar modelos de IA críticos por terceros (auditorías técnicas, de sesgos, de seguridad) antes de escalar su uso?', 'Multiple Choice (escala Likert A–E)', '["Nunca", "Rara vez (≤ 1/mes)", "Ocasional (2–3/mes)", "Frecuente (semanal)", "Casi siempre/Siempre"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', now(), null, '["Aplicación", "Estrategia"]'::jsonb, 2, 5),

('DO-A30', 'Cuestionario', 'Adopción', '4', '12', '¿Con qué frecuencia comunicas a toda la organización la visión de una operación habilitada por IA, conectando casos de uso concretos con la estrategia corporativa?', 'Multiple Choice (escala Likert A–E)', '["Nunca", "Rara vez (≤ 1/mes)", "Ocasional (2–3/mes)", "Frecuente (semanal)", "Casi siempre/Siempre"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', now(), null, '["Aplicación", "Estrategia"]'::jsonb, 2, 5);

-- CONOCIMIENTO - Rol 12
INSERT INTO "public"."preguntas" ("codigo", "section", "bloque", "area_id", "exclusivo_rol_id", "texto", "tipo", "opciones", "locale", "peso", "escala", "scoring", "created_at", "respuesta_correcta", "dimension", "exclusivo_nivel_id", "dificultad") VALUES
('DO-C1', 'Cuestionario', 'Conocimiento', '4', '12', '¿Cuál es la mejor definición de inteligencia artificial aplicada a operaciones?', 'Multiple Choice (una respuesta)', '["Software que reemplaza completamente a los gerentes de operaciones", "Herramientas que analizan datos para apoyar decisiones y automatizar partes del proceso", "Robots físicos que realizan tareas manuales en planta", "Cualquier sistema de reportes históricos en Excel"]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', now(), 'Herramientas que analizan datos para apoyar decisiones y automatizar partes del proceso', '["Aplicación", "Conocimiento"]'::jsonb, 2, 1),

('DO-C2', 'Cuestionario', 'Conocimiento', '4', '12', '¿Qué diferencia principal hay entre automatización tradicional (reglas) e IA?', 'Multiple Choice (una respuesta)', '["La automatización sólo funciona en fábricas, la IA sólo en oficinas", "La automatización sigue reglas fijas; la IA aprende patrones a partir de datos", "La automatización es más cara que la IA en todos los casos", "No hay diferencia relevante"]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', now(), 'La automatización sigue reglas fijas; la IA aprende patrones a partir de datos', '["Conocimiento"]'::jsonb, 2, 1),

('DO-C3', 'Cuestionario', 'Conocimiento', '4', '12', '¿Cuál de los siguientes es un caso de uso de IA típico para Dirección de Operaciones?', 'Multiple Choice (una respuesta)', '["Elaborar únicamente encuestas de clima laboral", "Pronosticar demanda con modelos que se actualizan automáticamente con datos históricos y variables externas", "Cambiar manualmente los turnos cada semana", "Firmar contratos con proveedores"]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', now(), 'Pronosticar demanda con modelos que se actualizan automáticamente con datos históricos y variables externas', '["Aplicación", "Conocimiento"]'::jsonb, 2, 1),

('DO-C4', 'Cuestionario', 'Conocimiento', '4', '12', 'Para que un modelo de IA de pronóstico de demanda funcione bien, ¿qué es más crítico?', 'Multiple Choice (una respuesta)', '["Tener el ERP más caro del mercado", "Contar con datos históricos de ventas limpios y variables relevantes (promociones, temporadas, etc.)", "Tener el piso de planta totalmente automatizado", "Reducir el número de proveedores"]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', now(), 'Contar con datos históricos de ventas limpios y variables relevantes (promociones, temporadas, etc.)', '["Conocimiento"]'::jsonb, 2, 1),

('DO-C5', 'Cuestionario', 'Conocimiento', '4', '12', '¿Qué describe mejor el concepto de mantenimiento predictivo con IA?', 'Multiple Choice (una respuesta)', '["Reparar equipos únicamente cuando fallan", "Cambiar componentes en fechas fijas sin analizar el uso real", "Usar datos de sensores y modelos para anticipar fallas y programar intervenciones", "Tercerizar todo el mantenimiento a un proveedor"]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', now(), 'Usar datos de sensores y modelos para anticipar fallas y programar intervenciones', '["Conocimiento"]'::jsonb, 2, 1),

('DO-C6', 'Cuestionario', 'Conocimiento', '4', '12', '¿Cuál es un riesgo ético relevante al usar IA en la planificación de turnos de personal?', 'Multiple Choice (una respuesta)', '["No cumplir con el presupuesto de TI", "Asignar turnos de manera sistemáticamente injusta a ciertos grupos de personas", "Disminuir el uso de hojas de cálculo", "Reducir el número de reportes impresos"]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', now(), 'Asignar turnos de manera sistemáticamente injusta a ciertos grupos de personas', '["Estrategia", "Conocimiento"]'::jsonb, 2, 1),

('DO-C7', 'Cuestionario', 'Conocimiento', '4', '12', '¿Cuál es una buena práctica al iniciar un piloto de IA en operaciones?', 'Multiple Choice (una respuesta)', '["Implementar la solución en toda la empresa desde el día uno", "Definir métricas claras de éxito (por ejemplo, reducción de mermas o lead time) y un alcance acotado", "Delegar todo al proveedor sin involucrar al equipo interno", "No comunicar nada al resto de áreas"]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', now(), 'Definir métricas claras de éxito (por ejemplo, reducción de mermas o lead time) y un alcance acotado', '["Conocimiento"]'::jsonb, 2, 2),

('DO-C8', 'Cuestionario', 'Conocimiento', '4', '12', '¿Qué es un caso de uso de IA en el contexto de Dirección de Operaciones?', 'Multiple Choice (una respuesta)', '["Cualquier iniciativa de TI", "Un problema operativo concreto donde la IA puede generar valor medible", "Un cambio en la estructura organizacional", "Un nuevo proveedor de materia prima"]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', now(), 'Un problema operativo concreto donde la IA puede generar valor medible', '["Aplicación", "Conocimiento"]'::jsonb, 2, 2),

('DO-C9', 'Cuestionario', 'Conocimiento', '4', '12', '¿Qué ventaja clave tiene usar IA para el pronóstico de demanda frente a un promedio móvil simple?', 'Multiple Choice (una respuesta)', '["Permite ignorar datos históricos", "Permite incorporar múltiples variables (promociones, clima, canales, etc.) y aprender patrones complejos", "Es siempre más barata", "Elimina la necesidad de supervisión humana"]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', now(), 'Permite incorporar múltiples variables (promociones, clima, canales, etc.) y aprender patrones complejos', '["Conocimiento"]'::jsonb, 2, 2),

('DO-C10', 'Cuestionario', 'Conocimiento', '4', '12', '¿Qué describe mejor la diferencia entre IA generativa y modelos predictivos clásicos en operaciones?', 'Multiple Choice (una respuesta)', '["La IA generativa genera texto o imágenes y los modelos predictivos generan números o probabilidades", "No hay diferencia", "La IA generativa sólo se usa en marketing", "Los modelos predictivos no se basan en datos"]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', now(), 'La IA generativa genera texto o imágenes y los modelos predictivos generan números o probabilidades', '["Conocimiento"]'::jsonb, 2, 2),

('DO-C11', 'Cuestionario', 'Conocimiento', '4', '12', '¿Qué es importante considerar al integrar un piloto de IA con el ERP existente?', 'Multiple Choice (una respuesta)', '["Que el ERP tenga el logo del proveedor de IA", "Definir interfaces de datos, seguridad y responsabilidades de mantenimiento", "Comenzar sin controles de acceso para acelerar la adopción", "Evitar cualquier documentación"]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', now(), 'Definir interfaces de datos, seguridad y responsabilidades de mantenimiento', '["Conocimiento"]'::jsonb, 2, 2),

('DO-C12', 'Cuestionario', 'Conocimiento', '4', '12', '¿Cuál es un riesgo de depender totalmente de un proveedor de IA sin capacidades internas mínimas?', 'Multiple Choice (una respuesta)', '["Reducir la carga de trabajo del equipo", "Quedar expuestos a altos costos y baja capacidad de cuestionar la solución", "Tener demasiadas alternativas de modelo", "Mejorar la negociación de contratos"]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', now(), 'Quedar expuestos a altos costos y baja capacidad de cuestionar la solución', '["Estrategia", "Conocimiento"]'::jsonb, 2, 2),

('DO-C13', 'Cuestionario', 'Conocimiento', '4', '12', '¿Qué indicador es más adecuado para evaluar el impacto de un modelo de IA en la planificación de inventarios?', 'Multiple Choice (una respuesta)', '["Número de correos enviados por el área", "Nivel de servicio (fill rate) y rotación u obsolescencia de inventario", "Metros cuadrados de oficina usados por el equipo", "Número de reportes impresos"]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', now(), 'Nivel de servicio (fill rate) y rotación u obsolescencia de inventario', '["Estrategia", "Conocimiento"]'::jsonb, 2, 3),

('DO-C14', 'Cuestionario', 'Conocimiento', '4', '12', '¿Qué describe mejor un gemelo digital en operaciones?', 'Multiple Choice (una respuesta)', '["La copia de seguridad del ERP", "Una representación virtual de la operación que permite simular escenarios con IA", "Un tablero de Excel con macros", "Un reporte mensual de producción"]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', now(), 'Una representación virtual de la operación que permite simular escenarios con IA', '["Conocimiento"]'::jsonb, 2, 3),

('DO-C15', 'Cuestionario', 'Conocimiento', '4', '12', 'En un proyecto de IA para optimizar rutas logísticas, ¿qué dato es más crítico además de direcciones y tiempos históricos?', 'Multiple Choice (una respuesta)', '["Modelo de vehículo del director", "Restricciones operativas (ventanas horarias, capacidades, prioridades de cliente)", "Color de los camiones", "Tamaño de la oficina logística"]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', now(), 'Restricciones operativas (ventanas horarias, capacidades, prioridades de cliente)', '["Conocimiento", "Productividad"]'::jsonb, 2, 3),

('DO-C16', 'Cuestionario', 'Conocimiento', '4', '12', '¿Qué implica una gobernanza de datos adecuada para IA en operaciones?', 'Multiple Choice (una respuesta)', '["Permitir que cualquiera cambie datos maestros", "Roles claros, calidad de datos, políticas de acceso y trazabilidad", "Uso intensivo de correos masivos", "Rotar constantemente de proveedor de IA"]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', now(), 'Roles claros, calidad de datos, políticas de acceso y trazabilidad', '["Aplicación", "Estrategia", "Conocimiento"]'::jsonb, 2, 3),

('DO-C17', 'Cuestionario', 'Conocimiento', '4', '12', '¿Qué es drift en un modelo de IA usado para pronóstico de demanda o clasificación de pedidos?', 'Multiple Choice (una respuesta)', '["El tiempo de respuesta del servidor", "El deterioro del desempeño del modelo cuando cambia el comportamiento de los datos", "El costo de licenciamiento", "Un tipo de algoritmo supervisado"]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', now(), 'El deterioro del desempeño del modelo cuando cambia el comportamiento de los datos', '["Conocimiento"]'::jsonb, 2, 3),

('DO-C18', 'Cuestionario', 'Conocimiento', '4', '12', '¿Qué debe evaluarse antes de reemplazar una decisión humana por una recomendación automática de IA en operaciones?', 'Multiple Choice (una respuesta)', '["Sólo el costo de la solución", "Riesgos, impacto en clientes o empleados y mecanismos de supervisión humana", "El número de diapositivas en la presentación", "La marca del proveedor de nube"]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', now(), 'Riesgos, impacto en clientes o empleados y mecanismos de supervisión humana', '["Conocimiento"]'::jsonb, 2, 3),

('DO-C19', 'Cuestionario', 'Conocimiento', '4', '12', '¿Qué es clave en una arquitectura de datos para soportar múltiples casos de uso de IA en operaciones?', 'Multiple Choice (una respuesta)', '["Tener muchos dashboards desconectados", "Plataformas integradas (data lake o warehouse), calidad de datos y APIs entre sistemas", "Depender sólo del ERP estándar", "Usar únicamente archivos locales"]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', now(), 'Plataformas integradas (data lake o warehouse), calidad de datos y APIs entre sistemas', '["Aplicación", "Conocimiento"]'::jsonb, 2, 4),

('DO-C20', 'Cuestionario', 'Conocimiento', '4', '12', '¿Qué rol cumple un product owner de un caso de uso de IA en operaciones?', 'Multiple Choice (una respuesta)', '["Programar modelos de IA", "Representar al negocio, priorizar el backlog y asegurar valor de negocio", "Aprobar todos los gastos de TI", "Hacer soporte de primer nivel"]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', now(), 'Representar al negocio, priorizar el backlog y asegurar valor de negocio', '["Aplicación", "Conocimiento"]'::jsonb, 2, 4),

('DO-C21', 'Cuestionario', 'Conocimiento', '4', '12', '¿Qué es una métrica adecuada para evaluar adopción de una herramienta de IA en operaciones?', 'Multiple Choice (una respuesta)', '["Número de correos enviados sobre el proyecto", "Porcentaje de decisiones clave que usan la recomendación del sistema frente a decisiones manuales", "Tamaño del budget de TI", "Número de reuniones del comité de seguimiento"]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', now(), 'Porcentaje de decisiones clave que usan la recomendación del sistema frente a decisiones manuales', '["Aplicación", "Conocimiento"]'::jsonb, 2, 4),

('DO-C22', 'Cuestionario', 'Conocimiento', '4', '12', 'En una estrategia de IA para operaciones, ¿qué elemento NO debe considerarse una estrategia suficiente por sí sola?', 'Multiple Choice (una respuesta)', '["Roadmap de casos de uso priorizado por impacto y factibilidad", "Plan de talento y capacidades (datos, tecnología, negocio)", "Gobernanza y modelo operativo claros", "Sólo la compra de una plataforma todo en uno sin cambiar procesos"]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', now(), 'Sólo la compra de una plataforma todo en uno sin cambiar procesos', '["Estrategia", "Conocimiento"]'::jsonb, 2, 4),

('DO-C23', 'Cuestionario', 'Conocimiento', '4', '12', '¿Qué describe mejor el concepto de MLOps relevante para Dirección de Operaciones?', 'Multiple Choice (una respuesta)', '["Prácticas para desplegar y mantener modelos de IA en producción de forma confiable y repetible", "Un tipo de ERP especializado en manufactura", "Un método de mejora continua sin datos", "Un estándar de seguridad física en planta"]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', now(), 'Prácticas para desplegar y mantener modelos de IA en producción de forma confiable y repetible', '["Conocimiento"]'::jsonb, 2, 4),

('DO-C24', 'Cuestionario', 'Conocimiento', '4', '12', '¿Qué riesgo estratégico existe si sólo un área de la operación usa IA y el resto no?', 'Multiple Choice (una respuesta)', '["Ninguno, es suficiente con un área", "Desalineación de decisiones, cuellos de botella y beneficios parciales", "Mayor compromiso del equipo", "Reducción automática de costos globales"]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', now(), 'Desalineación de decisiones, cuellos de botella y beneficios parciales', '["Estrategia", "Conocimiento"]'::jsonb, 2, 4),

('DO-C25', 'Cuestionario', 'Conocimiento', '4', '12', '¿Qué es un modelo operativo de operaciones IA-first?', 'Multiple Choice (una respuesta)', '["Un modelo donde la IA es un accesorio opcional", "Un modelo donde procesos, roles, datos y tecnología se diseñan asumiendo IA como núcleo de decisión", "Un modelo basado sólo en intuición", "Un modelo centrado exclusivamente en reducir headcount"]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', now(), 'Un modelo donde procesos, roles, datos y tecnología se diseñan asumiendo IA como núcleo de decisión', '["Conocimiento"]'::jsonb, 2, 5),

('DO-C26', 'Cuestionario', 'Conocimiento', '4', '12', '¿Qué componente es clave para escalar IA responsablemente en toda la cadena de valor operativa?', 'Multiple Choice (una respuesta)', '["Sólo incrementar el presupuesto de TI", "Marco de ética de IA, evaluación de impacto y mecanismos de supervisión humana", "Reducir al mínimo la documentación", "Externalizar toda la operación"]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', now(), 'Marco de ética de IA, evaluación de impacto y mecanismos de supervisión humana', '["Conocimiento"]'::jsonb, 2, 5),

('DO-C27', 'Cuestionario', 'Conocimiento', '4', '12', '¿Qué uso estratégico de IA es más relevante para una Dirección de Operaciones en nivel transformador?', 'Multiple Choice (una respuesta)', '["Diseñar nuevos modelos de servicio o producción habilitados por IA (por ejemplo, operaciones casi autónomas o plataformas de decisión en tiempo real)", "Elaborar únicamente reportes mensuales estáticos", "Automatizar un único proceso administrativo", "Implementar IA sólo en un centro piloto sin plan de escalamiento"]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', now(), 'Diseñar nuevos modelos de servicio o producción habilitados por IA (por ejemplo, operaciones casi autónomas o plataformas de decisión en tiempo real)', '["Aplicación", "Conocimiento"]'::jsonb, 2, 5),

('DO-C28', 'Cuestionario', 'Conocimiento', '4', '12', '¿Qué es un enfoque portafolio para inversiones en IA en operaciones?', 'Multiple Choice (una respuesta)', '["Invertir en un solo caso de uso hasta que funcione", "Gestionar múltiples casos de uso con diferentes niveles de riesgo e impacto, reasignando recursos según resultados", "Repartir presupuesto de forma igualitaria sin priorización", "Depender sólo de iniciativas bottom-up"]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', now(), 'Gestionar múltiples casos de uso con diferentes niveles de riesgo e impacto, reasignando recursos según resultados', '["Conocimiento"]'::jsonb, 2, 5),

('DO-C29', 'Cuestionario', 'Conocimiento', '4', '12', '¿Qué indicador estratégico ayuda a justificar la transformación de operaciones habilitada por IA ante el comité ejecutivo?', 'Multiple Choice (una respuesta)', '["Número de modelos en producción sin considerar impacto", "Impacto consolidado en margen operativo, capital de trabajo y NPS o SLAs", "Número de reuniones sobre IA", "Cantidad de dashboards creados"]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', now(), 'Impacto consolidado en margen operativo, capital de trabajo y NPS o SLAs', '["Aplicación", "Conocimiento"]'::jsonb, 2, 5),

('DO-C30', 'Cuestionario', 'Conocimiento', '4', '12', '¿Qué riesgo sistémico debe gestionar una Dirección de Operaciones altamente dependiente de IA?', 'Multiple Choice (una respuesta)', '["Tener demasiados datos limpios", "Vulnerabilidad ante ciberataques, fallas de modelos y disrupción de proveedores críticos de IA", "Exceso de supervisión humana", "Crecimiento moderado de la empresa"]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', now(), 'Vulnerabilidad ante ciberataques, fallas de modelos y disrupción de proveedores críticos de IA', '["Estrategia", "Conocimiento"]'::jsonb, 2, 5);
