-- ============================================================================
-- PREGUNTAS PARA CMO / DIRECTOR(A) DE MARKETING
-- ============================================================================
-- Rol incluido:
--   - Rol ID 2: CMO / Director(a) de Marketing (area_id: 3, nivel_id: 2)
-- ============================================================================

-- ============================================================================
-- ROL 2: CMO / Director(a) de Marketing
-- ============================================================================

-- ADOPCIÓN - Rol 2
INSERT INTO "public"."preguntas" ("codigo", "section", "bloque", "area_id", "exclusivo_rol_id", "texto", "tipo", "opciones", "locale", "peso", "escala", "scoring", "created_at", "respuesta_correcta", "dimension", "exclusivo_nivel_id", "dificultad") VALUES
('CMO-A1', 'Cuestionario', 'Adopción', '3', '2', 'Personalmente utilizo asistentes de IA, como chatbots o copilots, para revisar o mejorar textos de marketing como correos electrónicos, publicaciones o presentaciones.', 'Multiple Choice (escala Likert A–E)', '["Nunca", "Rara vez (≤ 1/mes)", "Ocasional (2–3/mes)", "Frecuente (semanal)", "Muy frecuente (diaria)"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', now(), null, '["Aplicación"]'::jsonb, 2, 1),

('CMO-A2', 'Cuestionario', 'Adopción', '3', '2', 'En mis reuniones de marketing, suelo pedir al equipo que traiga al menos un ejemplo concreto de cómo usó IA en su trabajo reciente.', 'Multiple Choice (escala Likert A–E)', '["Nunca", "Rara vez (≤ 1/mes)", "Ocasional (2–3/mes)", "Frecuente (semanal)", "Muy frecuente (diaria)"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', now(), null, '["Aplicación"]'::jsonb, 2, 1),

('CMO-A3', 'Cuestionario', 'Adopción', '3', '2', 'Antes de aprobar una pieza generada con IA, reviso personalmente o pido que se revise su coherencia con la voz de marca.', 'Multiple Choice (escala Likert A–E)', '["Nunca", "Rara vez (≤ 1/mes)", "Ocasional (2–3/mes)", "Frecuente (semanal)", "Muy frecuente (diaria)"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', now(), null, '["Aplicación"]'::jsonb, 2, 1),

('CMO-A4', 'Cuestionario', 'Adopción', '3', '2', 'Dedico parte de mi tiempo a explorar casos de uso sencillos de IA en marketing, por ejemplo scoring básico de leads o recomendaciones automatizadas de contenidos.', 'Multiple Choice (escala Likert A–E)', '["Nunca", "Rara vez (≤ 1/mes)", "Ocasional (2–3/mes)", "Frecuente (semanal)", "Muy frecuente (diaria)"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', now(), null, '["Productividad", "Aplicación"]'::jsonb, 2, 1),

('CMO-A5', 'Cuestionario', 'Adopción', '3', '2', 'He patrocinado al menos un piloto de IA de bajo riesgo, por ejemplo generación de copys o segmentaciones simples, con un presupuesto y objetivo claros.', 'Multiple Choice (escala Likert A–E)', '["Nunca", "Rara vez (≤ 1/mes)", "Ocasional (2–3/mes)", "Frecuente (semanal)", "Muy frecuente (diaria)"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', now(), null, '["Inversión", "Estrategia"]'::jsonb, 2, 1),

('CMO-A6', 'Cuestionario', 'Adopción', '3', '2', 'En mi equipo existen, aunque sean básicos, lineamientos sobre qué información sí o no se puede introducir en herramientas de IA externas.', 'Multiple Choice (escala Likert A–E)', '["Nunca", "Rara vez (≤ 1/mes)", "Ocasional (2–3/mes)", "Frecuente (semanal)", "Muy frecuente (diaria)"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', now(), null, '["Aplicación"]'::jsonb, 2, 1),

('CMO-A7', 'Cuestionario', 'Adopción', '3', '2', 'Pido de forma sistemática a mi equipo que documente en qué campañas se usó IA y qué impacto tuvo en los indicadores clave de desempeño.', 'Multiple Choice (escala Likert A–E)', '["Nunca", "Rara vez (≤ 1/mes)", "Ocasional (2–3/mes)", "Frecuente (semanal)", "Muy frecuente (diaria)"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', now(), null, '["Aplicación"]'::jsonb, 2, 2),

('CMO-A8', 'Cuestionario', 'Adopción', '3', '2', 'Utilizo IA para explorar insights rápidos, como agrupar comentarios de clientes o reseñas, antes de una reunión de estrategia.', 'Multiple Choice (escala Likert A–E)', '["Nunca", "Rara vez (≤ 1/mes)", "Ocasional (2–3/mes)", "Frecuente (semanal)", "Muy frecuente (diaria)"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', now(), null, '["Productividad", "Estrategia"]'::jsonb, 2, 2),

('CMO-A9', 'Cuestionario', 'Adopción', '3', '2', 'He asignado un champion de IA dentro del equipo de marketing para centralizar buenas prácticas y aprendizajes.', 'Multiple Choice (escala Likert A–E)', '["Nunca", "Rara vez (≤ 1/mes)", "Ocasional (2–3/mes)", "Frecuente (semanal)", "Muy frecuente (diaria)"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', now(), null, '["Aplicación"]'::jsonb, 2, 2),

('CMO-A10', 'Cuestionario', 'Adopción', '3', '2', 'Considero explícitamente el tiempo ahorrado gracias a la IA, por ejemplo en redacción de contenidos, cuando priorizo proyectos de marketing.', 'Multiple Choice (escala Likert A–E)', '["Nunca", "Rara vez (≤ 1/mes)", "Ocasional (2–3/mes)", "Frecuente (semanal)", "Muy frecuente (diaria)"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', now(), null, '["Productividad"]'::jsonb, 2, 2),

('CMO-A11', 'Cuestionario', 'Adopción', '3', '2', 'Reviso con el área legal o de cumplimiento si los usos de IA que proponemos cumplen con regulaciones de datos y publicidad.', 'Multiple Choice (escala Likert A–E)', '["Nunca", "Rara vez (≤ 1/mes)", "Ocasional (2–3/mes)", "Frecuente (semanal)", "Muy frecuente (diaria)"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', now(), null, '["Aplicación", "Estrategia"]'::jsonb, 2, 2),

('CMO-A12', 'Cuestionario', 'Adopción', '3', '2', 'Experimento activamente con distintas herramientas de IA, tanto de texto como de imagen o analítica, para entender su potencial antes de hacer inversiones mayores.', 'Multiple Choice (escala Likert A–E)', '["Nunca", "Rara vez (≤ 1/mes)", "Ocasional (2–3/mes)", "Frecuente (semanal)", "Muy frecuente (diaria)"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', now(), null, '["Aplicación"]'::jsonb, 2, 2),

('CMO-A13', 'Cuestionario', 'Adopción', '3', '2', 'Utilizo modelos de propensión como abandono, venta cruzada o venta incremental para priorizar audiencias en campañas clave.', 'Multiple Choice (escala Likert A–E)', '["Nunca", "Rara vez (≤ 1/mes)", "Ocasional (2–3/mes)", "Frecuente (semanal)", "Muy frecuente (diaria)"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', now(), null, '["Estrategia"]'::jsonb, 2, 3),

('CMO-A14', 'Cuestionario', 'Adopción', '3', '2', 'En los comités de inversión de marketing, presento resultados diferenciando entre impacto total e impacto incremental atribuido a modelos de IA.', 'Multiple Choice (escala Likert A–E)', '["Nunca", "Rara vez (≤ 1/mes)", "Ocasional (2–3/mes)", "Frecuente (semanal)", "Muy frecuente (diaria)"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', now(), null, '["Productividad", "Inversión"]'::jsonb, 2, 3),

('CMO-A15', 'Cuestionario', 'Adopción', '3', '2', 'Coordino con las áreas de tecnología o datos para asegurar que los modelos de IA estén integrados con el CRM, las herramientas de correo y las plataformas de medios.', 'Multiple Choice (escala Likert A–E)', '["Nunca", "Rara vez (≤ 1/mes)", "Ocasional (2–3/mes)", "Frecuente (semanal)", "Muy frecuente (diaria)"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', now(), null, '["Aplicación"]'::jsonb, 2, 3),

('CMO-A16', 'Cuestionario', 'Adopción', '3', '2', 'He impulsado la creación de tableros que muestran el desempeño específico de campañas que usan IA frente a las que no la usan.', 'Multiple Choice (escala Likert A–E)', '["Nunca", "Rara vez (≤ 1/mes)", "Ocasional (2–3/mes)", "Frecuente (semanal)", "Muy frecuente (diaria)"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', now(), null, '["Aplicación"]'::jsonb, 2, 3),

('CMO-A17', 'Cuestionario', 'Adopción', '3', '2', 'Tengo criterios claros para decidir cuándo vale la pena invertir en un modelo propio frente a usar capacidades nativas de plataformas como Google o Meta.', 'Multiple Choice (escala Likert A–E)', '["Nunca", "Rara vez (≤ 1/mes)", "Ocasional (2–3/mes)", "Frecuente (semanal)", "Muy frecuente (diaria)"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', now(), null, '["Aplicación"]'::jsonb, 2, 3),

('CMO-A18', 'Cuestionario', 'Adopción', '3', '2', 'Discuto regularmente con las áreas de legal, cumplimiento y experiencia de cliente los límites de personalización aceptables para la marca cuando usamos IA.', 'Multiple Choice (escala Likert A–E)', '["Nunca", "Rara vez (≤ 1/mes)", "Ocasional (2–3/mes)", "Frecuente (semanal)", "Muy frecuente (diaria)"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', now(), null, '["Estrategia"]'::jsonb, 2, 3),

('CMO-A19', 'Cuestionario', 'Adopción', '3', '2', 'Utilizo modelos de atribución avanzados que incluyen IA para redistribuir presupuesto entre canales de manera recurrente.', 'Multiple Choice (escala Likert A–E)', '["Nunca", "Rara vez (≤ 1/mes)", "Ocasional (2–3/mes)", "Frecuente (semanal)", "Muy frecuente (diaria)"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', now(), null, '["Inversión"]'::jsonb, 2, 4),

('CMO-A20', 'Cuestionario', 'Adopción', '3', '2', 'Trabajo con las áreas de datos o TI para definir un roadmap claro de capacidades de IA de marketing, incluyendo modelos, integraciones y herramientas.', 'Multiple Choice (escala Likert A–E)', '["Nunca", "Rara vez (≤ 1/mes)", "Ocasional (2–3/mes)", "Frecuente (semanal)", "Muy frecuente (diaria)"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', now(), null, '["Aplicación", "Estrategia"]'::jsonb, 2, 4),

('CMO-A21', 'Cuestionario', 'Adopción', '3', '2', 'Tengo establecidos indicadores de calidad de datos como completitud, consistencia y frescura, y los reviso en comités periódicos relacionados con IA y marketing.', 'Multiple Choice (escala Likert A–E)', '["Nunca", "Rara vez (≤ 1/mes)", "Ocasional (2–3/mes)", "Frecuente (semanal)", "Muy frecuente (diaria)"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', now(), null, '["Aplicación"]'::jsonb, 2, 4),

('CMO-A22', 'Cuestionario', 'Adopción', '3', '2', 'En las discusiones con el consejo directivo, presento escenarios de inversión basados en simulaciones de IA, por ejemplo qué pasa si aumento cierta proporción de inversión en televisión frente a medios digitales.', 'Multiple Choice (escala Likert A–E)', '["Nunca", "Rara vez (≤ 1/mes)", "Ocasional (2–3/mes)", "Frecuente (semanal)", "Muy frecuente (diaria)"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', now(), null, '["Inversión"]'::jsonb, 2, 4),

('CMO-A23', 'Cuestionario', 'Adopción', '3', '2', 'He impulsado programas de desarrollo de habilidades para que el equipo de marketing entienda qué hacen los modelos de IA, qué no hacen y cómo cuestionarlos de forma informada.', 'Multiple Choice (escala Likert A–E)', '["Nunca", "Rara vez (≤ 1/mes)", "Ocasional (2–3/mes)", "Frecuente (semanal)", "Muy frecuente (diaria)"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', now(), null, '["Aplicación"]'::jsonb, 2, 4),

('CMO-A24', 'Cuestionario', 'Adopción', '3', '2', 'Participo en la definición de políticas corporativas de IA sobre uso aceptable, transparencia hacia clientes y gestión de sesgos en iniciativas de marketing y experiencia de cliente.', 'Multiple Choice (escala Likert A–E)', '["Nunca", "Rara vez (≤ 1/mes)", "Ocasional (2–3/mes)", "Frecuente (semanal)", "Muy frecuente (diaria)"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', now(), null, '["Aplicación", "Estrategia"]'::jsonb, 2, 4),

('CMO-A25', 'Cuestionario', 'Adopción', '3', '2', 'Colidero junto con responsables como CIO o director de datos un comité o consejo de IA que define prioridades, riesgos y métricas clave para toda la organización.', 'Multiple Choice (escala Likert A–E)', '["Nunca", "Rara vez (≤ 1/mes)", "Ocasional (2–3/mes)", "Frecuente (semanal)", "Muy frecuente (diaria)"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', now(), null, '["Productividad", "Aplicación", "Estrategia"]'::jsonb, 2, 5),

('CMO-A26', 'Cuestionario', 'Adopción', '3', '2', 'Uso modelos de IA para evaluar y simular diferentes estrategias de crecimiento, como nuevos productos, mercados o canales, antes de presentarlas al consejo directivo.', 'Multiple Choice (escala Likert A–E)', '["Nunca", "Rara vez (≤ 1/mes)", "Ocasional (2–3/mes)", "Frecuente (semanal)", "Muy frecuente (diaria)"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', now(), null, '["Aplicación", "Estrategia"]'::jsonb, 2, 5),

('CMO-A27', 'Cuestionario', 'Adopción', '3', '2', 'He impulsado cambios organizacionales en roles, estructuras e incentivos para que la toma de decisiones en marketing sea consistentemente basada en datos y modelos de IA.', 'Multiple Choice (escala Likert A–E)', '["Nunca", "Rara vez (≤ 1/mes)", "Ocasional (2–3/mes)", "Frecuente (semanal)", "Muy frecuente (diaria)"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', now(), null, '["Aplicación"]'::jsonb, 2, 5),

('CMO-A28', 'Cuestionario', 'Adopción', '3', '2', 'El portafolio de proyectos de IA en marketing está priorizado con criterios claros de impacto esperado, complejidad y riesgos, y se revisa de forma periódica.', 'Multiple Choice (escala Likert A–E)', '["Nunca", "Rara vez (≤ 1/mes)", "Ocasional (2–3/mes)", "Frecuente (semanal)", "Muy frecuente (diaria)"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', now(), null, '["Estrategia"]'::jsonb, 2, 5),

('CMO-A29', 'Cuestionario', 'Adopción', '3', '2', 'Incorporo activamente la voz del cliente, tanto datos cualitativos como cuantitativos, en el diseño y evaluación de soluciones de IA, por ejemplo mediante pruebas de usabilidad o estudios de percepción.', 'Multiple Choice (escala Likert A–E)', '["Nunca", "Rara vez (≤ 1/mes)", "Ocasional (2–3/mes)", "Frecuente (semanal)", "Muy frecuente (diaria)"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', now(), null, '["Aplicación"]'::jsonb, 2, 5),

('CMO-A30', 'Cuestionario', 'Adopción', '3', '2', 'Comunico de forma clara y realista, tanto interna como externamente, qué hace y qué no hace nuestra IA en marketing, evitando generar expectativas exageradas o hype injustificado.', 'Multiple Choice (escala Likert A–E)', '["Nunca", "Rara vez (≤ 1/mes)", "Ocasional (2–3/mes)", "Frecuente (semanal)", "Muy frecuente (diaria)"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', now(), null, '["Aplicación"]'::jsonb, 2, 5);

-- CONOCIMIENTO - Rol 2
INSERT INTO "public"."preguntas" ("codigo", "section", "bloque", "area_id", "exclusivo_rol_id", "texto", "tipo", "opciones", "locale", "peso", "escala", "scoring", "created_at", "respuesta_correcta", "dimension", "exclusivo_nivel_id", "dificultad") VALUES
('CMO-C1', 'Cuestionario', 'Conocimiento', '3', '2', '¿Cuál de las siguientes opciones describe mejor qué es la inteligencia artificial aplicada al marketing?', 'Multiple Choice (una respuesta)', '["Es cualquier software de diseño gráfico", "Es el uso de datos y algoritmos para automatizar tareas y tomar decisiones de marketing de forma más inteligente", "Es únicamente la generación de imágenes y videos", "Es una herramienta para reemplazar completamente al equipo de marketing"]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', now(), 'Es el uso de datos y algoritmos para automatizar tareas y tomar decisiones de marketing de forma más inteligente', '["Conocimiento", "Aplicación"]'::jsonb, 2, 1),

('CMO-C2', 'Cuestionario', 'Conocimiento', '3', '2', 'Un ejemplo sencillo de uso de IA en marketing digital es:', 'Multiple Choice (una respuesta)', '["Enviar un mailing manual a toda la base de datos sin segmentar", "Programar publicaciones en redes sociales sin analizar resultados", "Usar una herramienta que recomiende automáticamente la mejor hora para enviar un email en función del comportamiento histórico de los usuarios", "Diseñar el logo de la empresa con un diseñador externo"]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', now(), 'Usar una herramienta que recomiende automáticamente la mejor hora para enviar un email en función del comportamiento histórico de los usuarios', '["Conocimiento", "Aplicación"]'::jsonb, 2, 1),

('CMO-C3', 'Cuestionario', 'Conocimiento', '3', '2', '¿Qué ventaja principal ofrece un asistente de IA generativa, como un chatbot, para un CMO?', 'Multiple Choice (una respuesta)', '["Garantiza que todas las ideas creativas serán exitosas", "Reduce la necesidad de medir resultados", "Acelera la generación de borradores de textos, ideas y briefings que luego el equipo puede refinar", "Sustituye completamente a las agencias creativas"]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', now(), 'Acelera la generación de borradores de textos, ideas y briefings que luego el equipo puede refinar', '["Conocimiento"]'::jsonb, 2, 1),

('CMO-C4', 'Cuestionario', 'Conocimiento', '3', '2', '¿Cuál de estas tareas es más adecuada para iniciar un piloto básico de IA en marketing?', 'Multiple Choice (una respuesta)', '["Redefinir por completo el modelo de negocio de la empresa", "Automatizar la generación de asuntos de email y variaciones de anuncios para pruebas A/B", "Cambiar el ERP de la compañía", "Externalizar todo el marketing a una consultora"]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', now(), 'Automatizar la generación de asuntos de email y variaciones de anuncios para pruebas A/B', '["Conocimiento"]'::jsonb, 2, 1),

('CMO-C5', 'Cuestionario', 'Conocimiento', '3', '2', '¿Cuál es un riesgo común al usar IA generativa para contenidos de marca?', 'Multiple Choice (una respuesta)', '["Que genere contenidos demasiado originales", "Que todo el contenido sea siempre legal por defecto", "Que produzca información incorrecta o sesgada que afecte la reputación de la marca", "Que elimine la necesidad de revisar el contenido"]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', now(), 'Que produzca información incorrecta o sesgada que afecte la reputación de la marca', '["Conocimiento", "Estrategia"]'::jsonb, 2, 1),

('CMO-C6', 'Cuestionario', 'Conocimiento', '3', '2', 'Cuando una plataforma como Meta Ads sugiere una audiencia similar basada en tus mejores clientes, ¿qué está usando principalmente?', 'Multiple Choice (una respuesta)', '["IA y modelos predictivos entrenados con tus datos", "Una selección aleatoria de usuarios", "Únicamente criterio manual del equipo interno", "Solo la edad y el género del público"]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', now(), 'IA y modelos predictivos entrenados con tus datos', '["Conocimiento"]'::jsonb, 2, 1),

('CMO-C7', 'Cuestionario', 'Conocimiento', '3', '2', '¿Cuál de estas es una buena práctica al usar IA generativa para redactar anuncios?', 'Multiple Choice (una respuesta)', '["Usar siempre la primera versión generada", "Prohibir por completo su uso", "Ajustar el prompt con contexto de marca, público objetivo y tono, y luego editar el resultado", "Pedir textos sin ninguna instrucción para ser más creativos"]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', now(), 'Ajustar el prompt con contexto de marca, público objetivo y tono, y luego editar el resultado', '["Conocimiento"]'::jsonb, 2, 2),

('CMO-C8', 'Cuestionario', 'Conocimiento', '3', '2', 'Una diferencia clave entre automatización de marketing tradicional e IA es que la IA:', 'Multiple Choice (una respuesta)', '["Solo envía emails más rápido", "Aprende de los datos y puede mejorar sus recomendaciones con el tiempo", "Evita la necesidad de definir objetivos de campaña", "Reemplaza al CRM"]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', now(), 'Aprende de los datos y puede mejorar sus recomendaciones con el tiempo', '["Conocimiento"]'::jsonb, 2, 2),

('CMO-C9', 'Cuestionario', 'Conocimiento', '3', '2', '¿Cuál es un ejemplo de prompt bien formulado para un CMO?', 'Multiple Choice (una respuesta)', '["Haz marketing", "Escribe cualquier cosa sobre nuestra marca", "Genera tres variantes de anuncio para una campaña de retención, tono cercano, para clientes que llevan tres meses inactivos, en formato de texto corto", "Dame ideas"]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', now(), 'Genera tres variantes de anuncio para una campaña de retención, tono cercano, para clientes que llevan tres meses inactivos, en formato de texto corto', '["Conocimiento"]'::jsonb, 2, 2),

('CMO-C10', 'Cuestionario', 'Conocimiento', '3', '2', '¿Qué indicador es más relevante para evaluar si la IA está mejorando la performance de anuncios?', 'Multiple Choice (una respuesta)', '["Número de reuniones internas", "Costo por adquisición o retorno de la inversión publicitaria", "Cantidad de creatividades generadas", "Número de prompts usados"]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', now(), 'Costo por adquisición o retorno de la inversión publicitaria', '["Conocimiento"]'::jsonb, 2, 2),

('CMO-C11', 'Cuestionario', 'Conocimiento', '3', '2', '¿Qué riesgo se corre si el equipo copia y pega datos sensibles de clientes en herramientas de IA públicas sin políticas claras?', 'Multiple Choice (una respuesta)', '["No hay riesgo, los datos se borran siempre", "Solo se pierde algo de tiempo", "Puede haber filtración de información, incumplimiento regulatorio y daño reputacional", "Únicamente se afecta el rendimiento de la campaña"]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', now(), 'Puede haber filtración de información, incumplimiento regulatorio y daño reputacional', '["Conocimiento", "Aplicación", "Estrategia"]'::jsonb, 2, 2),

('CMO-C12', 'Cuestionario', 'Conocimiento', '3', '2', 'La combinación de IA y pruebas A/B es útil porque:', 'Multiple Choice (una respuesta)', '["Hace innecesaria cualquier hipótesis", "Permite generar muchas variantes y luego validar empíricamente cuáles funcionan mejor", "Evita que tengamos que analizar métricas", "Solo sirve para grandes empresas"]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', now(), 'Permite generar muchas variantes y luego validar empíricamente cuáles funcionan mejor', '["Conocimiento"]'::jsonb, 2, 2),

('CMO-C13', 'Cuestionario', 'Conocimiento', '3', '2', '¿Qué es la segmentación predictiva en marketing?', 'Multiple Choice (una respuesta)', '["Clasificar clientes solo por edad y género", "Agrupar clientes al azar", "Usar modelos que predicen comportamientos futuros, como compra o abandono, para segmentar y priorizar acciones", "Enviar el mismo mensaje a toda la base"]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', now(), 'Usar modelos que predicen comportamientos futuros, como compra o abandono, para segmentar y priorizar acciones', '["Conocimiento"]'::jsonb, 2, 3),

('CMO-C14', 'Cuestionario', 'Conocimiento', '3', '2', 'Un ejemplo de uso de IA en CRM orientado a retención es:', 'Multiple Choice (una respuesta)', '["Eliminar contactos inactivos sin análisis", "Crear manualmente listas aleatorias", "Modelar probabilidad de abandono y activar campañas automáticas distintas según el nivel de riesgo", "Enviar el mismo email semanal a toda la base"]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', now(), 'Modelar probabilidad de abandono y activar campañas automáticas distintas según el nivel de riesgo', '["Conocimiento", "Aplicación"]'::jsonb, 2, 3),

('CMO-C15', 'Cuestionario', 'Conocimiento', '3', '2', '¿Qué rol tiene el first party data en una estrategia de IA de marketing?', 'Multiple Choice (una respuesta)', '["Es irrelevante, todo se puede comprar a terceros", "Es la principal fuente de datos sobre clientes y comportamientos que alimenta los modelos de IA", "Solo sirve para campañas offline", "Se usa solo en finanzas, no en marketing"]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', now(), 'Es la principal fuente de datos sobre clientes y comportamientos que alimenta los modelos de IA', '["Conocimiento", "Estrategia"]'::jsonb, 2, 3),

('CMO-C16', 'Cuestionario', 'Conocimiento', '3', '2', '¿Cuál de estos indicadores está más relacionado con medir impacto incremental de una campaña impulsada por IA?', 'Multiple Choice (una respuesta)', '["Aperturas de email", "Diferencia de conversiones entre un grupo expuesto y un grupo de control", "Número de creatividades generadas", "Cantidad de prompts utilizados"]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', now(), 'Diferencia de conversiones entre un grupo expuesto y un grupo de control', '["Conocimiento"]'::jsonb, 2, 3),

('CMO-C17', 'Cuestionario', 'Conocimiento', '3', '2', '¿Qué riesgo ético surge al personalizar demasiado ofertas con IA?', 'Multiple Choice (una respuesta)', '["Disminuir la relevancia de las ofertas", "Que todos los clientes reciban exactamente lo mismo", "Generar discriminación de precios o exclusión de ciertos segmentos sin transparencia", "Reducir el número de campañas"]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', now(), 'Generar discriminación de precios o exclusión de ciertos segmentos sin transparencia', '["Conocimiento", "Estrategia"]'::jsonb, 2, 3),

('CMO-C18', 'Cuestionario', 'Conocimiento', '3', '2', '¿Qué describe mejor una orquestación omnicanal apoyada en IA?', 'Multiple Choice (una respuesta)', '["Hacer una campaña solo en televisión", "Enviar el mismo mensaje por todos los canales al mismo tiempo", "Coordinar mensajes y ofertas en distintos canales según el comportamiento del cliente en tiempo casi real", "Tener equipos totalmente separados por canal"]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', now(), 'Coordinar mensajes y ofertas en distintos canales según el comportamiento del cliente en tiempo casi real', '["Conocimiento"]'::jsonb, 2, 3),

('CMO-C19', 'Cuestionario', 'Conocimiento', '3', '2', '¿Qué describe mejor el marketing mix modeling apoyado en IA?', 'Multiple Choice (una respuesta)', '["Un análisis solo cualitativo de campañas", "Un modelo estadístico o algorítmico que estima el impacto de distintos canales y factores en las ventas", "Un reporte estático mensual", "Un análisis exclusivo de redes sociales"]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', now(), 'Un modelo estadístico o algorítmico que estima el impacto de distintos canales y factores en las ventas', '["Conocimiento"]'::jsonb, 2, 4),

('CMO-C20', 'Cuestionario', 'Conocimiento', '3', '2', 'La diferencia principal entre atribución de último clic y modelos de atribución basados en IA es que estos últimos:', 'Multiple Choice (una respuesta)', '["Son más lentos", "Solo sirven para campañas offline", "Consideran múltiples puntos de contacto y patrones de comportamiento, no solo la última interacción", "No requieren datos históricos"]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', now(), 'Consideran múltiples puntos de contacto y patrones de comportamiento, no solo la última interacción', '["Conocimiento"]'::jsonb, 2, 4),

('CMO-C21', 'Cuestionario', 'Conocimiento', '3', '2', '¿Qué es un feature store en un entorno de IA para marketing?', 'Multiple Choice (una respuesta)', '["Una tienda física de productos", "Un repositorio centralizado de variables coherentes para usar en distintos modelos", "Un catálogo de campañas creativas", "Un marketplace de agencias"]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', now(), 'Un repositorio centralizado de variables coherentes para usar en distintos modelos', '["Conocimiento"]'::jsonb, 2, 4),

('CMO-C22', 'Cuestionario', 'Conocimiento', '3', '2', '¿Por qué es clave la gobernanza de datos en un entorno de IA de marketing avanzado?', 'Multiple Choice (una respuesta)', '["Solo para evitar duplicar archivos", "Para asegurar calidad, trazabilidad, cumplimiento regulatorio y uso responsable de los datos", "Para reducir el número de campañas", "Para eliminar la necesidad de métricas"]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', now(), 'Para asegurar calidad, trazabilidad, cumplimiento regulatorio y uso responsable de los datos', '["Conocimiento", "Aplicación", "Estrategia"]'::jsonb, 2, 4),

('CMO-C23', 'Cuestionario', 'Conocimiento', '3', '2', '¿Qué ventaja aporta un modelo de predicción de valor de vida del cliente al CMO?', 'Multiple Choice (una respuesta)', '["Evitar hacer investigación de mercado", "Tomar decisiones de inversión diferenciadas por segmento, priorizando aquellos con mayor valor futuro", "Eliminar por completo el riesgo de cancelación", "Solo sirve para reportes financieros anuales"]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', now(), 'Tomar decisiones de inversión diferenciadas por segmento, priorizando aquellos con mayor valor futuro', '["Conocimiento"]'::jsonb, 2, 4),

('CMO-C24', 'Cuestionario', 'Conocimiento', '3', '2', '¿Cuál es un riesgo de depender en exceso de automatizaciones de puja basadas en IA sin supervisión humana?', 'Multiple Choice (una respuesta)', '["Reducir el volumen de datos", "Sobreoptimizar a corto plazo a costa de la marca y del valor a largo plazo", "Mejorar demasiado el retorno de la inversión publicitaria", "Quitar trabajo a las agencias"]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', now(), 'Sobreoptimizar a corto plazo a costa de la marca y del valor a largo plazo', '["Conocimiento", "Estrategia"]'::jsonb, 2, 4),

('CMO-C25', 'Cuestionario', 'Conocimiento', '3', '2', '¿Qué caracteriza a una estrategia de IA a nivel corporativo liderada en parte por el CMO?', 'Multiple Choice (una respuesta)', '["Uso aislado de IA solo en redes sociales", "Múltiples iniciativas desconectadas en cada área", "Un roadmap transversal donde datos y modelos se reutilizan entre marketing, producto, operaciones y finanzas con una gobernanza clara", "Propiedad exclusiva de IA por parte del área de TI"]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', now(), 'Un roadmap transversal donde datos y modelos se reutilizan entre marketing, producto, operaciones y finanzas con una gobernanza clara', '["Conocimiento", "Estrategia"]'::jsonb, 2, 5),

('CMO-C26', 'Cuestionario', 'Conocimiento', '3', '2', '¿Qué es un marco de gobernanza de IA relevante para marketing?', 'Multiple Choice (una respuesta)', '["Un documento únicamente tecnológico", "Un conjunto de principios, roles y procesos para asegurar un uso responsable, medible y alineado al negocio de la IA", "Un contrato con una agencia", "Un manual de uso de redes sociales"]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', now(), 'Un conjunto de principios, roles y procesos para asegurar un uso responsable, medible y alineado al negocio de la IA', '["Conocimiento", "Estrategia"]'::jsonb, 2, 5),

('CMO-C27', 'Cuestionario', 'Conocimiento', '3', '2', '¿Qué implica usar IA para diseñar nuevos productos o servicios desde marketing?', 'Multiple Choice (una respuesta)', '["Dejar todo el desarrollo al área de TI", "Solo analizar campañas pasadas", "Usar modelos para identificar necesidades no cubiertas, simular escenarios de adopción y cocrear propuestas con clientes", "Únicamente bajar precios"]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', now(), 'Usar modelos para identificar necesidades no cubiertas, simular escenarios de adopción y cocrear propuestas con clientes', '["Conocimiento"]'::jsonb, 2, 5),

('CMO-C28', 'Cuestionario', 'Conocimiento', '3', '2', '¿Qué riesgo estratégico existe al sobreprometer capacidades de IA al mercado?', 'Multiple Choice (una respuesta)', '["Reducir el interés de inversionistas", "Incrementar temporalmente la moral interna", "Perder credibilidad con clientes, reguladores y el consejo si la realidad no acompaña las promesas", "Ninguno, la narrativa es lo más importante"]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', now(), 'Perder credibilidad con clientes, reguladores y el consejo si la realidad no acompaña las promesas', '["Conocimiento", "Estrategia"]'::jsonb, 2, 5),

('CMO-C29', 'Cuestionario', 'Conocimiento', '3', '2', '¿Qué significa que el CMO impulse una organización orientada a IA y centrada en el cliente?', 'Multiple Choice (una respuesta)', '["Cambiar solo la tecnología de marketing", "Reemplazar atención humana por bots en todos los puntos de contacto", "Replantear procesos, métricas, habilidades y cultura para que decisiones clave se apoyen sistemáticamente en datos y modelos con foco en la experiencia del cliente", "Únicamente lanzar una campaña sobre IA"]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', now(), 'Replantear procesos, métricas, habilidades y cultura para que decisiones clave se apoyen sistemáticamente en datos y modelos con foco en la experiencia del cliente', '["Conocimiento"]'::jsonb, 2, 5),

('CMO-C30', 'Cuestionario', 'Conocimiento', '3', '2', 'En términos de inversión, ¿qué hace sostenible una agenda de IA en marketing?', 'Multiple Choice (una respuesta)', '["Invertir lo máximo posible en cualquier herramienta nueva", "Depender completamente de proveedores externos", "Priorizar iniciativas con casos de negocio claros, medir el retorno y reinvertir en las que demuestran valor", "No medir el impacto para evitar fricciones internas"]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', now(), 'Priorizar iniciativas con casos de negocio claros, medir el retorno y reinvertir en las que demuestran valor', '["Conocimiento", "Inversión"]'::jsonb, 2, 5);
