-- ============================================================================
-- PREGUNTAS PARA MIEMBROS DE CONTABILIDAD
-- ============================================================================
-- Rol incluido:
--   - Rol ID 22: Miembros de Contabilidad (area_id: 7, nivel_id: 4)
-- ============================================================================

-- ============================================================================
-- ROL 22: Miembros de Contabilidad
-- ============================================================================

-- ADOPCIÓN - Rol 22
INSERT INTO "public"."preguntas" ("codigo", "section", "bloque", "area_id", "exclusivo_rol_id", "texto", "tipo", "opciones", "locale", "peso", "escala", "scoring", "created_at", "respuesta_correcta", "dimension", "exclusivo_nivel_id", "dificultad") VALUES
('MC-A1', 'Cuestionario', 'Adopción', '7', '22', 'En tu trabajo de contabilidad, ¿con qué frecuencia usas buscadores o chatbots de IA para aclarar conceptos contables básicos (por ejemplo, definiciones, fórmulas)?', 'Multiple Choice (escala Likert A–E)', '["Nunca", "Rara vez (≤ 1/mes)", "Ocasional (2–3/mes)", "Frecuente (semanal)", "Muy frecuente (diaria)"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', now(), null, '["Aplicación"]'::jsonb, 4, 1),

('MC-A2', 'Cuestionario', 'Adopción', '7', '22', '¿Con qué frecuencia utilizas IA (chatbots, asistentes de texto) para redactar o mejorar correos a clientes/proveedores relacionados con facturas, pagos o aclaraciones?', 'Multiple Choice (escala Likert A–E)', '["Nunca", "Rara vez (≤ 1/mes)", "Ocasional (2–3/mes)", "Frecuente (semanal)", "Muy frecuente (diaria)"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', now(), null, '["Aplicación"]'::jsonb, 4, 1),

('MC-A3', 'Cuestionario', 'Adopción', '7', '22', '¿Con qué frecuencia dedicas tiempo a explorar por tu cuenta contenidos (videos, tutoriales, artículos) sobre IA aplicada a contabilidad?', 'Multiple Choice (escala Likert A–E)', '["Nunca", "Rara vez (≤ 1/mes)", "Ocasional (2–3/mes)", "Frecuente (semanal)", "Muy frecuente (diaria)"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', now(), null, '["Aplicación", "Productividad"]'::jsonb, 4, 1),

('MC-A4', 'Cuestionario', 'Adopción', '7', '22', '¿Con qué frecuencia piensas en tareas repetitivas de tu trabajo (captura, revisión, conciliación) que podrían beneficiarse de IA, aunque todavía no la uses?', 'Multiple Choice (escala Likert A–E)', '["Nunca", "Rara vez (≤ 1/mes)", "Ocasional (2–3/mes)", "Frecuente (semanal)", "Muy frecuente (diaria)"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', now(), null, '["Aplicación"]'::jsonb, 4, 1),

('MC-A5', 'Cuestionario', 'Adopción', '7', '22', '¿Con qué frecuencia revisas si tu empresa tiene políticas o lineamientos sobre el uso de IA con datos contables?', 'Multiple Choice (escala Likert A–E)', '["Nunca", "Rara vez (≤ 1/mes)", "Ocasional (2–3/mes)", "Frecuente (semanal)", "Muy frecuente (diaria)"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', now(), null, '["Aplicación"]'::jsonb, 4, 1),

('MC-A6', 'Cuestionario', 'Adopción', '7', '22', '¿Con qué frecuencia propones a tu jefe o compañeros probar herramientas sencillas de IA (aunque sea de forma muy básica) en tareas del área contable?', 'Multiple Choice (escala Likert A–E)', '["Nunca", "Rara vez (≤ 1/mes)", "Ocasional (2–3/mes)", "Frecuente (semanal)", "Muy frecuente (diaria)"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', now(), null, '["Aplicación"]'::jsonb, 4, 1),

('MC-A7', 'Cuestionario', 'Adopción', '7', '22', '¿Con qué frecuencia usas IA para resumir correos largos relacionados con estados de cuenta, reclamaciones o aclaraciones con clientes/proveedores?', 'Multiple Choice (escala Likert A–E)', '["Nunca", "Rara vez (≤ 1/mes)", "Ocasional (2–3/mes)", "Frecuente (semanal)", "Muy frecuente (diaria)"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', now(), null, '["Aplicación"]'::jsonb, 4, 2),

('MC-A8', 'Cuestionario', 'Adopción', '7', '22', '¿Con qué frecuencia utilizas IA para traducir o simplificar explicaciones contables a personas no financieras (por ejemplo, áreas operativas)?', 'Multiple Choice (escala Likert A–E)', '["Nunca", "Rara vez (≤ 1/mes)", "Ocasional (2–3/mes)", "Frecuente (semanal)", "Muy frecuente (diaria)"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', now(), null, '["Aplicación"]'::jsonb, 4, 2),

('MC-A9', 'Cuestionario', 'Adopción', '7', '22', '¿Con qué frecuencia evalúas si la respuesta de la IA coincide con las políticas o criterios contables de tu empresa?', 'Multiple Choice (escala Likert A–E)', '["Nunca", "Rara vez (≤ 1/mes)", "Ocasional (2–3/mes)", "Frecuente (semanal)", "Muy frecuente (diaria)"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', now(), null, '["Aplicación"]'::jsonb, 4, 2),

('MC-A10', 'Cuestionario', 'Adopción', '7', '22', '¿Con qué frecuencia pruebas pequeños experimentos con IA para ver si te ahorran tiempo en tareas simples (por ejemplo, redactar descripciones de pólizas, notas explicativas)?', 'Multiple Choice (escala Likert A–E)', '["Nunca", "Rara vez (≤ 1/mes)", "Ocasional (2–3/mes)", "Frecuente (semanal)", "Muy frecuente (diaria)"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', now(), null, '["Aplicación", "Productividad"]'::jsonb, 4, 2),

('MC-A11', 'Cuestionario', 'Adopción', '7', '22', '¿Con qué frecuencia compartes con tus compañeros ejemplos de respuestas útiles de IA que te hayan ayudado en tareas contables?', 'Multiple Choice (escala Likert A–E)', '["Nunca", "Rara vez (≤ 1/mes)", "Ocasional (2–3/mes)", "Frecuente (semanal)", "Muy frecuente (diaria)"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', now(), null, '["Aplicación"]'::jsonb, 4, 2),

('MC-A12', 'Cuestionario', 'Adopción', '7', '22', '¿Con qué frecuencia propones usar IA para preparar borradores de reportes internos (por ejemplo, resúmenes de variaciones de gastos) que luego se revisan manualmente?', 'Multiple Choice (escala Likert A–E)', '["Nunca", "Rara vez (≤ 1/mes)", "Ocasional (2–3/mes)", "Frecuente (semanal)", "Muy frecuente (diaria)"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', now(), null, '["Productividad"]'::jsonb, 4, 2),

('MC-A13', 'Cuestionario', 'Adopción', '7', '22', '¿Con qué frecuencia utilizas IA integrada al sistema contable o herramientas externas para clasificar automáticamente facturas y gastos?', 'Multiple Choice (escala Likert A–E)', '["Nunca", "Rara vez (≤ 1/mes)", "Ocasional (2–3/mes)", "Frecuente (semanal)", "Muy frecuente (diaria)"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', now(), null, '["Aplicación"]'::jsonb, 4, 3),

('MC-A14', 'Cuestionario', 'Adopción', '7', '22', '¿Con qué frecuencia usas IA para preparar borradores de conciliaciones (por ejemplo, explicaciones de diferencias, agrupaciones de movimientos)?', 'Multiple Choice (escala Likert A–E)', '["Nunca", "Rara vez (≤ 1/mes)", "Ocasional (2–3/mes)", "Frecuente (semanal)", "Muy frecuente (diaria)"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', now(), null, '["Aplicación"]'::jsonb, 4, 3),

('MC-A15', 'Cuestionario', 'Adopción', '7', '22', '¿Con qué frecuencia ajustas tus prompts o instrucciones a la IA para obtener mejores resultados en tareas contables (por ejemplo, pedir formatos específicos de tabla)?', 'Multiple Choice (escala Likert A–E)', '["Nunca", "Rara vez (≤ 1/mes)", "Ocasional (2–3/mes)", "Frecuente (semanal)", "Muy frecuente (diaria)"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', now(), null, '["Productividad"]'::jsonb, 4, 3),

('MC-A16', 'Cuestionario', 'Adopción', '7', '22', '¿Con qué frecuencia colaboras con compañeros para revisar y mejorar los flujos de trabajo que ya usan IA (por ejemplo, revisando errores recurrentes)?', 'Multiple Choice (escala Likert A–E)', '["Nunca", "Rara vez (≤ 1/mes)", "Ocasional (2–3/mes)", "Frecuente (semanal)", "Muy frecuente (diaria)"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', now(), null, '["Aplicación"]'::jsonb, 4, 3),

('MC-A17', 'Cuestionario', 'Adopción', '7', '22', '¿Con qué frecuencia identificas riesgos (por ejemplo, datos sensibles, errores de clasificación) al usar IA y los comunicas a tu jefe o al área responsable?', 'Multiple Choice (escala Likert A–E)', '["Nunca", "Rara vez (≤ 1/mes)", "Ocasional (2–3/mes)", "Frecuente (semanal)", "Muy frecuente (diaria)"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', now(), null, '["Aplicación", "Estrategia"]'::jsonb, 4, 3),

('MC-A18', 'Cuestionario', 'Adopción', '7', '22', '¿Con qué frecuencia registras o comentas mejoras concretas de tiempo/calidad que has logrado usando IA, como insumo para justificar inversiones futuras?', 'Multiple Choice (escala Likert A–E)', '["Nunca", "Rara vez (≤ 1/mes)", "Ocasional (2–3/mes)", "Frecuente (semanal)", "Muy frecuente (diaria)"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', now(), null, '["Productividad"]'::jsonb, 4, 3),

('MC-A19', 'Cuestionario', 'Adopción', '7', '22', '¿Con qué frecuencia diseñas o propones flujos de trabajo donde la IA interviene en varios pasos (por ejemplo, lectura de factura, clasificación, alerta de anomalía)?', 'Multiple Choice (escala Likert A–E)', '["Nunca", "Rara vez (≤ 1/mes)", "Ocasional (2–3/mes)", "Frecuente (semanal)", "Muy frecuente (diaria)"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', now(), null, '["Aplicación"]'::jsonb, 4, 4),

('MC-A20', 'Cuestionario', 'Adopción', '7', '22', '¿Con qué frecuencia mides de forma explícita (horas, errores, reprocesos) el antes y después de implementar IA en un proceso contable concreto?', 'Multiple Choice (escala Likert A–E)', '["Nunca", "Rara vez (≤ 1/mes)", "Ocasional (2–3/mes)", "Frecuente (semanal)", "Muy frecuente (diaria)"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', now(), null, '["Aplicación"]'::jsonb, 4, 4),

('MC-A21', 'Cuestionario', 'Adopción', '7', '22', '¿Con qué frecuencia ajustas reglas o parámetros de IA (por ejemplo, criterios de clasificación o umbrales de alerta) con base en análisis de errores?', 'Multiple Choice (escala Likert A–E)', '["Nunca", "Rara vez (≤ 1/mes)", "Ocasional (2–3/mes)", "Frecuente (semanal)", "Muy frecuente (diaria)"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', now(), null, '["Aplicación"]'::jsonb, 4, 4),

('MC-A22', 'Cuestionario', 'Adopción', '7', '22', '¿Con qué frecuencia coordinas con otras áreas (TI, Finanzas, Auditoría) para revisar impactos y riesgos de las automatizaciones con IA que usas en el día a día?', 'Multiple Choice (escala Likert A–E)', '["Nunca", "Rara vez (≤ 1/mes)", "Ocasional (2–3/mes)", "Frecuente (semanal)", "Muy frecuente (diaria)"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', now(), null, '["Estrategia"]'::jsonb, 4, 4),

('MC-A23', 'Cuestionario', 'Adopción', '7', '22', '¿Con qué frecuencia propones formalmente (en reuniones, reportes) nuevas inversiones en IA, basadas en resultados medidos en tu área (ahorros, reducción de errores)?', 'Multiple Choice (escala Likert A–E)', '["Nunca", "Rara vez (≤ 1/mes)", "Ocasional (2–3/mes)", "Frecuente (semanal)", "Muy frecuente (diaria)"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', now(), null, '["Productividad"]'::jsonb, 4, 4),

('MC-A24', 'Cuestionario', 'Adopción', '7', '22', '¿Con qué frecuencia revisas lineamientos éticos o de cumplimiento para asegurarte de que los flujos con IA respetan normas contables, fiscales y de privacidad?', 'Multiple Choice (escala Likert A–E)', '["Nunca", "Rara vez (≤ 1/mes)", "Ocasional (2–3/mes)", "Frecuente (semanal)", "Muy frecuente (diaria)"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', now(), null, '["Estrategia"]'::jsonb, 4, 4),

('MC-A25', 'Cuestionario', 'Adopción', '7', '22', '¿Con qué frecuencia lideras o co-lideras iniciativas para identificar nuevos casos de uso de IA en los procesos contables (más allá de los ya implementados)?', 'Multiple Choice (escala Likert A–E)', '["Nunca", "Rara vez (≤ 1/mes)", "Ocasional (2–3/mes)", "Frecuente (semanal)", "Muy frecuente (diaria)"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', now(), null, '["Aplicación", "Estrategia"]'::jsonb, 4, 5),

('MC-A26', 'Cuestionario', 'Adopción', '7', '22', '¿Con qué frecuencia participas en la definición de métricas y tableros para medir el impacto global de la IA en el área de contabilidad (errores, tiempos, SLA)?', 'Multiple Choice (escala Likert A–E)', '["Nunca", "Rara vez (≤ 1/mes)", "Ocasional (2–3/mes)", "Frecuente (semanal)", "Muy frecuente (diaria)"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', now(), null, '["Productividad"]'::jsonb, 4, 5),

('MC-A27', 'Cuestionario', 'Adopción', '7', '22', '¿Con qué frecuencia apoyas a otros compañeros en el diseño de prompts eficaces, plantillas o flujos de trabajo con IA adaptados a tareas contables específicas?', 'Multiple Choice (escala Likert A–E)', '["Nunca", "Rara vez (≤ 1/mes)", "Ocasional (2–3/mes)", "Frecuente (semanal)", "Muy frecuente (diaria)"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', now(), null, '["Aplicación"]'::jsonb, 4, 5),

('MC-A28', 'Cuestionario', 'Adopción', '7', '22', '¿Con qué frecuencia participas en discusiones con TI, Auditoría, Legal o RRHH sobre políticas y riesgos de la IA aplicada a contabilidad?', 'Multiple Choice (escala Likert A–E)', '["Nunca", "Rara vez (≤ 1/mes)", "Ocasional (2–3/mes)", "Frecuente (semanal)", "Muy frecuente (diaria)"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', now(), null, '["Aplicación", "Estrategia"]'::jsonb, 4, 5),

('MC-A29', 'Cuestionario', 'Adopción', '7', '22', '¿Con qué frecuencia preparas o contribuyes a propuestas formales de inversión en nuevas herramientas de IA para el área (business case, retorno esperado, riesgos)?', 'Multiple Choice (escala Likert A–E)', '["Nunca", "Rara vez (≤ 1/mes)", "Ocasional (2–3/mes)", "Frecuente (semanal)", "Muy frecuente (diaria)"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', now(), null, '["Aplicación", "Inversión", "Estrategia"]'::jsonb, 4, 5),

('MC-A30', 'Cuestionario', 'Adopción', '7', '22', '¿Con qué frecuencia ayudas a construir o mantener lineamientos internos de uso responsable de IA (checklists, buenas prácticas, ejemplos de sí usar / no usar) para el equipo de contabilidad?', 'Multiple Choice (escala Likert A–E)', '["Nunca", "Rara vez (≤ 1/mes)", "Ocasional (2–3/mes)", "Frecuente (semanal)", "Muy frecuente (diaria)"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', now(), null, '["Aplicación"]'::jsonb, 4, 5);

-- CONOCIMIENTO - Rol 22
INSERT INTO "public"."preguntas" ("codigo", "section", "bloque", "area_id", "exclusivo_rol_id", "texto", "tipo", "opciones", "locale", "peso", "escala", "scoring", "created_at", "respuesta_correcta", "dimension", "exclusivo_nivel_id", "dificultad") VALUES
('MC-C1', 'Cuestionario', 'Conocimiento', '7', '22', 'Cuando hablamos de inteligencia artificial aplicada a contabilidad, ¿cuál de estas opciones describe mejor un caso de uso básico?', 'Multiple Choice (una respuesta)', '["Usar una calculadora para sumar facturas manualmente", "Usar un sistema ERP sin ninguna automatización", "Usar una herramienta que lee una factura en PDF y propone los datos para registrarla", "Imprimir todas las facturas para archivarlas en papel"]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', now(), null, '["Aplicación", "Conocimiento"]'::jsonb, 4, 1),

('MC-C2', 'Cuestionario', 'Conocimiento', '7', '22', '¿Cuál es la principal diferencia entre una hoja de cálculo tradicional y una herramienta de IA generativa?', 'Multiple Choice (una respuesta)', '["La hoja de cálculo siempre necesita conexión a internet y la IA no", "La IA puede generar texto, sugerencias o análisis a partir de instrucciones en lenguaje natural", "La IA solo sirve para traducir textos y la hoja de cálculo para cálculos", "No hay ninguna diferencia relevante"]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', now(), 'La IA puede generar texto, sugerencias o análisis a partir de instrucciones en lenguaje natural', '["Conocimiento"]'::jsonb, 4, 1),

('MC-C3', 'Cuestionario', 'Conocimiento', '7', '22', '¿Cuál de estas acciones es más adecuada para proteger datos contables al usar un chatbot público de IA?', 'Multiple Choice (una respuesta)', '["Copiar y pegar estados financieros completos con nombres de clientes", "Introducir solo datos ficticios o anonimizados cuando sea posible", "Compartir el usuario y contraseña del ERP para que la IA se conecte", "Subir la base completa de proveedores para que aprenda"]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', now(), 'Introducir solo datos ficticios o anonimizados cuando sea posible', '["Aplicación", "Conocimiento"]'::jsonb, 4, 1),

('MC-C4', 'Cuestionario', 'Conocimiento', '7', '22', 'Si te hablan de “automatizar tareas repetitivas de registro de facturas”, ¿a qué tecnología suele referirse esto?', 'Multiple Choice (una respuesta)', '["Solo a hojas de cálculo", "IA, RPA u otras herramientas que imitan pasos rutinarios en sistemas", "Exclusivamente a macros de Excel", "A cambiar de ERP"]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', now(), 'IA, RPA u otras herramientas que imitan pasos rutinarios en sistemas', '["Productividad", "Conocimiento"]'::jsonb, 4, 1),

('MC-C5', 'Cuestionario', 'Conocimiento', '7', '22', 'En contabilidad, ¿qué NO deberías esperar de una herramienta de IA?', 'Multiple Choice (una respuesta)', '["Que ayude a explicar un procedimiento contable en lenguaje simple", "Que genere borradores de explicaciones para conciliaciones", "Que sustituya completamente el juicio profesional y conocimiento de normas contables", "Que sugiera mejoras en la redacción de correos a proveedores"]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', now(), 'Que sustituya completamente el juicio profesional y conocimiento de normas contables', '["Conocimiento"]'::jsonb, 4, 1),

('MC-C6', 'Cuestionario', 'Conocimiento', '7', '22', '¿Cómo se llama la indicación o instrucción en lenguaje natural que se le da a una herramienta de IA generativa?', 'Multiple Choice (una respuesta)', '["Token", "Prompt", "Log", "Script contable"]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', now(), 'Prompt', '["Conocimiento"]'::jsonb, 4, 1),

('MC-C7', 'Cuestionario', 'Conocimiento', '7', '22', 'Ya has usado IA algunas veces. ¿Cuál es una buena forma de verificar la calidad de una explicación contable generada por IA?', 'Multiple Choice (una respuesta)', '["Confiar en ella si suena razonable", "Compararla con políticas contables internas o con una fuente confiable", "Preguntar a otro chatbot de IA si está bien", "Usarla tal cual si ahorra tiempo"]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', now(), 'Compararla con políticas contables internas o con una fuente confiable', '["Conocimiento"]'::jsonb, 4, 2),

('MC-C8', 'Cuestionario', 'Conocimiento', '7', '22', 'En cuentas por pagar, ¿qué tarea es un ejemplo claro de uso de IA/OCR?', 'Multiple Choice (una respuesta)', '["Imprimir facturas y archivarlas", "Ordenar manualmente facturas por fecha", "Leer facturas en PDF y extraer automáticamente importe, fecha e impuestos", "Enviar recordatorios de pago por teléfono"]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', now(), 'Leer facturas en PDF y extraer automáticamente importe, fecha e impuestos', '["Aplicación", "Conocimiento"]'::jsonb, 4, 2),

('MC-C9', 'Cuestionario', 'Conocimiento', '7', '22', '¿Qué limitación importante debes considerar al usar IA para interpretar normativas fiscales?', 'Multiple Choice (una respuesta)', '["La IA siempre está actualizada con las últimas reformas", "La IA puede inventar o mezclar información si no encuentra datos claros", "La IA reemplaza al asesor fiscal y al área legal", "La IA solo sirve para traducir la ley"]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', now(), 'La IA puede inventar o mezclar información si no encuentra datos claros', '["Conocimiento"]'::jsonb, 4, 2),

('MC-C10', 'Cuestionario', 'Conocimiento', '7', '22', 'Si una herramienta de IA propone clasificaciones de gastos por cuenta contable, ¿qué rol deberías jugar tú como miembro de contabilidad?', 'Multiple Choice (una respuesta)', '["Aceptar la sugerencia sin revisar", "Validar la propuesta y corregir cuando sea necesario", "Ignorar siempre las sugerencias", "Delegar la revisión a un área externa"]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', now(), 'Validar la propuesta y corregir cuando sea necesario', '["Conocimiento"]'::jsonb, 4, 2),

('MC-C11', 'Cuestionario', 'Conocimiento', '7', '22', 'En términos de inversión de tiempo, ¿qué práctica es más inteligente cuando estás empezando a usar IA?', 'Multiple Choice (una respuesta)', '["No dedicar nada de tiempo a aprender y usarla solo cuando te obliguen", "Reservar pequeños bloques de tiempo para probarla en tareas sencillas y medir si ahorra tiempo", "Dejar tareas clave del cierre contable exclusivamente a la IA desde el primer día", "Usarla solo fuera del horario laboral"]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', now(), 'Reservar pequeños bloques de tiempo para probarla en tareas sencillas y medir si ahorra tiempo', '["Inversión", "Productividad", "Conocimiento"]'::jsonb, 4, 2),

('MC-C12', 'Cuestionario', 'Conocimiento', '7', '22', '¿Cuál de los siguientes ejemplos describe una colaboración responsable entre personas y IA en contabilidad?', 'Multiple Choice (una respuesta)', '["La IA prepara borradores de notas y tú los revisas antes de enviarlos", "La IA envía directamente reportes a clientes sin tu revisión", "La IA cambia saldos en el ERP sin controles", "La IA decide sola qué políticas contables aplicar"]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', now(), 'La IA prepara borradores de notas y tú los revisas antes de enviarlos', '["Conocimiento"]'::jsonb, 4, 2),

('MC-C13', 'Cuestionario', 'Conocimiento', '7', '22', 'Estás usando IA para extraer datos de facturas. ¿Qué control es más adecuado para asegurar calidad?', 'Multiple Choice (una respuesta)', '["No hacer nada si el porcentaje de acierto es aceptable", "Revisar sistemáticamente las excepciones y errores identificados por el sistema", "Revisar el 100% de las facturas como si no existiera IA", "Desactivar todas las alertas de error"]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', now(), 'Revisar sistemáticamente las excepciones y errores identificados por el sistema', '["Aplicación", "Conocimiento"]'::jsonb, 4, 3),

('MC-C14', 'Cuestionario', 'Conocimiento', '7', '22', 'Una herramienta de IA te sugiere clasificar transacciones bancarias automáticamente. ¿Qué deberías confirmar antes de usarla en producción?', 'Multiple Choice (una respuesta)', '["Que la interfaz sea estéticamente agradable", "Que exista autorización de tu jefe y alineación con controles internos", "Que no haya forma de auditar los cambios", "Que las reglas de clasificación sean secretas"]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', now(), 'Que exista autorización de tu jefe y alineación con controles internos', '["Conocimiento"]'::jsonb, 4, 3),

('MC-C15', 'Cuestionario', 'Conocimiento', '7', '22', '¿Qué uso de IA encaja mejor en el flujo de conciliación bancaria?', 'Multiple Choice (una respuesta)', '["IA que genera estados financieros completos sin datos de bancos", "IA que sugiere posibles matches entre movimientos bancarios y pólizas registradas", "IA que solo cambia el tipo de letra del reporte", "IA que borra operaciones que no entiende"]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', now(), 'IA que sugiere posibles matches entre movimientos bancarios y pólizas registradas', '["Aplicación", "Conocimiento"]'::jsonb, 4, 3),

('MC-C16', 'Cuestionario', 'Conocimiento', '7', '22', 'Sobre el impacto estratégico de la IA en el área de contabilidad, ¿qué afirmación es más adecuada para tu rol?', 'Multiple Choice (una respuesta)', '["Como miembro del equipo, no tengo ningún rol en esto", "Puedo identificar puntos del proceso donde la IA reduce errores y tiempos, y compartirlo con mi jefe", "Solo la alta dirección define todo sin mi aportación", "La IA solo afecta a TI, no a contabilidad"]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', now(), 'Puedo identificar puntos del proceso donde la IA reduce errores y tiempos, y compartirlo con mi jefe', '["Conocimiento", "Estrategia"]'::jsonb, 4, 3),

('MC-C17', 'Cuestionario', 'Conocimiento', '7', '22', 'En términos de inversión de tiempo para usar IA, ¿qué indicador simple puedes observar en tu trabajo diario?', 'Multiple Choice (una respuesta)', '["Número de correos que envías al día", "Minutos u horas que ahorras cuando usas una automatización con IA", "Cantidad de hojas impresas por mes", "Número de llamadas telefónicas al proveedor"]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', now(), 'Minutos u horas que ahorras cuando usas una automatización con IA', '["Inversión", "Productividad", "Conocimiento"]'::jsonb, 4, 3),

('MC-C18', 'Cuestionario', 'Conocimiento', '7', '22', 'Cuando colaboras con otros departamentos usando IA, ¿qué práctica es más adecuada?', 'Multiple Choice (una respuesta)', '["Compartir capturas con datos sensibles en grupos públicos", "Definir claramente qué parte hace la IA y qué parte revisa cada persona", "Dejar que los demás departamentos usen tus credenciales", "Permitir que cualquier área modifique saldos contables con IA"]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', now(), 'Definir claramente qué parte hace la IA y qué parte revisa cada persona', '["Conocimiento"]'::jsonb, 4, 3),

('MC-C19', 'Cuestionario', 'Conocimiento', '7', '22', 'Cuando diseñas un flujo con IA para cuentas por pagar, ¿qué es fundamental para no debilitar los controles internos?', 'Multiple Choice (una respuesta)', '["Permitir que la IA apruebe pagos sin intervención humana", "Documentar claramente qué pasos son automáticos y cuáles requieren revisión humana", "Desactivar las bitácoras de cambios para simplificar", "No informar al área de auditoría interna"]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', now(), 'Documentar claramente qué pasos son automáticos y cuáles requieren revisión humana', '["Conocimiento"]'::jsonb, 4, 4),

('MC-C20', 'Cuestionario', 'Conocimiento', '7', '22', '¿Cuál es un ejemplo de métrica relevante para evaluar el impacto de IA en productividad contable?', 'Multiple Choice (una respuesta)', '["Número de likes en redes sociales de la empresa", "Porcentaje de facturas procesadas automáticamente sin corrección", "Número de correos reenviados con copia", "Veces que el sistema se reinicia"]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', now(), 'Porcentaje de facturas procesadas automáticamente sin corrección', '["Productividad", "Conocimiento"]'::jsonb, 4, 4),

('MC-C21', 'Cuestionario', 'Conocimiento', '7', '22', 'Si la IA ayuda a detectar anomalías en movimientos contables, ¿qué deberías evitar?', 'Multiple Choice (una respuesta)', '["Usar las alertas como insumo para investigar", "Ignorar las alertas por considerarlas exageradas", "Ajustar los umbrales de alerta con base en experiencia", "Documentar los falsos positivos y ajustar el modelo"]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', now(), 'Ignorar las alertas por considerarlas exageradas', '["Conocimiento"]'::jsonb, 4, 4),

('MC-C22', 'Cuestionario', 'Conocimiento', '7', '22', 'En términos estratégicos, ¿cómo puede un miembro de contabilidad aportar al plan de IA del área?', 'Multiple Choice (una respuesta)', '["Identificando procesos contables donde la IA genera ahorro medible y proponiéndolos formalmente", "Esperando a que todo venga definido desde la dirección sin aportar datos", "Usando IA solo para tareas personales", "Evitando toda documentación sobre automatizaciones"]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', now(), 'Identificando procesos contables donde la IA genera ahorro medible y proponiéndolos formalmente', '["Conocimiento"]'::jsonb, 4, 4),

('MC-C23', 'Cuestionario', 'Conocimiento', '7', '22', 'Sobre inversión de tiempo para usar IA, ¿qué estrategia es más adecuada en tu rol?', 'Multiple Choice (una respuesta)', '["Invertir en tareas con bajo impacto y alta complejidad de automatización", "Priorizar tareas repetitivas de alto volumen y riesgo de error", "Evitar cualquier cambio para no mover el proceso actual", "Solo automatizar tareas que haces muy pocas veces"]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', now(), 'Priorizar tareas repetitivas de alto volumen y riesgo de error', '["Inversión", "Productividad", "Conocimiento", "Estrategia"]'::jsonb, 4, 4),

('MC-C24', 'Cuestionario', 'Conocimiento', '7', '22', 'Si coordinas con TI para integrar IA al ERP contable, ¿qué aspecto no puedes descuidar?', 'Multiple Choice (una respuesta)', '["Diseño visual del icono de la IA", "Registro de logs y trazabilidad de qué propone o ejecuta la IA", "Eliminación de cualquier registro de auditoría para no llenar la base de datos", "Acceso ilimitado de la IA a todos los módulos sin restricciones"]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', now(), 'Registro de logs y trazabilidad de qué propone o ejecuta la IA', '["Conocimiento"]'::jsonb, 4, 4),

('MC-C25', 'Cuestionario', 'Conocimiento', '7', '22', 'Si eres referente de IA en el equipo, ¿qué práctica es clave para asegurar escalabilidad y sostenibilidad del uso de IA en contabilidad?', 'Multiple Choice (una respuesta)', '["Mantener todo el conocimiento en tu cabeza para ser indispensable", "Documentar casos de uso, flujos, riesgos y métricas en formatos accesibles para el equipo", "Probar herramientas sin informar a nadie", "Permitir que cada persona configure la IA sin ningún estándar"]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', now(), 'Documentar casos de uso, flujos, riesgos y métricas en formatos accesibles para el equipo', '["Aplicación", "Conocimiento"]'::jsonb, 4, 5),

('MC-C26', 'Cuestionario', 'Conocimiento', '7', '22', 'Al evaluar una nueva herramienta de IA contable, ¿qué criterio estratégico es más importante?', 'Multiple Choice (una respuesta)', '["Que tenga la interfaz más moderna", "Que aporte valor medible (tiempo, errores, cumplimiento) en procesos clave del área", "Que tenga la campaña de marketing más fuerte", "Que sea la más cara, asumiendo que es la mejor"]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', now(), 'Que aporte valor medible (tiempo, errores, cumplimiento) en procesos clave del área', '["Conocimiento"]'::jsonb, 4, 5),

('MC-C27', 'Cuestionario', 'Conocimiento', '7', '22', 'Si detectas que la IA está generando sesgos o errores sistemáticos (por ejemplo, clasificación incorrecta de ciertos tipos de gastos), ¿qué deberías hacer?', 'Multiple Choice (una respuesta)', '["Ignorarlo si el volumen global funciona", "Documentar el patrón, ajustar reglas y escalar a TI o auditoría si es significativo", "Desactivar las alertas para no ver el problema", "Culpabilizar a los usuarios que lo reportan"]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', now(), 'Documentar el patrón, ajustar reglas y escalar a TI o auditoría si es significativo', '["Conocimiento", "Estrategia"]'::jsonb, 4, 5),

('MC-C28', 'Cuestionario', 'Conocimiento', '7', '22', '¿Qué rol puede tener un referente de IA en la formación del equipo de contabilidad?', 'Multiple Choice (una respuesta)', '["Ninguno, la capacitación es solo de RRHH", "Diseñar o co-diseñar cápsulas prácticas de formación basadas en casos reales del área", "Limitarse a compartir enlaces sin contexto", "Evitar cualquier actividad de formación por falta de tiempo"]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', now(), 'Diseñar o co-diseñar cápsulas prácticas de formación basadas en casos reales del área', '["Aplicación", "Conocimiento"]'::jsonb, 4, 5),

('MC-C29', 'Cuestionario', 'Conocimiento', '7', '22', 'Respecto a inversión, ¿qué enfoque es más maduro para decidir en qué proyectos de IA enfocarse?', 'Multiple Choice (una respuesta)', '["Elegir proyectos solo porque usan la tecnología más reciente", "Priorizar proyectos con alto impacto en volumen, riesgo y alineación estratégica del área", "Priorizar proyectos que no tienen relación con contabilidad", "Elegir solo proyectos que te resulten interesantes a nivel personal"]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', now(), 'Priorizar proyectos con alto impacto en volumen, riesgo y alineación estratégica del área', '["Inversión", "Conocimiento"]'::jsonb, 4, 5),

('MC-C30', 'Cuestionario', 'Conocimiento', '7', '22', '¿Cómo se puede integrar la voz del equipo de contabilidad en decisiones de IA a nivel organización?', 'Multiple Choice (una respuesta)', '["Evitando su participación para no complicar", "Levantando sistemáticamente feedback sobre uso de IA en el día a día y presentándolo en foros de decisión", "Solo escuchando a la alta dirección", "Usando encuestas, pero sin leer los resultados"]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', now(), 'Levantando sistemáticamente feedback sobre uso de IA en el día a día y presentándolo en foros de decisión', '["Aplicación", "Conocimiento"]'::jsonb, 4, 5);
