-- ============================================================================
-- PREGUNTAS PARA MIEMBROS DE GOBIERNO / SECTOR PÚBLICO
-- ============================================================================
-- Rol incluido:
--   - Rol ID 28: Miembros de Gobierno / Sector público (area_id: 10, nivel_id: 4)
-- ============================================================================

-- ============================================================================
-- ROL 28: Miembros de Gobierno / Sector público
-- ============================================================================

-- ADOPCIÓN - Rol 28
INSERT INTO "public"."preguntas" ("codigo", "section", "bloque", "area_id", "exclusivo_rol_id", "texto", "tipo", "opciones", "locale", "peso", "escala", "scoring", "created_at", "respuesta_correcta", "dimension", "exclusivo_nivel_id", "dificultad") VALUES
('MG-A1', 'Cuestionario', 'Adopción', '10', '28', 'En tu trabajo diario, ¿con qué frecuencia utilizas asistentes de texto (por ejemplo, copilots o chatbots) para redactar correos, oficios o informes internos?', 'Multiple Choice (escala Likert A–E)', '["Nunca", "Rara vez (≤ 1/mes)", "Ocasional (2–3/mes)", "Frecuente (semanal)", "Muy frecuente (diaria)"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', now(), null, '["Aplicación"]'::jsonb, 4, 1),

('MG-A2', 'Cuestionario', 'Adopción', '10', '28', '¿Con qué frecuencia usas herramientas digitales (como buscadores avanzados o resumen automático) para revisar leyes, reglamentos o lineamientos?', 'Multiple Choice (escala Likert A–E)', '["Nunca", "Rara vez (≤ 1/mes)", "Ocasional (2–3/mes)", "Frecuente (semanal)", "Muy frecuente (diaria)"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', now(), null, '["Aplicación"]'::jsonb, 4, 1),

('MG-A3', 'Cuestionario', 'Adopción', '10', '28', '¿Con qué frecuencia compartes con tu equipo dudas o comentarios sobre el uso de nuevas herramientas de IA (aunque todavía no las uses directamente)?', 'Multiple Choice (escala Likert A–E)', '["Nunca", "Rara vez (≤ 1/mes)", "Ocasional (2–3/mes)", "Frecuente (semanal)", "Muy frecuente (diaria)"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', now(), null, '["Aplicación"]'::jsonb, 4, 1),

('MG-A4', 'Cuestionario', 'Adopción', '10', '28', '¿Con qué frecuencia has recibido o solicitado capacitación básica sobre IA o herramientas digitales impartida por tu institución o sindicato?', 'Multiple Choice (escala Likert A–E)', '["Nunca", "Rara vez (≤ 1/mes)", "Ocasional (2–3/mes)", "Frecuente (semanal)", "Muy frecuente (diaria)"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', now(), null, '["Aplicación"]'::jsonb, 4, 1),

('MG-A5', 'Cuestionario', 'Adopción', '10', '28', '¿Con qué frecuencia consideras que una tarea repetitiva (llenado de campos, captura de datos, clasificación de expedientes) podría realizarse de forma más rápida con apoyo de IA u otras automatizaciones?', 'Multiple Choice (escala Likert A–E)', '["Nunca", "Rara vez (≤ 1/mes)", "Ocasional (2–3/mes)", "Frecuente (semanal)", "Muy frecuente (diaria)"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', now(), null, '["Aplicación"]'::jsonb, 4, 1),

('MG-A6', 'Cuestionario', 'Adopción', '10', '28', '¿Con qué frecuencia te preocupa el impacto de la IA en la protección de datos personales y derechos de los ciudadanos atendidos por tu institución?', 'Multiple Choice (escala Likert A–E)', '["Nunca", "Rara vez (≤ 1/mes)", "Ocasional (2–3/mes)", "Frecuente (semanal)", "Muy frecuente (diaria)"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', now(), null, '["Aplicación"]'::jsonb, 4, 1),

('MG-A7', 'Cuestionario', 'Adopción', '10', '28', '¿Con qué frecuencia usas IA para generar borradores de correos, oficios o comunicados que luego editas?', 'Multiple Choice (escala Likert A–E)', '["Nunca", "Rara vez (≤ 1/mes)", "Ocasional (2–3/mes)", "Frecuente (semanal)", "Muy frecuente (diaria)"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', now(), null, '["Aplicación"]'::jsonb, 4, 2),

('MG-A8', 'Cuestionario', 'Adopción', '10', '28', '¿Con qué frecuencia usas IA para resumir documentos extensos (informes, minutas, diagnósticos) que necesitas revisar rápidamente?', 'Multiple Choice (escala Likert A–E)', '["Nunca", "Rara vez (≤ 1/mes)", "Ocasional (2–3/mes)", "Frecuente (semanal)", "Muy frecuente (diaria)"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', now(), null, '["Aplicación"]'::jsonb, 4, 2),

('MG-A9', 'Cuestionario', 'Adopción', '10', '28', '¿Con qué frecuencia revisas y corriges de forma crítica los resultados generados por IA antes de enviarlos a un superior o a la ciudadanía?', 'Multiple Choice (escala Likert A–E)', '["Nunca", "Rara vez (≤ 1/mes)", "Ocasional (2–3/mes)", "Frecuente (semanal)", "Muy frecuente (diaria)"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', now(), null, '["Productividad"]'::jsonb, 4, 2),

('MG-A10', 'Cuestionario', 'Adopción', '10', '28', '¿Con qué frecuencia compartes con tus colegas buenas prácticas o plantillas de prompts para usar IA en su trabajo?', 'Multiple Choice (escala Likert A–E)', '["Nunca", "Rara vez (≤ 1/mes)", "Ocasional (2–3/mes)", "Frecuente (semanal)", "Muy frecuente (diaria)"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', now(), null, '["Aplicación"]'::jsonb, 4, 2),

('MG-A11', 'Cuestionario', 'Adopción', '10', '28', '¿Con qué frecuencia propones a tu jefatura o equipo probar IA en tareas específicas (por ejemplo, clasificar solicitudes, agrupar quejas ciudadanas, preparar reportes)?', 'Multiple Choice (escala Likert A–E)', '["Nunca", "Rara vez (≤ 1/mes)", "Ocasional (2–3/mes)", "Frecuente (semanal)", "Muy frecuente (diaria)"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', now(), null, '["Aplicación", "Productividad"]'::jsonb, 4, 2),

('MG-A12', 'Cuestionario', 'Adopción', '10', '28', '¿Con qué frecuencia dedicas tiempo personal o institucional a aprender sobre nuevas herramientas de IA relevantes para tu área (cursos, tutoriales, guías internas)?', 'Multiple Choice (escala Likert A–E)', '["Nunca", "Rara vez (≤ 1/mes)", "Ocasional (2–3/mes)", "Frecuente (semanal)", "Muy frecuente (diaria)"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', now(), null, '["Aplicación", "Productividad"]'::jsonb, 4, 2),

('MG-A13', 'Cuestionario', 'Adopción', '10', '28', '¿Con qué frecuencia utilizas IA para agrupar, clasificar o priorizar información de expedientes, quejas o solicitudes antes de analizarlas en detalle?', 'Multiple Choice (escala Likert A–E)', '["Nunca", "Rara vez (≤ 1/mes)", "Ocasional (2–3/mes)", "Frecuente (semanal)", "Muy frecuente (diaria)"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', now(), null, '["Estrategia", "Aplicación"]'::jsonb, 4, 3),

('MG-A14', 'Cuestionario', 'Adopción', '10', '28', '¿Con qué frecuencia ajustas tus prompts o instrucciones a la IA para obtener resultados más útiles y específicos para tu área de política o programa?', 'Multiple Choice (escala Likert A–E)', '["Nunca", "Rara vez (≤ 1/mes)", "Ocasional (2–3/mes)", "Frecuente (semanal)", "Muy frecuente (diaria)"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', now(), null, '["Productividad"]'::jsonb, 4, 3),

('MG-A15', 'Cuestionario', 'Adopción', '10', '28', '¿Con qué frecuencia discutes con tu equipo los posibles riesgos éticos (sesgos, inequidad, transparencia) de los usos de IA que están probando?', 'Multiple Choice (escala Likert A–E)', '["Nunca", "Rara vez (≤ 1/mes)", "Ocasional (2–3/mes)", "Frecuente (semanal)", "Muy frecuente (diaria)"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', now(), null, '["Estrategia", "Aplicación"]'::jsonb, 4, 3),

('MG-A16', 'Cuestionario', 'Adopción', '10', '28', '¿Con qué frecuencia participas en reuniones donde se decide en qué procesos del área vale la pena invertir tiempo y recursos en IA?', 'Multiple Choice (escala Likert A–E)', '["Nunca", "Rara vez (≤ 1/mes)", "Ocasional (2–3/mes)", "Frecuente (semanal)", "Muy frecuente (diaria)"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', now(), null, '["Productividad"]'::jsonb, 4, 3),

('MG-A17', 'Cuestionario', 'Adopción', '10', '28', '¿Con qué frecuencia compartes con otras áreas (por ejemplo, TI, jurídico, planeación) resultados o hallazgos obtenidos con apoyo de IA para mejorar procesos conjuntos?', 'Multiple Choice (escala Likert A–E)', '["Nunca", "Rara vez (≤ 1/mes)", "Ocasional (2–3/mes)", "Frecuente (semanal)", "Muy frecuente (diaria)"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', now(), null, '["Productividad"]'::jsonb, 4, 3),

('MG-A18', 'Cuestionario', 'Adopción', '10', '28', '¿Con qué frecuencia ajustas indicadores de desempeño (por ejemplo, tiempos de respuesta, calidad de informes) considerando el uso de IA en tu flujo de trabajo?', 'Multiple Choice (escala Likert A–E)', '["Nunca", "Rara vez (≤ 1/mes)", "Ocasional (2–3/mes)", "Frecuente (semanal)", "Muy frecuente (diaria)"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', now(), null, '["Aplicación", "Productividad"]'::jsonb, 4, 3),

('MG-A19', 'Cuestionario', 'Adopción', '10', '28', '¿Con qué frecuencia lideras o co-lideras iniciativas donde se define un problema público específico y se evalúa si la IA es la herramienta adecuada para abordarlo?', 'Multiple Choice (escala Likert A–E)', '["Nunca", "Rara vez (≤ 1/mes)", "Ocasional (2–3/mes)", "Frecuente (semanal)", "Muy frecuente (diaria)"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', now(), null, '["Estrategia"]'::jsonb, 4, 4),

('MG-A20', 'Cuestionario', 'Adopción', '10', '28', '¿Con qué frecuencia negocias con otras áreas (TI, jurídico, datos, contraloría) las condiciones para implementar o escalar un proyecto de IA?', 'Multiple Choice (escala Likert A–E)', '["Nunca", "Rara vez (≤ 1/mes)", "Ocasional (2–3/mes)", "Frecuente (semanal)", "Muy frecuente (diaria)"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', now(), null, '["Aplicación"]'::jsonb, 4, 4),

('MG-A21', 'Cuestionario', 'Adopción', '10', '28', '¿Con qué frecuencia revisas métricas de desempeño de proyectos donde se usa IA (ej. tiempos de respuesta, calidad de decisiones, quejas ciudadanas) para tomar decisiones de mejora?', 'Multiple Choice (escala Likert A–E)', '["Nunca", "Rara vez (≤ 1/mes)", "Ocasional (2–3/mes)", "Frecuente (semanal)", "Muy frecuente (diaria)"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', now(), null, '["Productividad"]'::jsonb, 4, 4),

('MG-A22', 'Cuestionario', 'Adopción', '10', '28', '¿Con qué frecuencia promueves ajustes a procesos internos (flujos de aprobación, formatos) para aprovechar mejor las capacidades de IA ya disponibles?', 'Multiple Choice (escala Likert A–E)', '["Nunca", "Rara vez (≤ 1/mes)", "Ocasional (2–3/mes)", "Frecuente (semanal)", "Muy frecuente (diaria)"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', now(), null, '["Aplicación"]'::jsonb, 4, 4),

('MG-A23', 'Cuestionario', 'Adopción', '10', '28', '¿Con qué frecuencia aseguras que haya espacios de capacitación y acompañamiento para que el personal más rezagado pueda usar IA de forma segura y efectiva?', 'Multiple Choice (escala Likert A–E)', '["Nunca", "Rara vez (≤ 1/mes)", "Ocasional (2–3/mes)", "Frecuente (semanal)", "Muy frecuente (diaria)"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', now(), null, '["Aplicación"]'::jsonb, 4, 4),

('MG-A24', 'Cuestionario', 'Adopción', '10', '28', '¿Con qué frecuencia incorporas la discusión sobre riesgos éticos y posibles impactos negativos de la IA en documentos oficiales (minutas, términos de referencia, lineamientos)?', 'Multiple Choice (escala Likert A–E)', '["Nunca", "Rara vez (≤ 1/mes)", "Ocasional (2–3/mes)", "Frecuente (semanal)", "Muy frecuente (diaria)"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', now(), null, '["Estrategia"]'::jsonb, 4, 4),

('MG-A25', 'Cuestionario', 'Adopción', '10', '28', '¿Con qué frecuencia lideras el diseño o actualización de lineamientos internos sobre uso responsable de IA (por ejemplo, guías de privacidad, transparencia, supervisión humana)?', 'Multiple Choice (escala Likert A–E)', '["Nunca", "Rara vez (≤ 1/mes)", "Ocasional (2–3/mes)", "Frecuente (semanal)", "Muy frecuente (diaria)"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', now(), null, '["Estrategia", "Aplicación"]'::jsonb, 4, 5),

('MG-A26', 'Cuestionario', 'Adopción', '10', '28', '¿Con qué frecuencia impulsas o participas en evaluaciones independientes o auditorías de sistemas de IA usados por tu institución o por proveedores?', 'Multiple Choice (escala Likert A–E)', '["Nunca", "Rara vez (≤ 1/mes)", "Ocasional (2–3/mes)", "Frecuente (semanal)", "Muy frecuente (diaria)"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', now(), null, '["Estrategia"]'::jsonb, 4, 5),

('MG-A27', 'Cuestionario', 'Adopción', '10', '28', '¿Con qué frecuencia diseñas y facilitas espacios de capacitación o comunidades de práctica para que otros servidores públicos aprendan a usar IA en su trabajo?', 'Multiple Choice (escala Likert A–E)', '["Nunca", "Rara vez (≤ 1/mes)", "Ocasional (2–3/mes)", "Frecuente (semanal)", "Muy frecuente (diaria)"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', now(), null, '["Aplicación"]'::jsonb, 4, 5),

('MG-A28', 'Cuestionario', 'Adopción', '10', '28', '¿Con qué frecuencia integras resultados y lecciones aprendidas de proyectos de IA en documentos estratégicos (planes anuales, programas sectoriales, informes a órganos de control)?', 'Multiple Choice (escala Likert A–E)', '["Nunca", "Rara vez (≤ 1/mes)", "Ocasional (2–3/mes)", "Frecuente (semanal)", "Muy frecuente (diaria)"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', now(), null, '["Productividad"]'::jsonb, 4, 5),

('MG-A29', 'Cuestionario', 'Adopción', '10', '28', '¿Con qué frecuencia intervienes para ajustar o detener proyectos de IA cuando identificas riesgos altos para derechos, equidad o confianza ciudadana?', 'Multiple Choice (escala Likert A–E)', '["Nunca", "Rara vez (≤ 1/mes)", "Ocasional (2–3/mes)", "Frecuente (semanal)", "Muy frecuente (diaria)"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', now(), null, '["Estrategia"]'::jsonb, 4, 5),

('MG-A30', 'Cuestionario', 'Adopción', '10', '28', '¿Con qué frecuencia colaboras con actores externos (academia, sociedad civil, organismos internacionales) para diseñar o evaluar iniciativas de IA en el sector público?', 'Multiple Choice (escala Likert A–E)', '["Nunca", "Rara vez (≤ 1/mes)", "Ocasional (2–3/mes)", "Frecuente (semanal)", "Muy frecuente (diaria)"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', now(), null, '["Estrategia"]'::jsonb, 4, 5);

-- CONOCIMIENTO - Rol 28
INSERT INTO "public"."preguntas" ("codigo", "section", "bloque", "area_id", "exclusivo_rol_id", "texto", "tipo", "opciones", "locale", "peso", "escala", "scoring", "created_at", "respuesta_correcta", "dimension", "exclusivo_nivel_id", "dificultad") VALUES
('MG-C1', 'Cuestionario', 'Conocimiento', '10', '28', '¿Cuál de las siguientes opciones describe mejor qué es la inteligencia artificial (IA) en el contexto del gobierno?', 'Multiple Choice (una respuesta)', '["Un tipo de hardware que reemplaza computadoras", "Programas que imitan algunas capacidades humanas como analizar datos o generar textos", "Un sistema exclusivo para redes sociales", "Solo robots físicos que atienden a la ciudadanía"]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', now(), 'Programas que imitan algunas capacidades humanas como analizar datos o generar textos', '["Conocimiento"]'::jsonb, 4, 1),

('MG-C2', 'Cuestionario', 'Conocimiento', '10', '28', '¿Cuál es un ejemplo simple de IA que ya se usa en muchas instituciones públicas?', 'Multiple Choice (una respuesta)', '["Un archivador físico", "Una hoja de cálculo en blanco", "Un chatbot que responde preguntas frecuentes de la ciudadanía", "Un correo electrónico sin filtros"]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', now(), 'Un chatbot que responde preguntas frecuentes de la ciudadanía', '["Conocimiento"]'::jsonb, 4, 1),

('MG-C3', 'Cuestionario', 'Conocimiento', '10', '28', '¿Cuál es un riesgo importante al usar IA con datos de ciudadanos?', 'Multiple Choice (una respuesta)', '["Que la IA mejore la calidad del servicio", "Que se filtren datos personales o sensibles", "Que se reduzca el tiempo de respuesta", "Que se usen menos hojas impresas"]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', now(), 'Que se filtren datos personales o sensibles', '["Estrategia", "Conocimiento", "Aplicación"]'::jsonb, 4, 1),

('MG-C4', 'Cuestionario', 'Conocimiento', '10', '28', '¿Qué tarea del trabajo cotidiano en gobierno es más fácil de automatizar con IA?', 'Multiple Choice (una respuesta)', '["Definir la política pública nacional", "Firmar documentos legalmente", "Clasificar automáticamente correos o solicitudes por tema", "Sustituir al servidor público en reuniones con ciudadanía"]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', now(), 'Clasificar automáticamente correos o solicitudes por tema', '["Conocimiento", "Productividad"]'::jsonb, 4, 1),

('MG-C5', 'Cuestionario', 'Conocimiento', '10', '28', '¿Qué debe hacer un servidor público antes de usar información generada por IA en un oficio?', 'Multiple Choice (una respuesta)', '["Copiarla tal como sale", "Borrarla por completo", "Revisarla críticamente y compararla con fuentes oficiales", "Compartirla en redes sociales"]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', now(), 'Revisarla críticamente y compararla con fuentes oficiales', '["Conocimiento", "Aplicación"]'::jsonb, 4, 1),

('MG-C6', 'Cuestionario', 'Conocimiento', '10', '28', '¿Por qué es importante que el gobierno use IA de forma responsable?', 'Multiple Choice (una respuesta)', '["Para evitar que los ciudadanos usen internet", "Para reducir la transparencia", "Para mejorar servicios respetando derechos y confianza ciudadana", "Para sustituir al personal público inmediatamente"]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', now(), 'Para mejorar servicios respetando derechos y confianza ciudadana', '["Conocimiento"]'::jsonb, 4, 1),

('MG-C7', 'Cuestionario', 'Conocimiento', '10', '28', '¿Cuál de las siguientes tareas es un uso adecuado de IA generativa en el sector público?', 'Multiple Choice (una respuesta)', '["Inventar datos estadísticos sin fuentes", "Redactar un borrador de informe que luego revisas con tus propios criterios", "Firmar electrónicamente contratos sin leerlos", "Decidir automáticamente quién recibe un beneficio sin supervisión humana"]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', now(), 'Redactar un borrador de informe que luego revisas con tus propios criterios', '["Conocimiento", "Aplicación"]'::jsonb, 4, 2),

('MG-C8', 'Cuestionario', 'Conocimiento', '10', '28', 'Cuando usas IA para traducir un documento, ¿qué recomendación es más adecuada?', 'Multiple Choice (una respuesta)', '["Usar cualquier herramienta, incluso con datos confidenciales", "Publicar la traducción sin revisión", "Revisar que la traducción sea fiel al sentido del original", "Enviar datos personales sensibles a herramientas públicas sin restricciones"]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', now(), 'Revisar que la traducción sea fiel al sentido del original', '["Conocimiento"]'::jsonb, 4, 2),

('MG-C9', 'Cuestionario', 'Conocimiento', '10', '28', '¿Qué describe mejor a un copilot en ofimática (por ejemplo, copilots en hojas de cálculo o documentos)?', 'Multiple Choice (una respuesta)', '["Un sustituto del servidor público", "Un asistente que sugiere textos, fórmulas o gráficos que tú apruebas o corriges", "Un programa que bloquea el uso de IA", "Un sistema que firma documentos legalmente"]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', now(), 'Un asistente que sugiere textos, fórmulas o gráficos que tú apruebas o corriges', '["Conocimiento", "Aplicación"]'::jsonb, 4, 2),

('MG-C10', 'Cuestionario', 'Conocimiento', '10', '28', '¿Qué se entiende por sesgo algorítmico en IA aplicada a programas públicos?', 'Multiple Choice (una respuesta)', '["Que la IA siempre acierta", "Que la IA favorece o perjudica ciertos grupos de forma sistemática", "Que la IA es demasiado rápida", "Que la IA usa distintos idiomas"]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', now(), 'Que la IA favorece o perjudica ciertos grupos de forma sistemática', '["Conocimiento", "Aplicación"]'::jsonb, 4, 2),

('MG-C11', 'Cuestionario', 'Conocimiento', '10', '28', '¿Cuál de los siguientes es un indicador razonable para evaluar el impacto de IA en una ventanilla de atención ciudadana?', 'Multiple Choice (una respuesta)', '["Color de la interfaz del chatbot", "Número de reuniones internas del área", "Tiempo promedio de respuesta y nivel de satisfacción ciudadana", "Número de correos enviados entre áreas"]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', now(), 'Tiempo promedio de respuesta y nivel de satisfacción ciudadana', '["Conocimiento"]'::jsonb, 4, 2),

('MG-C12', 'Cuestionario', 'Conocimiento', '10', '28', '¿Qué representa mejor la inversión en IA para un área operativa de gobierno?', 'Multiple Choice (una respuesta)', '["Solo comprar licencias sin capacitar al personal", "Tiempo de aprendizaje, capacitación y ajustes de procesos para usar IA", "Cambiar el logotipo institucional", "Prohibir el uso de IA"]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', now(), 'Tiempo de aprendizaje, capacitación y ajustes de procesos para usar IA', '["Conocimiento", "Inversión"]'::jsonb, 4, 2),

('MG-C13', 'Cuestionario', 'Conocimiento', '10', '28', 'En un proceso de consulta ciudadana con miles de comentarios, ¿cómo podría usarse la IA de forma responsable?', 'Multiple Choice (una respuesta)', '["Para decidir sola qué propuestas se aprueban", "Para agrupar comentarios por temas y luego analizarlos humanamente", "Para eliminar comentarios negativos", "Para inventar respuestas en nombre de la ciudadanía"]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', now(), 'Para agrupar comentarios por temas y luego analizarlos humanamente', '["Conocimiento"]'::jsonb, 4, 3),

('MG-C14', 'Cuestionario', 'Conocimiento', '10', '28', '¿Qué es importante documentar al usar IA en un análisis que apoya una decisión pública?', 'Multiple Choice (una respuesta)', '["Nada, la IA es una caja mágica", "Solo el resultado final", "El tipo de datos usados, la herramienta, los criterios y las validaciones realizadas", "Únicamente el nombre del servidor público"]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', now(), 'El tipo de datos usados, la herramienta, los criterios y las validaciones realizadas', '["Conocimiento"]'::jsonb, 4, 3),

('MG-C15', 'Cuestionario', 'Conocimiento', '10', '28', 'Cuando se utiliza IA para priorizar expedientes, ¿qué rol debería tener el servidor público?', 'Multiple Choice (una respuesta)', '["Aceptar sin revisar la prioridad sugerida", "Revisar los criterios, validar casos sensibles y corregir errores", "Ignorar totalmente la IA", "Delegar en la IA la comunicación con los ciudadanos"]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', now(), 'Revisar los criterios, validar casos sensibles y corregir errores', '["Estrategia", "Conocimiento", "Aplicación"]'::jsonb, 4, 3),

('MG-C16', 'Cuestionario', 'Conocimiento', '10', '28', '¿Cuál es un beneficio operativo típico de integrar IA en la clasificación de solicitudes ciudadanas?', 'Multiple Choice (una respuesta)', '["Ocultar información al público", "Aumentar deliberadamente los tiempos de espera", "Reducir tiempos de triage y canalizar más rápido al área correcta", "Eliminar la necesidad de supervisores"]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', now(), 'Reducir tiempos de triage y canalizar más rápido al área correcta', '["Conocimiento"]'::jsonb, 4, 3),

('MG-C17', 'Cuestionario', 'Conocimiento', '10', '28', 'En términos de inversión, ¿qué aspecto suele ser ignorado cuando se planifica un piloto de IA en un área operativa?', 'Multiple Choice (una respuesta)', '["Costo de licencias", "Tiempo del personal para pruebas, ajustes y capacitación", "Necesidad de conexión a internet", "Número de escritorios en la oficina"]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', now(), 'Tiempo del personal para pruebas, ajustes y capacitación', '["Estrategia", "Conocimiento", "Inversión"]'::jsonb, 4, 3),

('MG-C18', 'Cuestionario', 'Conocimiento', '10', '28', '¿Qué práctica ayuda a reducir el riesgo de sesgos en modelos de IA usados en programas sociales?', 'Multiple Choice (una respuesta)', '["No documentar nada", "Evaluar el modelo en distintos grupos poblacionales y ajustar reglas de uso", "Usar solo datos de un grupo muy pequeño", "Evitar toda supervisión humana"]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', now(), 'Evaluar el modelo en distintos grupos poblacionales y ajustar reglas de uso', '["Estrategia", "Conocimiento"]'::jsonb, 4, 3),

('MG-C19', 'Cuestionario', 'Conocimiento', '10', '28', '¿Qué elemento es clave al proponer un nuevo caso de uso de IA en un programa público?', 'Multiple Choice (una respuesta)', '["Que use el modelo más complejo disponible", "Que se alinee con un problema público claro y medible", "Que elimine la supervisión humana", "Que solo mejore la apariencia de los reportes"]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', now(), 'Que se alinee con un problema público claro y medible', '["Conocimiento", "Aplicación"]'::jsonb, 4, 4),

('MG-C20', 'Cuestionario', 'Conocimiento', '10', '28', 'En un piloto de IA para atención ciudadana, ¿qué indicador de inversión es más relevante para evaluar si se escala?', 'Multiple Choice (una respuesta)', '["Número de logos del proveedor en las oficinas", "Horas de capacitación del personal y reducción de retrabajos", "Cantidad de likes en redes sociales", "Número de correos internos enviados"]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', now(), 'Horas de capacitación del personal y reducción de retrabajos', '["Conocimiento", "Inversión"]'::jsonb, 4, 4),

('MG-C21', 'Cuestionario', 'Conocimiento', '10', '28', '¿Qué práctica mejora la legitimidad de un proyecto de IA en gobierno?', 'Multiple Choice (una respuesta)', '["Ocultar a la ciudadanía que se usó IA", "Publicar lineamientos claros, explicar el rol de la IA y los mecanismos de queja", "Evitar toda documentación por seguridad", "Desactivar mecanismos de revisión humana"]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', now(), 'Publicar lineamientos claros, explicar el rol de la IA y los mecanismos de queja', '["Conocimiento"]'::jsonb, 4, 4),

('MG-C22', 'Cuestionario', 'Conocimiento', '10', '28', '¿Cuál de estos es un buen ejemplo de uso estratégico de IA en planeación de políticas?', 'Multiple Choice (una respuesta)', '["Elegir políticas solo según lo que proponga un modelo de texto", "Usar IA para explorar escenarios y generar alternativas de política que luego se discuten y ajustan", "Dejar que la IA diseñe el presupuesto sin límites", "Ignorar toda evidencia previa"]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', now(), 'Usar IA para explorar escenarios y generar alternativas de política que luego se discuten y ajustan', '["Conocimiento", "Aplicación"]'::jsonb, 4, 4),

('MG-C23', 'Cuestionario', 'Conocimiento', '10', '28', '¿Qué es deseable incluir en las bases de datos que alimentan proyectos de IA en gobierno?', 'Multiple Choice (una respuesta)', '["Datos sensibles sin anonimización", "Datos desactualizados y sin contexto", "Datos relevantes, actualizados y con medidas de protección (anonimización, minimización)", "Cualquier dato disponible sin revisión"]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', now(), 'Datos relevantes, actualizados y con medidas de protección (anonimización, minimización)', '["Conocimiento", "Aplicación"]'::jsonb, 4, 4),

('MG-C24', 'Cuestionario', 'Conocimiento', '10', '28', 'Cuando varias áreas comparten un mismo modelo de IA, ¿qué es clave para su gobernanza?', 'Multiple Choice (una respuesta)', '["Que no exista responsable claro", "Que cada área cambie el modelo sin coordinarse", "Que haya responsables, protocolos de cambios y seguimiento conjunto de resultados", "Que nadie evalúe el desempeño"]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', now(), 'Que haya responsables, protocolos de cambios y seguimiento conjunto de resultados', '["Estrategia", "Conocimiento"]'::jsonb, 4, 4),

('MG-C25', 'Cuestionario', 'Conocimiento', '10', '28', '¿Qué enfoque es más adecuado para evaluar el impacto de un sistema de IA que apoya decisiones sobre asignación de beneficios públicos?', 'Multiple Choice (una respuesta)', '["Revisar solo si reduce costos", "Analizar también si afecta de manera desigual a grupos vulnerables y si hay canales de apelación", "Ignorar a los grupos afectados", "Considerar solo la opinión del proveedor"]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', now(), 'Analizar también si afecta de manera desigual a grupos vulnerables y si hay canales de apelación', '["Conocimiento"]'::jsonb, 4, 5),

('MG-C26', 'Cuestionario', 'Conocimiento', '10', '28', '¿Qué elemento debe incluirse en una política interna de uso de IA en una institución pública?', 'Multiple Choice (una respuesta)', '["Prohibición absoluta de todo uso de IA", "Libertad total sin restricciones", "Criterios de uso aceptable, manejo de datos, supervisión humana y rendición de cuentas", "Solo la lista de herramientas favoritas de una persona"]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', now(), 'Criterios de uso aceptable, manejo de datos, supervisión humana y rendición de cuentas', '["Conocimiento", "Aplicación"]'::jsonb, 4, 5),

('MG-C27', 'Cuestionario', 'Conocimiento', '10', '28', 'Al diseñar un piloto de IA con un proveedor externo, ¿qué es crítico desde la perspectiva pública?', 'Multiple Choice (una respuesta)', '["Aceptar cláusulas que impidan auditar el sistema", "Asegurar transparencia sobre datos, modelos, métricas y posibilidad de auditoría", "Permitir uso libre de datos personales sin límite", "No establecer mecanismos de salida o reversión"]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', now(), 'Asegurar transparencia sobre datos, modelos, métricas y posibilidad de auditoría', '["Conocimiento"]'::jsonb, 4, 5),

('MG-C28', 'Cuestionario', 'Conocimiento', '10', '28', '¿Qué es una prueba de humano en el circuito (human-in-the-loop) en sistemas de IA del sector público?', 'Multiple Choice (una respuesta)', '["Un sistema que nunca muestra sus resultados", "Un proceso donde la IA decide todo sin revisión", "Un diseño donde una persona revisa y puede corregir o revertir decisiones sugeridas por IA", "Un sistema que no puede ser usado por humanos"]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', now(), 'Un diseño donde una persona revisa y puede corregir o revertir decisiones sugeridas por IA', '["Conocimiento"]'::jsonb, 4, 5),

('MG-C29', 'Cuestionario', 'Conocimiento', '10', '28', 'Desde la perspectiva de inversión pública, ¿qué ayuda a justificar escalar un proyecto de IA?', 'Multiple Choice (una respuesta)', '["Que esté de moda", "Evidencia de ahorros, mejoras en tiempos, satisfacción y menor carga administrativa del personal", "Que un proveedor lo ofrezca gratis al inicio sin condiciones claras", "Que se vea tecnológico"]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', now(), 'Evidencia de ahorros, mejoras en tiempos, satisfacción y menor carga administrativa del personal', '["Conocimiento", "Inversión"]'::jsonb, 4, 5),

('MG-C30', 'Cuestionario', 'Conocimiento', '10', '28', '¿Qué rol tiene un referente interno de IA en la coordinación interinstitucional?', 'Multiple Choice (una respuesta)', '["Impedir que otras áreas usen IA", "Mantener el conocimiento en secreto", "Facilitar espacios de intercambio, estandarizar buenas prácticas y apoyar alineación con marcos legales", "Decidir en solitario sobre todos los proyectos"]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', now(), 'Facilitar espacios de intercambio, estandarizar buenas prácticas y apoyar alineación con marcos legales', '["Conocimiento"]'::jsonb, 4, 5);
