-- ============================================================================
-- PREGUNTAS PARA DIRECCIÓN DE GOBIERNO / POLÍTICAS PÚBLICAS
-- ============================================================================
-- Rol incluido:
--   - Rol ID 27: Dirección de Gobierno / Políticas Públicas (area_id: 10, nivel_id: 2)
-- ============================================================================

-- ============================================================================
-- ROL 27: Dirección de Gobierno / Políticas Públicas
-- ============================================================================

-- ADOPCIÓN - Rol 27
INSERT INTO "public"."preguntas" ("codigo", "section", "bloque", "area_id", "exclusivo_rol_id", "texto", "tipo", "opciones", "locale", "peso", "escala", "scoring", "created_at", "respuesta_correcta", "dimension", "exclusivo_nivel_id", "dificultad") VALUES
('DG-A1', 'Cuestionario', 'Adopción', '10', '27', '¿Con qué frecuencia revisas propuestas o documentos donde se menciona el uso de IA en tu área?', 'Multiple Choice (escala Likert A–E)', '["Nunca", "Rara vez (≤ 1/mes)", "Ocasional (2–3/mes)", "Frecuente (semanal)", "Muy frecuente (diaria)"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', now(), null, '["Aplicación"]'::jsonb, 2, 1),

('DG-A2', 'Cuestionario', 'Adopción', '10', '27', '¿Con qué frecuencia solicitas a tu equipo explicaciones sobre los riesgos éticos de proyectos que incluyen IA (sesgos, privacidad, transparencia)?', 'Multiple Choice (escala Likert A–E)', '["Nunca", "Rara vez (≤ 1/mes)", "Ocasional (2–3/mes)", "Frecuente (semanal)", "Muy frecuente (diaria)"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', now(), null, '["Aplicación", "Estrategia"]'::jsonb, 2, 1),

('DG-A3', 'Cuestionario', 'Adopción', '10', '27', '¿Con qué frecuencia has usado herramientas de IA generativa para redactar borradores de notas, discursos o informes de política?', 'Multiple Choice (escala Likert A–E)', '["Nunca", "Rara vez (≤ 1/mes)", "Ocasional (2–3/mes)", "Frecuente (semanal)", "Muy frecuente (diaria)"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', now(), null, '["Aplicación"]'::jsonb, 2, 1),

('DG-A4', 'Cuestionario', 'Adopción', '10', '27', '¿Con qué frecuencia coordinas con el área de TI o datos para entender si algún proyecto en curso utiliza IA?', 'Multiple Choice (escala Likert A–E)', '["Nunca", "Rara vez (≤ 1/mes)", "Ocasional (2–3/mes)", "Frecuente (semanal)", "Muy frecuente (diaria)"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', now(), null, '["Aplicación"]'::jsonb, 2, 1),

('DG-A5', 'Cuestionario', 'Adopción', '10', '27', '¿Con qué frecuencia incluyes alguna referencia a IA o automatización avanzada en la planeación estratégica o programas de trabajo de tu área?', 'Multiple Choice (escala Likert A–E)', '["Nunca", "Rara vez (≤ 1/mes)", "Ocasional (2–3/mes)", "Frecuente (semanal)", "Muy frecuente (diaria)"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', now(), null, '["Aplicación"]'::jsonb, 2, 1),

('DG-A6', 'Cuestionario', 'Adopción', '10', '27', '¿Con qué frecuencia has decidido no avanzar en una iniciativa de IA por falta de evidencias, lineamientos o claridad en riesgos?', 'Multiple Choice (escala Likert A–E)', '["Nunca", "Rara vez (≤ 1/mes)", "Ocasional (2–3/mes)", "Frecuente (semanal)", "Muy frecuente (diaria)"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', now(), null, '["Estrategia"]'::jsonb, 2, 1),

('DG-A7', 'Cuestionario', 'Adopción', '10', '27', '¿Con qué frecuencia utilizas IA generativa para preparar borradores de documentos oficiales que luego revisas cuidadosamente?', 'Multiple Choice (escala Likert A–E)', '["Nunca", "Rara vez (≤ 1/mes)", "Ocasional (2–3/mes)", "Frecuente (semanal)", "Muy frecuente (diaria)"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', now(), null, '["Aplicación"]'::jsonb, 2, 2),

('DG-A8', 'Cuestionario', 'Adopción', '10', '27', '¿Con qué frecuencia has impulsado la elaboración o actualización de lineamientos internos sobre uso de IA en tu área?', 'Multiple Choice (escala Likert A–E)', '["Nunca", "Rara vez (≤ 1/mes)", "Ocasional (2–3/mes)", "Frecuente (semanal)", "Muy frecuente (diaria)"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', now(), null, '["Aplicación"]'::jsonb, 2, 2),

('DG-A9', 'Cuestionario', 'Adopción', '10', '27', '¿Con qué frecuencia involucras a la unidad jurídica, de transparencia o de protección de datos cuando se analiza un nuevo sistema de IA?', 'Multiple Choice (escala Likert A–E)', '["Nunca", "Rara vez (≤ 1/mes)", "Ocasional (2–3/mes)", "Frecuente (semanal)", "Muy frecuente (diaria)"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', now(), null, '["Aplicación"]'::jsonb, 2, 2),

('DG-A10', 'Cuestionario', 'Adopción', '10', '27', '¿Con qué frecuencia solicitas que los proveedores expliquen de manera comprensible cómo funciona su sistema de IA y qué datos usa?', 'Multiple Choice (escala Likert A–E)', '["Nunca", "Rara vez (≤ 1/mes)", "Ocasional (2–3/mes)", "Frecuente (semanal)", "Muy frecuente (diaria)"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', now(), null, '["Aplicación"]'::jsonb, 2, 2),

('DG-A11', 'Cuestionario', 'Adopción', '10', '27', '¿Con qué frecuencia consideras explícitamente, en reuniones de planeación, el impacto de IA en la productividad del área (tiempos, carga de trabajo, calidad de análisis)?', 'Multiple Choice (escala Likert A–E)', '["Nunca", "Rara vez (≤ 1/mes)", "Ocasional (2–3/mes)", "Frecuente (semanal)", "Muy frecuente (diaria)"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', now(), null, '["Productividad"]'::jsonb, 2, 2),

('DG-A12', 'Cuestionario', 'Adopción', '10', '27', '¿Con qué frecuencia priorizas presupuesto, ya sea de tiempo o dinero, para pilotos pequeños de IA en lugar de grandes implementaciones de alto riesgo?', 'Multiple Choice (escala Likert A–E)', '["Nunca", "Rara vez (≤ 1/mes)", "Ocasional (2–3/mes)", "Frecuente (semanal)", "Muy frecuente (diaria)"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', now(), null, '["Inversión", "Productividad", "Estrategia"]'::jsonb, 2, 2),

('DG-A13', 'Cuestionario', 'Adopción', '10', '27', '¿Con qué frecuencia supervisas proyectos concretos donde se aplica IA en tu área, por ejemplo para priorización, análisis de datos o segmentación?', 'Multiple Choice (escala Likert A–E)', '["Nunca", "Rara vez (≤ 1/mes)", "Ocasional (2–3/mes)", "Frecuente (semanal)", "Muy frecuente (diaria)"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', now(), null, '["Aplicación"]'::jsonb, 2, 3),

('DG-A14', 'Cuestionario', 'Adopción', '10', '27', '¿Con qué frecuencia defines, junto con las áreas de TI y datos, indicadores de desempeño y riesgo para los sistemas de IA en marcha?', 'Multiple Choice (escala Likert A–E)', '["Nunca", "Rara vez (≤ 1/mes)", "Ocasional (2–3/mes)", "Frecuente (semanal)", "Muy frecuente (diaria)"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', now(), null, '["Estrategia", "Aplicación"]'::jsonb, 2, 3),

('DG-A15', 'Cuestionario', 'Adopción', '10', '27', '¿Con qué frecuencia involucras activamente a organizaciones de la sociedad civil, academia u otros actores en el diseño o evaluación de proyectos de IA?', 'Multiple Choice (escala Likert A–E)', '["Nunca", "Rara vez (≤ 1/mes)", "Ocasional (2–3/mes)", "Frecuente (semanal)", "Muy frecuente (diaria)"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', now(), null, '["Aplicación"]'::jsonb, 2, 3),

('DG-A16', 'Cuestionario', 'Adopción', '10', '27', '¿Con qué frecuencia usas información producida por sistemas de IA, como modelos predictivos o clasificaciones, para ajustar programas o priorizar acciones?', 'Multiple Choice (escala Likert A–E)', '["Nunca", "Rara vez (≤ 1/mes)", "Ocasional (2–3/mes)", "Frecuente (semanal)", "Muy frecuente (diaria)"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', now(), null, '["Aplicación", "Estrategia"]'::jsonb, 2, 3),

('DG-A17', 'Cuestionario', 'Adopción', '10', '27', '¿Con qué frecuencia revisas reportes o paneles donde se monitorea el desempeño de sistemas de IA en producción?', 'Multiple Choice (escala Likert A–E)', '["Nunca", "Rara vez (≤ 1/mes)", "Ocasional (2–3/mes)", "Frecuente (semanal)", "Muy frecuente (diaria)"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', now(), null, '["Productividad"]'::jsonb, 2, 3),

('DG-A18', 'Cuestionario', 'Adopción', '10', '27', '¿Con qué frecuencia condicionas la continuidad o el escalamiento de proyectos de IA a resultados medibles y a evaluaciones de riesgo documentadas?', 'Multiple Choice (escala Likert A–E)', '["Nunca", "Rara vez (≤ 1/mes)", "Ocasional (2–3/mes)", "Frecuente (semanal)", "Muy frecuente (diaria)"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', now(), null, '["Productividad", "Estrategia"]'::jsonb, 2, 3),

('DG-A19', 'Cuestionario', 'Adopción', '10', '27', '¿Con qué frecuencia integras objetivos y principios de IA responsable en los documentos estratégicos de tu área, como planes, agendas o marcos de política?', 'Multiple Choice (escala Likert A–E)', '["Nunca", "Rara vez (≤ 1/mes)", "Ocasional (2–3/mes)", "Frecuente (semanal)", "Muy frecuente (diaria)"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', now(), null, '["Aplicación"]'::jsonb, 2, 4),

('DG-A20', 'Cuestionario', 'Adopción', '10', '27', '¿Con qué frecuencia lideras comités o grupos de trabajo interinstitucionales para coordinar la adopción de IA en políticas públicas?', 'Multiple Choice (escala Likert A–E)', '["Nunca", "Rara vez (≤ 1/mes)", "Ocasional (2–3/mes)", "Frecuente (semanal)", "Muy frecuente (diaria)"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', now(), null, '["Aplicación"]'::jsonb, 2, 4),

('DG-A21', 'Cuestionario', 'Adopción', '10', '27', '¿Con qué frecuencia decides iniciar, detener o rediseñar proyectos de IA con base en evaluaciones de impacto algorítmico y evidencias independientes?', 'Multiple Choice (escala Likert A–E)', '["Nunca", "Rara vez (≤ 1/mes)", "Ocasional (2–3/mes)", "Frecuente (semanal)", "Muy frecuente (diaria)"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', now(), null, '["Aplicación"]'::jsonb, 2, 4),

('DG-A22', 'Cuestionario', 'Adopción', '10', '27', '¿Con qué frecuencia impulsas mecanismos de participación ciudadana específicos para proyectos de IA, como consultas, mesas de diálogo o paneles de expertos?', 'Multiple Choice (escala Likert A–E)', '["Nunca", "Rara vez (≤ 1/mes)", "Ocasional (2–3/mes)", "Frecuente (semanal)", "Muy frecuente (diaria)"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', now(), null, '["Aplicación"]'::jsonb, 2, 4),

('DG-A23', 'Cuestionario', 'Adopción', '10', '27', '¿Con qué frecuencia revisas y ajustas el portafolio de proyectos de IA considerando riesgo, valor público y alineación con prioridades?', 'Multiple Choice (escala Likert A–E)', '["Nunca", "Rara vez (≤ 1/mes)", "Ocasional (2–3/mes)", "Frecuente (semanal)", "Muy frecuente (diaria)"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', now(), null, '["Estrategia"]'::jsonb, 2, 4),

('DG-A24', 'Cuestionario', 'Adopción', '10', '27', '¿Con qué frecuencia promueves la publicación proactiva de información sobre los sistemas de IA en uso, incluyendo finalidad, datos utilizados, responsables y mecanismos de reclamo?', 'Multiple Choice (escala Likert A–E)', '["Nunca", "Rara vez (≤ 1/mes)", "Ocasional (2–3/mes)", "Frecuente (semanal)", "Muy frecuente (diaria)"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', now(), null, '["Aplicación"]'::jsonb, 2, 4),

('DG-A25', 'Cuestionario', 'Adopción', '10', '27', '¿Con qué frecuencia participas directamente en el diseño o actualización de marcos regulatorios de IA, como leyes, reglamentos o guías nacionales?', 'Multiple Choice (escala Likert A–E)', '["Nunca", "Rara vez (≤ 1/mes)", "Ocasional (2–3/mes)", "Frecuente (semanal)", "Muy frecuente (diaria)"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', now(), null, '["Aplicación"]'::jsonb, 2, 5),

('DG-A26', 'Cuestionario', 'Adopción', '10', '27', '¿Con qué frecuencia impulsas o presides instancias nacionales o multinivel de coordinación sobre IA con otros niveles de gobierno y organismos autónomos?', 'Multiple Choice (escala Likert A–E)', '["Nunca", "Rara vez (≤ 1/mes)", "Ocasional (2–3/mes)", "Frecuente (semanal)", "Muy frecuente (diaria)"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', now(), null, '["Aplicación"]'::jsonb, 2, 5),

('DG-A27', 'Cuestionario', 'Adopción', '10', '27', '¿Con qué frecuencia impulsas esquemas de sandbox regulatorio, pilotos supervisados o auditorías externas para tecnologías de IA de alto impacto?', 'Multiple Choice (escala Likert A–E)', '["Nunca", "Rara vez (≤ 1/mes)", "Ocasional (2–3/mes)", "Frecuente (semanal)", "Muy frecuente (diaria)"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', now(), null, '["Estrategia"]'::jsonb, 2, 5),

('DG-A28', 'Cuestionario', 'Adopción', '10', '27', '¿Con qué frecuencia incluyes explícitamente requisitos de IA responsable, como explicabilidad, no discriminación, seguridad y gobernanza de datos, en licitaciones y contratos?', 'Multiple Choice (escala Likert A–E)', '["Nunca", "Rara vez (≤ 1/mes)", "Ocasional (2–3/mes)", "Frecuente (semanal)", "Muy frecuente (diaria)"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', now(), null, '["Aplicación", "Estrategia"]'::jsonb, 2, 5),

('DG-A29', 'Cuestionario', 'Adopción', '10', '27', '¿Con qué frecuencia difundes públicamente, por medio de reportes, foros o medios, los aprendizajes, buenas prácticas y fracasos en proyectos de IA de tu área?', 'Multiple Choice (escala Likert A–E)', '["Nunca", "Rara vez (≤ 1/mes)", "Ocasional (2–3/mes)", "Frecuente (semanal)", "Muy frecuente (diaria)"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', now(), null, '["Productividad"]'::jsonb, 2, 5),

('DG-A30', 'Cuestionario', 'Adopción', '10', '27', '¿Con qué frecuencia promueves que la experiencia de tu área en IA sirva como referencia para otros gobiernos, por ejemplo mediante colaboraciones internacionales, redes o estándares?', 'Multiple Choice (escala Likert A–E)', '["Nunca", "Rara vez (≤ 1/mes)", "Ocasional (2–3/mes)", "Frecuente (semanal)", "Muy frecuente (diaria)"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', now(), null, '["Aplicación"]'::jsonb, 2, 5);

-- CONOCIMIENTO - Rol 27
INSERT INTO "public"."preguntas" ("codigo", "section", "bloque", "area_id", "exclusivo_rol_id", "texto", "tipo", "opciones", "locale", "peso", "escala", "scoring", "created_at", "respuesta_correcta", "dimension", "exclusivo_nivel_id", "dificultad") VALUES
('DG-C1', 'Cuestionario', 'Conocimiento', '10', '27', '¿Cuál de las siguientes definiciones describe mejor la inteligencia artificial en el contexto de gobierno?', 'Multiple Choice (una respuesta)', '["Un software que reemplaza completamente a los servidores públicos.", "Sistemas que procesan datos y aprenden patrones para apoyar o automatizar decisiones.", "Un tipo de hardware especializado para computadoras gubernamentales.", "Solo chatbots que responden preguntas ciudadanas."]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', now(), 'Sistemas que procesan datos y aprenden patrones para apoyar o automatizar decisiones.', '["Conocimiento"]'::jsonb, 2, 1),

('DG-C2', 'Cuestionario', 'Conocimiento', '10', '27', 'Un ejemplo básico de uso de IA en políticas públicas es:', 'Multiple Choice (una respuesta)', '["Cambiar el logotipo del ministerio.", "Usar modelos para predecir demanda de servicios y planear capacidad.", "Imprimir normas en papel reciclado.", "Aumentar el número de reuniones presenciales."]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', now(), 'Usar modelos para predecir demanda de servicios y planear capacidad.', '["Aplicación", "Conocimiento"]'::jsonb, 2, 1),

('DG-C3', 'Cuestionario', 'Conocimiento', '10', '27', '¿Qué riesgo ético es más relevante al usar IA para priorizar beneficiarios de un programa social?', 'Multiple Choice (una respuesta)', '["Disminuir el número de correos electrónicos.", "Introducir sesgos que discriminen a ciertos grupos.", "Aumentar el tamaño de la institución.", "Mejorar la velocidad del internet institucional."]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', now(), 'Introducir sesgos que discriminen a ciertos grupos.', '["Estrategia", "Conocimiento"]'::jsonb, 2, 1),

('DG-C4', 'Cuestionario', 'Conocimiento', '10', '27', 'Cuando se habla de transparencia algorítmica en gobierno, se refiere principalmente a:', 'Multiple Choice (una respuesta)', '["Hacer públicas las direcciones de los servidores.", "Explicar criterios, datos y efectos de los sistemas de IA que impactan a la ciudadanía.", "Compartir todas las contraseñas de sistemas con la prensa.", "Prohibir cualquier automatización en decisiones."]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', now(), 'Explicar criterios, datos y efectos de los sistemas de IA que impactan a la ciudadanía.', '["Conocimiento"]'::jsonb, 2, 1),

('DG-C5', 'Cuestionario', 'Conocimiento', '10', '27', '¿Cuál es el rol mínimo deseable de una dirección de gobierno frente a proyectos de IA liderados por el área de TI?', 'Multiple Choice (una respuesta)', '["No involucrarse, porque es un tema técnico.", "Validar su alineación con objetivos de política pública y marcos normativos.", "Delegar todo al proveedor externo.", "Revisar solo el presupuesto, sin ver el diseño del sistema."]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', now(), 'Validar su alineación con objetivos de política pública y marcos normativos.', '["Conocimiento"]'::jsonb, 2, 1),

('DG-C6', 'Cuestionario', 'Conocimiento', '10', '27', 'Respecto al presupuesto en proyectos de IA en gobierno, un aspecto clave es:', 'Multiple Choice (una respuesta)', '["Gastar lo más posible para “no perder la ola”.", "Exigir evidencia de impacto y sostenibilidad antes de escalar.", "Evitar cualquier gasto en datos o capacitación interna.", "Contratar IA solo si es gratuita."]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', now(), 'Exigir evidencia de impacto y sostenibilidad antes de escalar.', '["Inversión", "Conocimiento"]'::jsonb, 2, 1),

('DG-C7', 'Cuestionario', 'Conocimiento', '10', '27', 'En el contexto de políticas públicas, un caso de uso típico de IA generativa es:', 'Multiple Choice (una respuesta)', '["Firmar electrónicamente contratos.", "Redactar borradores de informes y luego ajustarlos con criterio humano.", "Sustituir completamente al área jurídica.", "Decidir automáticamente qué leyes deben aprobarse."]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', now(), 'Redactar borradores de informes y luego ajustarlos con criterio humano.', '["Aplicación", "Conocimiento"]'::jsonb, 2, 2),

('DG-C8', 'Cuestionario', 'Conocimiento', '10', '27', '¿Qué aspecto es más importante al usar IA para resumir comentarios ciudadanos en una consulta pública?', 'Multiple Choice (una respuesta)', '["La velocidad sin importar la precisión.", "La forma visual de los gráficos.", "Verificar que la síntesis no distorsione posiciones minoritarias relevantes.", "Que el documento sea muy corto."]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', now(), 'Verificar que la síntesis no distorsione posiciones minoritarias relevantes.', '["Conocimiento"]'::jsonb, 2, 2),

('DG-C9', 'Cuestionario', 'Conocimiento', '10', '27', 'Un lineamiento interno de uso de IA en tu área debería incluir al menos:', 'Multiple Choice (una respuesta)', '["Lista de marcas de IA que están de moda.", "Reglas sobre protección de datos, sesgos y revisión humana de resultados.", "Instrucciones para usar redes sociales.", "Obligación de usar IA en cada decisión."]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', now(), 'Reglas sobre protección de datos, sesgos y revisión humana de resultados.', '["Aplicación", "Conocimiento"]'::jsonb, 2, 2),

('DG-C10', 'Cuestionario', 'Conocimiento', '10', '27', 'Si un proveedor ofrece un sistema de IA caja negra para decisiones sensibles, la prioridad debería ser:', 'Multiple Choice (una respuesta)', '["Aceptar el sistema porque “todos lo usan”.", "Evaluar condiciones de transparencia, explicabilidad y, si no se cumplen, limitar su uso.", "Dejar que lo pruebe otro país primero.", "Solo negociar un mejor precio."]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', now(), 'Evaluar condiciones de transparencia, explicabilidad y, si no se cumplen, limitar su uso.', '["Conocimiento"]'::jsonb, 2, 2),

('DG-C11', 'Cuestionario', 'Conocimiento', '10', '27', 'Al planear el presupuesto de un proyecto piloto con IA, ¿qué rubro es crítico considerar?', 'Multiple Choice (una respuesta)', '["Solo licencias de software.", "Formación de equipos internos y gestión de cambio.", "Decoración de oficinas.", "Viajes internacionales sin relación con el proyecto."]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', now(), 'Formación de equipos internos y gestión de cambio.', '["Inversión", "Conocimiento"]'::jsonb, 2, 2),

('DG-C12', 'Cuestionario', 'Conocimiento', '10', '27', 'El principal rol de la revisión humana en decisiones asistidas por IA es:', 'Multiple Choice (una respuesta)', '["Aprobar automáticamente lo que diga el sistema.", "Corregir errores, cuestionar sesgos y validar la decisión antes de aplicarla.", "Elegir los colores del tablero de datos.", "Acelerar procesos sin revisar nada."]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', now(), 'Corregir errores, cuestionar sesgos y validar la decisión antes de aplicarla.', '["Conocimiento"]'::jsonb, 2, 2),

('DG-C13', 'Cuestionario', 'Conocimiento', '10', '27', 'Para evaluar un proyecto de IA que clasifica solicitudes ciudadanas por prioridad, ¿qué indicador es clave?', 'Multiple Choice (una respuesta)', '["El color del dashboard.", "La precisión, pero también métricas de equidad entre grupos.", "La marca del proveedor.", "La longitud del manual de usuario."]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', now(), 'La precisión, pero también métricas de equidad entre grupos.', '["Conocimiento"]'::jsonb, 2, 3),

('DG-C14', 'Cuestionario', 'Conocimiento', '10', '27', '¿Qué es un piloto controlado de IA en contexto gubernamental?', 'Multiple Choice (una respuesta)', '["Un despliegue masivo nacional.", "Una prueba acotada en alcance, tiempos y población, con evaluación explícita de resultados.", "Una prueba sin seguimiento ni métricas.", "Un simulacro solo para foto política."]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', now(), 'Una prueba acotada en alcance, tiempos y población, con evaluación explícita de resultados.', '["Conocimiento"]'::jsonb, 2, 3),

('DG-C15', 'Cuestionario', 'Conocimiento', '10', '27', 'Ante un modelo de IA que mejora la productividad pero aumenta el riesgo de error grave para casos sensibles, la dirección debería:', 'Multiple Choice (una respuesta)', '["Maximizar productividad sin considerar riesgos.", "Ajustar el diseño, por ejemplo con revisión humana, exclusión de ciertos casos o umbrales, antes de adoptarlo.", "Ignorarlo totalmente.", "Dejar que la decisión la tome solo el proveedor."]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', now(), 'Ajustar el diseño, por ejemplo con revisión humana, exclusión de ciertos casos o umbrales, antes de adoptarlo.', '["Productividad", "Estrategia", "Conocimiento"]'::jsonb, 2, 3),

('DG-C16', 'Cuestionario', 'Conocimiento', '10', '27', '¿Qué describe mejor un pipeline de datos robusto para IA en gobierno?', 'Multiple Choice (una respuesta)', '["Archivos dispersos sin control de calidad.", "Procesos claros de captura, limpieza, documentación y actualización de datos.", "Cualquier hoja de cálculo compartida por correo.", "Datos comprados sin verificar su origen."]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', now(), 'Procesos claros de captura, limpieza, documentación y actualización de datos.', '["Aplicación", "Conocimiento"]'::jsonb, 2, 3),

('DG-C17', 'Cuestionario', 'Conocimiento', '10', '27', 'La participación ciudadana en proyectos de IA debe:', 'Multiple Choice (una respuesta)', '["Omitirse porque “la gente no entiende de tecnología”.", "Integrarse en etapas clave, como diseño, prueba y evaluación, cuando la IA afecta derechos o servicios.", "Restringirse a una nota de prensa al final.", "Delegarse completamente a proveedores."]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', now(), 'Integrarse en etapas clave, como diseño, prueba y evaluación, cuando la IA afecta derechos o servicios.', '["Conocimiento"]'::jsonb, 2, 3),

('DG-C18', 'Cuestionario', 'Conocimiento', '10', '27', '¿Cuál es una señal de que un proyecto de IA requiere supervisión regulatoria adicional?', 'Multiple Choice (una respuesta)', '["Que use un logotipo atractivo.", "Que impacte decisiones de alto riesgo, como libertades, acceso a beneficios o seguridad.", "Que no use datos personales.", "Que funcione solo en horario laboral."]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', now(), 'Que impacte decisiones de alto riesgo, como libertades, acceso a beneficios o seguridad.', '["Conocimiento"]'::jsonb, 2, 3),

('DG-C19', 'Cuestionario', 'Conocimiento', '10', '27', 'Un marco de gobernanza de IA en gobierno debe incluir, al menos:', 'Multiple Choice (una respuesta)', '["Reglas de uso de redes sociales personales.", "Roles y responsabilidades, gestión de riesgos, transparencia, participación y mecanismos de auditoría.", "Recomendaciones de compra de hardware.", "Solo lineamientos sobre comunicación institucional."]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', now(), 'Roles y responsabilidades, gestión de riesgos, transparencia, participación y mecanismos de auditoría.', '["Estrategia", "Conocimiento"]'::jsonb, 2, 4),

('DG-C20', 'Cuestionario', 'Conocimiento', '10', '27', '¿Cuál es un ejemplo de evaluación de impacto algorítmico?', 'Multiple Choice (una respuesta)', '["Medir la felicidad del equipo de TI.", "Analizar de forma estructurada los posibles impactos de un sistema de IA en derechos, equidad, transparencia y rendimiento.", "Revisar el número de correos enviados al día.", "Contar la cantidad de líneas de código."]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', now(), 'Analizar de forma estructurada los posibles impactos de un sistema de IA en derechos, equidad, transparencia y rendimiento.', '["Conocimiento"]'::jsonb, 2, 4),

('DG-C21', 'Cuestionario', 'Conocimiento', '10', '27', 'En un portafolio de proyectos de IA, un enfoque estratégico de inversión implica:', 'Multiple Choice (una respuesta)', '["Financiar solo proyectos de moda.", "Balancear pilotos de alto riesgo con proyectos de valor rápido y bajo riesgo, alineados a prioridades de gobierno.", "Distribuir el presupuesto al azar.", "Destinar todo el presupuesto a un único proyecto emblemático."]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', now(), 'Balancear pilotos de alto riesgo con proyectos de valor rápido y bajo riesgo, alineados a prioridades de gobierno.', '["Inversión", "Conocimiento"]'::jsonb, 2, 4),

('DG-C22', 'Cuestionario', 'Conocimiento', '10', '27', '¿Qué papel debe jugar una dirección de políticas públicas en las decisiones sobre datos para IA?', 'Multiple Choice (una respuesta)', '["Ninguno; es solo tema técnico.", "Definir criterios sobre qué datos son legítimos, relevantes y proporcionales en función del fin de política.", "Solo aprobar el presupuesto de almacenamiento.", "Delegar todo a proveedores externos."]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', now(), 'Definir criterios sobre qué datos son legítimos, relevantes y proporcionales en función del fin de política.', '["Aplicación", "Conocimiento"]'::jsonb, 2, 4),

('DG-C23', 'Cuestionario', 'Conocimiento', '10', '27', 'La alineación entre marcos legales nacionales y guías internacionales de IA, por ejemplo las de la OCDE, es importante porque:', 'Multiple Choice (una respuesta)', '["Permite ignorar la legislación local.", "Facilita cooperación, coherencia regulatoria y credibilidad internacional.", "Solo sirve para obtener premios.", "Evita cualquier responsabilidad gubernamental."]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', now(), 'Facilita cooperación, coherencia regulatoria y credibilidad internacional.', '["Conocimiento"]'::jsonb, 2, 4),

('DG-C24', 'Cuestionario', 'Conocimiento', '10', '27', 'Un esquema de rendición de cuentas sobre IA en tu área debe incluir:', 'Multiple Choice (una respuesta)', '["Solo un comunicado de prensa al inicio del proyecto.", "Informes periódicos públicos sobre desempeño, riesgos y acciones correctivas.", "Reuniones cerradas sin registro.", "Publicar únicamente resultados positivos."]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', now(), 'Informes periódicos públicos sobre desempeño, riesgos y acciones correctivas.', '["Conocimiento"]'::jsonb, 2, 4),

('DG-C25', 'Cuestionario', 'Conocimiento', '10', '27', 'Un sandbox regulatorio de IA en políticas públicas consiste en:', 'Multiple Choice (una respuesta)', '["Probar IA sin reglas ni supervisión.", "Un entorno controlado donde se prueban innovaciones de IA con salvaguardas, supervisión y reglas claras.", "Un laboratorio secreto de proveedores.", "Un evento de marketing tecnológico."]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', now(), 'Un entorno controlado donde se prueban innovaciones de IA con salvaguardas, supervisión y reglas claras.', '["Conocimiento"]'::jsonb, 2, 5),

('DG-C26', 'Cuestionario', 'Conocimiento', '10', '27', 'En un marco nacional de IA, la obligación de explicar decisiones automatizadas busca principalmente:', 'Multiple Choice (una respuesta)', '["Aumentar carga burocrática.", "Garantizar que las personas afectadas comprendan y puedan cuestionar decisiones importantes.", "Sustituir el derecho a la apelación.", "Favorecer a grandes proveedores."]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', now(), 'Garantizar que las personas afectadas comprendan y puedan cuestionar decisiones importantes.', '["Conocimiento"]'::jsonb, 2, 5),

('DG-C27', 'Cuestionario', 'Conocimiento', '10', '27', '¿Qué describe mejor una arquitectura institucional para gobernanza de IA a nivel país o región?', 'Multiple Choice (una respuesta)', '["Un solo responsable sin coordinación con otros actores.", "Conjunto de instituciones, comités y normas que se reparten roles, como regulación, supervisión, asesoría técnica y participación, de forma coherente.", "Solo una oficina de TI central.", "Solo un consejo consultivo sin poder real."]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', now(), 'Conjunto de instituciones, comités y normas que se reparten roles, como regulación, supervisión, asesoría técnica y participación, de forma coherente.', '["Estrategia", "Conocimiento"]'::jsonb, 2, 5),

('DG-C28', 'Cuestionario', 'Conocimiento', '10', '27', 'Un enfoque de IA centrada en derechos humanos implica:', 'Multiple Choice (una respuesta)', '["Maximizar uso de datos sin restricciones.", "Priorizar el respeto y protección de derechos en el diseño, implementación y supervisión de sistemas de IA.", "Focalizarse solo en eficiencia fiscal.", "Dejar las cuestiones de derechos para los tribunales."]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', now(), 'Priorizar el respeto y protección de derechos en el diseño, implementación y supervisión de sistemas de IA.', '["Conocimiento"]'::jsonb, 2, 5),

('DG-C29', 'Cuestionario', 'Conocimiento', '10', '27', '¿Cuál es un rol clave de una dirección de gobierno referente en IA respecto al sector privado y proveedores?', 'Multiple Choice (una respuesta)', '["Aceptar todas las propuestas para acelerar la innovación.", "Definir estándares mínimos y condiciones de contratación que exijan IA responsable, explicable y evaluable.", "Dejar que el mercado se autorregule completamente.", "Negociar solo precios bajos."]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', now(), 'Definir estándares mínimos y condiciones de contratación que exijan IA responsable, explicable y evaluable.', '["Conocimiento"]'::jsonb, 2, 5),

('DG-C30', 'Cuestionario', 'Conocimiento', '10', '27', 'En un contexto de alta madurez, la evaluación externa independiente de sistemas de IA:', 'Multiple Choice (una respuesta)', '["Es innecesaria si el proveedor es reconocido.", "Aporta legitimidad y detecta riesgos que la administración no ve internamente.", "Solo retrasa decisiones políticas.", "Debe evitarse para no exponer problemas."]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', now(), 'Aporta legitimidad y detecta riesgos que la administración no ve internamente.', '["Conocimiento"]'::jsonb, 2, 5);
