-- ============================================================================
-- PREGUNTAS PARA CTO / DIRECTOR(A) DE TECNOLOGÍA
-- ============================================================================
-- Rol incluido:
--   - Rol ID 3: CTO / Director(a) de Tecnología (area_id: 9, nivel_id: 2)
-- ============================================================================

-- ============================================================================
-- ROL 3: CTO / Director(a) de Tecnología
-- ============================================================================

-- ADOPCIÓN - Rol 3
INSERT INTO "public"."preguntas" ("codigo", "section", "bloque", "area_id", "exclusivo_rol_id", "texto", "tipo", "opciones", "locale", "peso", "escala", "scoring", "created_at", "respuesta_correcta", "dimension", "exclusivo_nivel_id", "dificultad") VALUES
('CTO-A1', 'Cuestionario', 'Adopción', '9', '3', '¿Con qué frecuencia utilizas herramientas de IA (p. ej. ChatGPT, Copilot) para revisar o redactar documentos técnicos, RFPs o correos clave?', 'Multiple Choice (escala Likert A–E)', '["Nunca", "Rara vez (≤ 1/mes)", "Ocasional (2–3/mes)", "Frecuente (semanal)", "Muy frecuente (diaria)"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', now(), null, '["Aplicación"]'::jsonb, 2, 1),

('CTO-A2', 'Cuestionario', 'Adopción', '9', '3', '¿Con qué frecuencia impulsas o apruebas pequeños pilotos de IA dentro del área de Tecnología (p. ej. un chatbot interno para FAQs de TI)?', 'Multiple Choice (escala Likert A–E)', '["Nunca", "Rara vez (≤ 1/mes)", "Ocasional (2–3/mes)", "Frecuente (semanal)", "Muy frecuente (diaria)"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', now(), null, '["Aplicación"]'::jsonb, 2, 1),

('CTO-A3', 'Cuestionario', 'Adopción', '9', '3', '¿Con qué frecuencia discutes explícitamente riesgos de datos y ética de IA con tu CISO, legal o compliance cuando surgen nuevas ideas de IA?', 'Multiple Choice (escala Likert A–E)', '["Nunca", "Rara vez (≤ 1/mes)", "Ocasional (2–3/mes)", "Frecuente (semanal)", "Muy frecuente (diaria)"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', now(), null, '["Aplicación", "Estrategia"]'::jsonb, 2, 1),

('CTO-A4', 'Cuestionario', 'Adopción', '9', '3', '¿Con qué frecuencia pides a tu equipo estimaciones de tiempo ahorrado o mejora de calidad al usar IA en tareas de TI?', 'Multiple Choice (escala Likert A–E)', '["Nunca", "Rara vez (≤ 1/mes)", "Ocasional (2–3/mes)", "Frecuente (semanal)", "Muy frecuente (diaria)"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', now(), null, '["Aplicación", "Productividad"]'::jsonb, 2, 1),

('CTO-A5', 'Cuestionario', 'Adopción', '9', '3', '¿Con qué frecuencia incluyes a IA como tema en comités de arquitectura, planes de roadmap tecnológico o revisiones trimestrales?', 'Multiple Choice (escala Likert A–E)', '["Nunca", "Rara vez (≤ 1/mes)", "Ocasional (2–3/mes)", "Frecuente (semanal)", "Muy frecuente (diaria)"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', now(), null, '["Estrategia"]'::jsonb, 2, 1),

('CTO-A6', 'Cuestionario', 'Adopción', '9', '3', '¿Con qué frecuencia coordinas con otros C-level (CEO, CFO, CHRO) para explorar oportunidades de IA más allá del área de TI?', 'Multiple Choice (escala Likert A–E)', '["Nunca", "Rara vez (≤ 1/mes)", "Ocasional (2–3/mes)", "Frecuente (semanal)", "Muy frecuente (diaria)"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', now(), null, '["Aplicación"]'::jsonb, 2, 1),

('CTO-A7', 'Cuestionario', 'Adopción', '9', '3', '¿Con qué frecuencia documentas y revisas, al cierre de un piloto, métricas de impacto (tiempo, costo, calidad) frente a la situación base?', 'Multiple Choice (escala Likert A–E)', '["Nunca", "Rara vez (≤ 1/mes)", "Ocasional (2–3/mes)", "Frecuente (semanal)", "Muy frecuente (diaria)"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', now(), null, '["Inversión", "Productividad"]'::jsonb, 2, 2),

('CTO-A8', 'Cuestionario', 'Adopción', '9', '3', '¿Con qué frecuencia involucras a usuarios finales (soporte TI, devs, negocio) en la definición de casos de uso a pilotear con IA?', 'Multiple Choice (escala Likert A–E)', '["Nunca", "Rara vez (≤ 1/mes)", "Ocasional (2–3/mes)", "Frecuente (semanal)", "Muy frecuente (diaria)"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', now(), null, '["Aplicación"]'::jsonb, 2, 2),

('CTO-A9', 'Cuestionario', 'Adopción', '9', '3', '¿Con qué frecuencia condicionas nuevas inversiones en IA a evidencias mínimas de impacto de pilotos anteriores?', 'Multiple Choice (escala Likert A–E)', '["Nunca", "Rara vez (≤ 1/mes)", "Ocasional (2–3/mes)", "Frecuente (semanal)", "Muy frecuente (diaria)"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', now(), null, '["Aplicación"]'::jsonb, 2, 2),

('CTO-A10', 'Cuestionario', 'Adopción', '9', '3', '¿Con qué frecuencia defines lineamientos claros para que los equipos NO suban datos sensibles a herramientas externas de IA?', 'Multiple Choice (escala Likert A–E)', '["Nunca", "Rara vez (≤ 1/mes)", "Ocasional (2–3/mes)", "Frecuente (semanal)", "Muy frecuente (diaria)"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', now(), null, '["Aplicación"]'::jsonb, 2, 2),

('CTO-A11', 'Cuestionario', 'Adopción', '9', '3', '¿Con qué frecuencia evalúas, junto con el CFO, el presupuesto necesario para pasar de pilotos a soluciones en producción?', 'Multiple Choice (escala Likert A–E)', '["Nunca", "Rara vez (≤ 1/mes)", "Ocasional (2–3/mes)", "Frecuente (semanal)", "Muy frecuente (diaria)"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', now(), null, '["Inversión"]'::jsonb, 2, 2),

('CTO-A12', 'Cuestionario', 'Adopción', '9', '3', '¿Con qué frecuencia incorporas resultados de pilotos de IA en presentaciones a la alta dirección (board, comité ejecutivo)?', 'Multiple Choice (escala Likert A–E)', '["Nunca", "Rara vez (≤ 1/mes)", "Ocasional (2–3/mes)", "Frecuente (semanal)", "Muy frecuente (diaria)"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', now(), null, '["Productividad"]'::jsonb, 2, 2),

('CTO-A13', 'Cuestionario', 'Adopción', '9', '3', '¿Con qué frecuencia revisas, junto con negocio, KPIs de soluciones de IA en producción (ej. NPS, tiempo de resolución, ingresos, fraudes evitados)?', 'Multiple Choice (escala Likert A–E)', '["Nunca", "Rara vez (≤ 1/mes)", "Ocasional (2–3/mes)", "Frecuente (semanal)", "Muy frecuente (diaria)"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', now(), null, '["Productividad"]'::jsonb, 2, 3),

('CTO-A14', 'Cuestionario', 'Adopción', '9', '3', '¿Con qué frecuencia promueves que nuevas aplicaciones internas consuman IA a través de APIs y servicios compartidos, en lugar de soluciones ad-hoc?', 'Multiple Choice (escala Likert A–E)', '["Nunca", "Rara vez (≤ 1/mes)", "Ocasional (2–3/mes)", "Frecuente (semanal)", "Muy frecuente (diaria)"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', now(), null, '["Aplicación"]'::jsonb, 2, 3),

('CTO-A15', 'Cuestionario', 'Adopción', '9', '3', '¿Con qué frecuencia asignas presupuesto específico para observabilidad de modelos (logs, métricas, alertas de drift)?', 'Multiple Choice (escala Likert A–E)', '["Nunca", "Rara vez (≤ 1/mes)", "Ocasional (2–3/mes)", "Frecuente (semanal)", "Muy frecuente (diaria)"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', now(), null, '["Inversión", "Productividad"]'::jsonb, 2, 3),

('CTO-A16', 'Cuestionario', 'Adopción', '9', '3', '¿Con qué frecuencia involucras a equipos multidisciplinares (datos, producto, legal, riesgo, negocio) en el diseño de nuevas soluciones de IA?', 'Multiple Choice (escala Likert A–E)', '["Nunca", "Rara vez (≤ 1/mes)", "Ocasional (2–3/mes)", "Frecuente (semanal)", "Muy frecuente (diaria)"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', now(), null, '["Aplicación", "Estrategia"]'::jsonb, 2, 3),

('CTO-A17', 'Cuestionario', 'Adopción', '9', '3', '¿Con qué frecuencia revisas contratos y SLAs con proveedores de IA (cloud, APIs) para optimizar costos frente a uso real?', 'Multiple Choice (escala Likert A–E)', '["Nunca", "Rara vez (≤ 1/mes)", "Ocasional (2–3/mes)", "Frecuente (semanal)", "Muy frecuente (diaria)"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', now(), null, '["Aplicación", "Inversión", "Productividad"]'::jsonb, 2, 3),

('CTO-A18', 'Cuestionario', 'Adopción', '9', '3', '¿Con qué frecuencia determinas, junto con el CISO, umbrales y alertas específicos para detectar usos anómalos de IA (abuso de prompts, extracción de datos, etc.)?', 'Multiple Choice (escala Likert A–E)', '["Nunca", "Rara vez (≤ 1/mes)", "Ocasional (2–3/mes)", "Frecuente (semanal)", "Muy frecuente (diaria)"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', now(), null, '["Aplicación"]'::jsonb, 2, 3),

('CTO-A19', 'Cuestionario', 'Adopción', '9', '3', '¿Con qué frecuencia revisas el roadmap de la plataforma de IA con líderes de producto, datos y negocio para alinear capacidades técnicas con prioridades estratégicas?', 'Multiple Choice (escala Likert A–E)', '["Nunca", "Rara vez (≤ 1/mes)", "Ocasional (2–3/mes)", "Frecuente (semanal)", "Muy frecuente (diaria)"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', now(), null, '["Aplicación", "Estrategia"]'::jsonb, 2, 4),

('CTO-A20', 'Cuestionario', 'Adopción', '9', '3', '¿Con qué frecuencia decides estandarizar nuevos casos de uso de IA como servicios o componentes reutilizables (en lugar de soluciones 100% específicas)?', 'Multiple Choice (escala Likert A–E)', '["Nunca", "Rara vez (≤ 1/mes)", "Ocasional (2–3/mes)", "Frecuente (semanal)", "Muy frecuente (diaria)"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', now(), null, '["Aplicación"]'::jsonb, 2, 4),

('CTO-A21', 'Cuestionario', 'Adopción', '9', '3', '¿Con qué frecuencia discutes con el CFO y el área de compras esquemas de pricing y contratos multi-proveedor para IA (on-prem, nube, APIs)?', 'Multiple Choice (escala Likert A–E)', '["Nunca", "Rara vez (≤ 1/mes)", "Ocasional (2–3/mes)", "Frecuente (semanal)", "Muy frecuente (diaria)"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', now(), null, '["Aplicación"]'::jsonb, 2, 4),

('CTO-A22', 'Cuestionario', 'Adopción', '9', '3', '¿Con qué frecuencia revisas, con el CISO, métricas de seguridad y compliance específicas de IA (data residency, uso de PII, respuestas tóxicas, etc.)?', 'Multiple Choice (escala Likert A–E)', '["Nunca", "Rara vez (≤ 1/mes)", "Ocasional (2–3/mes)", "Frecuente (semanal)", "Muy frecuente (diaria)"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', now(), null, '["Aplicación", "Estrategia", "Productividad"]'::jsonb, 2, 4),

('CTO-A23', 'Cuestionario', 'Adopción', '9', '3', '¿Con qué frecuencia incluyes a IA y la plataforma corporativa en tus decisiones de modernización de sistemas legacy (rehost, refactor, replace)?', 'Multiple Choice (escala Likert A–E)', '["Nunca", "Rara vez (≤ 1/mes)", "Ocasional (2–3/mes)", "Frecuente (semanal)", "Muy frecuente (diaria)"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', now(), null, '["Aplicación"]'::jsonb, 2, 4),

('CTO-A24', 'Cuestionario', 'Adopción', '9', '3', '¿Con qué frecuencia reservas presupuesto para formación interna (ingeniería de prompts, MLOps, seguridad en IA) asociada al uso de la plataforma?', 'Multiple Choice (escala Likert A–E)', '["Nunca", "Rara vez (≤ 1/mes)", "Ocasional (2–3/mes)", "Frecuente (semanal)", "Muy frecuente (diaria)"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', now(), null, '["Aplicación", "Inversión", "Estrategia"]'::jsonb, 2, 4),

('CTO-A25', 'Cuestionario', 'Adopción', '9', '3', '¿Con qué frecuencia revisas el portafolio completo de IA (proyectos, productos, plataformas) en el comité ejecutivo para tomar decisiones de inversión/desinversión?', 'Multiple Choice (escala Likert A–E)', '["Nunca", "Rara vez (≤ 1/mes)", "Ocasional (2–3/mes)", "Frecuente (semanal)", "Muy frecuente (diaria)"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', now(), null, '["Inversión"]'::jsonb, 2, 5),

('CTO-A26', 'Cuestionario', 'Adopción', '9', '3', '¿Con qué frecuencia impulsas rediseños profundos de procesos o productos (no solo automatización) basados en capacidades de IA?', 'Multiple Choice (escala Likert A–E)', '["Nunca", "Rara vez (≤ 1/mes)", "Ocasional (2–3/mes)", "Frecuente (semanal)", "Muy frecuente (diaria)"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', now(), null, '["Aplicación"]'::jsonb, 2, 5),

('CTO-A27', 'Cuestionario', 'Adopción', '9', '3', '¿Con qué frecuencia integras indicadores de IA (uso, valor, riesgo) en los tableros que revisa el board o consejo de administración?', 'Multiple Choice (escala Likert A–E)', '["Nunca", "Rara vez (≤ 1/mes)", "Ocasional (2–3/mes)", "Frecuente (semanal)", "Muy frecuente (diaria)"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', now(), null, '["Aplicación", "Estrategia"]'::jsonb, 2, 5),

('CTO-A28', 'Cuestionario', 'Adopción', '9', '3', '¿Con qué frecuencia participas en foros externos (ecosistema de IA, reguladores, academia, partners) para influir y anticipar tendencias regulatorias y tecnológicas?', 'Multiple Choice (escala Likert A–E)', '["Nunca", "Rara vez (≤ 1/mes)", "Ocasional (2–3/mes)", "Frecuente (semanal)", "Muy frecuente (diaria)"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', now(), null, '["Aplicación"]'::jsonb, 2, 5),

('CTO-A29', 'Cuestionario', 'Adopción', '9', '3', '¿Con qué frecuencia revisas, junto con CHRO, cómo IA impacta la estrategia de talento (perfiles, reskilling, nuevas competencias digitales)?', 'Multiple Choice (escala Likert A–E)', '["Nunca", "Rara vez (≤ 1/mes)", "Ocasional (2–3/mes)", "Frecuente (semanal)", "Muy frecuente (diaria)"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', now(), null, '["Aplicación", "Estrategia"]'::jsonb, 2, 5),

('CTO-A30', 'Cuestionario', 'Adopción', '9', '3', '¿Con qué frecuencia exiges evaluaciones de riesgo/impacto (técnico, ético, reputacional) antes de escalar soluciones de IA a gran escala con clientes/ciudadanos?', 'Multiple Choice (escala Likert A–E)', '["Nunca", "Rara vez (≤ 1/mes)", "Ocasional (2–3/mes)", "Frecuente (semanal)", "Muy frecuente (diaria)"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', now(), null, '["Estrategia"]'::jsonb, 2, 5);

-- CONOCIMIENTO - Rol 3
INSERT INTO "public"."preguntas" ("codigo", "section", "bloque", "area_id", "exclusivo_rol_id", "texto", "tipo", "opciones", "locale", "peso", "escala", "scoring", "created_at", "respuesta_correcta", "dimension", "exclusivo_nivel_id", "dificultad") VALUES
('CTO-C1', 'Cuestionario', 'Conocimiento', '9', '3', 'Como CTO, ¿qué describe mejor a la IA generativa?', 'Multiple Choice (una respuesta)', '["Un tipo de base de datos optimizada para big data.", "Un modelo que solo clasifica datos históricos sin generar contenido nuevo.", "Modelos capaces de generar texto, código o imágenes a partir de instrucciones.", "Un sistema de automatización RPA basado en reglas fijas."]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', now(), 'Un modelo que solo clasifica datos históricos sin generar contenido nuevo.', '["Conocimiento"]'::jsonb, 2, 1),

('CTO-C2', 'Cuestionario', 'Conocimiento', '9', '3', '¿Cuál es un caso de uso básico y de bajo riesgo para iniciar con IA en el área de Tecnología?', 'Multiple Choice (una respuesta)', '["Autorización automática de pagos de alto valor.", "Generación de borradores de documentación técnica y manuales internos.", "Aprobación automática de contratos legales.", "Modificación automática de reglas de firewall."]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', now(), 'Generación de borradores de documentación técnica y manuales internos.', '["Conocimiento", "Aplicación", "Estrategia"]'::jsonb, 2, 1),

('CTO-C3', 'Cuestionario', 'Conocimiento', '9', '3', 'Para un CTO en fase inicial de IA, ¿qué es lo más crítico definir primero?', 'Multiple Choice (una respuesta)', '["Un modelo propio entrenado desde cero.", "Una política básica de uso responsable de IA (datos, privacidad, riesgos).", "Un data center on-premise para IA.", "Un equipo de 20 científicos de datos senior."]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', now(), 'Una política básica de uso responsable de IA (datos, privacidad, riesgos).', '["Conocimiento"]'::jsonb, 2, 1),

('CTO-C4', 'Cuestionario', 'Conocimiento', '9', '3', '¿Qué riesgo es más común cuando los equipos prueban herramientas de IA públicas sin lineamientos?', 'Multiple Choice (una respuesta)', '["Incremento de la latencia en la red interna.", "Pérdida de acceso a internet.", "Filtración de información sensible en prompts o documentos.", "Aumento inmediato del costo de la nube."]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', now(), 'Incremento de la latencia en la red interna.', '["Conocimiento", "Aplicación", "Estrategia"]'::jsonb, 2, 1),

('CTO-C5', 'Cuestionario', 'Conocimiento', '9', '3', '¿Cuál es una expectativa realista de IA en esta fase para el área de TI?', 'Multiple Choice (una respuesta)', '["Automatizar el 100% del soporte TI de primer nivel.", "Eliminar la necesidad de arquitectos de software.", "Mejorar la velocidad de rediseñar documentación y propuestas técnicas.", "Reemplazar el comité de arquitectura."]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', now(), 'Eliminar la necesidad de arquitectos de software.', '["Conocimiento"]'::jsonb, 2, 1),

('CTO-C6', 'Cuestionario', 'Conocimiento', '9', '3', '¿Qué indicador temprano puede usar un CTO para evaluar si las pruebas de IA tienen sentido continuar?', 'Multiple Choice (una respuesta)', '["Número de herramientas de IA diferentes instaladas.", "Ahorro estimado de tiempo que reportan los equipos piloto.", "Cantidad de parámetros del modelo usado.", "Número de reuniones sobre IA realizadas."]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', now(), 'Número de reuniones sobre IA realizadas.', '["Conocimiento"]'::jsonb, 2, 1),

('CTO-C7', 'Cuestionario', 'Conocimiento', '9', '3', 'En una fase de pilotos, ¿qué práctica es clave para evitar PoCs eternos sin impacto?', 'Multiple Choice (una respuesta)', '["Probar todas las herramientas de IA del mercado.", "Definir hipótesis claras, métricas de éxito y horizonte de decisión.", "Centrarse solo en la precisión del modelo.", "Dejar que cada equipo defina su propia métrica."]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', now(), 'Probar todas las herramientas de IA del mercado.', '["Conocimiento"]'::jsonb, 2, 2),

('CTO-C8', 'Cuestionario', 'Conocimiento', '9', '3', '¿Cuál es una limitación típica al usar IA generativa en un piloto para soporte TI?', 'Multiple Choice (una respuesta)', '["No puede generar texto.", "No se puede conectar a sistemas internos.", "Puede alucinar respuestas si no se controla el contexto y fuentes.", "No se puede integrar con APIs."]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', now(), 'No se puede conectar a sistemas internos.', '["Conocimiento"]'::jsonb, 2, 2),

('CTO-C9', 'Cuestionario', 'Conocimiento', '9', '3', 'Para proteger datos en pilotos, una decisión básica de arquitectura es:', 'Multiple Choice (una respuesta)', '["Permitir que los usuarios suban cualquier tipo de documento.", "Deshabilitar todo registro de actividad.", "Definir qué datos pueden salir a proveedores externos y cuáles deben quedarse on-prem o en VPC.", "No usar logs por temas de privacidad."]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', now(), 'Permitir que los usuarios suban cualquier tipo de documento.', '["Conocimiento", "Aplicación"]'::jsonb, 2, 2),

('CTO-C10', 'Cuestionario', 'Conocimiento', '9', '3', 'Como CTO, ¿qué indicador financiero mínimo deberías observar en pilotos de IA?', 'Multiple Choice (una respuesta)', '["Número de prompts utilizados.", "Estimación de ahorro de horas vs. costo del piloto.", "Cantidad de GPUs contratadas.", "Número de reuniones del equipo de datos."]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', now(), 'b', '["Conocimiento", "Inversión"]'::jsonb, 2, 2),

('CTO-C11', 'Cuestionario', 'Conocimiento', '9', '3', '¿Cuál es la diferencia principal entre usar IA generativa tal cual viene y usarla con un conector a tu base de conocimiento interna (RAG)?', 'Multiple Choice (una respuesta)', '["RAG hace que el modelo sea más rápido pero menos preciso.", "RAG permite responder usando tus propios documentos como contexto.", "RAG desactiva la capacidad de generar texto.", "RAG solo sirve para visión por computadora."]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', now(), 'b', '["Conocimiento"]'::jsonb, 2, 2),

('CTO-C12', 'Cuestionario', 'Conocimiento', '9', '3', '¿Qué rol debería tener más visibilidad en los pilotos de IA para garantizar cumplimiento y seguridad?', 'Multiple Choice (una respuesta)', '["Únicamente el equipo de UX.", "Solo el CEO.", "CISO y/o equipo de seguridad junto con el CTO.", "Únicamente desarrolladores backend."]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', now(), 'Únicamente el equipo de UX.', '["Conocimiento", "Estrategia"]'::jsonb, 2, 2),

('CTO-C13', 'Cuestionario', 'Conocimiento', '9', '3', '¿Qué elemento es esencial en una arquitectura de MLOps para IA en producción?', 'Multiple Choice (una respuesta)', '["Solo un repositorio de código.", "Pipelines automatizados de entrenamiento, despliegue y monitoreo de modelos.", "Desplegar manualmente cada modelo en un servidor distinto.", "No registrar versiones de modelos."]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', now(), 'b', '["Conocimiento"]'::jsonb, 2, 3),

('CTO-C14', 'Cuestionario', 'Conocimiento', '9', '3', 'Para evaluar una solución de IA en producción, además de precisión, un CTO debería monitorear:', 'Multiple Choice (una respuesta)', '["Solo la satisfacción del equipo de datos.", "Latencia, costos por llamada, volumen de uso y métricas de negocio asociadas.", "Únicamente el tamaño del modelo.", "Número de GPUs instaladas."]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', now(), 'b', '["Conocimiento"]'::jsonb, 2, 3),

('CTO-C15', 'Cuestionario', 'Conocimiento', '9', '3', '¿Qué describe mejor el drift en modelos de IA?', 'Multiple Choice (una respuesta)', '["Cambio en la arquitectura de red interna.", "Cambio en la distribución de datos o en la relación entre variables y etiquetas con el tiempo.", "Fallo del hardware de IA.", "Cambio de proveedor cloud."]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', now(), 'Cambio en la arquitectura de red interna.', '["Conocimiento"]'::jsonb, 2, 3),

('CTO-C16', 'Cuestionario', 'Conocimiento', '9', '3', '¿Qué enfoque suele ser más eficiente para personalizar un LLM a datos propios en esta fase?', 'Multiple Choice (una respuesta)', '["Entrenar un modelo desde cero.", "Uso de RAG y, si hace falta, fine-tuning ligero sobre un modelo base.", "Solo traducir prompts a otro idioma.", "Aumentar el tamaño del prompt sin límite."]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', now(), 'Uso de RAG y, si hace falta, fine-tuning ligero sobre un modelo base.', '["Conocimiento", "Aplicación"]'::jsonb, 2, 3),

('CTO-C17', 'Cuestionario', 'Conocimiento', '9', '3', '¿Qué práctica ayuda a que diferentes áreas de negocio reutilicen capacidades de IA existentes?', 'Multiple Choice (una respuesta)', '["Crear soluciones de IA independientes y aisladas por área.", "Exponer modelos y flujos de IA vía APIs internas y catálogos reutilizables.", "Permitir acceso directo a los modelos en bruto sin documentación.", "Prohibir el uso de IA fuera de TI."]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', now(), 'Exponer modelos y flujos de IA vía APIs internas y catálogos reutilizables.', '["Conocimiento"]'::jsonb, 2, 3),

('CTO-C18', 'Cuestionario', 'Conocimiento', '9', '3', '¿Qué es clave para gestionar el costo de IA generativa en producción?', 'Multiple Choice (una respuesta)', '["No medir el número de llamadas a los modelos.", "Ajustar tamaños de contexto, cachés y políticas de uso según caso de negocio.", "Usar siempre el modelo más grande disponible.", "Desactivar cualquier forma de logging."]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', now(), 'Usar siempre el modelo más grande disponible.', '["Conocimiento", "Inversión"]'::jsonb, 2, 3),

('CTO-C19', 'Cuestionario', 'Conocimiento', '9', '3', '¿Qué componente es más característico de una plataforma corporativa de IA madura?', 'Multiple Choice (una respuesta)', '["Un único script de entrenamiento manual.", "Catálogo de modelos, feature store, pipelines de datos, MLOps y gobierno centralizado.", "Solo una base de datos SQL.", "Un tablero de BI tradicional."]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', now(), 'Catálogo de modelos, feature store, pipelines de datos, MLOps y gobierno centralizado.', '["Conocimiento"]'::jsonb, 2, 4),

('CTO-C20', 'Cuestionario', 'Conocimiento', '9', '3', '¿Qué enfoque de gobierno facilita que distintas áreas consuman IA sin perder control?', 'Multiple Choice (una respuesta)', '["Centralizar absolutamente todas las decisiones en el CTO.", "Establecer políticas, estándares y guardrails, permitiendo cierta autonomía a los equipos.", "Permitir uso libre de cualquier herramienta sin normas.", "Delegar todo el gobierno en un proveedor externo."]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', now(), 'Centralizar absolutamente todas las decisiones en el CTO.', '["Conocimiento"]'::jsonb, 2, 4),

('CTO-C21', 'Cuestionario', 'Conocimiento', '9', '3', '¿Cuál es un riesgo al diseñar la plataforma solo para un tipo de modelo o proveedor?', 'Multiple Choice (una respuesta)', '["Reducción de la latencia.", "Aumento del lock-in y menor flexibilidad para aprovechar nuevas tecnologías.", "Tener demasiadas opciones para elegir.", "Mejora de la resiliencia."]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', now(), 'Aumento del lock-in y menor flexibilidad para aprovechar nuevas tecnologías.', '["Conocimiento", "Estrategia"]'::jsonb, 2, 4),

('CTO-C22', 'Cuestionario', 'Conocimiento', '9', '3', 'Para optimizar costos de IA a escala, ¿qué estrategia es más adecuada?', 'Multiple Choice (una respuesta)', '["No limitar el tamaño de contexto ni temperatura.", "Diseñar políticas de uso por caso de negocio y segmentar modelos (pequeños/medianos/grandes).", "Bloquear el uso de cualquier modelo pequeño.", "Usar siempre el modelo más caro y potente."]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', now(), 'b', '["Conocimiento", "Inversión", "Estrategia", "Productividad"]'::jsonb, 2, 4),

('CTO-C23', 'Cuestionario', 'Conocimiento', '9', '3', '¿Qué métrica es más relevante para evaluar la adopción de la plataforma de IA dentro de la organización?', 'Multiple Choice (una respuesta)', '["Número de GPUs físicas instaladas.", "Número de equipos de negocio que consumen la plataforma y volumen de llamadas a APIs de IA.", "Tamaño máximo del modelo soportado.", "Cantidad de frameworks de IA instalados."]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', now(), 'b', '["Conocimiento", "Aplicación"]'::jsonb, 2, 4),

('CTO-C24', 'Cuestionario', 'Conocimiento', '9', '3', '¿Qué práctica mejora la seguridad y cumplimiento en la plataforma de IA?', 'Multiple Choice (una respuesta)', '["Permitir prompts anónimos sin trazabilidad.", "Registrar prompts, respuestas y metadatos con controles de acceso y retención apropiados.", "Desactivar cualquier registro de actividad.", "Compartir todos los logs de IA con cualquier usuario interno."]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', now(), 'Permitir prompts anónimos sin trazabilidad.', '["Conocimiento", "Estrategia"]'::jsonb, 2, 4),

('CTO-C25', 'Cuestionario', 'Conocimiento', '9', '3', 'Como CTO AI-first, ¿qué es clave al priorizar un portafolio de iniciativas de IA?', 'Multiple Choice (una respuesta)', '["Priorizar solo las iniciativas con mayor complejidad técnica.", "Balancear impacto de negocio, factibilidad técnica, riesgo y alineación estratégica.", "Elegir únicamente las ideas propuestas por TI.", "Elegir solo proyectos que usen el modelo más grande."]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', now(), 'Balancear impacto de negocio, factibilidad técnica, riesgo y alineación estratégica.', '["Conocimiento", "Estrategia"]'::jsonb, 2, 5),

('CTO-C26', 'Cuestionario', 'Conocimiento', '9', '3', '¿Qué elemento distingue una estrategia AI-first de una simple adopción táctica?', 'Multiple Choice (una respuesta)', '["Uso de un modelo propietario de gran tamaño.", "Rediseño de productos, procesos y modelo de negocio alrededor de capacidades de IA.", "Tener un chatbot corporativo.", "Solo automatizar tareas internas de TI."]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', now(), 'Tener un chatbot corporativo.', '["Conocimiento", "Aplicación", "Estrategia"]'::jsonb, 2, 5),

('CTO-C27', 'Cuestionario', 'Conocimiento', '9', '3', '¿Qué es crítico al evaluar si construir o comprar modelos de IA (build vs. buy)?', 'Multiple Choice (una respuesta)', '["Solo considerar la preferencia personal del equipo de datos.", "Evaluar propiedad intelectual, diferenciación competitiva, costos de ciclo de vida y time-to-market.", "Elegir siempre construir.", "Elegir siempre comprar."]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', now(), 'b', '["Conocimiento"]'::jsonb, 2, 5),

('CTO-C28', 'Cuestionario', 'Conocimiento', '9', '3', '¿Qué componente de gobernanza de IA es más relevante en una organización AI-first?', 'Multiple Choice (una respuesta)', '["Un documento genérico de políticas guardado en un repositorio.", "Marcos y procesos activos para gestionar riesgos (comités, revisiones de modelos, registro de IA crítica).", "Prohibir todo uso de IA.", "Delegar completamente la gobernanza al proveedor cloud."]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', now(), 'Prohibir todo uso de IA.', '["Conocimiento", "Estrategia"]'::jsonb, 2, 5),

('CTO-C29', 'Cuestionario', 'Conocimiento', '9', '3', '¿Qué indicador estratégico conecta mejor IA con valor para accionistas?', 'Multiple Choice (una respuesta)', '["Número total de modelos en producción.", "Porcentaje de ingresos, margen o ahorro atribuible a iniciativas de IA prioritarias.", "Número de conferencias de IA asistidas por el equipo.", "Cantidad de GPUs instaladas."]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', now(), 'Porcentaje de ingresos, margen o ahorro atribuible a iniciativas de IA prioritarias.', '["Conocimiento"]'::jsonb, 2, 5),

('CTO-C30', 'Cuestionario', 'Conocimiento', '9', '3', '¿Qué factor es clave para escalar IA manteniendo licencia social y reputación?', 'Multiple Choice (una respuesta)', '["Minimizar la transparencia de los modelos para evitar cuestionamientos.", "Integrar principios de IA responsable, mecanismos de explicación y canales de queja/escala.", "Comunicar lo menos posible al público.", "Dejar todo en manos de marketing."]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', now(), 'Integrar principios de IA responsable, mecanismos de explicación y canales de queja/escala.', '["Conocimiento"]'::jsonb, 2, 5);
