-- ============================================================================
-- PREGUNTAS PARA LÍDER/GERENTE DE VENTAS
-- ============================================================================
-- Rol incluido:
--   - Rol ID 6: Líder/Gerente de Ventas (area_id: 2, nivel_id: 3)
-- ============================================================================

-- ============================================================================
-- ROL 6: Líder/Gerente de Ventas
-- ============================================================================

-- ADOPCIÓN - Rol 6
INSERT INTO "public"."preguntas" ("codigo", "section", "bloque", "area_id", "exclusivo_rol_id", "texto", "tipo", "opciones", "locale", "peso", "escala", "scoring", "created_at", "respuesta_correcta", "dimension", "exclusivo_nivel_id", "dificultad") VALUES
('LGV-A1', 'Cuestionario', 'Adopción', '2', '6', 'Uso herramientas de IA (por ejemplo, asistentes de texto) para redactar o mejorar correos a clientes clave.', 'Multiple Choice (escala Likert A–E)', '["Nunca", "Rara vez (≤ 1/mes)", "Ocasional (2–3/mes)", "Frecuente (semanal)", "Muy frecuente (diaria)"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', now(), null, '["Aplicación"]'::jsonb, 3, 1),

('LGV-A2', 'Cuestionario', 'Adopción', '2', '6', 'Reviso dentro del CRM cualquier recomendación “automática” (por ejemplo, leads sugeridos, recordatorios inteligentes) antes de priorizar a quién contactar.', 'Multiple Choice (escala Likert A–E)', '["Nunca", "Rara vez (≤ 1/mes)", "Ocasional (2–3/mes)", "Frecuente (semanal)", "Muy frecuente (diaria)"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', now(), null, '["Estrategia"]'::jsonb, 3, 1),

('LGV-A3', 'Cuestionario', 'Adopción', '2', '6', 'Incluyo en mis reuniones de equipo al menos un comentario o ejemplo sobre cómo usar IA para vender mejor.', 'Multiple Choice (escala Likert A–E)', '["Nunca", "Rara vez (≤ 1/mes)", "Ocasional (2–3/mes)", "Frecuente (semanal)", "Muy frecuente (diaria)"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', now(), null, '["Aplicación"]'::jsonb, 3, 1),

('LGV-A4', 'Cuestionario', 'Adopción', '2', '6', 'Dedico tiempo cada mes a explorar nuevas funciones de IA en las herramientas comerciales que ya usamos (CRM, marketing, etc.).', 'Multiple Choice (escala Likert A–E)', '["Nunca", "Rara vez (≤ 1/mes)", "Ocasional (2–3/mes)", "Frecuente (semanal)", "Muy frecuente (diaria)"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', now(), null, '["Aplicación", "Productividad"]'::jsonb, 3, 1),

('LGV-A5', 'Cuestionario', 'Adopción', '2', '6', 'Antes de enviar un mensaje generado por IA, reviso el contenido para asegurarme de que respeta nuestros valores y la relación con el cliente.', 'Multiple Choice (escala Likert A–E)', '["Nunca", "Rara vez (≤ 1/mes)", "Ocasional (2–3/mes)", "Frecuente (semanal)", "Muy frecuente (diaria)"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', now(), null, '["Aplicación"]'::jsonb, 3, 1),

('LGV-A6', 'Cuestionario', 'Adopción', '2', '6', 'Cuando necesito preparar una reunión con un cliente importante, uso IA para resumir información relevante (correos previos, notas, historial).', 'Multiple Choice (escala Likert A–E)', '["Nunca", "Rara vez (≤ 1/mes)", "Ocasional (2–3/mes)", "Frecuente (semanal)", "Muy frecuente (diaria)"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', now(), null, '["Aplicación"]'::jsonb, 3, 1),

('LGV-A7', 'Cuestionario', 'Adopción', '2', '6', 'Uso IA para generar versiones alternativas de scripts de llamada y pruebas A/B en correos de prospección.', 'Multiple Choice (escala Likert A–E)', '["Nunca", "Rara vez (≤ 1/mes)", "Ocasional (2–3/mes)", "Frecuente (semanal)", "Muy frecuente (diaria)"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', now(), null, '["Aplicación"]'::jsonb, 3, 2),

('LGV-A8', 'Cuestionario', 'Adopción', '2', '6', 'Cuando reviso el pipeline, considero las puntuaciones o recomendaciones de IA para decidir qué oportunidades coachingear con mi equipo.', 'Multiple Choice (escala Likert A–E)', '["Nunca", "Rara vez (≤ 1/mes)", "Ocasional (2–3/mes)", "Frecuente (semanal)", "Muy frecuente (diaria)"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', now(), null, '["Aplicación"]'::jsonb, 3, 2),

('LGV-A9', 'Cuestionario', 'Adopción', '2', '6', 'Capacito a los vendedores en el uso básico de IA (por ejemplo, cómo pedir buenos prompts o cómo integrar IA en su rutina diaria).', 'Multiple Choice (escala Likert A–E)', '["Nunca", "Rara vez (≤ 1/mes)", "Ocasional (2–3/mes)", "Frecuente (semanal)", "Muy frecuente (diaria)"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', now(), null, '["Aplicación"]'::jsonb, 3, 2),

('LGV-A10', 'Cuestionario', 'Adopción', '2', '6', 'Reviso periódicamente los mensajes automatizados para asegurar que no generen promesas que la empresa no pueda cumplir.', 'Multiple Choice (escala Likert A–E)', '["Nunca", "Rara vez (≤ 1/mes)", "Ocasional (2–3/mes)", "Frecuente (semanal)", "Muy frecuente (diaria)"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', now(), null, '["Aplicación"]'::jsonb, 3, 2),

('LGV-A11', 'Cuestionario', 'Adopción', '2', '6', 'Propongo pequeñas inversiones (tiempo o licencias) para probar nuevas funciones de IA en nuestra operación comercial.', 'Multiple Choice (escala Likert A–E)', '["Nunca", "Rara vez (≤ 1/mes)", "Ocasional (2–3/mes)", "Frecuente (semanal)", "Muy frecuente (diaria)"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', now(), null, '["Productividad"]'::jsonb, 3, 2),

('LGV-A12', 'Cuestionario', 'Adopción', '2', '6', 'Utilizo IA para resumir y ordenar información de reuniones con clientes y compartirla con el equipo.', 'Multiple Choice (escala Likert A–E)', '["Nunca", "Rara vez (≤ 1/mes)", "Ocasional (2–3/mes)", "Frecuente (semanal)", "Muy frecuente (diaria)"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', now(), null, '["Aplicación"]'::jsonb, 3, 2),

('LGV-A13', 'Cuestionario', 'Adopción', '2', '6', 'Diseño junto con el área de TI/Operaciones flujos de trabajo donde la IA participa en momentos clave (por ejemplo, asignación de leads, recordatorios, recomendaciones).', 'Multiple Choice (escala Likert A–E)', '["Nunca", "Rara vez (≤ 1/mes)", "Ocasional (2–3/mes)", "Frecuente (semanal)", "Muy frecuente (diaria)"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', now(), null, '["Aplicación"]'::jsonb, 3, 3),

('LGV-A14', 'Cuestionario', 'Adopción', '2', '6', 'Uso reportes y dashboards con métricas apoyadas en IA para revisar el desempeño comercial en mis reuniones de seguimiento.', 'Multiple Choice (escala Likert A–E)', '["Nunca", "Rara vez (≤ 1/mes)", "Ocasional (2–3/mes)", "Frecuente (semanal)", "Muy frecuente (diaria)"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', now(), null, '["Aplicación", "Productividad"]'::jsonb, 3, 3),

('LGV-A15', 'Cuestionario', 'Adopción', '2', '6', 'Ajusto las metas y prioridades del equipo considerando tanto la información tradicional (pipeline, historial) como las sugerencias de IA.', 'Multiple Choice (escala Likert A–E)', '["Nunca", "Rara vez (≤ 1/mes)", "Ocasional (2–3/mes)", "Frecuente (semanal)", "Muy frecuente (diaria)"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', now(), null, '["Aplicación"]'::jsonb, 3, 3),

('LGV-A16', 'Cuestionario', 'Adopción', '2', '6', 'He redefinido tareas del equipo de ventas para que dediquen menos tiempo a actividades manuales gracias a automatizaciones con IA.', 'Multiple Choice (escala Likert A–E)', '["Nunca", "Rara vez (≤ 1/mes)", "Ocasional (2–3/mes)", "Frecuente (semanal)", "Muy frecuente (diaria)"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', now(), null, '["Aplicación", "Productividad"]'::jsonb, 3, 3),

('LGV-A17', 'Cuestionario', 'Adopción', '2', '6', 'Discuto abiertamente con el equipo los límites de la IA (qué puede decidir y qué no) para evitar delegar decisiones críticas sin criterio humano.', 'Multiple Choice (escala Likert A–E)', '["Nunca", "Rara vez (≤ 1/mes)", "Ocasional (2–3/mes)", "Frecuente (semanal)", "Muy frecuente (diaria)"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', now(), null, '["Aplicación"]'::jsonb, 3, 3),

('LGV-A18', 'Cuestionario', 'Adopción', '2', '6', 'Promuevo que los vendedores compartan “buenas prácticas” de prompts y usos de IA entre ellos.', 'Multiple Choice (escala Likert A–E)', '["Nunca", "Rara vez (≤ 1/mes)", "Ocasional (2–3/mes)", "Frecuente (semanal)", "Muy frecuente (diaria)"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', now(), null, '["Aplicación"]'::jsonb, 3, 3),

('LGV-A19', 'Cuestionario', 'Adopción', '2', '6', 'Participo en la definición de KPIs específicos para evaluar el impacto de las soluciones de IA en el desempeño de ventas.', 'Multiple Choice (escala Likert A–E)', '["Nunca", "Rara vez (≤ 1/mes)", "Ocasional (2–3/mes)", "Frecuente (semanal)", "Muy frecuente (diaria)"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', now(), null, '["Productividad"]'::jsonb, 3, 4),

('LGV-A20', 'Cuestionario', 'Adopción', '2', '6', 'Reviso con frecuencia la calidad de los datos en el CRM y tomo acciones cuando detecto problemas que afectan a los modelos de IA.', 'Multiple Choice (escala Likert A–E)', '["Nunca", "Rara vez (≤ 1/mes)", "Ocasional (2–3/mes)", "Frecuente (semanal)", "Muy frecuente (diaria)"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', now(), null, '["Aplicación"]'::jsonb, 3, 4),

('LGV-A21', 'Cuestionario', 'Adopción', '2', '6', 'Uso insights de IA para personalizar estrategias por segmento (por ejemplo, diferentes discursos, bundles o canales).', 'Multiple Choice (escala Likert A–E)', '["Nunca", "Rara vez (≤ 1/mes)", "Ocasional (2–3/mes)", "Frecuente (semanal)", "Muy frecuente (diaria)"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', now(), null, '["Estrategia", "Productividad", "Aplicación"]'::jsonb, 3, 4),

('LGV-A22', 'Cuestionario', 'Adopción', '2', '6', 'Incluyo la discusión sobre IA de forma sistemática en mis reuniones de seguimiento (pipeline reviews, QBRs), no sólo como algo “extra”.', 'Multiple Choice (escala Likert A–E)', '["Nunca", "Rara vez (≤ 1/mes)", "Ocasional (2–3/mes)", "Frecuente (semanal)", "Muy frecuente (diaria)"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', now(), null, '["Aplicación"]'::jsonb, 3, 4),

('LGV-A23', 'Cuestionario', 'Adopción', '2', '6', 'Cuestiono y ajusto las recomendaciones de IA cuando no encajan con el contexto cualitativo que tengo del cliente.', 'Multiple Choice (escala Likert A–E)', '["Nunca", "Rara vez (≤ 1/mes)", "Ocasional (2–3/mes)", "Frecuente (semanal)", "Muy frecuente (diaria)"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', now(), null, '["Aplicación"]'::jsonb, 3, 4),

('LGV-A24', 'Cuestionario', 'Adopción', '2', '6', 'Propongo y lidero pequeños pilotos de IA antes de escalar una solución a todo el equipo de ventas.', 'Multiple Choice (escala Likert A–E)', '["Nunca", "Rara vez (≤ 1/mes)", "Ocasional (2–3/mes)", "Frecuente (semanal)", "Muy frecuente (diaria)"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', now(), null, '["Aplicación"]'::jsonb, 3, 4),

('LGV-A25', 'Cuestionario', 'Adopción', '2', '6', 'Participo activamente en comités o grupos de trabajo donde se define la estrategia de IA de la organización, aportando la perspectiva comercial.', 'Multiple Choice (escala Likert A–E)', '["Nunca", "Rara vez (≤ 1/mes)", "Ocasional (2–3/mes)", "Frecuente (semanal)", "Muy frecuente (diaria)"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', now(), null, '["Estrategia"]'::jsonb, 3, 5),

('LGV-A26', 'Cuestionario', 'Adopción', '2', '6', 'Impulso iniciativas para rediseñar el modelo comercial (segmentación, canales, propuesta de valor) aprovechando capacidades avanzadas de IA.', 'Multiple Choice (escala Likert A–E)', '["Nunca", "Rara vez (≤ 1/mes)", "Ocasional (2–3/mes)", "Frecuente (semanal)", "Muy frecuente (diaria)"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', now(), null, '["Estrategia"]'::jsonb, 3, 5),

('LGV-A27', 'Cuestionario', 'Adopción', '2', '6', 'Promuevo una cultura en la que el equipo comparta aprendizajes y buenas prácticas de IA de forma sistemática (rituales, comunidades de práctica, etc.).', 'Multiple Choice (escala Likert A–E)', '["Nunca", "Rara vez (≤ 1/mes)", "Ocasional (2–3/mes)", "Frecuente (semanal)", "Muy frecuente (diaria)"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', now(), null, '["Aplicación"]'::jsonb, 3, 5),

('LGV-A28', 'Cuestionario', 'Adopción', '2', '6', 'Cuestiono y reviso periódicamente las políticas de uso de IA en ventas (privacidad, transparencia con clientes, sesgos) junto con otras áreas.', 'Multiple Choice (escala Likert A–E)', '["Nunca", "Rara vez (≤ 1/mes)", "Ocasional (2–3/mes)", "Frecuente (semanal)", "Muy frecuente (diaria)"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', now(), null, '["Aplicación", "Estrategia"]'::jsonb, 3, 5),

('LGV-A29', 'Cuestionario', 'Adopción', '2', '6', 'Defiendo ante la dirección inversiones en datos, integraciones y talento que habiliten un modelo comercial apoyado en IA de largo plazo.', 'Multiple Choice (escala Likert A–E)', '["Nunca", "Rara vez (≤ 1/mes)", "Ocasional (2–3/mes)", "Frecuente (semanal)", "Muy frecuente (diaria)"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', now(), null, '["Aplicación"]'::jsonb, 3, 5),

('LGV-A30', 'Cuestionario', 'Adopción', '2', '6', 'Uso resultados de análisis avanzados (por ejemplo, segmentación dinámica, recomendaciones de IA) para proponer nuevos productos, bundles o servicios al mercado.', 'Multiple Choice (escala Likert A–E)', '["Nunca", "Rara vez (≤ 1/mes)", "Ocasional (2–3/mes)", "Frecuente (semanal)", "Muy frecuente (diaria)"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', now(), null, '["Aplicación", "Productividad"]'::jsonb, 3, 5);

-- CONOCIMIENTO - Rol 6
INSERT INTO "public"."preguntas" ("codigo", "section", "bloque", "area_id", "exclusivo_rol_id", "texto", "tipo", "opciones", "locale", "peso", "escala", "scoring", "created_at", "respuesta_correcta", "dimension", "exclusivo_nivel_id", "dificultad") VALUES
('LGV-C1', 'Cuestionario', 'Conocimiento', '2', '6', '¿Cuál de las siguientes opciones describe mejor qué es la inteligencia artificial aplicada a ventas?', 'Multiple Choice (una respuesta)', '["Un sistema que reemplaza por completo al equipo de ventas.", "Herramientas que analizan datos de clientes para apoyar tareas como priorizar leads o personalizar mensajes.", "Un tipo de hardware especial para hacer llamadas más rápidas.", "Una base de datos de contactos sin capacidades de análisis."]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', now(), 'Herramientas que analizan datos de clientes para apoyar tareas como priorizar leads o personalizar mensajes.', '["Conocimiento", "Aplicación"]'::jsonb, 3, 1),

('LGV-C2', 'Cuestionario', 'Conocimiento', '2', '6', '¿Qué es un CRM con capacidades de IA?', 'Multiple Choice (una respuesta)', '["Un archivo Excel compartido.", "Un sistema que sólo almacena datos de clientes sin generar reportes.", "Un sistema que puede priorizar leads, sugerir próximos pasos y generar insights automáticamente.", "Una herramienta usada solo por Finanzas."]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', now(), 'Un sistema que puede priorizar leads, sugerir próximos pasos y generar insights automáticamente.', '["Conocimiento"]'::jsonb, 3, 1),

('LGV-C3', 'Cuestionario', 'Conocimiento', '2', '6', '¿Cuál de estas tareas es más típica de la IA en ventas?', 'Multiple Choice (una respuesta)', '["Definir la política salarial del equipo.", "Sugerir qué leads tienen más probabilidad de cerrar.", "Firmar contratos con clientes.", "Definir la estructura de comisiones."]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', now(), 'Sugerir qué leads tienen más probabilidad de cerrar.', '["Conocimiento"]'::jsonb, 3, 1),

('LGV-C4', 'Cuestionario', 'Conocimiento', '2', '6', '¿Qué significa “automatizar un correo de seguimiento con IA”?', 'Multiple Choice (una respuesta)', '["Enviar un mismo correo genérico a todos.", "Generar borradores personalizados según el historial del cliente.", "Dejar de responder correos.", "Enviar correos sin registro en el CRM."]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', now(), 'Generar borradores personalizados según el historial del cliente.', '["Conocimiento", "Productividad"]'::jsonb, 3, 1),

('LGV-C5', 'Cuestionario', 'Conocimiento', '2', '6', '¿Cuál es un riesgo básico de usar IA en ventas sin supervisión?', 'Multiple Choice (una respuesta)', '["Aumentar siempre las ventas.", "Enviar mensajes incorrectos o poco éticos a clientes.", "Reducir el tiempo de respuesta.", "Tener mejor organización de información."]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', now(), 'Enviar mensajes incorrectos o poco éticos a clientes.', '["Conocimiento", "Estrategia"]'::jsonb, 3, 1),

('LGV-C6', 'Cuestionario', 'Conocimiento', '2', '6', '¿Cuál de estas fuentes de datos suele alimentar a la IA en ventas?', 'Multiple Choice (una respuesta)', '["Únicamente redes sociales personales del gerente.", "Datos del CRM: historial de interacciones, montos, cierres, etc.", "Sólo información de Recursos Humanos.", "Un listado aleatorio de contactos."]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', now(), 'Datos del CRM: historial de interacciones, montos, cierres, etc.', '["Conocimiento", "Aplicación"]'::jsonb, 3, 1),

('LGV-C7', 'Cuestionario', 'Conocimiento', '2', '6', '¿Qué es el lead scoring basado en IA?', 'Multiple Choice (una respuesta)', '["Repartir leads de forma aleatoria.", "Ordenar leads según la intuición del vendedor.", "Asignar una puntuación automática a cada lead según su probabilidad de conversión.", "Medir sólo el número de llamadas realizadas."]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', now(), 'Asignar una puntuación automática a cada lead según su probabilidad de conversión.', '["Conocimiento"]'::jsonb, 3, 2),

('LGV-C8', 'Cuestionario', 'Conocimiento', '2', '6', '¿Cuál es una ventaja clave de usar IA para redactar correos de seguimiento?', 'Multiple Choice (una respuesta)', '["Evitar por completo que el equipo de ventas revise los textos.", "Reducir tiempo y aumentar personalización según el contexto del cliente.", "Enviar correos sin firma ni datos de contacto.", "Enviar más spam."]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', now(), 'Reducir tiempo y aumentar personalización según el contexto del cliente.', '["Conocimiento"]'::jsonb, 3, 2),

('LGV-C9', 'Cuestionario', 'Conocimiento', '2', '6', '¿Qué indicador puede mejorar directamente con IA en ventas?', 'Multiple Choice (una respuesta)', '["Número de vacaciones del equipo.", "Tasa de conversión de oportunidades a cierres.", "Número de reuniones sociales.", "Tiempo de permanencia en la oficina."]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', now(), 'Tasa de conversión de oportunidades a cierres.', '["Conocimiento"]'::jsonb, 3, 2),

('LGV-C10', 'Cuestionario', 'Conocimiento', '2', '6', '¿Cuál es una forma razonable de evaluar si la IA está ayudando en el proceso comercial?', 'Multiple Choice (una respuesta)', '["Ver si a los vendedores “les gusta” la nueva herramienta.", "Comparar antes y después métricas como conversión, ticket promedio o ciclo de venta.", "Contar cuántos correos genera la IA.", "Preguntar al proveedor de la herramienta si “cree” que funciona."]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', now(), 'Comparar antes y después métricas como conversión, ticket promedio o ciclo de venta.', '["Conocimiento"]'::jsonb, 3, 2),

('LGV-C11', 'Cuestionario', 'Conocimiento', '2', '6', '¿Qué se debe hacer con datos sensibles de clientes al usar IA?', 'Multiple Choice (una respuesta)', '["Compartirlos en cualquier herramienta pública sin restricciones.", "Solo usarlos en herramientas aprobadas por la empresa y con políticas claras de privacidad.", "Publicarlos en redes sociales para tener más visibilidad.", "Guardarlos en dispositivos personales sin protección."]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', now(), 'Solo usarlos en herramientas aprobadas por la empresa y con políticas claras de privacidad.', '["Conocimiento", "Aplicación"]'::jsonb, 3, 2),

('LGV-C12', 'Cuestionario', 'Conocimiento', '2', '6', '¿Cuál de estas decisiones de inversión es más alineada con un uso táctico de IA en ventas?', 'Multiple Choice (una respuesta)', '["Comprar una herramienta de IA sin capacitar al equipo.", "Invertir en módulos de IA dentro del CRM y en un entrenamiento básico para el equipo.", "Reducir el presupuesto de datos de clientes.", "Cambiar toda la fuerza de ventas por bots."]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', now(), 'Invertir en módulos de IA dentro del CRM y en un entrenamiento básico para el equipo.', '["Conocimiento", "Inversión", "Aplicación"]'::jsonb, 3, 2),

('LGV-C13', 'Cuestionario', 'Conocimiento', '2', '6', '¿Qué combinación describe mejor un proceso de ventas “integrado con IA”?', 'Multiple Choice (una respuesta)', '["Sólo usar IA para redactar correos.", "Aplicar IA en varias etapas: priorización de leads, seguimiento, forecast y análisis de resultados.", "Tener una herramienta de IA sin datos.", "Medir sólo la cantidad de llamadas."]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', now(), 'Aplicar IA en varias etapas: priorización de leads, seguimiento, forecast y análisis de resultados.', '["Conocimiento"]'::jsonb, 3, 3),

('LGV-C14', 'Cuestionario', 'Conocimiento', '2', '6', '¿Qué implica un “forecast de ventas” apoyado en IA?', 'Multiple Choice (una respuesta)', '["Estimar ventas a ojo según la intuición del gerente.", "Utilizar modelos que analizan datos históricos y actividad actual para proyectar resultados.", "Preguntar al proveedor cuánto cree que se venderá.", "Copiar el forecast del año anterior."]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', now(), 'Utilizar modelos que analizan datos históricos y actividad actual para proyectar resultados.', '["Conocimiento"]'::jsonb, 3, 3),

('LGV-C15', 'Cuestionario', 'Conocimiento', '2', '6', '¿Qué práctica ayuda a mejorar la calidad del lead scoring de IA?', 'Multiple Choice (una respuesta)', '["No registrar actividades en el CRM.", "Completar la mayor cantidad posible de campos relevantes y mantener los datos limpios.", "Actualizar datos sólo al final del año.", "Evitar registrar motivo de pérdida."]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', now(), 'Completar la mayor cantidad posible de campos relevantes y mantener los datos limpios.', '["Conocimiento"]'::jsonb, 3, 3),

('LGV-C16', 'Cuestionario', 'Conocimiento', '2', '6', '¿Qué es una “alerta inteligente” en un contexto de ventas?', 'Multiple Choice (una respuesta)', '["Un recordatorio genérico en el calendario.", "Una notificación generada por IA cuando detecta cambios relevantes en la cuenta o en la probabilidad de cierre.", "Un correo enviado por recursos humanos.", "Un mensaje automático sin relación con el cliente."]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', now(), 'Una notificación generada por IA cuando detecta cambios relevantes en la cuenta o en la probabilidad de cierre.', '["Conocimiento"]'::jsonb, 3, 3),

('LGV-C17', 'Cuestionario', 'Conocimiento', '2', '6', '¿Por qué es importante considerar sesgos en modelos de IA para ventas?', 'Multiple Choice (una respuesta)', '["Porque podrían favorecer injustamente ciertos leads o segmentos sin justificación válida.", "Porque los sesgos aumentan siempre las ventas.", "Porque evitan que usemos métricas.", "Porque hacen más lenta la operación."]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', now(), 'Porque podrían favorecer injustamente ciertos leads o segmentos sin justificación válida.', '["Conocimiento", "Estrategia"]'::jsonb, 3, 3),

('LGV-C18', 'Cuestionario', 'Conocimiento', '2', '6', '¿Qué decisión de inversión muestra una mentalidad de integración de IA en procesos?', 'Multiple Choice (una respuesta)', '["Comprar muchas herramientas sin integrarlas al CRM.", "Consolidar herramientas y asegurar que los módulos de IA estén integrados en el flujo de trabajo del equipo.", "Prohibir el uso de IA.", "Dejar que cada vendedor compre cualquier herramienta por su cuenta."]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', now(), 'Consolidar herramientas y asegurar que los módulos de IA estén integrados en el flujo de trabajo del equipo.', '["Conocimiento", "Inversión"]'::jsonb, 3, 3),

('LGV-C19', 'Cuestionario', 'Conocimiento', '2', '6', '¿Qué caracteriza un enfoque “data-driven” con IA en ventas?', 'Multiple Choice (una respuesta)', '["Tomar decisiones sólo por intuición.", "Basar decisiones clave en datos, modelos de IA y experimentos medidos.", "Cambiar la estrategia cada semana sin datos.", "Confiar únicamente en la opinión del proveedor de la herramienta."]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', now(), 'Basar decisiones clave en datos, modelos de IA y experimentos medidos.', '["Conocimiento"]'::jsonb, 3, 4),

('LGV-C20', 'Cuestionario', 'Conocimiento', '2', '6', '¿Cuál es un uso avanzado de IA en la gestión de territorios o cuentas?', 'Multiple Choice (una respuesta)', '["Asignar cuentas al azar.", "Utilizar modelos que consideran potencial, histórico de compras y probabilidad de crecimiento para repartir territorios.", "Repartir cuentas según quién se queje menos.", "Asignar todo a un supervendedor."]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', now(), 'Utilizar modelos que consideran potencial, histórico de compras y probabilidad de crecimiento para repartir territorios.', '["Conocimiento", "Aplicación"]'::jsonb, 3, 4),

('LGV-C21', 'Cuestionario', 'Conocimiento', '2', '6', '¿Qué es un “experimento controlado” en la adopción de IA en ventas?', 'Multiple Choice (una respuesta)', '["Probar una herramienta sin comparar resultados.", "Comparar un grupo que usa IA versus otro que no, midiendo métricas específicas.", "Cambiar todos los procesos al mismo tiempo.", "Preguntar informalmente al equipo si siente que “va mejor”."]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', now(), 'Comparar un grupo que usa IA versus otro que no, midiendo métricas específicas.', '["Conocimiento", "Aplicación"]'::jsonb, 3, 4),

('LGV-C22', 'Cuestionario', 'Conocimiento', '2', '6', '¿Por qué es importante la gobernanza de datos al escalar IA en ventas?', 'Multiple Choice (una respuesta)', '["Porque sin reglas claras, se pueden usar datos inexactos o no permitidos, afectando resultados y reputación.", "Porque hace la operación más lenta sin beneficio.", "Porque evita que se compartan mejores prácticas.", "Porque limita el uso de métricas."]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', now(), 'Porque sin reglas claras, se pueden usar datos inexactos o no permitidos, afectando resultados y reputación.', '["Conocimiento", "Estrategia", "Aplicación"]'::jsonb, 3, 4),

('LGV-C23', 'Cuestionario', 'Conocimiento', '2', '6', '¿Cuál es una señal de retorno de inversión (ROI) positivo en IA para ventas?', 'Multiple Choice (una respuesta)', '["Mayor gasto en licencias.", "Mejora medible en indicadores como conversión, ticket promedio o costo de adquisición vs inversión realizada.", "Que la herramienta tenga muchas funciones.", "Que el proveedor sea conocido."]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', now(), 'Mejora medible en indicadores como conversión, ticket promedio o costo de adquisición vs inversión realizada.', '["Conocimiento", "Inversión"]'::jsonb, 3, 4),

('LGV-C24', 'Cuestionario', 'Conocimiento', '2', '6', '¿Qué rol suele tener un gerente de ventas en la adopción de IA a este nivel?', 'Multiple Choice (una respuesta)', '["Usuario pasivo de una herramienta.", "Líder que define casos de uso, métricas de éxito y coordina con otras áreas la integración.", "Desarrollador de modelos de IA.", "Auditor de TI."]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', now(), 'Líder que define casos de uso, métricas de éxito y coordina con otras áreas la integración.', '["Conocimiento", "Aplicación"]'::jsonb, 3, 4),

('LGV-C25', 'Cuestionario', 'Conocimiento', '2', '6', '¿Qué diferencia a un enfoque “transformacional” de IA en ventas de uno meramente táctico?', 'Multiple Choice (una respuesta)', '["Usar IA sólo para redactar correos.", "Rediseñar procesos, roles y propuestas de valor alrededor de capacidades de IA, alineado a la estrategia del negocio.", "Comprar más licencias sin cambiar procesos.", "Aumentar el número de dashboards."]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', now(), 'Rediseñar procesos, roles y propuestas de valor alrededor de capacidades de IA, alineado a la estrategia del negocio.', '["Conocimiento"]'::jsonb, 3, 5),

('LGV-C26', 'Cuestionario', 'Conocimiento', '2', '6', '¿Cuál es un riesgo estratégico al depender en exceso de un único proveedor de IA para el modelo comercial?', 'Multiple Choice (una respuesta)', '["Tener demasiadas opciones de integración.", "Quedar expuesto a cambios de precios, políticas o fallos que afecten todo el modelo de ventas.", "Mejorar la resiliencia del negocio.", "Reducir la necesidad de estrategia."]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', now(), 'Quedar expuesto a cambios de precios, políticas o fallos que afecten todo el modelo de ventas.', '["Conocimiento", "Estrategia"]'::jsonb, 3, 5),

('LGV-C27', 'Cuestionario', 'Conocimiento', '2', '6', '¿Qué implica incluir IA en la propuesta de valor al cliente?', 'Multiple Choice (una respuesta)', '["Solo mencionar “tenemos IA” en la presentación comercial.", "Diseñar servicios/productos donde la IA aporte resultados tangibles para el cliente (por ejemplo, recomendaciones, personalización, tiempos de respuesta).", "Aumentar precios sin cambios en el servicio.", "Eliminar la interacción humana."]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', now(), 'Diseñar servicios/productos donde la IA aporte resultados tangibles para el cliente (por ejemplo, recomendaciones, personalización, tiempos de respuesta).', '["Conocimiento"]'::jsonb, 3, 5),

('LGV-C28', 'Cuestionario', 'Conocimiento', '2', '6', '¿Por qué la ética de IA se vuelve crítica al escalar modelos que afectan miles de clientes?', 'Multiple Choice (una respuesta)', '["Porque los errores se mantienen locales.", "Porque una mala decisión automatizada puede amplificarse y dañar masivamente la confianza y resultados del negocio.", "Porque reduce la necesidad de cumplimiento normativo.", "Porque elimina la responsabilidad del gerente."]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', now(), 'Porque una mala decisión automatizada puede amplificarse y dañar masivamente la confianza y resultados del negocio.', '["Conocimiento", "Estrategia"]'::jsonb, 3, 5),

('LGV-C29', 'Cuestionario', 'Conocimiento', '2', '6', '¿Qué tipo de inversión refleja una visión de largo plazo en IA para ventas?', 'Multiple Choice (una respuesta)', '["Comprar muchas herramientas sin capacitación ni estrategia.", "Invertir en datos, integraciones, habilidades del equipo y gobierno de IA, no sólo en licencias.", "Rotar proveedores continuamente sin evaluar resultados.", "Reducir la inversión en datos para ahorrar."]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', now(), 'Invertir en datos, integraciones, habilidades del equipo y gobierno de IA, no sólo en licencias.', '["Conocimiento", "Inversión"]'::jsonb, 3, 5),

('LGV-C30', 'Cuestionario', 'Conocimiento', '2', '6', '¿Qué rol juega un gerente de ventas en las decisiones corporativas sobre IA?', 'Multiple Choice (una respuesta)', '["Ninguno, es solo usuario final.", "Representa la voz del cliente y del equipo comercial, definiendo requerimientos, prioridades y riesgos junto a otras áreas.", "Diseña solo modelos técnicos de IA.", "Aprobar contratos legales sin revisión."]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', now(), 'Representa la voz del cliente y del equipo comercial, definiendo requerimientos, prioridades y riesgos junto a otras áreas.', '["Conocimiento"]'::jsonb, 3, 5);
