-- ============================================================================
-- PREGUNTAS PARA DIRECCIÓN/JEFATURA DE CONTABILIDAD
-- ============================================================================
-- Rol incluido:
--   - Rol ID 15: Dirección/Jefatura de Contabilidad (area_id: 7, nivel_id: 2)
-- ============================================================================

-- ============================================================================
-- ROL 15: Dirección/Jefatura de Contabilidad
-- ============================================================================

-- ADOPCIÓN - Rol 15
INSERT INTO "public"."preguntas" ("codigo", "section", "bloque", "area_id", "exclusivo_rol_id", "texto", "tipo", "opciones", "locale", "peso", "escala", "scoring", "created_at", "respuesta_correcta", "dimension", "exclusivo_nivel_id", "dificultad") VALUES
('DC-A1', 'Cuestionario', 'Adopción', '7', '15', 'Uso IA o funciones inteligentes para redactar o revisar correos y minutas relacionadas con temas contables.', 'Multiple Choice (escala Likert A–E)', '["Nunca", "Rara vez (≤ 1/mes)", "Ocasional (2–3/mes)", "Frecuente (semanal)", "Muy frecuente (diaria)"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', now(), null, '["Aplicación"]'::jsonb, 2, 1),

('DC-A2', 'Cuestionario', 'Adopción', '7', '15', 'Consulto herramientas de IA, por ejemplo chatbots, para obtener explicaciones preliminares sobre normas contables o fiscales, que luego verifico.', 'Multiple Choice (escala Likert A–E)', '["Nunca", "Rara vez (≤ 1/mes)", "Ocasional (2–3/mes)", "Frecuente (semanal)", "Muy frecuente (diaria)"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', now(), null, '["Aplicación"]'::jsonb, 2, 1),

('DC-A3', 'Cuestionario', 'Adopción', '7', '15', 'Exploro información sobre nuevas herramientas de IA aplicadas a contabilidad, por ejemplo webinars, artículos o demos, aunque aún no las implemente.', 'Multiple Choice (escala Likert A–E)', '["Nunca", "Rara vez (≤ 1/mes)", "Ocasional (2–3/mes)", "Frecuente (semanal)", "Muy frecuente (diaria)"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', now(), null, '["Aplicación"]'::jsonb, 2, 1),

('DC-A4', 'Cuestionario', 'Adopción', '7', '15', 'Comento con mi equipo las posibilidades de usar IA para reducir trabajo manual en cierres contables.', 'Multiple Choice (escala Likert A–E)', '["Nunca", "Rara vez (≤ 1/mes)", "Ocasional (2–3/mes)", "Frecuente (semanal)", "Muy frecuente (diaria)"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', now(), null, '["Aplicación"]'::jsonb, 2, 1),

('DC-A5', 'Cuestionario', 'Adopción', '7', '15', 'Tengo en cuenta consideraciones de confidencialidad de datos cuando alguien propone usar IA con información contable.', 'Multiple Choice (escala Likert A–E)', '["Nunca", "Rara vez (≤ 1/mes)", "Ocasional (2–3/mes)", "Frecuente (semanal)", "Muy frecuente (diaria)"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', now(), null, '["Aplicación", "Estrategia"]'::jsonb, 2, 1),

('DC-A6', 'Cuestionario', 'Adopción', '7', '15', 'He probado, aunque sea de forma piloto, al menos una herramienta de IA relacionada con procesos contables.', 'Multiple Choice (escala Likert A–E)', '["Nunca", "Rara vez (≤ 1/mes)", "Ocasional (2–3/mes)", "Frecuente (semanal)", "Muy frecuente (diaria)"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', now(), null, '["Aplicación"]'::jsonb, 2, 1),

('DC-A7', 'Cuestionario', 'Adopción', '7', '15', 'Uso IA para preparar borradores de políticas contables, presentaciones para auditoría o resúmenes de cambios normativos.', 'Multiple Choice (escala Likert A–E)', '["Nunca", "Rara vez (≤ 1/mes)", "Ocasional (2–3/mes)", "Frecuente (semanal)", "Muy frecuente (diaria)"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', now(), null, '["Aplicación", "Estrategia"]'::jsonb, 2, 2),

('DC-A8', 'Cuestionario', 'Adopción', '7', '15', 'Pido a la IA ejemplos de tratamientos contables o fiscales y luego los contrasto con la normativa oficial antes de decidir.', 'Multiple Choice (escala Likert A–E)', '["Nunca", "Rara vez (≤ 1/mes)", "Ocasional (2–3/mes)", "Frecuente (semanal)", "Muy frecuente (diaria)"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', now(), null, '["Aplicación"]'::jsonb, 2, 2),

('DC-A9', 'Cuestionario', 'Adopción', '7', '15', 'He impulsado pequeños pilotos de IA, por ejemplo para capturar facturas o clasificar documentos, en el área de contabilidad.', 'Multiple Choice (escala Likert A–E)', '["Nunca", "Rara vez (≤ 1/mes)", "Ocasional (2–3/mes)", "Frecuente (semanal)", "Muy frecuente (diaria)"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', now(), null, '["Aplicación"]'::jsonb, 2, 2),

('DC-A10', 'Cuestionario', 'Adopción', '7', '15', 'Coordino con TI o proveedores la prueba de herramientas de IA que podrían integrarse con el ERP contable.', 'Multiple Choice (escala Likert A–E)', '["Nunca", "Rara vez (≤ 1/mes)", "Ocasional (2–3/mes)", "Frecuente (semanal)", "Muy frecuente (diaria)"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', now(), null, '["Aplicación"]'::jsonb, 2, 2),

('DC-A11', 'Cuestionario', 'Adopción', '7', '15', 'Incluyo criterios relacionados con IA, como automatización y analítica, cuando discuto mejoras de procesos contables.', 'Multiple Choice (escala Likert A–E)', '["Nunca", "Rara vez (≤ 1/mes)", "Ocasional (2–3/mes)", "Frecuente (semanal)", "Muy frecuente (diaria)"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', now(), null, '["Aplicación"]'::jsonb, 2, 2),

('DC-A12', 'Cuestionario', 'Adopción', '7', '15', 'Reviso si el uso de IA respeta las políticas internas de seguridad y confidencialidad de información financiera.', 'Multiple Choice (escala Likert A–E)', '["Nunca", "Rara vez (≤ 1/mes)", "Ocasional (2–3/mes)", "Frecuente (semanal)", "Muy frecuente (diaria)"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', now(), null, '["Aplicación", "Estrategia"]'::jsonb, 2, 2),

('DC-A13', 'Cuestionario', 'Adopción', '7', '15', 'Uso IA para identificar transacciones atípicas o inconsistencias en el libro mayor durante el cierre mensual.', 'Multiple Choice (escala Likert A–E)', '["Nunca", "Rara vez (≤ 1/mes)", "Ocasional (2–3/mes)", "Frecuente (semanal)", "Muy frecuente (diaria)"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', now(), null, '["Aplicación"]'::jsonb, 2, 3),

('DC-A14', 'Cuestionario', 'Adopción', '7', '15', 'He ajustado flujos de trabajo en el equipo de contabilidad para aprovechar salidas de IA, por ejemplo revisando primero las alertas de riesgo.', 'Multiple Choice (escala Likert A–E)', '["Nunca", "Rara vez (≤ 1/mes)", "Ocasional (2–3/mes)", "Frecuente (semanal)", "Muy frecuente (diaria)"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', now(), null, '["Aplicación", "Estrategia"]'::jsonb, 2, 3),

('DC-A15', 'Cuestionario', 'Adopción', '7', '15', 'Trabajo con TI o proveedores para definir reglas de integración de datos entre IA y ERP contable, como campos, frecuencia de actualización y validaciones.', 'Multiple Choice (escala Likert A–E)', '["Nunca", "Rara vez (≤ 1/mes)", "Ocasional (2–3/mes)", "Frecuente (semanal)", "Muy frecuente (diaria)"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', now(), null, '["Aplicación"]'::jsonb, 2, 3),

('DC-A16', 'Cuestionario', 'Adopción', '7', '15', 'Utilizo informes generados por IA, como análisis de variaciones y tendencias, como insumo para presentaciones a Dirección Financiera o a la dirección general.', 'Multiple Choice (escala Likert A–E)', '["Nunca", "Rara vez (≤ 1/mes)", "Ocasional (2–3/mes)", "Frecuente (semanal)", "Muy frecuente (diaria)"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', now(), null, '["Aplicación"]'::jsonb, 2, 3),

('DC-A17', 'Cuestionario', 'Adopción', '7', '15', 'Incluyo en los procedimientos de cierre instrucciones específicas sobre cómo revisar y documentar las salidas de IA.', 'Multiple Choice (escala Likert A–E)', '["Nunca", "Rara vez (≤ 1/mes)", "Ocasional (2–3/mes)", "Frecuente (semanal)", "Muy frecuente (diaria)"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', now(), null, '["Aplicación"]'::jsonb, 2, 3),

('DC-A18', 'Cuestionario', 'Adopción', '7', '15', 'Considero explícitamente el costo de licencias, mantenimiento y soporte de soluciones de IA en el presupuesto del área de contabilidad.', 'Multiple Choice (escala Likert A–E)', '["Nunca", "Rara vez (≤ 1/mes)", "Ocasional (2–3/mes)", "Frecuente (semanal)", "Muy frecuente (diaria)"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', now(), null, '["Inversión"]'::jsonb, 2, 3),

('DC-A19', 'Cuestionario', 'Adopción', '7', '15', 'Participo activamente en la definición de la hoja de ruta de IA para contabilidad, incluyendo priorización de casos de uso, plazos y responsables.', 'Multiple Choice (escala Likert A–E)', '["Nunca", "Rara vez (≤ 1/mes)", "Ocasional (2–3/mes)", "Frecuente (semanal)", "Muy frecuente (diaria)"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', now(), null, '["Aplicación"]'::jsonb, 2, 4),

('DC-A20', 'Cuestionario', 'Adopción', '7', '15', 'Impulso el uso de IA para generar alertas tempranas sobre riesgos contables, por ejemplo saldos inusuales o movimientos atípicos por segmento.', 'Multiple Choice (escala Likert A–E)', '["Nunca", "Rara vez (≤ 1/mes)", "Ocasional (2–3/mes)", "Frecuente (semanal)", "Muy frecuente (diaria)"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', now(), null, '["Aplicación", "Estrategia"]'::jsonb, 2, 4),

('DC-A21', 'Cuestionario', 'Adopción', '7', '15', 'Coordino con Auditoría Interna y Externa el uso de IA para facilitar pruebas, muestreos o análisis de transacciones.', 'Multiple Choice (escala Likert A–E)', '["Nunca", "Rara vez (≤ 1/mes)", "Ocasional (2–3/mes)", "Frecuente (semanal)", "Muy frecuente (diaria)"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', now(), null, '["Aplicación", "Estrategia"]'::jsonb, 2, 4),

('DC-A22', 'Cuestionario', 'Adopción', '7', '15', 'Monitoreo periódicamente métricas de desempeño de la IA, como precisión, tiempos de proceso y volumen de alertas útiles, y actúo en consecuencia.', 'Multiple Choice (escala Likert A–E)', '["Nunca", "Rara vez (≤ 1/mes)", "Ocasional (2–3/mes)", "Frecuente (semanal)", "Muy frecuente (diaria)"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', now(), null, '["Productividad"]'::jsonb, 2, 4),

('DC-A23', 'Cuestionario', 'Adopción', '7', '15', 'Incluyo en los comités de riesgo y control interno temas específicos sobre desempeño y riesgos de modelos de IA.', 'Multiple Choice (escala Likert A–E)', '["Nunca", "Rara vez (≤ 1/mes)", "Ocasional (2–3/mes)", "Frecuente (semanal)", "Muy frecuente (diaria)"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', now(), null, '["Estrategia"]'::jsonb, 2, 4),

('DC-A24', 'Cuestionario', 'Adopción', '7', '15', 'Gestiono el presupuesto de IA en contabilidad, incluyendo licencias, desarrollo y soporte, con una visión de portafolio de proyectos como prioridades, payback y retorno de inversión.', 'Multiple Choice (escala Likert A–E)', '["Nunca", "Rara vez (≤ 1/mes)", "Ocasional (2–3/mes)", "Frecuente (semanal)", "Muy frecuente (diaria)"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', now(), null, '["Inversión"]'::jsonb, 2, 4),

('DC-A25', 'Cuestionario', 'Adopción', '7', '15', 'Lidero discusiones con la Alta Dirección sobre cómo la IA en contabilidad puede habilitar nuevos modelos de reporte y toma de decisiones.', 'Multiple Choice (escala Likert A–E)', '["Nunca", "Rara vez (≤ 1/mes)", "Ocasional (2–3/mes)", "Frecuente (semanal)", "Muy frecuente (diaria)"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', now(), null, '["Aplicación"]'::jsonb, 2, 5),

('DC-A26', 'Cuestionario', 'Adopción', '7', '15', 'Promuevo el uso de modelos predictivos, como provisiones, flujo de caja y riesgo de cobranza, como insumo regular en la planificación financiera.', 'Multiple Choice (escala Likert A–E)', '["Nunca", "Rara vez (≤ 1/mes)", "Ocasional (2–3/mes)", "Frecuente (semanal)", "Muy frecuente (diaria)"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', now(), null, '["Aplicación", "Estrategia"]'::jsonb, 2, 5),

('DC-A27', 'Cuestionario', 'Adopción', '7', '15', 'Participo en comités corporativos de datos e IA para asegurar que las necesidades contables y de cumplimiento estén consideradas.', 'Multiple Choice (escala Likert A–E)', '["Nunca", "Rara vez (≤ 1/mes)", "Ocasional (2–3/mes)", "Frecuente (semanal)", "Muy frecuente (diaria)"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', now(), null, '["Aplicación", "Estrategia"]'::jsonb, 2, 5),

('DC-A28', 'Cuestionario', 'Adopción', '7', '15', 'Impulso la formación del equipo de contabilidad en competencias de datos e IA, incluyendo capacitaciones, certificaciones y mentoring.', 'Multiple Choice (escala Likert A–E)', '["Nunca", "Rara vez (≤ 1/mes)", "Ocasional (2–3/mes)", "Frecuente (semanal)", "Muy frecuente (diaria)"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', now(), null, '["Aplicación"]'::jsonb, 2, 5),

('DC-A29', 'Cuestionario', 'Adopción', '7', '15', 'Exijo que los proyectos de IA contable incluyan análisis de impacto ético, riesgos de sesgo y planes de mitigación.', 'Multiple Choice (escala Likert A–E)', '["Nunca", "Rara vez (≤ 1/mes)", "Ocasional (2–3/mes)", "Frecuente (semanal)", "Muy frecuente (diaria)"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', now(), null, '["Estrategia"]'::jsonb, 2, 5),

('DC-A30', 'Cuestionario', 'Adopción', '7', '15', 'Reviso periódicamente el portafolio de iniciativas de IA en contabilidad, priorizando aquellas con mayor impacto en valor para la organización y en cumplimiento.', 'Multiple Choice (escala Likert A–E)', '["Nunca", "Rara vez (≤ 1/mes)", "Ocasional (2–3/mes)", "Frecuente (semanal)", "Muy frecuente (diaria)"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', now(), null, '["Estrategia"]'::jsonb, 2, 5);

-- CONOCIMIENTO - Rol 15
INSERT INTO "public"."preguntas" ("codigo", "section", "bloque", "area_id", "exclusivo_rol_id", "texto", "tipo", "opciones", "locale", "peso", "escala", "scoring", "created_at", "respuesta_correcta", "dimension", "exclusivo_nivel_id", "dificultad") VALUES
('DC-C1', 'Cuestionario', 'Conocimiento', '7', '15', 'La siguiente es una descripción más precisa de IA en el contexto de contabilidad.', 'Multiple Choice (una respuesta)', '["Una hoja de cálculo con fórmulas avanzadas.", "Sistemas que aplican reglas fijas para automatizar tareas repetitivas.", "Sistemas que aprenden de datos para identificar patrones y apoyar decisiones contables.", "Cualquier software financiero instalado en el ERP."]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', now(), 'Sistemas que aprenden de datos para identificar patrones y apoyar decisiones contables.', '["Conocimiento"]'::jsonb, 2, 1),

('DC-C2', 'Cuestionario', 'Conocimiento', '7', '15', 'Cuál de los siguientes es un ejemplo típico de uso de IA en contabilidad', 'Multiple Choice (una respuesta)', '["Imprimir todas las facturas y archivarlas físicamente.", "Uso de un sistema que extrae y valida automáticamente datos de facturas PDF.", "Elaborar manualmente todos los asientos contables.", "Enviar estados financieros por correo electrónico."]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', now(), 'Uso de un sistema que extrae y valida automáticamente datos de facturas PDF.', '["Aplicación", "Conocimiento"]'::jsonb, 2, 1),

('DC-C3', 'Cuestionario', 'Conocimiento', '7', '15', 'La principal diferencia entre IA y automatización tradicional basada en macros o reglas es que la IA', 'Multiple Choice (una respuesta)', '["Siempre es más barata.", "No requiere datos históricos.", "Puede aprender de los datos y mejorar con el tiempo.", "Nunca comete errores."]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', now(), 'Puede aprender de los datos y mejorar con el tiempo.', '["Conocimiento"]'::jsonb, 2, 1),

('DC-C4', 'Cuestionario', 'Conocimiento', '7', '15', 'Qué riesgo es más relevante al usar IA con información contable sensible', 'Multiple Choice (una respuesta)', '["Que el ERP se vuelva más lento.", "Riesgos de privacidad, filtración de datos y cumplimiento normativo.", "Que el equipo trabaje más rápido.", "Que aumente el número de reportes generados."]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', now(), 'Riesgos de privacidad, filtración de datos y cumplimiento normativo.', '["Aplicación", "Conocimiento", "Estrategia"]'::jsonb, 2, 1),

('DC-C5', 'Cuestionario', 'Conocimiento', '7', '15', 'En el contexto de IA, el sesgo del modelo se refiere a', 'Multiple Choice (una respuesta)', '["Un error de tipeo en los asientos contables.", "Resultados sistemáticamente inclinados por la forma en que se entrenó el modelo o los datos usados.", "El favoritismo del director hacia un proveedor.", "Un cambio en la legislación fiscal."]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', now(), 'Resultados sistemáticamente inclinados por la forma en que se entrenó el modelo o los datos usados.', '["Conocimiento"]'::jsonb, 2, 1),

('DC-C6', 'Cuestionario', 'Conocimiento', '7', '15', 'Al evaluar una herramienta de IA para contabilidad, un criterio básico de inversión es', 'Multiple Choice (una respuesta)', '["Que tenga la interfaz más moderna.", "Que sea la herramienta más cara del mercado.", "Que el ahorro de tiempo y costo y la reducción de errores justifiquen la inversión.", "Que la recomiende cualquier compañero."]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', now(), 'Que el ahorro de tiempo y costo y la reducción de errores justifiquen la inversión.', '["Inversión", "Conocimiento"]'::jsonb, 2, 1),

('DC-C7', 'Cuestionario', 'Conocimiento', '7', '15', 'Cuál es un uso razonable de IA generativa para una Dirección de Contabilidad', 'Multiple Choice (una respuesta)', '["Aprobar automáticamente estados financieros sin revisión.", "Proponer borradores de políticas contables que luego se revisan y ajustan.", "Determinar por sí sola el tratamiento fiscal definitivo.", "Sustituir la opinión del auditor externo."]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', now(), 'Proponer borradores de políticas contables que luego se revisan y ajustan.', '["Aplicación", "Conocimiento"]'::jsonb, 2, 2),

('DC-C8', 'Cuestionario', 'Conocimiento', '7', '15', 'Un beneficio esperado de usar IA para capturar facturas de proveedores es principalmente', 'Multiple Choice (una respuesta)', '["Incrementar el volumen de papel impreso.", "Reducir la visibilidad de las operaciones.", "Disminuir errores manuales y acelerar el registro contable.", "Aumentar el tiempo de captura."]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', now(), 'Disminuir errores manuales y acelerar el registro contable.', '["Conocimiento"]'::jsonb, 2, 2),

('DC-C9', 'Cuestionario', 'Conocimiento', '7', '15', 'En el contexto de IA, entrenar un modelo significa', 'Multiple Choice (una respuesta)', '["Instalar el software en el servidor.", "Ajustar el modelo usando datos históricos para que aprenda patrones.", "Configurar usuarios en el ERP.", "Cambiar el plan de cuentas."]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', now(), 'Ajustar el modelo usando datos históricos para que aprenda patrones.', '["Conocimiento"]'::jsonb, 2, 2),

('DC-C10', 'Cuestionario', 'Conocimiento', '7', '15', 'Cuál de estas tareas es más adecuada para IA en auditoría interna contable', 'Multiple Choice (una respuesta)', '["Firmar los reportes de auditoría.", "Analizar grandes volúmenes de transacciones para identificar anomalías.", "Definir la estrategia corporativa de la empresa.", "Decidir sobre despidos."]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', now(), 'Analizar grandes volúmenes de transacciones para identificar anomalías.', '["Conocimiento", "Estrategia"]'::jsonb, 2, 2),

('DC-C11', 'Cuestionario', 'Conocimiento', '7', '15', 'Un riesgo de depender demasiado de la IA en contabilidad es', 'Multiple Choice (una respuesta)', '["Reducir la consistencia en la aplicación de políticas.", "Aceptar resultados sin cuestionarlos, aun cuando existan señales de error o sesgo.", "Que las personas aprendan más sobre datos.", "Aumentar la trazabilidad de decisiones."]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', now(), 'Aceptar resultados sin cuestionarlos, aun cuando existan señales de error o sesgo.', '["Conocimiento", "Estrategia"]'::jsonb, 2, 2),

('DC-C12', 'Cuestionario', 'Conocimiento', '7', '15', 'Desde la perspectiva de inversión, una buena práctica al evaluar proyectos de IA en contabilidad es', 'Multiple Choice (una respuesta)', '["No cuantificar el beneficio esperado.", "Ignorar la integración con sistemas actuales.", "Estimar ahorros de tiempo, reducción de errores y costos de implementación y mantenimiento.", "Solo comparar logos de proveedores."]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', now(), 'Estimar ahorros de tiempo, reducción de errores y costos de implementación y mantenimiento.', '["Inversión", "Conocimiento"]'::jsonb, 2, 2),

('DC-C13', 'Cuestionario', 'Conocimiento', '7', '15', 'Un sistema de IA que sugiere automáticamente posibles reclasificaciones contables en el cierre se considera principalmente', 'Multiple Choice (una respuesta)', '["Un reemplazo del ERP.", "Una capa de analítica y recomendación sobre el sistema contable.", "Una obligación legal.", "Un módulo de nómina."]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', now(), 'Una capa de analítica y recomendación sobre el sistema contable.', '["Conocimiento"]'::jsonb, 2, 3),

('DC-C14', 'Cuestionario', 'Conocimiento', '7', '15', 'Qué indicador refleja mejor el impacto de IA en la productividad del cierre contable', 'Multiple Choice (una respuesta)', '["Color de los reportes.", "Reducción de horas hombre invertidas en tareas repetitivas sin afectar la calidad.", "Número de reuniones sociales del equipo.", "Cantidad de hojas impresas."]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', now(), 'Reducción de horas hombre invertidas en tareas repetitivas sin afectar la calidad.', '["Productividad", "Conocimiento"]'::jsonb, 2, 3),

('DC-C15', 'Cuestionario', 'Conocimiento', '7', '15', 'En un modelo de IA para detectar transacciones atípicas, un falso positivo significa que', 'Multiple Choice (una respuesta)', '["El sistema no detecta ninguna anomalía.", "Se marca como sospechosa una transacción que en realidad es correcta.", "Se acepta una transacción fraudulenta como válida.", "El modelo deja de funcionar."]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', now(), 'Se marca como sospechosa una transacción que en realidad es correcta.', '["Conocimiento"]'::jsonb, 2, 3),

('DC-C16', 'Cuestionario', 'Conocimiento', '7', '15', 'Para integrar IA con el ERP contable, es clave asegurar que', 'Multiple Choice (una respuesta)', '["No exista trazabilidad entre sistemas.", "Los datos maestros, como catálogo de cuentas, centros de costo y proveedores, estén alineados.", "Los usuarios no tengan roles definidos.", "Se desactive el control interno actual."]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', now(), 'Los datos maestros, como catálogo de cuentas, centros de costo y proveedores, estén alineados.', '["Conocimiento"]'::jsonb, 2, 3),

('DC-C17', 'Cuestionario', 'Conocimiento', '7', '15', 'Desde la perspectiva estratégica, usar IA en conciliaciones bancarias permite', 'Multiple Choice (una respuesta)', '["Que el banco asuma toda la responsabilidad.", "Detección más rápida de discrepancias y reducción de riesgo operativo.", "Eliminar la supervisión humana.", "Hacer conciliaciones solo una vez al año."]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', now(), 'Detección más rápida de discrepancias y reducción de riesgo operativo.', '["Conocimiento"]'::jsonb, 2, 3),

('DC-C18', 'Cuestionario', 'Conocimiento', '7', '15', 'En términos de inversión, un error clásico al implementar IA en contabilidad es', 'Multiple Choice (una respuesta)', '["Considerar costos de capacitación.", "Subestimar el esfuerzo de limpieza y calidad de datos previo al proyecto.", "Medir ahorros potenciales.", "Analizar brechas de proceso."]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', now(), 'Subestimar el esfuerzo de limpieza y calidad de datos previo al proyecto.', '["Inversión", "Aplicación", "Conocimiento"]'::jsonb, 2, 3),

('DC-C19', 'Cuestionario', 'Conocimiento', '7', '15', 'Un enfoque adecuado para validar un modelo de IA usado en detección de fraudes contables es', 'Multiple Choice (una respuesta)', '["Confiar solo en la opinión del proveedor.", "Probar el modelo con datos históricos etiquetados, revisando tasas de falsos positivos y falsos negativos.", "Implementarlo directamente en producción sin pruebas.", "Evaluarlo solo por su interfaz gráfica."]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', now(), 'Probar el modelo con datos históricos etiquetados, revisando tasas de falsos positivos y falsos negativos.', '["Conocimiento"]'::jsonb, 2, 4),

('DC-C20', 'Cuestionario', 'Conocimiento', '7', '15', 'Gobernanza de modelos en el contexto de IA contable implica', 'Multiple Choice (una respuesta)', '["Tener al proveedor en el mismo país.", "Definir roles, criterios de aprobación, monitoreo continuo y documentación de modelos de IA.", "Instalar más servidores.", "Rotar al personal de contabilidad cada mes."]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', now(), 'Definir roles, criterios de aprobación, monitoreo continuo y documentación de modelos de IA.', '["Conocimiento", "Estrategia"]'::jsonb, 2, 4),

('DC-C21', 'Cuestionario', 'Conocimiento', '7', '15', 'Para evaluar el impacto estratégico de IA en el cierre contable, un indicador relevante es', 'Multiple Choice (una respuesta)', '["Número de reuniones del área.", "Días de reducción del ciclo de cierre sin aumentos de ajustes o reclasificaciones posteriores.", "Cantidad de correos enviados por el equipo.", "Número de impresoras en oficina."]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', now(), 'Días de reducción del ciclo de cierre sin aumentos de ajustes o reclasificaciones posteriores.', '["Conocimiento", "Estrategia"]'::jsonb, 2, 4),

('DC-C22', 'Cuestionario', 'Conocimiento', '7', '15', 'Cuál es un uso avanzado de IA en reporting financiero', 'Multiple Choice (una respuesta)', '["Enviar estados financieros por correo.", "Generar narrativas automáticas que expliquen variaciones significativas en estados financieros a partir de datos.", "Cambiar manualmente cada celda de un Excel.", "Firmar digitalmente reportes."]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', now(), 'Generar narrativas automáticas que expliquen variaciones significativas en estados financieros a partir de datos.', '["Inversión", "Aplicación", "Conocimiento"]'::jsonb, 2, 4),

('DC-C23', 'Cuestionario', 'Conocimiento', '7', '15', 'Desde la perspectiva de inversión, un portafolio de proyectos de IA en contabilidad bien gestionado debería', 'Multiple Choice (una respuesta)', '["Concentrar todo el presupuesto en una sola herramienta.", "Equilibrar quick wins operativos con proyectos estratégicos de mayor impacto y plazo.", "Evitar cualquier tipo de piloto o prueba.", "No requerir seguimiento de ROI."]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', now(), 'Equilibrar quick wins operativos con proyectos estratégicos de mayor impacto y plazo.', '["Inversión", "Conocimiento"]'::jsonb, 2, 4),

('DC-C24', 'Cuestionario', 'Conocimiento', '7', '15', 'En términos de ética, al usar IA para calificar riesgos de clientes o proveedores es importante', 'Multiple Choice (una respuesta)', '["No documentar los criterios para evitar auditorías.", "Revisar que los datos no generen discriminación indebida y que las reglas sean explicables.", "Excluir cualquier revisión humana.", "Usar solo datos no relacionados con el negocio."]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', now(), 'Revisar que los datos no generen discriminación indebida y que las reglas sean explicables.', '["Conocimiento", "Estrategia"]'::jsonb, 2, 4),

('DC-C25', 'Cuestionario', 'Conocimiento', '7', '15', 'Un modelo de IA que pronostica provisiones o deterioros de cuentas por cobrar a partir de comportamiento histórico se clasifica como', 'Multiple Choice (una respuesta)', '["Automatización de tareas físicas.", "Modelo predictivo de riesgo de crédito o cobranza.", "Sistema de nómina.", "Herramienta de firma digital."]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', now(), 'Modelo predictivo de riesgo de crédito o cobranza.', '["Conocimiento"]'::jsonb, 2, 5),

('DC-C26', 'Cuestionario', 'Conocimiento', '7', '15', 'Al integrar IA en decisiones contables con impacto material en estados financieros, es clave asegurar que', 'Multiple Choice (una respuesta)', '["Solo el proveedor entienda el funcionamiento del modelo.", "Exista documentación de supuestos, límites de uso y procesos de override humano.", "No haya trazabilidad de decisiones.", "El modelo se ejecute sin registros."]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', now(), 'Exista documentación de supuestos, límites de uso y procesos de override humano.', '["Inversión", "Conocimiento"]'::jsonb, 2, 5),

('DC-C27', 'Cuestionario', 'Conocimiento', '7', '15', 'Desde la perspectiva estratégica de la organización, el rol de la Dirección de Contabilidad respecto a IA debería incluir', 'Multiple Choice (una respuesta)', '["Limitarse a registrar transacciones.", "Aportar información y criterios para que la IA soporte decisiones de negocio como riesgos, márgenes y cumplimiento.", "Solo negociar licencias de software.", "Delegar todas las decisiones en TI."]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', now(), 'Aportar información y criterios para que la IA soporte decisiones de negocio como riesgos, márgenes y cumplimiento.', '["Conocimiento"]'::jsonb, 2, 5),

('DC-C28', 'Cuestionario', 'Conocimiento', '7', '15', 'Qué enfoque de medición de impacto de IA habilita mejor comparaciones entre áreas o periodos', 'Multiple Choice (una respuesta)', '["Opiniones subjetivas del equipo.", "KPIs cuantitativos como tiempo de cierre, errores detectados y costo por transacción antes y después de la implementación.", "Número de reuniones virtuales.", "Cantidad de correos enviados."]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', now(), 'KPIs cuantitativos como tiempo de cierre, errores detectados y costo por transacción antes y después de la implementación.', '["Conocimiento"]'::jsonb, 2, 5),

('DC-C29', 'Cuestionario', 'Conocimiento', '7', '15', 'En términos de inversión, una estrategia madura de IA en contabilidad debe considerar', 'Multiple Choice (una respuesta)', '["Solo costos de licencias anuales.", "Costos y beneficios a lo largo del ciclo de vida, incluyendo datos, gobernanza, mantenimiento y actualización de modelos.", "Exclusivamente el precio inicial.", "Evitar medir beneficios intangibles."]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', now(), 'Costos y beneficios a lo largo del ciclo de vida, incluyendo datos, gobernanza, mantenimiento y actualización de modelos.', '["Inversión", "Conocimiento", "Estrategia"]'::jsonb, 2, 5),

('DC-C30', 'Cuestionario', 'Conocimiento', '7', '15', 'Desde la perspectiva ética y regulatoria, el uso de IA en contabilidad debería alinearse con', 'Multiple Choice (una respuesta)', '["Solo las preferencias internas del área.", "Normas contables, regulatorias, políticas de datos y principios de IA responsable de la organización.", "Lo que indiquen redes sociales.", "Decisiones ad hoc según cada caso sin criterios claros."]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', now(), 'Normas contables, regulatorias, políticas de datos y principios de IA responsable de la organización.', '["Aplicación", "Conocimiento", "Estrategia"]'::jsonb, 2, 5);
