-- ============================================================================
-- PREGUNTAS PARA DIRECCIÓN DE FINANZAS (CFO)
-- ============================================================================
-- Rol incluido:
--   - Rol ID 13: Dirección de Finanzas (CFO) (area_id: 5, nivel_id: 2)
-- ============================================================================

-- ============================================================================
-- ROL 13: Dirección de Finanzas (CFO)
-- ============================================================================

-- ADOPCIÓN - Rol 13
INSERT INTO "public"."preguntas" ("codigo", "section", "bloque", "area_id", "exclusivo_rol_id", "texto", "tipo", "opciones", "locale", "peso", "escala", "scoring", "created_at", "respuesta_correcta", "dimension", "exclusivo_nivel_id", "dificultad") VALUES
('DF-A1', 'Cuestionario', 'Adopción', '5', '13', '¿Con qué frecuencia exploras artículos, webinars o cursos sobre IA aplicada a finanzas o al rol de CFO?', 'Multiple Choice (escala Likert A–E)', '["Nunca", "Rara vez (≤ 1/mes)", "Ocasional (2–3/mes)", "Frecuente (semanal)", "Casi siempre / sistemáticamente"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', now(), null, '["Aplicación"]'::jsonb, 2, 1),

('DF-A2', 'Cuestionario', 'Adopción', '5', '13', '¿Con qué frecuencia pruebas herramientas de IA para preparar resúmenes o explicaciones de reportes financieros?', 'Multiple Choice (escala Likert A–E)', '["Nunca", "Rara vez (≤ 1/mes)", "Ocasional (2–3/mes)", "Frecuente (semanal)", "Casi siempre / sistemáticamente"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', now(), null, '["Productividad", "Inversión", "Aplicación"]'::jsonb, 2, 1),

('DF-A3', 'Cuestionario', 'Adopción', '5', '13', '¿Con qué frecuencia has planteado en tu equipo la posibilidad de automatizar con IA tareas repetitivas financieras como conciliaciones o extracción de datos?', 'Multiple Choice (escala Likert A–E)', '["Nunca", "Rara vez (≤ 1/mes)", "Ocasional (2–3/mes)", "Frecuente (semanal)", "Casi siempre / sistemáticamente"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', now(), null, '["Productividad", "Aplicación"]'::jsonb, 2, 1),

('DF-A4', 'Cuestionario', 'Adopción', '5', '13', '¿Con qué frecuencia discutes con otros directores el potencial de la IA para mejorar forecasting, control de gastos o gestión de riesgo financiero?', 'Multiple Choice (escala Likert A–E)', '["Nunca", "Rara vez (≤ 1/mes)", "Ocasional (2–3/mes)", "Frecuente (semanal)", "Casi siempre / sistemáticamente"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', now(), null, '["Estrategia", "Inversión"]'::jsonb, 2, 1),

('DF-A5', 'Cuestionario', 'Adopción', '5', '13', '¿Con qué frecuencia participas en conversaciones con TI o datos sobre la viabilidad de proyectos de IA en finanzas?', 'Multiple Choice (escala Likert A–E)', '["Nunca", "Rara vez (≤ 1/mes)", "Ocasional (2–3/mes)", "Frecuente (semanal)", "Casi siempre / sistemáticamente"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', now(), null, '["Aplicación"]'::jsonb, 2, 1),

('DF-A6', 'Cuestionario', 'Adopción', '5', '13', '¿Con qué frecuencia revisas, aunque sea de forma exploratoria, el presupuesto que podría destinarse a iniciativas de IA en la función financiera?', 'Multiple Choice (escala Likert A–E)', '["Nunca", "Rara vez (≤ 1/mes)", "Ocasional (2–3/mes)", "Frecuente (semanal)", "Casi siempre / sistemáticamente"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', now(), null, '["Estrategia", "Inversión"]'::jsonb, 2, 1),

('DF-A7', 'Cuestionario', 'Adopción', '5', '13', '¿Con qué frecuencia ejecutas o supervisas pilotos de IA en procesos financieros específicos con métricas definidas?', 'Multiple Choice (escala Likert A–E)', '["Nunca", "Rara vez (≤ 1/mes)", "Ocasional (2–3/mes)", "Frecuente (semanal)", "Casi siempre / sistemáticamente"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', now(), null, '["Productividad", "Inversión"]'::jsonb, 2, 2),

('DF-A8', 'Cuestionario', 'Adopción', '5', '13', '¿Con qué frecuencia incorporas resultados de herramientas de IA como alertas de anomalías o scoring de riesgo en tus discusiones financieras con tu equipo?', 'Multiple Choice (escala Likert A–E)', '["Nunca", "Rara vez (≤ 1/mes)", "Ocasional (2–3/mes)", "Frecuente (semanal)", "Casi siempre / sistemáticamente"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', now(), null, '["Estrategia", "Productividad", "Aplicación"]'::jsonb, 2, 2),

('DF-A9', 'Cuestionario', 'Adopción', '5', '13', '¿Con qué frecuencia ajustas procesos financieros como controles y flujos de aprobación como consecuencia de lecciones aprendidas en pilotos de IA?', 'Multiple Choice (escala Likert A–E)', '["Nunca", "Rara vez (≤ 1/mes)", "Ocasional (2–3/mes)", "Frecuente (semanal)", "Casi siempre / sistemáticamente"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', now(), null, '["Inversión"]'::jsonb, 2, 2),

('DF-A10', 'Cuestionario', 'Adopción', '5', '13', '¿Con qué frecuencia trabajas con TI o datos para mejorar la calidad de datos en los procesos donde estás probando IA?', 'Multiple Choice (escala Likert A–E)', '["Nunca", "Rara vez (≤ 1/mes)", "Ocasional (2–3/mes)", "Frecuente (semanal)", "Casi siempre / sistemáticamente"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', now(), null, '["Aplicación"]'::jsonb, 2, 2),

('DF-A11', 'Cuestionario', 'Adopción', '5', '13', '¿Con qué frecuencia presentas al CEO o Comité de Dirección un caso de negocio resumido de los pilotos de IA con beneficios, riesgos y siguientes pasos?', 'Multiple Choice (escala Likert A–E)', '["Nunca", "Rara vez (≤ 1/mes)", "Ocasional (2–3/mes)", "Frecuente (semanal)", "Casi siempre / sistemáticamente"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', now(), null, '["Estrategia"]'::jsonb, 2, 2),

('DF-A12', 'Cuestionario', 'Adopción', '5', '13', '¿Con qué frecuencia consideras explícitamente riesgos éticos o de cumplimiento al decidir extender un piloto de IA en finanzas?', 'Multiple Choice (escala Likert A–E)', '["Nunca", "Rara vez (≤ 1/mes)", "Ocasional (2–3/mes)", "Frecuente (semanal)", "Casi siempre / sistemáticamente"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', now(), null, '["Estrategia"]'::jsonb, 2, 2),

('DF-A13', 'Cuestionario', 'Adopción', '5', '13', '¿Con qué frecuencia utilizas salidas de modelos de IA como forecasting o análisis de escenarios en presentaciones formales a CEO o Consejo?', 'Multiple Choice (escala Likert A–E)', '["Nunca", "Rara vez (≤ 1/mes)", "Ocasional (2–3/mes)", "Frecuente (semanal)", "Casi siempre / sistemáticamente"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', now(), null, '["Aplicación"]'::jsonb, 2, 3),

('DF-A14', 'Cuestionario', 'Adopción', '5', '13', '¿Con qué frecuencia tu equipo de finanzas interactúa con herramientas de IA integradas al ERP como recomendaciones en cash application o alertas de gasto?', 'Multiple Choice (escala Likert A–E)', '["Nunca", "Rara vez (≤ 1/mes)", "Ocasional (2–3/mes)", "Frecuente (semanal)", "Casi siempre / sistemáticamente"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', now(), null, '["Aplicación"]'::jsonb, 2, 3),

('DF-A15', 'Cuestionario', 'Adopción', '5', '13', '¿Con qué frecuencia revisas KPI específicos de IA como porcentaje de conciliaciones automatizadas o precisión de forecasting con IA frente a sin IA?', 'Multiple Choice (escala Likert A–E)', '["Nunca", "Rara vez (≤ 1/mes)", "Ocasional (2–3/mes)", "Frecuente (semanal)", "Casi siempre / sistemáticamente"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', now(), null, '["Productividad"]'::jsonb, 2, 3),

('DF-A16', 'Cuestionario', 'Adopción', '5', '13', '¿Con qué frecuencia promueves sesiones conjuntas entre finanzas, TI y negocio para revisar y ajustar modelos de IA financieros?', 'Multiple Choice (escala Likert A–E)', '["Nunca", "Rara vez (≤ 1/mes)", "Ocasional (2–3/mes)", "Frecuente (semanal)", "Casi siempre / sistemáticamente"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', now(), null, '["Inversión"]'::jsonb, 2, 3),

('DF-A17', 'Cuestionario', 'Adopción', '5', '13', '¿Con qué frecuencia ajustas presupuestos o recursos internos para fortalecer proyectos de IA que han demostrado impacto en resultados financieros?', 'Multiple Choice (escala Likert A–E)', '["Nunca", "Rara vez (≤ 1/mes)", "Ocasional (2–3/mes)", "Frecuente (semanal)", "Casi siempre / sistemáticamente"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', now(), null, '["Productividad", "Inversión"]'::jsonb, 2, 3),

('DF-A18', 'Cuestionario', 'Adopción', '5', '13', '¿Con qué frecuencia revisas con tu equipo riesgos de sesgo, cumplimiento y seguridad asociados al uso ya integrado de IA en finanzas?', 'Multiple Choice (escala Likert A–E)', '["Nunca", "Rara vez (≤ 1/mes)", "Ocasional (2–3/mes)", "Frecuente (semanal)", "Casi siempre / sistemáticamente"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', now(), null, '["Estrategia", "Aplicación"]'::jsonb, 2, 3),

('DF-A19', 'Cuestionario', 'Adopción', '5', '13', '¿Con qué frecuencia lideras discusiones de alto nivel sobre priorización de iniciativas de IA con el CEO y otros ejecutivos C-level?', 'Multiple Choice (escala Likert A–E)', '["Nunca", "Rara vez (≤ 1/mes)", "Ocasional (2–3/mes)", "Frecuente (semanal)", "Casi siempre / sistemáticamente"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', now(), null, '["Estrategia"]'::jsonb, 2, 4),

('DF-A20', 'Cuestionario', 'Adopción', '5', '13', '¿Con qué frecuencia utilizas paneles integrados de finanzas e IA para monitorear en tiempo casi real riesgos, flujo de caja y KPIs clave?', 'Multiple Choice (escala Likert A–E)', '["Nunca", "Rara vez (≤ 1/mes)", "Ocasional (2–3/mes)", "Frecuente (semanal)", "Casi siempre / sistemáticamente"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', now(), null, '["Estrategia", "Productividad", "Aplicación"]'::jsonb, 2, 4),

('DF-A21', 'Cuestionario', 'Adopción', '5', '13', '¿Con qué frecuencia tomas decisiones sobre reasignar capital o recursos basándote en insights generados por modelos de IA financieros?', 'Multiple Choice (escala Likert A–E)', '["Nunca", "Rara vez (≤ 1/mes)", "Ocasional (2–3/mes)", "Frecuente (semanal)", "Casi siempre / sistemáticamente"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', now(), null, '["Productividad", "Inversión"]'::jsonb, 2, 4),

('DF-A22', 'Cuestionario', 'Adopción', '5', '13', '¿Con qué frecuencia impulsas iniciativas transversales para definir políticas de uso responsable de IA en finanzas junto con negocio, legal y compliance?', 'Multiple Choice (escala Likert A–E)', '["Nunca", "Rara vez (≤ 1/mes)", "Ocasional (2–3/mes)", "Frecuente (semanal)", "Casi siempre / sistemáticamente"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', now(), null, '["Estrategia", "Aplicación"]'::jsonb, 2, 4),

('DF-A23', 'Cuestionario', 'Adopción', '5', '13', '¿Con qué frecuencia revisas reportes de performance de modelos como drift, sesgo y calidad de datos y tomas acciones correctivas en IA financiera?', 'Multiple Choice (escala Likert A–E)', '["Nunca", "Rara vez (≤ 1/mes)", "Ocasional (2–3/mes)", "Frecuente (semanal)", "Casi siempre / sistemáticamente"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', now(), null, '["Productividad", "Aplicación"]'::jsonb, 2, 4),

('DF-A24', 'Cuestionario', 'Adopción', '5', '13', '¿Con qué frecuencia patrocinas programas de formación en IA y analítica para tu equipo de finanzas a fin de elevar sus capacidades?', 'Multiple Choice (escala Likert A–E)', '["Nunca", "Rara vez (≤ 1/mes)", "Ocasional (2–3/mes)", "Frecuente (semanal)", "Casi siempre / sistemáticamente"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', now(), null, '["Aplicación"]'::jsonb, 2, 4),

('DF-A25', 'Cuestionario', 'Adopción', '5', '13', '¿Con qué frecuencia lideras la definición o ajuste del roadmap corporativo de IA asegurando que las iniciativas financieras estén alineadas con la estrategia global?', 'Multiple Choice (escala Likert A–E)', '["Nunca", "Rara vez (≤ 1/mes)", "Ocasional (2–3/mes)", "Frecuente (semanal)", "Casi siempre / sistemáticamente"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', now(), null, '["Estrategia"]'::jsonb, 2, 5),

('DF-A26', 'Cuestionario', 'Adopción', '5', '13', '¿Con qué frecuencia decides sobre grandes inversiones o desinversiones en plataformas de IA basándote en un portafolio global de casos de uso y ROI financiero?', 'Multiple Choice (escala Likert A–E)', '["Nunca", "Rara vez (≤ 1/mes)", "Ocasional (2–3/mes)", "Frecuente (semanal)", "Casi siempre / sistemáticamente"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', now(), null, '["Inversión", "Aplicación"]'::jsonb, 2, 5),

('DF-A27', 'Cuestionario', 'Adopción', '5', '13', '¿Con qué frecuencia impulsas iniciativas para integrar IA avanzada como modelos explicables o agentes autónomos en procesos críticos de finanzas como tesorería o riesgo de crédito?', 'Multiple Choice (escala Likert A–E)', '["Nunca", "Rara vez (≤ 1/mes)", "Ocasional (2–3/mes)", "Frecuente (semanal)", "Casi siempre / sistemáticamente"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', now(), null, '["Estrategia"]'::jsonb, 2, 5),

('DF-A28', 'Cuestionario', 'Adopción', '5', '13', '¿Con qué frecuencia trabajas de forma estructurada con reguladores, auditores y legal o compliance para asegurar que el uso de IA financiera cumple estándares y regulaciones?', 'Multiple Choice (escala Likert A–E)', '["Nunca", "Rara vez (≤ 1/mes)", "Ocasional (2–3/mes)", "Frecuente (semanal)", "Casi siempre / sistemáticamente"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', now(), null, '["Aplicación"]'::jsonb, 2, 5),

('DF-A29', 'Cuestionario', 'Adopción', '5', '13', '¿Con qué frecuencia promueves que los resultados de IA se integren en los procesos de planeación estratégica, fusiones y adquisiciones, asignación de capital y gestión de portafolio corporativo?', 'Multiple Choice (escala Likert A–E)', '["Nunca", "Rara vez (≤ 1/mes)", "Ocasional (2–3/mes)", "Frecuente (semanal)", "Casi siempre / sistemáticamente"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', now(), null, '["Productividad"]'::jsonb, 2, 5),

('DF-A30', 'Cuestionario', 'Adopción', '5', '13', '¿Con qué frecuencia apadrinas, comunicas y modelas una cultura donde finanzas sea referente de uso responsable y sofisticado de IA en toda la organización?', 'Multiple Choice (escala Likert A–E)', '["Nunca", "Rara vez (≤ 1/mes)", "Ocasional (2–3/mes)", "Frecuente (semanal)", "Casi siempre / sistemáticamente"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', now(), null, '["Aplicación"]'::jsonb, 2, 5);

-- CONOCIMIENTO - Rol 13
INSERT INTO "public"."preguntas" ("codigo", "section", "bloque", "area_id", "exclusivo_rol_id", "texto", "tipo", "opciones", "locale", "peso", "escala", "scoring", "created_at", "respuesta_correcta", "dimension", "exclusivo_nivel_id", "dificultad") VALUES
('DF-C1', 'Cuestionario', 'Conocimiento', '5', '13', '¿Cuál de las siguientes opciones describe mejor la IA en el contexto financiero?', 'Multiple Choice (una respuesta)', '["Un sistema que sólo automatiza tareas repetitivas siguiendo reglas fijas.", "Un conjunto de técnicas que permiten a los sistemas aprender de datos y apoyar decisiones financieras.", "Un software exclusivamente para procesar nómina.", "Un tipo de hardware especializado para contabilidad."]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', now(), 'Un conjunto de técnicas que permiten a los sistemas aprender de datos y apoyar decisiones financieras.', '["Inversión", "Conocimiento"]'::jsonb, 2, 1),

('DF-C2', 'Cuestionario', 'Conocimiento', '5', '13', '¿Qué tarea financiera es un caso típico para aplicar IA?', 'Multiple Choice (una respuesta)', '["Firmar manualmente cheques.", "Redactar la política de viáticos.", "Predecir flujo de caja a partir de datos históricos y variables externas.", "Definir la estructura legal de la empresa."]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', now(), 'Predecir flujo de caja a partir de datos históricos y variables externas.', '["Aplicación", "Conocimiento"]'::jsonb, 2, 1),

('DF-C3', 'Cuestionario', 'Conocimiento', '5', '13', '¿Qué beneficio directo puede aportar la IA en el cierre contable?', 'Multiple Choice (una respuesta)', '["Aumentar el tiempo de conciliación manual.", "Disminuir la visibilidad del auditor externo.", "Automatizar conciliaciones y detección de partidas inusuales.", "Eliminar la necesidad de controles internos."]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', now(), 'Automatizar conciliaciones y detección de partidas inusuales.', '["Conocimiento"]'::jsonb, 2, 1),

('DF-C4', 'Cuestionario', 'Conocimiento', '5', '13', '¿Cuál es un riesgo clave al usar IA en decisiones financieras?', 'Multiple Choice (una respuesta)', '["Tener demasiados datos limpios.", "Que el modelo aprenda patrones sesgados o poco explicables.", "Que el cierre contable sea demasiado rápido.", "Que el número de reportes disminuya."]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', now(), 'Que el modelo aprenda patrones sesgados o poco explicables.', '["Estrategia", "Conocimiento"]'::jsonb, 2, 1),

('DF-C5', 'Cuestionario', 'Conocimiento', '5', '13', '¿Qué elemento es imprescindible antes de invertir en un proyecto de IA financiera?', 'Multiple Choice (una respuesta)', '["Contratar al proveedor más caro.", "Tener un logo atractivo para el proyecto.", "Definir caso de negocio, métricas esperadas y calidad de datos.", "Aumentar el número de reportes manuales."]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', now(), 'Definir caso de negocio, métricas esperadas y calidad de datos.', '["Conocimiento"]'::jsonb, 2, 1),

('DF-C6', 'Cuestionario', 'Conocimiento', '5', '13', '¿Qué rol suele ser un aliado natural del CFO para proyectos de IA?', 'Multiple Choice (una respuesta)', '["Únicamente el área de marketing.", "El área de TI / datos.", "El área de mantenimiento.", "Sólo el área legal."]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', now(), 'El área de TI / datos.', '["Conocimiento"]'::jsonb, 2, 1),

('DF-C7', 'Cuestionario', 'Conocimiento', '5', '13', '¿Qué describe mejor un piloto de IA bien planteado en finanzas?', 'Multiple Choice (una respuesta)', '["Probar cualquier herramienta sin objetivos claros.", "Un experimento acotado con un proceso específico, métricas y periodo de prueba definidos.", "Cambiar todo el ERP por IA.", "Usar IA sólo porque la competencia lo hace."]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', now(), 'Un experimento acotado con un proceso específico, métricas y periodo de prueba definidos.', '["Conocimiento"]'::jsonb, 2, 2),

('DF-C8', 'Cuestionario', 'Conocimiento', '5', '13', '¿En qué proceso financiero suele verse un beneficio rápido de IA?', 'Multiple Choice (una respuesta)', '["Aprobación manual de vacaciones.", "Automatización de extracción y clasificación de facturas en cuentas por pagar.", "Diseño del organigrama de la empresa.", "Firma de contratos con proveedores."]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', now(), 'Automatización de extracción y clasificación de facturas en cuentas por pagar.', '["Inversión", "Conocimiento"]'::jsonb, 2, 2),

('DF-C9', 'Cuestionario', 'Conocimiento', '5', '13', '¿Cuál es un indicador razonable de éxito en un piloto de IA para conciliación contable?', 'Multiple Choice (una respuesta)', '["Número de hojas de cálculo usadas.", "Reducción del tiempo de conciliación, mejora en tasa de coincidencias y menos errores.", "Cantidad de correos enviados por el equipo.", "Número de reuniones sobre el tema."]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', now(), 'Reducción del tiempo de conciliación, mejora en tasa de coincidencias y menos errores.', '["Conocimiento"]'::jsonb, 2, 2),

('DF-C10', 'Cuestionario', 'Conocimiento', '5', '13', 'Un modelo de IA para detectar anomalías en gastos:', 'Multiple Choice (una respuesta)', '["Sólo sirve si reemplaza totalmente al área de auditoría.", "Puede apoyar a auditoría identificando transacciones inusuales para revisión.", "No es útil si la empresa es pequeña.", "Es obligatorio en todas las empresas."]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', now(), 'Puede apoyar a auditoría identificando transacciones inusuales para revisión.', '["Conocimiento"]'::jsonb, 2, 2),

('DF-C11', 'Cuestionario', 'Conocimiento', '5', '13', '¿Qué aspecto ético debe considerar un CFO al aprobar un piloto de IA financiera?', 'Multiple Choice (una respuesta)', '["Que los modelos sean lo más opacos posible.", "Que nadie en el equipo entienda cómo funciona.", "Cómo se manejan datos sensibles, sesgos y trazabilidad de decisiones.", "Que el proveedor tenga un logo atractivo."]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', now(), 'Cómo se manejan datos sensibles, sesgos y trazabilidad de decisiones.', '["Conocimiento"]'::jsonb, 2, 2),

('DF-C12', 'Cuestionario', 'Conocimiento', '5', '13', '¿Qué refleja mejor una inversión táctica en IA?', 'Multiple Choice (una respuesta)', '["Pequeñas inversiones piloto enfocadas en quick wins con ROI medible.", "Un cambio total de la arquitectura tecnológica de la empresa.", "Un aumento general del presupuesto sin destino claro.", "Sólo contratar más analistas junior."]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', now(), 'Pequeñas inversiones piloto enfocadas en quick wins con ROI medible.', '["Inversión", "Conocimiento"]'::jsonb, 2, 2),

('DF-C13', 'Cuestionario', 'Conocimiento', '5', '13', 'Al integrar IA en forecasting financiero, ¿qué práctica es más adecuada?', 'Multiple Choice (una respuesta)', '["Delegar completamente las proyecciones al modelo sin revisión humana.", "Combinar proyecciones de IA con juicio del CFO y del equipo FP&A.", "Usar IA sólo para formatear gráficos.", "Cambiar las proyecciones cada vez que el modelo se ejecuta."]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', now(), 'Combinar proyecciones de IA con juicio del CFO y del equipo FP&A.', '["Inversión", "Conocimiento"]'::jsonb, 2, 3),

('DF-C14', 'Cuestionario', 'Conocimiento', '5', '13', '¿Qué caracteriza a un proceso integrado de cierre contable con IA?', 'Multiple Choice (una respuesta)', '["La IA sólo genera decoraciones visuales para los informes.", "La IA está embebida en conciliaciones, detección de anomalías y preparación de reportes.", "El equipo de finanzas sólo revisa reportes manuales.", "No se mide ningún indicador de tiempo o calidad."]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', now(), 'La IA está embebida en conciliaciones, detección de anomalías y preparación de reportes.', '["Conocimiento"]'::jsonb, 2, 3),

('DF-C15', 'Cuestionario', 'Conocimiento', '5', '13', '¿Qué es importante al usar IA para cash flow en tiempo casi real?', 'Multiple Choice (una respuesta)', '["No conectar la IA a sistemas transaccionales.", "Actualizar los datos de ERP y bancos y monitorear desviaciones clave de forma continua.", "Limitar el modelo a un solo escenario fijo al año.", "Evitar cualquier interacción con tesorería."]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', now(), 'Actualizar los datos de ERP y bancos y monitorear desviaciones clave de forma continua.', '["Productividad", "Conocimiento"]'::jsonb, 2, 3),

('DF-C16', 'Cuestionario', 'Conocimiento', '5', '13', 'Respecto a la transparencia de modelos de IA en finanzas:', 'Multiple Choice (una respuesta)', '["No es relevante si el modelo tiene buen performance.", "Es clave contar con explicaciones comprensibles para auditores y reguladores.", "Sólo importa para marketing.", "Es un tema exclusivo del área de TI."]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', now(), 'Es clave contar con explicaciones comprensibles para auditores y reguladores.', '["Conocimiento"]'::jsonb, 2, 3),

('DF-C17', 'Cuestionario', 'Conocimiento', '5', '13', '¿Qué factor ayuda a priorizar procesos para integrar IA?', 'Multiple Choice (una respuesta)', '["Procesos con poco impacto financiero y bajo volumen de datos.", "Procesos de alto volumen, repetitivos y con impacto material en resultados.", "Procesos puramente creativos sin datos.", "Procesos que ya están completamente optimizados manualmente."]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', now(), 'Procesos de alto volumen, repetitivos y con impacto material en resultados.', '["Estrategia", "Conocimiento"]'::jsonb, 2, 3),

('DF-C18', 'Cuestionario', 'Conocimiento', '5', '13', '¿Qué rol debería jugar el CFO en la capacitación del equipo de finanzas en IA?', 'Multiple Choice (una respuesta)', '["Ninguno, es un tema sólo técnico.", "Definir competencias mínimas y apoyar programas de upskilling específicos.", "Delegar todo a Recursos Humanos sin involucrarse.", "Evitar que el equipo use IA para no cambiar procesos."]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', now(), 'Definir competencias mínimas y apoyar programas de upskilling específicos.', '["Aplicación", "Conocimiento"]'::jsonb, 2, 3),

('DF-C19', 'Cuestionario', 'Conocimiento', '5', '13', 'En una transformación de IA en finanzas, ¿qué enfoque de portafolio es más sólido?', 'Multiple Choice (una respuesta)', '["Invertir en muchos proyectos dispersos sin priorización.", "Priorizar iniciativas según impacto financiero esperado, riesgo y viabilidad de datos.", "Concentrarse sólo en proyectos vistosos para prensa.", "Evitar proyectos que afecten procesos core."]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', now(), 'Priorizar iniciativas según impacto financiero esperado, riesgo y viabilidad de datos.', '["Aplicación", "Conocimiento"]'::jsonb, 2, 4),

('DF-C20', 'Cuestionario', 'Conocimiento', '5', '13', '¿Qué describe un uso estratégico de IA en planificación de escenarios?', 'Multiple Choice (una respuesta)', '["Generar sólo un escenario base al año.", "Usar IA para simular múltiples escenarios de mercado, costos y demanda y apoyar decisiones de capital.", "Usar IA únicamente para mostrar gráficos de colores.", "Ignorar variables externas en los modelos."]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', now(), 'Usar IA para simular múltiples escenarios de mercado, costos y demanda y apoyar decisiones de capital.', '["Estrategia", "Aplicación", "Conocimiento"]'::jsonb, 2, 4),

('DF-C21', 'Cuestionario', 'Conocimiento', '5', '13', 'Respecto a gobierno de modelos de IA:', 'Multiple Choice (una respuesta)', '["No se requiere documentación si el modelo es preciso.", "Es necesario un marco de gobierno que defina roles, validaciones, monitoreo y documentación.", "Es responsabilidad exclusiva del proveedor.", "Debe decidirlo cada analista de manera individual."]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', now(), 'Es necesario un marco de gobierno que defina roles, validaciones, monitoreo y documentación.', '["Conocimiento"]'::jsonb, 2, 4),

('DF-C22', 'Cuestionario', 'Conocimiento', '5', '13', '¿Cómo puede el CFO usar IA para gestionar riesgo de crédito o contrapartes?', 'Multiple Choice (una respuesta)', '["Eliminar cualquier análisis humano.", "Complementar el scoring tradicional con modelos de IA que analicen patrones históricos y señales externas.", "Ignorar datos históricos.", "Dar a todos los clientes el mismo límite de crédito."]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', now(), 'Complementar el scoring tradicional con modelos de IA que analicen patrones históricos y señales externas.', '["Estrategia", "Conocimiento"]'::jsonb, 2, 4),

('DF-C23', 'Cuestionario', 'Conocimiento', '5', '13', 'En términos de talento, un CFO que lidera transformación con IA debería:', 'Multiple Choice (una respuesta)', '["Mantener los roles tal como están, sin nuevas habilidades.", "Impulsar nuevas habilidades analíticas, de datos y colaboración con TI en su equipo.", "Reemplazar a todos por perfiles puramente técnicos.", "Externalizar por completo la función financiera."]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', now(), 'Impulsar nuevas habilidades analíticas, de datos y colaboración con TI en su equipo.', '["Aplicación", "Conocimiento"]'::jsonb, 2, 4),

('DF-C24', 'Cuestionario', 'Conocimiento', '5', '13', '¿Qué enfoque es adecuado para gestionar el ROI de IA a escala?', 'Multiple Choice (una respuesta)', '["No medir resultados, sólo percepciones.", "Definir métricas financieras claras como ahorros, ingresos incrementales y reducción de riesgo, y revisarlas periódicamente.", "Evaluar sólo métricas técnicas como precisión del modelo.", "Usar sólo encuestas de satisfacción interna."]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', now(), 'Definir métricas financieras claras como ahorros, ingresos incrementales y reducción de riesgo, y revisarlas periódicamente.', '["Inversión", "Conocimiento"]'::jsonb, 2, 4),

('DF-C25', 'Cuestionario', 'Conocimiento', '5', '13', 'En una organización con IA a escala, ¿qué rol clave debe jugar el CFO?', 'Multiple Choice (una respuesta)', '["Limitarse a aprobar presupuestos sin cuestionar casos de negocio.", "Codiseñar la estrategia de IA, vinculando iniciativas con creación de valor y gestión integral de riesgos.", "Delegar todos los temas de IA al CAIO o CTO.", "Centrarse sólo en contabilidad financiera."]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', now(), 'Codiseñar la estrategia de IA, vinculando iniciativas con creación de valor y gestión integral de riesgos.', '["Conocimiento"]'::jsonb, 2, 5),

('DF-C26', 'Cuestionario', 'Conocimiento', '5', '13', '¿Qué caracteriza a un marco avanzado de IA explicable relevante para el CFO?', 'Multiple Choice (una respuesta)', '["No se documenta nada mientras el modelo sea preciso.", "Provee explicaciones adaptadas a audiencias como regulador, auditor y Consejo, y soporta decisiones de alto impacto.", "Sólo muestra fórmulas matemáticas complejas.", "Lo define en solitario el proveedor tecnológico."]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', now(), 'Provee explicaciones adaptadas a audiencias como regulador, auditor y Consejo, y soporta decisiones de alto impacto.', '["Conocimiento"]'::jsonb, 2, 5),

('DF-C27', 'Cuestionario', 'Conocimiento', '5', '13', '¿Cómo puede la IA apoyar decisiones de asignación de capital a nivel corporativo?', 'Multiple Choice (una respuesta)', '["Prohibiendo el análisis de escenarios.", "Integrando simulaciones y modelos predictivos de retorno y riesgo bajo distintos escenarios.", "Reemplazando completamente el juicio de la Alta Dirección.", "Fijando un único escenario óptimo inamovible."]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', now(), 'Integrando simulaciones y modelos predictivos de retorno y riesgo bajo distintos escenarios.', '["Conocimiento"]'::jsonb, 2, 5),

('DF-C28', 'Cuestionario', 'Conocimiento', '5', '13', 'Respecto a sistemas de IA autónomos en tesorería, el CFO debería:', 'Multiple Choice (una respuesta)', '["Permitir acciones autónomas sin límites ni supervisión.", "Definir límites, controles, monitoreo y escenarios en los que se requiere aprobación humana.", "Prohibir cualquier automatización.", "Ceder el control por completo al proveedor."]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', now(), 'Definir límites, controles, monitoreo y escenarios en los que se requiere aprobación humana.', '["Conocimiento"]'::jsonb, 2, 5),

('DF-C29', 'Cuestionario', 'Conocimiento', '5', '13', '¿Qué elemento es central para sostener IA a escala en finanzas?', 'Multiple Choice (una respuesta)', '["Múltiples fuentes de datos desconectadas.", "Una arquitectura de datos gobernada, con calidad, linaje y seguridad, integrada con sistemas de IA.", "Cada área manejando sus propios datos sin estándares.", "No invertir en infraestructura de datos."]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', now(), 'Una arquitectura de datos gobernada, con calidad, linaje y seguridad, integrada con sistemas de IA.', '["Conocimiento"]'::jsonb, 2, 5),

('DF-C30', 'Cuestionario', 'Conocimiento', '5', '13', '¿Cómo debería relacionarse el CFO con el resto de C-level respecto a IA?', 'Multiple Choice (una respuesta)', '["Actuar de manera aislada para proteger la función financiera.", "Coliderar el roadmap de IA con CEO, CTO, CAIO y negocio, alineando valor, riesgo y regulación.", "Sólo asistir a reuniones cuando se le solicite presupuesto.", "Limitarse a temas estrictamente contables."]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', now(), 'Coliderar el roadmap de IA con CEO, CTO, CAIO y negocio, alineando valor, riesgo y regulación.', '["Conocimiento"]'::jsonb, 2, 5);
