-- ============================================================================
-- PREGUNTAS PARA MIEMBROS DE COMPRAS
-- ============================================================================
-- Rol incluido:
--   - Rol ID 23: Miembros de Compras (area_id: 8, nivel_id: 4)
-- ============================================================================

-- ============================================================================
-- ROL 23: Miembros de Compras
-- ============================================================================

-- ADOPCIÓN - Rol 23
INSERT INTO "public"."preguntas" ("codigo", "section", "bloque", "area_id", "exclusivo_rol_id", "texto", "tipo", "opciones", "locale", "peso", "escala", "scoring", "created_at", "respuesta_correcta", "dimension", "exclusivo_nivel_id", "dificultad") VALUES
('MCP-A1', 'Cuestionario', 'Adopción', '8', '23', 'Uso alguna herramienta de IA (por ejemplo, un chatbot) para redactar o revisar al menos un correo a proveedores al mes.', 'Multiple Choice (escala Likert A–E)', '["Nunca", "Rara vez (≤ 1/mes)", "Ocasional (2–3/mes)", "Frecuente (semanal)", "Muy frecuente (diaria)"]', 'MX/LATAM', '8.333333', null, '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', now(), null, '["Aplicación"]'::jsonb, 4, 1),

('MCP-A2', 'Cuestionario', 'Adopción', '8', '23', 'Cuando tengo que hacer una explicación de requerimientos, considero usar IA para mejorar la redacción y claridad del texto.', 'Multiple Choice (escala Likert A–E)', '["Nunca", "Rara vez (≤ 1/mes)", "Ocasional (2–3/mes)", "Frecuente (semanal)", "Muy frecuente (diaria)"]', 'MX/LATAM', '8.333333', null, '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', now(), null, '["Aplicación"]'::jsonb, 4, 1),

('MCP-A3', 'Cuestionario', 'Adopción', '8', '23', 'Me siento con curiosidad y apertura para experimentar con IA en tareas sencillas de Compras.', 'Multiple Choice (escala Likert A–E)', '["Nunca", "Rara vez (≤ 1/mes)", "Ocasional (2–3/mes)", "Frecuente (semanal)", "Muy frecuente (diaria)"]', 'MX/LATAM', '8.333333', null, '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', now(), null, '["Aplicación"]'::jsonb, 4, 1),

('MCP-A4', 'Cuestionario', 'Adopción', '8', '23', 'He pedido apoyo a un compañero o líder para que me muestre cómo usar alguna herramienta de IA relacionada con Compras.', 'Multiple Choice (escala Likert A–E)', '["Nunca", "Rara vez (≤ 1/mes)", "Ocasional (2–3/mes)", "Frecuente (semanal)", "Muy frecuente (diaria)"]', 'MX/LATAM', '8.333333', null, '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', now(), null, '["Aplicación"]'::jsonb, 4, 1),

('MCP-A5', 'Cuestionario', 'Adopción', '8', '23', 'Antes de enviar un texto generado por IA a proveedores, reviso que cumpla con el tono y las políticas básicas de la empresa.', 'Multiple Choice (escala Likert A–E)', '["Nunca", "Rara vez (≤ 1/mes)", "Ocasional (2–3/mes)", "Frecuente (semanal)", "Muy frecuente (diaria)"]', 'MX/LATAM', '8.333333', null, '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', now(), null, '["Aplicación"]'::jsonb, 4, 1),

('MCP-A6', 'Cuestionario', 'Adopción', '8', '23', 'Estoy dispuesto(a) a dedicar al menos unos minutos a la semana a probar cómo la IA puede apoyarme en mis tareas de Compras.', 'Multiple Choice (escala Likert A–E)', '["Nunca", "Rara vez (≤ 1/mes)", "Ocasional (2–3/mes)", "Frecuente (semanal)", "Muy frecuente (diaria)"]', 'MX/LATAM', '8.333333', null, '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', now(), null, '["Aplicación"]'::jsonb, 4, 1),

('MCP-A7', 'Cuestionario', 'Adopción', '8', '23', 'Utilizo IA al menos una vez al mes para redactar o mejorar solicitudes de cotización a proveedores.', 'Multiple Choice (escala Likert A–E)', '["Nunca", "Rara vez (≤ 1/mes)", "Ocasional (2–3/mes)", "Frecuente (semanal)", "Muy frecuente (diaria)"]', 'MX/LATAM', '8.333333', null, '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', now(), null, '["Aplicación"]'::jsonb, 4, 2),

('MCP-A8', 'Cuestionario', 'Adopción', '8', '23', 'Ajusto y personalizo los prompts que uso en IA para que se adapten a categorías específicas de compras (por ejemplo, servicios vs. materiales).', 'Multiple Choice (escala Likert A–E)', '["Nunca", "Rara vez (≤ 1/mes)", "Ocasional (2–3/mes)", "Frecuente (semanal)", "Muy frecuente (diaria)"]', 'MX/LATAM', '8.333333', null, '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', now(), null, '["Aplicación"]'::jsonb, 4, 2),

('MCP-A9', 'Cuestionario', 'Adopción', '8', '23', 'Cuando uso IA para preparar comparativos simples, siempre reviso que los datos estén completos y correctos.', 'Multiple Choice (escala Likert A–E)', '["Nunca", "Rara vez (≤ 1/mes)", "Ocasional (2–3/mes)", "Frecuente (semanal)", "Muy frecuente (diaria)"]', 'MX/LATAM', '8.333333', null, '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', now(), null, '["Aplicación"]'::jsonb, 4, 2),

('MCP-A10', 'Cuestionario', 'Adopción', '8', '23', 'Comparto con mis compañeros ejemplos de prompts o textos que me han funcionado bien en IA para Compras.', 'Multiple Choice (escala Likert A–E)', '["Nunca", "Rara vez (≤ 1/mes)", "Ocasional (2–3/mes)", "Frecuente (semanal)", "Muy frecuente (diaria)"]', 'MX/LATAM', '8.333333', null, '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', now(), null, '["Aplicación"]'::jsonb, 4, 2),

('MCP-A11', 'Cuestionario', 'Adopción', '8', '23', 'He utilizado IA para generar al menos una versión de resumen de cotizaciones para presentarlo a mi jefe o a otra área.', 'Multiple Choice (escala Likert A–E)', '["Nunca", "Rara vez (≤ 1/mes)", "Ocasional (2–3/mes)", "Frecuente (semanal)", "Muy frecuente (diaria)"]', 'MX/LATAM', '8.333333', null, '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', now(), null, '["Aplicación"]'::jsonb, 4, 2),

('MCP-A12', 'Cuestionario', 'Adopción', '8', '23', 'Dedico parte de mi tiempo de trabajo (aunque sea poco) a aprender nuevas formas de usar IA en tareas de Compras.', 'Multiple Choice (escala Likert A–E)', '["Nunca", "Rara vez (≤ 1/mes)", "Ocasional (2–3/mes)", "Frecuente (semanal)", "Muy frecuente (diaria)"]', 'MX/LATAM', '8.333333', null, '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', now(), null, '["Productividad"]'::jsonb, 4, 2),

('MCP-A13', 'Cuestionario', 'Adopción', '8', '23', 'Uso IA de forma regular (al menos semanal) para resumir y comparar cotizaciones de varios proveedores.', 'Multiple Choice (escala Likert A–E)', '["Nunca", "Rara vez (≤ 1/mes)", "Ocasional (2–3/mes)", "Frecuente (semanal)", "Muy frecuente (diaria)"]', 'MX/LATAM', '8.333333', null, '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', now(), null, '["Aplicación"]'::jsonb, 4, 3),

('MCP-A14', 'Cuestionario', 'Adopción', '8', '23', 'Defino criterios claros (precio, plazo, calidad, etc.) cuando pido a la IA que me ayude a analizar propuestas de proveedores.', 'Multiple Choice (escala Likert A–E)', '["Nunca", "Rara vez (≤ 1/mes)", "Ocasional (2–3/mes)", "Frecuente (semanal)", "Muy frecuente (diaria)"]', 'MX/LATAM', '8.333333', null, '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', now(), null, '["Aplicación"]'::jsonb, 4, 3),

('MCP-A15', 'Cuestionario', 'Adopción', '8', '23', 'Ajusto los resultados generados por IA antes de compartirlos con mi jefe u otras áreas (formato, lenguaje, conclusiones).', 'Multiple Choice (escala Likert A–E)', '["Nunca", "Rara vez (≤ 1/mes)", "Ocasional (2–3/mes)", "Frecuente (semanal)", "Muy frecuente (diaria)"]', 'MX/LATAM', '8.333333', null, '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', now(), null, '["Productividad"]'::jsonb, 4, 3),

('MCP-A16', 'Cuestionario', 'Adopción', '8', '23', 'Trabajo con compañeros de Compras para construir o mejorar juntos prompts y plantillas de IA reutilizables.', 'Multiple Choice (escala Likert A–E)', '["Nunca", "Rara vez (≤ 1/mes)", "Ocasional (2–3/mes)", "Frecuente (semanal)", "Muy frecuente (diaria)"]', 'MX/LATAM', '8.333333', null, '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', now(), null, '["Aplicación"]'::jsonb, 4, 3),

('MCP-A17', 'Cuestionario', 'Adopción', '8', '23', 'Me preocupo por evitar compartir información sensible de proveedores o precios en herramientas de IA no autorizadas por la empresa.', 'Multiple Choice (escala Likert A–E)', '["Nunca", "Rara vez (≤ 1/mes)", "Ocasional (2–3/mes)", "Frecuente (semanal)", "Muy frecuente (diaria)"]', 'MX/LATAM', '8.333333', null, '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', now(), null, '["Aplicación"]'::jsonb, 4, 3),

('MCP-A18', 'Cuestionario', 'Adopción', '8', '23', 'Reviso si el uso de IA en ciertas tareas me permite liberar tiempo para actividades de mayor valor (por ejemplo, negociación, relación con proveedores).', 'Multiple Choice (escala Likert A–E)', '["Nunca", "Rara vez (≤ 1/mes)", "Ocasional (2–3/mes)", "Frecuente (semanal)", "Muy frecuente (diaria)"]', 'MX/LATAM', '8.333333', null, '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', now(), null, '["Aplicación", "Productividad"]'::jsonb, 4, 3),

('MCP-A19', 'Cuestionario', 'Adopción', '8', '23', 'Uso IA de forma constante para preparar comparativos que incluyan precio, tiempos de entrega y criterios de servicio.', 'Multiple Choice (escala Likert A–E)', '["Nunca", "Rara vez (≤ 1/mes)", "Ocasional (2–3/mes)", "Frecuente (semanal)", "Muy frecuente (diaria)"]', 'MX/LATAM', '8.333333', null, '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', now(), null, '["Aplicación", "Productividad"]'::jsonb, 4, 4),

('MCP-A20', 'Cuestionario', 'Adopción', '8', '23', 'Apoyo a compañeros de Compras a diseñar prompts y plantillas de IA que ellos puedan reutilizar.', 'Multiple Choice (escala Likert A–E)', '["Nunca", "Rara vez (≤ 1/mes)", "Ocasional (2–3/mes)", "Frecuente (semanal)", "Muy frecuente (diaria)"]', 'MX/LATAM', '8.333333', null, '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', now(), null, '["Aplicación"]'::jsonb, 4, 4),

('MCP-A21', 'Cuestionario', 'Adopción', '8', '23', 'Evalúo activamente el impacto de la IA en tiempos de ciclo (desde solicitud hasta orden de compra) para identificar mejoras.', 'Multiple Choice (escala Likert A–E)', '["Nunca", "Rara vez (≤ 1/mes)", "Ocasional (2–3/mes)", "Frecuente (semanal)", "Muy frecuente (diaria)"]', 'MX/LATAM', '8.333333', null, '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', now(), null, '["Productividad"]'::jsonb, 4, 4),

('MCP-A22', 'Cuestionario', 'Adopción', '8', '23', 'Uso IA para explorar riesgos potenciales de proveedores (por ejemplo, revisando noticias o información pública) antes de recomendaciones.', 'Multiple Choice (escala Likert A–E)', '["Nunca", "Rara vez (≤ 1/mes)", "Ocasional (2–3/mes)", "Frecuente (semanal)", "Muy frecuente (diaria)"]', 'MX/LATAM', '8.333333', null, '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', now(), null, '["Aplicación", "Estrategia"]'::jsonb, 4, 4),

('MCP-A23', 'Cuestionario', 'Adopción', '8', '23', 'Participo en discusiones con mi jefe u otras áreas para definir en qué tareas de Compras tiene sentido invertir más en IA.', 'Multiple Choice (escala Likert A–E)', '["Nunca", "Rara vez (≤ 1/mes)", "Ocasional (2–3/mes)", "Frecuente (semanal)", "Muy frecuente (diaria)"]', 'MX/LATAM', '8.333333', null, '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', now(), null, '["Aplicación"]'::jsonb, 4, 4),

('MCP-A24', 'Cuestionario', 'Adopción', '8', '23', 'Documentamos en el equipo cómo se usan las herramientas de IA para que otros puedan entender y auditar el proceso.', 'Multiple Choice (escala Likert A–E)', '["Nunca", "Rara vez (≤ 1/mes)", "Ocasional (2–3/mes)", "Frecuente (semanal)", "Muy frecuente (diaria)"]', 'MX/LATAM', '8.333333', null, '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', now(), null, '["Aplicación"]'::jsonb, 4, 4),

('MCP-A25', 'Cuestionario', 'Adopción', '8', '23', 'Lidero o impulso iniciativas para estandarizar el uso de IA en el equipo de Compras (plantillas, guías, mejores prácticas).', 'Multiple Choice (escala Likert A–E)', '["Nunca", "Rara vez (≤ 1/mes)", "Ocasional (2–3/mes)", "Frecuente (semanal)", "Muy frecuente (diaria)"]', 'MX/LATAM', '8.333333', null, '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', now(), null, '["Aplicación", "Estrategia"]'::jsonb, 4, 5),

('MCP-A26', 'Cuestionario', 'Adopción', '8', '23', 'Trabajo con otras áreas (TI, Legal, Finanzas) para asegurar que el uso de IA en Compras cumpla con políticas y regulaciones.', 'Multiple Choice (escala Likert A–E)', '["Nunca", "Rara vez (≤ 1/mes)", "Ocasional (2–3/mes)", "Frecuente (semanal)", "Muy frecuente (diaria)"]', 'MX/LATAM', '8.333333', null, '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', now(), null, '["Aplicación"]'::jsonb, 4, 5),

('MCP-A27', 'Cuestionario', 'Adopción', '8', '23', 'Analizo y comunico al equipo indicadores que muestran el impacto de IA en ahorro, tiempos de ciclo o calidad de las decisiones de Compras.', 'Multiple Choice (escala Likert A–E)', '["Nunca", "Rara vez (≤ 1/mes)", "Ocasional (2–3/mes)", "Frecuente (semanal)", "Muy frecuente (diaria)"]', 'MX/LATAM', '8.333333', null, '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', now(), null, '["Aplicación", "Productividad"]'::jsonb, 4, 5),

('MCP-A28', 'Cuestionario', 'Adopción', '8', '23', 'Diseño o adapto flujos de trabajo donde IA está integrada de forma clara (por ejemplo, generación de comparativos, análisis de gasto, alertas de riesgo).', 'Multiple Choice (escala Likert A–E)', '["Nunca", "Rara vez (≤ 1/mes)", "Ocasional (2–3/mes)", "Frecuente (semanal)", "Muy frecuente (diaria)"]', 'MX/LATAM', '8.333333', null, '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', now(), null, '["Estrategia"]'::jsonb, 4, 5),

('MCP-A29', 'Cuestionario', 'Adopción', '8', '23', 'Acompaño a otros miembros de Compras en el uso responsable de IA, incluyendo buenas prácticas para proteger datos sensibles de proveedores.', 'Multiple Choice (escala Likert A–E)', '["Nunca", "Rara vez (≤ 1/mes)", "Ocasional (2–3/mes)", "Frecuente (semanal)", "Muy frecuente (diaria)"]', 'MX/LATAM', '8.333333', null, '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', now(), null, '["Aplicación"]'::jsonb, 4, 5),

('MCP-A30', 'Cuestionario', 'Adopción', '8', '23', 'Participo en decisiones sobre en qué herramientas o capacidades de IA tiene sentido invertir para el área de Compras.', 'Multiple Choice (escala Likert A–E)', '["Nunca", "Rara vez (≤ 1/mes)", "Ocasional (2–3/mes)", "Frecuente (semanal)", "Muy frecuente (diaria)"]', 'MX/LATAM', '8.333333', null, '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', now(), null, '["Aplicación"]'::jsonb, 4, 5);

-- CONOCIMIENTO - Rol 23
INSERT INTO "public"."preguntas" ("codigo", "section", "bloque", "area_id", "exclusivo_rol_id", "texto", "tipo", "opciones", "locale", "peso", "escala", "scoring", "created_at", "respuesta_correcta", "dimension", "exclusivo_nivel_id", "dificultad") VALUES
('MCP-C1', 'Cuestionario', 'Conocimiento', '8', '23', '¿Cuál de las siguientes opciones describe mejor qué es la inteligencia artificial (IA) aplicada a Compras?', 'Multiple Choice (una respuesta)', '["Un sistema que solo almacena órdenes de compra.", "Herramientas que imitan capacidades humanas (como analizar, resumir o predecir) para apoyar tareas de compras.", "Un software que únicamente envía correos automáticos a proveedores.", "Una base de datos estática con precios históricos."]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', now(), null, '["Conocimiento", "Aplicación"]'::jsonb, 4, 1),

('MCP-C2', 'Cuestionario', 'Conocimiento', '8', '23', '¿Cuál es un ejemplo simple de uso de IA en el trabajo de Compras?', 'Multiple Choice (una respuesta)', '["Escanear físicamente facturas con una impresora.", "Usar un chatbot para redactar un correo inicial de solicitud de cotización a varios proveedores.", "Imprimir todas las cotizaciones para revisarlas a mano.", "Guardar órdenes de compra en una carpeta compartida."]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', now(), 'Usar un chatbot para redactar un correo inicial de solicitud de cotización a varios proveedores.', '["Conocimiento", "Aplicación"]'::jsonb, 4, 1),

('MCP-C3', 'Cuestionario', 'Conocimiento', '8', '23', '¿Qué ventaja puede aportar la IA al comparar cotizaciones de varios proveedores?', 'Multiple Choice (una respuesta)', '["Asegura que siempre elija al proveedor más caro.", "Puede ayudar a ordenar y resumir información de precios y condiciones más rápido.", "Elimina la necesidad de revisar las condiciones antes de firmar.", "Reemplaza totalmente al área de Compras."]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', now(), 'Puede ayudar a ordenar y resumir información de precios y condiciones más rápido.', '["Conocimiento"]'::jsonb, 4, 1),

('MCP-C4', 'Cuestionario', 'Conocimiento', '8', '23', '¿Qué riesgo básico existe al copiar y pegar texto generado por IA en una comunicación con proveedores?', 'Multiple Choice (una respuesta)', '["Ninguno, la IA siempre es 100% correcta.", "Puede incluir errores o términos que no se ajustan a las políticas de la empresa.", "Los correos no se entregan nunca.", "El proveedor está obligado legalmente a aceptar lo que diga el texto."]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', now(), 'Puede incluir errores o términos que no se ajustan a las políticas de la empresa.', '["Conocimiento", "Estrategia"]'::jsonb, 4, 1),

('MCP-C5', 'Cuestionario', 'Conocimiento', '8', '23', '¿Cuál de estas tareas es más adecuada para comenzar a usar IA en Compras?', 'Multiple Choice (una respuesta)', '["Aprobar pagos sin revisar las facturas.", "Pedir a la IA que revise términos legales complejos sin abogado.", "Apoyarse en IA para mejorar la redacción y claridad de solicitudes de cotización.", "Compartir información confidencial de proveedores en cualquier chat público."]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', now(), 'Apoyarse en IA para mejorar la redacción y claridad de solicitudes de cotización.', '["Conocimiento"]'::jsonb, 4, 1),

('MCP-C6', 'Cuestionario', 'Conocimiento', '8', '23', '¿Qué dato NO deberías compartir con una herramienta de IA abierta sin revisar las políticas de la empresa?', 'Multiple Choice (una respuesta)', '["Un ejemplo genérico de correo.", "El listado completo de precios negociados con un proveedor clave.", "Una descripción general de una categoría de compra (ej. papelería).", "Un ejemplo ficticio de orden de compra."]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', now(), 'El listado completo de precios negociados con un proveedor clave.', '["Conocimiento"]'::jsonb, 4, 1),

('MCP-C7', 'Cuestionario', 'Conocimiento', '8', '23', '¿Qué es un “prompt” en el contexto de uso de IA generativa en Compras?', 'Multiple Choice (una respuesta)', '["El sistema de aprobación de órdenes de compra.", "El texto o instrucción que damos a la IA para que genere una respuesta.", "El contrato firmado con un proveedor.", "El código interno de un material."]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', now(), 'El texto o instrucción que damos a la IA para que genere una respuesta.', '["Conocimiento", "Aplicación"]'::jsonb, 4, 2),

('MCP-C8', 'Cuestionario', 'Conocimiento', '8', '23', '¿Cuál de estas prácticas mejora la calidad de las respuestas de IA al preparar una solicitud de cotización?', 'Multiple Choice (una respuesta)', '["Escribir “hazme una cotización” sin más contexto.", "Incluir detalles de cantidades, tiempos de entrega y criterios de evaluación.", "Evitar mencionar el objetivo de la compra.", "Pedir que la cotización sea lo más genérica posible."]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', now(), 'Incluir detalles de cantidades, tiempos de entrega y criterios de evaluación.', '["Conocimiento"]'::jsonb, 4, 2),

('MCP-C9', 'Cuestionario', 'Conocimiento', '8', '23', '¿Qué tipo de información es adecuado compartir con la IA al preparar comparativos?', 'Multiple Choice (una respuesta)', '["Datos personales sensibles de proveedores sin anonimizar.", "Precios y condiciones, usando datos ficticios o anonimizados según políticas.", "Contraseñas del ERP.", "Números de cuenta bancaria completos de proveedores."]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', now(), 'Precios y condiciones, usando datos ficticios o anonimizados según políticas.', '["Conocimiento", "Aplicación"]'::jsonb, 4, 2),

('MCP-C10', 'Cuestionario', 'Conocimiento', '8', '23', '¿Cómo puede la IA apoyar la productividad diaria de un miembro de Compras?', 'Multiple Choice (una respuesta)', '["Eliminando la necesidad de documentar procesos.", "Generando borradores de comparativos, resúmenes de cotizaciones y correos estándar.", "Decidiendo sola qué proveedor elegir.", "Reemplazando las aprobaciones del jefe."]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', now(), 'Generando borradores de comparativos, resúmenes de cotizaciones y correos estándar.', '["Conocimiento", "Productividad"]'::jsonb, 4, 2),

('MCP-C11', 'Cuestionario', 'Conocimiento', '8', '23', '¿Cuál es una señal de que la IA generó una respuesta potencialmente sesgada al evaluar proveedores?', 'Multiple Choice (una respuesta)', '["Siempre propone revisar todas las ofertas.", "Favorece repetidamente a un proveedor sin fundamento objetivo.", "Presenta una tabla con todos los proveedores.", "Muestra los datos de todos los proveedores por igual."]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', now(), 'Favorece repetidamente a un proveedor sin fundamento objetivo.', '["Conocimiento"]'::jsonb, 4, 2),

('MCP-C12', 'Cuestionario', 'Conocimiento', '8', '23', '¿Qué representa mejor una “buena inversión” de tiempo en IA para Compras?', 'Multiple Choice (una respuesta)', '["Usar IA solo para tareas personales.", "Dedicar algo de tiempo a crear plantillas reutilizables para RFQ y comparativos.", "Probar una herramienta distinta cada día sin aplicar nada al proceso.", "Evitar contarle al equipo para que nadie más la use."]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', now(), 'Dedicar algo de tiempo a crear plantillas reutilizables para RFQ y comparativos.', '["Conocimiento", "Inversión", "Productividad"]'::jsonb, 4, 2),

('MCP-C13', 'Cuestionario', 'Conocimiento', '8', '23', '¿Cómo puede ayudar la IA integrada en una plataforma de e-procurement?', 'Multiple Choice (una respuesta)', '["Bloqueando todas las órdenes de compra.", "Sugiriendo proveedores, clasificando gastos y detectando incongruencias en órdenes y facturas.", "Eliminando la necesidad de controles de aprobación.", "Evitando que se hagan nuevos pedidos."]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', now(), 'Sugiriendo proveedores, clasificando gastos y detectando incongruencias en órdenes y facturas.', '["Conocimiento"]'::jsonb, 4, 3),

('MCP-C14', 'Cuestionario', 'Conocimiento', '8', '23', '¿Qué buena práctica es clave al usar IA para analizar comparativos complejos de proveedores?', 'Multiple Choice (una respuesta)', '["No revisar la información fuente si el resumen “suena bien”.", "Definir criterios claros (precio, plazo, calidad, servicio) y comunicarlos a la IA.", "Pedir solo que muestre el proveedor más barato.", "Dejar que la IA decida sin entender los criterios."]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', now(), 'Definir criterios claros (precio, plazo, calidad, servicio) y comunicarlos a la IA.', '["Conocimiento"]'::jsonb, 4, 3),

('MCP-C15', 'Cuestionario', 'Conocimiento', '8', '23', '¿Cuál es un uso adecuado de IA para pronosticar demanda o consumo en Compras a nivel operativo?', 'Multiple Choice (una respuesta)', '["Pedirle que invente números sin datos históricos.", "Usar datos históricos de consumo y pedir a la IA patrones o tendencias, verificando resultados.", "Sustituir al área de Planificación sin validación.", "Ignorar los datos y basarse solo en la intuición."]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', now(), 'Usar datos históricos de consumo y pedir a la IA patrones o tendencias, verificando resultados.', '["Conocimiento", "Aplicación"]'::jsonb, 4, 3),

('MCP-C16', 'Cuestionario', 'Conocimiento', '8', '23', '¿Qué riesgo existe al depender demasiado de IA para evaluar el desempeño de proveedores?', 'Multiple Choice (una respuesta)', '["Ninguno, la IA es neutral por definición.", "Se pueden reforzar sesgos si los datos o criterios están mal definidos.", "Los proveedores desaparecen del sistema.", "Los contratos se vuelven inválidos."]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', now(), 'Se pueden reforzar sesgos si los datos o criterios están mal definidos.', '["Conocimiento", "Estrategia"]'::jsonb, 4, 3),

('MCP-C17', 'Cuestionario', 'Conocimiento', '8', '23', '¿Qué describe mejor el impacto de IA en la productividad de un miembro de Compras?', 'Multiple Choice (una respuesta)', '["Hacer que el trabajo sea más lento.", "Reducir tiempo en tareas repetitivas (redacción, formateo, primeros análisis), liberando tiempo para análisis de valor.", "Eliminar la necesidad de capacitación.", "Aumentar el número de errores siempre."]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', now(), 'Reducir tiempo en tareas repetitivas (redacción, formateo, primeros análisis), liberando tiempo para análisis de valor.', '["Conocimiento", "Productividad"]'::jsonb, 4, 3),

('MCP-C18', 'Cuestionario', 'Conocimiento', '8', '23', 'En términos de inversión en IA, ¿qué es más eficiente para el área de Compras al usar IA?', 'Multiple Choice (una respuesta)', '["Que cada persona invente sus propios prompts sin compartirlos.", "Crear bibliotecas de prompts y plantillas comunes para el equipo.", "Prohibir totalmente el uso de IA.", "Cambiar de herramienta cada semana."]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', now(), 'Crear bibliotecas de prompts y plantillas comunes para el equipo.', '["Conocimiento", "Inversión"]'::jsonb, 4, 3),

('MCP-C19', 'Cuestionario', 'Conocimiento', '8', '23', '¿Cómo puede la IA apoyar un análisis de gasto (spend analysis) en Compras?', 'Multiple Choice (una respuesta)', '["Borrando registros históricos.", "Clasificando transacciones, identificando patrones de gasto y posibles oportunidades de ahorro.", "Cerrando el acceso al ERP.", "Eliminando facturas duplicadas sin revisión."]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', now(), 'Clasificando transacciones, identificando patrones de gasto y posibles oportunidades de ahorro.', '["Conocimiento"]'::jsonb, 4, 4),

('MCP-C20', 'Cuestionario', 'Conocimiento', '8', '23', '¿Qué papel puede tener la IA en la gestión de riesgo de proveedores?', 'Multiple Choice (una respuesta)', '["Ignorar noticias negativas sobre proveedores.", "Analizar información pública y datos internos para ayudar a identificar riesgos financieros, de cumplimiento o reputacionales.", "Decidir automáticamente romper contratos.", "Ocultar problemas a la empresa."]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', now(), 'Analizar información pública y datos internos para ayudar a identificar riesgos financieros, de cumplimiento o reputacionales.', '["Conocimiento", "Estrategia"]'::jsonb, 4, 4),

('MCP-C21', 'Cuestionario', 'Conocimiento', '8', '23', '¿Qué es importante al usar IA para sugerir consolidación de proveedores en una categoría?', 'Multiple Choice (una respuesta)', '["Considerar solo el precio unitario.", "Incluir criterios de servicio, calidad, riesgo y dependencia excesiva de un único proveedor.", "Eliminar todos los proveedores locales.", "Elegir al proveedor con mejor logo."]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', now(), 'Incluir criterios de servicio, calidad, riesgo y dependencia excesiva de un único proveedor.', '["Conocimiento"]'::jsonb, 4, 4),

('MCP-C22', 'Cuestionario', 'Conocimiento', '8', '23', '¿Qué describe mejor una buena práctica ética al usar IA para evaluar propuestas económicas?', 'Multiple Choice (una respuesta)', '["Ocultar ciertos datos a la IA para sesgar los resultados.", "Asegurar que los criterios usados por IA sean transparentes y revisables por el equipo.", "Pedir que la IA favorezca a un proveedor “preferido”.", "No documentar cómo se llegó a la decisión."]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', now(), 'Asegurar que los criterios usados por IA sean transparentes y revisables por el equipo.', '["Conocimiento", "Estrategia"]'::jsonb, 4, 4),

('MCP-C23', 'Cuestionario', 'Conocimiento', '8', '23', 'Desde el punto de vista de productividad, ¿qué combina mejor IA y procesos de Compras?', 'Multiple Choice (una respuesta)', '["Automatizar pasos sin definir responsables.", "Diseñar flujos donde IA realiza tareas repetitivas y el comprador se enfoca en análisis y negociación.", "Usar IA solo para tareas personales.", "Evitar toda automatización."]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', now(), 'Diseñar flujos donde IA realiza tareas repetitivas y el comprador se enfoca en análisis y negociación.', '["Conocimiento", "Productividad"]'::jsonb, 4, 4),

('MCP-C24', 'Cuestionario', 'Conocimiento', '8', '23', 'En términos de inversión en IA, ¿qué puede hacer un miembro de Compras a nivel colaborador?', 'Multiple Choice (una respuesta)', '["Guardar para sí todas las buenas prácticas de IA.", "Proponer al área la adopción de plantillas y entrenamientos básicos para el equipo.", "Comprar herramientas por su cuenta sin avisar.", "Evitar mencionar IA en reuniones."]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', now(), 'Proponer al área la adopción de plantillas y entrenamientos básicos para el equipo.', '["Conocimiento", "Inversión"]'::jsonb, 4, 4),

('MCP-C25', 'Cuestionario', 'Conocimiento', '8', '23', '¿Cuál es una función avanzada de IA que puede apoyar la negociación con proveedores?', 'Multiple Choice (una respuesta)', '["Generar automáticamente firmas en los contratos.", "Simular escenarios de volumen, precio y condiciones para evaluar diferentes estrategias de negociación.", "Enviar acuerdos sin revisar.", "Bloquear el acceso a historiales de compra."]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', now(), 'Simular escenarios de volumen, precio y condiciones para evaluar diferentes estrategias de negociación.', '["Conocimiento"]'::jsonb, 4, 5),

('MCP-C26', 'Cuestionario', 'Conocimiento', '8', '23', '¿Qué deberías considerar al proponer una nueva herramienta de IA para el área de Compras?', 'Multiple Choice (una respuesta)', '["Solo si es la más “moderna”.", "Seguridad de datos, integración con ERP/e-procurement y retorno esperado de la inversión.", "Que nadie más la conozca.", "Que funcione solo para una persona."]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', now(), 'Seguridad de datos, integración con ERP/e-procurement y retorno esperado de la inversión.', '["Conocimiento"]'::jsonb, 4, 5),

('MCP-C27', 'Cuestionario', 'Conocimiento', '8', '23', '¿Qué enfoque reduce el riesgo de sesgos al usar IA para filtrar proveedores?', 'Multiple Choice (una respuesta)', '["Permitir que IA decida sin revisar criterios.", "Definir criterios objetivos, revisar los prompts y validar muestras de resultados de manera periódica.", "Eliminar del sistema a proveedores según preferencia personal.", "Evitar documentar cómo se decide."]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', now(), 'Definir criterios objetivos, revisar los prompts y validar muestras de resultados de manera periódica.', '["Conocimiento", "Estrategia"]'::jsonb, 4, 5),

('MCP-C28', 'Cuestionario', 'Conocimiento', '8', '23', '¿Cuál es un rol clave de un referente en IA dentro del equipo de Compras?', 'Multiple Choice (una respuesta)', '["Ser el único que usa IA.", "Capacitar, documentar buenas prácticas y ayudar a traducir necesidades del equipo en casos de uso de IA.", "Ocultar información para mantener ventaja personal.", "Elegir proveedores sin consultar."]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', now(), 'Capacitar, documentar buenas prácticas y ayudar a traducir necesidades del equipo en casos de uso de IA.', '["Conocimiento", "Aplicación"]'::jsonb, 4, 5),

('MCP-C29', 'Cuestionario', 'Conocimiento', '8', '23', '¿Qué muestra una buena madurez de IA en procesos de Compras a nivel operativo?', 'Multiple Choice (una respuesta)', '["Procesos no documentados que dependen de una sola persona.", "Flujos definidos donde IA tiene un rol claro, medido y revisado periódicamente.", "Uso de IA solo de forma experimental y aislada.", "No involucrar al área de TI."]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', now(), 'Flujos definidos donde IA tiene un rol claro, medido y revisado periódicamente.', '["Conocimiento"]'::jsonb, 4, 5),

('MCP-C30', 'Cuestionario', 'Conocimiento', '8', '23', 'En términos de inversión, ¿qué indicador ayuda a demostrar el valor de IA en Compras?', 'Multiple Choice (una respuesta)', '["Número de herramientas probadas sin adopción real.", "Reducción de tiempo de ciclo, aumento de ahorro o mejora de cumplimiento asociada a IA.", "Cantidad de correos enviados por día.", "Número de errores no detectados."]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', now(), 'Reducción de tiempo de ciclo, aumento de ahorro o mejora de cumplimiento asociada a IA.', '["Conocimiento", "Inversión"]'::jsonb, 4, 5);
