-- ============================================================================
-- PREGUNTAS PARA FREELANCER
-- ============================================================================
-- Rol incluido:
--   - Rol ID 25: Freelancer (area_id: 1, nivel_id: 4)
-- ============================================================================

-- ============================================================================
-- ROL 25: Freelancer
-- ============================================================================

-- ADOPCIÓN - Rol 25
INSERT INTO "public"."preguntas" ("codigo", "section", "bloque", "area_id", "exclusivo_rol_id", "texto", "tipo", "opciones", "locale", "peso", "escala", "scoring", "created_at", "respuesta_correcta", "dimension", "exclusivo_nivel_id", "dificultad") VALUES
('FL-A1', 'Cuestionario', 'Adopción', '1', '25', 'Uso alguna herramienta de IA para generar ideas iniciales, como temas, títulos o enfoques, para mis servicios o contenidos.', 'Multiple Choice (escala Likert A–E)', '["Nunca", "Rara vez (≤ 1/mes)", "Ocasional (2–3/mes)", "Frecuente (semanal)", "Muy frecuente (diaria)"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', now(), null, '["Aplicación"]'::jsonb, 4, 1),

('FL-A2', 'Cuestionario', 'Adopción', '1', '25', 'Recurro a IA para ahorrar tiempo en tareas repetitivas, por ejemplo corrección de textos o resúmenes de información.', 'Multiple Choice (escala Likert A–E)', '["Nunca", "Rara vez (≤ 1/mes)", "Ocasional (2–3/mes)", "Frecuente (semanal)", "Muy frecuente (diaria)"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', now(), null, '["Productividad", "Aplicación"]'::jsonb, 4, 1),

('FL-A3', 'Cuestionario', 'Adopción', '1', '25', 'Antes de enviar algo a un cliente, reviso críticamente el contenido generado por IA para asegurar que refleje mi estilo y los requisitos del proyecto.', 'Multiple Choice (escala Likert A–E)', '["Nunca", "Rara vez (≤ 1/mes)", "Ocasional (2–3/mes)", "Frecuente (semanal)", "Muy frecuente (diaria)"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', now(), null, '["Aplicación"]'::jsonb, 4, 1),

('FL-A4', 'Cuestionario', 'Adopción', '1', '25', 'He dedicado tiempo, aunque sea mínimo, a aprender cómo funcionan las herramientas de IA que podría usar en mi trabajo freelance.', 'Multiple Choice (escala Likert A–E)', '["Nunca", "Rara vez (≤ 1/mes)", "Ocasional (2–3/mes)", "Frecuente (semanal)", "Muy frecuente (diaria)"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', now(), null, '["Productividad", "Aplicación"]'::jsonb, 4, 1),

('FL-A5', 'Cuestionario', 'Adopción', '1', '25', 'Cuando colaboro con otros freelancers o con clientes, explico clara y honestamente si y cómo uso IA en el proyecto.', 'Multiple Choice (escala Likert A–E)', '["Nunca", "Rara vez (≤ 1/mes)", "Ocasional (2–3/mes)", "Frecuente (semanal)", "Muy frecuente (diaria)"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', now(), null, '["Aplicación"]'::jsonb, 4, 1),

('FL-A6', 'Cuestionario', 'Adopción', '1', '25', 'He considerado destinar una pequeña parte de mis ingresos o tiempo mensual para probar nuevas herramientas de IA que puedan mejorar mi servicio.', 'Multiple Choice (escala Likert A–E)', '["Nunca", "Rara vez (≤ 1/mes)", "Ocasional (2–3/mes)", "Frecuente (semanal)", "Muy frecuente (diaria)"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', now(), null, '["Productividad", "Aplicación"]'::jsonb, 4, 1),

('FL-A7', 'Cuestionario', 'Adopción', '1', '25', 'Uso IA para generar borradores de propuestas comerciales que luego adapto antes de enviarlas a mis clientes.', 'Multiple Choice (escala Likert A–E)', '["Nunca", "Rara vez (≤ 1/mes)", "Ocasional (2–3/mes)", "Frecuente (semanal)", "Muy frecuente (diaria)"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', now(), null, '["Aplicación"]'::jsonb, 4, 2),

('FL-A8', 'Cuestionario', 'Adopción', '1', '25', 'Pido a la IA que me ayude a resumir información de artículos, documentos o briefs extensos proporcionados por mis clientes.', 'Multiple Choice (escala Likert A–E)', '["Nunca", "Rara vez (≤ 1/mes)", "Ocasional (2–3/mes)", "Frecuente (semanal)", "Muy frecuente (diaria)"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', now(), null, '["Aplicación"]'::jsonb, 4, 2),

('FL-A9', 'Cuestionario', 'Adopción', '1', '25', 'Reviso mis resultados, como tiempos de entrega y satisfacción del cliente, para evaluar si el uso de IA está realmente mejorando mi negocio freelance.', 'Multiple Choice (escala Likert A–E)', '["Nunca", "Rara vez (≤ 1/mes)", "Ocasional (2–3/mes)", "Frecuente (semanal)", "Muy frecuente (diaria)"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', now(), null, '["Productividad", "Aplicación"]'::jsonb, 4, 2),

('FL-A10', 'Cuestionario', 'Adopción', '1', '25', 'Al colaborar con otros freelancers, comparto prompts o formas de usar IA que han funcionado bien para mí.', 'Multiple Choice (escala Likert A–E)', '["Nunca", "Rara vez (≤ 1/mes)", "Ocasional (2–3/mes)", "Frecuente (semanal)", "Muy frecuente (diaria)"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', now(), null, '["Aplicación"]'::jsonb, 4, 2),

('FL-A11', 'Cuestionario', 'Adopción', '1', '25', 'He realizado alguna búsqueda específica, como artículos, cursos o videos, para aprender mejores prácticas de IA aplicada al freelancing.', 'Multiple Choice (escala Likert A–E)', '["Nunca", "Rara vez (≤ 1/mes)", "Ocasional (2–3/mes)", "Frecuente (semanal)", "Muy frecuente (diaria)"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', now(), null, '["Aplicación"]'::jsonb, 4, 2),

('FL-A12', 'Cuestionario', 'Adopción', '1', '25', 'Reservo parte de mi tiempo mensual para experimentar con nuevas formas de usar IA en diferentes áreas, como marketing, entrega del servicio y administración.', 'Multiple Choice (escala Likert A–E)', '["Nunca", "Rara vez (≤ 1/mes)", "Ocasional (2–3/mes)", "Frecuente (semanal)", "Muy frecuente (diaria)"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', now(), null, '["Productividad"]'::jsonb, 4, 2),

('FL-A13', 'Cuestionario', 'Adopción', '1', '25', 'Tengo definidos prompts tipo plantilla, reutilizables, para actividades clave de mi trabajo freelance, por ejemplo briefs, propuestas, guiones o publicaciones.', 'Multiple Choice (escala Likert A–E)', '["Nunca", "Rara vez (≤ 1/mes)", "Ocasional (2–3/mes)", "Frecuente (semanal)", "Muy frecuente (diaria)"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', now(), null, '["Aplicación"]'::jsonb, 4, 3),

('FL-A14', 'Cuestionario', 'Adopción', '1', '25', 'Uso IA para comparar varias opciones de propuesta o estrategia para un cliente y tomar decisiones mejor informadas.', 'Multiple Choice (escala Likert A–E)', '["Nunca", "Rara vez (≤ 1/mes)", "Ocasional (2–3/mes)", "Frecuente (semanal)", "Muy frecuente (diaria)"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', now(), null, '["Estrategia", "Aplicación"]'::jsonb, 4, 3),

('FL-A15', 'Cuestionario', 'Adopción', '1', '25', 'Integro IA en mi proceso de investigación, por ejemplo resúmenes de documentos y extracción de ideas, antes de desarrollar entregables.', 'Multiple Choice (escala Likert A–E)', '["Nunca", "Rara vez (≤ 1/mes)", "Ocasional (2–3/mes)", "Frecuente (semanal)", "Muy frecuente (diaria)"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', now(), null, '["Aplicación"]'::jsonb, 4, 3),

('FL-A16', 'Cuestionario', 'Adopción', '1', '25', 'Al colaborar con agencias o equipos, acordamos explícitamente qué partes del trabajo pueden ser asistidas por IA y cómo documentarlo.', 'Multiple Choice (escala Likert A–E)', '["Nunca", "Rara vez (≤ 1/mes)", "Ocasional (2–3/mes)", "Frecuente (semanal)", "Muy frecuente (diaria)"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', now(), null, '["Aplicación"]'::jsonb, 4, 3),

('FL-A17', 'Cuestionario', 'Adopción', '1', '25', 'Evalúo regularmente si el tiempo y dinero invertidos en herramientas de IA están generando mayores ingresos, mejores clientes o más tiempo libre.', 'Multiple Choice (escala Likert A–E)', '["Nunca", "Rara vez (≤ 1/mes)", "Ocasional (2–3/mes)", "Frecuente (semanal)", "Muy frecuente (diaria)"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', now(), null, '["Productividad", "Aplicación"]'::jsonb, 4, 3),

('FL-A18', 'Cuestionario', 'Adopción', '1', '25', 'Uso IA para crear variantes personalizadas, por ejemplo versiones de un mismo contenido adaptadas a diferentes audiencias o canales.', 'Multiple Choice (escala Likert A–E)', '["Nunca", "Rara vez (≤ 1/mes)", "Ocasional (2–3/mes)", "Frecuente (semanal)", "Muy frecuente (diaria)"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', now(), null, '["Aplicación"]'::jsonb, 4, 3),

('FL-A19', 'Cuestionario', 'Adopción', '1', '25', 'Tengo documentados workflows estándar donde la IA interviene en varias etapas de mis proyectos, como onboarding, análisis, propuesta, entregable y retroalimentación.', 'Multiple Choice (escala Likert A–E)', '["Nunca", "Rara vez (≤ 1/mes)", "Ocasional (2–3/mes)", "Frecuente (semanal)", "Muy frecuente (diaria)"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', now(), null, '["Aplicación"]'::jsonb, 4, 4),

('FL-A20', 'Cuestionario', 'Adopción', '1', '25', 'Uso IA para testear diferentes versiones de mensajes de venta, páginas de servicio o campañas, midiendo qué funciona mejor con mis clientes.', 'Multiple Choice (escala Likert A–E)', '["Nunca", "Rara vez (≤ 1/mes)", "Ocasional (2–3/mes)", "Frecuente (semanal)", "Muy frecuente (diaria)"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', now(), null, '["Aplicación"]'::jsonb, 4, 4),

('FL-A21', 'Cuestionario', 'Adopción', '1', '25', 'Integro IA en mi gestión financiera o de pricing, por ejemplo simulaciones de tarifas, escenarios de carga de trabajo y objetivos de ingresos.', 'Multiple Choice (escala Likert A–E)', '["Nunca", "Rara vez (≤ 1/mes)", "Ocasional (2–3/mes)", "Frecuente (semanal)", "Muy frecuente (diaria)"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', now(), null, '["Aplicación"]'::jsonb, 4, 4),

('FL-A22', 'Cuestionario', 'Adopción', '1', '25', 'Coordino con clientes y colaboradores para definir límites claros sobre el tipo de datos que pueden procesarse con IA, como datos sensibles o confidenciales.', 'Multiple Choice (escala Likert A–E)', '["Nunca", "Rara vez (≤ 1/mes)", "Ocasional (2–3/mes)", "Frecuente (semanal)", "Muy frecuente (diaria)"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', now(), null, '["Estrategia", "Aplicación"]'::jsonb, 4, 4),

('FL-A23', 'Cuestionario', 'Adopción', '1', '25', 'Uso IA para construir activos reutilizables, como plantillas extensas, guías y sistemas de prompts, que me permiten entregar más rápido y escalar.', 'Multiple Choice (escala Likert A–E)', '["Nunca", "Rara vez (≤ 1/mes)", "Ocasional (2–3/mes)", "Frecuente (semanal)", "Muy frecuente (diaria)"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', now(), null, '["Aplicación"]'::jsonb, 4, 4),

('FL-A24', 'Cuestionario', 'Adopción', '1', '25', 'Evalúo periódicamente mi portafolio de herramientas de IA para eliminar las que no aportan valor y reinvertir en las que sí lo hacen.', 'Multiple Choice (escala Likert A–E)', '["Nunca", "Rara vez (≤ 1/mes)", "Ocasional (2–3/mes)", "Frecuente (semanal)", "Muy frecuente (diaria)"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', now(), null, '["Aplicación"]'::jsonb, 4, 4),

('FL-A25', 'Cuestionario', 'Adopción', '1', '25', 'He diseñado sistemas de automatización donde IA se conecta con otras herramientas, como captación de leads, clasificación con IA, respuesta inicial y agendado de llamadas.', 'Multiple Choice (escala Likert A–E)', '["Nunca", "Rara vez (≤ 1/mes)", "Ocasional (2–3/mes)", "Frecuente (semanal)", "Muy frecuente (diaria)"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', now(), null, '["Aplicación"]'::jsonb, 4, 5),

('FL-A26', 'Cuestionario', 'Adopción', '1', '25', 'Uso IA para modelar escenarios de negocio, por ejemplo qué pasa si subo tarifas, cambio de nicho o acepto menos proyectos pero de mayor valor.', 'Multiple Choice (escala Likert A–E)', '["Nunca", "Rara vez (≤ 1/mes)", "Ocasional (2–3/mes)", "Frecuente (semanal)", "Muy frecuente (diaria)"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', now(), null, '["Aplicación"]'::jsonb, 4, 5),

('FL-A27', 'Cuestionario', 'Adopción', '1', '25', 'Incluyo en mis propuestas de valor cómo la IA me permite entregar más rápido y con mejor calidad, explicando claramente qué beneficios recibe el cliente.', 'Multiple Choice (escala Likert A–E)', '["Nunca", "Rara vez (≤ 1/mes)", "Ocasional (2–3/mes)", "Frecuente (semanal)", "Muy frecuente (diaria)"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', now(), null, '["Aplicación"]'::jsonb, 4, 5),

('FL-A28', 'Cuestionario', 'Adopción', '1', '25', 'Trabajo con otros freelancers o microequipos donde compartimos sistemas y plantillas de IA, mejorándolos en conjunto.', 'Multiple Choice (escala Likert A–E)', '["Nunca", "Rara vez (≤ 1/mes)", "Ocasional (2–3/mes)", "Frecuente (semanal)", "Muy frecuente (diaria)"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', now(), null, '["Aplicación"]'::jsonb, 4, 5),

('FL-A29', 'Cuestionario', 'Adopción', '1', '25', 'Monitoreo indicadores como tiempo invertido, ingresos por proyecto y satisfacción del cliente para ajustar y mejorar mis workflows de IA de forma continua.', 'Multiple Choice (escala Likert A–E)', '["Nunca", "Rara vez (≤ 1/mes)", "Ocasional (2–3/mes)", "Frecuente (semanal)", "Muy frecuente (diaria)"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', now(), null, '["Productividad"]'::jsonb, 4, 5),

('FL-A30', 'Cuestionario', 'Adopción', '1', '25', 'Antes de implementar una nueva automatización basada en IA, realizo pruebas controladas con pocos clientes o proyectos para reducir riesgos.', 'Multiple Choice (escala Likert A–E)', '["Nunca", "Rara vez (≤ 1/mes)", "Ocasional (2–3/mes)", "Frecuente (semanal)", "Muy frecuente (diaria)"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', now(), null, '["Estrategia", "Aplicación"]'::jsonb, 4, 5);

-- CONOCIMIENTO - Rol 25
INSERT INTO "public"."preguntas" ("codigo", "section", "bloque", "area_id", "exclusivo_rol_id", "texto", "tipo", "opciones", "locale", "peso", "escala", "scoring", "created_at", "respuesta_correcta", "dimension", "exclusivo_nivel_id", "dificultad") VALUES
('FL-C1', 'Cuestionario', 'Conocimiento', '1', '25', 'En tu trabajo como freelancer, ¿qué describe mejor a una herramienta de IA generativa como ChatGPT o similares?', 'Multiple Choice (una respuesta)', '["Un programa que solo corrige ortografía.", "Un sistema que puede generar texto, ideas o contenido a partir de instrucciones en lenguaje natural.", "Un editor de video tradicional sin funciones automáticas.", "Un gestor de proyectos basado en hojas de cálculo."]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', now(), 'Un sistema que puede generar texto, ideas o contenido a partir de instrucciones en lenguaje natural.', '["Conocimiento"]'::jsonb, 4, 1),

('FL-C2', 'Cuestionario', 'Conocimiento', '1', '25', '¿Cuál de las siguientes tareas es más típica para aplicar IA en el trabajo freelance?', 'Multiple Choice (una respuesta)', '["Subir facturas al banco físicamente.", "Generar borradores de correos para clientes y mejorarlos.", "Imprimir manualmente todos los contratos.", "Guardar archivos en una carpeta local sin revisión."]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', now(), 'Generar borradores de correos para clientes y mejorarlos.', '["Aplicación", "Conocimiento"]'::jsonb, 4, 1),

('FL-C3', 'Cuestionario', 'Conocimiento', '1', '25', 'Cuando usas IA para crear contenido para un cliente, ¿qué es una buena práctica básica?', 'Multiple Choice (una respuesta)', '["Copiar y pegar sin leer.", "Revisar, editar y adaptar el contenido generado antes de entregarlo.", "Entregar el contenido tal cual, pero con tu logo.", "Avisar que todo lo hizo la máquina y no revisar."]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', now(), 'Revisar, editar y adaptar el contenido generado antes de entregarlo.', '["Conocimiento"]'::jsonb, 4, 1),

('FL-C4', 'Cuestionario', 'Conocimiento', '1', '25', '¿Qué ventaja clave ofrece la IA a un freelancer que trabaja solo?', 'Multiple Choice (una respuesta)', '["Aumentar el número de reuniones presenciales.", "Reducir la necesidad de organizarse.", "Apoyar con ideas, borradores y tareas repetitivas para ahorrar tiempo.", "Eliminar la relación directa con los clientes."]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', now(), 'Apoyar con ideas, borradores y tareas repetitivas para ahorrar tiempo.', '["Conocimiento"]'::jsonb, 4, 1),

('FL-C5', 'Cuestionario', 'Conocimiento', '1', '25', '¿Cuál es un riesgo al usar IA con datos de tus clientes?', 'Multiple Choice (una respuesta)', '["Trabajar demasiado lento.", "Exponer información sensible en plataformas que no son seguras o no tienen permisos.", "Tener demasiadas ideas creativas.", "No usar plantillas."]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', now(), 'Exponer información sensible en plataformas que no son seguras o no tienen permisos.', '["Aplicación", "Estrategia", "Conocimiento"]'::jsonb, 4, 1),

('FL-C6', 'Cuestionario', 'Conocimiento', '1', '25', 'Si un cliente indica en el contrato que no desea contenido generado por IA, ¿qué deberías hacer?', 'Multiple Choice (una respuesta)', '["Ignorarlo, porque nadie lo revisará.", "Usar IA igualmente sin avisar.", "Respetar la cláusula y, en caso de necesitar IA, negociar y documentar el acuerdo.", "Rechazar todo uso de tecnología."]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', now(), 'Respetar la cláusula y, en caso de necesitar IA, negociar y documentar el acuerdo.', '["Conocimiento"]'::jsonb, 4, 1),

('FL-C7', 'Cuestionario', 'Conocimiento', '1', '25', '¿Cuál de estas tareas es un uso razonable de IA para apoyar tu marketing como freelancer?', 'Multiple Choice (una respuesta)', '["Definir tus tarifas sin analizar el mercado.", "Generar ideas de posts y luego adaptarlos a tu voz.", "Decidir por ti qué clientes rechazar.", "Firmar contratos en tu nombre."]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', now(), 'Generar ideas de posts y luego adaptarlos a tu voz.', '["Aplicación", "Conocimiento"]'::jsonb, 4, 2),

('FL-C8', 'Cuestionario', 'Conocimiento', '1', '25', 'Cuando usas un generador de imágenes, por ejemplo Midjourney u otros, ¿qué deberías tener en cuenta?', 'Multiple Choice (una respuesta)', '["Que todas las imágenes son siempre libres de derechos.", "Que debes revisar las políticas de uso y licencias antes de vender el resultado.", "Que no necesitas pedir permiso a ningún cliente.", "Que puedes reproducir marcas registradas sin problema."]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', now(), 'Que debes revisar las políticas de uso y licencias antes de vender el resultado.', '["Conocimiento"]'::jsonb, 4, 2),

('FL-C9', 'Cuestionario', 'Conocimiento', '1', '25', '¿Qué es un prompt en el contexto de IA generativa?', 'Multiple Choice (una respuesta)', '["El precio de tu servicio.", "La instrucción o mensaje que le das a la IA para que genere una respuesta.", "El contrato con el cliente.", "El tiempo que tardas en pagar impuestos."]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', now(), 'La instrucción o mensaje que le das a la IA para que genere una respuesta.', '["Conocimiento"]'::jsonb, 4, 2),

('FL-C10', 'Cuestionario', 'Conocimiento', '1', '25', 'Si usas IA para escribir un primer borrador de un artículo freelance, ¿qué paso es recomendable para mantener tu toque humano?', 'Multiple Choice (una respuesta)', '["Publicar el texto sin leerlo.", "Cambiar solo el título.", "Editar, reorganizar y añadir ejemplos basados en tu experiencia.", "Usar siempre el mismo prompt."]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', now(), 'Editar, reorganizar y añadir ejemplos basados en tu experiencia.', '["Conocimiento"]'::jsonb, 4, 2),

('FL-C11', 'Cuestionario', 'Conocimiento', '1', '25', '¿Qué puede pasar si dependes exclusivamente de IA para todo tu contenido?', 'Multiple Choice (una respuesta)', '["Tu marca personal se fortalece automáticamente.", "Tu estilo puede volverse genérico y menos diferenciado.", "Ningún cliente lo notará jamás.", "Los buscadores siempre te posicionarán mejor."]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', now(), 'Tu estilo puede volverse genérico y menos diferenciado.', '["Conocimiento"]'::jsonb, 4, 2),

('FL-C12', 'Cuestionario', 'Conocimiento', '1', '25', 'Al planear invertir en una nueva herramienta de IA de pago, ¿qué deberías evaluar?', 'Multiple Choice (una respuesta)', '["Solo si tiene muchos colores en la interfaz.", "Si el costo se justifica con el tiempo ahorrado o el valor agregado a tus servicios.", "Si es la más cara del mercado.", "Si la usa todo el mundo sin cuestionar."]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', now(), 'Si el costo se justifica con el tiempo ahorrado o el valor agregado a tus servicios.', '["Conocimiento"]'::jsonb, 4, 2),

('FL-C13', 'Cuestionario', 'Conocimiento', '1', '25', '¿Cuál es una buena práctica al diseñar prompts para IA en tu trabajo freelance?', 'Multiple Choice (una respuesta)', '["Usar frases muy cortas sin contexto.", "Especificar rol, objetivo, tono, audiencia y formato esperado.", "Escribir cualquier cosa; la IA siempre entiende.", "Cambiar el idioma sin avisar."]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', now(), 'Especificar rol, objetivo, tono, audiencia y formato esperado.', '["Conocimiento"]'::jsonb, 4, 3),

('FL-C14', 'Cuestionario', 'Conocimiento', '1', '25', 'Si usas IA para traducir entregables, ¿qué deberías hacer antes de enviarlos al cliente?', 'Multiple Choice (una respuesta)', '["Confiar 100% en la IA y no leer nada.", "Revisar términos técnicos y matices culturales.", "Traducir de nuevo usando otra IA siempre.", "Agregar errores a propósito."]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', now(), 'Revisar términos técnicos y matices culturales.', '["Conocimiento"]'::jsonb, 4, 3),

('FL-C15', 'Cuestionario', 'Conocimiento', '1', '25', '¿Qué describe mejor un workflow de IA en el contexto freelance?', 'Multiple Choice (una respuesta)', '["Un solo prompt aislado.", "Una secuencia de pasos donde la IA interviene en varios momentos del proceso, como brief, borrador y revisión.", "Solo la parte de facturación.", "Un archivo de texto sin estructura."]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', now(), 'Una secuencia de pasos donde la IA interviene en varios momentos del proceso, como brief, borrador y revisión.', '["Conocimiento"]'::jsonb, 4, 3),

('FL-C16', 'Cuestionario', 'Conocimiento', '1', '25', '¿Cuándo puede ser problemático usar IA con información de un cliente?', 'Multiple Choice (una respuesta)', '["Cuando la información es pública.", "Cuando subes datos sensibles a herramientas que pueden reutilizarlos para entrenar modelos.", "Cuando lo haces en tu propio dispositivo.", "Cuando usas conexión a internet."]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', now(), 'Cuando subes datos sensibles a herramientas que pueden reutilizarlos para entrenar modelos.', '["Aplicación", "Conocimiento"]'::jsonb, 4, 3),

('FL-C17', 'Cuestionario', 'Conocimiento', '1', '25', 'En términos de estrategia freelance, ¿qué ventaja te da dominar IA mejor que otros freelancers de tu nicho?', 'Multiple Choice (una respuesta)', '["Justificar tarifas mucho más bajas.", "Posicionarte como alguien que entrega más valor en menos tiempo, manteniendo márgenes saludables.", "Hacer más trabajo gratis.", "Depender solo de plataformas de gig-economy."]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', now(), 'Posicionarte como alguien que entrega más valor en menos tiempo, manteniendo márgenes saludables.', '["Estrategia", "Conocimiento"]'::jsonb, 4, 3),

('FL-C18', 'Cuestionario', 'Conocimiento', '1', '25', 'Si una herramienta de IA cambia su política de precios y dobla el costo, ¿qué enfoque es más sano para tu negocio?', 'Multiple Choice (una respuesta)', '["Aceptar el aumento sin analizarlo.", "Revisar alternativas, calcular el retorno de inversión y decidir si cambiar o renegociar.", "Dejar de ofrecer servicios.", "Ignorar las notificaciones."]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', now(), 'Revisar alternativas, calcular el retorno de inversión y decidir si cambiar o renegociar.', '["Inversión", "Conocimiento"]'::jsonb, 4, 3),

('FL-C19', 'Cuestionario', 'Conocimiento', '1', '25', '¿Qué representa mejor el rol de la IA en un negocio freelance maduro?', 'Multiple Choice (una respuesta)', '["Un reemplazo total del freelancer.", "Un copiloto que automatiza partes del trabajo mientras tú decides y supervisas.", "Un simple corrector ortográfico.", "Un chatbot para uso personal sin impacto en el negocio."]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', now(), 'Un copiloto que automatiza partes del trabajo mientras tú decides y supervisas.', '["Conocimiento"]'::jsonb, 4, 4),

('FL-C20', 'Cuestionario', 'Conocimiento', '1', '25', 'Cuando diseñas un flujo automatizado, por ejemplo respuestas a leads, ¿qué es clave para no perder tu toque humano?', 'Multiple Choice (una respuesta)', '["Evitar responder mensajes.", "Combinar mensajes generados por IA con revisiones y puntos de contacto humanos estratégicos.", "Dejar que la IA responda siempre sin supervisión.", "Nunca usar IA, aunque escales."]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', now(), 'Combinar mensajes generados por IA con revisiones y puntos de contacto humanos estratégicos.', '["Conocimiento"]'::jsonb, 4, 4),

('FL-C21', 'Cuestionario', 'Conocimiento', '1', '25', '¿Cuál es un criterio razonable para decidir qué procesos automatizar con IA primero?', 'Multiple Choice (una respuesta)', '["Los más creativos y personalizados.", "Los más repetitivos y de bajo valor para el cliente.", "Solo los más complejos.", "Ninguno; todo debe ser manual."]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', now(), 'Los más repetitivos y de bajo valor para el cliente.', '["Productividad", "Conocimiento"]'::jsonb, 4, 4),

('FL-C22', 'Cuestionario', 'Conocimiento', '1', '25', 'Si un cliente te contrata específicamente por tu creatividad humana, ¿cómo integrar IA sin comprometer esto?', 'Multiple Choice (una respuesta)', '["Ocultando totalmente que usas IA.", "Usándola para explorar opciones, pero construyendo tú la propuesta final con tu criterio.", "Dejando que la IA entregue el producto final.", "Rechazando toda tecnología."]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', now(), 'Usándola para explorar opciones, pero construyendo tú la propuesta final con tu criterio.', '["Conocimiento"]'::jsonb, 4, 4),

('FL-C23', 'Cuestionario', 'Conocimiento', '1', '25', '¿Qué implica una política responsable de uso de IA en tu negocio freelance?', 'Multiple Choice (una respuesta)', '["No informar a nadie sobre la IA.", "Definir y documentar cómo, cuándo y con qué datos usas IA, y comunicarlo cuando sea relevante.", "Permitir que la IA decida por ti.", "Prohibir toda experimentación."]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', now(), 'Definir y documentar cómo, cuándo y con qué datos usas IA, y comunicarlo cuando sea relevante.', '["Aplicación", "Conocimiento"]'::jsonb, 4, 4),

('FL-C24', 'Cuestionario', 'Conocimiento', '1', '25', '¿Qué riesgo financiero existe al construir tu oferta freelance sobre una sola herramienta de IA propietaria?', 'Multiple Choice (una respuesta)', '["Ninguno, las plataformas nunca cambian.", "Quedar expuesto a cambios de precio, restricciones o cierres que afecten directamente tu capacidad de entrega.", "Ganar clientes automáticamente.", "Reducir tu productividad para siempre."]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', now(), 'Quedar expuesto a cambios de precio, restricciones o cierres que afecten directamente tu capacidad de entrega.', '["Inversión", "Estrategia", "Conocimiento"]'::jsonb, 4, 4),

('FL-C25', 'Cuestionario', 'Conocimiento', '1', '25', '¿Qué caracteriza a un freelancer que orquesta IA en su negocio?', 'Multiple Choice (una respuesta)', '["Usa una única herramienta para todo.", "Combina varias herramientas de IA y automatizaciones conectadas a sus sistemas, como CRM, correo y facturación.", "Solo usa IA para entretenimiento.", "No documenta ningún proceso."]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', now(), 'Combina varias herramientas de IA y automatizaciones conectadas a sus sistemas, como CRM, correo y facturación.', '["Conocimiento"]'::jsonb, 4, 5),

('FL-C26', 'Cuestionario', 'Conocimiento', '1', '25', '¿Cuál es un riesgo clave al automatizar completamente la interacción inicial con clientes mediante IA?', 'Multiple Choice (una respuesta)', '["Ahorrar demasiado tiempo.", "Generar respuestas impersonales o inexactas que dañen la relación desde el principio.", "Recibir demasiadas solicitudes de proyecto.", "Tener demasiadas opciones de workflow."]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', now(), 'Generar respuestas impersonales o inexactas que dañen la relación desde el principio.', '["Productividad", "Estrategia", "Conocimiento"]'::jsonb, 4, 5),

('FL-C27', 'Cuestionario', 'Conocimiento', '1', '25', 'Cuando tú diseñas un sistema donde IA genera entregables en serie, por ejemplo múltiples piezas de contenido, ¿qué deberías asegurar?', 'Multiple Choice (una respuesta)', '["Que nadie pueda revisar nada.", "Que existan puntos de control humano para calidad, contexto y coherencia con la marca.", "Que todo sea 100% automático sin supervisión.", "Que el cliente no se entere del proceso."]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', now(), 'Que existan puntos de control humano para calidad, contexto y coherencia con la marca.', '["Conocimiento"]'::jsonb, 4, 5),

('FL-C28', 'Cuestionario', 'Conocimiento', '1', '25', 'En términos de inversión, ¿qué tiene sentido para un freelancer muy avanzado en IA?', 'Multiple Choice (una respuesta)', '["Nunca pagar por herramientas ni formación.", "Invertir de forma estratégica en herramientas, formación y automatización que generen retornos claros en ingresos, tiempo o calidad.", "Comprar todas las herramientas de moda sin análisis.", "Depender de una sola fuente de ingresos."]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', now(), 'Invertir de forma estratégica en herramientas, formación y automatización que generen retornos claros en ingresos, tiempo o calidad.', '["Inversión", "Conocimiento"]'::jsonb, 4, 5),

('FL-C29', 'Cuestionario', 'Conocimiento', '1', '25', '¿Qué enfoque respeta mejor la ética y la relación con los clientes al ofrecer servicios potenciados con IA?', 'Multiple Choice (una respuesta)', '["Presentar tus servicios como 100% IA sin trabajo humano.", "Comunicar con transparencia que usas IA como parte del proceso, explicando el valor agregado de tu criterio y experiencia.", "Ocultar completamente el uso de IA.", "Transferir la responsabilidad de errores solo al cliente."]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', now(), 'Comunicar con transparencia que usas IA como parte del proceso, explicando el valor agregado de tu criterio y experiencia.', '["Estrategia", "Conocimiento"]'::jsonb, 4, 5),

('FL-C30', 'Cuestionario', 'Conocimiento', '1', '25', 'Si ves que un flujo automatizado empieza a generar errores sistemáticos, ¿qué deberías hacer?', 'Multiple Choice (una respuesta)', '["Ignorarlo.", "Pausar, revisar y rediseñar el flujo, incluidos prompts, datos y pasos, antes de seguir escalando.", "Culpar a los clientes.", "Duplicar el presupuesto en anuncios."]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', now(), 'Pausar, revisar y rediseñar el flujo, incluidos prompts, datos y pasos, antes de seguir escalando.', '["Conocimiento"]'::jsonb, 4, 5);
