-- ============================================================================
-- PREGUNTAS PARA DIRECCIÓN DE VENTAS
-- ============================================================================
-- Rol incluido:
--   - Rol ID 11: Dirección de Ventas (area_id: 2, nivel_id: 2)
-- ============================================================================

-- ============================================================================
-- ROL 11: Dirección de Ventas
-- ============================================================================

-- ADOPCIÓN - Rol 11
INSERT INTO "public"."preguntas" ("codigo", "section", "bloque", "area_id", "exclusivo_rol_id", "texto", "tipo", "opciones", "locale", "peso", "escala", "scoring", "created_at", "respuesta_correcta", "dimension", "exclusivo_nivel_id", "dificultad") VALUES
('DV-A1', 'Cuestionario', 'Adopción', '2', '11', '¿Con qué frecuencia utilizas IA para redactar correos de prospección o seguimiento a clientes clave?', 'Multiple Choice (escala Likert A–E)', '["Nunca", "Rara vez (≤ 1/mes)", "Ocasional (2–3/mes)", "Frecuente (semanal)", "Muy frecuente (diaria)"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', now(), null, '["Aplicación"]'::jsonb, 2, 1),

('DV-A2', 'Cuestionario', 'Adopción', '2', '11', '¿Con qué frecuencia revisas o pruebas las sugerencias automáticas de “próximo paso” que ofrece tu CRM u otras herramientas de IA?', 'Multiple Choice (escala Likert A–E)', '["Nunca", "Rara vez (≤ 1/mes)", "Ocasional (2–3/mes)", "Frecuente (semanal)", "Muy frecuente (diaria)"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', now(), null, '["Aplicación"]'::jsonb, 2, 1),

('DV-A3', 'Cuestionario', 'Adopción', '2', '11', '¿Qué tanto usas por tu cuenta asistentes de IA (chatbots, copilots) para aclarar conceptos básicos (términos, métricas, definiciones) relacionados con ventas?', 'Multiple Choice (escala Likert A–E)', '["Nunca", "Rara vez (≤ 1/mes)", "Ocasional (2–3/mes)", "Frecuente (semanal)", "Muy frecuente (diaria)"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', now(), null, '["Productividad", "Aplicación"]'::jsonb, 2, 1),

('DV-A4', 'Cuestionario', 'Adopción', '2', '11', '¿Con qué frecuencia pides a tu equipo que comparta ejemplos concretos de cómo usan IA en su día a día comercial?', 'Multiple Choice (escala Likert A–E)', '["Nunca", "Rara vez (≤ 1/mes)", "Ocasional (2–3/mes)", "Frecuente (semanal)", "Muy frecuente (diaria)"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', now(), null, '["Aplicación"]'::jsonb, 2, 1),

('DV-A5', 'Cuestionario', 'Adopción', '2', '11', '¿Con qué frecuencia destinas tiempo en tus reuniones de staff a revisar brevemente nuevas funciones de IA de las herramientas que ya tienen?', 'Multiple Choice (escala Likert A–E)', '["Nunca", "Rara vez (≤ 1/mes)", "Ocasional (2–3/mes)", "Frecuente (semanal)", "Muy frecuente (diaria)"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', now(), null, '["Productividad", "Aplicación"]'::jsonb, 2, 1),

('DV-A6', 'Cuestionario', 'Adopción', '2', '11', '¿Qué tan habitual es que verifiques, antes de usar IA con datos de clientes, si la herramienta cumple con políticas básicas de privacidad y manejo de datos de tu organización?', 'Multiple Choice (escala Likert A–E)', '["Nunca", "Rara vez (≤ 1/mes)", "Ocasional (2–3/mes)", "Frecuente (semanal)", "Muy frecuente (diaria)"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', now(), null, '["Estrategia", "Aplicación"]'::jsonb, 2, 1),

('DV-A7', 'Cuestionario', 'Adopción', '2', '11', '¿Con qué frecuencia generas borradores de correos de prospección o seguimiento con IA y luego los revisas antes de enviar?', 'Multiple Choice (escala Likert A–E)', '["Nunca", "Rara vez (≤ 1/mes)", "Ocasional (2–3/mes)", "Frecuente (semanal)", "Muy frecuente (diaria)"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', now(), null, '["Aplicación"]'::jsonb, 2, 2),

('DV-A8', 'Cuestionario', 'Adopción', '2', '11', '¿Qué tan habitual es que compares tasas de apertura y respuesta de campañas donde se usó IA vs. campañas tradicionales?', 'Multiple Choice (escala Likert A–E)', '["Nunca", "Rara vez (≤ 1/mes)", "Ocasional (2–3/mes)", "Frecuente (semanal)", "Muy frecuente (diaria)"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', now(), null, '["Aplicación"]'::jsonb, 2, 2),

('DV-A9', 'Cuestionario', 'Adopción', '2', '11', '¿Con qué frecuencia ajustas los “prompts” o instrucciones que das a la IA para obtener mejores mensajes comerciales?', 'Multiple Choice (escala Likert A–E)', '["Nunca", "Rara vez (≤ 1/mes)", "Ocasional (2–3/mes)", "Frecuente (semanal)", "Muy frecuente (diaria)"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', now(), null, '["Aplicación"]'::jsonb, 2, 2),

('DV-A10', 'Cuestionario', 'Adopción', '2', '11', '¿Qué tan seguido pides a tus gerentes de ventas que compartan en reuniones de equipo ejemplos de mensajes generados con IA que hayan funcionado bien?', 'Multiple Choice (escala Likert A–E)', '["Nunca", "Rara vez (≤ 1/mes)", "Ocasional (2–3/mes)", "Frecuente (semanal)", "Muy frecuente (diaria)"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', now(), null, '["Aplicación"]'::jsonb, 2, 2),

('DV-A11', 'Cuestionario', 'Adopción', '2', '11', '¿Con qué frecuencia asignas tiempo o presupuesto para que tu equipo experimente con IA en nuevas plantillas de emails, discursos o presentaciones de ventas?', 'Multiple Choice (escala Likert A–E)', '["Nunca", "Rara vez (≤ 1/mes)", "Ocasional (2–3/mes)", "Frecuente (semanal)", "Muy frecuente (diaria)"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', now(), null, '["Productividad", "Aplicación", "Inversión"]'::jsonb, 2, 2),

('DV-A12', 'Cuestionario', 'Adopción', '2', '11', '¿Qué tanto revisas que los mensajes generados por IA respeten lineamientos de marca y no prometan beneficios que la empresa no puede cumplir?', 'Multiple Choice (escala Likert A–E)', '["Nunca", "Rara vez (≤ 1/mes)", "Ocasional (2–3/mes)", "Frecuente (semanal)", "Muy frecuente (diaria)"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', now(), null, '["Aplicación"]'::jsonb, 2, 2),

('DV-A13', 'Cuestionario', 'Adopción', '2', '11', '¿Con qué frecuencia revisas el pipeline apoyándote en vistas o reportes que incluyen pronósticos generados por IA?', 'Multiple Choice (escala Likert A–E)', '["Nunca", "Rara vez (≤ 1/mes)", "Ocasional (2–3/mes)", "Frecuente (semanal)", "Muy frecuente (diaria)"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', now(), null, '["Productividad"]'::jsonb, 2, 3),

('DV-A14', 'Cuestionario', 'Adopción', '2', '11', '¿Qué tan habitual es que ajustes prioridades de cuentas y oportunidades en función de los puntajes de lead scoring o riesgo de pérdida generados por IA?', 'Multiple Choice (escala Likert A–E)', '["Nunca", "Rara vez (≤ 1/mes)", "Ocasional (2–3/mes)", "Frecuente (semanal)", "Muy frecuente (diaria)"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', now(), null, '["Estrategia"]'::jsonb, 2, 3),

('DV-A15', 'Cuestionario', 'Adopción', '2', '11', '¿Con qué frecuencia exploras, por tu cuenta, diferentes filtros y vistas en el CRM para entender mejor cómo la IA está clasificando las oportunidades?', 'Multiple Choice (escala Likert A–E)', '["Nunca", "Rara vez (≤ 1/mes)", "Ocasional (2–3/mes)", "Frecuente (semanal)", "Muy frecuente (diaria)"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', now(), null, '["Aplicación"]'::jsonb, 2, 3),

('DV-A16', 'Cuestionario', 'Adopción', '2', '11', '¿Qué tan seguido trabajas con Marketing para ajustar campañas y mensajes basados en insights generados por IA sobre segmentos con mayor probabilidad de cierre?', 'Multiple Choice (escala Likert A–E)', '["Nunca", "Rara vez (≤ 1/mes)", "Ocasional (2–3/mes)", "Frecuente (semanal)", "Muy frecuente (diaria)"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', now(), null, '["Productividad"]'::jsonb, 2, 3),

('DV-A17', 'Cuestionario', 'Adopción', '2', '11', '¿Con qué frecuencia revisas, en discusiones con Finanzas o Dirección General, si la inversión en IA para pipeline se refleja en mejoras de forecast y revenue?', 'Multiple Choice (escala Likert A–E)', '["Nunca", "Rara vez (≤ 1/mes)", "Ocasional (2–3/mes)", "Frecuente (semanal)", "Muy frecuente (diaria)"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', now(), null, '["Inversión"]'::jsonb, 2, 3),

('DV-A18', 'Cuestionario', 'Adopción', '2', '11', '¿Qué tan habitual es que analices casos donde las recomendaciones de IA fueron erróneas o sesgadas, y ajustes procesos o criterios para reducir esos riesgos?', 'Multiple Choice (escala Likert A–E)', '["Nunca", "Rara vez (≤ 1/mes)", "Ocasional (2–3/mes)", "Frecuente (semanal)", "Muy frecuente (diaria)"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', now(), null, '["Estrategia"]'::jsonb, 2, 3),

('DV-A19', 'Cuestionario', 'Adopción', '2', '11', '¿Con qué frecuencia utilizas dashboards que integran métricas tradicionales (pipeline, cuota, margen) con indicadores generados por IA (riesgo de fuga, probabilidad de cierre, etc.) para tomar decisiones semanales?', 'Multiple Choice (escala Likert A–E)', '["Nunca", "Rara vez (≤ 1/mes)", "Ocasional (2–3/mes)", "Frecuente (semanal)", "Muy frecuente (diaria)"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', now(), null, '["Estrategia", "Productividad", "Aplicación"]'::jsonb, 2, 4),

('DV-A20', 'Cuestionario', 'Adopción', '2', '11', '¿Qué tan habitual es que ajustes estrategia comercial (focus en segmentos, territorios, productos) en función de patrones detectados por IA en los datos de clientes y oportunidades?', 'Multiple Choice (escala Likert A–E)', '["Nunca", "Rara vez (≤ 1/mes)", "Ocasional (2–3/mes)", "Frecuente (semanal)", "Muy frecuente (diaria)"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', now(), null, '["Estrategia", "Aplicación"]'::jsonb, 2, 4),

('DV-A21', 'Cuestionario', 'Adopción', '2', '11', '¿Con qué frecuencia exploras tú mismo/a distintos escenarios en herramientas de forecast con IA (por ejemplo, cambiando supuestos de conversión o pipeline) para entender la sensibilidad de los resultados?', 'Multiple Choice (escala Likert A–E)', '["Nunca", "Rara vez (≤ 1/mes)", "Ocasional (2–3/mes)", "Frecuente (semanal)", "Muy frecuente (diaria)"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', now(), null, '["Productividad", "Aplicación"]'::jsonb, 2, 4),

('DV-A22', 'Cuestionario', 'Adopción', '2', '11', '¿Qué tan seguido trabajas conjuntamente con Marketing, Customer Success y Finanzas para definir métricas compartidas en dashboards impulsados por IA (ej. LTV, CAC, churn, revenue expansion)?', 'Multiple Choice (escala Likert A–E)', '["Nunca", "Rara vez (≤ 1/mes)", "Ocasional (2–3/mes)", "Frecuente (semanal)", "Muy frecuente (diaria)"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', now(), null, '["Productividad"]'::jsonb, 2, 4),

('DV-A23', 'Cuestionario', 'Adopción', '2', '11', '¿Con qué frecuencia revisas el retorno esperado y real (ROI) de las inversiones en IA para ventas, comparando ahorro de tiempo, aumento de ingresos y costo total de propiedad?', 'Multiple Choice (escala Likert A–E)', '["Nunca", "Rara vez (≤ 1/mes)", "Ocasional (2–3/mes)", "Frecuente (semanal)", "Muy frecuente (diaria)"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', now(), null, '["Productividad", "Inversión"]'::jsonb, 2, 4),

('DV-A24', 'Cuestionario', 'Adopción', '2', '11', '¿Qué tan habitual es que requieras explicaciones claras (por parte de proveedores o de tu equipo de datos) sobre cómo los modelos de IA toman decisiones que afectan comisiones, territorio o priorización de clientes?', 'Multiple Choice (escala Likert A–E)', '["Nunca", "Rara vez (≤ 1/mes)", "Ocasional (2–3/mes)", "Frecuente (semanal)", "Muy frecuente (diaria)"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', now(), null, '["Aplicación"]'::jsonb, 2, 4),

('DV-A25', 'Cuestionario', 'Adopción', '2', '11', '¿Con qué frecuencia impulsas iniciativas donde IA se integra a lo largo de todo el funnel (desde marketing hasta customer success) con una visión unificada de revenue?', 'Multiple Choice (escala Likert A–E)', '["Nunca", "Rara vez (≤ 1/mes)", "Ocasional (2–3/mes)", "Frecuente (semanal)", "Muy frecuente (diaria)"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', now(), null, '["Estrategia"]'::jsonb, 2, 5),

('DV-A26', 'Cuestionario', 'Adopción', '2', '11', '¿Qué tan habitual es que definas y revises objetivos de negocio específicos para proyectos de IA (por ejemplo, mejorar conversión en X%, reducir churn en Y%) y los uses para tomar decisiones de continuidad o escalamiento?', 'Multiple Choice (escala Likert A–E)', '["Nunca", "Rara vez (≤ 1/mes)", "Ocasional (2–3/mes)", "Frecuente (semanal)", "Muy frecuente (diaria)"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', now(), null, '["Aplicación"]'::jsonb, 2, 5),

('DV-A27', 'Cuestionario', 'Adopción', '2', '11', '¿Con qué frecuencia exploras, junto con equipos de datos o analytics, modelos más avanzados (ej. segmentación por valor, propensity models, pricing dinámico) y discutes su aplicabilidad comercial?', 'Multiple Choice (escala Likert A–E)', '["Nunca", "Rara vez (≤ 1/mes)", "Ocasional (2–3/mes)", "Frecuente (semanal)", "Muy frecuente (diaria)"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', now(), null, '["Aplicación"]'::jsonb, 2, 5),

('DV-A28', 'Cuestionario', 'Adopción', '2', '11', '¿Qué tan seguido convocas a equipos interfuncionales (Marketing, Producto, TI, Finanzas, Legal) para asegurar que los proyectos de IA en ventas estén alineados con la estrategia global y cumplan regulaciones?', 'Multiple Choice (escala Likert A–E)', '["Nunca", "Rara vez (≤ 1/mes)", "Ocasional (2–3/mes)", "Frecuente (semanal)", "Muy frecuente (diaria)"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', now(), null, '["Estrategia", "Aplicación"]'::jsonb, 2, 5),

('DV-A29', 'Cuestionario', 'Adopción', '2', '11', '¿Con qué frecuencia revisas un portafolio de iniciativas de IA para ventas, reasignando presupuesto de proyectos con poco impacto a aquellos con mejores resultados?', 'Multiple Choice (escala Likert A–E)', '["Nunca", "Rara vez (≤ 1/mes)", "Ocasional (2–3/mes)", "Frecuente (semanal)", "Muy frecuente (diaria)"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', now(), null, '["Estrategia", "Productividad", "Inversión"]'::jsonb, 2, 5),

('DV-A30', 'Cuestionario', 'Adopción', '2', '11', '¿Qué tan habitual es que establezcas principios explícitos de uso responsable de IA en ventas (por ejemplo, transparencia, no discriminación, respeto a la privacidad) y los comuniques al equipo?', 'Multiple Choice (escala Likert A–E)', '["Nunca", "Rara vez (≤ 1/mes)", "Ocasional (2–3/mes)", "Frecuente (semanal)", "Muy frecuente (diaria)"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', now(), null, '["Estrategia", "Aplicación"]'::jsonb, 2, 5);

-- CONOCIMIENTO - Rol 11
INSERT INTO "public"."preguntas" ("codigo", "section", "bloque", "area_id", "exclusivo_rol_id", "texto", "tipo", "opciones", "locale", "peso", "escala", "scoring", "created_at", "respuesta_correcta", "dimension", "exclusivo_nivel_id", "dificultad") VALUES
('DV-C1', 'Cuestionario', 'Conocimiento', '2', '11', 'Como Director/a de Ventas, ¿qué describe mejor una herramienta de IA generativa aplicada a ventas?', 'Multiple Choice (una respuesta)', '["Un CRM tradicional sin análisis automático", "Un sistema que solo almacena datos históricos de ventas", "Una herramienta que genera contenido y recomendaciones a partir de datos y texto", "Un sistema de facturación electrónica"]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', now(), 'Una herramienta que genera contenido y recomendaciones a partir de datos y texto', '["Conocimiento", "Aplicación"]'::jsonb, 2, 1),

('DV-C2', 'Cuestionario', 'Conocimiento', '2', '11', '¿Cuál es un ejemplo sencillo de uso de IA en la gestión comercial?', 'Multiple Choice (una respuesta)', '["Imprimir los reportes de ventas en papel", "Usar IA para proponer el asunto y cuerpo de un correo de prospección", "Reunirse semanalmente con los vendedores sin datos", "Calcular comisiones en una calculadora manual"]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', now(), 'Usar IA para proponer el asunto y cuerpo de un correo de prospección', '["Conocimiento", "Aplicación"]'::jsonb, 2, 1),

('DV-C3', 'Cuestionario', 'Conocimiento', '2', '11', '¿Qué limitación básica debe considerar un Director de Ventas al usar IA para recomendar próximos pasos con un cliente?', 'Multiple Choice (una respuesta)', '["La IA siempre conoce mejor al cliente que el equipo de ventas", "La IA puede equivocarse si los datos de entrada son incompletos o sesgados", "La IA no puede procesar grandes volúmenes de datos", "La IA reemplaza totalmente la relación humana con el cliente"]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', now(), 'La IA puede equivocarse si los datos de entrada son incompletos o sesgados', '["Conocimiento"]'::jsonb, 2, 1),

('DV-C4', 'Cuestionario', 'Conocimiento', '2', '11', 'En un CRM con funciones de IA, ¿qué tarea ayuda más directamente a la productividad del equipo de ventas?', 'Multiple Choice (una respuesta)', '["Agregar manualmente todos los contactos sin plantillas", "Que la IA complete automáticamente campos repetitivos en el CRM", "Imprimir listas de clientes una vez al mes", "Pedir reportes por correo a cada vendedor"]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', now(), 'Que la IA complete automáticamente campos repetitivos en el CRM', '["Conocimiento", "Productividad", "Aplicación"]'::jsonb, 2, 1),

('DV-C5', 'Cuestionario', 'Conocimiento', '2', '11', 'Respecto a inversión en IA, ¿qué decisión básica corresponde al rol de Dirección de Ventas?', 'Multiple Choice (una respuesta)', '["Elegir tecnologías sin considerar impacto en el pipeline", "Definir junto con TI y Finanzas qué herramientas de IA aportan más valor al equipo comercial", "Comprar cualquier herramienta de moda en el mercado", "Dejar que cada vendedor contrate la IA que prefiera sin alineación"]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', now(), 'Definir junto con TI y Finanzas qué herramientas de IA aportan más valor al equipo comercial', '["Conocimiento", "Inversión"]'::jsonb, 2, 1),

('DV-C6', 'Cuestionario', 'Conocimiento', '2', '11', '¿Por qué es importante la calidad de datos en un CRM con IA para ventas?', 'Multiple Choice (una respuesta)', '["Porque hace el CRM más lento", "Porque afecta directamente la precisión de las recomendaciones y pronósticos", "Porque solo importa para marketing", "Porque evita que los vendedores usen Excel"]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', now(), 'Porque afecta directamente la precisión de las recomendaciones y pronósticos', '["Conocimiento", "Aplicación"]'::jsonb, 2, 1),

('DV-C7', 'Cuestionario', 'Conocimiento', '2', '11', '¿Qué es el “lead scoring” apoyado en IA en un contexto de ventas B2B?', 'Multiple Choice (una respuesta)', '["Una forma de ordenar contactos alfabéticamente", "Un sistema que asigna puntajes a leads en función de criterios manuales únicamente", "Un modelo que asigna puntajes a leads buscando predecir probabilidad de compra a partir de datos", "Un sistema de facturación automática"]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', now(), 'Un modelo que asigna puntajes a leads buscando predecir probabilidad de compra a partir de datos', '["Conocimiento"]'::jsonb, 2, 2),

('DV-C8', 'Cuestionario', 'Conocimiento', '2', '11', '¿Cuál es una buena práctica inicial al introducir IA en la prospección outbound?', 'Multiple Choice (una respuesta)', '["Generar secuencias de correo con IA y enviarlas sin revisión", "Diseñar mensajes tipo con IA, pero revisarlos y adaptarlos a segmentos estratégicos", "Prohibir que el equipo modifique los textos generados por IA", "Cambiar todo el pitch de ventas cada semana"]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', now(), 'Diseñar mensajes tipo con IA, pero revisarlos y adaptarlos a segmentos estratégicos', '["Conocimiento"]'::jsonb, 2, 2),

('DV-C9', 'Cuestionario', 'Conocimiento', '2', '11', '¿Qué riesgo táctico existe al usar IA para personalizar mensajes sin supervisión?', 'Multiple Choice (una respuesta)', '["Que la IA deje de funcionar sin aviso", "Que los mensajes incluyan errores de contexto, datos falsos o tono inadecuado para el cliente", "Que los correos se envíen más rápido", "Que el CRM se vuelva más caro"]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', now(), 'Que los mensajes incluyan errores de contexto, datos falsos o tono inadecuado para el cliente', '["Conocimiento", "Estrategia"]'::jsonb, 2, 2),

('DV-C10', 'Cuestionario', 'Conocimiento', '2', '11', '¿Cómo podría un Director de Ventas usar IA para analizar rápidamente notas de reuniones comerciales?', 'Multiple Choice (una respuesta)', '["Transcribiendo manualmente cada reunión", "Pidiendo a la IA que resuma, a partir de una transcripción, los próximos pasos y riesgos clave", "Solicitando un reporte trimestral sin datos", "Eliminando las grabaciones después de cada llamada"]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', now(), 'Pidiendo a la IA que resuma, a partir de una transcripción, los próximos pasos y riesgos clave', '["Conocimiento"]'::jsonb, 2, 2),

('DV-C11', 'Cuestionario', 'Conocimiento', '2', '11', 'Desde una perspectiva de inversión, ¿qué indicador simple puede seguir la Dirección de Ventas al probar IA en prospección?', 'Multiple Choice (una respuesta)', '["Número de correos enviados sin importar resultados", "Aumento en tasa de respuesta positiva o reuniones agendadas respecto a un proceso sin IA", "Horas de uso de la herramienta", "Cantidad de licencias compradas"]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', now(), 'Aumento en tasa de respuesta positiva o reuniones agendadas respecto a un proceso sin IA', '["Conocimiento", "Inversión"]'::jsonb, 2, 2),

('DV-C12', 'Cuestionario', 'Conocimiento', '2', '11', '¿Qué rol juega el equipo de ventas al ajustar el uso de IA en mensajes comerciales?', 'Multiple Choice (una respuesta)', '["Ninguno, la IA decide sola", "Revisar ejemplos, proponer mejoras y compartir “prompts” y plantillas que funcionen mejor", "Solo reportar errores técnicos", "Usar IA solo cuando TI lo pida"]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', now(), 'Revisar ejemplos, proponer mejoras y compartir “prompts” y plantillas que funcionen mejor', '["Conocimiento", "Aplicación"]'::jsonb, 2, 2),

('DV-C13', 'Cuestionario', 'Conocimiento', '2', '11', '¿Qué ventaja ofrece un modelo de IA integrado al CRM para gestionar el pipeline de ventas?', 'Multiple Choice (una respuesta)', '["Elimina la necesidad de registrar actividades", "Permite priorizar oportunidades y estimar probabilidad de cierre basada en datos históricos", "Calcula automáticamente las comisiones", "Sustituye la revisión de pipeline por parte de la Dirección"]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', now(), 'Permite priorizar oportunidades y estimar probabilidad de cierre basada en datos históricos', '["Conocimiento"]'::jsonb, 2, 3),

('DV-C14', 'Cuestionario', 'Conocimiento', '2', '11', 'En una reunión de forecast, ¿qué uso básico de IA es coherente con el rol de Dirección de Ventas?', 'Multiple Choice (una respuesta)', '["Confiar solo en la opinión de cada vendedor", "Usar pronósticos de IA como un escenario más, combinado con juicio del equipo", "Ignorar por completo las proyecciones del CRM", "Cambiar las metas según la sugerencia del modelo sin discutirlo"]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', now(), 'Usar pronósticos de IA como un escenario más, combinado con juicio del equipo', '["Conocimiento", "Aplicación"]'::jsonb, 2, 3),

('DV-C15', 'Cuestionario', 'Conocimiento', '2', '11', '¿Qué indicador ayuda a medir el impacto de IA en la gestión del pipeline?', 'Multiple Choice (una respuesta)', '["Número de correos internos enviados", "Reducción en el ciclo de ventas medio o aumento en tasa de cierre, después de integrar IA", "Horas de reunión", "Número de productos en catálogo"]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', now(), 'Reducción en el ciclo de ventas medio o aumento en tasa de cierre, después de integrar IA', '["Conocimiento"]'::jsonb, 2, 3),

('DV-C16', 'Cuestionario', 'Conocimiento', '2', '11', '¿Qué riesgo aparece al usar IA para priorizar oportunidades sin revisar la segmentación de clientes?', 'Multiple Choice (una respuesta)', '["Una segmentación demasiado diversa", "La IA podría favorecer sistemáticamente ciertos tipos de clientes y descuidar otros segmentos valiosos", "Todas las oportunidades se cierran más rápido", "Se reduce el volumen de datos"]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', now(), 'La IA podría favorecer sistemáticamente ciertos tipos de clientes y descuidar otros segmentos valiosos', '["Conocimiento", "Estrategia"]'::jsonb, 2, 3),

('DV-C17', 'Cuestionario', 'Conocimiento', '2', '11', 'Desde la perspectiva de inversión, ¿qué decisión es propia de un Director de Ventas que integra IA en pipeline?', 'Multiple Choice (una respuesta)', '["Adquirir varias herramientas aisladas sin integración con el CRM", "Priorizar herramientas que se integren con el CRM principal y permitan medir impacto en forecast y conversiones", "Comprar IA solo para una región", "Dejar que cada vendedor elija su herramienta sin coordinación"]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', now(), 'Priorizar herramientas que se integren con el CRM principal y permitan medir impacto en forecast y conversiones', '["Conocimiento", "Inversión"]'::jsonb, 2, 3),

('DV-C18', 'Cuestionario', 'Conocimiento', '2', '11', '¿Qué rol juega la colaboración con otras áreas al integrar IA en la gestión de pipeline?', 'Multiple Choice (una respuesta)', '["Ninguno, ventas decide todo", "Es clave coordinarse con Marketing y Customer Success para alinear datos, definiciones de etapas y métricas", "TI solo debe pagar la licencia", "Finanzas solo define el presupuesto"]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', now(), 'Es clave coordinarse con Marketing y Customer Success para alinear datos, definiciones de etapas y métricas', '["Conocimiento"]'::jsonb, 2, 3),

('DV-C19', 'Cuestionario', 'Conocimiento', '2', '11', '¿Qué caracteriza a una gestión de ventas “data-driven” apoyada en IA a nivel de Dirección?', 'Multiple Choice (una respuesta)', '["Basarse principalmente en la intuición de los mejores vendedores", "Tomar decisiones guiadas por datos, modelos y métricas alineadas al plan comercial", "Revisar datos solo al final del año", "Delegar toda decisión estratégica a TI"]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', now(), 'Tomar decisiones guiadas por datos, modelos y métricas alineadas al plan comercial', '["Conocimiento"]'::jsonb, 2, 4),

('DV-C20', 'Cuestionario', 'Conocimiento', '2', '11', '¿Qué uso de IA es coherente con un enfoque estratégico en reuniones de QBR (Quarterly Business Review)?', 'Multiple Choice (una respuesta)', '["Presentar solo cifras agregadas sin análisis", "Integrar escenarios de forecast generados por IA para discutir riesgos y oportunidades por segmento", "Revisar únicamente historias de éxito individuales", "Evitar mostrar datos para no confundir al equipo"]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', now(), 'Integrar escenarios de forecast generados por IA para discutir riesgos y oportunidades por segmento', '["Conocimiento", "Aplicación"]'::jsonb, 2, 4),

('DV-C21', 'Cuestionario', 'Conocimiento', '2', '11', '¿Qué indicador ayuda a evaluar impacto de IA en la productividad de la fuerza de ventas a nivel Dirección?', 'Multiple Choice (una respuesta)', '["Número de reuniones internas", "Horas de capacitación realizadas", "Incremento en ventas por representante o por hora de trabajo después de automatizar tareas con IA", "Número de reportes generados"]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', now(), 'Incremento en ventas por representante o por hora de trabajo después de automatizar tareas con IA', '["Conocimiento", "Productividad"]'::jsonb, 2, 4),

('DV-C22', 'Cuestionario', 'Conocimiento', '2', '11', '¿Qué riesgo aparece al depender en exceso de modelos opacos (“caja negra”) para decisiones clave de asignación de territorio y cuotas?', 'Multiple Choice (una respuesta)', '["Los modelos siempre son neutros", "El equipo podría percibir decisiones como injustas, difícilmente explicables o sesgadas", "Se reduce el volumen de datos", "Mejora automáticamente el clima laboral"]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', now(), 'El equipo podría percibir decisiones como injustas, difícilmente explicables o sesgadas', '["Conocimiento", "Estrategia"]'::jsonb, 2, 4),

('DV-C23', 'Cuestionario', 'Conocimiento', '2', '11', '¿Qué buena práctica de inversión en IA corresponde a este nivel de adopción?', 'Multiple Choice (una respuesta)', '["Financiar proyectos de IA aislados sin indicadores", "Definir un portafolio de iniciativas de IA para ventas con objetivos, KPIs y responsables claros", "Comprar todas las funcionalidades disponibles del proveedor", "Evaluar proyectos solo por su costo y no por su impacto en revenue"]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', now(), 'Definir un portafolio de iniciativas de IA para ventas con objetivos, KPIs y responsables claros', '["Conocimiento", "Aplicación", "Inversión"]'::jsonb, 2, 4),

('DV-C24', 'Cuestionario', 'Conocimiento', '2', '11', '¿Qué rol debe jugar la Dirección de Ventas respecto al desarrollo de capacidades en IA en su equipo?', 'Multiple Choice (una respuesta)', '["Ninguno, cada vendedor aprende solo", "Definir un plan de capacitación en IA comercial, promover espacios de práctica y compartir mejores casos", "Delegar todo a Recursos Humanos", "Capacitar solo al área de TI"]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', now(), 'Definir un plan de capacitación en IA comercial, promover espacios de práctica y compartir mejores casos', '["Conocimiento", "Aplicación"]'::jsonb, 2, 4),

('DV-C25', 'Cuestionario', 'Conocimiento', '2', '11', '¿Qué caracteriza a una estrategia comercial donde la IA es un habilitador central?', 'Multiple Choice (una respuesta)', '["La IA se usa solo para tareas administrativas", "La IA se integra en decisiones clave de segmentación, pricing, priorización de cuentas y diseño de la fuerza de ventas", "Solo se utiliza para redactar correos", "Se limita al análisis de datos históricos sin conexión con la ejecución"]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', now(), 'La IA se integra en decisiones clave de segmentación, pricing, priorización de cuentas y diseño de la fuerza de ventas', '["Conocimiento", "Estrategia"]'::jsonb, 2, 5),

('DV-C26', 'Cuestionario', 'Conocimiento', '2', '11', '¿Qué rol tiene la IA en un modelo de “next best action” (siguiente mejor acción) para ventas?', 'Multiple Choice (una respuesta)', '["Generar una lista fija de pasos para todos los clientes", "Recomendar dinámicamente la acción más probable para mejorar conversión o valor del cliente", "Calcular solo el histórico de ventas", "Asignar cuotas sin datos"]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', now(), 'Recomendar dinámicamente la acción más probable para mejorar conversión o valor del cliente', '["Conocimiento"]'::jsonb, 2, 5),

('DV-C27', 'Cuestionario', 'Conocimiento', '2', '11', '¿Qué indicador avanzado puede usar la Dirección de Ventas para evaluar impacto estratégico de IA en el negocio?', 'Multiple Choice (una respuesta)', '["Número de herramientas contratadas", "Incremento en revenue incremental atribuible a iniciativas de IA (por ejemplo, uplift de conversión en segmentos tratados con IA vs. control)", "Cantidad de reuniones internas sobre IA", "Número de dashboards disponibles"]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', now(), 'Incremento en revenue incremental atribuible a iniciativas de IA (por ejemplo, uplift de conversión en segmentos tratados con IA vs. control)', '["Conocimiento", "Estrategia"]'::jsonb, 2, 5),

('DV-C28', 'Cuestionario', 'Conocimiento', '2', '11', '¿Qué riesgo ético y de negocio es crítico cuando IA influye en decisiones de precio, descuento y condiciones comerciales?', 'Multiple Choice (una respuesta)', '["Que el equipo tenga demasiada información", "Que se generen discriminaciones injustas entre clientes o segmentos sin justificación comercial válida", "Que las herramientas sean muy económicas", "Que los reportes se vean complejos"]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', now(), 'Que se generen discriminaciones injustas entre clientes o segmentos sin justificación comercial válida', '["Conocimiento", "Estrategia"]'::jsonb, 2, 5),

('DV-C29', 'Cuestionario', 'Conocimiento', '2', '11', 'Desde la perspectiva de inversión portafolio, ¿qué decisión refleja liderazgo transformador en IA para ventas?', 'Multiple Choice (una respuesta)', '["Apostar todo el presupuesto a una sola herramienta y caso de uso", "Diseñar un roadmap de IA con apuestas piloto, escalamiento de casos exitosos y retiro de iniciativas sin impacto", "Reducir toda inversión en capacitación", "Asignar presupuesto sin criterios de priorización"]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', now(), 'Diseñar un roadmap de IA con apuestas piloto, escalamiento de casos exitosos y retiro de iniciativas sin impacto', '["Conocimiento", "Inversión"]'::jsonb, 2, 5),

('DV-C30', 'Cuestionario', 'Conocimiento', '2', '11', '¿Qué rol juega la Dirección de Ventas en la gobernanza de datos e IA a nivel organizacional?', 'Multiple Choice (una respuesta)', '["Ninguno, es solo de TI", "Participar activamente en comités de datos e IA, definiendo criterios comerciales, métricas y límites de uso", "Solo validar presupuestos", "Revisar correos antes de enviarlos"]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', now(), 'Participar activamente en comités de datos e IA, definiendo criterios comerciales, métricas y límites de uso', '["Conocimiento", "Estrategia", "Aplicación"]'::jsonb, 2, 5);
