-- ============================================================================
-- PREGUNTAS PARA EDUCACIÓN/DOCENTES
-- ============================================================================
-- Rol incluido:
--   - Rol ID 9: Educación/Docentes (area_id: 10, nivel_id: 3)
-- ============================================================================

-- ============================================================================
-- ROL 9: Educación/Docentes
-- ============================================================================

-- ADOPCIÓN - Rol 9
INSERT INTO "public"."preguntas" ("codigo", "section", "bloque", "area_id", "exclusivo_rol_id", "texto", "tipo", "opciones", "locale", "peso", "escala", "scoring", "created_at", "respuesta_correcta", "dimension", "exclusivo_nivel_id", "dificultad") VALUES
('ED-A1', 'Cuestionario', 'Adopción', '10', '9', 'Uso IA para inspirarme con ideas de actividades o ejemplos cuando preparo una clase.', 'Multiple Choice (escala Likert A–E)', '["Nunca", "Rara vez (≤ 1/mes)", "Ocasional (2–3/mes)", "Casi siempre", "Muy frecuente (diaria)"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', now(), null, '["Aplicación"]'::jsonb, 3, 1),

('ED-A2', 'Cuestionario', 'Adopción', '10', '9', 'Cuando utilizo IA, reviso el contenido generado para asegurarme de que se adapte a mi grupo de estudiantes.', 'Multiple Choice (escala Likert A–E)', '["Nunca", "Rara vez (≤ 1/mes)", "Ocasional (2–3/mes)", "Casi siempre", "Muy frecuente (diaria)"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', now(), null, '["Aplicación"]'::jsonb, 3, 1),

('ED-A3', 'Cuestionario', 'Adopción', '10', '9', 'Busco información o recursos para entender mejor qué es la IA y cómo se usa en educación.', 'Multiple Choice (escala Likert A–E)', '["Nunca", "Rara vez (≤ 1/mes)", "Ocasional (2–3/mes)", "Casi siempre", "Muy frecuente (diaria)"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', now(), null, '["Aplicación"]'::jsonb, 3, 1),

('ED-A4', 'Cuestionario', 'Adopción', '10', '9', 'He dedicado tiempo específico (fuera de mis clases) a probar alguna herramienta de IA aplicable a mi asignatura.', 'Multiple Choice (escala Likert A–E)', '["Nunca", "Rara vez (≤ 1/mes)", "Ocasional (2–3/mes)", "Casi siempre", "Muy frecuente (diaria)"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', now(), null, '["Productividad", "Aplicación"]'::jsonb, 3, 1),

('ED-A5', 'Cuestionario', 'Adopción', '10', '9', 'Converso con colegas sobre dudas, temores o ideas relacionadas con el uso de IA en el aula.', 'Multiple Choice (escala Likert A–E)', '["Nunca", "Rara vez (≤ 1/mes)", "Ocasional (2–3/mes)", "Casi siempre", "Muy frecuente (diaria)"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', now(), null, '["Aplicación"]'::jsonb, 3, 1),

('ED-A6', 'Cuestionario', 'Adopción', '10', '9', 'Cuando pienso en la IA, considero también riesgos como plagio, desinformación o pérdida de habilidades de los estudiantes.', 'Multiple Choice (escala Likert A–E)', '["Nunca", "Rara vez (≤ 1/mes)", "Ocasional (2–3/mes)", "Casi siempre", "Muy frecuente (diaria)"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', now(), null, '["Estrategia", "Aplicación"]'::jsonb, 3, 1),

('ED-A7', 'Cuestionario', 'Adopción', '10', '9', 'Uso IA para generar borradores de actividades o ejercicios que luego adapto a mi contexto.', 'Multiple Choice (escala Likert A–E)', '["Nunca", "Rara vez (≤ 1/mes)", "Ocasional (2–3/mes)", "Casi siempre", "Muy frecuente (diaria)"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', now(), null, '["Aplicación"]'::jsonb, 3, 2),

('ED-A8', 'Cuestionario', 'Adopción', '10', '9', 'Pido a la IA que me sugiera diferentes formas de explicar un mismo concepto a distintos niveles de estudiantes.', 'Multiple Choice (escala Likert A–E)', '["Nunca", "Rara vez (≤ 1/mes)", "Ocasional (2–3/mes)", "Casi siempre", "Muy frecuente (diaria)"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', now(), null, '["Aplicación"]'::jsonb, 3, 2),

('ED-A9', 'Cuestionario', 'Adopción', '10', '9', 'He invertido tiempo en aprender a escribir prompts más claros para obtener mejores resultados de la IA.', 'Multiple Choice (escala Likert A–E)', '["Nunca", "Rara vez (≤ 1/mes)", "Ocasional (2–3/mes)", "Casi siempre", "Muy frecuente (diaria)"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', now(), null, '["Productividad"]'::jsonb, 3, 2),

('ED-A10', 'Cuestionario', 'Adopción', '10', '9', 'Discuto con mis estudiantes el uso responsable de IA (plagio, autoría, verificación de información).', 'Multiple Choice (escala Likert A–E)', '["Nunca", "Rara vez (≤ 1/mes)", "Ocasional (2–3/mes)", "Casi siempre", "Muy frecuente (diaria)"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', now(), null, '["Aplicación"]'::jsonb, 3, 2),

('ED-A11', 'Cuestionario', 'Adopción', '10', '9', 'Colaboro con al menos un colega para compartir experiencias sobre el uso de IA en nuestras asignaturas.', 'Multiple Choice (escala Likert A–E)', '["Nunca", "Rara vez (≤ 1/mes)", "Ocasional (2–3/mes)", "Casi siempre", "Muy frecuente (diaria)"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', now(), null, '["Aplicación"]'::jsonb, 3, 2),

('ED-A12', 'Cuestionario', 'Adopción', '10', '9', 'Evalúo si el uso de IA realmente me ahorra tiempo en comparación con mis métodos tradicionales.', 'Multiple Choice (escala Likert A–E)', '["Nunca", "Rara vez (≤ 1/mes)", "Ocasional (2–3/mes)", "Casi siempre", "Muy frecuente (diaria)"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', now(), null, '["Productividad", "Aplicación"]'::jsonb, 3, 2),

('ED-A13', 'Cuestionario', 'Adopción', '10', '9', 'Uso IA de forma regular para adaptar textos y materiales a diferentes niveles de competencia de mis estudiantes.', 'Multiple Choice (escala Likert A–E)', '["Nunca", "Rara vez (≤ 1/mes)", "Ocasional (2–3/mes)", "Casi siempre", "Muy frecuente (diaria)"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', now(), null, '["Aplicación"]'::jsonb, 3, 3),

('ED-A14', 'Cuestionario', 'Adopción', '10', '9', 'Utilizo IA para generar retroalimentación inicial sobre trabajos de estudiantes y luego la complemento con mi análisis.', 'Multiple Choice (escala Likert A–E)', '["Nunca", "Rara vez (≤ 1/mes)", "Ocasional (2–3/mes)", "Casi siempre", "Muy frecuente (diaria)"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', now(), null, '["Aplicación"]'::jsonb, 3, 3),

('ED-A15', 'Cuestionario', 'Adopción', '10', '9', 'Reviso datos o reportes (ya sea de IA o de plataformas educativas) para tomar decisiones sobre qué reforzar en clase.', 'Multiple Choice (escala Likert A–E)', '["Nunca", "Rara vez (≤ 1/mes)", "Ocasional (2–3/mes)", "Casi siempre", "Muy frecuente (diaria)"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', now(), null, '["Productividad", "Aplicación"]'::jsonb, 3, 3),

('ED-A16', 'Cuestionario', 'Adopción', '10', '9', 'He invertido tiempo en comparar distintas herramientas de IA para elegir las que mejor se ajustan a mi asignatura.', 'Multiple Choice (escala Likert A–E)', '["Nunca", "Rara vez (≤ 1/mes)", "Ocasional (2–3/mes)", "Casi siempre", "Muy frecuente (diaria)"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', now(), null, '["Productividad", "Aplicación"]'::jsonb, 3, 3),

('ED-A17', 'Cuestionario', 'Adopción', '10', '9', 'Trabajo con otros docentes para diseñar actividades o proyectos donde los estudiantes usen IA de manera guiada.', 'Multiple Choice (escala Likert A–E)', '["Nunca", "Rara vez (≤ 1/mes)", "Ocasional (2–3/mes)", "Casi siempre", "Muy frecuente (diaria)"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', now(), null, '["Aplicación"]'::jsonb, 3, 3),

('ED-A18', 'Cuestionario', 'Adopción', '10', '9', 'Antes de implementar una actividad con IA, considero posibles riesgos (plagio, dependencia, equidad de acceso) y cómo mitigarlos.', 'Multiple Choice (escala Likert A–E)', '["Nunca", "Rara vez (≤ 1/mes)", "Ocasional (2–3/mes)", "Casi siempre", "Muy frecuente (diaria)"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', now(), null, '["Estrategia", "Aplicación"]'::jsonb, 3, 3),

('ED-A19', 'Cuestionario', 'Adopción', '10', '9', 'Integro IA de forma sistemática en mis secuencias didácticas, alineándola con los objetivos y criterios de evaluación del curso.', 'Multiple Choice (escala Likert A–E)', '["Nunca", "Rara vez (≤ 1/mes)", "Ocasional (2–3/mes)", "Casi siempre", "Muy frecuente (diaria)"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', now(), null, '["Aplicación"]'::jsonb, 3, 4),

('ED-A20', 'Cuestionario', 'Adopción', '10', '9', 'Utilizo datos generados o analizados por IA para ajustar la dificultad, el ritmo o los recursos de mis clases.', 'Multiple Choice (escala Likert A–E)', '["Nunca", "Rara vez (≤ 1/mes)", "Ocasional (2–3/mes)", "Casi siempre", "Muy frecuente (diaria)"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', now(), null, '["Aplicación"]'::jsonb, 3, 4),

('ED-A21', 'Cuestionario', 'Adopción', '10', '9', 'He dedicado tiempo a formaciones (cursos, webinars, lecturas) específicas sobre IA aplicada a la educación.', 'Multiple Choice (escala Likert A–E)', '["Nunca", "Rara vez (≤ 1/mes)", "Ocasional (2–3/mes)", "Casi siempre", "Muy frecuente (diaria)"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', now(), null, '["Productividad", "Aplicación"]'::jsonb, 3, 4),

('ED-A22', 'Cuestionario', 'Adopción', '10', '9', 'Participo en grupos o comunidades de práctica donde compartimos experiencias y recursos de IA entre docentes.', 'Multiple Choice (escala Likert A–E)', '["Nunca", "Rara vez (≤ 1/mes)", "Ocasional (2–3/mes)", "Casi siempre", "Muy frecuente (diaria)"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', now(), null, '["Aplicación"]'::jsonb, 3, 4),

('ED-A23', 'Cuestionario', 'Adopción', '10', '9', 'Antes de incorporar una nueva herramienta de IA, reviso sus condiciones de uso, tratamiento de datos y compatibilidad con las políticas de mi institución.', 'Multiple Choice (escala Likert A–E)', '["Nunca", "Rara vez (≤ 1/mes)", "Ocasional (2–3/mes)", "Casi siempre", "Muy frecuente (diaria)"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', now(), null, '["Aplicación"]'::jsonb, 3, 4),

('ED-A24', 'Cuestionario', 'Adopción', '10', '9', 'Reviso periódicamente si la IA que utilizo realmente mejora los resultados de aprendizaje (no solo si gusta a los estudiantes).', 'Multiple Choice (escala Likert A–E)', '["Nunca", "Rara vez (≤ 1/mes)", "Ocasional (2–3/mes)", "Casi siempre", "Muy frecuente (diaria)"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', now(), null, '["Productividad"]'::jsonb, 3, 4),

('ED-A25', 'Cuestionario', 'Adopción', '10', '9', 'Lidero o impulso iniciativas (talleres, proyectos, pilotos) para que otros docentes aprendan a integrar IA en sus clases.', 'Multiple Choice (escala Likert A–E)', '["Nunca", "Rara vez (≤ 1/mes)", "Ocasional (2–3/mes)", "Casi siempre", "Muy frecuente (diaria)"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', now(), null, '["Estrategia"]'::jsonb, 3, 5),

('ED-A26', 'Cuestionario', 'Adopción', '10', '9', 'Diseño o adapto rúbricas y criterios específicos para evaluar trabajos de estudiantes que han usado IA en su proceso.', 'Multiple Choice (escala Likert A–E)', '["Nunca", "Rara vez (≤ 1/mes)", "Ocasional (2–3/mes)", "Casi siempre", "Muy frecuente (diaria)"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', now(), null, '["Aplicación"]'::jsonb, 3, 5),

('ED-A27', 'Cuestionario', 'Adopción', '10', '9', 'Participo activamente en la definición o mejora de lineamientos institucionales sobre uso responsable de IA.', 'Multiple Choice (escala Likert A–E)', '["Nunca", "Rara vez (≤ 1/mes)", "Ocasional (2–3/mes)", "Casi siempre", "Muy frecuente (diaria)"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', now(), null, '["Aplicación"]'::jsonb, 3, 5),

('ED-A28', 'Cuestionario', 'Adopción', '10', '9', 'Evalúo de manera sistemática (con datos y evidencias) el impacto de las actividades con IA en el aprendizaje y la motivación de mis estudiantes.', 'Multiple Choice (escala Likert A–E)', '["Nunca", "Rara vez (≤ 1/mes)", "Ocasional (2–3/mes)", "Casi siempre", "Muy frecuente (diaria)"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', now(), null, '["Aplicación"]'::jsonb, 3, 5),

('ED-A29', 'Cuestionario', 'Adopción', '10', '9', 'He invertido tiempo en explorar herramientas de IA avanzadas o especializadas y en transferir ese conocimiento a mi comunidad docente.', 'Multiple Choice (escala Likert A–E)', '["Nunca", "Rara vez (≤ 1/mes)", "Ocasional (2–3/mes)", "Casi siempre", "Muy frecuente (diaria)"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', now(), null, '["Productividad", "Aplicación"]'::jsonb, 3, 5),

('ED-A30', 'Cuestionario', 'Adopción', '10', '9', 'Trabajo coordinadamente con otros actores (orientación, coordinación académica, TIC) para alinear el uso de IA con los objetivos del centro educativo.', 'Multiple Choice (escala Likert A–E)', '["Nunca", "Rara vez (≤ 1/mes)", "Ocasional (2–3/mes)", "Casi siempre", "Muy frecuente (diaria)"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', now(), null, '["Aplicación"]'::jsonb, 3, 5);

-- CONOCIMIENTO - Rol 9
INSERT INTO "public"."preguntas" ("codigo", "section", "bloque", "area_id", "exclusivo_rol_id", "texto", "tipo", "opciones", "locale", "peso", "escala", "scoring", "created_at", "respuesta_correcta", "dimension", "exclusivo_nivel_id", "dificultad") VALUES
('ED-C1', 'Cuestionario', 'Conocimiento', '10', '9', '¿Cuál de las siguientes opciones describe mejor qué es la inteligencia artificial (IA) aplicada a la educación?', 'Multiple Choice (una respuesta)', '["Cualquier programa de computador usado en la escuela.", "Tecnología que imita ciertas capacidades humanas (como analizar texto o imágenes) para apoyar procesos educativos.", "Únicamente robots físicos que reemplazan docentes.", "Cualquier video o presentación usada en clase."]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', now(), 'Tecnología que imita ciertas capacidades humanas (como analizar texto o imágenes) para apoyar procesos educativos.', '["Conocimiento", "Aplicación"]'::jsonb, 3, 1),

('ED-C2', 'Cuestionario', 'Conocimiento', '10', '9', 'Un ejemplo sencillo de uso de IA por un docente es…', 'Multiple Choice (una respuesta)', '["Escribir todos los exámenes a mano.", "Usar un chatbot para generar ideas de actividades para una clase.", "Proyectar una película en el aula.", "Imprimir una guía que encontró en un libro."]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', now(), 'Usar un chatbot para generar ideas de actividades para una clase.', '["Conocimiento", "Aplicación"]'::jsonb, 3, 1),

('ED-C3', 'Cuestionario', 'Conocimiento', '10', '9', '¿Cuál es un riesgo básico al usar IA con información de estudiantes?', 'Multiple Choice (una respuesta)', '["Que los estudiantes aprendan más rápido.", "Que la IA escriba demasiado rápido.", "Compartir datos personales sin protección adecuada.", "Que los estudiantes hagan más preguntas."]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', now(), 'Compartir datos personales sin protección adecuada.', '["Conocimiento", "Estrategia", "Aplicación"]'::jsonb, 3, 1),

('ED-C4', 'Cuestionario', 'Conocimiento', '10', '9', '¿Qué afirmación es más adecuada sobre la relación entre IA y docentes?', 'Multiple Choice (una respuesta)', '["La IA reemplazará completamente a los docentes.", "La IA es solo una moda y pronto desaparecerá.", "La IA puede apoyar al docente, pero no reemplaza su rol pedagógico y humano.", "La IA decide sola qué deben aprender los estudiantes."]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', now(), 'La IA puede apoyar al docente, pero no reemplaza su rol pedagógico y humano.', '["Conocimiento"]'::jsonb, 3, 1),

('ED-C5', 'Cuestionario', 'Conocimiento', '10', '9', 'Si un docente copia y pega directamente una actividad generada por IA sin revisarla, el principal problema es que…', 'Multiple Choice (una respuesta)', '["La actividad no tendrá imágenes.", "Podría contener errores, sesgos o no ajustarse al contexto de sus estudiantes.", "La actividad no será lo suficientemente larga.", "Los estudiantes dejarán de preguntar."]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', now(), 'Podría contener errores, sesgos o no ajustarse al contexto de sus estudiantes.', '["Conocimiento"]'::jsonb, 3, 1),

('ED-C6', 'Cuestionario', 'Conocimiento', '10', '9', '¿Qué inversión mínima suele requerir empezar a usar IA en la docencia?', 'Multiple Choice (una respuesta)', '["Siempre comprar hardware muy costoso.", "Solo aprender a formular buenas instrucciones (prompts) y usar herramientas básicas disponibles.", "Contratar un equipo de programadores.", "Instalar robots en todas las aulas."]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', now(), 'Solo aprender a formular buenas instrucciones (prompts) y usar herramientas básicas disponibles.', '["Inversión", "Conocimiento"]'::jsonb, 3, 1),

('ED-C7', 'Cuestionario', 'Conocimiento', '10', '9', '¿Cuál de estas tareas es más adecuada para un primer uso de IA por parte de un docente?', 'Multiple Choice (una respuesta)', '["Delegar toda la calificación de exámenes sin supervisión.", "Pedir a la IA ideas de preguntas para un cuestionario que luego revisaré.", "Solicitar a la IA que ponga calificaciones finales de la asignatura.", "Dejar que la IA responda preguntas de los padres sin supervisión."]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', now(), 'Pedir a la IA ideas de preguntas para un cuestionario que luego revisaré.', '["Conocimiento", "Aplicación"]'::jsonb, 3, 2),

('ED-C8', 'Cuestionario', 'Conocimiento', '10', '9', '¿Qué es un ''prompt'' en el contexto de IA generativa?', 'Multiple Choice (una respuesta)', '["El sistema de calificaciones de la escuela.", "El texto o instrucción que damos a la IA para que genere una respuesta.", "Un tipo de examen estandarizado.", "Un dispositivo físico que guarda las notas."]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', now(), 'El texto o instrucción que damos a la IA para que genere una respuesta.', '["Conocimiento"]'::jsonb, 3, 2),

('ED-C9', 'Cuestionario', 'Conocimiento', '10', '9', 'Si usas IA para generar un texto que mostrarás a tus estudiantes, ¿qué deberías hacer primero?', 'Multiple Choice (una respuesta)', '["Copiarlo tal cual sin leerlo.", "Revisar contenido, nivel de dificultad y adecuación cultural.", "Pedir al estudiante que lo revise por ti.", "Publicarlo en redes sociales."]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', now(), 'Revisar contenido, nivel de dificultad y adecuación cultural.', '["Conocimiento"]'::jsonb, 3, 2),

('ED-C10', 'Cuestionario', 'Conocimiento', '10', '9', '¿Cuál de estas afirmaciones describe mejor una limitación de la IA generativa?', 'Multiple Choice (una respuesta)', '["Siempre dice la verdad.", "Puede inventar información que suena creíble pero es incorrecta.", "Solo funciona si hay un docente presente.", "Solo sirve para materias de ciencias."]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', now(), 'Puede inventar información que suena creíble pero es incorrecta.', '["Conocimiento"]'::jsonb, 3, 2),

('ED-C11', 'Cuestionario', 'Conocimiento', '10', '9', 'En términos de inversión, ¿qué es lo más razonable para un docente que inicia con IA?', 'Multiple Choice (una respuesta)', '["Empezar con herramientas gratuitas o de prueba aprobadas por su institución.", "Pagar licencias costosas sin evaluar su utilidad.", "Esperar a que los estudiantes compren las herramientas.", "No usar nada hasta que exista una sola plataforma oficial mundial."]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', now(), 'Empezar con herramientas gratuitas o de prueba aprobadas por su institución.', '["Inversión", "Conocimiento"]'::jsonb, 3, 2),

('ED-C12', 'Cuestionario', 'Conocimiento', '10', '9', '¿Qué rol debería seguir teniendo el docente aunque use IA en su curso?', 'Multiple Choice (una respuesta)', '["Ser solo un observador pasivo.", "Ser la persona que decide objetivos, actividades y criterios de evaluación.", "Dejar todas las decisiones a la IA.", "Solo gestionar la disciplina del aula."]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', now(), 'Ser la persona que decide objetivos, actividades y criterios de evaluación.', '["Conocimiento"]'::jsonb, 3, 2),

('ED-C13', 'Cuestionario', 'Conocimiento', '10', '9', '¿Cuál de las siguientes es una buena práctica al usar IA para diferenciar actividades según el nivel de los estudiantes?', 'Multiple Choice (una respuesta)', '["Generar una sola actividad y usarla para todo el grupo.", "Pedir a la IA que proponga actividades en niveles básico, intermedio y avanzado, y ajustar después.", "Pedir a la IA que asigne automáticamente las actividades sin intervención del docente.", "Dejar que los estudiantes elijan cualquier actividad generada por la IA."]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', now(), 'Pedir a la IA que proponga actividades en niveles básico, intermedio y avanzado, y ajustar después.', '["Conocimiento"]'::jsonb, 3, 3),

('ED-C14', 'Cuestionario', 'Conocimiento', '10', '9', 'Al usar IA para retroalimentar trabajos escritos, ¿qué debería hacer el docente?', 'Multiple Choice (una respuesta)', '["Copiar la retroalimentación de la IA sin leerla.", "Revisar, adaptar el tono y complementar con comentarios propios.", "Pedir a la IA que dé retroalimentación solo con emojis.", "Enviar la retroalimentación sin tomar en cuenta los criterios de evaluación."]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', now(), 'Revisar, adaptar el tono y complementar con comentarios propios.', '["Conocimiento"]'::jsonb, 3, 3),

('ED-C15', 'Cuestionario', 'Conocimiento', '10', '9', '¿Qué describe mejor el uso de IA para analítica de aprendizaje?', 'Multiple Choice (una respuesta)', '["Herramientas que solo cuentan la asistencia.", "Sistemas que procesan datos de desempeño para identificar patrones y apoyar decisiones pedagógicas.", "Plataformas para chatear con estudiantes sin supervisión.", "Cualquier hoja de cálculo manual."]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', now(), 'Sistemas que procesan datos de desempeño para identificar patrones y apoyar decisiones pedagógicas.', '["Conocimiento", "Aplicación"]'::jsonb, 3, 3),

('ED-C16', 'Cuestionario', 'Conocimiento', '10', '9', 'Si la IA sugiere una calificación diferente a la que el docente considera justa, ¿qué debería primar?', 'Multiple Choice (una respuesta)', '["La calificación de la IA siempre.", "La calificación del docente, considerando criterios y evidencias.", "Lo que opine el estudiante únicamente.", "Lo que diga la mayoría del curso."]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', now(), 'La calificación del docente, considerando criterios y evidencias.', '["Conocimiento"]'::jsonb, 3, 3),

('ED-C17', 'Cuestionario', 'Conocimiento', '10', '9', 'En términos de inversión, ¿cuál es una estrategia adecuada al usar varias herramientas de IA?', 'Multiple Choice (una respuesta)', '["Probar muchas herramientas a la vez sin evaluar su impacto.", "Priorizar 1–2 herramientas que aporten más valor a tu asignatura y dominarlas.", "Cambiar de herramienta cada semana.", "Usar solo las que recomiendan los estudiantes."]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', now(), 'Priorizar 1–2 herramientas que aporten más valor a tu asignatura y dominarlas.', '["Inversión", "Conocimiento", "Estrategia", "Aplicación"]'::jsonb, 3, 3),

('ED-C18', 'Cuestionario', 'Conocimiento', '10', '9', '¿Cuál es un criterio clave para decidir si una actividad con IA realmente mejora el aprendizaje?', 'Multiple Choice (una respuesta)', '["Si la IA genera contenido bonito.", "Si reduce la participación del docente.", "Si hay evidencia de que los estudiantes comprenden mejor y participan más.", "Si requiere muchos dispositivos costosos."]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', now(), 'Si hay evidencia de que los estudiantes comprenden mejor y participan más.', '["Conocimiento"]'::jsonb, 3, 3),

('ED-C19', 'Cuestionario', 'Conocimiento', '10', '9', 'Al diseñar una secuencia didáctica que integra IA, ¿qué es fundamental definir primero?', 'Multiple Choice (una respuesta)', '["La herramienta de IA más novedosa.", "Los objetivos de aprendizaje y criterios de éxito.", "El dispositivo que usarán los estudiantes.", "El número de preguntas que generará la IA."]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', now(), 'Los objetivos de aprendizaje y criterios de éxito.', '["Conocimiento"]'::jsonb, 3, 4),

('ED-C20', 'Cuestionario', 'Conocimiento', '10', '9', 'Un uso estratégicamente sólido de IA para evaluación formativa sería…', 'Multiple Choice (una respuesta)', '["Dejar que la IA decida la calificación final.", "Usar IA para generar preguntas rápidas y ajustar la clase según los resultados.", "Utilizar IA solo para decorar las presentaciones.", "Pedir a la IA que responda los exámenes por los estudiantes."]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', now(), 'Usar IA para generar preguntas rápidas y ajustar la clase según los resultados.', '["Conocimiento", "Aplicación"]'::jsonb, 3, 4),

('ED-C21', 'Cuestionario', 'Conocimiento', '10', '9', 'En analítica de aprendizaje asistida por IA, una práctica responsable es…', 'Multiple Choice (una respuesta)', '["Compartir públicamente todos los datos de los estudiantes.", "Usar datos anonimizados cuando sea posible y comunicar el propósito de su uso.", "Recolectar la mayor cantidad de datos posible sin informar.", "Ignorar las políticas institucionales de privacidad."]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', now(), 'Usar datos anonimizados cuando sea posible y comunicar el propósito de su uso.', '["Conocimiento", "Aplicación"]'::jsonb, 3, 4),

('ED-C22', 'Cuestionario', 'Conocimiento', '10', '9', 'En términos de productividad, ¿qué ventaja ofrece automatizar con IA ciertas tareas administrativas?', 'Multiple Choice (una respuesta)', '["Eliminar toda la planificación docente.", "Liberar tiempo para dedicarlo a retroalimentación de mayor calidad y acompañamiento.", "Aumentar el número de informes aunque nadie los lea.", "Evitar cualquier interacción directa con estudiantes."]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', now(), 'Liberar tiempo para dedicarlo a retroalimentación de mayor calidad y acompañamiento.', '["Productividad", "Conocimiento"]'::jsonb, 3, 4),

('ED-C23', 'Cuestionario', 'Conocimiento', '10', '9', 'Si tu institución dispone de un presupuesto limitado, ¿qué enfoque de inversión en IA es más razonable?', 'Multiple Choice (una respuesta)', '["Comprar muchas licencias sin capacitación docente.", "Priorizar herramientas alineadas al currículo y acompañarlas con formación.", "Adquirir solo herramientas de marketing.", "Depender de lo que traigan los estudiantes en sus dispositivos."]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', now(), 'Priorizar herramientas alineadas al currículo y acompañarlas con formación.', '["Inversión", "Conocimiento"]'::jsonb, 3, 4),

('ED-C24', 'Cuestionario', 'Conocimiento', '10', '9', '¿Qué elemento es clave para diseñar actividades con IA que promuevan pensamiento crítico?', 'Multiple Choice (una respuesta)', '["Pedir a la IA todas las respuestas correctas y darlas a los estudiantes.", "Diseñar tareas donde los estudiantes deban cuestionar, comparar y mejorar las respuestas de la IA.", "Prohibir que los estudiantes evalúen lo que genera la IA.", "Centrarse solo en tareas repetitivas."]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', now(), 'Diseñar tareas donde los estudiantes deban cuestionar, comparar y mejorar las respuestas de la IA.', '["Conocimiento"]'::jsonb, 3, 4),

('ED-C25', 'Cuestionario', 'Conocimiento', '10', '9', 'En el diseño de proyectos innovadores con IA en el aula, una práctica clave de liderazgo docente es…', 'Multiple Choice (una respuesta)', '["Implementar cambios sin informar a nadie.", "Co-diseñar experiencias con otros docentes y compartir evidencias de impacto.", "Dejar que solo los estudiantes decidan cómo usar IA.", "Centrarse únicamente en herramientas de moda."]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', now(), 'Co-diseñar experiencias con otros docentes y compartir evidencias de impacto.', '["Conocimiento"]'::jsonb, 3, 5),

('ED-C26', 'Cuestionario', 'Conocimiento', '10', '9', 'Al proponer lineamientos institucionales de uso de IA, ¿qué aspecto no puede faltar?', 'Multiple Choice (una respuesta)', '["Número de dispositivos en el aula.", "Criterios de uso responsable, privacidad, autoría y equidad de acceso.", "La marca de la herramienta preferida por el docente.", "La duración de los recreos."]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', now(), 'Criterios de uso responsable, privacidad, autoría y equidad de acceso.', '["Conocimiento", "Aplicación"]'::jsonb, 3, 5),

('ED-C27', 'Cuestionario', 'Conocimiento', '10', '9', 'Para evaluar el impacto de una innovación con IA en la docencia, es recomendable…', 'Multiple Choice (una respuesta)', '["Basarse solo en opiniones anecdóticas.", "Combinar datos cuantitativos (resultados, uso) y cualitativos (percepciones de docentes y estudiantes).", "Contar solo la cantidad de veces que se usó la IA.", "Considerar solo la satisfacción del docente."]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', now(), 'Combinar datos cuantitativos (resultados, uso) y cualitativos (percepciones de docentes y estudiantes).', '["Conocimiento"]'::jsonb, 3, 5),

('ED-C28', 'Cuestionario', 'Conocimiento', '10', '9', 'En términos de inversión y sostenibilidad, ¿qué indicador es más relevante al escalar proyectos con IA?', 'Multiple Choice (una respuesta)', '["Que la herramienta sea la más publicitada.", "Que el costo y el tiempo de capacitación sean sostenibles para la institución.", "Que solo requiera dispositivos costosos.", "Que dependa de una sola persona experta."]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', now(), 'Que el costo y el tiempo de capacitación sean sostenibles para la institución.', '["Inversión", "Conocimiento"]'::jsonb, 3, 5),

('ED-C29', 'Cuestionario', 'Conocimiento', '10', '9', 'Respecto a la colaboración con otros docentes en IA, un enfoque maduro es…', 'Multiple Choice (una respuesta)', '["Guardar las buenas prácticas para uno mismo.", "Documentar experiencias, guías y materiales, y compartirlos con el equipo docente.", "Dejar que cada quien experimente sin compartir resultados.", "Usar IA solo para la propia asignatura."]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', now(), 'Documentar experiencias, guías y materiales, y compartirlos con el equipo docente.', '["Conocimiento"]'::jsonb, 3, 5),

('ED-C30', 'Cuestionario', 'Conocimiento', '10', '9', 'Para promover pensamiento crítico en los estudiantes frente a la IA, el docente innovador debería…', 'Multiple Choice (una respuesta)', '["Pedirles que acepten todo lo que dice la IA.", "Diseñar actividades donde comparen varias fuentes (IA, libros, artículos) y justifiquen qué información es más confiable.", "Prohibir cualquier uso de IA.", "Fomentar solo tareas automatizadas."]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', now(), 'Diseñar actividades donde comparen varias fuentes (IA, libros, artículos) y justifiquen qué información es más confiable.', '["Conocimiento"]'::jsonb, 3, 5);
