-- ============================================================================
-- PREGUNTAS PARA GERENTE DE MARKETING
-- ============================================================================
-- Rol incluido:
--   - Rol ID 4: Gerente de Marketing (area_id: 3, nivel_id: 3)
-- ============================================================================

-- ============================================================================
-- ROL 4: Gerente de Marketing
-- ============================================================================

-- ADOPCIÓN - Rol 4
INSERT INTO "public"."preguntas" ("codigo", "section", "bloque", "area_id", "exclusivo_rol_id", "texto", "tipo", "opciones", "locale", "peso", "escala", "scoring", "created_at", "respuesta_correcta", "dimension", "exclusivo_nivel_id", "dificultad") VALUES
('GM-A1', 'Cuestionario', 'Adopción', '3', '4', 'En tu rol de Gerente de Marketing, ¿con qué frecuencia usas IA para generar ideas iniciales de copys o mensajes de campaña?', 'Multiple Choice (escala Likert A–E)', '["Nunca", "Rara vez (≤ 1/mes)", "Ocasional (2–3/mes)", "Frecuente (semanal)", "Muy frecuente (diaria)"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', now(), null, '["Aplicación"]'::jsonb, 3, 1),

('GM-A2', 'Cuestionario', 'Adopción', '3', '4', '¿Con qué frecuencia usas IA para generar variantes de anuncios o emails que luego pruebas en campañas (A/B o multivariantes)?', 'Multiple Choice (escala Likert A–E)', '["Nunca", "Rara vez (≤ 1/mes)", "Ocasional (2–3/mes)", "Frecuente (semanal)", "Muy frecuente (diaria)"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', now(), null, '["Aplicación"]'::jsonb, 3, 1),

('GM-A3', 'Cuestionario', 'Adopción', '3', '4', '¿Con qué frecuencia utilizas IA para diseñar journeys automatizados (por ejemplo, secuencias de emails o mensajes según comportamiento del usuario)?', 'Multiple Choice (escala Likert A–E)', '["Nunca", "Rara vez (≤ 1/mes)", "Ocasional (2–3/mes)", "Frecuente (semanal)", "Muy frecuente (diaria)"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', now(), null, '["Aplicación"]'::jsonb, 3, 1),

('GM-A4', 'Cuestionario', 'Adopción', '3', '4', '¿Con qué frecuencia utilizas modelos predictivos (churn, next-best-offer, propensión) para definir prioridades de campañas o segmentos?', 'Multiple Choice (escala Likert A–E)', '["Nunca", "Rara vez (≤ 1/mes)", "Ocasional (2–3/mes)", "Frecuente (semanal)", "Muy frecuente (diaria)"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', now(), null, '["Aplicación"]'::jsonb, 3, 1),

('GM-A5', 'Cuestionario', 'Adopción', '3', '4', '¿Con qué frecuencia participas en decisiones de portafolio de inversión (proyectos, herramientas, datos) relacionadas con IA en marketing a nivel organizacional?', 'Multiple Choice (escala Likert A–E)', '["Nunca", "Rara vez (≤ 1/mes)", "Ocasional (2–3/mes)", "Frecuente (semanal)", "Muy frecuente (diaria)"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', now(), null, '["Aplicación", "Inversión"]'::jsonb, 3, 1),

('GM-A6', 'Cuestionario', 'Adopción', '3', '4', '¿Con qué frecuencia utilizas IA para resumir información (por ejemplo, reportes largos o artículos de marketing) y así ahorrar tiempo?', 'Multiple Choice (escala Likert A–E)', '["Nunca", "Rara vez (≤ 1/mes)", "Ocasional (2–3/mes)", "Frecuente (semanal)", "Muy frecuente (diaria)"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', now(), null, '["Productividad", "Aplicación"]'::jsonb, 3, 1),

('GM-A7', 'Cuestionario', 'Adopción', '3', '4', '¿Con qué frecuencia revisas indicadores clave (aperturas, clics, conversiones) para juzgar si la IA está aportando mejoras en tus campañas?', 'Multiple Choice (escala Likert A–E)', '["Nunca", "Rara vez (≤ 1/mes)", "Ocasional (2–3/mes)", "Frecuente (semanal)", "Muy frecuente (diaria)"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', now(), null, '["Aplicación"]'::jsonb, 3, 2),

('GM-A8', 'Cuestionario', 'Adopción', '3', '4', '¿Con qué frecuencia revisas junto con tu equipo los insights generados por IA sobre desempeño de campañas para decidir ajustes?', 'Multiple Choice (escala Likert A–E)', '["Nunca", "Rara vez (≤ 1/mes)", "Ocasional (2–3/mes)", "Frecuente (semanal)", "Muy frecuente (diaria)"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', now(), null, '["Productividad", "Aplicación"]'::jsonb, 3, 2),

('GM-A9', 'Cuestionario', 'Adopción', '3', '4', '¿Qué tan frecuente es que ajustes reglas y umbrales de automatización (por ejemplo, triggers de journeys) basándote en análisis de IA y feedback del negocio?', 'Multiple Choice (escala Likert A–E)', '["Nunca", "Rara vez (≤ 1/mes)", "Ocasional (2–3/mes)", "Frecuente (semanal)", "Muy frecuente (diaria)"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', now(), null, '["Aplicación"]'::jsonb, 3, 2),

('GM-A10', 'Cuestionario', 'Adopción', '3', '4', '¿Qué tan frecuente es que definas (o revises) una hoja de ruta de casos de uso de IA en marketing priorizada por impacto, complejidad y alineación estratégica?', 'Multiple Choice (escala Likert A–E)', '["Nunca", "Rara vez (≤ 1/mes)", "Ocasional (2–3/mes)", "Frecuente (semanal)", "Muy frecuente (diaria)"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', now(), null, '["Aplicación"]'::jsonb, 3, 2),

('GM-A11', 'Cuestionario', 'Adopción', '3', '4', '¿Qué tan frecuente es que revises y edites críticamente el contenido que genera la IA antes de usarlo en una campaña?', 'Multiple Choice (escala Likert A–E)', '["Nunca", "Rara vez (≤ 1/mes)", "Ocasional (2–3/mes)", "Frecuente (semanal)", "Muy frecuente (diaria)"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', now(), null, '["Aplicación"]'::jsonb, 3, 2),

('GM-A12', 'Cuestionario', 'Adopción', '3', '4', '¿Qué tan frecuente es que ajustes tus prompts o instrucciones a la IA según el desempeño observado en campañas?', 'Multiple Choice (escala Likert A–E)', '["Nunca", "Rara vez (≤ 1/mes)", "Ocasional (2–3/mes)", "Frecuente (semanal)", "Muy frecuente (diaria)"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', now(), null, '["Aplicación"]'::jsonb, 3, 2),

('GM-A13', 'Cuestionario', 'Adopción', '3', '4', '¿Qué tan frecuente es que combines datos de distintas fuentes (web, CRM, redes sociales) para alimentar modelos o funcionalidades de IA que usas en marketing?', 'Multiple Choice (escala Likert A–E)', '["Nunca", "Rara vez (≤ 1/mes)", "Ocasional (2–3/mes)", "Frecuente (semanal)", "Muy frecuente (diaria)"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', now(), null, '["Aplicación"]'::jsonb, 3, 3),

('GM-A14', 'Cuestionario', 'Adopción', '3', '4', '¿Con qué frecuencia trabajas junto con TI/Data para priorizar backlog de casos de uso de IA en marketing según impacto y complejidad?', 'Multiple Choice (escala Likert A–E)', '["Nunca", "Rara vez (≤ 1/mes)", "Ocasional (2–3/mes)", "Frecuente (semanal)", "Muy frecuente (diaria)"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', now(), null, '["Estrategia", "Aplicación"]'::jsonb, 3, 3),

('GM-A15', 'Cuestionario', 'Adopción', '3', '4', '¿Con qué frecuencia trabajas con otras áreas (TI, Data, Legal, Finanzas) para establecer políticas y estándares corporativos sobre uso de IA en la relación con clientes?', 'Multiple Choice (escala Likert A–E)', '["Nunca", "Rara vez (≤ 1/mes)", "Ocasional (2–3/mes)", "Frecuente (semanal)", "Muy frecuente (diaria)"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', now(), null, '["Aplicación"]'::jsonb, 3, 3),

('GM-A16', 'Cuestionario', 'Adopción', '3', '4', '¿Con qué frecuencia compartes con tu equipo ejemplos o aprendizajes obtenidos usando IA en tareas de marketing?', 'Multiple Choice (escala Likert A–E)', '["Nunca", "Rara vez (≤ 1/mes)", "Ocasional (2–3/mes)", "Frecuente (semanal)", "Muy frecuente (diaria)"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', now(), null, '["Aplicación"]'::jsonb, 3, 3),

('GM-A17', 'Cuestionario', 'Adopción', '3', '4', '¿Con qué frecuencia involucras a tu equipo (o agencia) para revisar y mejorar el contenido generado por IA antes de lanzarlo?', 'Multiple Choice (escala Likert A–E)', '["Nunca", "Rara vez (≤ 1/mes)", "Ocasional (2–3/mes)", "Frecuente (semanal)", "Muy frecuente (diaria)"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', now(), null, '["Aplicación"]'::jsonb, 3, 3),

('GM-A18', 'Cuestionario', 'Adopción', '3', '4', '¿Con qué frecuencia coordinas con Ventas / Atención al cliente para validar si las recomendaciones o mensajes generados por IA son coherentes con lo que ellos observan en el cliente?', 'Multiple Choice (escala Likert A–E)', '["Nunca", "Rara vez (≤ 1/mes)", "Ocasional (2–3/mes)", "Frecuente (semanal)", "Muy frecuente (diaria)"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', now(), null, '["Aplicación"]'::jsonb, 3, 3),

('GM-A19', 'Cuestionario', 'Adopción', '3', '4', '¿Qué tan frecuente es que revises y comuniques al equipo de marketing el impacto de la IA (por ejemplo, mejoras en conversión, reducción de CPA) como parte del seguimiento de resultados?', 'Multiple Choice (escala Likert A–E)', '["Nunca", "Rara vez (≤ 1/mes)", "Ocasional (2–3/mes)", "Frecuente (semanal)", "Muy frecuente (diaria)"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', now(), null, '["Productividad", "Aplicación"]'::jsonb, 3, 4),

('GM-A20', 'Cuestionario', 'Adopción', '3', '4', '¿Qué tan frecuente es que comuniques al comité de dirección o C-Level resultados y aprendizajes de los programas de IA en marketing (incluyendo riesgos y próximos pasos)?', 'Multiple Choice (escala Likert A–E)', '["Nunca", "Rara vez (≤ 1/mes)", "Ocasional (2–3/mes)", "Frecuente (semanal)", "Muy frecuente (diaria)"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', now(), null, '["Productividad", "Estrategia"]'::jsonb, 3, 4),

('GM-A21', 'Cuestionario', 'Adopción', '3', '4', '¿Con qué frecuencia has reservado tiempo específico (aunque sea breve) para explorar nuevas funciones de IA en las herramientas de marketing que ya usas (p.ej. IA en plataformas de anuncios o email)?', 'Multiple Choice (escala Likert A–E)', '["Nunca", "Rara vez (≤ 1/mes)", "Ocasional (2–3/mes)", "Frecuente (semanal)", "Muy frecuente (diaria)"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', now(), null, '["Productividad", "Aplicación"]'::jsonb, 3, 4),

('GM-A22', 'Cuestionario', 'Adopción', '3', '4', '¿Con qué frecuencia destinas parte del presupuesto o tiempo del equipo para probar nuevas funciones de IA en tus plataformas de marketing actuales?', 'Multiple Choice (escala Likert A–E)', '["Nunca", "Rara vez (≤ 1/mes)", "Ocasional (2–3/mes)", "Frecuente (semanal)", "Muy frecuente (diaria)"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', now(), null, '["Productividad", "Aplicación", "Inversión"]'::jsonb, 3, 4),

('GM-A23', 'Cuestionario', 'Adopción', '3', '4', '¿Qué tan frecuente es que ajustes presupuestos o distribución de inversión en campañas en función de recomendaciones o simulaciones generadas por IA?', 'Multiple Choice (escala Likert A–E)', '["Nunca", "Rara vez (≤ 1/mes)", "Ocasional (2–3/mes)", "Frecuente (semanal)", "Muy frecuente (diaria)"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', now(), null, '["Inversión"]'::jsonb, 3, 4),

('GM-A24', 'Cuestionario', 'Adopción', '3', '4', '¿Con qué frecuencia defines o actualizas lineamientos internos (guidelines) sobre cuándo y cómo usar IA en campañas (tono, datos permitidos, revisiones)?', 'Multiple Choice (escala Likert A–E)', '["Nunca", "Rara vez (≤ 1/mes)", "Ocasional (2–3/mes)", "Frecuente (semanal)", "Muy frecuente (diaria)"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', now(), null, '["Aplicación"]'::jsonb, 3, 4),

('GM-A25', 'Cuestionario', 'Adopción', '3', '4', '¿Con qué frecuencia promueves iniciativas de formación para que el resto del equipo de marketing desarrolle capacidades en IA (talleres, laboratorios, guías de uso)?', 'Multiple Choice (escala Likert A–E)', '["Nunca", "Rara vez (≤ 1/mes)", "Ocasional (2–3/mes)", "Frecuente (semanal)", "Muy frecuente (diaria)"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', now(), null, '["Estrategia", "Aplicación"]'::jsonb, 3, 5),

('GM-A26', 'Cuestionario', 'Adopción', '3', '4', '¿Con qué frecuencia consideras posibles riesgos (reputacionales, legales, de privacidad) cuando decides si usar o no IA en una pieza de comunicación?', 'Multiple Choice (escala Likert A–E)', '["Nunca", "Rara vez (≤ 1/mes)", "Ocasional (2–3/mes)", "Frecuente (semanal)", "Muy frecuente (diaria)"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', now(), null, '["Estrategia"]'::jsonb, 3, 5),

('GM-A27', 'Cuestionario', 'Adopción', '3', '4', '¿Con qué frecuencia verificas que el uso de IA en tus campañas respete las políticas internas de marca y privacidad de la organización?', 'Multiple Choice (escala Likert A–E)', '["Nunca", "Rara vez (≤ 1/mes)", "Ocasional (2–3/mes)", "Frecuente (semanal)", "Muy frecuente (diaria)"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', now(), null, '["Estrategia", "Aplicación"]'::jsonb, 3, 5),

('GM-A28', 'Cuestionario', 'Adopción', '3', '4', '¿Con qué frecuencia revisas posibles sesgos (por ejemplo, exclusión de ciertos segmentos) al analizar los resultados que la IA impulsa en tus campañas?', 'Multiple Choice (escala Likert A–E)', '["Nunca", "Rara vez (≤ 1/mes)", "Ocasional (2–3/mes)", "Frecuente (semanal)", "Muy frecuente (diaria)"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', now(), null, '["Productividad", "Estrategia"]'::jsonb, 3, 5),

('GM-A29', 'Cuestionario', 'Adopción', '3', '4', '¿Qué tan frecuente es que asignes explícitamente parte del presupuesto de marketing a iniciativas de IA (pilotos, herramientas, capacitación del equipo)?', 'Multiple Choice (escala Likert A–E)', '["Nunca", "Rara vez (≤ 1/mes)", "Ocasional (2–3/mes)", "Frecuente (semanal)", "Muy frecuente (diaria)"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', now(), null, '["Estrategia", "Aplicación", "Inversión"]'::jsonb, 3, 5),

('GM-A30', 'Cuestionario', 'Adopción', '3', '4', '¿Qué tan frecuente es que incluyas explícitamente criterios éticos (sesgos, transparencia, impacto en clientes vulnerables) en la evaluación y priorización de proyectos de IA en marketing?', 'Multiple Choice (escala Likert A–E)', '["Nunca", "Rara vez (≤ 1/mes)", "Ocasional (2–3/mes)", "Frecuente (semanal)", "Muy frecuente (diaria)"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', now(), null, '["Estrategia"]'::jsonb, 3, 5);

-- CONOCIMIENTO - Rol 4
INSERT INTO "public"."preguntas" ("codigo", "section", "bloque", "area_id", "exclusivo_rol_id", "texto", "tipo", "opciones", "locale", "peso", "escala", "scoring", "created_at", "respuesta_correcta", "dimension", "exclusivo_nivel_id", "dificultad") VALUES
('GM-C1', 'Cuestionario', 'Conocimiento', '3', '4', '¿Cuál de las siguientes opciones es un ejemplo sencillo de uso de IA generativa en marketing?', 'Multiple Choice (una respuesta)', '["Programar manualmente la fecha de envío de un email.", "Exportar un reporte desde Excel sin modificarlo.", "Usar una herramienta de IA para proponer copys iniciales de un anuncio.", "Cambiar el logo de la marca una vez al año."]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', now(), 'Usar una herramienta de IA para proponer copys iniciales de un anuncio.', '["Conocimiento", "Aplicación"]'::jsonb, 3, 1),

('GM-C2', 'Cuestionario', 'Conocimiento', '3', '4', '¿Cuál de las siguientes tareas se beneficia más de usar IA de forma táctica en campañas digitales?', 'Multiple Choice (una respuesta)', '["Firmar contratos con proveedores.", "Generar varias versiones de anuncios para pruebas A/B.", "Registrar manualmente todas las visitas en un cuaderno.", "Definir la estructura legal de la empresa."]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', now(), 'Generar varias versiones de anuncios para pruebas A/B.', '["Conocimiento"]'::jsonb, 3, 1),

('GM-C3', 'Cuestionario', 'Conocimiento', '3', '4', '¿Cuál de estas descripciones refleja mejor un uso integrado de IA en campañas de marketing digital?', 'Multiple Choice (una respuesta)', '["Usar IA solo para corregir ortografía.", "Generar copys aislados sin considerar datos ni segmentación.", "Emplear IA para segmentar audiencias, generar creatividades y sugerir optimizaciones sobre el desempeño de las campañas.", "Usar IA únicamente para traducir textos."]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', now(), 'Emplear IA para segmentar audiencias, generar creatividades y sugerir optimizaciones sobre el desempeño de las campañas.', '["Conocimiento", "Aplicación"]'::jsonb, 3, 1),

('GM-C4', 'Cuestionario', 'Conocimiento', '3', '4', '¿Qué caracteriza a un enfoque data-driven de IA en marketing?', 'Multiple Choice (una respuesta)', '["Decidir campañas solo por intuición.", "Basar decisiones en datos estructurados y no estructurados, usando IA para generar insights y acciones medibles.", "Ignorar los datos históricos.", "Elegir canales al azar."]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', now(), 'Basar decisiones en datos estructurados y no estructurados, usando IA para generar insights y acciones medibles.', '["Conocimiento"]'::jsonb, 3, 1),

('GM-C5', 'Cuestionario', 'Conocimiento', '3', '4', '¿Qué diferencia clave existe entre probar IA en campañas aisladas y tener una estrategia de IA en marketing?', 'Multiple Choice (una respuesta)', '["No hay diferencia significativa.", "La estrategia implica definir objetivos, roadmap de casos de uso, inversión, gobierno de datos y métricas claras de impacto.", "La estrategia solo significa usar la herramienta más cara.", "Probar IA en campañas aisladas siempre es suficiente."]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', now(), 'La estrategia implica definir objetivos, roadmap de casos de uso, inversión, gobierno de datos y métricas claras de impacto.', '["Conocimiento", "Estrategia"]'::jsonb, 3, 1),

('GM-C6', 'Cuestionario', 'Conocimiento', '3', '4', '¿Qué describe mejor a un asistente de texto basado en IA (como un chatbot generativo)?', 'Multiple Choice (una respuesta)', '["Un programa que solo corrige la ortografía de los textos.", "Una herramienta capaz de generar y reformular textos a partir de instrucciones en lenguaje natural.", "Únicamente un traductor de idiomas sin otras capacidades.", "Un sistema que solo envía emails en horarios programados."]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', now(), 'Una herramienta capaz de generar y reformular textos a partir de instrucciones en lenguaje natural.', '["Conocimiento"]'::jsonb, 3, 1),

('GM-C7', 'Cuestionario', 'Conocimiento', '3', '4', '¿Qué describe mejor el uso de IA en una plataforma de email marketing?', 'Multiple Choice (una respuesta)', '["Solo permite programar envíos en una fecha.", "Puede sugerir asuntos y contenidos personalizados según datos básicos de los suscriptores.", "Solo cambia el color de los botones.", "Solo mide aperturas sin dar recomendaciones."]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', now(), 'Puede sugerir asuntos y contenidos personalizados según datos básicos de los suscriptores.', '["Conocimiento", "Aplicación"]'::jsonb, 3, 2),

('GM-C8', 'Cuestionario', 'Conocimiento', '3', '4', '¿Qué ventaja aporta la IA al análisis de resultados de campaña?', 'Multiple Choice (una respuesta)', '["Permite evitar medir resultados.", "Resume datos y sugiere patrones que pueden pasar desapercibidos al análisis manual.", "Elimina la necesidad de tener objetivos de campaña.", "Garantiza resultados positivos."]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', now(), 'Resume datos y sugiere patrones que pueden pasar desapercibidos al análisis manual.', '["Conocimiento", "Productividad"]'::jsonb, 3, 2),

('GM-C9', 'Cuestionario', 'Conocimiento', '3', '4', '¿Qué es un modelo de propensión a compra (propensity model) aplicado al marketing?', 'Multiple Choice (una respuesta)', '["Un análisis del diseño del logo.", "Un modelo que estima la probabilidad de que un cliente realice una compra, usado para priorizar acciones.", "Un reporte de ventas del último año.", "Una encuesta de satisfacción."]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', now(), 'Un modelo que estima la probabilidad de que un cliente realice una compra, usado para priorizar acciones.', '["Conocimiento", "Aplicación"]'::jsonb, 3, 2),

('GM-C10', 'Cuestionario', 'Conocimiento', '3', '4', '¿Qué describe mejor un modelo de atribución asistido por IA?', 'Multiple Choice (una respuesta)', '["Un modelo que asigna todo el valor al último clic.", "Un enfoque que usa IA para estimar la contribución de cada punto de contacto en el journey a la conversión.", "Un reporte manual de impresiones.", "Un esquema que solo mira visitas al sitio web."]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', now(), 'Un enfoque que usa IA para estimar la contribución de cada punto de contacto en el journey a la conversión.', '["Conocimiento"]'::jsonb, 3, 2),

('GM-C11', 'Cuestionario', 'Conocimiento', '3', '4', '¿Cuál de estas actividades es más apropiada para comenzar a usar IA en el trabajo de marketing?', 'Multiple Choice (una respuesta)', '["Definir la estrategia anual sin consultar datos.", "Redactar todos los copys solo a mano.", "Usar IA como primer borrador de copys y luego ajustarlos al tono de la marca.", "Reemplazar completamente al equipo creativo por IA."]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', now(), 'Usar IA como primer borrador de copys y luego ajustarlos al tono de la marca.', '["Conocimiento"]'::jsonb, 3, 2),

('GM-C12', 'Cuestionario', 'Conocimiento', '3', '4', '¿Cuál de estos indicadores es más relevante para evaluar el impacto de una acción de IA táctico en email marketing?', 'Multiple Choice (una respuesta)', '["Número de empleados del área de marketing.", "Tasa de apertura y clics de los emails.", "Precio de la competencia.", "Color del logo de la marca."]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', now(), 'Tasa de apertura y clics de los emails.', '["Conocimiento"]'::jsonb, 3, 2),

('GM-C13', 'Cuestionario', 'Conocimiento', '3', '4', '¿Qué es un journey automatizado en marketing apoyado en IA?', 'Multiple Choice (una respuesta)', '["Una sola campaña enviada el mismo día a todos los clientes.", "Un flujo de interacciones (emails, mensajes, anuncios) que se dispara según el comportamiento del cliente, optimizado con IA.", "Un informe mensual de ventas.", "Una campaña de branding sin segmentación."]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', now(), 'Un flujo de interacciones (emails, mensajes, anuncios) que se dispara según el comportamiento del cliente, optimizado con IA.', '["Conocimiento"]'::jsonb, 3, 3),

('GM-C14', 'Cuestionario', 'Conocimiento', '3', '4', '¿Cuál de las siguientes es una aplicación típica de IA en orquestación de customer journeys?', 'Multiple Choice (una respuesta)', '["Enviar el mismo email cada mes a toda la base.", "Ajustar dinámicamente el siguiente mensaje y canal según respuestas previas y probabilidad de conversión.", "Desactivar todos los mensajes automatizados.", "Cambiar el color del logo cada semana."]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', now(), 'Ajustar dinámicamente el siguiente mensaje y canal según respuestas previas y probabilidad de conversión.', '["Conocimiento", "Aplicación"]'::jsonb, 3, 3),

('GM-C15', 'Cuestionario', 'Conocimiento', '3', '4', '¿Cuál es una responsabilidad clave de un Estratega de IA en Marketing en relación con otras áreas (TI, Legal, Finanzas)?', 'Multiple Choice (una respuesta)', '["Definir campañas sin consultar a nadie.", "Alinear objetivos de IA con capacidades técnicas, marcos legales y presupuestos disponibles.", "Delegar toda la responsabilidad a TI.", "Desvincular los proyectos de IA de la estrategia corporativa."]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', now(), 'Alinear objetivos de IA con capacidades técnicas, marcos legales y presupuestos disponibles.', '["Conocimiento"]'::jsonb, 3, 3),

('GM-C16', 'Cuestionario', 'Conocimiento', '3', '4', '¿Qué beneficio inmediato puede aportar la IA a un Gerente de Marketing con poca experiencia en estas herramientas?', 'Multiple Choice (una respuesta)', '["Eliminar la necesidad de analizar resultados de campaña.", "Facilitar ideas y ejemplos que aceleren la generación de campañas.", "Decidir automáticamente el presupuesto del área.", "Garantizar que todas las campañas serán exitosas."]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', now(), 'Facilitar ideas y ejemplos que aceleren la generación de campañas.', '["Conocimiento", "Aplicación"]'::jsonb, 3, 3),

('GM-C17', 'Cuestionario', 'Conocimiento', '3', '4', '¿Cuál es una buena práctica al usar IA para adaptar copys a diferentes segmentos?', 'Multiple Choice (una respuesta)', '["Usar el mismo mensaje para todos los segmentos.", "Ajustar las instrucciones a la IA describiendo claramente a cada segmento.", "Pedir siempre el mensaje más genérico posible.", "Generar un texto y confiar en que la IA lo segmentará sola."]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', now(), 'Ajustar las instrucciones a la IA describiendo claramente a cada segmento.', '["Conocimiento"]'::jsonb, 3, 3),

('GM-C18', 'Cuestionario', 'Conocimiento', '3', '4', '¿Cuál de los siguientes es un ejemplo de uso de IA para personalización en marketing?', 'Multiple Choice (una respuesta)', '["Enviar el mismo asunto de email a toda la base.", "Ajustar manualmente cada email uno por uno.", "Utilizar IA para adaptar el mensaje y las recomendaciones de producto según comportamiento previo del usuario.", "Enviar un email por año a todos los clientes."]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', now(), 'Utilizar IA para adaptar el mensaje y las recomendaciones de producto según comportamiento previo del usuario.', '["Conocimiento", "Aplicación"]'::jsonb, 3, 3),

('GM-C19', 'Cuestionario', 'Conocimiento', '3', '4', '¿Qué rol debería tener un Gerente de Marketing al introducir IA avanzada en el área?', 'Multiple Choice (una respuesta)', '["Delegar todo a TI sin involucrarse.", "Liderar la definición de casos de uso, coordinar con Data/TI y alinear al equipo de marketing.", "Ignorar los proyectos de IA.", "Pedir solo más presupuesto sin un plan claro."]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', now(), 'Liderar la definición de casos de uso, coordinar con Data/TI y alinear al equipo de marketing.', '["Conocimiento"]'::jsonb, 3, 4),

('GM-C20', 'Cuestionario', 'Conocimiento', '3', '4', '¿Qué papel tienen los marcos éticos y de gobernanza en una estrategia de IA en marketing?', 'Multiple Choice (una respuesta)', '["Son irrelevantes para marketing.", "Ayudan a asegurar que el uso de IA sea transparente, justo, explicable y cumpla regulaciones.", "Solo se aplican a áreas de TI.", "Se limitan a diseño gráfico."]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', now(), 'Ayudan a asegurar que el uso de IA sea transparente, justo, explicable y cumpla regulaciones.', '["Conocimiento", "Estrategia"]'::jsonb, 3, 4),

('GM-C21', 'Cuestionario', 'Conocimiento', '3', '4', '¿Cuál es una buena práctica cuando se usa IA para redactar correos de marketing?', 'Multiple Choice (una respuesta)', '["Enviar siempre el texto tal cual lo genera la IA.", "Revisar el contenido generado, adaptarlo al tono de marca y validar con el equipo.", "Pedir a la IA que copie literalmente correos de la competencia.", "No informar al equipo sobre el uso de IA."]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', now(), 'Revisar el contenido generado, adaptarlo al tono de marca y validar con el equipo.', '["Conocimiento"]'::jsonb, 3, 4),

('GM-C22', 'Cuestionario', 'Conocimiento', '3', '4', '¿Qué riesgo táctico existe al depender demasiado de IA para generar contenido sin involucrar al equipo?', 'Multiple Choice (una respuesta)', '["Mejorar demasiado la productividad.", "Reducir la coherencia de la voz de marca y desconectar al equipo del proceso creativo.", "Disminuir el costo de agencia.", "Incrementar automáticamente el engagement."]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', now(), 'Reducir la coherencia de la voz de marca y desconectar al equipo del proceso creativo.', '["Conocimiento", "Estrategia", "Aplicación"]'::jsonb, 3, 4),

('GM-C23', 'Cuestionario', 'Conocimiento', '3', '4', '¿Qué riesgo estratégico existe al integrar IA en campañas sin coordinar con Ventas u otras áreas?', 'Multiple Choice (una respuesta)', '["Mejorar la alineación del mensaje.", "Generar ofertas o mensajes no alineados con disponibilidad, pricing o promesas al cliente.", "Reducir las ventas.", "Disminuir la carga de trabajo del equipo comercial."]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', now(), 'Generar ofertas o mensajes no alineados con disponibilidad, pricing o promesas al cliente.', '["Conocimiento", "Estrategia"]'::jsonb, 3, 4),

('GM-C24', 'Cuestionario', 'Conocimiento', '3', '4', '¿Qué riesgo conlleva automatizar demasiadas decisiones de marketing con IA sin supervisión humana?', 'Multiple Choice (una respuesta)', '["Incrementar la transparencia.", "Posibles decisiones no alineadas con la estrategia o valores de la marca, difíciles de explicar.", "Reducir la velocidad de respuesta.", "Mejorar automáticamente la reputación."]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', now(), 'Posibles decisiones no alineadas con la estrategia o valores de la marca, difíciles de explicar.', '["Conocimiento", "Productividad", "Estrategia"]'::jsonb, 3, 4),

('GM-C25', 'Cuestionario', 'Conocimiento', '3', '4', '¿Qué indicador es más apropiado para evaluar el ROI de un programa de IA en marketing a nivel estratégico?', 'Multiple Choice (una respuesta)', '["Número de reuniones internas sobre IA.", "Percepción subjetiva del equipo.", "Impacto agregado en ingresos, margen o eficiencia de marketing frente a escenarios sin IA.", "Número de herramientas compradas."]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', now(), 'Impacto agregado en ingresos, margen o eficiencia de marketing frente a escenarios sin IA.', '["Conocimiento", "Inversión"]'::jsonb, 3, 5),

('GM-C26', 'Cuestionario', 'Conocimiento', '3', '4', '¿Qué riesgo básico existe al usar IA para generar mensajes de marketing sin supervisión?', 'Multiple Choice (una respuesta)', '["Reducir el tiempo de trabajo.", "Incrementar la creatividad.", "Publicar mensajes que no respeten valores de la marca o normativas.", "Mejorar de forma automática el ROI."]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', now(), 'Publicar mensajes que no respeten valores de la marca o normativas.', '["Conocimiento", "Estrategia"]'::jsonb, 3, 5),

('GM-C27', 'Cuestionario', 'Conocimiento', '3', '4', '¿Qué aspecto ético es importante considerar al usar IA con datos de clientes?', 'Multiple Choice (una respuesta)', '["Que la IA genere textos más largos.", "Que el resultado se vea moderno.", "Respetar la privacidad, consentimientos y regulaciones al usar datos para personalización.", "Usar siempre todos los datos posibles sin restricciones."]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', now(), 'Respetar la privacidad, consentimientos y regulaciones al usar datos para personalización.', '["Conocimiento", "Aplicación"]'::jsonb, 3, 5),

('GM-C28', 'Cuestionario', 'Conocimiento', '3', '4', '¿Cuál de los siguientes aspectos es importante monitorizar al usar IA para optimizar campañas en plataformas de anuncios?', 'Multiple Choice (una respuesta)', '["Solo el número de impresiones.", "Gasto, ROAS/CPA y si los anuncios cumplen políticas de contenido y segmentación.", "Únicamente el número de likes.", "Solo la cantidad de anuncios generados."]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', now(), 'Gasto, ROAS/CPA y si los anuncios cumplen políticas de contenido y segmentación.', '["Conocimiento", "Productividad"]'::jsonb, 3, 5),

('GM-C29', 'Cuestionario', 'Conocimiento', '3', '4', '¿Qué aspecto es clave al evaluar inversiones en herramientas de IA para marketing?', 'Multiple Choice (una respuesta)', '["Solo que la interfaz sea bonita.", "Alineación con objetivos de negocio, integración con datos existentes y potencial de ROI.", "Que sea la herramienta de moda.", "Que solo un proveedor la recomiende."]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', now(), 'Alineación con objetivos de negocio, integración con datos existentes y potencial de ROI.', '["Conocimiento", "Aplicación"]'::jsonb, 3, 5),

('GM-C30', 'Cuestionario', 'Conocimiento', '3', '4', '¿Qué riesgo estratégico existe si la organización depende de pocos perfiles clave para todos los proyectos de IA en marketing?', 'Multiple Choice (una respuesta)', '["Mayor resiliencia del sistema.", "Dependencia crítica (single point of failure) y dificultad para escalar capacidades.", "Reducción del costo de formación.", "Mejora automática del clima laboral."]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', now(), 'Dependencia crítica (single point of failure) y dificultad para escalar capacidades.', '["Conocimiento", "Estrategia"]'::jsonb, 3, 5);
