-- ============================================================================
-- PREGUNTAS PARA ANALISTA/ESPECIALISTA TI
-- ============================================================================
-- Rol incluido:
--   - Rol ID 7: Analista/Especialista TI (area_id: 9, nivel_id: 4)
-- ============================================================================

-- ============================================================================
-- ROL 7: Analista/Especialista TI
-- ============================================================================

-- ADOPCIÓN - Rol 7
INSERT INTO "public"."preguntas" ("codigo", "section", "bloque", "area_id", "exclusivo_rol_id", "texto", "tipo", "opciones", "locale", "peso", "escala", "scoring", "created_at", "respuesta_correcta", "dimension", "exclusivo_nivel_id", "dificultad") VALUES
('ATI-A1', 'Cuestionario', 'Adopción', '9', '7', '¿Con qué frecuencia usas IA para redactar o mejorar respuestas a tickets de usuarios?', 'Multiple Choice (escala Likert A–E)', '["Nunca", "Rara vez (≤ 1/mes)", "Ocasional (2–3/mes)", "Frecuente (semanal)", "Muy frecuente (diaria)"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', now(), null, '["Aplicación"]'::jsonb, 4, 1),

('ATI-A2', 'Cuestionario', 'Adopción', '9', '7', '¿Con qué frecuencia usas IA para traducir mensajes técnicos a un lenguaje comprensible para usuarios finales?', 'Multiple Choice (escala Likert A–E)', '["Nunca", "Rara vez (≤ 1/mes)", "Ocasional (2–3/mes)", "Frecuente (semanal)", "Muy frecuente (diaria)"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', now(), null, '["Aplicación"]'::jsonb, 4, 1),

('ATI-A3', 'Cuestionario', 'Adopción', '9', '7', '¿Con qué frecuencia consultas IA para que te explique conceptos básicos de TI que necesitas recordar (protocolos, comandos, definiciones)?', 'Multiple Choice (escala Likert A–E)', '["Nunca", "Rara vez (≤ 1/mes)", "Ocasional (2–3/mes)", "Frecuente (semanal)", "Muy frecuente (diaria)"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', now(), null, '["Aplicación"]'::jsonb, 4, 1),

('ATI-A4', 'Cuestionario', 'Adopción', '9', '7', '¿Con qué frecuencia usas IA para resumir correos o documentos relacionados con incidentes o cambios?', 'Multiple Choice (escala Likert A–E)', '["Nunca", "Rara vez (≤ 1/mes)", "Ocasional (2–3/mes)", "Frecuente (semanal)", "Muy frecuente (diaria)"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', now(), null, '["Aplicación"]'::jsonb, 4, 1),

('ATI-A5', 'Cuestionario', 'Adopción', '9', '7', '¿Con qué frecuencia conversas con IA sobre ideas sencillas para mejorar tu forma de atender tickets (plantillas, mensajes tipo)?', 'Multiple Choice (escala Likert A–E)', '["Nunca", "Rara vez (≤ 1/mes)", "Ocasional (2–3/mes)", "Frecuente (semanal)", "Muy frecuente (diaria)"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', now(), null, '["Aplicación"]'::jsonb, 4, 1),

('ATI-A6', 'Cuestionario', 'Adopción', '9', '7', '¿Con qué frecuencia dedicas tiempo personal de trabajo (por ejemplo, 30–60 minutos al mes) a explorar nuevas herramientas de IA recomendadas por tu organización o colegas?', 'Multiple Choice (escala Likert A–E)', '["Nunca", "Rara vez (≤ 1/mes)", "Ocasional (2–3/mes)", "Frecuente (semanal)", "Muy frecuente (diaria)"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', now(), null, '["Productividad", "Aplicación"]'::jsonb, 4, 1),

('ATI-A7', 'Cuestionario', 'Adopción', '9', '7', '¿Con qué frecuencia usas IA para proponer textos de artículos de base de conocimiento a partir de tickets resueltos?', 'Multiple Choice (escala Likert A–E)', '["Nunca", "Rara vez (≤ 1/mes)", "Ocasional (2–3/mes)", "Frecuente (semanal)", "Muy frecuente (diaria)"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', now(), null, '["Aplicación"]'::jsonb, 4, 2),

('ATI-A8', 'Cuestionario', 'Adopción', '9', '7', '¿Con qué frecuencia usas IA para preparar explicaciones de cambios o incidentes para usuarios de negocio (no técnicos)?', 'Multiple Choice (escala Likert A–E)', '["Nunca", "Rara vez (≤ 1/mes)", "Ocasional (2–3/mes)", "Frecuente (semanal)", "Muy frecuente (diaria)"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', now(), null, '["Aplicación"]'::jsonb, 4, 2),

('ATI-A9', 'Cuestionario', 'Adopción', '9', '7', '¿Con qué frecuencia comparas tus resultados (scripts, correos, documentación) con y sin IA para evaluar si realmente mejora tu trabajo?', 'Multiple Choice (escala Likert A–E)', '["Nunca", "Rara vez (≤ 1/mes)", "Ocasional (2–3/mes)", "Frecuente (semanal)", "Muy frecuente (diaria)"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', now(), null, '["Productividad"]'::jsonb, 4, 2),

('ATI-A10', 'Cuestionario', 'Adopción', '9', '7', '¿Con qué frecuencia discutes con tu líder o compañeros en qué tareas de TI vale la pena invertir tiempo en IA?', 'Multiple Choice (escala Likert A–E)', '["Nunca", "Rara vez (≤ 1/mes)", "Ocasional (2–3/mes)", "Frecuente (semanal)", "Muy frecuente (diaria)"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', now(), null, '["Productividad"]'::jsonb, 4, 2),

('ATI-A11', 'Cuestionario', 'Adopción', '9', '7', '¿Con qué frecuencia revisas que lo generado por la IA cumpla las políticas de seguridad y privacidad de la organización?', 'Multiple Choice (escala Likert A–E)', '["Nunca", "Rara vez (≤ 1/mes)", "Ocasional (2–3/mes)", "Frecuente (semanal)", "Muy frecuente (diaria)"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', now(), null, '["Estrategia"]'::jsonb, 4, 2),

('ATI-A12', 'Cuestionario', 'Adopción', '9', '7', '¿Con qué frecuencia utilizas IA para planificar tu día (priorizar tickets, agrupar tareas, estimar tiempos)?', 'Multiple Choice (escala Likert A–E)', '["Nunca", "Rara vez (≤ 1/mes)", "Ocasional (2–3/mes)", "Frecuente (semanal)", "Muy frecuente (diaria)"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', now(), null, '["Estrategia", "Productividad", "Aplicación"]'::jsonb, 4, 2),

('ATI-A13', 'Cuestionario', 'Adopción', '9', '7', '¿Con qué frecuencia usas IA para generar o refinar scripts (PowerShell, Bash, Python) que apoyan tareas de administración de sistemas o redes?', 'Multiple Choice (escala Likert A–E)', '["Nunca", "Rara vez (≤ 1/mes)", "Ocasional (2–3/mes)", "Frecuente (semanal)", "Muy frecuente (diaria)"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', now(), null, '["Aplicación"]'::jsonb, 4, 3),

('ATI-A14', 'Cuestionario', 'Adopción', '9', '7', '¿Con qué frecuencia usas IA para analizar o resumir logs de aplicaciones, sistemas o seguridad?', 'Multiple Choice (escala Likert A–E)', '["Nunca", "Rara vez (≤ 1/mes)", "Ocasional (2–3/mes)", "Frecuente (semanal)", "Muy frecuente (diaria)"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', now(), null, '["Estrategia", "Aplicación"]'::jsonb, 4, 3),

('ATI-A15', 'Cuestionario', 'Adopción', '9', '7', '¿Con qué frecuencia propones a tu equipo pequeñas mejoras de proceso basadas en lo que has probado con IA (por ejemplo, plantillas de respuesta, runbooks)?', 'Multiple Choice (escala Likert A–E)', '["Nunca", "Rara vez (≤ 1/mes)", "Ocasional (2–3/mes)", "Frecuente (semanal)", "Muy frecuente (diaria)"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', now(), null, '["Aplicación"]'::jsonb, 4, 3),

('ATI-A16', 'Cuestionario', 'Adopción', '9', '7', '¿Con qué frecuencia colaboras con otros Analistas TI para compartir prompts o buenas prácticas de uso de IA en el soporte?', 'Multiple Choice (escala Likert A–E)', '["Nunca", "Rara vez (≤ 1/mes)", "Ocasional (2–3/mes)", "Frecuente (semanal)", "Muy frecuente (diaria)"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', now(), null, '["Aplicación"]'::jsonb, 4, 3),

('ATI-A17', 'Cuestionario', 'Adopción', '9', '7', '¿Con qué frecuencia tienes en cuenta el costo de licencias o consumo de IA (tokens, uso por usuario) cuando decides qué tanto usar una herramienta?', 'Multiple Choice (escala Likert A–E)', '["Nunca", "Rara vez (≤ 1/mes)", "Ocasional (2–3/mes)", "Frecuente (semanal)", "Muy frecuente (diaria)"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', now(), null, '["Inversión", "Aplicación"]'::jsonb, 4, 3),

('ATI-A18', 'Cuestionario', 'Adopción', '9', '7', '¿Con qué frecuencia revisas con tu líder o equipo si los automatismos con IA que usan (en ITSM, monitoreo, etc.) están funcionando como se esperaba?', 'Multiple Choice (escala Likert A–E)', '["Nunca", "Rara vez (≤ 1/mes)", "Ocasional (2–3/mes)", "Frecuente (semanal)", "Muy frecuente (diaria)"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', now(), null, '["Aplicación"]'::jsonb, 4, 3),

('ATI-A19', 'Cuestionario', 'Adopción', '9', '7', '¿Con qué frecuencia diseñas o mantienes playbooks/runbooks donde IA participa (por ejemplo, sugiriendo causas y pasos de resolución)?', 'Multiple Choice (escala Likert A–E)', '["Nunca", "Rara vez (≤ 1/mes)", "Ocasional (2–3/mes)", "Frecuente (semanal)", "Muy frecuente (diaria)"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', now(), null, '["Aplicación"]'::jsonb, 4, 4),

('ATI-A20', 'Cuestionario', 'Adopción', '9', '7', '¿Con qué frecuencia conectas IA con fuentes de datos de monitoreo (logs, métricas) para automatizar análisis o alertas (aunque sea en pruebas)?', 'Multiple Choice (escala Likert A–E)', '["Nunca", "Rara vez (≤ 1/mes)", "Ocasional (2–3/mes)", "Frecuente (semanal)", "Muy frecuente (diaria)"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', now(), null, '["Productividad", "Aplicación"]'::jsonb, 4, 4),

('ATI-A21', 'Cuestionario', 'Adopción', '9', '7', '¿Con qué frecuencia lideras o co-lideras discusiones técnicas sobre qué flujos de trabajo deberían automatizarse con IA y cuáles no?', 'Multiple Choice (escala Likert A–E)', '["Nunca", "Rara vez (≤ 1/mes)", "Ocasional (2–3/mes)", "Frecuente (semanal)", "Muy frecuente (diaria)"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', now(), null, '["Productividad"]'::jsonb, 4, 4),

('ATI-A22', 'Cuestionario', 'Adopción', '9', '7', '¿Con qué frecuencia revisas datos concretos (KPIs, métricas) para evaluar si un flujo con IA justifica la inversión (licencias, tiempo de mantenimiento)?', 'Multiple Choice (escala Likert A–E)', '["Nunca", "Rara vez (≤ 1/mes)", "Ocasional (2–3/mes)", "Frecuente (semanal)", "Muy frecuente (diaria)"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', now(), null, '["Inversión", "Productividad", "Aplicación"]'::jsonb, 4, 4),

('ATI-A23', 'Cuestionario', 'Adopción', '9', '7', '¿Con qué frecuencia ajustas prompts, parámetros o reglas para reducir errores o comportamientos no deseados de la IA en tus flujos?', 'Multiple Choice (escala Likert A–E)', '["Nunca", "Rara vez (≤ 1/mes)", "Ocasional (2–3/mes)", "Frecuente (semanal)", "Muy frecuente (diaria)"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', now(), null, '["Aplicación"]'::jsonb, 4, 4),

('ATI-A24', 'Cuestionario', 'Adopción', '9', '7', '¿Con qué frecuencia compartes con otros equipos (por ejemplo, seguridad, desarrollo, negocio) lecciones aprendidas sobre el uso de IA en operaciones TI?', 'Multiple Choice (escala Likert A–E)', '["Nunca", "Rara vez (≤ 1/mes)", "Ocasional (2–3/mes)", "Frecuente (semanal)", "Muy frecuente (diaria)"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', now(), null, '["Estrategia", "Aplicación"]'::jsonb, 4, 4),

('ATI-A25', 'Cuestionario', 'Adopción', '9', '7', '¿Con qué frecuencia diseñas o participas en el diseño de arquitecturas de IA (por ejemplo, RAG sobre documentación de TI, AIOps avanzado) para tu organización?', 'Multiple Choice (escala Likert A–E)', '["Nunca", "Rara vez (≤ 1/mes)", "Ocasional (2–3/mes)", "Frecuente (semanal)", "Muy frecuente (diaria)"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', now(), null, '["Aplicación"]'::jsonb, 4, 5),

('ATI-A26', 'Cuestionario', 'Adopción', '9', '7', '¿Con qué frecuencia participas en la definición o revisión de políticas de uso de IA (datos permitidos, acceso, gobierno) desde tu perspectiva técnica de TI?', 'Multiple Choice (escala Likert A–E)', '["Nunca", "Rara vez (≤ 1/mes)", "Ocasional (2–3/mes)", "Frecuente (semanal)", "Muy frecuente (diaria)"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', now(), null, '["Aplicación"]'::jsonb, 4, 5),

('ATI-A27', 'Cuestionario', 'Adopción', '9', '7', '¿Con qué frecuencia colaboras con equipos de negocio o datos para priorizar casos de uso de IA según impacto en resultados (disponibilidad, SLA, experiencia de usuario)?', 'Multiple Choice (escala Likert A–E)', '["Nunca", "Rara vez (≤ 1/mes)", "Ocasional (2–3/mes)", "Frecuente (semanal)", "Muy frecuente (diaria)"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', now(), null, '["Estrategia", "Productividad", "Aplicación"]'::jsonb, 4, 5),

('ATI-A28', 'Cuestionario', 'Adopción', '9', '7', '¿Con qué frecuencia lideras o apoyas análisis de ROI (tiempo, costo, reducción de incidentes) para justificar o revisar inversiones en herramientas de IA para TI?', 'Multiple Choice (escala Likert A–E)', '["Nunca", "Rara vez (≤ 1/mes)", "Ocasional (2–3/mes)", "Frecuente (semanal)", "Muy frecuente (diaria)"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', now(), null, '["Inversión", "Productividad", "Aplicación"]'::jsonb, 4, 5),

('ATI-A29', 'Cuestionario', 'Adopción', '9', '7', '¿Con qué frecuencia compartes formaciones, talleres o guías para otros miembros del área TI sobre uso responsable y efectivo de IA?', 'Multiple Choice (escala Likert A–E)', '["Nunca", "Rara vez (≤ 1/mes)", "Ocasional (2–3/mes)", "Frecuente (semanal)", "Muy frecuente (diaria)"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', now(), null, '["Aplicación"]'::jsonb, 4, 5),

('ATI-A30', 'Cuestionario', 'Adopción', '9', '7', '¿Con qué frecuencia impulsas mejoras para que las soluciones de IA en TI incluyan monitoreo continuo de calidad, sesgos y errores?', 'Multiple Choice (escala Likert A–E)', '["Nunca", "Rara vez (≤ 1/mes)", "Ocasional (2–3/mes)", "Frecuente (semanal)", "Muy frecuente (diaria)"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', now(), null, '["Estrategia"]'::jsonb, 4, 5);

-- CONOCIMIENTO - Rol 7
INSERT INTO "public"."preguntas" ("codigo", "section", "bloque", "area_id", "exclusivo_rol_id", "texto", "tipo", "opciones", "locale", "peso", "escala", "scoring", "created_at", "respuesta_correcta", "dimension", "exclusivo_nivel_id", "dificultad") VALUES
('ATI-C1', 'Cuestionario', 'Conocimiento', '9', '7', 'En tu trabajo como Analista/Especialista TI, ¿cuál de las siguientes opciones describe mejor a una herramienta de IA generativa?', 'Multiple Choice (una respuesta)', '["Un sistema que solo ejecuta scripts estáticos escritos por el administrador.", "Un modelo capaz de generar texto, código o contenido nuevo a partir de instrucciones en lenguaje natural.", "Un sistema de tickets que asigna casos a un técnico según turnos fijos.", "Un antivirus que actualiza su firma de virus una vez al mes."]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', now(), 'Un modelo capaz de generar texto, código o contenido nuevo a partir de instrucciones en lenguaje natural.', '["Conocimiento"]'::jsonb, 4, 1),

('ATI-C2', 'Cuestionario', 'Conocimiento', '9', '7', '¿Cuál es un ejemplo adecuado de uso de IA en el soporte TI de primer nivel?', 'Multiple Choice (una respuesta)', '["Usar IA para decidir automáticamente despidos por bajo rendimiento.", "Usar IA para redactar un primer borrador de respuesta a un ticket complejo.", "Usar IA para desactivar sin revisión todas las cuentas marcadas como sospechosas.", "Usar IA para formatear discos duros sin respaldo."]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', now(), 'Usar IA para redactar un primer borrador de respuesta a un ticket complejo.', '["Conocimiento", "Aplicación"]'::jsonb, 4, 1),

('ATI-C3', 'Cuestionario', 'Conocimiento', '9', '7', 'Cuando pegas información de tickets en una herramienta de IA, ¿qué buena práctica básica deberías seguir?', 'Multiple Choice (una respuesta)', '["Incluir todos los datos personales para dar más contexto.", "Evitar datos sensibles o que permitan identificar a personas o clientes.", "Pegar credenciales completas para que la IA pueda probar conexiones.", "Subir archivos de configuración con claves de acceso sin enmascarar."]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', now(), 'Evitar datos sensibles o que permitan identificar a personas o clientes.', '["Conocimiento", "Aplicación"]'::jsonb, 4, 1),

('ATI-C4', 'Cuestionario', 'Conocimiento', '9', '7', '¿Cuál de estas tareas es razonable pedirle a un chatbot de IA dentro de tu rol de TI?', 'Multiple Choice (una respuesta)', '["Tomar decisiones finales sobre cambios en la infraestructura.", "Aprobar automáticamente aumentos de presupuesto de licencias.", "Explicar en lenguaje sencillo el impacto de un incidente sobre los usuarios.", "Ajustar de forma autónoma las reglas del firewall en producción."]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', now(), 'Explicar en lenguaje sencillo el impacto de un incidente sobre los usuarios.', '["Conocimiento"]'::jsonb, 4, 1),

('ATI-C5', 'Cuestionario', 'Conocimiento', '9', '7', 'Una limitación frecuente de los modelos de IA generativa es que:', 'Multiple Choice (una respuesta)', '["Nunca cometen errores ortográficos.", "Siempre devuelven la verdad si el prompt es claro.", "Pueden “inventar” información que suena creíble pero es incorrecta.", "No pueden procesar texto en más de un idioma."]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', now(), 'Pueden “inventar” información que suena creíble pero es incorrecta.', '["Conocimiento"]'::jsonb, 4, 1),

('ATI-C6', 'Cuestionario', 'Conocimiento', '9', '7', 'En un sistema de tickets con funciones básicas de IA, ¿qué beneficio podrías esperar?', 'Multiple Choice (una respuesta)', '["Que la IA cambie la prioridad de todos los tickets sin criterio.", "Que la IA sugiera categorías o soluciones basadas en tickets similares anteriores.", "Que la IA desinstale software de los equipos sin aprobación.", "Que la IA bloquee a usuarios que abran muchos tickets."]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', now(), 'Que la IA sugiera categorías o soluciones basadas en tickets similares anteriores.', '["Conocimiento"]'::jsonb, 4, 1),

('ATI-C7', 'Cuestionario', 'Conocimiento', '9', '7', '¿Cuál es una diferencia clave entre una regla fija en un sistema de automatización y un modelo de IA?', 'Multiple Choice (una respuesta)', '["La IA solo ejecuta una instrucción predefinida.", "La IA puede aprender patrones a partir de datos, mientras que la regla fija no.", "La regla fija se adapta sola y la IA no.", "No hay diferencia relevante en TI."]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', now(), 'La IA puede aprender patrones a partir de datos, mientras que la regla fija no.', '["Conocimiento"]'::jsonb, 4, 2),

('ATI-C8', 'Cuestionario', 'Conocimiento', '9', '7', '¿Qué tipo de información es generalmente más segura usar con IA en una organización típica?', 'Multiple Choice (una respuesta)', '["Listas de contraseñas de administradores.", "Datos de tarjetas de crédito.", "Textos ya públicos de la base de conocimiento de TI.", "Archivos de configuración sin anonimizar."]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', now(), 'Textos ya públicos de la base de conocimiento de TI.', '["Conocimiento", "Aplicación"]'::jsonb, 4, 2),

('ATI-C9', 'Cuestionario', 'Conocimiento', '9', '7', '¿Cuál es un buen ejemplo de uso de IA para documentación TI?', 'Multiple Choice (una respuesta)', '["Que la IA borre documentos antiguos sin autorización.", "Generar un primer borrador de un artículo de la base de conocimiento a partir de un ticket resuelto.", "Que la IA cambie automáticamente el procedimiento de recuperación ante desastres.", "Que la IA comparta documentación interna con cualquier usuario externo."]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', now(), 'Generar un primer borrador de un artículo de la base de conocimiento a partir de un ticket resuelto.', '["Conocimiento", "Aplicación"]'::jsonb, 4, 2),

('ATI-C10', 'Cuestionario', 'Conocimiento', '9', '7', 'Si tu organización tiene una política de uso de IA, ¿qué debería ser lo primero que hagas antes de usar una nueva herramienta?', 'Multiple Choice (una respuesta)', '["Usarla intensivamente y preguntar después.", "Compartir datos confidenciales para probar su precisión.", "Revisar la política de uso de IA y las restricciones de datos.", "Enviar los logs de producción completos al proveedor de IA."]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', now(), 'Revisar la política de uso de IA y las restricciones de datos.', '["Conocimiento", "Aplicación"]'::jsonb, 4, 2),

('ATI-C11', 'Cuestionario', 'Conocimiento', '9', '7', 'Desde la perspectiva de productividad, ¿qué indicador es más razonable para evaluar el impacto de IA en soporte TI?', 'Multiple Choice (una respuesta)', '["Número de memes generados con IA en el chat del equipo.", "Reducción del tiempo promedio de resolución de ciertos tipos de tickets.", "Número de prompts escritos por día.", "Cantidad de texto generado por IA, sin importar su utilidad."]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', now(), 'Reducción del tiempo promedio de resolución de ciertos tipos de tickets.', '["Conocimiento", "Productividad"]'::jsonb, 4, 2),

('ATI-C12', 'Cuestionario', 'Conocimiento', '9', '7', 'En términos de inversión de tiempo, ¿qué enfoque tiene más sentido para un Analista TI que recién empieza a usar IA?', 'Multiple Choice (una respuesta)', '["Dedicar unas horas al mes a pruebas guiadas y revisar resultados con alguien con más experiencia.", "Dejar todo su trabajo normal para aprender IA durante semanas.", "No invertir tiempo hasta que IA sea obligatorio.", "Trabajar solo con herramientas no aprobadas por la organización."]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', now(), 'Dedicar unas horas al mes a pruebas guiadas y revisar resultados con alguien con más experiencia.', '["Inversión", "Conocimiento", "Productividad"]'::jsonb, 4, 2),

('ATI-C13', 'Cuestionario', 'Conocimiento', '9', '7', 'En una herramienta ITSM con IA, ¿qué funcionalidad es más típica?', 'Multiple Choice (una respuesta)', '["IA que cambia la infraestructura sin aprobación humana.", "IA que sugiere clasificación y prioridad de tickets basándose en casos históricos.", "IA que modifica salarios del equipo según número de tickets.", "IA que se instala sola en todos los servidores sin permiso."]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', now(), 'IA que sugiere clasificación y prioridad de tickets basándose en casos históricos.', '["Conocimiento"]'::jsonb, 4, 3),

('ATI-C14', 'Cuestionario', 'Conocimiento', '9', '7', 'Cuando usas IA para generar un script de PowerShell o Bash, ¿qué paso es imprescindible antes de usarlo en producción?', 'Multiple Choice (una respuesta)', '["Confiar si la IA responde con seguridad.", "Ejecutarlo directamente en servidores productivos.", "Revisar y probar el script en un entorno de pruebas controlado.", "Compartir el script sin probarlo con todo el equipo."]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', now(), 'Revisar y probar el script en un entorno de pruebas controlado.', '["Conocimiento"]'::jsonb, 4, 3),

('ATI-C15', 'Cuestionario', 'Conocimiento', '9', '7', '¿Cuál de las siguientes es una buena práctica al usar IA para analizar logs?', 'Multiple Choice (una respuesta)', '["Enviar logs con datos personales sin anonimizar.", "Pedirle a la IA que “invente” logs de ejemplo para producción.", "Definir claramente qué patrón o error quieres identificar y revisar críticamente las sugerencias.", "Aceptar cualquier patrón sugerido sin validación."]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', now(), 'Definir claramente qué patrón o error quieres identificar y revisar críticamente las sugerencias.', '["Conocimiento"]'::jsonb, 4, 3),

('ATI-C16', 'Cuestionario', 'Conocimiento', '9', '7', 'Desde el punto de vista estratégico, ¿qué es razonable esperar de IA en operaciones TI?', 'Multiple Choice (una respuesta)', '["Que elimine completamente la necesidad de personal de TI.", "Que aporte datos y resúmenes para mejorar la toma de decisiones sobre priorización y capacidad.", "Que tome decisiones finales sobre presupuestos de infraestructura.", "Que garantice cero incidentes de seguridad."]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', now(), 'Que aporte datos y resúmenes para mejorar la toma de decisiones sobre priorización y capacidad.', '["Conocimiento"]'::jsonb, 4, 3),

('ATI-C17', 'Cuestionario', 'Conocimiento', '9', '7', 'Al elegir entre dos herramientas de IA para TI, ¿qué criterio de inversión tiene más sentido para un colaborador que participa en la evaluación?', 'Multiple Choice (una respuesta)', '["Qué herramienta tiene la interfaz más colorida.", "Qué herramienta tiene más “moda” en redes sociales.", "La combinación de costo (licencias/tiempo) vs. ahorro de esfuerzo y mejora de calidad.", "La que genera respuestas más largas."]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', now(), 'La combinación de costo (licencias/tiempo) vs. ahorro de esfuerzo y mejora de calidad.', '["Inversión", "Conocimiento", "Aplicación"]'::jsonb, 4, 3),

('ATI-C18', 'Cuestionario', 'Conocimiento', '9', '7', '¿Qué riesgo aparece cuando un equipo de TI se apoya demasiado en IA para generar soluciones?', 'Multiple Choice (una respuesta)', '["Que el equipo desarrolle más criterio técnico.", "Que se pierda comprensión profunda y se acepten soluciones sin entenderlas.", "Que se reduzca el número de tickets resueltos.", "Que disminuya la documentación."]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', now(), 'Que se pierda comprensión profunda y se acepten soluciones sin entenderlas.', '["Estrategia", "Conocimiento", "Aplicación"]'::jsonb, 4, 3),

('ATI-C19', 'Cuestionario', 'Conocimiento', '9', '7', '¿Qué describe mejor el concepto de AIOps en el contexto de TI?', 'Multiple Choice (una respuesta)', '["Uso de IA solo para marketing.", "Aplicación de IA y analítica a datos de operaciones TI (logs, eventos, métricas) para detectar patrones y automatizar acciones.", "Una nueva versión de ITIL sin IA.", "Un simple script manual de monitoreo."]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', now(), 'Aplicación de IA y analítica a datos de operaciones TI (logs, eventos, métricas) para detectar patrones y automatizar acciones.', '["Conocimiento"]'::jsonb, 4, 4),

('ATI-C20', 'Cuestionario', 'Conocimiento', '9', '7', 'En un flujo de trabajo donde IA sugiere causas probables de incidentes, ¿qué rol debería jugar el Analista TI?', 'Multiple Choice (una respuesta)', '["Aceptar siempre la primera sugerencia.", "Validar la hipótesis de la IA con evidencia y experiencia antes de aplicar cambios.", "Dejar que la IA aplique directamente los cambios en producción.", "Ignorar las sugerencias y trabajar como antes."]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', now(), 'Validar la hipótesis de la IA con evidencia y experiencia antes de aplicar cambios.', '["Conocimiento"]'::jsonb, 4, 4),

('ATI-C21', 'Cuestionario', 'Conocimiento', '9', '7', 'Cuando integras IA con herramientas de monitoreo, ¿qué métrica ayuda más a evaluar el impacto en resultados operativos?', 'Multiple Choice (una respuesta)', '["Número de dashboards nuevos creados.", "Reducción de tiempo de detección y resolución de incidentes críticos.", "Cantidad de prompts usados al día.", "Número de logs enviados a la nube."]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', now(), 'Reducción de tiempo de detección y resolución de incidentes críticos.', '["Conocimiento", "Productividad", "Aplicación"]'::jsonb, 4, 4),

('ATI-C22', 'Cuestionario', 'Conocimiento', '9', '7', 'En términos de colaboración, ¿qué práctica es más efectiva al introducir IA en flujos de trabajo de TI?', 'Multiple Choice (una respuesta)', '["Diseñar el flujo solo y comunicarlo al final.", "Involucrar a soporte, redes, seguridad y negocio para revisar riesgos y beneficios antes de ponerlo en producción.", "Mantener en secreto los prompts para que nadie los copie.", "Pedir a cada área que diseñe su propia solución sin coordinación."]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', now(), 'Involucrar a soporte, redes, seguridad y negocio para revisar riesgos y beneficios antes de ponerlo en producción.', '["Conocimiento"]'::jsonb, 4, 4),

('ATI-C23', 'Cuestionario', 'Conocimiento', '9', '7', 'Si tu equipo evalúa invertir en una nueva plataforma de IA para operaciones TI, ¿en qué debería enfocar tu análisis como colaborador técnico?', 'Multiple Choice (una respuesta)', '["En si la interfaz es bonita.", "En compatibilidad con sistemas actuales, facilidad de integración y esfuerzo de mantenimiento.", "Solo en si usa el modelo de IA “más nuevo”.", "En si reemplaza la necesidad de procesos."]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', now(), 'En compatibilidad con sistemas actuales, facilidad de integración y esfuerzo de mantenimiento.', '["Conocimiento", "Aplicación"]'::jsonb, 4, 4),

('ATI-C24', 'Cuestionario', 'Conocimiento', '9', '7', 'Desde la perspectiva de riesgos, ¿qué es clave al diseñar flujos automatizados con IA?', 'Multiple Choice (una respuesta)', '["Permitir que IA ejecute cualquier acción que “parezca correcta”.", "Tener mecanismos de rollback, límites de acción y monitoreo de errores.", "No registrar qué hizo la IA para ahorrar espacio.", "No informar a nadie cuando la IA falle."]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', now(), 'Tener mecanismos de rollback, límites de acción y monitoreo de errores.', '["Estrategia", "Conocimiento"]'::jsonb, 4, 4),

('ATI-C25', 'Cuestionario', 'Conocimiento', '9', '7', 'En una arquitectura de IA tipo RAG (Retrieval-Augmented Generation) aplicada a documentación TI, ¿qué paso es central?', 'Multiple Choice (una respuesta)', '["Generar respuestas sin consultar ninguna fuente interna.", "Recuperar documentos relevantes de la base de conocimiento y usarlos como contexto para la respuesta.", "Borrar la documentación una vez consultada.", "Usar solo datos públicos de Internet."]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', now(), 'Recuperar documentos relevantes de la base de conocimiento y usarlos como contexto para la respuesta.', '["Conocimiento", "Aplicación"]'::jsonb, 4, 5),

('ATI-C26', 'Cuestionario', 'Conocimiento', '9', '7', '¿Cuál de estas afirmaciones sobre gobernanza de IA en TI es más adecuada?', 'Multiple Choice (una respuesta)', '["No es necesaria si los resultados “parecen correctos”.", "Solo importa la precisión, no quién puede usar la IA ni cómo.", "Debe incluir políticas de acceso, tipos de datos permitidos, monitoreo de uso y revisión de impactos.", "Solo se aplica a IA usada por el área de datos, no por TI."]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', now(), 'Debe incluir políticas de acceso, tipos de datos permitidos, monitoreo de uso y revisión de impactos.', '["Estrategia", "Conocimiento"]'::jsonb, 4, 5),

('ATI-C27', 'Cuestionario', 'Conocimiento', '9', '7', 'Al evaluar el ROI de una solución de AIOps, ¿qué combinación tiene más sentido?', 'Multiple Choice (una respuesta)', '["Costos de licencia + reducción en horas-hombre de diagnóstico + disminución de incidentes críticos no detectados.", "Número de dashboards creados + número de prompts.", "Likes en publicaciones internas sobre IA.", "Horas invertidas en entrenar al equipo sin medir resultados."]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', now(), 'Costos de licencia + reducción en horas-hombre de diagnóstico + disminución de incidentes críticos no detectados.', '["Inversión", "Conocimiento"]'::jsonb, 4, 5),

('ATI-C28', 'Cuestionario', 'Conocimiento', '9', '7', 'En términos de colaboración interdisciplinaria, ¿qué rol puede jugar un Especialista TI enfocado en IA?', 'Multiple Choice (una respuesta)', '["Trabajar aislado sin compartir nada con otros equipos.", "Servir de puente técnico entre TI, datos, seguridad y negocio para definir y ajustar casos de uso de IA.", "Definir todos los casos de uso sin consultar a negocio.", "Limitarse a ejecutar lo que diga otro equipo, sin opinar."]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', now(), 'Servir de puente técnico entre TI, datos, seguridad y negocio para definir y ajustar casos de uso de IA.', '["Conocimiento"]'::jsonb, 4, 5),

('ATI-C29', 'Cuestionario', 'Conocimiento', '9', '7', '¿Cuál es una diferencia clave entre entrenar un modelo propio y usar un modelo de IA pre-entrenado de la nube en el contexto de TI?', 'Multiple Choice (una respuesta)', '["Ambos tienen exactamente el mismo costo.", "Entrenar un modelo propio suele requerir más datos, recursos y mantenimiento; el modelo pre-entrenado reduce esa carga pero puede limitar la personalización.", "El modelo pre-entrenado siempre es peor.", "Solo los modelos propios pueden usarse en TI."]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', now(), 'Entrenar un modelo propio suele requerir más datos, recursos y mantenimiento; el modelo pre-entrenado reduce esa carga pero puede limitar la personalización.', '["Conocimiento"]'::jsonb, 4, 5),

('ATI-C30', 'Cuestionario', 'Conocimiento', '9', '7', 'En términos de riesgos avanzados, ¿qué deberías considerar al desplegar IA para tomar acciones automáticas en infraestructura (por ejemplo, reinicios, escalado)?', 'Multiple Choice (una respuesta)', '["No necesitas logs ni auditoría si la IA es confiable.", "Es suficiente con una prueba inicial; luego no hace falta monitoreo.", "Necesitas trazabilidad de acciones, límites claros, mecanismos de rollback y revisión periódica.", "Es mejor que la IA tenga acceso total a todo."]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', now(), 'Necesitas trazabilidad de acciones, límites claros, mecanismos de rollback y revisión periódica.', '["Estrategia", "Conocimiento"]'::jsonb, 4, 5);
