-- ============================================================================
-- PREGUNTAS PARA CONSULTOR
-- ============================================================================
-- Rol incluido:
--   - Rol ID 26: Consultor (area_id: 1, nivel_id: 4)
-- ============================================================================

-- ============================================================================
-- ROL 26: Consultor
-- ============================================================================

-- ADOPCIÓN - Rol 26
INSERT INTO "public"."preguntas" ("codigo", "section", "bloque", "area_id", "exclusivo_rol_id", "texto", "tipo", "opciones", "locale", "peso", "escala", "scoring", "created_at", "respuesta_correcta", "dimension", "exclusivo_nivel_id", "dificultad") VALUES
('CON-A1', 'Cuestionario', 'Adopción', '1', '26', 'En tus proyectos de consultoría, ¿con qué frecuencia utilizas IA para buscar información inicial o sintetizar fuentes (por ejemplo, resúmenes de artículos, informes, benchmarks)?', 'Multiple Choice (escala Likert A–E)', '["Nunca", "Rara vez (≤ 1/mes)", "Ocasional (2–3/mes)", "Frecuente (semanal)", "Muy frecuente (diaria)"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', now(), null, '["Aplicación"]'::jsonb, 4, 1),

('CON-A2', 'Cuestionario', 'Adopción', '1', '26', '¿Con qué frecuencia usas IA para preparar guiones de entrevistas o workshops con clientes (preguntas clave, dinámicas, ejemplos)?', 'Multiple Choice (escala Likert A–E)', '["Nunca", "Rara vez (≤ 1/mes)", "Ocasional (2–3/mes)", "Frecuente (semanal)", "Muy frecuente (diaria)"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', now(), null, '["Aplicación"]'::jsonb, 4, 1),

('CON-A3', 'Cuestionario', 'Adopción', '1', '26', '¿Con qué frecuencia usas IA para estructurar entregables complejos (por ejemplo, sugerir índice, secciones y mensajes clave) antes de redactar?', 'Multiple Choice (escala Likert A–E)', '["Nunca", "Rara vez (≤ 1/mes)", "Ocasional (2–3/mes)", "Frecuente (semanal)", "Muy frecuente (diaria)"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', now(), null, '["Aplicación"]'::jsonb, 4, 1),

('CON-A4', 'Cuestionario', 'Adopción', '1', '26', '¿Con qué frecuencia diseñas o utilizas flujos semi-automatizados (por ejemplo, IA + hoja de cálculo + email) para acelerar tareas repetitivas de tus proyectos?', 'Multiple Choice (escala Likert A–E)', '["Nunca", "Rara vez (≤ 1/mes)", "Ocasional (2–3/mes)", "Frecuente (semanal)", "Muy frecuente (diaria)"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', now(), null, '["Aplicación"]'::jsonb, 4, 1),

('CON-A5', 'Cuestionario', 'Adopción', '1', '26', '¿Con qué frecuencia lideras con el cliente procesos formales de priorización de casos de uso de IA (por impacto/viabilidad) y los plasmas en un portafolio?', 'Multiple Choice (escala Likert A–E)', '["Nunca", "Rara vez (≤ 1/mes)", "Ocasional (2–3/mes)", "Frecuente (semanal)", "Muy frecuente (diaria)"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', now(), null, '["Aplicación"]'::jsonb, 4, 1),

('CON-A6', 'Cuestionario', 'Adopción', '1', '26', '¿Con qué frecuencia utilizas IA para redactar borradores de correos, propuestas o secciones de informes que luego tú revisas?', 'Multiple Choice (escala Likert A–E)', '["Nunca", "Rara vez (≤ 1/mes)", "Ocasional (2–3/mes)", "Frecuente (semanal)", "Muy frecuente (diaria)"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', now(), null, '["Aplicación"]'::jsonb, 4, 1),

('CON-A7', 'Cuestionario', 'Adopción', '1', '26', '¿Con qué frecuencia utilizas IA para proponer varias versiones de una diapositiva o sección de informe antes de elegir y adaptar la mejor?', 'Multiple Choice (escala Likert A–E)', '["Nunca", "Rara vez (≤ 1/mes)", "Ocasional (2–3/mes)", "Frecuente (semanal)", "Muy frecuente (diaria)"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', now(), null, '["Aplicación"]'::jsonb, 4, 2),

('CON-A8', 'Cuestionario', 'Adopción', '1', '26', '¿Con qué frecuencia utilizas IA para revisar coherencia y consistencia entre diferentes secciones de un informe o presentación?', 'Multiple Choice (escala Likert A–E)', '["Nunca", "Rara vez (≤ 1/mes)", "Ocasional (2–3/mes)", "Frecuente (semanal)", "Muy frecuente (diaria)"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', now(), null, '["Aplicación"]'::jsonb, 4, 2),

('CON-A9', 'Cuestionario', 'Adopción', '1', '26', '¿Con qué frecuencia mides explícitamente el tiempo ahorrado o la mejora en calidad gracias al uso de IA en tus proyectos?', 'Multiple Choice (escala Likert A–E)', '["Nunca", "Rara vez (≤ 1/mes)", "Ocasional (2–3/mes)", "Frecuente (semanal)", "Muy frecuente (diaria)"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', now(), null, '["Productividad", "Aplicación"]'::jsonb, 4, 2),

('CON-A10', 'Cuestionario', 'Adopción', '1', '26', '¿Con qué frecuencia diseñas o utilizas assets de IA reutilizables (bots internos, plantillas avanzadas, agentes) que se integran en múltiples proyectos con distintos clientes?', 'Multiple Choice (escala Likert A–E)', '["Nunca", "Rara vez (≤ 1/mes)", "Ocasional (2–3/mes)", "Frecuente (semanal)", "Muy frecuente (diaria)"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', now(), null, '["Aplicación"]'::jsonb, 4, 2),

('CON-A11', 'Cuestionario', 'Adopción', '1', '26', '¿Con qué frecuencia la IA te ayuda a generar ideas de recomendaciones o iniciativas que luego incluyes (adaptadas) en tus propuestas al cliente?', 'Multiple Choice (escala Likert A–E)', '["Nunca", "Rara vez (≤ 1/mes)", "Ocasional (2–3/mes)", "Frecuente (semanal)", "Muy frecuente (diaria)"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', now(), null, '["Estrategia"]'::jsonb, 4, 2),

('CON-A12', 'Cuestionario', 'Adopción', '1', '26', '¿Con qué frecuencia usas IA para explorar escenarios alternativos (por ejemplo, cómo cambiarían los resultados si el cliente prioriza un área u otra)?', 'Multiple Choice (escala Likert A–E)', '["Nunca", "Rara vez (≤ 1/mes)", "Ocasional (2–3/mes)", "Frecuente (semanal)", "Muy frecuente (diaria)"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', now(), null, '["Productividad"]'::jsonb, 4, 2),

('CON-A13', 'Cuestionario', 'Adopción', '1', '26', '¿Con qué frecuencia usas IA para simular el impacto de diferentes iniciativas (por ejemplo, describir potenciales beneficios y riesgos por escenario)?', 'Multiple Choice (escala Likert A–E)', '["Nunca", "Rara vez (≤ 1/mes)", "Ocasional (2–3/mes)", "Frecuente (semanal)", "Muy frecuente (diaria)"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', now(), null, '["Estrategia"]'::jsonb, 4, 3),

('CON-A14', 'Cuestionario', 'Adopción', '1', '26', '¿Con qué frecuencia incluyes en tus entregables roadmaps o planes de adopción de IA como parte de tus recomendaciones al cliente?', 'Multiple Choice (escala Likert A–E)', '["Nunca", "Rara vez (≤ 1/mes)", "Ocasional (2–3/mes)", "Frecuente (semanal)", "Muy frecuente (diaria)"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', now(), null, '["Estrategia", "Aplicación"]'::jsonb, 4, 3),

('CON-A15', 'Cuestionario', 'Adopción', '1', '26', '¿Con qué frecuencia participas directamente en la definición de la estrategia corporativa de IA del cliente (visión, objetivos, roadmap, gobierno)?', 'Multiple Choice (escala Likert A–E)', '["Nunca", "Rara vez (≤ 1/mes)", "Ocasional (2–3/mes)", "Frecuente (semanal)", "Muy frecuente (diaria)"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', now(), null, '["Estrategia"]'::jsonb, 4, 3),

('CON-A16', 'Cuestionario', 'Adopción', '1', '26', '¿Con qué frecuencia compartes con tu equipo o con el cliente ejemplos de salidas de IA (por ejemplo, ideas, resúmenes, guiones de workshop) para discutirlas juntos?', 'Multiple Choice (escala Likert A–E)', '["Nunca", "Rara vez (≤ 1/mes)", "Ocasional (2–3/mes)", "Frecuente (semanal)", "Muy frecuente (diaria)"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', now(), null, '["Aplicación"]'::jsonb, 4, 3),

('CON-A17', 'Cuestionario', 'Adopción', '1', '26', '¿Con qué frecuencia compartes tus prompts efectivos con colegas u otros consultores para mejorar el uso de IA en el equipo?', 'Multiple Choice (escala Likert A–E)', '["Nunca", "Rara vez (≤ 1/mes)", "Ocasional (2–3/mes)", "Frecuente (semanal)", "Muy frecuente (diaria)"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', now(), null, '["Aplicación"]'::jsonb, 4, 3),

('CON-A18', 'Cuestionario', 'Adopción', '1', '26', '¿Con qué frecuencia cocreas con el cliente materiales generados con IA (por ejemplo, ejemplos de journeys, arquetipos de usuarios, guiones de role-play) durante workshops?', 'Multiple Choice (escala Likert A–E)', '["Nunca", "Rara vez (≤ 1/mes)", "Ocasional (2–3/mes)", "Frecuente (semanal)", "Muy frecuente (diaria)"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', now(), null, '["Aplicación"]'::jsonb, 4, 3),

('CON-A19', 'Cuestionario', 'Adopción', '1', '26', '¿Con qué frecuencia trabajas junto a equipos internos del cliente (datos, TI, negocio) para coconstruir casos de uso de IA que pasen de idea a piloto?', 'Multiple Choice (escala Likert A–E)', '["Nunca", "Rara vez (≤ 1/mes)", "Ocasional (2–3/mes)", "Frecuente (semanal)", "Muy frecuente (diaria)"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', now(), null, '["Aplicación"]'::jsonb, 4, 4),

('CON-A20', 'Cuestionario', 'Adopción', '1', '26', '¿Con qué frecuencia coordinas el trabajo entre negocio, datos, TI y legal/compliance para asegurar que las iniciativas de IA sean viables, seguras y alineadas a la regulación?', 'Multiple Choice (escala Likert A–E)', '["Nunca", "Rara vez (≤ 1/mes)", "Ocasional (2–3/mes)", "Frecuente (semanal)", "Muy frecuente (diaria)"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', now(), null, '["Estrategia", "Aplicación"]'::jsonb, 4, 4),

('CON-A21', 'Cuestionario', 'Adopción', '1', '26', '¿Con qué frecuencia dedicas tiempo deliberado (por ejemplo, cada semana) a aprender nuevas funcionalidades o casos de uso de IA relevantes para tus proyectos de consultoría?', 'Multiple Choice (escala Likert A–E)', '["Nunca", "Rara vez (≤ 1/mes)", "Ocasional (2–3/mes)", "Frecuente (semanal)", "Muy frecuente (diaria)"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', now(), null, '["Productividad", "Aplicación"]'::jsonb, 4, 4),

('CON-A22', 'Cuestionario', 'Adopción', '1', '26', '¿Con qué frecuencia destinas parte de tu tiempo de proyecto para configurar plantillas de prompts reutilizables para proyectos futuros?', 'Multiple Choice (escala Likert A–E)', '["Nunca", "Rara vez (≤ 1/mes)", "Ocasional (2–3/mes)", "Frecuente (semanal)", "Muy frecuente (diaria)"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', now(), null, '["Productividad", "Aplicación"]'::jsonb, 4, 4),

('CON-A23', 'Cuestionario', 'Adopción', '1', '26', '¿Con qué frecuencia propones explícitamente en tus proyectos dedicar tiempo o presupuesto a explorar y prototipar casos de uso de IA con el cliente?', 'Multiple Choice (escala Likert A–E)', '["Nunca", "Rara vez (≤ 1/mes)", "Ocasional (2–3/mes)", "Frecuente (semanal)", "Muy frecuente (diaria)"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', now(), null, '["Inversión", "Productividad", "Aplicación"]'::jsonb, 4, 4),

('CON-A24', 'Cuestionario', 'Adopción', '1', '26', '¿Con qué frecuencia ayudas al cliente a definir presupuesto, recursos y fases para implementar proyectos de IA?', 'Multiple Choice (escala Likert A–E)', '["Nunca", "Rara vez (≤ 1/mes)", "Ocasional (2–3/mes)", "Frecuente (semanal)", "Muy frecuente (diaria)"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', now(), null, '["Inversión", "Aplicación"]'::jsonb, 4, 4),

('CON-A25', 'Cuestionario', 'Adopción', '1', '26', '¿Con qué frecuencia ayudas a construir casos de negocio detallados de IA (incluyendo CAPEX/OPEX, beneficios, riesgos y plan de implementación) para aprobación en comités ejecutivos?', 'Multiple Choice (escala Likert A–E)', '["Nunca", "Rara vez (≤ 1/mes)", "Ocasional (2–3/mes)", "Frecuente (semanal)", "Muy frecuente (diaria)"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', now(), null, '["Estrategia"]'::jsonb, 4, 5),

('CON-A26', 'Cuestionario', 'Adopción', '1', '26', '¿Con qué frecuencia revisas o preguntas por políticas de uso de IA y confidencialidad (tuyas o del cliente) antes de usar IA con información sensible?', 'Multiple Choice (escala Likert A–E)', '["Nunca", "Rara vez (≤ 1/mes)", "Ocasional (2–3/mes)", "Frecuente (semanal)", "Muy frecuente (diaria)"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', now(), null, '["Estrategia", "Aplicación"]'::jsonb, 4, 5),

('CON-A27', 'Cuestionario', 'Adopción', '1', '26', '¿Con qué frecuencia verificas hechos clave o datos importantes que la IA te entrega (por ejemplo, volúmenes de mercado, cifras financieras) antes de incluirlos en entregables?', 'Multiple Choice (escala Likert A–E)', '["Nunca", "Rara vez (≤ 1/mes)", "Ocasional (2–3/mes)", "Frecuente (semanal)", "Muy frecuente (diaria)"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', now(), null, '["Aplicación"]'::jsonb, 4, 5),

('CON-A28', 'Cuestionario', 'Adopción', '1', '26', '¿Con qué frecuencia incorporas en tus entregables advertencias o notas sobre limitaciones y riesgos de IA cuando recomiendas su uso al cliente?', 'Multiple Choice (escala Likert A–E)', '["Nunca", "Rara vez (≤ 1/mes)", "Ocasional (2–3/mes)", "Frecuente (semanal)", "Muy frecuente (diaria)"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', now(), null, '["Estrategia", "Aplicación"]'::jsonb, 4, 5),

('CON-A29', 'Cuestionario', 'Adopción', '1', '26', '¿Con qué frecuencia incluyes en tus recomendaciones lineamientos de gobernanza, ética y gestión de riesgo de IA (comités, políticas, controles)?', 'Multiple Choice (escala Likert A–E)', '["Nunca", "Rara vez (≤ 1/mes)", "Ocasional (2–3/mes)", "Frecuente (semanal)", "Muy frecuente (diaria)"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', now(), null, '["Estrategia"]'::jsonb, 4, 5),

('CON-A30', 'Cuestionario', 'Adopción', '1', '26', '¿Con qué frecuencia impulsas la incorporación de principios y políticas de IA responsable (por ejemplo, transparencia, equidad, explicabilidad) en los documentos y decisiones de alto nivel del cliente?', 'Multiple Choice (escala Likert A–E)', '["Nunca", "Rara vez (≤ 1/mes)", "Ocasional (2–3/mes)", "Frecuente (semanal)", "Muy frecuente (diaria)"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', now(), null, '["Aplicación"]'::jsonb, 4, 5);

-- CONOCIMIENTO - Rol 26
INSERT INTO "public"."preguntas" ("codigo", "section", "bloque", "area_id", "exclusivo_rol_id", "texto", "tipo", "opciones", "locale", "peso", "escala", "scoring", "created_at", "respuesta_correcta", "dimension", "exclusivo_nivel_id", "dificultad") VALUES
('CON-C1', 'Cuestionario', 'Conocimiento', '1', '26', '¿Cuál de las siguientes opciones describe mejor una herramienta de IA generativa como ChatGPT en el contexto de consultoría? A) Un buscador web que solo devuelve enlaces a páginas existentes. B) Un sistema que genera contenido nuevo (texto, imágenes, código) a partir de instrucciones en lenguaje natural. C) Un sistema que únicamente almacena y muestra plantillas de consultoría predefinidas. D) Un CRM especializado para gestionar clientes de consultoría.', 'Multiple Choice (una respuesta)', '["Un buscador web que solo devuelve enlaces a páginas existentes.", "Un sistema que genera contenido nuevo (texto, imágenes, código) a partir de instrucciones en lenguaje natural.", "Un sistema que únicamente almacena y muestra plantillas de consultoría predefinidas.", "Un CRM especializado para gestionar clientes de consultoría."]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', now(), 'Un sistema que genera contenido nuevo (texto, imágenes, código) a partir de instrucciones en lenguaje natural.', '["Conocimiento"]'::jsonb, 4, 1),

('CON-C2', 'Cuestionario', 'Conocimiento', '1', '26', '¿Qué afirmación describe mejor el concepto de ''prompt'' en IA generativa? A) Es el tipo de modelo matemático usado por la IA. B) Es el mensaje o instrucción que das a la IA para guiar su respuesta. C) Es el nombre del archivo donde se guardan las respuestas de la IA. D) Es el lenguaje de programación en el que se entrenó el modelo.', 'Multiple Choice (una respuesta)', '["Es el tipo de modelo matemático usado por la IA.", "Es el mensaje o instrucción que das a la IA para guiar su respuesta.", "Es el nombre del archivo donde se guardan las respuestas de la IA.", "Es el lenguaje de programación en el que se entrenó el modelo."]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', now(), 'Es el mensaje o instrucción que das a la IA para guiar su respuesta.', '["Conocimiento"]'::jsonb, 4, 1),

('CON-C3', 'Cuestionario', 'Conocimiento', '1', '26', '¿Qué ventaja tiene usar ''prompts iterativos'' (con varias rondas) en lugar de un único prompt? A) Ninguna; la IA siempre responde igual. B) Permite refinar la respuesta, corregir errores y ajustar el nivel de detalle paso a paso. C) Solo sirve para hacer más lenta la conversación. D) Es obligatorio para que el modelo funcione.', 'Multiple Choice (una respuesta)', '["Ninguna; la IA siempre responde igual.", "Permite refinar la respuesta, corregir errores y ajustar el nivel de detalle paso a paso.", "Solo sirve para hacer más lenta la conversación.", "Es obligatorio para que el modelo funcione."]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', now(), 'Permite refinar la respuesta, corregir errores y ajustar el nivel de detalle paso a paso.', '["Conocimiento"]'::jsonb, 4, 1),

('CON-C4', 'Cuestionario', 'Conocimiento', '1', '26', '¿Qué describe mejor el concepto de ''flujo de trabajo automatizado con IA'' en consultoría? A) Un único prompt usado una vez. B) Un proceso que combina varias herramientas (IA generativa, hojas de cálculo, CRM, etc.) automatizando pasos repetitivos. C) Una presentación con muchas diapositivas. D) Un documento con prompts guardados sin usarlos.', 'Multiple Choice (una respuesta)', '["Un único prompt usado una vez.", "Un proceso que combina varias herramientas (IA generativa, hojas de cálculo, CRM, etc.) automatizando pasos repetitivos.", "Una presentación con muchas diapositivas.", "Un documento con prompts guardados sin usarlos."]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', now(), 'Un proceso que combina varias herramientas (IA generativa, hojas de cálculo, CRM, etc.) automatizando pasos repetitivos.', '["Conocimiento", "Aplicación"]'::jsonb, 4, 1),

('CON-C5', 'Cuestionario', 'Conocimiento', '1', '26', '¿Qué es más relevante al diseñar una arquitectura de solución de IA para un cliente? A) Elegir el modelo de IA ''de moda'' en redes sociales. B) Alinear datos, modelos, aplicaciones y procesos de negocio en una arquitectura escalable y gobernada. C) Maximizar la cantidad de dashboards sin importar su uso. D) Usar el mayor número de proveedores posible.', 'Multiple Choice (una respuesta)', '["Elegir el modelo de IA ''''de moda'''' en redes sociales.", "Alinear datos, modelos, aplicaciones y procesos de negocio en una arquitectura escalable y gobernada.", "Maximizar la cantidad de dashboards sin importar su uso.", "Usar el mayor número de proveedores posible."]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', now(), 'Alinear datos, modelos, aplicaciones y procesos de negocio en una arquitectura escalable y gobernada.', '["Conocimiento", "Aplicación"]'::jsonb, 4, 1),

('CON-C6', 'Cuestionario', 'Conocimiento', '1', '26', '¿Cuál es un uso básico y apropiado de IA en un proyecto de consultoría? A) Sustituir todas las entrevistas con stakeholders por conversaciones con IA. B) Generar un resumen inicial de un informe extenso del cliente para preparar una reunión. C) Tomar todas las decisiones estratégicas del proyecto según lo que la IA recomiende. D) Compartir directamente con la IA información altamente confidencial del cliente sin restricciones.', 'Multiple Choice (una respuesta)', '["Sustituir todas las entrevistas con stakeholders por conversaciones con IA.", "Generar un resumen inicial de un informe extenso del cliente para preparar una reunión.", "Tomar todas las decisiones estratégicas del proyecto según lo que la IA recomiende.", "Compartir directamente con la IA información altamente confidencial del cliente sin restricciones."]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', now(), 'Generar un resumen inicial de un informe extenso del cliente para preparar una reunión.', '["Estrategia", "Conocimiento", "Aplicación"]'::jsonb, 4, 1),

('CON-C7', 'Cuestionario', 'Conocimiento', '1', '26', '¿Cuál de estos prompts es más útil para un consultor que busca ideas de iniciativas para reducir costos en operaciones? A) ''Haz mi trabajo por mí''. B) ''Dame ideas''. C) ''Genera 10 ideas de iniciativas para reducir costos operativos en una empresa de manufactura mediana en Latinoamérica, clasificadas por impacto estimado y facilidad de implementación.'' D) ''Escribe algo sobre operaciones''.', 'Multiple Choice (una respuesta)', '["''''Haz mi trabajo por mí''''.", "''''Dame ideas''''.", "''''Genera 10 ideas de iniciativas para reducir costos operativos en una empresa de manufactura mediana en Latinoamérica, clasificadas por impacto estimado y facilidad de implementación.", "''''Escribe algo sobre operaciones''''."]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', now(), '''''Genera 10 ideas de iniciativas para reducir costos operativos en una empresa de manufactura mediana en Latinoamérica, clasificadas por impacto estimado y facilidad de implementación.', '["Inversión", "Estrategia", "Conocimiento"]'::jsonb, 4, 2),

('CON-C8', 'Cuestionario', 'Conocimiento', '1', '26', 'Un cliente te pide ideas de iniciativas de IA para su área de compras. ¿Qué enfoque es más adecuado? A) Pedir a la IA una lista genérica de iniciativas sin contexto. B) Dar a la IA contexto de la industria, tamaño de la empresa y principales dolores de compras, y pedirle casos de uso priorizados. C) Dejar que la IA decida la estrategia completa sin que tú intervengas. D) No usar IA porque compras es un área ''solo humana''.', 'Multiple Choice (una respuesta)', '["Pedir a la IA una lista genérica de iniciativas sin contexto.", "Dar a la IA contexto de la industria, tamaño de la empresa y principales dolores de compras, y pedirle casos de uso priorizados.", "Dejar que la IA decida la estrategia completa sin que tú intervengas.", "No usar IA porque compras es un área ''''solo humana''''."]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', now(), 'Dar a la IA contexto de la industria, tamaño de la empresa y principales dolores de compras, y pedirle casos de uso priorizados.', '["Estrategia", "Conocimiento", "Aplicación"]'::jsonb, 4, 2),

('CON-C9', 'Cuestionario', 'Conocimiento', '1', '26', 'En un proyecto de operaciones, ¿qué caso de uso intermedio de IA es más razonable para un consultor no técnico? A) Diseñar y entrenar desde cero un modelo de predicción en Python. B) Usar una plataforma sin código/low-code que permita configurar modelos de pronóstico de demanda con datos del cliente, con apoyo del equipo de datos. C) Sustituir el ERP del cliente por la IA. D) Dejar que la IA contrate proveedores automáticamente.', 'Multiple Choice (una respuesta)', '["Diseñar y entrenar desde cero un modelo de predicción en Python.", "Usar una plataforma sin código/low-code que permita configurar modelos de pronóstico de demanda con datos del cliente, con apoyo del equipo de datos.", "Sustituir el ERP del cliente por la IA.", "Dejar que la IA contrate proveedores automáticamente."]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', now(), 'Usar una plataforma sin código/low-code que permita configurar modelos de pronóstico de demanda con datos del cliente, con apoyo del equipo de datos.', '["Conocimiento", "Aplicación"]'::jsonb, 4, 2),

('CON-C10', 'Cuestionario', 'Conocimiento', '1', '26', 'Al priorizar casos de uso de IA en una organización, ¿qué matriz es típica? A) Impacto en redes sociales vs número de diapositivas. B) Impacto en negocio vs viabilidad (técnica, de datos y organizacional). C) Número de personas en el comité vs cantidad de emails. D) Cantidad de proveedores vs idiomas soportados.', 'Multiple Choice (una respuesta)', '["Impacto en redes sociales vs número de diapositivas.", "Impacto en negocio vs viabilidad (técnica, de datos y organizacional).", "Número de personas en el comité vs cantidad de emails.", "Cantidad de proveedores vs idiomas soportados."]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', now(), 'Impacto en negocio vs viabilidad (técnica, de datos y organizacional).', '["Estrategia", "Conocimiento", "Aplicación"]'::jsonb, 4, 2),

('CON-C11', 'Cuestionario', 'Conocimiento', '1', '26', '¿Qué riesgo es más relevante al pegar información sensible de un cliente en una herramienta pública de IA? A) Que la IA tarde más en responder. B) Que el archivo del cliente se borre automáticamente. C) Que se compartan sin querer datos confidenciales o regulados con terceros. D) Que el diseño visual de la presentación se vea afectado.', 'Multiple Choice (una respuesta)', '["Que la IA tarde más en responder.", "Que el archivo del cliente se borre automáticamente.", "Que se compartan sin querer datos confidenciales o regulados con terceros.", "Que el diseño visual de la presentación se vea afectado."]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', now(), 'Que se compartan sin querer datos confidenciales o regulados con terceros.', '["Estrategia", "Conocimiento", "Aplicación"]'::jsonb, 4, 2),

('CON-C12', 'Cuestionario', 'Conocimiento', '1', '26', '¿Cuál es una buena práctica al usar IA para mejorar la redacción de una propuesta? A) Pedir a la IA que envíe la propuesta directamente al cliente. B) Copiar y pegar el borrador de la IA sin revisar. C) Usar la IA para mejorar claridad y estructura, y luego revisar tú el contenido crítico. D) Evitar cualquier edición posterior porque la IA ya optimizó el texto.', 'Multiple Choice (una respuesta)', '["Pedir a la IA que envíe la propuesta directamente al cliente.", "Copiar y pegar el borrador de la IA sin revisar.", "Usar la IA para mejorar claridad y estructura, y luego revisar tú el contenido crítico.", "Evitar cualquier edición posterior porque la IA ya optimizó el texto."]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', now(), 'Usar la IA para mejorar claridad y estructura, y luego revisar tú el contenido crítico.', '["Conocimiento"]'::jsonb, 4, 2),

('CON-C13', 'Cuestionario', 'Conocimiento', '1', '26', '¿Cuál es un uso eficiente de IA en el análisis de datos básico (sin ser científico de datos)? A) Pedirle que fabrique datos para que el resultado se vea mejor. B) Utilizarla para explicar tablas, detectar patrones simples y generar visualizaciones iniciales que luego tú validas. C) Dejar todo el análisis de datos en manos de la IA sin revisar. D) Evitar cualquier uso de IA con datos.', 'Multiple Choice (una respuesta)', '["Pedirle que fabrique datos para que el resultado se vea mejor.", "Utilizarla para explicar tablas, detectar patrones simples y generar visualizaciones iniciales que luego tú validas.", "Dejar todo el análisis de datos en manos de la IA sin revisar.", "Evitar cualquier uso de IA con datos."]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', now(), 'Utilizarla para explicar tablas, detectar patrones simples y generar visualizaciones iniciales que luego tú validas.', '["Conocimiento", "Aplicación"]'::jsonb, 4, 3),

('CON-C14', 'Cuestionario', 'Conocimiento', '1', '26', '¿Cómo puede la IA mejorar la gestión de conocimiento dentro de una práctica de consultoría? A) Eliminando la necesidad de documentar lecciones aprendidas. B) Ayudando a indexar, resumir y responder preguntas sobre materiales de proyectos pasados. C) Impidiendo que se compartan mejores prácticas. D) Sustituyendo el repositorio de documentos por completo.', 'Multiple Choice (una respuesta)', '["Eliminando la necesidad de documentar lecciones aprendidas.", "Ayudando a indexar, resumir y responder preguntas sobre materiales de proyectos pasados.", "Impidiendo que se compartan mejores prácticas.", "Sustituyendo el repositorio de documentos por completo."]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', now(), 'Ayudando a indexar, resumir y responder preguntas sobre materiales de proyectos pasados.', '["Conocimiento"]'::jsonb, 4, 3),

('CON-C15', 'Cuestionario', 'Conocimiento', '1', '26', 'En consultoría, ¿qué representa mejor la idea de ''asset-based consulting'' con IA? A) Vender solo horas de consultor. B) Desarrollar herramientas, plantillas, modelos o agentes de IA reutilizables que se integran en múltiples proyectos. C) No documentar nada y empezar de cero en cada proyecto. D) Enviar al cliente únicamente un informe en PDF.', 'Multiple Choice (una respuesta)', '["Vender solo horas de consultor.", "Desarrollar herramientas, plantillas, modelos o agentes de IA reutilizables que se integran en múltiples proyectos.", "No documentar nada y empezar de cero en cada proyecto.", "Enviar al cliente únicamente un informe en PDF."]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', now(), 'Desarrollar herramientas, plantillas, modelos o agentes de IA reutilizables que se integran en múltiples proyectos.', '["Conocimiento", "Aplicación"]'::jsonb, 4, 3),

('CON-C16', 'Cuestionario', 'Conocimiento', '1', '26', '¿Cuál es un beneficio típico de usar IA para redactar el primer borrador de un entregable de consultoría? A) Garantizar que no habrá errores en los datos. B) Reducir el tiempo de elaboración para concentrarse en el análisis y el storytelling. C) Evitar la necesidad de revisar el contenido. D) Reemplazar por completo a los consultores junior.', 'Multiple Choice (una respuesta)', '["Garantizar que no habrá errores en los datos.", "Reducir el tiempo de elaboración para concentrarse en el análisis y el storytelling.", "Evitar la necesidad de revisar el contenido.", "Reemplazar por completo a los consultores junior."]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', now(), 'Reducir el tiempo de elaboración para concentrarse en el análisis y el storytelling.', '["Conocimiento", "Productividad", "Aplicación"]'::jsonb, 4, 3),

('CON-C17', 'Cuestionario', 'Conocimiento', '1', '26', 'En un diagnóstico inicial, ¿cómo puede la IA apoyar mejor a un consultor? A) Decidiendo unilateralmente qué soluciones implementar. B) Generando listas de hipótesis de problema y preguntas para entrevistas. C) Reemplazando completamente el análisis financiero. D) Seleccionando proveedores de tecnología sin información adicional.', 'Multiple Choice (una respuesta)', '["Decidiendo unilateralmente qué soluciones implementar.", "Generando listas de hipótesis de problema y preguntas para entrevistas.", "Reemplazando completamente el análisis financiero.", "Seleccionando proveedores de tecnología sin información adicional."]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', now(), 'Generando listas de hipótesis de problema y preguntas para entrevistas.', '["Inversión", "Conocimiento", "Aplicación"]'::jsonb, 4, 3),

('CON-C18', 'Cuestionario', 'Conocimiento', '1', '26', '¿Qué rol debería tener la IA al definir las recomendaciones estratégicas finales para un cliente? A) Ser la única fuente de decisión. B) Ser una fuente de ideas y simulaciones, complementada por el análisis y juicio del consultor. C) Ser usada solo para temas de diseño gráfico. D) No tener ningún rol en la estrategia.', 'Multiple Choice (una respuesta)', '["Ser la única fuente de decisión.", "Ser una fuente de ideas y simulaciones, complementada por el análisis y juicio del consultor.", "Ser usada solo para temas de diseño gráfico.", "No tener ningún rol en la estrategia."]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', now(), 'Ser una fuente de ideas y simulaciones, complementada por el análisis y juicio del consultor.', '["Estrategia", "Conocimiento"]'::jsonb, 4, 3),

('CON-C19', 'Cuestionario', 'Conocimiento', '1', '26', '¿Qué elemento NO puede faltar en una hoja de ruta de IA para un cliente? A) Secuencia de casos de uso priorizados por impacto y viabilidad. B) Responsables, capacidades requeridas y métricas de éxito. C) Canales de redes sociales personales del consultor. D) Consideraciones de datos, tecnología y cambio organizacional.', 'Multiple Choice (una respuesta)', '["Secuencia de casos de uso priorizados por impacto y viabilidad.", "Responsables, capacidades requeridas y métricas de éxito.", "Canales de redes sociales personales del consultor.", "Consideraciones de datos, tecnología y cambio organizacional."]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', now(), 'Canales de redes sociales personales del consultor.', '["Conocimiento", "Productividad", "Aplicación"]'::jsonb, 4, 4),

('CON-C20', 'Cuestionario', 'Conocimiento', '1', '26', 'En una estrategia corporativa de IA, ¿qué elemento NO puede faltar? A) Un enfoque alineado a la estrategia de negocio, priorización de casos de uso y capacidades clave (datos, talento, tecnología). B) Mecanismos de gobierno y ética de IA. C) Plan de desarrollo de capacidades internas en el cliente. D) Diseño del logo de la IA del cliente sin relación con los casos de uso.', 'Multiple Choice (una respuesta)', '["Un enfoque alineado a la estrategia de negocio, priorización de casos de uso y capacidades clave (datos, talento, tecnología).", "Mecanismos de gobierno y ética de IA.", "Plan de desarrollo de capacidades internas en el cliente.", "Diseño del logo de la IA del cliente sin relación con los casos de uso."]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', now(), 'Diseño del logo de la IA del cliente sin relación con los casos de uso.', '["Estrategia", "Conocimiento", "Aplicación"]'::jsonb, 4, 4),

('CON-C21', 'Cuestionario', 'Conocimiento', '1', '26', '¿Cómo puede ayudar la IA a un consultor que trabaja en proyectos de marketing, operaciones o finanzas? A) Proporcionando ideas, ejemplos y frameworks que luego el consultor adapta al contexto del cliente. B) Tomando decisiones finales sobre precios, personal o inversiones sin necesidad de análisis adicional. C) Eliminando la necesidad de entender el negocio del cliente. D) Asegurando automáticamente el cumplimiento regulatorio en todos los países.', 'Multiple Choice (una respuesta)', '["Proporcionando ideas, ejemplos y frameworks que luego el consultor adapta al contexto del cliente.", "Tomando decisiones finales sobre precios, personal o inversiones sin necesidad de análisis adicional.", "Eliminando la necesidad de entender el negocio del cliente.", "Asegurando automáticamente el cumplimiento regulatorio en todos los países."]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', now(), 'Proporcionando ideas, ejemplos y frameworks que luego el consultor adapta al contexto del cliente.', '["Estrategia", "Conocimiento"]'::jsonb, 4, 4),

('CON-C22', 'Cuestionario', 'Conocimiento', '1', '26', '¿Cuál es un criterio razonable para decidir si pagar una licencia de IA de pago como consultor independiente? A) Que la herramienta sea la más cara del mercado. B) Que la herramienta prometa reemplazar totalmente tu trabajo. C) Que el ahorro de tiempo y mejora en la calidad de tus entregables compense el costo mensual de la licencia. D) Que sea la herramienta que usan tus amigos, sin considerar tu tipo de proyectos.', 'Multiple Choice (una respuesta)', '["Que la herramienta sea la más cara del mercado.", "Que la herramienta prometa reemplazar totalmente tu trabajo.", "Que el ahorro de tiempo y mejora en la calidad de tus entregables compense el costo mensual de la licencia.", "Que sea la herramienta que usan tus amigos, sin considerar tu tipo de proyectos."]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', now(), 'Que el ahorro de tiempo y mejora en la calidad de tus entregables compense el costo mensual de la licencia.', '["Inversión", "Conocimiento", "Productividad"]'::jsonb, 4, 4),

('CON-C23', 'Cuestionario', 'Conocimiento', '1', '26', 'Al evaluar una nueva herramienta de IA para tus proyectos, ¿qué indicador es más relevante? A) La popularidad en redes sociales. B) El número de funciones, aunque no las uses. C) El impacto en productividad y calidad de entregables en tus casos de uso típicos, comparado con el costo. D) Que use la ''tecnología más nueva'', sin importar el soporte.', 'Multiple Choice (una respuesta)', '["La popularidad en redes sociales.", "El número de funciones, aunque no las uses.", "El impacto en productividad y calidad de entregables en tus casos de uso típicos, comparado con el costo.", "Que use la ''''tecnología más nueva'''', sin importar el soporte."]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', now(), 'El impacto en productividad y calidad de entregables en tus casos de uso típicos, comparado con el costo.', '["Inversión", "Conocimiento", "Productividad", "Aplicación"]'::jsonb, 4, 4),

('CON-C24', 'Cuestionario', 'Conocimiento', '1', '26', 'Al construir un caso de negocio para invertir en IA, ¿qué aspecto es más crítico? A) Solo el ahorro en licencias de software. B) Cuántos modelos de IA se pueden usar. C) Beneficios cuantificables (ahorro de tiempo, reducción de errores, aumento de ingresos) comparados con costos de implementación, cambio y riesgos. D) Que la competencia use IA, sin importar el impacto.', 'Multiple Choice (una respuesta)', '["Solo el ahorro en licencias de software.", "Cuántos modelos de IA se pueden usar.", "Beneficios cuantificables (ahorro de tiempo, reducción de errores, aumento de ingresos) comparados con costos de implementación, cambio y riesgos.", "Que la competencia use IA, sin importar el impacto."]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', now(), 'Beneficios cuantificables (ahorro de tiempo, reducción de errores, aumento de ingresos) comparados con costos de implementación, cambio y riesgos.', '["Inversión", "Estrategia", "Conocimiento", "Productividad"]'::jsonb, 4, 4),

('CON-C25', 'Cuestionario', 'Conocimiento', '1', '26', '¿Qué indicador ilustra mejor la madurez de inversión en IA de un cliente? A) Cantidad de menciones de ''IA'' en presentaciones internas. B) Porcentaje del presupuesto de TI y transformación asignado a iniciativas de IA con KPIs claros. C) Número de influencers de IA seguidos en redes. D) Cantidad de diferentes herramientas gratuitas instaladas.', 'Multiple Choice (una respuesta)', '["Cantidad de menciones de ''''IA'''' en presentaciones internas.", "Porcentaje del presupuesto de TI y transformación asignado a iniciativas de IA con KPIs claros.", "Número de influencers de IA seguidos en redes.", "Cantidad de diferentes herramientas gratuitas instaladas."]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', now(), 'Porcentaje del presupuesto de TI y transformación asignado a iniciativas de IA con KPIs claros.', '["Inversión", "Productividad", "Estrategia", "Conocimiento", "Aplicación"]'::jsonb, 4, 5),

('CON-C26', 'Cuestionario', 'Conocimiento', '1', '26', 'Para un consultor que casi no usa IA, ¿qué inversión inicial es más razonable? A) Contratar de inmediato un equipo de científicos de datos de tiempo completo. B) Comprar todas las licencias empresariales de IA disponibles. C) Empezar con una o dos herramientas clave y dedicar tiempo semanal a aprenderlas. D) No invertir nada y esperar a que el cliente provea todas las herramientas.', 'Multiple Choice (una respuesta)', '["Contratar de inmediato un equipo de científicos de datos de tiempo completo.", "Comprar todas las licencias empresariales de IA disponibles.", "Empezar con una o dos herramientas clave y dedicar tiempo semanal a aprenderlas.", "No invertir nada y esperar a que el cliente provea todas las herramientas."]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', now(), 'Empezar con una o dos herramientas clave y dedicar tiempo semanal a aprenderlas.', '["Inversión", "Conocimiento", "Productividad", "Aplicación"]'::jsonb, 4, 5),

('CON-C27', 'Cuestionario', 'Conocimiento', '1', '26', '¿Qué significa que la IA puede ''alucinar''? A) Que solo responde si le hablas de temas creativos. B) Que inventa información o datos con aparente seguridad aunque no sean ciertos. C) Que repite siempre la misma respuesta. D) Que solo responde en inglés.', 'Multiple Choice (una respuesta)', '["Que solo responde si le hablas de temas creativos.", "Que inventa información o datos con aparente seguridad aunque no sean ciertos.", "Que repite siempre la misma respuesta.", "Que solo responde en inglés."]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', now(), 'Que inventa información o datos con aparente seguridad aunque no sean ciertos.', '["Estrategia", "Conocimiento", "Aplicación"]'::jsonb, 4, 5),

('CON-C28', 'Cuestionario', 'Conocimiento', '1', '26', '¿Qué práctica reduce el riesgo de exponer datos sensibles del cliente? A) Pegar toda la base de datos del cliente en una herramienta pública. B) Usar versiones on-premise o con acuerdos de confidencialidad, o desidentificar los datos antes de usarlos en IA pública. C) Compartir las credenciales de la herramienta con el cliente. D) Enviar los datos por correo personal.', 'Multiple Choice (una respuesta)', '["Pegar toda la base de datos del cliente en una herramienta pública.", "Usar versiones on-premise o con acuerdos de confidencialidad, o desidentificar los datos antes de usarlos en IA pública.", "Compartir las credenciales de la herramienta con el cliente.", "Enviar los datos por correo personal."]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', now(), 'Usar versiones on-premise o con acuerdos de confidencialidad, o desidentificar los datos antes de usarlos en IA pública.', '["Estrategia", "Conocimiento", "Aplicación"]'::jsonb, 4, 5),

('CON-C29', 'Cuestionario', 'Conocimiento', '1', '26', '¿Qué es una práctica responsable al introducir IA en un proceso de RRHH del cliente (por ejemplo, selección)? A) Dejar que la IA tome decisiones de contratación sin supervisión. B) No informar a los candidatos del uso de IA. C) Evaluar sesgos, mantener supervisión humana y definir criterios de transparencia y apelación. D) No probar el sistema antes de usarlo en producción.', 'Multiple Choice (una respuesta)', '["Dejar que la IA tome decisiones de contratación sin supervisión.", "No informar a los candidatos del uso de IA.", "Evaluar sesgos, mantener supervisión humana y definir criterios de transparencia y apelación.", "No probar el sistema antes de usarlo en producción."]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', now(), 'Evaluar sesgos, mantener supervisión humana y definir criterios de transparencia y apelación.', '["Estrategia", "Conocimiento", "Aplicación"]'::jsonb, 4, 5),

('CON-C30', 'Cuestionario', 'Conocimiento', '1', '26', '¿Cuál de las siguientes prácticas se alinea mejor con un marco de IA responsable en una organización? A) ''Move fast and break things'' sin controles. B) Centralizar todas las decisiones de IA en TI sin involucrar al negocio. C) Definir principios de IA responsable, procesos de evaluación de riesgos y supervisión continua de modelos. D) Dejar que cada área implemente IA sin coordinación.', 'Multiple Choice (una respuesta)', '["''''Move fast and break things'''' sin controles.", "Centralizar todas las decisiones de IA en TI sin involucrar al negocio.", "Definir principios de IA responsable, procesos de evaluación de riesgos y supervisión continua de modelos.", "Dejar que cada área implemente IA sin coordinación."]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', now(), 'Definir principios de IA responsable, procesos de evaluación de riesgos y supervisión continua de modelos.', '["Estrategia", "Conocimiento"]'::jsonb, 4, 5);
