-- ============================================================================
-- PREGUNTAS PARA ACADEMIA/INVESTIGACIÓN
-- ============================================================================
-- Rol incluido:
--   - Rol ID 8: Academia/Investigación (area_id: 10, nivel_id: 3)
-- ============================================================================

-- ============================================================================
-- ROL 8: Academia/Investigación
-- ============================================================================

-- ADOPCIÓN - Rol 8
INSERT INTO "public"."preguntas" ("codigo", "section", "bloque", "area_id", "exclusivo_rol_id", "texto", "tipo", "opciones", "locale", "peso", "escala", "scoring", "created_at", "respuesta_correcta", "dimension", "exclusivo_nivel_id", "dificultad") VALUES
('AC-A1', 'Cuestionario', 'Adopción', '10', '8', 'Con qué frecuencia utilizas IA (por ejemplo, correctores inteligentes) para mejorar gramática, ortografía o estilo de tus textos académicos?', 'Multiple Choice (escala Likert A–E)', '["Nunca", "Rara vez (≤ 1/mes)", "Ocasional (2–3/mes)", "Frecuente (semanal)", "Muy frecuente (diaria)"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', now(), null, '["Aplicación"]'::jsonb, 3, 1),

('AC-A2', 'Cuestionario', 'Adopción', '10', '8', 'Con qué frecuencia pides a una herramienta de IA que te dé una visión general inicial sobre un tema de investigación antes de buscar artículos específicos?', 'Multiple Choice (escala Likert A–E)', '["Nunca", "Rara vez (≤ 1/mes)", "Ocasional (2–3/mes)", "Frecuente (semanal)", "Muy frecuente (diaria)"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', now(), null, '["Aplicación"]'::jsonb, 3, 1),

('AC-A3', 'Cuestionario', 'Adopción', '10', '8', 'Con qué frecuencia utilizas IA para redactar o mejorar correos electrónicos relacionados con tu investigación (a coautores, tutores, coordinadores)?', 'Multiple Choice (escala Likert A–E)', '["Nunca", "Rara vez (≤ 1/mes)", "Ocasional (2–3/mes)", "Frecuente (semanal)", "Muy frecuente (diaria)"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', now(), null, '["Aplicación"]'::jsonb, 3, 1),

('AC-A4', 'Cuestionario', 'Adopción', '10', '8', 'Con qué frecuencia consultas IA para entender mejor conceptos teóricos o metodológicos (por ejemplo, explicaciones simplificadas de modelos estadísticos)?', 'Multiple Choice (escala Likert A–E)', '["Nunca", "Rara vez (≤ 1/mes)", "Ocasional (2–3/mes)", "Frecuente (semanal)", "Muy frecuente (diaria)"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', now(), null, '["Aplicación"]'::jsonb, 3, 1),

('AC-A5', 'Cuestionario', 'Adopción', '10', '8', 'Con qué frecuencia usas IA para traducir resúmenes, párrafos o presentaciones de tu investigación a otro idioma?', 'Multiple Choice (escala Likert A–E)', '["Nunca", "Rara vez (≤ 1/mes)", "Ocasional (2–3/mes)", "Frecuente (semanal)", "Muy frecuente (diaria)"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', now(), null, '["Aplicación"]'::jsonb, 3, 1),

('AC-A6', 'Cuestionario', 'Adopción', '10', '8', 'Con qué frecuencia dedicas tiempo (o pequeños recursos económicos) a probar nuevas herramientas de IA para apoyar tu investigación (versiones de prueba, cursos breves, tutoriales)?', 'Multiple Choice (escala Likert A–E)', '["Nunca", "Rara vez (≤ 1/mes)", "Ocasional (2–3/mes)", "Frecuente (semanal)", "Muy frecuente (diaria)"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', now(), null, '["Productividad", "Aplicación"]'::jsonb, 3, 1),

('AC-A7', 'Cuestionario', 'Adopción', '10', '8', 'Con qué frecuencia utilizas IA para sugerir palabras clave, títulos tentativos o revistas posibles para tus manuscritos?', 'Multiple Choice (escala Likert A–E)', '["Nunca", "Rara vez (≤ 1/mes)", "Ocasional (2–3/mes)", "Frecuente (semanal)", "Muy frecuente (diaria)"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', now(), null, '["Aplicación"]'::jsonb, 3, 2),

('AC-A8', 'Cuestionario', 'Adopción', '10', '8', 'Con qué frecuencia usas IA para generar un borrador inicial de secciones sencillas (p. ej., “agradecimientos”, “limitaciones”, “futuras líneas de investigación”) que luego editas?', 'Multiple Choice (escala Likert A–E)', '["Nunca", "Rara vez (≤ 1/mes)", "Ocasional (2–3/mes)", "Frecuente (semanal)", "Muy frecuente (diaria)"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', now(), null, '["Aplicación"]'::jsonb, 3, 2),

('AC-A9', 'Cuestionario', 'Adopción', '10', '8', 'Con qué frecuencia compartes con colegas o supervisores borradores de textos en los que has usado IA, comentando explícitamente qué partes fueron asistidas por la herramienta?', 'Multiple Choice (escala Likert A–E)', '["Nunca", "Rara vez (≤ 1/mes)", "Ocasional (2–3/mes)", "Frecuente (semanal)", "Muy frecuente (diaria)"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', now(), null, '["Aplicación"]'::jsonb, 3, 2),

('AC-A10', 'Cuestionario', 'Adopción', '10', '8', 'Con qué frecuencia utilizas IA para obtener ejemplos de estructuras de sección (p. ej., cómo organizar “Métodos” o “Discusión”) que adaptas a tu propio trabajo?', 'Multiple Choice (escala Likert A–E)', '["Nunca", "Rara vez (≤ 1/mes)", "Ocasional (2–3/mes)", "Frecuente (semanal)", "Muy frecuente (diaria)"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', now(), null, '["Aplicación"]'::jsonb, 3, 2),

('AC-A11', 'Cuestionario', 'Adopción', '10', '8', 'Con qué frecuencia revisas las condiciones de uso y privacidad de las herramientas de IA que usas para tus textos académicos?', 'Multiple Choice (escala Likert A–E)', '["Nunca", "Rara vez (≤ 1/mes)", "Ocasional (2–3/mes)", "Frecuente (semanal)", "Muy frecuente (diaria)"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', now(), null, '["Aplicación", "Estrategia"]'::jsonb, 3, 2),

('AC-A12', 'Cuestionario', 'Adopción', '10', '8', 'Con qué frecuencia participas en talleres, charlas o cursos breves sobre uso de IA en escritura o investigación académica?', 'Multiple Choice (escala Likert A–E)', '["Nunca", "Rara vez (≤ 1/mes)", "Ocasional (2–3/mes)", "Frecuente (semanal)", "Muy frecuente (diaria)"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', now(), null, '["Aplicación"]'::jsonb, 3, 2),

('AC-A13', 'Cuestionario', 'Adopción', '10', '8', 'Con qué frecuencia usas IA para apoyar el análisis de datos (por ejemplo, generación de código en R/Python, explicación de resultados estadísticos, revisión de supuestos de modelos)?', 'Multiple Choice (escala Likert A–E)', '["Nunca", "Rara vez (≤ 1/mes)", "Ocasional (2–3/mes)", "Frecuente (semanal)", "Muy frecuente (diaria)"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', now(), null, '["Productividad", "Aplicación"]'::jsonb, 3, 3),

('AC-A14', 'Cuestionario', 'Adopción', '10', '8', 'Con qué frecuencia integras IA en procesos de revisión de literatura más estructurados (p. ej., filtros iniciales, agrupación temática de artículos, extracción de variables)?', 'Multiple Choice (escala Likert A–E)', '["Nunca", "Rara vez (≤ 1/mes)", "Ocasional (2–3/mes)", "Frecuente (semanal)", "Muy frecuente (diaria)"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', now(), null, '["Aplicación"]'::jsonb, 3, 3),

('AC-A15', 'Cuestionario', 'Adopción', '10', '8', 'Con qué frecuencia documentas explícitamente en tus protocolos o cuadernos de investigación qué tareas fueron asistidas por IA?', 'Multiple Choice (escala Likert A–E)', '["Nunca", "Rara vez (≤ 1/mes)", "Ocasional (2–3/mes)", "Frecuente (semanal)", "Muy frecuente (diaria)"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', now(), null, '["Aplicación"]'::jsonb, 3, 3),

('AC-A16', 'Cuestionario', 'Adopción', '10', '8', 'Con qué frecuencia discutes con tu tutor, supervisor o coautores decisiones importantes de análisis que fueron sugeridas por herramientas de IA?', 'Multiple Choice (escala Likert A–E)', '["Nunca", "Rara vez (≤ 1/mes)", "Ocasional (2–3/mes)", "Frecuente (semanal)", "Muy frecuente (diaria)"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', now(), null, '["Aplicación"]'::jsonb, 3, 3),

('AC-A17', 'Cuestionario', 'Adopción', '10', '8', 'Con qué frecuencia revisas críticamente las salidas de IA (código, resúmenes, tablas) antes de incorporarlas a tu manuscrito o informe?', 'Multiple Choice (escala Likert A–E)', '["Nunca", "Rara vez (≤ 1/mes)", "Ocasional (2–3/mes)", "Frecuente (semanal)", "Muy frecuente (diaria)"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', now(), null, '["Aplicación"]'::jsonb, 3, 3),

('AC-A18', 'Cuestionario', 'Adopción', '10', '8', 'Con qué frecuencia propones a tu grupo de investigación pequeñas mejoras de flujo de trabajo (p. ej., plantillas, scripts, configuraciones) basadas en lo que has aprendido usando IA?', 'Multiple Choice (escala Likert A–E)', '["Nunca", "Rara vez (≤ 1/mes)", "Ocasional (2–3/mes)", "Frecuente (semanal)", "Muy frecuente (diaria)"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', now(), null, '["Aplicación"]'::jsonb, 3, 3),

('AC-A19', 'Cuestionario', 'Adopción', '10', '8', 'Con qué frecuencia utilizas IA para co-diseñar planes de recolección de datos, guiones de entrevistas, encuestas o tareas experimentales que luego discutes con tu equipo?', 'Multiple Choice (escala Likert A–E)', '["Nunca", "Rara vez (≤ 1/mes)", "Ocasional (2–3/mes)", "Frecuente (semanal)", "Muy frecuente (diaria)"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', now(), null, '["Aplicación"]'::jsonb, 3, 4),

('AC-A20', 'Cuestionario', 'Adopción', '10', '8', 'Con qué frecuencia usas IA para realizar simulaciones (p. ej., datos sintéticos, escenarios alternativos) que te ayudan a anticipar problemas de diseño o análisis?', 'Multiple Choice (escala Likert A–E)', '["Nunca", "Rara vez (≤ 1/mes)", "Ocasional (2–3/mes)", "Frecuente (semanal)", "Muy frecuente (diaria)"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', now(), null, '["Aplicación"]'::jsonb, 3, 4),

('AC-A21', 'Cuestionario', 'Adopción', '10', '8', 'Con qué frecuencia llevas un registro organizado de prompts, configuraciones y herramientas de IA utilizadas en tus proyectos, para poder reproducir el flujo de trabajo?', 'Multiple Choice (escala Likert A–E)', '["Nunca", "Rara vez (≤ 1/mes)", "Ocasional (2–3/mes)", "Frecuente (semanal)", "Muy frecuente (diaria)"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', now(), null, '["Aplicación"]'::jsonb, 3, 4),

('AC-A22', 'Cuestionario', 'Adopción', '10', '8', 'Con qué frecuencia propones al equipo decisiones metodológicas (p. ej., elección de modelos, criterios de inclusión) que originalmente fueron sugeridas por una herramienta de IA, explicando su razonamiento?', 'Multiple Choice (escala Likert A–E)', '["Nunca", "Rara vez (≤ 1/mes)", "Ocasional (2–3/mes)", "Frecuente (semanal)", "Muy frecuente (diaria)"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', now(), null, '["Aplicación"]'::jsonb, 3, 4),

('AC-A23', 'Cuestionario', 'Adopción', '10', '8', 'Con qué frecuencia evalúas explícitamente los riesgos éticos (sesgos, privacidad, transparencia) cuando incorporas IA en nuevas fases del proyecto?', 'Multiple Choice (escala Likert A–E)', '["Nunca", "Rara vez (≤ 1/mes)", "Ocasional (2–3/mes)", "Frecuente (semanal)", "Muy frecuente (diaria)"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', now(), null, '["Estrategia"]'::jsonb, 3, 4),

('AC-A24', 'Cuestionario', 'Adopción', '10', '8', 'Con qué frecuencia participas en decisiones sobre qué licencias, suscripciones o herramientas de IA vale la pena financiar para tu grupo/laboratorio?', 'Multiple Choice (escala Likert A–E)', '["Nunca", "Rara vez (≤ 1/mes)", "Ocasional (2–3/mes)", "Frecuente (semanal)", "Muy frecuente (diaria)"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', now(), null, '["Aplicación"]'::jsonb, 3, 4),

('AC-A25', 'Cuestionario', 'Adopción', '10', '8', 'Con qué frecuencia participas en el diseño o ajuste de modelos (p. ej., fine-tuning, configuración avanzada, elección de arquitecturas) específicamente para apoyar tu línea de investigación?', 'Multiple Choice (escala Likert A–E)', '["Nunca", "Rara vez (≤ 1/mes)", "Ocasional (2–3/mes)", "Frecuente (semanal)", "Muy frecuente (diaria)"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', now(), null, '["Aplicación"]'::jsonb, 3, 5),

('AC-A26', 'Cuestionario', 'Adopción', '10', '8', 'Con qué frecuencia diseñas pipelines semi-o totalmente automatizados (IA + código + herramientas de gestión de datos) para tareas como revisión sistemática, análisis de grandes corpus o monitoreo de literatura?', 'Multiple Choice (escala Likert A–E)', '["Nunca", "Rara vez (≤ 1/mes)", "Ocasional (2–3/mes)", "Frecuente (semanal)", "Muy frecuente (diaria)"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', now(), null, '["Aplicación"]'::jsonb, 3, 5),

('AC-A27', 'Cuestionario', 'Adopción', '10', '8', 'Con qué frecuencia lideras discusiones en tu grupo o departamento sobre lineamientos de uso responsable de IA (ética, transparencia, privacidad, autoría)?', 'Multiple Choice (escala Likert A–E)', '["Nunca", "Rara vez (≤ 1/mes)", "Ocasional (2–3/mes)", "Frecuente (semanal)", "Muy frecuente (diaria)"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', now(), null, '["Aplicación", "Estrategia"]'::jsonb, 3, 5),

('AC-A28', 'Cuestionario', 'Adopción', '10', '8', 'Con qué frecuencia involucras a estudiantes o colegas en proyectos donde la IA es parte central del diseño metodológico, enseñándoles explícitamente el flujo de trabajo?', 'Multiple Choice (escala Likert A–E)', '["Nunca", "Rara vez (≤ 1/mes)", "Ocasional (2–3/mes)", "Frecuente (semanal)", "Muy frecuente (diaria)"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', now(), null, '["Aplicación"]'::jsonb, 3, 5),

('AC-A29', 'Cuestionario', 'Adopción', '10', '8', 'Con qué frecuencia elaboras o actualizas documentación compartida (guías, repositorios, plantillas) sobre buenas prácticas de IA en tu área de investigación?', 'Multiple Choice (escala Likert A–E)', '["Nunca", "Rara vez (≤ 1/mes)", "Ocasional (2–3/mes)", "Frecuente (semanal)", "Muy frecuente (diaria)"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', now(), null, '["Aplicación"]'::jsonb, 3, 5),

('AC-A30', 'Cuestionario', 'Adopción', '10', '8', 'Con qué frecuencia participas o impulsas decisiones sobre inversiones significativas en infraestructura de IA (suscripciones, servidores, herramientas especializadas) para tu unidad académica, aportando análisis de costo–beneficio?', 'Multiple Choice (escala Likert A–E)', '["Nunca", "Rara vez (≤ 1/mes)", "Ocasional (2–3/mes)", "Frecuente (semanal)", "Muy frecuente (diaria)"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', now(), null, '["Inversión", "Aplicación"]'::jsonb, 3, 5);

-- CONOCIMIENTO - Rol 8
INSERT INTO "public"."preguntas" ("codigo", "section", "bloque", "area_id", "exclusivo_rol_id", "texto", "tipo", "opciones", "locale", "peso", "escala", "scoring", "created_at", "respuesta_correcta", "dimension", "exclusivo_nivel_id", "dificultad") VALUES
('AC-C1', 'Cuestionario', 'Conocimiento', '10', '8', 'En investigación académica, ¿cuál es un uso apropiado de un chatbot de IA generativa como apoyo inicial?', 'Multiple Choice (una respuesta)', '["Sustituir la lectura de los artículos y citar directamente al chatbot", "Generar ideas o resúmenes preliminares que luego se verifican con las fuentes originales", "Dejar que escriba todo el artículo y enviarlo tal cual", "Usarlo para inventar resultados cuando faltan datos"]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', now(), 'Generar ideas o resúmenes preliminares que luego se verifican con las fuentes originales', '["Aplicación", "Conocimiento"]'::jsonb, 3, 1),

('AC-C2', 'Cuestionario', 'Conocimiento', '10', '8', '¿Cuál de las siguientes tareas es un ejemplo típico de IA en revisión de literatura?', 'Multiple Choice (una respuesta)', '["Firmar como coautor en un artículo científico", "Decidir automáticamente si un estudio es ético", "Sugerir artículos relacionados y extraer palabras clave relevantes", "Aprobar el presupuesto del proyecto"]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', now(), 'Sugerir artículos relacionados y extraer palabras clave relevantes', '["Conocimiento"]'::jsonb, 3, 1),

('AC-C3', 'Cuestionario', 'Conocimiento', '10', '8', 'Un riesgo importante al usar IA generativa para escribir secciones de un paper es:', 'Multiple Choice (una respuesta)', '["Que mejore la claridad del texto", "Que reduzca el número de referencias necesarias", "Que invente información o citas que parecen reales pero no lo son", "Que obligue a usar más tablas y figuras"]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', now(), 'Que invente información o citas que parecen reales pero no lo son', '["Estrategia", "Conocimiento"]'::jsonb, 3, 1),

('AC-C4', 'Cuestionario', 'Conocimiento', '10', '8', 'Respecto a las políticas de revistas sobre uso de IA en manuscritos, lo más habitual es que:', 'Multiple Choice (una respuesta)', '["Esté estrictamente prohibido cualquier uso de IA", "Se permita el uso, pero se exija transparencia sobre cómo se utilizó", "No haga falta declarar nada", "La IA sea reconocida como autora"]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', now(), 'Se permita el uso, pero se exija transparencia sobre cómo se utilizó', '["Aplicación", "Conocimiento"]'::jsonb, 3, 1),

('AC-C5', 'Cuestionario', 'Conocimiento', '10', '8', '¿Cuál de las siguientes herramientas es un ejemplo de sistema de apoyo que puede incorporar IA para revisar originalidad o similitud de textos?', 'Multiple Choice (una respuesta)', '["Un editor de imágenes", "Un sistema de detección de plagio", "Un lector de PDFs sin búsqueda", "Un calendario online"]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', now(), 'Un sistema de detección de plagio', '["Aplicación", "Conocimiento"]'::jsonb, 3, 1),

('AC-C6', 'Cuestionario', 'Conocimiento', '10', '8', 'Para proteger datos sensibles al usar herramientas de IA en la nube, lo más recomendable es:', 'Multiple Choice (una respuesta)', '["Subir bases de datos con identificadores personales sin problema", "Compartir datos de participantes porque la IA “no los guarda”", "Evitar subir datos sensibles o anonimizarlos siguiendo las normas éticas e institucionales", "No informar al comité de ética sobre el uso de IA"]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', now(), 'Evitar subir datos sensibles o anonimizarlos siguiendo las normas éticas e institucionales', '["Aplicación", "Conocimiento"]'::jsonb, 3, 1),

('AC-C7', 'Cuestionario', 'Conocimiento', '10', '8', '¿Qué es un “prompt” en el contexto de IA generativa aplicada a la investigación?', 'Multiple Choice (una respuesta)', '["El conjunto de datos de entrenamiento del modelo", "La instrucción o mensaje que se envía al modelo para obtener una respuesta", "El algoritmo interno que usa el modelo", "El DOI de un artículo"]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', now(), 'La instrucción o mensaje que se envía al modelo para obtener una respuesta', '["Aplicación", "Conocimiento"]'::jsonb, 3, 2),

('AC-C8', 'Cuestionario', 'Conocimiento', '10', '8', 'Cuando usas IA para resumir un artículo, ¿cuál es una buena práctica?', 'Multiple Choice (una respuesta)', '["Confiar ciegamente en el resumen generado", "Evitar leer el artículo original si el resumen parece correcto", "Comparar el resumen con el contenido real y ajustar manualmente", "Pedir sólo el título para ahorrar tiempo"]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', now(), 'Comparar el resumen con el contenido real y ajustar manualmente', '["Conocimiento"]'::jsonb, 3, 2),

('AC-C9', 'Cuestionario', 'Conocimiento', '10', '8', '¿Cuál de estos usos de IA es más adecuado para preparar la sección de antecedentes de un trabajo?', 'Multiple Choice (una respuesta)', '["Generar todo el texto y publicarlo sin cambios", "Pedir sugerencias de estructura y luego escribir el texto verificando cada referencia", "Pedir que invente nuevos estudios para fortalecer la hipótesis", "Usar IA para modificar los resultados de estudios previos"]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', now(), 'Pedir sugerencias de estructura y luego escribir el texto verificando cada referencia', '["Aplicación", "Conocimiento"]'::jsonb, 3, 2),

('AC-C10', 'Cuestionario', 'Conocimiento', '10', '8', '¿Qué aspecto es esencial al usar IA en redacciones académicas para evitar problemas de plagio?', 'Multiple Choice (una respuesta)', '["No citar ninguna fuente", "Ocultar que se usó IA", "Mantener la autoría intelectual, citar las fuentes originales y seguir las políticas de la revista/institución", "Copiar literalmente las respuestas de la IA"]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', now(), 'Mantener la autoría intelectual, citar las fuentes originales y seguir las políticas de la revista/institución', '["Conocimiento"]'::jsonb, 3, 2),

('AC-C11', 'Cuestionario', 'Conocimiento', '10', '8', 'Si subes fragmentos de tu manuscrito a una herramienta de IA pública, ¿qué deberías verificar antes?', 'Multiple Choice (una respuesta)', '["El precio de la suscripción", "Si la herramienta permite usar esos datos para seguir entrenando el modelo y las condiciones de privacidad", "Si la herramienta tiene modo oscuro", "El número de usuarios activos"]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', now(), 'Si la herramienta permite usar esos datos para seguir entrenando el modelo y las condiciones de privacidad', '["Conocimiento"]'::jsonb, 3, 2),

('AC-C12', 'Cuestionario', 'Conocimiento', '10', '8', 'Una ventaja de usar IA para apoyo en escritura científica es:', 'Multiple Choice (una respuesta)', '["Que garantice la aceptación del artículo", "Que evita la revisión por pares", "Que puede ayudar a mejorar claridad, cohesión y corrección lingüística del texto", "Que reemplaza la necesidad de aprender a escribir bien"]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', now(), 'Que puede ayudar a mejorar claridad, cohesión y corrección lingüística del texto', '["Conocimiento"]'::jsonb, 3, 2),

('AC-C13', 'Cuestionario', 'Conocimiento', '10', '8', 'En análisis de datos, ¿cuál es un uso adecuado de IA para un investigador no especialista en machine learning?', 'Multiple Choice (una respuesta)', '["Dejar que la IA escoja cualquier modelo y publicar resultados sin entenderlos", "Usar IA para sugerir modelos y luego revisar supuestos, métricas y coherencia con la teoría", "Permitir que la IA modifique los datos para que “encajen” mejor", "Ignorar la validez externa del modelo"]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', now(), 'Usar IA para sugerir modelos y luego revisar supuestos, métricas y coherencia con la teoría', '["Aplicación", "Conocimiento"]'::jsonb, 3, 3),

('AC-C14', 'Cuestionario', 'Conocimiento', '10', '8', '¿Qué describe mejor la idea de “caja negra” en modelos de IA aplicados a investigación?', 'Multiple Choice (una respuesta)', '["Modelos con código abierto y fácilmente interpretables", "Modelos cuyo funcionamiento interno es poco transparente o difícil de interpretar", "Modelos sólo gráficos", "Modelos que no necesitan datos de entrenamiento"]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', now(), 'Modelos cuyo funcionamiento interno es poco transparente o difícil de interpretar', '["Aplicación", "Conocimiento"]'::jsonb, 3, 3),

('AC-C15', 'Cuestionario', 'Conocimiento', '10', '8', 'En una revisión sistemática de literatura, ¿cómo puede apoyar la IA de manera responsable?', 'Multiple Choice (una respuesta)', '["Seleccionando artículos sin necesidad de criterios de inclusión", "Realizando el screening inicial según criterios definidos por el investigador y requiriendo validación humana", "Inventando artículos para cubrir vacíos de evidencia", "Eliminando artículos que contradicen la hipótesis del investigador"]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', now(), 'Realizando el screening inicial según criterios definidos por el investigador y requiriendo validación humana', '["Conocimiento"]'::jsonb, 3, 3),

('AC-C16', 'Cuestionario', 'Conocimiento', '10', '8', '¿Qué debe hacer un investigador al reportar el uso de IA en el análisis de datos?', 'Multiple Choice (una respuesta)', '["No mencionar nada para no “complicar” la revisión", "Describir qué tareas realizó la IA, qué herramientas usó y qué decisiones humanas se tomaron", "Indicar solo que se utilizó “tecnología avanzada”", "Dejar que la IA escriba la sección de métodos sin revisión"]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', now(), 'Describir qué tareas realizó la IA, qué herramientas usó y qué decisiones humanas se tomaron', '["Aplicación", "Conocimiento"]'::jsonb, 3, 3),

('AC-C17', 'Cuestionario', 'Conocimiento', '10', '8', 'En términos de productividad, ¿qué es más razonable esperar al integrar IA en el flujo de investigación?', 'Multiple Choice (una respuesta)', '["Reducir el tiempo total de proyecto a la mitad sin cambiar nada más", "Facilitar tareas repetitivas y liberar tiempo para análisis crítico y diseño", "Que la IA haga el trabajo creativo mientras el investigador solo firma", "Que ya no se necesiten revisores humanos"]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', now(), 'Facilitar tareas repetitivas y liberar tiempo para análisis crítico y diseño', '["Productividad", "Conocimiento"]'::jsonb, 3, 3),

('AC-C18', 'Cuestionario', 'Conocimiento', '10', '8', 'Respecto a la inversión en IA para el laboratorio o grupo, un investigador colaborador debería:', 'Multiple Choice (una respuesta)', '["Decidir solo qué herramientas se compran", "Ignorar los costos porque no son su responsabilidad", "Aportar evidencias sobre qué herramientas aportan más valor y sugerir prioridades a la dirección", "Usar solo herramientas gratuitas sin discutirlo"]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', now(), 'Aportar evidencias sobre qué herramientas aportan más valor y sugerir prioridades a la dirección', '["Inversión", "Conocimiento"]'::jsonb, 3, 3),

('AC-C19', 'Cuestionario', 'Conocimiento', '10', '8', 'Al usar IA para co-diseñar un estudio (p. ej., definir variables o instrumentos), ¿qué es fundamental?', 'Multiple Choice (una respuesta)', '["Dejar que la IA defina todo el diseño sin intervención humana", "Verificar que las propuestas de la IA sean coherentes con la literatura y los objetivos del estudio", "No consultar a los coautores para no sesgar a la IA", "Hacer que la IA firme como coautora"]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', now(), 'Verificar que las propuestas de la IA sean coherentes con la literatura y los objetivos del estudio', '["Conocimiento"]'::jsonb, 3, 4),

('AC-C20', 'Cuestionario', 'Conocimiento', '10', '8', '¿Qué ventaja puede aportar la IA en la planificación de experimentos o estudios observacionales?', 'Multiple Choice (una respuesta)', '["Reducir la necesidad de justificar el diseño", "Simular escenarios, estimar tamaños muestrales o explorar configuraciones de variables", "Eliminar la necesidad de comité de ética", "Evitar el preregistro de hipótesis"]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', now(), 'Simular escenarios, estimar tamaños muestrales o explorar configuraciones de variables', '["Aplicación", "Estrategia", "Conocimiento"]'::jsonb, 3, 4),

('AC-C21', 'Cuestionario', 'Conocimiento', '10', '8', 'En términos de colaboración, ¿qué práctica es deseable cuando un investigador usa IA de manera intensiva en el proyecto?', 'Multiple Choice (una respuesta)', '["Mantener el uso de IA como un “secreto” personal", "Compartir con el equipo qué herramientas se usan, cómo se usan y qué limitaciones tienen", "Asumir que todos usan IA de la misma forma", "Delegar en la IA la coordinación del equipo"]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', now(), 'Compartir con el equipo qué herramientas se usan, cómo se usan y qué limitaciones tienen', '["Conocimiento"]'::jsonb, 3, 4),

('AC-C22', 'Cuestionario', 'Conocimiento', '10', '8', 'Si un modelo de IA sugiere un resultado que contradice la teoría y la evidencia previa, ¿qué debería hacer el investigador?', 'Multiple Choice (una respuesta)', '["Publicarlo porque “la IA no se equivoca”", "Ignorar la teoría y seguir sólo la IA", "Revisar datos, supuestos y replicar análisis antes de aceptar o rechazar el resultado", "Ajustar los datos para que se parezcan a la salida de IA"]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', now(), 'Revisar datos, supuestos y replicar análisis antes de aceptar o rechazar el resultado', '["Conocimiento"]'::jsonb, 3, 4),

('AC-C23', 'Cuestionario', 'Conocimiento', '10', '8', '¿Qué consideración estratégica es clave al incorporar IA en múltiples etapas del proyecto?', 'Multiple Choice (una respuesta)', '["No dejar evidencia de qué se hizo con IA", "Diseñar flujos reproducibles (p. ej., registrar prompts, versiones de modelos, configuraciones)", "Cambiar de herramienta constantemente sin documentarlo", "Depender de una sola herramienta sin evaluar alternativas"]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', now(), 'Diseñar flujos reproducibles (p. ej., registrar prompts, versiones de modelos, configuraciones)', '["Conocimiento"]'::jsonb, 3, 4),

('AC-C24', 'Cuestionario', 'Conocimiento', '10', '8', 'Respecto a recursos, ¿qué enfoque es más razonable para decidir inversiones en herramientas de IA para el grupo?', 'Multiple Choice (una respuesta)', '["Priorizar siempre la herramienta más cara", "Elegir herramientas basadas en marketing y popularidad", "Evaluar costo–beneficio, alineación con las necesidades del grupo y requisitos de privacidad/ética", "Evitar cualquier gasto en IA"]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', now(), 'Evaluar costo–beneficio, alineación con las necesidades del grupo y requisitos de privacidad/ética', '["Aplicación", "Conocimiento"]'::jsonb, 3, 4),

('AC-C25', 'Cuestionario', 'Conocimiento', '10', '8', '¿Qué describe mejor el fine-tuning (ajuste fino) de un modelo de lenguaje para un dominio de investigación específico?', 'Multiple Choice (una respuesta)', '["Cambiar el color de la interfaz de la herramienta", "Entrenar un modelo pequeño desde cero", "Ajustar un modelo pre-entrenado con datos adicionales del dominio para especializarlo", "Reducir el tamaño de fuente en los resultados"]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', now(), 'Ajustar un modelo pre-entrenado con datos adicionales del dominio para especializarlo', '["Conocimiento"]'::jsonb, 3, 5),

('AC-C26', 'Cuestionario', 'Conocimiento', '10', '8', 'Al automatizar partes de una revisión sistemática con IA, ¿qué requisito metodológico es clave para mantener el rigor?', 'Multiple Choice (una respuesta)', '["Delegar toda la selección de estudios a la IA", "Documentar criterios, validar muestras a mano y reportar claramente el papel de la IA", "No informar que se usó IA para evitar cuestionamientos", "Permitir que la IA modifique los criterios de inclusión durante el proceso"]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', now(), 'Documentar criterios, validar muestras a mano y reportar claramente el papel de la IA', '["Productividad", "Conocimiento"]'::jsonb, 3, 5),

('AC-C27', 'Cuestionario', 'Conocimiento', '10', '8', '¿Cuál es un riesgo específico al generar datos sintéticos con IA para investigación?', 'Multiple Choice (una respuesta)', '["Reducir el número de variables", "Que los datos sintéticos reproduzcan o amplifiquen sesgos de los datos originales", "Que los datos se vuelvan más fáciles de analizar", "Que no se pueda usar ningún método estadístico"]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', now(), 'Que los datos sintéticos reproduzcan o amplifiquen sesgos de los datos originales', '["Aplicación", "Estrategia", "Conocimiento"]'::jsonb, 3, 5),

('AC-C28', 'Cuestionario', 'Conocimiento', '10', '8', 'Cuando se construye un pipeline automatizado de análisis con IA y código, ¿qué práctica aumenta la reproducibilidad?', 'Multiple Choice (una respuesta)', '["Usar siempre la última versión de cualquier modelo sin registrarla", "No usar control de versiones", "Documentar versiones de modelos, dependencias, parámetros y publicar scripts/notebooks cuando sea posible", "Compartir sólo capturas de pantalla de los resultados"]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', now(), 'Documentar versiones de modelos, dependencias, parámetros y publicar scripts/notebooks cuando sea posible', '["Conocimiento"]'::jsonb, 3, 5),

('AC-C29', 'Cuestionario', 'Conocimiento', '10', '8', 'En términos de estrategia de grupo, un pionero en IA debería:', 'Multiple Choice (una respuesta)', '["Imponer su forma de trabajar sin escuchar al resto", "Diseñar lineamientos y buenas prácticas de uso de IA co-creados con el equipo, alineados con políticas institucionales y de revistas", "Mantener en secreto los flujos de trabajo para conservar “ventaja competitiva”", "Desentenderse de la formación de estudiantes y colegas"]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', now(), 'Diseñar lineamientos y buenas prácticas de uso de IA co-creados con el equipo, alineados con políticas institucionales y de revistas', '["Estrategia", "Conocimiento"]'::jsonb, 3, 5),

('AC-C30', 'Cuestionario', 'Conocimiento', '10', '8', 'Respecto a inversión, ¿qué enfoque es propio de un pionero responsable en IA en el laboratorio?', 'Multiple Choice (una respuesta)', '["Probar cualquier herramienta sin considerar seguridad ni presupuesto", "Elegir herramientas sólo por ser gratuitas", "Evaluar impacto científico, riesgos éticos, sostenibilidad económica y necesidades de formación del equipo", "Dejar que la IA escoja cuáles herramientas comprar"]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', now(), 'Evaluar impacto científico, riesgos éticos, sostenibilidad económica y necesidades de formación del equipo', '["Inversión", "Conocimiento"]'::jsonb, 3, 5);
