-- ============================================================================
-- PREGUNTAS PARA DIRECCIÓN DE COMPRAS / SUPPLY
-- ============================================================================
-- Rol incluido:
--   - Rol ID 16: Dirección de Compras / Supply (area_id: 8, nivel_id: 2)
-- ============================================================================

-- ============================================================================
-- ROL 16: Dirección de Compras / Supply
-- ============================================================================

-- ADOPCIÓN - Rol 16
INSERT INTO "public"."preguntas" ("codigo", "section", "bloque", "area_id", "exclusivo_rol_id", "texto", "tipo", "opciones", "locale", "peso", "escala", "scoring", "created_at", "respuesta_correcta", "dimension", "exclusivo_nivel_id", "dificultad") VALUES
('DCS-A1', 'Cuestionario', 'Adopción', '8', '16', 'En tu rol de Dirección de Compras/Supply, ¿con qué frecuencia utilizas algún asistente de IA (por ejemplo, tipo chatbot) para redactar o mejorar correos a proveedores?', 'Multiple Choice (escala Likert A–E)', '["Nunca", "Rara vez (≤ 1/mes)", "Ocasionalmente", "Frecuente (semanal)", "Muy frecuentemente"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', now(), null, '["Aplicación"]'::jsonb, 2, 1),

('DCS-A2', 'Cuestionario', 'Adopción', '8', '16', '¿Con qué frecuencia revisas, aunque sea de forma general, si tu ERP o herramienta de compras incluye funciones inteligentes (sugerencias, alertas, clasificaciones automáticas)?', 'Multiple Choice (escala Likert A–E)', '["Nunca", "Rara vez (≤ 1/mes)", "Ocasionalmente", "Frecuente (semanal)", "Muy frecuentemente"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', now(), null, '["Aplicación"]'::jsonb, 2, 1),

('DCS-A3', 'Cuestionario', 'Adopción', '8', '16', '¿Con qué frecuencia pides a tu equipo que explore o pruebe nuevas herramientas de IA aplicadas a Compras, aunque sea en pruebas pequeñas?', 'Multiple Choice (escala Likert A–E)', '["Nunca", "Rara vez (≤ 1/mes)", "Ocasionalmente", "Frecuente (semanal)", "Muy frecuentemente"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', now(), null, '["Aplicación"]'::jsonb, 2, 1),

('DCS-A4', 'Cuestionario', 'Adopción', '8', '16', '¿Con qué frecuencia utilizas IA para preparar resúmenes ejecutivos de información de proveedores, por ejemplo historial de desempeño, riesgos e incidencias, para reuniones internas?', 'Multiple Choice (escala Likert A–E)', '["Nunca", "Rara vez (≤ 1/mes)", "Ocasionalmente", "Frecuente (semanal)", "Muy frecuentemente"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', now(), null, '["Estrategia", "Aplicación"]'::jsonb, 2, 1),

('DCS-A5', 'Cuestionario', 'Adopción', '8', '16', '¿Con qué frecuencia discutes con otros directivos, como Finanzas, Operaciones o TI, oportunidades básicas de aplicar IA en procesos de Compras?', 'Multiple Choice (escala Likert A–E)', '["Nunca", "Rara vez (≤ 1/mes)", "Ocasionalmente", "Frecuente (semanal)", "Muy frecuentemente"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', now(), null, '["Aplicación"]'::jsonb, 2, 1),

('DCS-A6', 'Cuestionario', 'Adopción', '8', '16', '¿Con qué frecuencia planteas preocupaciones éticas o de riesgo, como privacidad, confidencialidad o sesgos, cuando alguien propone usar IA en la relación con proveedores?', 'Multiple Choice (escala Likert A–E)', '["Nunca", "Rara vez (≤ 1/mes)", "Ocasionalmente", "Frecuente (semanal)", "Muy frecuentemente"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', now(), null, '["Estrategia"]'::jsonb, 2, 1),

('DCS-A7', 'Cuestionario', 'Adopción', '8', '16', '¿Con qué frecuencia usas IA para generar o revisar borradores de RFP o RFQ de complejidad baja o media?', 'Multiple Choice (escala Likert A–E)', '["Nunca", "Rara vez (≤ 1/mes)", "Ocasionalmente", "Frecuente (semanal)", "Muy frecuentemente"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', now(), null, '["Aplicación"]'::jsonb, 2, 2),

('DCS-A8', 'Cuestionario', 'Adopción', '8', '16', '¿Con qué frecuencia pides a la IA que resuma propuestas de proveedores y resalte puntos clave, como riesgos, excepciones y beneficios?', 'Multiple Choice (escala Likert A–E)', '["Nunca", "Rara vez (≤ 1/mes)", "Ocasionalmente", "Frecuente (semanal)", "Muy frecuentemente"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', now(), null, '["Estrategia"]'::jsonb, 2, 2),

('DCS-A9', 'Cuestionario', 'Adopción', '8', '16', '¿Con qué frecuencia involucras a tu equipo en pequeñas pruebas de IA, por ejemplo comparar un análisis manual de gasto con uno generado por IA?', 'Multiple Choice (escala Likert A–E)', '["Nunca", "Rara vez (≤ 1/mes)", "Ocasionalmente", "Frecuente (semanal)", "Muy frecuentemente"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', now(), null, '["Aplicación"]'::jsonb, 2, 2),

('DCS-A10', 'Cuestionario', 'Adopción', '8', '16', '¿Con qué frecuencia compartes aprendizajes prácticos sobre IA con otros directores, por ejemplo en comités o reuniones de alineación?', 'Multiple Choice (escala Likert A–E)', '["Nunca", "Rara vez (≤ 1/mes)", "Ocasionalmente", "Frecuente (semanal)", "Muy frecuentemente"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', now(), null, '["Aplicación"]'::jsonb, 2, 2),

('DCS-A11', 'Cuestionario', 'Adopción', '8', '16', '¿Con qué frecuencia revisas si el uso de IA en Compras respeta las políticas de confidencialidad y protección de datos de la empresa?', 'Multiple Choice (escala Likert A–E)', '["Nunca", "Rara vez (≤ 1/mes)", "Ocasionalmente", "Frecuente (semanal)", "Muy frecuentemente"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', now(), null, '["Estrategia", "Aplicación"]'::jsonb, 2, 2),

('DCS-A12', 'Cuestionario', 'Adopción', '8', '16', '¿Con qué frecuencia asignas explícitamente tiempo o presupuesto para que el equipo de Compras aprenda y experimente con IA?', 'Multiple Choice (escala Likert A–E)', '["Nunca", "Rara vez (≤ 1/mes)", "Ocasionalmente", "Frecuente (semanal)", "Muy frecuentemente"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', now(), null, '["Inversión", "Aplicación", "Productividad"]'::jsonb, 2, 2),

('DCS-A13', 'Cuestionario', 'Adopción', '8', '16', '¿Con qué frecuencia utilizas dashboards de analítica de gasto con elementos de IA, como clasificación automática o detección de anomalías, para definir acciones en categorías clave?', 'Multiple Choice (escala Likert A–E)', '["Nunca", "Rara vez (≤ 1/mes)", "Ocasionalmente", "Frecuente (semanal)", "Muy frecuentemente"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', now(), null, '["Aplicación"]'::jsonb, 2, 3),

('DCS-A14', 'Cuestionario', 'Adopción', '8', '16', '¿Con qué frecuencia usas IA para simular escenarios de consolidación de proveedores, por ejemplo qué pasa si reduces de un número mayor a menos proveedores?', 'Multiple Choice (escala Likert A–E)', '["Nunca", "Rara vez (≤ 1/mes)", "Ocasionalmente", "Frecuente (semanal)", "Muy frecuentemente"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', now(), null, '["Aplicación"]'::jsonb, 2, 3),

('DCS-A15', 'Cuestionario', 'Adopción', '8', '16', '¿Con qué frecuencia revisas junto con tu equipo por qué la IA hizo ciertas recomendaciones, buscando explicaciones básicas de los modelos?', 'Multiple Choice (escala Likert A–E)', '["Nunca", "Rara vez (≤ 1/mes)", "Ocasionalmente", "Frecuente (semanal)", "Muy frecuentemente"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', now(), null, '["Aplicación"]'::jsonb, 2, 3),

('DCS-A16', 'Cuestionario', 'Adopción', '8', '16', '¿Con qué frecuencia involucras a Finanzas, Operaciones y TI en la definición de casos de uso de IA para categorías estratégicas de Compras?', 'Multiple Choice (escala Likert A–E)', '["Nunca", "Rara vez (≤ 1/mes)", "Ocasionalmente", "Frecuente (semanal)", "Muy frecuentemente"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', now(), null, '["Aplicación"]'::jsonb, 2, 3),

('DCS-A17', 'Cuestionario', 'Adopción', '8', '16', '¿Con qué frecuencia reasignas esfuerzos o presupuesto de iniciativas con poco impacto hacia casos de IA en Compras con impacto probado?', 'Multiple Choice (escala Likert A–E)', '["Nunca", "Rara vez (≤ 1/mes)", "Ocasionalmente", "Frecuente (semanal)", "Muy frecuentemente"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', now(), null, '["Inversión", "Estrategia"]'::jsonb, 2, 3),

('DCS-A18', 'Cuestionario', 'Adopción', '8', '16', '¿Con qué frecuencia revisas que los modelos de scoring de proveedores no generen sesgos injustos, por ejemplo penalizar sistemáticamente a ciertos tipos de proveedores sin razón objetiva?', 'Multiple Choice (escala Likert A–E)', '["Nunca", "Rara vez (≤ 1/mes)", "Ocasionalmente", "Frecuente (semanal)", "Muy frecuentemente"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', now(), null, '["Estrategia"]'::jsonb, 2, 3),

('DCS-A19', 'Cuestionario', 'Adopción', '8', '16', '¿Con qué frecuencia revisas y actualizas el roadmap de IA de Compras o Supply, alineándolo con la estrategia global de la empresa?', 'Multiple Choice (escala Likert A–E)', '["Nunca", "Rara vez (≤ 1/mes)", "Ocasionalmente", "Frecuente (semanal)", "Muy frecuentemente"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', now(), null, '["Estrategia"]'::jsonb, 2, 4),

('DCS-A20', 'Cuestionario', 'Adopción', '8', '16', '¿Con qué frecuencia lideras foros o comités transversales, como Compras, Finanzas, Operaciones y TI, para coordinar iniciativas de IA?', 'Multiple Choice (escala Likert A–E)', '["Nunca", "Rara vez (≤ 1/mes)", "Ocasionalmente", "Frecuente (semanal)", "Muy frecuentemente"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', now(), null, '["Estrategia"]'::jsonb, 2, 4),

('DCS-A21', 'Cuestionario', 'Adopción', '8', '16', '¿Con qué frecuencia revisas, junto con TI y Legal, los riesgos de uso de IA con proveedores, como datos, cumplimiento y contratos?', 'Multiple Choice (escala Likert A–E)', '["Nunca", "Rara vez (≤ 1/mes)", "Ocasionalmente", "Frecuente (semanal)", "Muy frecuentemente"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', now(), null, '["Estrategia", "Aplicación"]'::jsonb, 2, 4),

('DCS-A22', 'Cuestionario', 'Adopción', '8', '16', '¿Con qué frecuencia reasignas recursos, como personas y presupuesto, de iniciativas tradicionales de Compras hacia proyectos de IA con mejor retorno de inversión comprobado?', 'Multiple Choice (escala Likert A–E)', '["Nunca", "Rara vez (≤ 1/mes)", "Ocasionalmente", "Frecuente (semanal)", "Muy frecuentemente"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', now(), null, '["Inversión", "Estrategia"]'::jsonb, 2, 4),

('DCS-A23', 'Cuestionario', 'Adopción', '8', '16', '¿Con qué frecuencia promueves que los indicadores clave del área, como ahorro, nivel de servicio, riesgo y ESG, incluyan métricas específicas relacionadas con el impacto de la IA?', 'Multiple Choice (escala Likert A–E)', '["Nunca", "Rara vez (≤ 1/mes)", "Ocasionalmente", "Frecuente (semanal)", "Muy frecuentemente"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', now(), null, '["Estrategia", "Productividad"]'::jsonb, 2, 4),

('DCS-A24', 'Cuestionario', 'Adopción', '8', '16', '¿Con qué frecuencia impulsas programas de formación diferenciada en IA para tu equipo, por ejemplo analistas, compradores y jefaturas, según su rol?', 'Multiple Choice (escala Likert A–E)', '["Nunca", "Rara vez (≤ 1/mes)", "Ocasionalmente", "Frecuente (semanal)", "Muy frecuentemente"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', now(), null, '["Aplicación"]'::jsonb, 2, 4),

('DCS-A25', 'Cuestionario', 'Adopción', '8', '16', '¿Con qué frecuencia impulsas proyectos que usan IA avanzada, como optimización, simulación o gemelos digitales, para rediseñar la red de suministro y no solo optimizar compras puntuales?', 'Multiple Choice (escala Likert A–E)', '["Nunca", "Rara vez (≤ 1/mes)", "Ocasionalmente", "Frecuente (semanal)", "Muy frecuentemente"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', now(), null, '["Productividad"]'::jsonb, 2, 5),

('DCS-A26', 'Cuestionario', 'Adopción', '8', '16', '¿Con qué frecuencia impulsas iniciativas conjuntas con proveedores estratégicos para compartir datos y modelos de IA, como pronósticos compartidos, mantenimiento predictivo o planificación conjunta?', 'Multiple Choice (escala Likert A–E)', '["Nunca", "Rara vez (≤ 1/mes)", "Ocasionalmente", "Frecuente (semanal)", "Muy frecuentemente"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', now(), null, '["Estrategia", "Aplicación"]'::jsonb, 2, 5),

('DCS-A27', 'Cuestionario', 'Adopción', '8', '16', '¿Con qué frecuencia presentas en foros internos o externos, como comités ejecutivos, conferencias o asociaciones, los resultados de la transformación de Compras habilitada por IA?', 'Multiple Choice (escala Likert A–E)', '["Nunca", "Rara vez (≤ 1/mes)", "Ocasionalmente", "Frecuente (semanal)", "Muy frecuentemente"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', now(), null, '["Aplicación", "Productividad"]'::jsonb, 2, 5),

('DCS-A28', 'Cuestionario', 'Adopción', '8', '16', '¿Con qué frecuencia cuestionas activamente modelos de IA existentes, por ejemplo criterios de scoring, pesos y variables, para reducir sesgos y mejorar su alineación con objetivos ESG y de resiliencia?', 'Multiple Choice (escala Likert A–E)', '["Nunca", "Rara vez (≤ 1/mes)", "Ocasionalmente", "Frecuente (semanal)", "Muy frecuentemente"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', now(), null, '["Estrategia"]'::jsonb, 2, 5),

('DCS-A29', 'Cuestionario', 'Adopción', '8', '16', '¿Con qué frecuencia decides, a nivel de dirección, reequilibrar el portafolio de inversiones de CAPEX u OPEX para dar más peso a iniciativas de datos e IA en Compras o Supply frente a iniciativas tradicionales?', 'Multiple Choice (escala Likert A–E)', '["Nunca", "Rara vez (≤ 1/mes)", "Ocasionalmente", "Frecuente (semanal)", "Muy frecuentemente"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', now(), null, '["Estrategia", "Aplicación"]'::jsonb, 2, 5),

('DCS-A30', 'Cuestionario', 'Adopción', '8', '16', '¿Con qué frecuencia conectas explícitamente los resultados de IA en Compras, como ahorro, resiliencia, ESG e innovación, con la narrativa estratégica hacia el CEO y el Directorio?', 'Multiple Choice (escala Likert A–E)', '["Nunca", "Rara vez (≤ 1/mes)", "Ocasionalmente", "Frecuente (semanal)", "Muy frecuentemente"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', now(), null, '["Productividad"]'::jsonb, 2, 5);

-- CONOCIMIENTO - Rol 16
INSERT INTO "public"."preguntas" ("codigo", "section", "bloque", "area_id", "exclusivo_rol_id", "texto", "tipo", "opciones", "locale", "peso", "escala", "scoring", "created_at", "respuesta_correcta", "dimension", "exclusivo_nivel_id", "dificultad") VALUES
('DCS-C1', 'Cuestionario', 'Conocimiento', '8', '16', 'En Compras, ¿qué describe mejor el término inteligencia artificial (IA)? A) Cualquier software que automatiza pedidos de compra B) Sistemas que aplican reglas fijas preprogramadas sin aprender C) Tecnologías que usan datos para aprender patrones y apoyar decisiones de forma automática D) Robots físicos que mueven cajas en el almacén', 'Multiple Choice (una respuesta)', '["Cualquier software que automatiza pedidos de compra", "Sistemas que aplican reglas fijas preprogramadas sin aprender", "Tecnologías que usan datos para aprender patrones y apoyar decisiones de forma automática", "Robots físicos que mueven cajas en el almacén"]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', now(), 'Tecnologías que usan datos para aprender patrones y apoyar decisiones de forma automática', '["Conocimiento", "Aplicación"]'::jsonb, 2, 1),

('DCS-C2', 'Cuestionario', 'Conocimiento', '8', '16', '¿Cuál es un ejemplo sencillo de IA que ya podría estar presente en tu ERP de compras? A) El módulo de aprobación manual de órdenes B) El registro histórico de proveedores C) La sugerencia automática de proveedor en función de pedidos anteriores D) La numeración secuencial de órdenes de compra', 'Multiple Choice (una respuesta)', '["El módulo de aprobación manual de órdenes", "El registro histórico de proveedores", "La sugerencia automática de proveedor en función de pedidos anteriores", "La numeración secuencial de órdenes de compra"]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', now(), 'La sugerencia automática de proveedor en función de pedidos anteriores', '["Conocimiento"]'::jsonb, 2, 1),

('DCS-C3', 'Cuestionario', 'Conocimiento', '8', '16', '¿Cuál de las siguientes tareas de Compras es más adecuada para empezar a usar IA de forma básica? A) Definir la estrategia global de categorías a 5 años B) Hacer un análisis simple de gasto por proveedor usando datos históricos C) Negociar cara a cara condiciones críticas con proveedores estratégicos D) Aprobar políticas corporativas de compliance', 'Multiple Choice (una respuesta)', '["Definir la estrategia global de categorías a 5 años", "Hacer un análisis simple de gasto por proveedor usando datos históricos", "Negociar cara a cara condiciones críticas con proveedores estratégicos", "Aprobar políticas corporativas de compliance"]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', now(), 'Hacer un análisis simple de gasto por proveedor usando datos históricos', '["Conocimiento", "Estrategia", "Aplicación"]'::jsonb, 2, 1),

('DCS-C4', 'Cuestionario', 'Conocimiento', '8', '16', 'En una relación con proveedores, ¿qué riesgo básico existe al usar IA sin revisar sus resultados? A) Que desaparezcan las órdenes de compra del ERP B) Que la IA siempre negocie mejor que un humano C) Que la IA se equivoque por datos incompletos o sesgados D) Que la IA aumente automáticamente los precios', 'Multiple Choice (una respuesta)', '["Que desaparezcan las órdenes de compra del ERP", "Que la IA siempre negocie mejor que un humano", "Que la IA se equivoque por datos incompletos o sesgados", "Que la IA aumente automáticamente los precios"]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', now(), 'Que la IA se equivoque por datos incompletos o sesgados', '["Conocimiento", "Estrategia", "Aplicación", "Productividad"]'::jsonb, 2, 1),

('DCS-C5', 'Cuestionario', 'Conocimiento', '8', '16', '¿Cuál es una razón válida para no confiar completamente en un texto generado por un asistente de IA para enviar a un proveedor? A) Porque todos los textos generados por IA son ilegales B) Porque puede inventar datos o condiciones que no son reales C) Porque la IA no puede escribir en más de un idioma D) Porque los proveedores saben reconocer siempre textos generados por IA', 'Multiple Choice (una respuesta)', '["Porque todos los textos generados por IA son ilegales", "Porque puede inventar datos o condiciones que no son reales", "Porque la IA no puede escribir en más de un idioma", "Porque los proveedores saben reconocer siempre textos generados por IA"]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', now(), 'Porque puede inventar datos o condiciones que no son reales', '["Conocimiento", "Aplicación"]'::jsonb, 2, 1),

('DCS-C6', 'Cuestionario', 'Conocimiento', '8', '16', 'Al planear invertir tiempo del equipo en formarse en IA para Compras, ¿qué criterio básico debería considerarse? A) Solo el costo de las licencias de software B) Que la formación esté de moda en redes sociales C) El impacto potencial en ahorro, riesgo y eficiencia del área D) Que todos los proveedores usen la misma herramienta', 'Multiple Choice (una respuesta)', '["Solo el costo de las licencias de software", "Que la formación esté de moda en redes sociales", "El impacto potencial en ahorro, riesgo y eficiencia del área", "Que todos los proveedores usen la misma herramienta"]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', now(), 'El impacto potencial en ahorro, riesgo y eficiencia del área', '["Aplicación", "Inversión", "Estrategia", "Productividad", "Conocimiento"]'::jsonb, 2, 1),

('DCS-C7', 'Cuestionario', 'Conocimiento', '8', '16', '¿Cuál es un uso típico de IA en la clasificación de gasto en Compras? A) Generar contratos sin revisión legal B) Asignar automáticamente categorías a facturas y órdenes según descripciones y patrones C) Decidir automáticamente qué proveedor despedir D) Aprobar pagos sin intervención humana', 'Multiple Choice (una respuesta)', '["Generar contratos sin revisión legal", "Asignar automáticamente categorías a facturas y órdenes según descripciones y patrones", "Decidir automáticamente qué proveedor despedir", "Aprobar pagos sin intervención humana"]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', now(), 'Asignar automáticamente categorías a facturas y órdenes según descripciones y patrones', '["Conocimiento", "Aplicación"]'::jsonb, 2, 2),

('DCS-C8', 'Cuestionario', 'Conocimiento', '8', '16', '¿Cuál es una buena práctica al usar IA para redactar una RFP simple? A) Usar el texto que propone la IA sin cambios B) Pedir a la IA que incluya precios y plazos inventados C) Revisar y adaptar el texto a las políticas internas y al contexto del proveedor D) Enviar la RFP sin que nadie del área la revise', 'Multiple Choice (una respuesta)', '["Usar el texto que propone la IA sin cambios", "Pedir a la IA que incluya precios y plazos inventados", "Revisar y adaptar el texto a las políticas internas y al contexto del proveedor", "Enviar la RFP sin que nadie del área la revise"]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', now(), 'Revisar y adaptar el texto a las políticas internas y al contexto del proveedor', '["Conocimiento"]'::jsonb, 2, 2),

('DCS-C9', 'Cuestionario', 'Conocimiento', '8', '16', '¿Qué ventaja aporta la IA al evaluar varias propuestas de proveedores para una misma categoría? A) Garantiza que la propuesta más barata siempre es la mejor B) Elimina por completo la necesidad de analistas C) Permite comparar múltiples variables, como precio, calidad, plazo y riesgo, de forma más rápida y consistente D) Impide que el equipo participe en la decisión', 'Multiple Choice (una respuesta)', '["Garantiza que la propuesta más barata siempre es la mejor", "Elimina por completo la necesidad de analistas", "Permite comparar múltiples variables, como precio, calidad, plazo y riesgo, de forma más rápida y consistente", "Impide que el equipo participe en la decisión"]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', now(), 'Permite comparar múltiples variables, como precio, calidad, plazo y riesgo, de forma más rápida y consistente', '["Conocimiento", "Estrategia", "Aplicación"]'::jsonb, 2, 2),

('DCS-C10', 'Cuestionario', 'Conocimiento', '8', '16', '¿Cuál es un riesgo de fiarse solo del historial de desempeño de un proveedor cuando la IA sugiere renovarle el contrato? A) Que el proveedor cambie su nombre B) Que la IA ignore cambios recientes del mercado o problemas no registrados en los datos C) Que el ERP deje de funcionar D) Que la IA reduzca los precios por error', 'Multiple Choice (una respuesta)', '["Que el proveedor cambie su nombre", "Que la IA ignore cambios recientes del mercado o problemas no registrados en los datos", "Que el ERP deje de funcionar", "Que la IA reduzca los precios por error"]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', now(), 'Que la IA ignore cambios recientes del mercado o problemas no registrados en los datos', '["Conocimiento", "Estrategia", "Aplicación"]'::jsonb, 2, 2),

('DCS-C11', 'Cuestionario', 'Conocimiento', '8', '16', 'En términos de inversión, ¿qué enfoque tiene más sentido para la Dirección de Compras que empieza a usar IA? A) Comprar la herramienta de IA más cara del mercado para todo el grupo B) Empezar con pruebas piloto en algunas categorías clave antes de escalar C) No invertir en formación del equipo D) Exigir a todos los proveedores que usen la misma IA', 'Multiple Choice (una respuesta)', '["Comprar la herramienta de IA más cara del mercado para todo el grupo", "Empezar con pruebas piloto en algunas categorías clave antes de escalar", "No invertir en formación del equipo", "Exigir a todos los proveedores que usen la misma IA"]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', now(), 'Empezar con pruebas piloto en algunas categorías clave antes de escalar', '["Conocimiento", "Inversión", "Aplicación"]'::jsonb, 2, 2),

('DCS-C12', 'Cuestionario', 'Conocimiento', '8', '16', '¿Cuál de estas afirmaciones sobre IA y negociación con proveedores es más razonable? A) La IA puede simular escenarios y apoyar la preparación de la negociación, pero la decisión final debe ser humana B) La IA debe decidir las condiciones finales sin intervención humana C) La IA siempre consigue mejores condiciones que un negociador experto D) La IA puede reemplazar completamente al equipo de Compras', 'Multiple Choice (una respuesta)', '["La IA puede simular escenarios y apoyar la preparación de la negociación, pero la decisión final debe ser humana", "La IA debe decidir las condiciones finales sin intervención humana", "La IA siempre consigue mejores condiciones que un negociador experto", "La IA puede reemplazar completamente al equipo de Compras"]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', now(), 'La IA puede simular escenarios y apoyar la preparación de la negociación, pero la decisión final debe ser humana', '["Conocimiento", "Aplicación"]'::jsonb, 2, 2),

('DCS-C13', 'Cuestionario', 'Conocimiento', '8', '16', '¿Qué hace típicamente un módulo de analítica de gasto con IA? A) Solo registra facturas B) Analiza patrones de gasto, categoriza y detecta oportunidades de consolidación o ahorro C) Genera órdenes de compra sin datos D) Borra proveedores inactivos', 'Multiple Choice (una respuesta)', '["Solo registra facturas", "Analiza patrones de gasto, categoriza y detecta oportunidades de consolidación o ahorro", "Genera órdenes de compra sin datos", "Borra proveedores inactivos"]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', now(), 'Analiza patrones de gasto, categoriza y detecta oportunidades de consolidación o ahorro', '["Conocimiento", "Aplicación", "Productividad"]'::jsonb, 2, 3),

('DCS-C14', 'Cuestionario', 'Conocimiento', '8', '16', 'Al usar IA para scoring de proveedores, ¿qué es importante incluir además de precio? A) Únicamente el volumen de compras B) Variables como desempeño histórico, calidad, cumplimiento, riesgo financiero y criterios ESG C) Solo la opinión del director de Compras D) Exclusivamente el plazo de pago', 'Multiple Choice (una respuesta)', '["Únicamente el volumen de compras", "Variables como desempeño histórico, calidad, cumplimiento, riesgo financiero y criterios ESG", "Solo la opinión del director de Compras", "Exclusivamente el plazo de pago"]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', now(), 'Variables como desempeño histórico, calidad, cumplimiento, riesgo financiero y criterios ESG', '["Conocimiento", "Inversión", "Estrategia"]'::jsonb, 2, 3),

('DCS-C15', 'Cuestionario', 'Conocimiento', '8', '16', '¿Qué describe mejor un modelo de pronóstico de demanda apoyado en IA para decisiones de compra? A) Un calendario fijo de compras sin cambio B) Un modelo que usa datos históricos y variables externas para estimar demanda futura C) Una estimación manual basada solo en experiencia D) Un proceso de aprobación de contratos', 'Multiple Choice (una respuesta)', '["Un calendario fijo de compras sin cambio", "Un modelo que usa datos históricos y variables externas para estimar demanda futura", "Una estimación manual basada solo en experiencia", "Un proceso de aprobación de contratos"]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', now(), 'Un modelo que usa datos históricos y variables externas para estimar demanda futura', '["Conocimiento", "Aplicación"]'::jsonb, 2, 3),

('DCS-C16', 'Cuestionario', 'Conocimiento', '8', '16', '¿Cuál es un riesgo al usar IA para optimizar el número de proveedores o consolidación? A) Reducir proveedores sin considerar riesgo de dependencia y resiliencia de la cadena B) Aumentar siempre el número de proveedores C) Eliminar la necesidad de contratos escritos D) Hacer irrelevante la gestión de inventarios', 'Multiple Choice (una respuesta)', '["Reducir proveedores sin considerar riesgo de dependencia y resiliencia de la cadena", "Aumentar siempre el número de proveedores", "Eliminar la necesidad de contratos escritos", "Hacer irrelevante la gestión de inventarios"]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', now(), 'Reducir proveedores sin considerar riesgo de dependencia y resiliencia de la cadena', '["Conocimiento", "Estrategia", "Productividad"]'::jsonb, 2, 3),

('DCS-C17', 'Cuestionario', 'Conocimiento', '8', '16', 'Cuando se integra IA en una categoría clave, ¿qué indicador es más relevante para medir impacto? A) Número de correos enviados a proveedores B) Cantidad de reuniones internas C) Ahorro logrado, variación de riesgo y nivel de servicio medidos antes y después D) Número de presentaciones generadas', 'Multiple Choice (una respuesta)', '["Número de correos enviados a proveedores", "Cantidad de reuniones internas", "Ahorro logrado, variación de riesgo y nivel de servicio medidos antes y después", "Número de presentaciones generadas"]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', now(), 'Ahorro logrado, variación de riesgo y nivel de servicio medidos antes y después', '["Conocimiento", "Estrategia", "Productividad"]'::jsonb, 2, 3),

('DCS-C18', 'Cuestionario', 'Conocimiento', '8', '16', '¿Cuál es una práctica adecuada de gobierno de datos para IA en Compras? A) Permitir que cada usuario cargue datos sin controles B) No documentar el origen de los datos C) Definir responsables de calidad de datos y procesos de limpieza y actualización D) Mezclar datos confidenciales de proveedores con datos públicos sin reglas', 'Multiple Choice (una respuesta)', '["Permitir que cada usuario cargue datos sin controles", "No documentar el origen de los datos", "Definir responsables de calidad de datos y procesos de limpieza y actualización", "Mezclar datos confidenciales de proveedores con datos públicos sin reglas"]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', now(), 'Definir responsables de calidad de datos y procesos de limpieza y actualización', '["Conocimiento", "Estrategia", "Aplicación"]'::jsonb, 2, 3),

('DCS-C19', 'Cuestionario', 'Conocimiento', '8', '16', '¿Qué significa orquestar una estrategia de IA en Compras o Supply a nivel dirección de área? A) Permitir que cada categoría use la IA como quiera B) Definir una visión, priorizar casos de uso, alinear procesos, personas y tecnología, y medir resultados C) Dejar toda la responsabilidad en TI D) Usar cualquier herramienta gratuita sin alineación con el negocio', 'Multiple Choice (una respuesta)', '["Permitir que cada categoría use la IA como quiera", "Definir una visión, priorizar casos de uso, alinear procesos, personas y tecnología, y medir resultados", "Dejar toda la responsabilidad en TI", "Usar cualquier herramienta gratuita sin alineación con el negocio"]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', now(), 'Definir una visión, priorizar casos de uso, alinear procesos, personas y tecnología, y medir resultados', '["Conocimiento", "Estrategia", "Aplicación", "Productividad"]'::jsonb, 2, 4),

('DCS-C20', 'Cuestionario', 'Conocimiento', '8', '16', '¿Cuál es un criterio clave para priorizar casos de uso de IA en el portafolio de Compras? A) Qué proveedor de software hizo la mejor presentación comercial B) Qué iniciativa usa la tecnología más novedosa C) El impacto esperado en ahorro, riesgo, servicio y alineación con la estrategia de negocio D) Qué proyecto requiere menos esfuerzo del equipo', 'Multiple Choice (una respuesta)', '["Qué proveedor de software hizo la mejor presentación comercial", "Qué iniciativa usa la tecnología más novedosa", "El impacto esperado en ahorro, riesgo, servicio y alineación con la estrategia de negocio", "Qué proyecto requiere menos esfuerzo del equipo"]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', now(), 'El impacto esperado en ahorro, riesgo, servicio y alineación con la estrategia de negocio', '["Conocimiento", "Estrategia", "Aplicación", "Productividad"]'::jsonb, 2, 4),

('DCS-C21', 'Cuestionario', 'Conocimiento', '8', '16', '¿Qué describe mejor el concepto de source-to-pay habilitado con IA? A) Solo el proceso de pago a proveedores B) Todo el ciclo desde la identificación de necesidad, sourcing y contratación hasta el pago, con analítica y automatización inteligentes en cada etapa C) Únicamente la negociación D) Solo la gestión de contratos', 'Multiple Choice (una respuesta)', '["Solo el proceso de pago a proveedores", "Todo el ciclo desde la identificación de necesidad, sourcing y contratación hasta el pago, con analítica y automatización inteligentes en cada etapa", "Únicamente la negociación", "Solo la gestión de contratos"]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', now(), 'Todo el ciclo desde la identificación de necesidad, sourcing y contratación hasta el pago, con analítica y automatización inteligentes en cada etapa', '["Conocimiento", "Aplicación"]'::jsonb, 2, 4),

('DCS-C22', 'Cuestionario', 'Conocimiento', '8', '16', '¿Cuál es un componente clave de un marco ético para uso de IA en Compras? A) Ocultar a los proveedores que se utiliza IA B) No informar internamente cómo se toman decisiones C) Establecer principios y límites claros sobre qué decisiones pueden automatizarse y cuáles requieren revisión humana D) Dejar que cada analista decida sus propios criterios', 'Multiple Choice (una respuesta)', '["Ocultar a los proveedores que se utiliza IA", "No informar internamente cómo se toman decisiones", "Establecer principios y límites claros sobre qué decisiones pueden automatizarse y cuáles requieren revisión humana", "Dejar que cada analista decida sus propios criterios"]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', now(), 'Establecer principios y límites claros sobre qué decisiones pueden automatizarse y cuáles requieren revisión humana', '["Conocimiento", "Aplicación", "Productividad"]'::jsonb, 2, 4),

('DCS-C23', 'Cuestionario', 'Conocimiento', '8', '16', '¿Qué rol debería tener la Dirección de Compras en el gobierno de datos de IA? A) Ninguno, es tema exclusivo de TI B) Asegurar que los datos de Compras sean de calidad, estén normalizados y se compartan de forma segura con otros dominios C) Decidir qué datos se borran sin consultar a nadie D) Bloquear todo acceso a datos por parte de otras áreas', 'Multiple Choice (una respuesta)', '["Ninguno, es tema exclusivo de TI", "Asegurar que los datos de Compras sean de calidad, estén normalizados y se compartan de forma segura con otros dominios", "Decidir qué datos se borran sin consultar a nadie", "Bloquear todo acceso a datos por parte de otras áreas"]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', now(), 'Asegurar que los datos de Compras sean de calidad, estén normalizados y se compartan de forma segura con otros dominios', '["Conocimiento", "Aplicación"]'::jsonb, 2, 4),

('DCS-C24', 'Cuestionario', 'Conocimiento', '8', '16', 'Desde la perspectiva de inversión, ¿qué distingue a una Dirección de Compras que orquesta IA estratégicamente? A) Comprar muchas herramientas sin medir resultados B) Invertir en pocas iniciativas, pero con clara medición de retorno de inversión y escalabilidad C) Evitar cualquier inversión para no arriesgarse D) Dejar que cada categoría contrate su propia IA sin coordinación', 'Multiple Choice (una respuesta)', '["Comprar muchas herramientas sin medir resultados", "Invertir en pocas iniciativas, pero con clara medición de retorno de inversión y escalabilidad", "Evitar cualquier inversión para no arriesgarse", "Dejar que cada categoría contrate su propia IA sin coordinación"]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', now(), 'Invertir en pocas iniciativas, pero con clara medición de retorno de inversión y escalabilidad', '["Aplicación", "Inversión", "Estrategia", "Productividad", "Conocimiento"]'::jsonb, 2, 4),

('DCS-C25', 'Cuestionario', 'Conocimiento', '8', '16', '¿Qué describe mejor un gemelo digital de la cadena de suministro apoyado en IA? A) Una copia de la base de datos de proveedores B) Un modelo virtual que replica la red de suministro y permite simular escenarios y decisiones C) Un archivo de cálculo con la lista de materiales D) Un informe mensual en PDF', 'Multiple Choice (una respuesta)', '["Una copia de la base de datos de proveedores", "Un modelo virtual que replica la red de suministro y permite simular escenarios y decisiones", "Un archivo de cálculo con la lista de materiales", "Un informe mensual en PDF"]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', now(), 'Un modelo virtual que replica la red de suministro y permite simular escenarios y decisiones', '["Conocimiento", "Aplicación"]'::jsonb, 2, 5),

('DCS-C26', 'Cuestionario', 'Conocimiento', '8', '16', '¿Cuál es un uso avanzado de IA en la colaboración con proveedores estratégicos? A) Enviarles automáticamente todas las bases de datos internas B) Co-desarrollar modelos de pronóstico de demanda compartidos para planificar producción y compras C) Dejar que el proveedor decida precios sin negociación D) Obligar al proveedor a usar una única herramienta sin soporte', 'Multiple Choice (una respuesta)', '["Enviarles automáticamente todas las bases de datos internas", "Co-desarrollar modelos de pronóstico de demanda compartidos para planificar producción y compras", "Dejar que el proveedor decida precios sin negociación", "Obligar al proveedor a usar una única herramienta sin soporte"]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', now(), 'Co-desarrollar modelos de pronóstico de demanda compartidos para planificar producción y compras', '["Conocimiento", "Estrategia", "Aplicación"]'::jsonb, 2, 5),

('DCS-C27', 'Cuestionario', 'Conocimiento', '8', '16', 'En un enfoque de IA para resiliencia de la cadena de suministro, ¿qué aspecto es crítico? A) Considerar solo el costo unitario B) Ignorar riesgos geopolíticos y climáticos C) Integrar variables de riesgo, como ubicación, ESG, dependencia y capacidad, en los modelos D) Depender de un solo proveedor global', 'Multiple Choice (una respuesta)', '["Considerar solo el costo unitario", "Ignorar riesgos geopolíticos y climáticos", "Integrar variables de riesgo, como ubicación, ESG, dependencia y capacidad, en los modelos", "Depender de un solo proveedor global"]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', now(), 'Integrar variables de riesgo, como ubicación, ESG, dependencia y capacidad, en los modelos', '["Conocimiento", "Inversión", "Estrategia"]'::jsonb, 2, 5),

('DCS-C28', 'Cuestionario', 'Conocimiento', '8', '16', '¿Cuál es un ejemplo de indicador de impacto estratégico de IA para la Dirección de Compras o Supply? A) Número de correos enviados por mes B) Cantidad de reportes impresos C) Reducción de tiempo de ciclo de abastecimiento, reducción de rupturas de stock y mejora de margen gracias a decisiones soportadas por IA D) Número de licencias de software adquiridas', 'Multiple Choice (una respuesta)', '["Número de correos enviados por mes", "Cantidad de reportes impresos", "Reducción de tiempo de ciclo de abastecimiento, reducción de rupturas de stock y mejora de margen gracias a decisiones soportadas por IA", "Número de licencias de software adquiridas"]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', now(), 'Reducción de tiempo de ciclo de abastecimiento, reducción de rupturas de stock y mejora de margen gracias a decisiones soportadas por IA', '["Conocimiento", "Estrategia", "Productividad"]'::jsonb, 2, 5),

('DCS-C29', 'Cuestionario', 'Conocimiento', '8', '16', 'En términos de inversión en IA, ¿qué caracteriza a una función de Compras transformadora? A) Invertir sin coordinar con la estrategia corporativa B) Destinar presupuesto relevante y sostenido a datos, talento, herramientas y cambio cultural, con retorno medido C) Solo adquirir herramientas gratuitas D) Invertir una vez y no actualizar nunca más', 'Multiple Choice (una respuesta)', '["Invertir sin coordinar con la estrategia corporativa", "Destinar presupuesto relevante y sostenido a datos, talento, herramientas y cambio cultural, con retorno medido", "Solo adquirir herramientas gratuitas", "Invertir una vez y no actualizar nunca más"]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', now(), 'Destinar presupuesto relevante y sostenido a datos, talento, herramientas y cambio cultural, con retorno medido', '["Conocimiento", "Inversión", "Estrategia", "Aplicación"]'::jsonb, 2, 5),

('DCS-C30', 'Cuestionario', 'Conocimiento', '8', '16', 'Desde la perspectiva ética, ¿qué desafío nuevo suele aparecer al usar IA avanzada en selección de proveedores? A) Que nadie entienda los indicadores B) Que los proveedores no quieran firmar contratos C) Que los modelos puedan discriminar indirectamente a ciertos proveedores, por tamaño, país o perfil, si los datos o las variables no están bien diseñados D) Que los contratos pierdan validez legal', 'Multiple Choice (una respuesta)', '["Que nadie entienda los indicadores", "Que los proveedores no quieran firmar contratos", "Que los modelos puedan discriminar indirectamente a ciertos proveedores, por tamaño, país o perfil, si los datos o las variables no están bien diseñados", "Que los contratos pierdan validez legal"]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', now(), 'Que los modelos puedan discriminar indirectamente a ciertos proveedores, por tamaño, país o perfil, si los datos o las variables no están bien diseñados', '["Conocimiento", "Estrategia", "Aplicación"]'::jsonb, 2, 5);
