-- ============================================================================
-- PREGUNTAS PARA CEO
-- ============================================================================
-- Rol incluido:
--   - Rol ID 1: CEO (area_id: 1, nivel_id: 6)
-- ============================================================================

-- ============================================================================
-- ROL 1: CEO
-- ============================================================================

-- ADOPCIÓN - Rol 1
INSERT INTO "public"."preguntas" ("codigo", "section", "bloque", "area_id", "exclusivo_rol_id", "texto", "tipo", "opciones", "locale", "peso", "escala", "scoring", "created_at", "respuesta_correcta", "dimension", "exclusivo_nivel_id", "dificultad") VALUES
('CEO-A1', 'Cuestionario', 'Adopción', '1', '1', 'Uso herramientas de IA para resumir documentos largos (reportes, presentaciones, contratos) que me comparte mi equipo directivo.', 'Multiple Choice (escala Likert A–E)', '["Nunca", "Rara vez (≤ 1/mes)", "Ocasional (2–3/mes)", "Frecuente (semanal)", "Muy frecuente (diaria)"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', now(), null, '["Productividad", "Aplicación"]'::jsonb, 6, 1),

('CEO-A2', 'Cuestionario', 'Adopción', '1', '1', 'Cuando escucho una propuesta de proyecto de IA, hago al menos una pregunta sobre datos, riesgos o métricas de éxito.', 'Multiple Choice (escala Likert A–E)', '["Nunca", "Rara vez (≤ 1/mes)", "Ocasional (2–3/mes)", "Frecuente (semanal)", "Muy frecuente (diaria)"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', now(), null, '["Estrategia", "Aplicación"]'::jsonb, 6, 1),

('CEO-A3', 'Cuestionario', 'Adopción', '1', '1', 'Busco activamente ejemplos de cómo otros CEOs están usando IA (artículos, casos, redes, foros, pares).', 'Multiple Choice (escala Likert A–E)', '["Nunca", "Rara vez (≤ 1/mes)", "Ocasional (2–3/mes)", "Frecuente (semanal)", "Muy frecuente (diaria)"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', now(), null, '["Productividad", "Aplicación"]'::jsonb, 6, 1),

('CEO-A4', 'Cuestionario', 'Adopción', '1', '1', 'Agendo tiempo en mi semana para experimentar personalmente con herramientas de IA (no solo delego el tema al equipo).', 'Multiple Choice (escala Likert A–E)', '["Nunca", "Rara vez (≤ 1/mes)", "Ocasional (2–3/mes)", "Frecuente (semanal)", "Muy frecuente (diaria)"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', now(), null, '["Productividad", "Aplicación"]'::jsonb, 6, 1),

('CEO-A5', 'Cuestionario', 'Adopción', '1', '1', 'Incentivo a mi comité ejecutivo a explorar pequeños casos de uso de IA en sus áreas, aunque sean de bajo riesgo y alcance limitado.', 'Multiple Choice (escala Likert A–E)', '["Nunca", "Rara vez (≤ 1/mes)", "Ocasional (2–3/mes)", "Frecuente (semanal)", "Muy frecuente (diaria)"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', now(), null, '["Productividad", "Aplicación"]'::jsonb, 6, 1),

('CEO-A6', 'Cuestionario', 'Adopción', '1', '1', 'Pido que cualquier iniciativa de IA esté vinculada a indicadores de negocio claros (ventas, costos, NPS, tiempos de ciclo, etc.).', 'Multiple Choice (escala Likert A–E)', '["Nunca", "Rara vez (≤ 1/mes)", "Ocasional (2–3/mes)", "Frecuente (semanal)", "Muy frecuente (diaria)"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', now(), null, '["Estrategia", "Aplicación"]'::jsonb, 6, 1),

('CEO-A7', 'Cuestionario', 'Adopción', '1', '1', 'Utilizo IA para redactar o pulir discursos, cartas a accionistas y mensajes clave a toda la organización.', 'Multiple Choice (escala Likert A–E)', '["Nunca", "Rara vez (≤ 1/mes)", "Ocasional (2–3/mes)", "Frecuente (semanal)", "Muy frecuente (diaria)"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', now(), null, '["Productividad", "Aplicación"]'::jsonb, 6, 2),

('CEO-A8', 'Cuestionario', 'Adopción', '1', '1', 'Antes de reuniones importantes (consejo, regulador, grandes clientes), uso IA para simular preguntas difíciles y preparar posibles respuestas.', 'Multiple Choice (escala Likert A–E)', '["Nunca", "Rara vez (≤ 1/mes)", "Ocasional (2–3/mes)", "Frecuente (semanal)", "Muy frecuente (diaria)"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', now(), null, '["Productividad", "Aplicación"]'::jsonb, 6, 2),

('CEO-A9', 'Cuestionario', 'Adopción', '1', '1', 'Comparto con mi equipo directivo ejemplos concretos de cómo la IA me ayuda en mi trabajo diario e invito a que prueben prácticas similares.', 'Multiple Choice (escala Likert A–E)', '["Nunca", "Rara vez (≤ 1/mes)", "Ocasional (2–3/mes)", "Frecuente (semanal)", "Muy frecuente (diaria)"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', now(), null, '["Productividad", "Aplicación"]'::jsonb, 6, 2),

('CEO-A10', 'Cuestionario', 'Adopción', '1', '1', 'He definido reglas personales sobre qué tipo de información sensible NO introducir en herramientas de IA, y las comunico a mi equipo.', 'Multiple Choice (escala Likert A–E)', '["Nunca", "Rara vez (≤ 1/mes)", "Ocasional (2–3/mes)", "Frecuente (semanal)", "Muy frecuente (diaria)"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', now(), null, '["Inversión", "Estrategia"]'::jsonb, 6, 2),

('CEO-A11', 'Cuestionario', 'Adopción', '1', '1', 'Dedico una parte explícita de mi agenda (por ejemplo, una hora a la semana) a explorar nuevos casos de uso de IA relevantes para las distintas áreas del negocio.', 'Multiple Choice (escala Likert A–E)', '["Nunca", "Rara vez (≤ 1/mes)", "Ocasional (2–3/mes)", "Frecuente (semanal)", "Muy frecuente (diaria)"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', now(), null, '["Productividad", "Aplicación"]'::jsonb, 6, 2),

('CEO-A12', 'Cuestionario', 'Adopción', '1', '1', 'Pido a mis reportes directos que, al presentarme proyectos, incluyan si han evaluado el uso de IA y con qué impacto estimado.', 'Multiple Choice (escala Likert A–E)', '["Nunca", "Rara vez (≤ 1/mes)", "Ocasional (2–3/mes)", "Frecuente (semanal)", "Muy frecuente (diaria)"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', now(), null, '["Productividad", "Estrategia"]'::jsonb, 6, 2),

('CEO-A13', 'Cuestionario', 'Adopción', '1', '1', 'Reviso regularmente resultados de pilotos de IA (KPIs de negocio, aprendizaje, siguientes pasos) con mi equipo ejecutivo.', 'Multiple Choice (escala Likert A–E)', '["Nunca", "Rara vez (≤ 1/mes)", "Ocasional (2–3/mes)", "Frecuente (semanal)", "Muy frecuente (diaria)"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', now(), null, '["Productividad", "Estrategia"]'::jsonb, 6, 3),

('CEO-A14', 'Cuestionario', 'Adopción', '1', '1', 'Asigno responsables claros (dueños de negocio y de datos/tecnología) para cada piloto de IA.', 'Multiple Choice (escala Likert A–E)', '["Nunca", "Rara vez (≤ 1/mes)", "Ocasional (2–3/mes)", "Frecuente (semanal)", "Muy frecuente (diaria)"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', now(), null, '["Estrategia", "Aplicación"]'::jsonb, 6, 3),

('CEO-A15', 'Cuestionario', 'Adopción', '1', '1', 'Estoy dispuesto a detener o rediseñar un piloto de IA cuando los resultados no justifican la inversión, aun si la tecnología es “atractiva”.', 'Multiple Choice (escala Likert A–E)', '["Nunca", "Rara vez (≤ 1/mes)", "Ocasional (2–3/mes)", "Frecuente (semanal)", "Muy frecuente (diaria)"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', now(), null, '["Inversión", "Estrategia"]'::jsonb, 6, 3),

('CEO-A16', 'Cuestionario', 'Adopción', '1', '1', 'Pido a mis equipos que, en los pilotos de IA, documenten aprendizajes para acelerar iniciativas futuras (lo que funcionó y lo que no).', 'Multiple Choice (escala Likert A–E)', '["Nunca", "Rara vez (≤ 1/mes)", "Ocasional (2–3/mes)", "Frecuente (semanal)", "Muy frecuente (diaria)"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', now(), null, '["Estrategia", "Aplicación"]'::jsonb, 6, 3),

('CEO-A17', 'Cuestionario', 'Adopción', '1', '1', 'Utilizo IA para explorar escenarios de negocio (proyecciones, sensibilidad, supuestos) a partir de datos de pilotos.', 'Multiple Choice (escala Likert A–E)', '["Nunca", "Rara vez (≤ 1/mes)", "Ocasional (2–3/mes)", "Frecuente (semanal)", "Muy frecuente (diaria)"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', now(), null, '["Estrategia", "Aplicación"]'::jsonb, 6, 3),

('CEO-A18', 'Cuestionario', 'Adopción', '1', '1', 'He tomado al menos una decisión concreta de inversión (más, menos o reasignación de presupuesto) basada en los resultados de un piloto de IA.', 'Multiple Choice (escala Likert A–E)', '["Nunca", "Rara vez (≤ 1/mes)", "Ocasional (2–3/mes)", "Frecuente (semanal)", "Muy frecuente (diaria)"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', now(), null, '["Inversión", "Estrategia"]'::jsonb, 6, 3),

('CEO-A19', 'Cuestionario', 'Adopción', '1', '1', 'Hemos definido y comunicamos una hoja de ruta de IA con casos de uso prioritarios, capacidades y objetivos de negocio.', 'Multiple Choice (escala Likert A–E)', '["Nunca", "Rara vez (≤ 1/mes)", "Ocasional (2–3/mes)", "Frecuente (semanal)", "Muy frecuente (diaria)"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', now(), null, '["Estrategia", "Aplicación"]'::jsonb, 6, 4),

('CEO-A20', 'Cuestionario', 'Adopción', '1', '1', 'Existen roles y estructuras formales (CoE, equipo de datos/IA, champions en áreas) que coordinan y acompañan proyectos de IA.', 'Multiple Choice (escala Likert A–E)', '["Nunca", "Rara vez (≤ 1/mes)", "Ocasional (2–3/mes)", "Frecuente (semanal)", "Muy frecuente (diaria)"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', now(), null, '["Estrategia", "Aplicación"]'::jsonb, 6, 4),

('CEO-A21', 'Cuestionario', 'Adopción', '1', '1', 'Superviso que proyectos de IA en diferentes áreas compartan plataformas de datos y estándares, evitando silos y duplicidades.', 'Multiple Choice (escala Likert A–E)', '["Nunca", "Rara vez (≤ 1/mes)", "Ocasional (2–3/mes)", "Frecuente (semanal)", "Muy frecuente (diaria)"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', now(), null, '["Estrategia", "Aplicación"]'::jsonb, 6, 4),

('CEO-A22', 'Cuestionario', 'Adopción', '1', '1', 'En las reuniones de seguimiento estratégico, revisamos indicadores de impacto de IA en P&L (ingresos, costos, riesgos).', 'Multiple Choice (escala Likert A–E)', '["Nunca", "Rara vez (≤ 1/mes)", "Ocasional (2–3/mes)", "Frecuente (semanal)", "Muy frecuente (diaria)"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', now(), null, '["Productividad", "Estrategia"]'::jsonb, 6, 4),

('CEO-A23', 'Cuestionario', 'Adopción', '1', '1', 'He aprobado programas de formación en IA y analítica para directivos y mandos medios, con seguimiento de participación y resultados.', 'Multiple Choice (escala Likert A–E)', '["Nunca", "Rara vez (≤ 1/mes)", "Ocasional (2–3/mes)", "Frecuente (semanal)", "Muy frecuente (diaria)"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', now(), null, '["Inversión", "Estrategia"]'::jsonb, 6, 4),

('CEO-A24', 'Cuestionario', 'Adopción', '1', '1', 'Promuevo que la IA sea vista como un copiloto que aumenta el talento humano, no como sustituto automático, en mis mensajes y decisiones.', 'Multiple Choice (escala Likert A–E)', '["Nunca", "Rara vez (≤ 1/mes)", "Ocasional (2–3/mes)", "Frecuente (semanal)", "Muy frecuente (diaria)"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', now(), null, '["Estrategia", "Aplicación"]'::jsonb, 6, 4),

('CEO-A25', 'Cuestionario', 'Adopción', '1', '1', 'He impulsado cambios en el modelo de negocio (nuevos productos/servicios, pricing, canales) explícitamente habilitados por IA y datos.', 'Multiple Choice (escala Likert A–E)', '["Nunca", "Rara vez (≤ 1/mes)", "Ocasional (2–3/mes)", "Frecuente (semanal)", "Muy frecuente (diaria)"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', now(), null, '["Productividad", "Aplicación"]'::jsonb, 6, 5),

('CEO-A26', 'Cuestionario', 'Adopción', '1', '1', 'Uso IA de forma intensiva para revisar portafolios de proyectos, priorizar y reasignar recursos en función del valor generado o esperado.', 'Multiple Choice (escala Likert A–E)', '["Nunca", "Rara vez (≤ 1/mes)", "Ocasional (2–3/mes)", "Frecuente (semanal)", "Muy frecuente (diaria)"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', now(), null, '["Inversión", "Estrategia"]'::jsonb, 6, 5),

('CEO-A27', 'Cuestionario', 'Adopción', '1', '1', 'He establecido límites claros de autonomía de IA en decisiones críticas (qué decide la máquina, qué revisa un humano, qué se audita).', 'Multiple Choice (escala Likert A–E)', '["Nunca", "Rara vez (≤ 1/mes)", "Ocasional (2–3/mes)", "Frecuente (semanal)", "Muy frecuente (diaria)"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', now(), null, '["Productividad", "Aplicación"]'::jsonb, 6, 5),

('CEO-A28', 'Cuestionario', 'Adopción', '1', '1', 'Existen métricas de valor de IA (ingresos adicionales, ahorro, reducción de riesgo, experiencia de cliente) que reviso periódicamente a nivel de consejo.', 'Multiple Choice (escala Likert A–E)', '["Nunca", "Rara vez (≤ 1/mes)", "Ocasional (2–3/mes)", "Frecuente (semanal)", "Muy frecuente (diaria)"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', now(), null, '["Productividad", "Estrategia"]'::jsonb, 6, 5),

('CEO-A29', 'Cuestionario', 'Adopción', '1', '1', 'Fomento que IA y automatización liberen tiempo de los colaboradores para trabajo de mayor valor (innovación, relación con cliente, análisis), y mido ese efecto.', 'Multiple Choice (escala Likert A–E)', '["Nunca", "Rara vez (≤ 1/mes)", "Ocasional (2–3/mes)", "Frecuente (semanal)", "Muy frecuente (diaria)"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', now(), null, '["Productividad", "Aplicación"]'::jsonb, 6, 5),

('CEO-A30', 'Cuestionario', 'Adopción', '1', '1', 'Mantengo un diálogo activo con el ecosistema externo (startups, grandes proveedores, academia, reguladores) para anticipar tendencias de IA y ajustar la estrategia.', 'Multiple Choice (escala Likert A–E)', '["Nunca", "Rara vez (≤ 1/mes)", "Ocasional (2–3/mes)", "Frecuente (semanal)", "Muy frecuente (diaria)"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', now(), null, '["Estrategia", "Aplicación"]'::jsonb, 6, 5);

-- CONOCIMIENTO - Rol 1
INSERT INTO "public"."preguntas" ("codigo", "section", "bloque", "area_id", "exclusivo_rol_id", "texto", "tipo", "opciones", "locale", "peso", "escala", "scoring", "created_at", "respuesta_correcta", "dimension", "exclusivo_nivel_id", "dificultad") VALUES
('CEO-C1', 'Cuestionario', 'Conocimiento', '1', '1', 'Como CEO, ¿cuál es la definición más precisa de inteligencia artificial (IA)?', 'Multiple Choice (una respuesta)', '["Software que solo sigue reglas fijas programadas manualmente.", "Tecnología que permite a sistemas aprender de datos y hacer predicciones o decisiones con mínima intervención humana.", "Cualquier automatización usada en la empresa, incluyendo macros de Excel.", "Robots físicos que reemplazan por completo a las personas."]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', now(), 'Tecnología que permite a sistemas aprender de datos y hacer predicciones o decisiones con mínima intervención humana.', '["Conocimiento", "Aplicación"]'::jsonb, 6, 1),

('CEO-C2', 'Cuestionario', 'Conocimiento', '1', '1', '¿Cuál de estos ejemplos describe mejor un uso de IA generativa para un CEO?', 'Multiple Choice (una respuesta)', '["Enviar correos masivos usando una lista de distribución fija.", "Usar un modelo que redacta borradores de discursos y correos a partir de instrucciones de texto.", "Hacer un presupuesto anual en Excel con fórmulas.", "Pagar publicidad en redes sociales sin segmentación."]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', now(), 'Usar un modelo que redacta borradores de discursos y correos a partir de instrucciones de texto.', '["Conocimiento", "Aplicación"]'::jsonb, 6, 1),

('CEO-C3', 'Cuestionario', 'Conocimiento', '1', '1', '¿Qué ventaja principal obtiene un CEO al usar IA para resumir reportes extensos de la organización?', 'Multiple Choice (una respuesta)', '["Evitar por completo leer cualquier reporte.", "Obtener una síntesis rápida para enfocar su atención en decisiones clave.", "Garantizar que todas las conclusiones serán correctas.", "Sustituir al CFO en el análisis financiero."]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', now(), 'Obtener una síntesis rápida para enfocar su atención en decisiones clave.', '["Conocimiento", "Estrategia"]'::jsonb, 6, 1),

('CEO-C4', 'Cuestionario', 'Conocimiento', '1', '1', 'En una primera aproximación a IA en tu empresa, ¿qué iniciativa es más razonable?', 'Multiple Choice (una respuesta)', '["Invertir de inmediato la mayoría del presupuesto de TI en IA.", "Lanzar proyectos de IA simultáneos en todas las áreas.", "Definir uno o pocos pilotos con impacto claro y datos disponibles.", "Esperar a que todos los competidores hayan implementado IA."]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', now(), 'Definir uno o pocos pilotos con impacto claro y datos disponibles.', '["Conocimiento", "Aplicación"]'::jsonb, 6, 1),

('CEO-C5', 'Cuestionario', 'Conocimiento', '1', '1', '¿Qué riesgo ético básico debe considerar un CEO al aprobar un proyecto de IA?', 'Multiple Choice (una respuesta)', '["La IA siempre será más cara que las soluciones tradicionales.", "Que el modelo reproduzca sesgos o discriminación presentes en los datos.", "Que la IA obligue a todos los clientes a usar solo canales digitales.", "Que la IA no pueda actualizarse nunca."]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', now(), 'Que el modelo reproduzca sesgos o discriminación presentes en los datos.', '["Conocimiento", "Aplicación"]'::jsonb, 6, 1),

('CEO-C6', 'Cuestionario', 'Conocimiento', '1', '1', 'Cuando tu equipo propone un “chatbot de atención al cliente con IA”, ¿qué pregunta inicial es más importante como CEO?', 'Multiple Choice (una respuesta)', '["¿Cuál es el proveedor con mejor marketing?", "¿Cuántos desarrolladores necesitamos contratar inmediatamente?", "¿Qué problema de negocio resuelve y cómo mediremos el impacto en clientes y costos?", "¿Podemos ponerle un nombre atractivo al chatbot?"]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', now(), '¿Qué problema de negocio resuelve y cómo mediremos el impacto en clientes y costos?', '["Conocimiento", "Aplicación"]'::jsonb, 6, 1),

('CEO-C7', 'Cuestionario', 'Conocimiento', '1', '1', '¿Qué es un “prompt” en herramientas de IA generativa como ChatGPT o copilots?', 'Multiple Choice (una respuesta)', '["Un programa completo escrito en un lenguaje de programación.", "El texto o instrucciones que el usuario escribe para guiar la respuesta de la IA.", "El nombre técnico del modelo de IA.", "Un archivo adjunto con datos estructurados."]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', now(), 'El texto o instrucciones que el usuario escribe para guiar la respuesta de la IA.', '["Conocimiento", "Aplicación"]'::jsonb, 6, 2),

('CEO-C8', 'Cuestionario', 'Conocimiento', '1', '1', '¿Qué afirmación sobre datos confidenciales y uso de IA es más adecuada para un CEO?', 'Multiple Choice (una respuesta)', '["Puedo introducir cualquier dato confidencial porque la IA siempre lo olvida.", "Nunca debo usar IA para ningún tipo de documento corporativo.", "Debo asegurarme de que las herramientas tengan acuerdos claros de privacidad y limitar qué información sensible se comparte.", "Los datos confidenciales solo son un riesgo en áreas financieras, no en otras."]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', now(), 'Debo asegurarme de que las herramientas tengan acuerdos claros de privacidad y limitar qué información sensible se comparte.', '["Conocimiento", "Aplicación"]'::jsonb, 6, 2),

('CEO-C9', 'Cuestionario', 'Conocimiento', '1', '1', '¿Cuál es la diferencia más relevante entre analítica descriptiva y predictiva para ti como CEO?', 'Multiple Choice (una respuesta)', '["La descriptiva es manual y la predictiva es automática.", "La descriptiva explica qué ocurrió; la predictiva estima qué podría ocurrir a futuro.", "La descriptiva usa hojas de cálculo y la predictiva usa solo gráficos.", "No hay diferencia relevante desde la perspectiva del CEO."]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', now(), 'La descriptiva explica qué ocurrió; la predictiva estima qué podría ocurrir a futuro.', '["Conocimiento", "Aplicación"]'::jsonb, 6, 2),

('CEO-C10', 'Cuestionario', 'Conocimiento', '1', '1', '¿Cuál de estos usos de IA es más apropiado para preparar una reunión de consejo?', 'Multiple Choice (una respuesta)', '["Generar automáticamente las actas firmadas de la reunión.", "Crear resúmenes ejecutivos, posibles preguntas difíciles y respuestas preliminares.", "Asignar acciones a cada consejero sin su consentimiento.", "Bloquear cualquier pregunta inesperada gracias a IA."]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', now(), 'Crear resúmenes ejecutivos, posibles preguntas difíciles y respuestas preliminares.', '["Conocimiento", "Aplicación"]'::jsonb, 6, 2),

('CEO-C11', 'Cuestionario', 'Conocimiento', '1', '1', 'Al comparar herramientas de IA para tu uso personal como CEO, ¿qué criterio es más importante?', 'Multiple Choice (una respuesta)', '["Que tenga la interfaz más llamativa.", "Que solo funcione en tu dispositivo móvil.", "Que se integre bien con tus herramientas actuales (correo, ofimática, calendario) y políticas de seguridad.", "Que tenga el logo de moda en redes sociales."]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', now(), 'Que se integre bien con tus herramientas actuales (correo, ofimática, calendario) y políticas de seguridad.', '["Conocimiento", "Aplicación"]'::jsonb, 6, 2),

('CEO-C12', 'Cuestionario', 'Conocimiento', '1', '1', '¿Cuál es un indicador temprano de que tus experimentos personales con IA empiezan a generar valor organizacional?', 'Multiple Choice (una respuesta)', '["Que solo tú uses IA sin compartir aprendizajes.", "Que tus asistentes directos copien tus prácticas y documenten casos de uso.", "Que se prohíba el uso de IA en toda la organización.", "Que el tema de IA solo se trate en reuniones informales."]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', now(), 'Que tus asistentes directos copien tus prácticas y documenten casos de uso.', '["Conocimiento", "Estrategia"]'::jsonb, 6, 2),

('CEO-C13', 'Cuestionario', 'Conocimiento', '1', '1', '¿Cuál es el propósito principal de un piloto de IA en la organización?', 'Multiple Choice (una respuesta)', '["Probar la tecnología por moda, sin métricas.", "Validar en pequeño el impacto de IA sobre un problema de negocio con datos reales.", "Sustituir de inmediato toda una función por IA.", "Probar tantos casos de uso como sea posible al mismo tiempo."]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', now(), 'Validar en pequeño el impacto de IA sobre un problema de negocio con datos reales.', '["Conocimiento", "Estrategia"]'::jsonb, 6, 3),

('CEO-C14', 'Cuestionario', 'Conocimiento', '1', '1', '¿Qué indicador es más adecuado para evaluar un piloto de IA en atención al cliente?', 'Multiple Choice (una respuesta)', '["Número de reuniones internas sobre el proyecto.", "Tasa de resolución en primer contacto y tiempo medio de respuesta.", "Tamaño del equipo de TI dedicado al proyecto.", "Cantidad de correos enviados a los clientes."]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', now(), 'Tasa de resolución en primer contacto y tiempo medio de respuesta.', '["Conocimiento", "Aplicación"]'::jsonb, 6, 3),

('CEO-C15', 'Cuestionario', 'Conocimiento', '1', '1', '¿Qué aspecto de calidad de datos debería preocuparte más como CEO al escalar pilotos de IA?', 'Multiple Choice (una respuesta)', '["Que las bases de datos tengan nombres creativos.", "Que existan duplicidades, datos incompletos o mal etiquetados que afecten los modelos.", "Que se utilicen múltiples colores en los reportes.", "Que los datos estén almacenados en varios países."]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', now(), 'Que existan duplicidades, datos incompletos o mal etiquetados que afecten los modelos.', '["Conocimiento", "Aplicación"]'::jsonb, 6, 3),

('CEO-C16', 'Cuestionario', 'Conocimiento', '1', '1', 'Si un piloto de IA genera ahorros evidentes pero es muy difícil de mantener, ¿qué decisión estratégica es más adecuada?', 'Multiple Choice (una respuesta)', '["Escalarlo de inmediato sin cambios.", "Cancelarlo sin revisar alternativas.", "Evaluar rediseñar la solución o cambiar de socio para asegurar escalabilidad y mantenimiento.", "Ignorar la opinión de TI y seguir adelante."]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', now(), 'Evaluar rediseñar la solución o cambiar de socio para asegurar escalabilidad y mantenimiento.', '["Conocimiento", "Aplicación"]'::jsonb, 6, 3),

('CEO-C17', 'Cuestionario', 'Conocimiento', '1', '1', '¿Qué rol tiene más sentido que lidere la coordinación técnica de los pilotos de IA (no la visión de negocio)?', 'Multiple Choice (una respuesta)', '["CEO directamente.", "Un Chief Data/AI Officer o un líder de datos/analítica con mandato transversal.", "Cualquier desarrollador junior.", "Solo el área de marketing."]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', now(), 'Un Chief Data/AI Officer o un líder de datos/analítica con mandato transversal.', '["Conocimiento", "Aplicación"]'::jsonb, 6, 3),

('CEO-C18', 'Cuestionario', 'Conocimiento', '1', '1', '¿Qué característica distingue a un buen caso de uso de IA para piloto en operaciones?', 'Multiple Choice (una respuesta)', '["Que sea muy visible pero con datos escasos.", "Que afecte un proceso de alto volumen, con datos suficientes y beneficio económico claro.", "Que solo involucre a una persona.", "Que dependa únicamente de hojas de cálculo manuales."]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', now(), 'Que afecte un proceso de alto volumen, con datos suficientes y beneficio económico claro.', '["Conocimiento", "Aplicación"]'::jsonb, 6, 3),

('CEO-C19', 'Cuestionario', 'Conocimiento', '1', '1', '¿Qué describe mejor una hoja de ruta de IA a nivel corporativo?', 'Multiple Choice (una respuesta)', '["Una lista de tecnologías de moda sin prioridades.", "Un plan que alinea casos de uso, datos, talento y gobierno de IA con los objetivos estratégicos de negocio.", "Un documento exclusivo del área de TI.", "Una presentación que se muestra solo una vez al consejo."]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', now(), 'Un plan que alinea casos de uso, datos, talento y gobierno de IA con los objetivos estratégicos de negocio.', '["Conocimiento", "Aplicación"]'::jsonb, 6, 4),

('CEO-C20', 'Cuestionario', 'Conocimiento', '1', '1', '¿Cuál es un modelo de gobierno de IA razonable para una organización mediana/grande?', 'Multiple Choice (una respuesta)', '["Cada área decide por su cuenta sin coordinación.", "Un modelo “hub-and-spoke” con un equipo central de IA/datos y equipos locales en las áreas.", "Centralizar todo en un solo desarrollador.", "Delegar IA únicamente a proveedores externos."]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', now(), 'Un modelo “hub-and-spoke” con un equipo central de IA/datos y equipos locales en las áreas.', '["Conocimiento", "Estrategia"]'::jsonb, 6, 4),

('CEO-C21', 'Cuestionario', 'Conocimiento', '1', '1', 'Al diseñar políticas de uso de IA para empleados, ¿qué elemento NO debería faltar?', 'Multiple Choice (una respuesta)', '["Lineamientos sobre uso de datos sensibles y confidencialidad.", "Criterios para la revisión humana de decisiones críticas.", "Permisos claros sobre qué herramientas corporativas están aprobadas.", "Un mensaje que diga “usen cualquier herramienta que encuentren en internet”."]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', now(), 'Un mensaje que diga “usen cualquier herramienta que encuentren en internet”.', '["Conocimiento", "Aplicación"]'::jsonb, 6, 4),

('CEO-C22', 'Cuestionario', 'Conocimiento', '1', '1', '¿Qué indicador a nivel CEO muestra mejor que la IA está escalando en la organización?', 'Multiple Choice (una respuesta)', '["Número de demos internas realizadas.", "Porcentaje de procesos críticos con componentes de IA medidos por impacto en P&L.", "Cantidad de correos con la palabra “IA”.", "Número de proveedores de IA contratados sin evaluación."]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', now(), 'Porcentaje de procesos críticos con componentes de IA medidos por impacto en P&L.', '["Conocimiento", "Estrategia"]'::jsonb, 6, 4),

('CEO-C23', 'Cuestionario', 'Conocimiento', '1', '1', '¿Qué enfoque de talento es más consistente con una transformación IA?', 'Multiple Choice (una respuesta)', '["Esperar que las habilidades aparezcan de forma orgánica.", "Combinación de contratación selectiva, re-skilling y formación continua para roles clave.", "Despedir a todo el personal y rehacer la plantilla desde cero.", "Limitar la IA solo al área de TI."]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', now(), 'Combinación de contratación selectiva, re-skilling y formación continua para roles clave.', '["Conocimiento", "Aplicación"]'::jsonb, 6, 4),

('CEO-C24', 'Cuestionario', 'Conocimiento', '1', '1', 'En el contexto de IA, un “centro de excelencia (CoE)” sirve principalmente para:', 'Multiple Choice (una respuesta)', '["Acumular todos los proyectos en un solo equipo y bloquear a las áreas.", "Definir estándares, mejores prácticas y apoyar a las áreas en el despliegue de casos de uso.", "Gestionar únicamente infraestructura de servidores.", "Hacer marketing interno sin responsabilidades reales."]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', now(), 'Definir estándares, mejores prácticas y apoyar a las áreas en el despliegue de casos de uso.', '["Conocimiento", "Aplicación"]'::jsonb, 6, 4),

('CEO-C25', 'Cuestionario', 'Conocimiento', '1', '1', 'Una empresa “AI-first” se caracteriza principalmente por:', 'Multiple Choice (una respuesta)', '["Tener muchas herramientas de IA aisladas en distintas áreas.", "Colocar IA en el logo corporativo.", "Diseñar productos, procesos y modelo de negocio alrededor de datos e IA como capacidades centrales.", "Subcontratar toda la IA a un solo proveedor sin estrategia propia."]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', now(), 'Diseñar productos, procesos y modelo de negocio alrededor de datos e IA como capacidades centrales.', '["Conocimiento", "Aplicación"]'::jsonb, 6, 5),

('CEO-C26', 'Cuestionario', 'Conocimiento', '1', '1', '¿Qué describe mejor el uso de agentes de IA en un contexto corporativo?', 'Multiple Choice (una respuesta)', '["Programas que solo envían correos masivos.", "Sistemas capaces de ejecutar secuencias de tareas (consultar datos, decidir, accionar) con cierto grado de autonomía supervisada.", "IA usada exclusivamente para chats simples.", "Herramientas que solo traducen textos."]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', now(), 'Sistemas capaces de ejecutar secuencias de tareas (consultar datos, decidir, accionar) con cierto grado de autonomía supervisada.', '["Conocimiento", "Aplicación"]'::jsonb, 6, 5),

('CEO-C27', 'Cuestionario', 'Conocimiento', '1', '1', '¿Qué decisión estratégica ejemplifica mejor una visión AI-first?', 'Multiple Choice (una respuesta)', '["Añadir una función de IA superficial en un producto sin cambiar el modelo de negocio.", "Rediseñar un servicio clave para que se apoye en datos en tiempo real y recomendaciones de IA como parte central del valor ofrecido.", "Comprar la licencia más cara de IA sin un caso de uso claro.", "Crear un chatbot interno sin conexión con procesos."]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', now(), 'Rediseñar un servicio clave para que se apoye en datos en tiempo real y recomendaciones de IA como parte central del valor ofrecido.', '["Conocimiento", "Aplicación"]'::jsonb, 6, 5),

('CEO-C28', 'Cuestionario', 'Conocimiento', '1', '1', '¿Qué enfoque de gestión de portafolio de IA es más adecuado para un CEO AI-first?', 'Multiple Choice (una respuesta)', '["Tratar todos los proyectos de IA igual, sin priorización.", "Mantener un portafolio balanceado entre quick wins, proyectos de escalamiento y apuestas transformacionales, con revisiones periódicas.", "Invertir solo en proyectos de muy largo plazo.", "Cambiar de prioridad cada semana según la tecnología de moda."]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', now(), 'Mantener un portafolio balanceado entre quick wins, proyectos de escalamiento y apuestas transformacionales, con revisiones periódicas.', '["Conocimiento", "Aplicación"]'::jsonb, 6, 5),

('CEO-C29', 'Cuestionario', 'Conocimiento', '1', '1', 'En términos de riesgo, ¿qué debe definir el CEO al usar IA en decisiones de alto impacto (crédito, precios, cumplimiento, empleo)?', 'Multiple Choice (una respuesta)', '["Que la IA tome decisiones finales sin intervención humana.", "Umbrales claros donde la IA sugiere y un humano decide o valida para mitigar riesgos.", "Dejar que cada área defina límites sin alineación.", "No usar IA para ninguna decisión relevante."]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', now(), 'Umbrales claros donde la IA sugiere y un humano decide o valida para mitigar riesgos.', '["Conocimiento", "Productividad"]'::jsonb, 6, 5),

('CEO-C30', 'Cuestionario', 'Conocimiento', '1', '1', '¿Qué papel juegan las alianzas externas (startups, proveedores, universidades) en una estrategia AI-first?', 'Multiple Choice (una respuesta)', '["Son irrelevantes si la empresa tiene TI interna.", "Complementan capacidades internas, aceleran innovación y acceso a talento y tecnología.", "Solo sirven para marketing.", "Deben reemplazar completamente al equipo interno."]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', now(), 'Complementan capacidades internas, aceleran innovación y acceso a talento y tecnología.', '["Conocimiento", "Estrategia"]'::jsonb, 6, 5);
