-- ============================================================================
-- PREGUNTAS PARA MIEMBROS DE MARKETING
-- ============================================================================
-- Rol incluido:
--   - Rol ID 18: Miembros de Marketing (area_id: 3, nivel_id: 4)
-- ============================================================================

-- ============================================================================
-- ROL 18: Miembros de Marketing
-- ============================================================================

-- ADOPCIÓN - Rol 18
INSERT INTO "public"."preguntas" ("codigo", "section", "bloque", "area_id", "exclusivo_rol_id", "texto", "tipo", "opciones", "locale", "peso", "escala", "scoring", "created_at", "respuesta_correcta", "dimension", "exclusivo_nivel_id", "dificultad") VALUES
('MM-A1', 'Cuestionario', 'Adopción', '3', '18', '¿Con qué frecuencia usas IA para generar borradores de textos, como publicaciones, correos electrónicos o descripciones de productos, que luego tú editas?', 'Multiple Choice (escala Likert A–E)', '["Nunca", "Rara vez (≤ 1/mes)", "Ocasional (2–3/mes)", "Casi siempre", "Siempre / Casi a diario"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', now(), null, '["Aplicación"]'::jsonb, 4, 1),

('MM-A2', 'Cuestionario', 'Adopción', '3', '18', '¿Con qué frecuencia utilizas IA para generar distintas versiones de un mismo anuncio o publicación, con el fin de probar cuál funciona mejor?', 'Multiple Choice (escala Likert A–E)', '["Nunca", "Rara vez (≤ 1/mes)", "Ocasional (2–3/mes)", "Casi siempre", "Siempre / Casi a diario"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', now(), null, '["Aplicación"]'::jsonb, 4, 1),

('MM-A3', 'Cuestionario', 'Adopción', '3', '18', '¿Con qué frecuencia usas IA para construir o refinar segmentos, por ejemplo personas parecidas a quienes compraron en los últimos 30 días?', 'Multiple Choice (escala Likert A–E)', '["Nunca", "Rara vez (≤ 1/mes)", "Ocasional (2–3/mes)", "Casi siempre", "Siempre / Casi a diario"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', now(), null, '["Aplicación"]'::jsonb, 4, 1),

('MM-A4', 'Cuestionario', 'Adopción', '3', '18', '¿Con qué frecuencia diseñas flujos complejos, por ejemplo journeys multicanal, donde la IA participa en la decisión de la siguiente mejor acción para el usuario?', 'Multiple Choice (escala Likert A–E)', '["Nunca", "Rara vez (≤ 1/mes)", "Ocasional (2–3/mes)", "Casi siempre", "Siempre / Casi a diario"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', now(), null, '["Aplicación"]'::jsonb, 4, 1),

('MM-A5', 'Cuestionario', 'Adopción', '3', '18', '¿Con qué frecuencia configuras o participas activamente en la configuración de modelos avanzados, por ejemplo de propensión a compra, abandono o recomendación, y los usas para diseñar campañas específicas?', 'Multiple Choice (escala Likert A–E)', '["Nunca", "Rara vez (≤ 1/mes)", "Ocasional (2–3/mes)", "Casi siempre", "Siempre / Casi a diario"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', now(), null, '["Aplicación"]'::jsonb, 4, 1),

('MM-A6', 'Cuestionario', 'Adopción', '3', '18', '¿Con qué frecuencia utilizas IA para obtener ideas iniciales de campañas, mensajes o conceptos creativos?', 'Multiple Choice (escala Likert A–E)', '["Nunca", "Rara vez (≤ 1/mes)", "Ocasional (2–3/mes)", "Casi siempre", "Siempre / Casi a diario"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', now(), null, '["Aplicación"]'::jsonb, 4, 1),

('MM-A7', 'Cuestionario', 'Adopción', '3', '18', '¿Con qué frecuencia usas IA para adaptar un mismo mensaje a diferentes segmentos, por ejemplo nuevos clientes frente a clientes recurrentes?', 'Multiple Choice (escala Likert A–E)', '["Nunca", "Rara vez (≤ 1/mes)", "Ocasional (2–3/mes)", "Casi siempre", "Siempre / Casi a diario"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', now(), null, '["Aplicación"]'::jsonb, 4, 2),

('MM-A8', 'Cuestionario', 'Adopción', '3', '18', '¿Con qué frecuencia diseñas experimentos, por ejemplo pruebas A o B o multivariantes, donde la IA te ayuda a generar las variantes y tú defines las reglas de medición?', 'Multiple Choice (escala Likert A–E)', '["Nunca", "Rara vez (≤ 1/mes)", "Ocasional (2–3/mes)", "Casi siempre", "Siempre / Casi a diario"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', now(), null, '["Aplicación"]'::jsonb, 4, 2),

('MM-A9', 'Cuestionario', 'Adopción', '3', '18', '¿Con qué frecuencia utilizas IA para simular diferentes escenarios de campaña, por ejemplo cambios de presupuesto, audiencia o creatividades, y estimar el impacto esperado?', 'Multiple Choice (escala Likert A–E)', '["Nunca", "Rara vez (≤ 1/mes)", "Ocasional (2–3/mes)", "Casi siempre", "Siempre / Casi a diario"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', now(), null, '["Aplicación", "Inversión"]'::jsonb, 4, 2),

('MM-A10', 'Cuestionario', 'Adopción', '3', '18', '¿Con qué frecuencia utilizas IA para priorizar oportunidades de inversión en marketing, por ejemplo decidir a qué canales o audiencias asignar más presupuesto basándote en simulaciones de retorno de inversión?', 'Multiple Choice (escala Likert A–E)', '["Nunca", "Rara vez (≤ 1/mes)", "Ocasional (2–3/mes)", "Casi siempre", "Siempre / Casi a diario"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', now(), null, '["Aplicación", "Estrategia", "Inversión"]'::jsonb, 4, 2),

('MM-A11', 'Cuestionario', 'Adopción', '3', '18', 'En tu experiencia, ¿con qué frecuencia la IA te ayuda a entregar más rápido tus tareas de contenido, por ejemplo pasar de una página en blanco a un primer borrador?', 'Multiple Choice (escala Likert A–E)', '["Nunca", "Rara vez (≤ 1/mes)", "Ocasional (2–3/mes)", "Casi siempre", "Siempre / Casi a diario"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', now(), null, '["Aplicación"]'::jsonb, 4, 2),

('MM-A12', 'Cuestionario', 'Adopción', '3', '18', '¿Con qué frecuencia utilizas IA para resumir resultados de campañas, por ejemplo copiando métricas y pidiendo un resumen con hallazgos clave?', 'Multiple Choice (escala Likert A–E)', '["Nunca", "Rara vez (≤ 1/mes)", "Ocasional (2–3/mes)", "Casi siempre", "Siempre / Casi a diario"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', now(), null, '["Productividad", "Aplicación"]'::jsonb, 4, 2),

('MM-A13', 'Cuestionario', 'Adopción', '3', '18', '¿Con qué frecuencia usas IA para sintetizar aprendizajes de varias campañas, por ejemplo proporcionando resultados de varios meses y pidiendo patrones comunes?', 'Multiple Choice (escala Likert A–E)', '["Nunca", "Rara vez (≤ 1/mes)", "Ocasional (2–3/mes)", "Casi siempre", "Siempre / Casi a diario"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', now(), null, '["Productividad"]'::jsonb, 4, 3),

('MM-A14', 'Cuestionario', 'Adopción', '3', '18', '¿Con qué frecuencia combinas datos de varias fuentes, como CRM, analítica web y plataformas de anuncios, y usas IA para generar insights integrados que guían tus decisiones?', 'Multiple Choice (escala Likert A–E)', '["Nunca", "Rara vez (≤ 1/mes)", "Ocasional (2–3/mes)", "Casi siempre", "Siempre / Casi a diario"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', now(), null, '["Productividad", "Aplicación"]'::jsonb, 4, 3),

('MM-A15', 'Cuestionario', 'Adopción', '3', '18', '¿Con qué frecuencia construyes o supervisas paneles e informes donde la IA resume resultados y propone acciones concretas, que luego discutes con tu equipo?', 'Multiple Choice (escala Likert A–E)', '["Nunca", "Rara vez (≤ 1/mes)", "Ocasional (2–3/mes)", "Casi siempre", "Siempre / Casi a diario"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', now(), null, '["Productividad", "Aplicación"]'::jsonb, 4, 3),

('MM-A16', 'Cuestionario', 'Adopción', '3', '18', '¿Con qué frecuencia compartes con tu equipo ejemplos de contenido generado por IA para revisarlos juntos antes de publicar?', 'Multiple Choice (escala Likert A–E)', '["Nunca", "Rara vez (≤ 1/mes)", "Ocasional (2–3/mes)", "Casi siempre", "Siempre / Casi a diario"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', now(), null, '["Aplicación"]'::jsonb, 4, 3),

('MM-A17', 'Cuestionario', 'Adopción', '3', '18', '¿Con qué frecuencia compartes con otros miembros de marketing los prompts que te han funcionado bien para generar contenido?', 'Multiple Choice (escala Likert A–E)', '["Nunca", "Rara vez (≤ 1/mes)", "Ocasional (2–3/mes)", "Casi siempre", "Siempre / Casi a diario"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', now(), null, '["Aplicación"]'::jsonb, 4, 3),

('MM-A18', 'Cuestionario', 'Adopción', '3', '18', '¿Con qué frecuencia colaboras con otros equipos, como ventas, producto o atención al cliente, compartiendo reportes o resúmenes generados con IA para alinear acciones?', 'Multiple Choice (escala Likert A–E)', '["Nunca", "Rara vez (≤ 1/mes)", "Ocasional (2–3/mes)", "Casi siempre", "Siempre / Casi a diario"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', now(), null, '["Productividad", "Aplicación"]'::jsonb, 4, 3),

('MM-A19', 'Cuestionario', 'Adopción', '3', '18', '¿Con qué frecuencia colaboras con áreas de datos, inteligencia de negocios o TI para mejorar la calidad de los datos que se usan en modelos o recomendaciones de IA?', 'Multiple Choice (escala Likert A–E)', '["Nunca", "Rara vez (≤ 1/mes)", "Ocasional (2–3/mes)", "Casi siempre", "Siempre / Casi a diario"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', now(), null, '["Aplicación"]'::jsonb, 4, 4),

('MM-A20', 'Cuestionario', 'Adopción', '3', '18', '¿Con qué frecuencia trabajas con otros equipos, como datos, TI, área legal o cumplimiento, para establecer límites claros de qué datos se pueden usar con IA y cómo?', 'Multiple Choice (escala Likert A–E)', '["Nunca", "Rara vez (≤ 1/mes)", "Ocasional (2–3/mes)", "Casi siempre", "Siempre / Casi a diario"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', now(), null, '["Aplicación", "Estrategia"]'::jsonb, 4, 4),

('MM-A21', 'Cuestionario', 'Adopción', '3', '18', '¿Con qué frecuencia revisas críticamente los textos generados por IA para detectar errores, sesgos o afirmaciones dudosas antes de usarlos?', 'Multiple Choice (escala Likert A–E)', '["Nunca", "Rara vez (≤ 1/mes)", "Ocasional (2–3/mes)", "Casi siempre", "Siempre / Casi a diario"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', now(), null, '["Estrategia"]'::jsonb, 4, 4),

('MM-A22', 'Cuestionario', 'Adopción', '3', '18', '¿Con qué frecuencia revisas las políticas de uso de datos de las herramientas de IA que usas, o preguntas a alguien de TI o Legal sobre ello?', 'Multiple Choice (escala Likert A–E)', '["Nunca", "Rara vez (≤ 1/mes)", "Ocasional (2–3/mes)", "Casi siempre", "Siempre / Casi a diario"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', now(), null, '["Aplicación"]'::jsonb, 4, 4),

('MM-A23', 'Cuestionario', 'Adopción', '3', '18', '¿Con qué frecuencia revisas que las recomendaciones automatizadas de pujas, audiencia o creatividades tengan sentido para tu contexto de negocio antes de aplicarlas?', 'Multiple Choice (escala Likert A–E)', '["Nunca", "Rara vez (≤ 1/mes)", "Ocasional (2–3/mes)", "Casi siempre", "Siempre / Casi a diario"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', now(), null, '["Aplicación"]'::jsonb, 4, 4),

('MM-A24', 'Cuestionario', 'Adopción', '3', '18', '¿Con qué frecuencia evalúas riesgos éticos, por ejemplo sesgos, sobresegmentación o impacto en la percepción de privacidad, antes de lanzar campañas muy personalizadas apoyadas en IA?', 'Multiple Choice (escala Likert A–E)', '["Nunca", "Rara vez (≤ 1/mes)", "Ocasional (2–3/mes)", "Casi siempre", "Siempre / Casi a diario"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', now(), null, '["Estrategia"]'::jsonb, 4, 4),

('MM-A25', 'Cuestionario', 'Adopción', '3', '18', '¿Con qué frecuencia impulsas cambios en procesos de marketing, por ejemplo briefs, aprobaciones, control de calidad o guías de marca, para integrar el uso de IA de forma sistemática y responsable?', 'Multiple Choice (escala Likert A–E)', '["Nunca", "Rara vez (≤ 1/mes)", "Ocasional (2–3/mes)", "Casi siempre", "Siempre / Casi a diario"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', now(), null, '["Aplicación"]'::jsonb, 4, 5),

('MM-A26', 'Cuestionario', 'Adopción', '3', '18', '¿Con qué frecuencia inviertes tiempo personal, por ejemplo en cursos, tutoriales o seminarios en línea, para aprender a usar mejor herramientas de IA aplicadas al marketing?', 'Multiple Choice (escala Likert A–E)', '["Nunca", "Rara vez (≤ 1/mes)", "Ocasional (2–3/mes)", "Casi siempre", "Siempre / Casi a diario"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', now(), null, '["Productividad", "Aplicación"]'::jsonb, 4, 5),

('MM-A27', 'Cuestionario', 'Adopción', '3', '18', '¿Con qué frecuencia propones probar nuevas herramientas o funciones de IA, por ejemplo versiones beta de IA en plataformas de anuncios, correo o CRM, y reservas tiempo para experimentarlas?', 'Multiple Choice (escala Likert A–E)', '["Nunca", "Rara vez (≤ 1/mes)", "Ocasional (2–3/mes)", "Casi siempre", "Siempre / Casi a diario"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', now(), null, '["Productividad", "Aplicación"]'::jsonb, 4, 5),

('MM-A28', 'Cuestionario', 'Adopción', '3', '18', '¿Con qué frecuencia propones o lideras mini proyectos internos para mejorar procesos, como plantillas de prompts, librería de ejemplos de IA o listas de verificación de revisión?', 'Multiple Choice (escala Likert A–E)', '["Nunca", "Rara vez (≤ 1/mes)", "Ocasional (2–3/mes)", "Casi siempre", "Siempre / Casi a diario"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', now(), null, '["Aplicación"]'::jsonb, 4, 5),

('MM-A29', 'Cuestionario', 'Adopción', '3', '18', '¿Con qué frecuencia lideras o participas activamente en la definición de qué herramientas de IA merece la pena mantener, escalar o sustituir, basándote en resultados medidos?', 'Multiple Choice (escala Likert A–E)', '["Nunca", "Rara vez (≤ 1/mes)", "Ocasional (2–3/mes)", "Casi siempre", "Siempre / Casi a diario"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', now(), null, '["Productividad", "Aplicación"]'::jsonb, 4, 5),

('MM-A30', 'Cuestionario', 'Adopción', '3', '18', '¿Con qué frecuencia compartes aprendizajes, casos de éxito y errores en el uso de IA con tu organización, por ejemplo en charlas internas, documentos o sesiones de entrenamiento?', 'Multiple Choice (escala Likert A–E)', '["Nunca", "Rara vez (≤ 1/mes)", "Ocasional (2–3/mes)", "Casi siempre", "Siempre / Casi a diario"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', now(), null, '["Aplicación"]'::jsonb, 4, 5);

-- CONOCIMIENTO - Rol 18
INSERT INTO "public"."preguntas" ("codigo", "section", "bloque", "area_id", "exclusivo_rol_id", "texto", "tipo", "opciones", "locale", "peso", "escala", "scoring", "created_at", "respuesta_correcta", "dimension", "exclusivo_nivel_id", "dificultad") VALUES
('MM-C1', 'Cuestionario', 'Conocimiento', '3', '18', '¿Cuál de las siguientes opciones describe mejor a una herramienta de IA generativa de texto como ChatGPT en el trabajo de marketing? A) Un editor de imágenes que solo corrige colores. B) Un asistente capaz de generar y reformular textos a partir de instrucciones o prompts. C) Un sistema que solo sirve para programar campañas de email. D) Una base de datos estática de plantillas de anuncios.', 'Multiple Choice (una respuesta)', '["Un editor de imágenes que solo corrige colores.", "Un asistente capaz de generar y reformular textos a partir de instrucciones o prompts.", "Un sistema que solo sirve para programar campañas de email.", "Una base de datos estática de plantillas de anuncios."]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', now(), 'Un asistente capaz de generar y reformular textos a partir de instrucciones o prompts.', '["Aplicación", "Conocimiento"]'::jsonb, 4, 1),

('MM-C2', 'Cuestionario', 'Conocimiento', '3', '18', '¿Cuál de estas actividades es un uso adecuado de IA en email marketing? A) Dejar que la IA decida sola a qué segmento enviar la campaña sin reglas. B) Usar IA para proponer asuntos y variantes de texto, y tú elegir y probar las mejores. C) Usar IA para enviar correos a contactos sin consentimiento. D) Usar IA para ocultar enlaces de baja.', 'Multiple Choice (una respuesta)', '["Dejar que la IA decida sola a qué segmento enviar la campaña sin reglas.", "Usar IA para proponer asuntos y variantes de texto, y tú elegir y probar las mejores.", "Usar IA para enviar correos a contactos sin consentimiento.", "Usar IA para ocultar enlaces de baja."]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', now(), 'Usar IA para proponer asuntos y variantes de texto, y tú elegir y probar las mejores.', '["Aplicación", "Conocimiento"]'::jsonb, 4, 1),

('MM-C3', 'Cuestionario', 'Conocimiento', '3', '18', '¿Qué describe mejor el uso de IA para personalización en marketing digital? A) Enviar el mismo mensaje a toda la base de datos. B) Ajustar contenidos, ofertas o creatividades según datos de comportamiento y perfil del usuario. C) Reducir el número de segmentos a uno solo. D) Enviar más correos sin segmentar.', 'Multiple Choice (una respuesta)', '["Enviar el mismo mensaje a toda la base de datos.", "Ajustar contenidos, ofertas o creatividades según datos de comportamiento y perfil del usuario.", "Reducir el número de segmentos a uno solo.", "Enviar más correos sin segmentar."]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', now(), 'Ajustar contenidos, ofertas o creatividades según datos de comportamiento y perfil del usuario.', '["Aplicación", "Conocimiento"]'::jsonb, 4, 1),

('MM-C4', 'Cuestionario', 'Conocimiento', '3', '18', '¿Qué describe mejor un flujo de trabajo con IA en el ciclo de marketing, es decir IA en el bucle? A) IA genera todo y se publica automáticamente. B) Las personas generan todo y no usan IA. C) IA propone opciones, la persona las revisa, ajusta y retroalimenta a la IA para mejorar. D) IA solo corrige ortografía.', 'Multiple Choice (una respuesta)', '["IA genera todo y se publica automáticamente.", "Las personas generan todo y no usan IA.", "IA propone opciones, la persona las revisa, ajusta y retroalimenta a la IA para mejorar.", "IA solo corrige ortografía."]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', now(), 'IA propone opciones, la persona las revisa, ajusta y retroalimenta a la IA para mejorar.', '["Conocimiento"]'::jsonb, 4, 1),

('MM-C5', 'Cuestionario', 'Conocimiento', '3', '18', '¿Qué describe mejor el uso de IA para optimización continua de campañas, también llamada optimización siempre activa? A) Ajustar manualmente las campañas una vez al año. B) Configurar reglas y modelos que ajustan creatividades, pujas o segmentos en base a datos en tiempo casi real, supervisados por personas. C) Desactivar todos los controles humanos. D) Enviar la misma campaña durante meses sin cambios.', 'Multiple Choice (una respuesta)', '["Ajustar manualmente las campañas una vez al año.", "Configurar reglas y modelos que ajustan creatividades, pujas o segmentos en base a datos en tiempo casi real, supervisados por personas.", "Desactivar todos los controles humanos.", "Enviar la misma campaña durante meses sin cambios."]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', now(), 'Configurar reglas y modelos que ajustan creatividades, pujas o segmentos en base a datos en tiempo casi real, supervisados por personas.', '["Productividad", "Conocimiento", "Aplicación"]'::jsonb, 4, 1),

('MM-C6', 'Cuestionario', 'Conocimiento', '3', '18', '¿Cuál es un ejemplo sencillo y correcto de uso de IA en marketing? A) Usar IA para enviar automáticamente correos sin revisarlos. B) Usar IA para generar ideas de titulares y luego ajustarlos manualmente a la marca. C) Usar IA para comprar bases de datos de contactos sin permiso. D) Usar IA para falsificar reseñas de clientes.', 'Multiple Choice (una respuesta)', '["Usar IA para enviar automáticamente correos sin revisarlos.", "Usar IA para generar ideas de titulares y luego ajustarlos manualmente a la marca.", "Usar IA para comprar bases de datos de contactos sin permiso.", "Usar IA para falsificar reseñas de clientes."]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', now(), 'Usar IA para generar ideas de titulares y luego ajustarlos manualmente a la marca.', '["Aplicación", "Conocimiento"]'::jsonb, 4, 1),

('MM-C7', 'Cuestionario', 'Conocimiento', '3', '18', '¿Qué ventaja principal ofrecen los asistentes de IA para la creación de textos en anuncios? A) Garantizan una tasa de conversión fija. B) Permiten generar y adaptar muchas variaciones de texto de forma rápida. C) Eliminan la necesidad de conocer al público objetivo. D) Sustituyen completamente al equipo creativo.', 'Multiple Choice (una respuesta)', '["Garantizan una tasa de conversión fija.", "Permiten generar y adaptar muchas variaciones de texto de forma rápida.", "Eliminan la necesidad de conocer al público objetivo.", "Sustituyen completamente al equipo creativo."]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', now(), 'Permiten generar y adaptar muchas variaciones de texto de forma rápida.', '["Aplicación", "Conocimiento"]'::jsonb, 4, 2),

('MM-C8', 'Cuestionario', 'Conocimiento', '3', '18', '¿Qué es una audiencia similar o lookalike apoyada en IA en plataformas de anuncios? A) Un conjunto de personas que han rechazado todas tus ofertas. B) Un grupo de usuarios con comportamientos parecidos a tus mejores clientes. C) Tu base completa de contactos. D) Los usuarios que visitaron la página web una sola vez.', 'Multiple Choice (una respuesta)', '["Un conjunto de personas que han rechazado todas tus ofertas.", "Un grupo de usuarios con comportamientos parecidos a tus mejores clientes.", "Tu base completa de contactos.", "Los usuarios que visitaron la página web una sola vez."]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', now(), 'Un grupo de usuarios con comportamientos parecidos a tus mejores clientes.', '["Conocimiento"]'::jsonb, 4, 2),

('MM-C9', 'Cuestionario', 'Conocimiento', '3', '18', '¿Cómo puede la IA apoyar en la priorización de audiencias para una campaña? A) Seleccionando al azar una parte de la base. B) Analizando historiales de interacción y conversión para sugerir segmentos con mayor probabilidad de respuesta. C) Eliminando a todos los usuarios inactivos sin revisar. D) Recomendando siempre la audiencia más grande.', 'Multiple Choice (una respuesta)', '["Seleccionando al azar una parte de la base.", "Analizando historiales de interacción y conversión para sugerir segmentos con mayor probabilidad de respuesta.", "Eliminando a todos los usuarios inactivos sin revisar.", "Recomendando siempre la audiencia más grande."]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', now(), 'Analizando historiales de interacción y conversión para sugerir segmentos con mayor probabilidad de respuesta.', '["Conocimiento"]'::jsonb, 4, 2),

('MM-C10', 'Cuestionario', 'Conocimiento', '3', '18', '¿Qué es un modelo de propensión o probabilidad de conversión en marketing? A) Un informe de clics. B) Un modelo que estima la probabilidad de que un usuario realice una acción, como una compra o un registro. C) El presupuesto máximo de la campaña. D) Un tipo de anuncio animado.', 'Multiple Choice (una respuesta)', '["Un informe de clics.", "Un modelo que estima la probabilidad de que un usuario realice una acción, como una compra o un registro.", "El presupuesto máximo de la campaña.", "Un tipo de anuncio animado."]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', now(), 'Un modelo que estima la probabilidad de que un usuario realice una acción, como una compra o un registro.', '["Conocimiento", "Inversión"]'::jsonb, 4, 2),

('MM-C11', 'Cuestionario', 'Conocimiento', '3', '18', '¿Qué limitación es típica de los asistentes de IA generativa? A) Siempre utilizan datos en tiempo real. B) Nunca cometen errores gramaticales. C) Pueden inventar datos o afirmaciones incorrectas si el prompt no es claro. D) Garantizan que el contenido será totalmente original y sin sesgos.', 'Multiple Choice (una respuesta)', '["Siempre utilizan datos en tiempo real.", "Nunca cometen errores gramaticales.", "Pueden inventar datos o afirmaciones incorrectas si el prompt no es claro.", "Garantizan que el contenido será totalmente original y sin sesgos."]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', now(), 'Pueden inventar datos o afirmaciones incorrectas si el prompt no es claro.', '["Productividad", "Estrategia", "Conocimiento", "Aplicación"]'::jsonb, 4, 2),

('MM-C12', 'Cuestionario', 'Conocimiento', '3', '18', '¿Qué es importante incluir en un buen prompt para generar contenido alineado con la marca? A) Solo la longitud del texto. B) El presupuesto de la campaña. C) El público objetivo, el tono de la marca y el objetivo del mensaje. D) Solo el nombre del producto.', 'Multiple Choice (una respuesta)', '["Solo la longitud del texto.", "El presupuesto de la campaña.", "El público objetivo, el tono de la marca y el objetivo del mensaje.", "Solo el nombre del producto."]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', now(), 'El público objetivo, el tono de la marca y el objetivo del mensaje.', '["Conocimiento", "Inversión"]'::jsonb, 4, 2),

('MM-C13', 'Cuestionario', 'Conocimiento', '3', '18', '¿Qué ventaja ofrece combinar IA con pruebas A o B en campañas? A) Evita la necesidad de definir métricas. B) Permite iterar más rápido sobre creatividades y segmentaciones y aprender de los resultados. C) Garantiza que todas las variantes funcionen igual. D) Elimina la necesidad de revisar datos.', 'Multiple Choice (una respuesta)', '["Evita la necesidad de definir métricas.", "Permite iterar más rápido sobre creatividades y segmentaciones y aprender de los resultados.", "Garantiza que todas las variantes funcionen igual.", "Elimina la necesidad de revisar datos."]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', now(), 'Permite iterar más rápido sobre creatividades y segmentaciones y aprender de los resultados.', '["Productividad", "Conocimiento", "Aplicación"]'::jsonb, 4, 3),

('MM-C14', 'Cuestionario', 'Conocimiento', '3', '18', '¿Qué es un conjunto de instrucciones base o prompt de sistema en el uso avanzado de IA? A) Un anuncio de display. B) Un conjunto de reglas y contexto que se reutiliza para mantener la coherencia en las respuestas de la IA. C) El nombre de la campaña. D) El presupuesto máximo diario.', 'Multiple Choice (una respuesta)', '["Un anuncio de display.", "Un conjunto de reglas y contexto que se reutiliza para mantener la coherencia en las respuestas de la IA.", "El nombre de la campaña.", "El presupuesto máximo diario."]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', now(), 'Un conjunto de reglas y contexto que se reutiliza para mantener la coherencia en las respuestas de la IA.', '["Aplicación", "Conocimiento", "Inversión"]'::jsonb, 4, 3),

('MM-C15', 'Cuestionario', 'Conocimiento', '3', '18', '¿Qué riesgo surge al usar solo datos históricos para entrenar modelos de IA en marketing sin considerar cambios recientes en el mercado? A) Que los modelos sean más precisos. B) Que los modelos se vuelvan obsoletos y recomienden acciones no alineadas con la nueva realidad. C) Menor necesidad de medir. D) Aumento automático del retorno de inversión.', 'Multiple Choice (una respuesta)', '["Que los modelos sean más precisos.", "Que los modelos se vuelvan obsoletos y recomienden acciones no alineadas con la nueva realidad.", "Menor necesidad de medir.", "Aumento automático del retorno de inversión."]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', now(), 'Que los modelos se vuelvan obsoletos y recomienden acciones no alineadas con la nueva realidad.', '["Aplicación", "Estrategia", "Conocimiento", "Inversión"]'::jsonb, 4, 3),

('MM-C16', 'Cuestionario', 'Conocimiento', '3', '18', '¿Qué es un prompt en el contexto de IA? A) El nombre del modelo de IA. B) La instrucción o texto que le damos a la IA para que genere una respuesta. C) El informe final de una campaña. D) El presupuesto asignado a una campaña.', 'Multiple Choice (una respuesta)', '["El nombre del modelo de IA.", "La instrucción o texto que le damos a la IA para que genere una respuesta.", "El informe final de una campaña.", "El presupuesto asignado a una campaña."]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', now(), 'La instrucción o texto que le damos a la IA para que genere una respuesta.', '["Conocimiento", "Inversión"]'::jsonb, 4, 3),

('MM-C17', 'Cuestionario', 'Conocimiento', '3', '18', '¿Qué riesgo aparece al reutilizar masivamente contenido generado por IA sin personalizarlo? A) Mejora automática del posicionamiento en buscadores. B) Aumento garantizado de la tasa de clic. C) Mensajes genéricos, poco diferenciados y con posible canibalización entre piezas. D) Mayor fidelidad a la voz única de la marca.', 'Multiple Choice (una respuesta)', '["Mejora automática del posicionamiento en buscadores.", "Aumento garantizado de la tasa de clic.", "Mensajes genéricos, poco diferenciados y con posible canibalización entre piezas.", "Mayor fidelidad a la voz única de la marca."]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', now(), 'Mensajes genéricos, poco diferenciados y con posible canibalización entre piezas.', '["Aplicación", "Estrategia", "Conocimiento"]'::jsonb, 4, 3),

('MM-C18', 'Cuestionario', 'Conocimiento', '3', '18', '¿Qué es un journey automatizado en marketing apoyado en IA? A) Una campaña manual enviada una sola vez. B) Una secuencia de interacciones que se activa según el comportamiento del usuario y se optimiza con IA. C) Un informe mensual de resultados. D) Una reunión del equipo de marketing.', 'Multiple Choice (una respuesta)', '["Una campaña manual enviada una sola vez.", "Una secuencia de interacciones que se activa según el comportamiento del usuario y se optimiza con IA.", "Un informe mensual de resultados.", "Una reunión del equipo de marketing."]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', now(), 'Una secuencia de interacciones que se activa según el comportamiento del usuario y se optimiza con IA.', '["Productividad", "Conocimiento", "Aplicación"]'::jsonb, 4, 3),

('MM-C19', 'Cuestionario', 'Conocimiento', '3', '18', '¿Qué riesgo ético aparece al combinar datos de comportamiento muy detallados con IA para personalización extrema? A) Aumento de la tasa de apertura. B) Posibles percepciones de invasión de privacidad y manipulación excesiva. C) Reducción del número de campañas. D) Mejora automática de la reputación de marca.', 'Multiple Choice (una respuesta)', '["Aumento de la tasa de apertura.", "Posibles percepciones de invasión de privacidad y manipulación excesiva.", "Reducción del número de campañas.", "Mejora automática de la reputación de marca."]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', now(), 'Posibles percepciones de invasión de privacidad y manipulación excesiva.', '["Aplicación", "Estrategia", "Conocimiento"]'::jsonb, 4, 4),

('MM-C20', 'Cuestionario', 'Conocimiento', '3', '18', '¿Cuál es una buena práctica de gobernanza de IA para un miembro avanzado de marketing? A) Guardar los prompts solo en su computadora personal. B) Definir junto con líderes lineamientos de uso, revisión humana y documentación de experimentos con IA. C) No informar a nadie sobre el uso que hace de IA. D) Compartir accesos sin control a cualquier herramienta de IA.', 'Multiple Choice (una respuesta)', '["Guardar los prompts solo en su computadora personal.", "Definir junto con líderes lineamientos de uso, revisión humana y documentación de experimentos con IA.", "No informar a nadie sobre el uso que hace de IA.", "Compartir accesos sin control a cualquier herramienta de IA."]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', now(), 'Definir junto con líderes lineamientos de uso, revisión humana y documentación de experimentos con IA.', '["Aplicación", "Estrategia", "Conocimiento"]'::jsonb, 4, 4),

('MM-C21', 'Cuestionario', 'Conocimiento', '3', '18', 'Desde la perspectiva de privacidad, ¿qué es lo más prudente al usar IA externa, por ejemplo en una página web pública? A) Subir cualquier base de datos de clientes si sirve para mejorar el contenido. B) No subir datos personales identificables ni información sensible de clientes. C) Subir solo correos electrónicos de clientes, porque no son datos sensibles. D) Subir solo información financiera de la empresa.', 'Multiple Choice (una respuesta)', '["Subir cualquier base de datos de clientes si sirve para mejorar el contenido.", "No subir datos personales identificables ni información sensible de clientes.", "Subir solo correos electrónicos de clientes, porque no son datos sensibles.", "Subir solo información financiera de la empresa."]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', now(), 'No subir datos personales identificables ni información sensible de clientes.', '["Aplicación", "Estrategia", "Conocimiento"]'::jsonb, 4, 4),

('MM-C22', 'Cuestionario', 'Conocimiento', '3', '18', 'En redes sociales, ¿qué función de IA puede ayudar a mejorar el rendimiento de publicaciones? A) Sugerencias de horarios y formatos basadas en datos históricos. B) Eliminar comentarios negativos automáticamente. C) Comprar seguidores sin que el algoritmo lo note. D) Publicar el mismo contenido a la misma hora siempre.', 'Multiple Choice (una respuesta)', '["Sugerencias de horarios y formatos basadas en datos históricos.", "Eliminar comentarios negativos automáticamente.", "Comprar seguidores sin que el algoritmo lo note.", "Publicar el mismo contenido a la misma hora siempre."]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', now(), 'Sugerencias de horarios y formatos basadas en datos históricos.', '["Aplicación", "Conocimiento"]'::jsonb, 4, 4),

('MM-C23', 'Cuestionario', 'Conocimiento', '3', '18', '¿Cuál es un riesgo al usar modelos de IA para segmentación sin supervisión humana? A) Tener demasiadas ideas de segmentación. B) Sesgos que excluyen o sobreincluyen a ciertos grupos de forma injustificada. C) Que las campañas sean siempre más baratas. D) Que ya no haga falta medir resultados.', 'Multiple Choice (una respuesta)', '["Tener demasiadas ideas de segmentación.", "Sesgos que excluyen o sobreincluyen a ciertos grupos de forma injustificada.", "Que las campañas sean siempre más baratas.", "Que ya no haga falta medir resultados."]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', now(), 'Sesgos que excluyen o sobreincluyen a ciertos grupos de forma injustificada.', '["Productividad", "Estrategia", "Conocimiento"]'::jsonb, 4, 4),

('MM-C24', 'Cuestionario', 'Conocimiento', '3', '18', '¿Qué es una buena práctica al evaluar el impacto de la IA en el retorno de inversión de marketing? A) No separar campañas con IA de campañas sin IA. B) Definir hipótesis, métricas y periodos de prueba claros para comparar escenarios con y sin IA. C) Cambiar muchas variables a la vez sin documentar. D) Basarse solo en impresiones y clics.', 'Multiple Choice (una respuesta)', '["No separar campañas con IA de campañas sin IA.", "Definir hipótesis, métricas y periodos de prueba claros para comparar escenarios con y sin IA.", "Cambiar muchas variables a la vez sin documentar.", "Basarse solo en impresiones y clics."]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', now(), 'Definir hipótesis, métricas y periodos de prueba claros para comparar escenarios con y sin IA.', '["Productividad", "Conocimiento", "Inversión"]'::jsonb, 4, 4),

('MM-C25', 'Cuestionario', 'Conocimiento', '3', '18', '¿Qué indicador es más útil para evaluar si la inversión en IA en marketing está generando valor? A) Número de herramientas contratadas. B) Horas dedicadas a probar herramientas sin medir nada. C) Impacto sobre indicadores relevantes, por ejemplo coste por adquisición, valor de vida del cliente o margen, comparando escenarios con y sin IA. D) Número de prompts escritos al día.', 'Multiple Choice (una respuesta)', '["Número de herramientas contratadas.", "Horas dedicadas a probar herramientas sin medir nada.", "Impacto sobre indicadores relevantes, por ejemplo coste por adquisición, valor de vida del cliente o margen, comparando escenarios con y sin IA.", "Número de prompts escritos al día."]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', now(), 'Impacto sobre indicadores relevantes, por ejemplo coste por adquisición, valor de vida del cliente o margen, comparando escenarios con y sin IA.', '["Aplicación", "Conocimiento", "Inversión"]'::jsonb, 4, 5),

('MM-C26', 'Cuestionario', 'Conocimiento', '3', '18', '¿Quién es responsable final del contenido que se publica en una campaña generada con ayuda de IA? A) Solo la herramienta de IA. B) El proveedor de la herramienta. C) El miembro de marketing y la empresa que aprueban y publican el contenido. D) Nadie, porque la IA es autónoma.', 'Multiple Choice (una respuesta)', '["Solo la herramienta de IA.", "El proveedor de la herramienta.", "El miembro de marketing y la empresa que aprueban y publican el contenido.", "Nadie, porque la IA es autónoma."]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', now(), 'El miembro de marketing y la empresa que aprueban y publican el contenido.', '["Conocimiento"]'::jsonb, 4, 5),

('MM-C27', 'Cuestionario', 'Conocimiento', '3', '18', '¿Qué describe mejor la inversión saludable en IA para un miembro de marketing? A) Gastar todo el presupuesto en nuevas licencias sin pruebas. B) Probar herramientas gratuitas o de bajo costo, medir impacto y luego escalar. C) Evitar cualquier gasto en IA para no arriesgar. D) Comprar la herramienta más cara del mercado porque debe ser la mejor.', 'Multiple Choice (una respuesta)', '["Gastar todo el presupuesto en nuevas licencias sin pruebas.", "Probar herramientas gratuitas o de bajo costo, medir impacto y luego escalar.", "Evitar cualquier gasto en IA para no arriesgar.", "Comprar la herramienta más cara del mercado porque debe ser la mejor."]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', now(), 'Probar herramientas gratuitas o de bajo costo, medir impacto y luego escalar.', '["Aplicación", "Conocimiento", "Inversión"]'::jsonb, 4, 5),

('MM-C28', 'Cuestionario', 'Conocimiento', '3', '18', '¿Cuál es una buena práctica de inversión de tiempo al usar IA para análisis de datos de campañas? A) Depender solo de paneles automáticos sin revisar nada. B) Reservar bloques de tiempo para revisar las explicaciones generadas por IA, contrastarlas con los datos y planear acciones. C) Ignorar las recomendaciones de IA. D) Analizar solo una métrica aislada.', 'Multiple Choice (una respuesta)', '["Depender solo de paneles automáticos sin revisar nada.", "Reservar bloques de tiempo para revisar las explicaciones generadas por IA, contrastarlas con los datos y planear acciones.", "Ignorar las recomendaciones de IA.", "Analizar solo una métrica aislada."]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', now(), 'Reservar bloques de tiempo para revisar las explicaciones generadas por IA, contrastarlas con los datos y planear acciones.', '["Productividad", "Conocimiento", "Inversión", "Aplicación"]'::jsonb, 4, 5),

('MM-C29', 'Cuestionario', 'Conocimiento', '3', '18', '¿Cuál es un uso eficiente de tu tiempo como miembro avanzado de marketing al trabajar con IA? A) Escribir los mismos prompts desde cero cada vez. B) Crear y mantener una librería de prompts, plantillas y ejemplos para reutilizar y compartir con el equipo. C) Usar IA solo para tareas menores. D) No documentar nada para ser más rápido.', 'Multiple Choice (una respuesta)', '["Escribir los mismos prompts desde cero cada vez.", "Crear y mantener una librería de prompts, plantillas y ejemplos para reutilizar y compartir con el equipo.", "Usar IA solo para tareas menores.", "No documentar nada para ser más rápido."]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', now(), 'Crear y mantener una librería de prompts, plantillas y ejemplos para reutilizar y compartir con el equipo.', '["Productividad", "Conocimiento", "Aplicación"]'::jsonb, 4, 5),

('MM-C30', 'Cuestionario', 'Conocimiento', '3', '18', '¿Qué enfoque de trabajo potencia mejor la productividad de una persona experta en IA en marketing? A) Hacer todo sola con IA. B) Diseñar marcos de trabajo, plantillas y guías para que el resto del equipo pueda utilizar IA de forma escalable. C) Ocultar su conocimiento para mantener ventaja personal. D) Rechazar tareas de documentación.', 'Multiple Choice (una respuesta)', '["Hacer todo sola con IA.", "Diseñar marcos de trabajo, plantillas y guías para que el resto del equipo pueda utilizar IA de forma escalable.", "Ocultar su conocimiento para mantener ventaja personal.", "Rechazar tareas de documentación."]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', now(), 'Diseñar marcos de trabajo, plantillas y guías para que el resto del equipo pueda utilizar IA de forma escalable.', '["Productividad", "Conocimiento", "Aplicación"]'::jsonb, 4, 5);
