-- ============================================================================
-- PREGUNTAS PARA MIEMBROS DE VENTAS
-- ============================================================================
-- Rol incluido:
--   - Rol ID 17: Miembros de Ventas (area_id: 2, nivel_id: 4)
-- ============================================================================

-- ============================================================================
-- ROL 17: Miembros de Ventas
-- ============================================================================

-- ADOPCIÓN - Rol 17
INSERT INTO "public"."preguntas" ("codigo", "section", "bloque", "area_id", "exclusivo_rol_id", "texto", "tipo", "opciones", "locale", "peso", "escala", "scoring", "created_at", "respuesta_correcta", "dimension", "exclusivo_nivel_id", "dificultad") VALUES
('MV-A1', 'Cuestionario', 'Adopción', '2', '17', 'Uso IA para mejorar la redacción de correos de ventas (tono, claridad, corrección).', 'Multiple Choice (escala Likert A–E)', '["Nunca", "Casi nunca (1–2 veces al mes)", "A veces (1–2 veces por semana)", "Casi siempre (3–4 veces por semana)", "Siempre (todos o casi todos los días)"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', now(), null, '["Aplicación"]'::jsonb, 4, 1),

('MV-A2', 'Cuestionario', 'Adopción', '2', '17', 'Uso IA, por sugerencia de mi líder o compañeros, para mejorar correos o mensajes en redes a clientes.', 'Multiple Choice (escala Likert A–E)', '["Nunca", "Casi nunca (1–2 veces al mes)", "A veces (1–2 veces por semana)", "Casi siempre (3–4 veces por semana)", "Siempre (todos o casi todos los días)"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', now(), null, '["Aplicación"]'::jsonb, 4, 1),

('MV-A3', 'Cuestionario', 'Adopción', '2', '17', 'Uso IA para priorizar mi lista diaria de leads u oportunidades (por ejemplo, enfocarme en los de mayor probabilidad de cierre).', 'Multiple Choice (escala Likert A–E)', '["Nunca", "Casi nunca (1–2 veces al mes)", "A veces (1–2 veces por semana)", "Casi siempre (3–4 veces por semana)", "Siempre (todos o casi todos los días)"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', now(), null, '["Aplicación", "Estrategia"]'::jsonb, 4, 1),

('MV-A4', 'Cuestionario', 'Adopción', '2', '17', 'Uso IA integrada al CRM para planear mi agenda semanal (qué clientes contactar, en qué orden y con qué mensajes).', 'Multiple Choice (escala Likert A–E)', '["Nunca", "Casi nunca (1–2 veces al mes)", "A veces (1–2 veces por semana)", "Casi siempre (3–4 veces por semana)", "Siempre (todos o casi todos los días)"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', now(), null, '["Aplicación"]'::jsonb, 4, 1),

('MV-A5', 'Cuestionario', 'Adopción', '2', '17', 'Diseño y ajusto flujos de trabajo con IA que abarcan varias etapas (prospección, seguimientos, recordatorios, análisis de pipeline).', 'Multiple Choice (escala Likert A–E)', '["Nunca", "Casi nunca (1–2 veces al mes)", "A veces (1–2 veces por semana)", "Casi siempre (3–4 veces por semana)", "Siempre (todos o casi todos los días)"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', now(), null, '["Aplicación"]'::jsonb, 4, 1),

('MV-A6', 'Cuestionario', 'Adopción', '2', '17', 'Pido a la IA ideas de preguntas para conocer mejor las necesidades del cliente antes de una llamada.', 'Multiple Choice (escala Likert A–E)', '["Nunca", "Casi nunca (1–2 veces al mes)", "A veces (1–2 veces por semana)", "Casi siempre (3–4 veces por semana)", "Siempre (todos o casi todos los días)"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', now(), null, '["Aplicación"]'::jsonb, 4, 1),

('MV-A7', 'Cuestionario', 'Adopción', '2', '17', 'Cuando tengo un caso complejo, pido a la IA variantes de argumentos para manejar objeciones del cliente.', 'Multiple Choice (escala Likert A–E)', '["Nunca", "Casi nunca (1–2 veces al mes)", "A veces (1–2 veces por semana)", "Casi siempre (3–4 veces por semana)", "Siempre (todos o casi todos los días)"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', now(), null, '["Aplicación"]'::jsonb, 4, 2),

('MV-A8', 'Cuestionario', 'Adopción', '2', '17', 'Pido a la IA que adapte mis mensajes de venta a distintos segmentos (sector, tamaño de empresa, rol del contacto).', 'Multiple Choice (escala Likert A–E)', '["Nunca", "Casi nunca (1–2 veces al mes)", "A veces (1–2 veces por semana)", "Casi siempre (3–4 veces por semana)", "Siempre (todos o casi todos los días)"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', now(), null, '["Aplicación"]'::jsonb, 4, 2),

('MV-A9', 'Cuestionario', 'Adopción', '2', '17', 'Ejecuto pruebas A/B con mensajes generados o ajustados por IA y reviso métricas para optimizar mis campañas personales.', 'Multiple Choice (escala Likert A–E)', '["Nunca", "Casi nunca (1–2 veces al mes)", "A veces (1–2 veces por semana)", "Casi siempre (3–4 veces por semana)", "Siempre (todos o casi todos los días)"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', now(), null, '["Productividad"]'::jsonb, 4, 2),

('MV-A10', 'Cuestionario', 'Adopción', '2', '17', 'Uso IA para analizar patrones de éxito y fracaso en mi pipeline y propongo cambios concretos al proceso comercial.', 'Multiple Choice (escala Likert A–E)', '["Nunca", "Casi nunca (1–2 veces al mes)", "A veces (1–2 veces por semana)", "Casi siempre (3–4 veces por semana)", "Siempre (todos o casi todos los días)"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', now(), null, '["Aplicación"]'::jsonb, 4, 2),

('MV-A11', 'Cuestionario', 'Adopción', '2', '17', 'Reviso y corrijo el contenido generado por IA antes de enviarlo al cliente.', 'Multiple Choice (escala Likert A–E)', '["Nunca", "Casi nunca (1–2 veces al mes)", "A veces (1–2 veces por semana)", "Casi siempre (3–4 veces por semana)", "Siempre (todos o casi todos los días)"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', now(), null, '["Aplicación"]'::jsonb, 4, 2),

('MV-A12', 'Cuestionario', 'Adopción', '2', '17', 'Reviso si las sugerencias de IA son coherentes con la información que tengo en el CRM.', 'Multiple Choice (escala Likert A–E)', '["Nunca", "Casi nunca (1–2 veces al mes)", "A veces (1–2 veces por semana)", "Casi siempre (3–4 veces por semana)", "Siempre (todos o casi todos los días)"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', now(), null, '["Aplicación"]'::jsonb, 4, 2),

('MV-A13', 'Cuestionario', 'Adopción', '2', '17', 'Uso IA para preparar guiones de llamada y variantes de preguntas según el tipo de cliente.', 'Multiple Choice (escala Likert A–E)', '["Nunca", "Casi nunca (1–2 veces al mes)", "A veces (1–2 veces por semana)", "Casi siempre (3–4 veces por semana)", "Siempre (todos o casi todos los días)"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', now(), null, '["Aplicación"]'::jsonb, 4, 3),

('MV-A14', 'Cuestionario', 'Adopción', '2', '17', 'Ajusto mis prompts y plantillas de IA según los resultados reales (cierres, respuestas, reuniones agendadas).', 'Multiple Choice (escala Likert A–E)', '["Nunca", "Casi nunca (1–2 veces al mes)", "A veces (1–2 veces por semana)", "Casi siempre (3–4 veces por semana)", "Siempre (todos o casi todos los días)"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', now(), null, '["Productividad"]'::jsonb, 4, 3),

('MV-A15', 'Cuestionario', 'Adopción', '2', '17', 'Coordino con marketing u otras áreas para alinear mensajes y prompts de IA a la propuesta de valor y campañas activas.', 'Multiple Choice (escala Likert A–E)', '["Nunca", "Casi nunca (1–2 veces al mes)", "A veces (1–2 veces por semana)", "Casi siempre (3–4 veces por semana)", "Siempre (todos o casi todos los días)"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', now(), null, '["Aplicación"]'::jsonb, 4, 3),

('MV-A16', 'Cuestionario', 'Adopción', '2', '17', 'Uso IA para resumir información de productos o servicios y explicarla al cliente de forma sencilla.', 'Multiple Choice (escala Likert A–E)', '["Nunca", "Casi nunca (1–2 veces al mes)", "A veces (1–2 veces por semana)", "Casi siempre (3–4 veces por semana)", "Siempre (todos o casi todos los días)"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', now(), null, '["Aplicación"]'::jsonb, 4, 3),

('MV-A17', 'Cuestionario', 'Adopción', '2', '17', 'Uso IA para resumir notas de reuniones y registrarlas de forma más ordenada en el CRM.', 'Multiple Choice (escala Likert A–E)', '["Nunca", "Casi nunca (1–2 veces al mes)", "A veces (1–2 veces por semana)", "Casi siempre (3–4 veces por semana)", "Siempre (todos o casi todos los días)"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', now(), null, '["Aplicación"]'::jsonb, 4, 3),

('MV-A18', 'Cuestionario', 'Adopción', '2', '17', 'Analizo con IA mis correos o notas de reuniones para identificar mejoras en mi argumento de venta.', 'Multiple Choice (escala Likert A–E)', '["Nunca", "Casi nunca (1–2 veces al mes)", "A veces (1–2 veces por semana)", "Casi siempre (3–4 veces por semana)", "Siempre (todos o casi todos los días)"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', now(), null, '["Aplicación"]'::jsonb, 4, 3),

('MV-A19', 'Cuestionario', 'Adopción', '2', '17', 'Uso IA para identificar señales tempranas de riesgo en mis oportunidades (por ejemplo, falta de respuestas, retrasos, cambios de contacto).', 'Multiple Choice (escala Likert A–E)', '["Nunca", "Casi nunca (1–2 veces al mes)", "A veces (1–2 veces por semana)", "Casi siempre (3–4 veces por semana)", "Siempre (todos o casi todos los días)"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', now(), null, '["Estrategia", "Aplicación"]'::jsonb, 4, 4),

('MV-A20', 'Cuestionario', 'Adopción', '2', '17', 'Evalúo nuevas herramientas o integraciones de IA y doy feedback estructurado sobre su impacto en mi productividad y resultados.', 'Multiple Choice (escala Likert A–E)', '["Nunca", "Casi nunca (1–2 veces al mes)", "A veces (1–2 veces por semana)", "Casi siempre (3–4 veces por semana)", "Siempre (todos o casi todos los días)"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', now(), null, '["Productividad", "Aplicación"]'::jsonb, 4, 4),

('MV-A21', 'Cuestionario', 'Adopción', '2', '17', 'Dedico parte de mi tiempo personal o laboral a aprender cosas básicas sobre IA para ventas (videos, cursos, artículos).', 'Multiple Choice (escala Likert A–E)', '["Nunca", "Casi nunca (1–2 veces al mes)", "A veces (1–2 veces por semana)", "Casi siempre (3–4 veces por semana)", "Siempre (todos o casi todos los días)"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', now(), null, '["Productividad"]'::jsonb, 4, 4),

('MV-A22', 'Cuestionario', 'Adopción', '2', '17', 'Invierto algo de tiempo en probar nuevas funciones de IA sugeridas por la empresa (por ejemplo, plantillas, asistentes en el CRM).', 'Multiple Choice (escala Likert A–E)', '["Nunca", "Casi nunca (1–2 veces al mes)", "A veces (1–2 veces por semana)", "Casi siempre (3–4 veces por semana)", "Siempre (todos o casi todos los días)"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', now(), null, '["Productividad"]'::jsonb, 4, 4),

('MV-A23', 'Cuestionario', 'Adopción', '2', '17', 'Dedico tiempo cada mes a aprender nuevas formas de integrar IA en mi proceso de ventas (cursos, tutoriales, pruebas).', 'Multiple Choice (escala Likert A–E)', '["Nunca", "Casi nunca (1–2 veces al mes)", "A veces (1–2 veces por semana)", "Casi siempre (3–4 veces por semana)", "Siempre (todos o casi todos los días)"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', now(), null, '["Productividad"]'::jsonb, 4, 4),

('MV-A24', 'Cuestionario', 'Adopción', '2', '17', 'Invierto tiempo en probar nuevas integraciones de IA autorizadas (por ejemplo, IA en llamadas, IA en propuestas) y comparto feedback.', 'Multiple Choice (escala Likert A–E)', '["Nunca", "Casi nunca (1–2 veces al mes)", "A veces (1–2 veces por semana)", "Casi siempre (3–4 veces por semana)", "Siempre (todos o casi todos los días)"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', now(), null, '["Productividad"]'::jsonb, 4, 4),

('MV-A25', 'Cuestionario', 'Adopción', '2', '17', 'Apoyo a otros compañeros de ventas a mejorar sus prompts y uso de IA, compartiendo ejemplos, playbooks y aprendizajes.', 'Multiple Choice (escala Likert A–E)', '["Nunca", "Casi nunca (1–2 veces al mes)", "A veces (1–2 veces por semana)", "Casi siempre (3–4 veces por semana)", "Siempre (todos o casi todos los días)"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', now(), null, '["Aplicación"]'::jsonb, 4, 5),

('MV-A26', 'Cuestionario', 'Adopción', '2', '17', 'Comento con mi líder o compañeros sobre oportunidades simples de usar IA en nuestro proceso de ventas.', 'Multiple Choice (escala Likert A–E)', '["Nunca", "Casi nunca (1–2 veces al mes)", "A veces (1–2 veces por semana)", "Casi siempre (3–4 veces por semana)", "Siempre (todos o casi todos los días)"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', now(), null, '["Aplicación"]'::jsonb, 4, 5),

('MV-A27', 'Cuestionario', 'Adopción', '2', '17', 'Comparto con mi equipo ejemplos de correos o mensajes mejorados por IA que han dado buenos resultados.', 'Multiple Choice (escala Likert A–E)', '["Nunca", "Casi nunca (1–2 veces al mes)", "A veces (1–2 veces por semana)", "Casi siempre (3–4 veces por semana)", "Siempre (todos o casi todos los días)"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', now(), null, '["Productividad", "Aplicación"]'::jsonb, 4, 5),

('MV-A28', 'Cuestionario', 'Adopción', '2', '17', 'Comparto con mi equipo y líder hallazgos sobre qué prompts o configuraciones de IA me han ayudado a cerrar más ventas.', 'Multiple Choice (escala Likert A–E)', '["Nunca", "Casi nunca (1–2 veces al mes)", "A veces (1–2 veces por semana)", "Casi siempre (3–4 veces por semana)", "Siempre (todos o casi todos los días)"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', now(), null, '["Aplicación"]'::jsonb, 4, 5),

('MV-A29', 'Cuestionario', 'Adopción', '2', '17', 'Cuido no compartir en IA externa información confidencial del cliente y, si es necesario, reduzco o anonimizo los datos.', 'Multiple Choice (escala Likert A–E)', '["Nunca", "Casi nunca (1–2 veces al mes)", "A veces (1–2 veces por semana)", "Casi siempre (3–4 veces por semana)", "Siempre (todos o casi todos los días)"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', now(), null, '["Estrategia", "Aplicación"]'::jsonb, 4, 5),

('MV-A30', 'Cuestionario', 'Adopción', '2', '17', 'Verifico regularmente que mi uso de IA respete políticas internas, privacidad de clientes y estándares éticos de la empresa.', 'Multiple Choice (escala Likert A–E)', '["Nunca", "Casi nunca (1–2 veces al mes)", "A veces (1–2 veces por semana)", "Casi siempre (3–4 veces por semana)", "Siempre (todos o casi todos los días)"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', now(), null, '["Estrategia", "Aplicación"]'::jsonb, 4, 5);

-- CONOCIMIENTO - Rol 17
INSERT INTO "public"."preguntas" ("codigo", "section", "bloque", "area_id", "exclusivo_rol_id", "texto", "tipo", "opciones", "locale", "peso", "escala", "scoring", "created_at", "respuesta_correcta", "dimension", "exclusivo_nivel_id", "dificultad") VALUES
('MV-C1', 'Cuestionario', 'Conocimiento', '2', '17', '¿Cuál de las siguientes opciones describe mejor una herramienta de IA generativa aplicada a ventas?', 'Multiple Choice (una respuesta)', '["Un sistema que solo registra llamadas en el CRM.", "Una herramienta que crea textos o ideas nuevas a partir de instrucciones del vendedor.", "Una hoja de cálculo con fórmulas para sumar ventas.", "Un sistema que bloquea correos de spam."]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', now(), 'Una herramienta que crea textos o ideas nuevas a partir de instrucciones del vendedor.', '["Conocimiento", "Aplicación"]'::jsonb, 4, 1),

('MV-C2', 'Cuestionario', 'Conocimiento', '2', '17', '¿Cuál es una buena práctica al usar IA para escribir correos de seguimiento?', 'Multiple Choice (una respuesta)', '["Enviar siempre el texto tal cual lo genera la IA.", "Ajustar el texto a la situación del cliente y revisar datos clave.", "Usar el mismo texto para todos los clientes.", "Evitar mencionar el problema del cliente."]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', now(), 'Ajustar el texto a la situación del cliente y revisar datos clave.', '["Conocimiento"]'::jsonb, 4, 1),

('MV-C3', 'Cuestionario', 'Conocimiento', '2', '17', '¿Cuál es una forma adecuada de evaluar si un mensaje generado por IA mejora tus resultados de ventas?', 'Multiple Choice (una respuesta)', '["Usarlo una sola vez y decidir por intuición.", "Preguntar solo a un colega si le gusta.", "Probarlo con varios clientes y comparar tasas de respuesta frente a un mensaje anterior.", "Asumir que es mejor porque lo hizo la IA."]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', now(), 'Probarlo con varios clientes y comparar tasas de respuesta frente a un mensaje anterior.', '["Productividad", "Conocimiento"]'::jsonb, 4, 1),

('MV-C4', 'Cuestionario', 'Conocimiento', '2', '17', '¿Qué describe mejor un experimento A/B usando IA en mensajes de ventas?', 'Multiple Choice (una respuesta)', '["Enviar el mismo mensaje a todos los clientes.", "Probar dos versiones de mensajes generados o mejorados por IA y comparar tasas de apertura o respuesta.", "Cambiar el color del logo en el correo.", "Preguntar al equipo cuál les gusta más sin medir resultados."]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', now(), 'Probar dos versiones de mensajes generados o mejorados por IA y comparar tasas de apertura o respuesta.', '["Conocimiento"]'::jsonb, 4, 1),

('MV-C5', 'Cuestionario', 'Conocimiento', '2', '17', '¿Qué diferencia a un vendedor “orquestador de IA” de un usuario básico?', 'Multiple Choice (una respuesta)', '["Solo usa IA para corregir ortografía.", "Diseña flujos completos de trabajo con IA y los ajusta según datos reales de resultados.", "Rechaza cualquier tipo de medición.", "Usa IA únicamente para entretenimiento."]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', now(), 'Diseña flujos completos de trabajo con IA y los ajusta según datos reales de resultados.', '["Conocimiento"]'::jsonb, 4, 1),

('MV-C6', 'Cuestionario', 'Conocimiento', '2', '17', '¿Qué tarea es más adecuada para una IA básica en el trabajo de ventas?', 'Multiple Choice (una respuesta)', '["Decidir el precio final sin revisar políticas de la empresa.", "Redactar un primer borrador de correo a un cliente.", "Firmar contratos de manera automática.", "Aprobar descuentos fuera de política."]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', now(), 'Redactar un primer borrador de correo a un cliente.', '["Conocimiento"]'::jsonb, 4, 1),

('MV-C7', 'Cuestionario', 'Conocimiento', '2', '17', '¿Qué describe mejor a un CRM con funciones de IA?', 'Multiple Choice (una respuesta)', '["Un documento en papel donde se anotan las ventas.", "Un sistema que solo almacena contactos sin análisis.", "Un sistema que registra datos y sugiere próximas acciones o clientes prioritarios.", "Un chat de grupo sin historial de clientes."]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', now(), 'Un sistema que registra datos y sugiere próximas acciones o clientes prioritarios.', '["Conocimiento"]'::jsonb, 4, 2),

('MV-C8', 'Cuestionario', 'Conocimiento', '2', '17', '¿Qué ventaja ofrece un asistente de IA integrado al CRM frente a usar IA en una ventana aparte?', 'Multiple Choice (una respuesta)', '["Ninguna, es exactamente lo mismo.", "Facilita que la IA use datos del cliente (historial, sector, tamaño de cuenta) para personalizar sugerencias.", "Hace el sistema más lento sin beneficios.", "Solo cambia el color de la pantalla."]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', now(), 'Facilita que la IA use datos del cliente (historial, sector, tamaño de cuenta) para personalizar sugerencias.', '["Conocimiento"]'::jsonb, 4, 2),

('MV-C9', 'Cuestionario', 'Conocimiento', '2', '17', '¿Qué ventaja tiene combinar datos del CRM con IA para planear tu semana de trabajo?', 'Multiple Choice (una respuesta)', '["Hacer más reuniones internas sin ver clientes.", "Identificar qué cuentas atacar primero según probabilidad de cierre y valor potencial.", "Eliminar todos los contactos inactivos automáticamente.", "Evitar registrar actividades en el CRM."]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', now(), 'Identificar qué cuentas atacar primero según probabilidad de cierre y valor potencial.', '["Conocimiento", "Aplicación"]'::jsonb, 4, 2),

('MV-C10', 'Cuestionario', 'Conocimiento', '2', '17', '¿Qué representa mejor una mejora responsable en el uso de IA cuando impacta directamente en los incentivos de ventas (comisión)?', 'Multiple Choice (una respuesta)', '["Ocultar al equipo los prompts que funcionan mejor.", "Usar IA para maximizar ventas a cualquier costo, aunque la información sea confusa.", "Usar IA para aumentar ventas asegurando claridad, honestidad y alineamiento con la propuesta de valor real.", "Dejar de registrar ventas para que la IA no las vea."]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', now(), 'Usar IA para aumentar ventas asegurando claridad, honestidad y alineamiento con la propuesta de valor real.', '["Conocimiento", "Aplicación"]'::jsonb, 4, 2),

('MV-C11', 'Cuestionario', 'Conocimiento', '2', '17', '¿Qué es un “prompt” en el uso de IA?', 'Multiple Choice (una respuesta)', '["El nombre del cliente en el CRM.", "El reporte mensual de ventas.", "La instrucción o petición que se le da a la IA para que responda.", "El documento legal que firma el cliente."]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', now(), 'La instrucción o petición que se le da a la IA para que responda.', '["Conocimiento", "Aplicación"]'::jsonb, 4, 2),

('MV-C12', 'Cuestionario', 'Conocimiento', '2', '17', '¿Qué tipo de tarea es menos recomendable delegar totalmente a la IA?', 'Multiple Choice (una respuesta)', '["Sugerir ideas de asuntos para emails.", "Crear una lista de preguntas para una reunión.", "Decidir si aceptar o no una condición crítica de contrato sin revisar.", "Proponer frases para romper el hielo en la llamada."]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', now(), 'Decidir si aceptar o no una condición crítica de contrato sin revisar.', '["Conocimiento"]'::jsonb, 4, 2),

('MV-C13', 'Cuestionario', 'Conocimiento', '2', '17', '¿Qué describe mejor el uso de IA para “scoring” de leads?', 'Multiple Choice (una respuesta)', '["Ordenar listas por orden alfabético.", "Asignar manualmente un número al azar a cada cliente.", "Priorizar leads según probabilidad de compra usando datos históricos y patrones.", "Eliminar leads que no te caen bien."]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', now(), 'Priorizar leads según probabilidad de compra usando datos históricos y patrones.', '["Conocimiento", "Aplicación"]'::jsonb, 4, 3),

('MV-C14', 'Cuestionario', 'Conocimiento', '2', '17', '¿Qué riesgo existe al alimentar IA con información no actualizada del CRM?', 'Multiple Choice (una respuesta)', '["Ninguno, la IA siempre corrige los datos.", "La IA puede proponer acciones basadas en datos erróneos y afectar tus prioridades.", "Solo se afecta el diseño visual del CRM.", "El sistema se bloquea automáticamente."]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', now(), 'La IA puede proponer acciones basadas en datos erróneos y afectar tus prioridades.', '["Estrategia", "Conocimiento", "Aplicación"]'::jsonb, 4, 3),

('MV-C15', 'Cuestionario', 'Conocimiento', '2', '17', '¿Qué aporta incluir datos de “motivo de pérdida” en un análisis con IA del pipeline de ventas?', 'Multiple Choice (una respuesta)', '["Solo aumenta el tamaño de la base.", "Permite a la IA encontrar patrones de por qué se pierden oportunidades y proponer mejoras.", "Hace más lento el cierre de ventas.", "Solo sirve para marketing."]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', now(), 'Permite a la IA encontrar patrones de por qué se pierden oportunidades y proponer mejoras.', '["Conocimiento", "Aplicación"]'::jsonb, 4, 3),

('MV-C16', 'Cuestionario', 'Conocimiento', '2', '17', '¿Qué riesgo básico existe al copiar y pegar textos de IA sin revisar?', 'Multiple Choice (una respuesta)', '["Que el correo llegue más rápido.", "Que el cliente reciba información incorrecta o poco personalizada.", "Que el CRM deje de funcionar.", "Que el vendedor pierda acceso a su correo."]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', now(), 'Que el cliente reciba información incorrecta o poco personalizada.', '["Conocimiento", "Estrategia"]'::jsonb, 4, 3),

('MV-C17', 'Cuestionario', 'Conocimiento', '2', '17', '¿Cuál es un beneficio de guardar en la IA ejemplos de correos que funcionaron bien?', 'Multiple Choice (una respuesta)', '["Que la IA ignore esos ejemplos.", "Que la IA aprenda estilo y mensajes que generaron buenos resultados.", "Que los correos tarden más en generarse.", "Que se pierdan los datos del cliente."]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', now(), 'Que la IA aprenda estilo y mensajes que generaron buenos resultados.', '["Conocimiento"]'::jsonb, 4, 3),

('MV-C18', 'Cuestionario', 'Conocimiento', '2', '17', '¿Qué riesgo existe al basarse solo en el scoring de IA para decidir con quién hablar?', 'Multiple Choice (una respuesta)', '["Tener más información disponible.", "Dejar de lado cuentas con potencial que la IA no prioriza bien.", "Dejar de registrar datos en el CRM.", "Aumentar las llamadas efectivas."]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', now(), 'Dejar de lado cuentas con potencial que la IA no prioriza bien.', '["Conocimiento", "Estrategia"]'::jsonb, 4, 3),

('MV-C19', 'Cuestionario', 'Conocimiento', '2', '17', '¿Qué es un flujo de trabajo con IA en ventas?', 'Multiple Choice (una respuesta)', '["Una lista de tareas sin relación entre sí.", "Una secuencia de pasos donde IA apoya distintas etapas (investigación, mensajes, seguimiento, recordatorios).", "Un solo correo mejorado por IA.", "Solo una llamada telefónica."]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', now(), 'Una secuencia de pasos donde IA apoya distintas etapas (investigación, mensajes, seguimiento, recordatorios).', '["Conocimiento"]'::jsonb, 4, 4),

('MV-C20', 'Cuestionario', 'Conocimiento', '2', '17', '¿Qué es un “playbook” de ventas apoyado en IA?', 'Multiple Choice (una respuesta)', '["Una lista de correos genéricos sin orden.", "Un documento que define etapas, mensajes, prompts y flujos de IA para distintos escenarios de ventas.", "Un reporte financiero.", "Un chat improvisado entre colegas."]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', now(), 'Un documento que define etapas, mensajes, prompts y flujos de IA para distintos escenarios de ventas.', '["Conocimiento"]'::jsonb, 4, 4),

('MV-C21', 'Cuestionario', 'Conocimiento', '2', '17', '¿Cuál de estos datos es más sensible y debe cuidarse al usar IA?', 'Multiple Choice (una respuesta)', '["El clima de la semana.", "El logo público de la empresa.", "Listados con datos personales y de contacto de clientes.", "Información general disponible en la web."]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', now(), 'Listados con datos personales y de contacto de clientes.', '["Conocimiento", "Aplicación"]'::jsonb, 4, 4),

('MV-C22', 'Cuestionario', 'Conocimiento', '2', '17', '¿Qué describe mejor un “caso de uso” de IA en ventas?', 'Multiple Choice (una respuesta)', '["Una opinión personal sobre la IA.", "Un ejemplo concreto de cómo la IA apoya una tarea del proceso de ventas.", "El logo de la herramienta de IA.", "El manual de marca de la empresa."]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', now(), 'Un ejemplo concreto de cómo la IA apoya una tarea del proceso de ventas.', '["Conocimiento", "Aplicación"]'::jsonb, 4, 4),

('MV-C23', 'Cuestionario', 'Conocimiento', '2', '17', '¿Qué es un “prompt de contexto” útil para IA en ventas?', 'Multiple Choice (una respuesta)', '["“Haz lo que tú quieras con este cliente”.", "“Genera un correo para cualquier cliente”.", "“Genera un correo para un cliente del sector X, tamaño Y, interesado en el producto Z, después de haber tenido una demo”.", "“Escribe lo que sea”."]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', now(), '“Genera un correo para un cliente del sector X, tamaño Y, interesado en el producto Z, después de haber tenido una demo”.', '["Conocimiento"]'::jsonb, 4, 4),

('MV-C24', 'Cuestionario', 'Conocimiento', '2', '17', '¿Qué práctica es más responsable al compartir datos de clientes con IA externa?', 'Multiple Choice (una respuesta)', '["Subir bases completas con datos sensibles sin permiso.", "Consultar política de datos de la empresa y, si es necesario, anonimizar o reducir la información enviada.", "Compartir toda la información porque “todos lo hacen”.", "Nunca usar IA, aunque existan herramientas aprobadas."]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', now(), 'Consultar política de datos de la empresa y, si es necesario, anonimizar o reducir la información enviada.', '["Conocimiento", "Aplicación"]'::jsonb, 4, 4),

('MV-C25', 'Cuestionario', 'Conocimiento', '2', '17', '¿Qué riesgo ético aparece al usar IA para hiperpersonalizar mensajes de ventas?', 'Multiple Choice (una respuesta)', '["Aumentar la claridad de la oferta.", "Que el cliente sienta que se invadió su privacidad o se usó información que no esperaba.", "Reducir la tasa de respuesta.", "Perder toda la base de datos."]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', now(), 'Que el cliente sienta que se invadió su privacidad o se usó información que no esperaba.', '["Conocimiento", "Estrategia"]'::jsonb, 4, 5),

('MV-C26', 'Cuestionario', 'Conocimiento', '2', '17', '¿Cuál es una ventaja sencilla de usar IA para preparar una llamada de ventas?', 'Multiple Choice (una respuesta)', '["Evitar hablar con el cliente.", "Ahorrar tiempo al tener sugerencias de preguntas y argumentos.", "No volver a usar el CRM.", "Cerrar la venta sin escuchar al cliente."]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', now(), 'Ahorrar tiempo al tener sugerencias de preguntas y argumentos.', '["Conocimiento"]'::jsonb, 4, 5),

('MV-C27', 'Cuestionario', 'Conocimiento', '2', '17', '¿Por qué es importante respetar las políticas internas al cargar datos en herramientas de IA externas?', 'Multiple Choice (una respuesta)', '["Porque hace el trabajo más lento.", "Porque así se evita que otros colegas usen la IA.", "Porque protege datos de clientes y a la empresa de posibles riesgos legales.", "Porque la IA no funciona sin políticas."]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', now(), 'Porque protege datos de clientes y a la empresa de posibles riesgos legales.', '["Conocimiento", "Aplicación"]'::jsonb, 4, 5),

('MV-C28', 'Cuestionario', 'Conocimiento', '2', '17', '¿Por qué es útil guardar en IA ejemplos de objeciones típicas y respuestas efectivas?', 'Multiple Choice (una respuesta)', '["Para que la IA rechace a los clientes.", "Para que la IA pueda sugerir respuestas más alineadas a la realidad de tu mercado.", "Para borrar todas las objeciones.", "Para que el CRM deje de registrar objeciones."]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', now(), 'Para que la IA pueda sugerir respuestas más alineadas a la realidad de tu mercado.', '["Conocimiento"]'::jsonb, 4, 5),

('MV-C29', 'Cuestionario', 'Conocimiento', '2', '17', '¿Por qué tiene sentido documentar los prompts de IA que mejor funcionan en el equipo de ventas?', 'Multiple Choice (una respuesta)', '["Para que cada persona los guarde solo para sí.", "Para acelerar la curva de aprendizaje del equipo y estandarizar buenas prácticas.", "Para reemplazar los manuales de uso del CRM.", "Para que solo los use el área de TI."]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', now(), 'Para acelerar la curva de aprendizaje del equipo y estandarizar buenas prácticas.', '["Conocimiento", "Aplicación"]'::jsonb, 4, 5),

('MV-C30', 'Cuestionario', 'Conocimiento', '2', '17', '¿Por qué es importante medir el impacto de la IA en indicadores como tasa de cierre, ticket promedio o ciclo de venta?', 'Multiple Choice (una respuesta)', '["Para decidir si la IA reemplaza totalmente al equipo de ventas.", "Para saber si las prácticas con IA realmente mejoran resultados y justificar la inversión de tiempo/esfuerzo.", "Solo para cumplir un requisito de TI.", "Para comparar con empresas de otros sectores sin contexto."]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', now(), 'Para saber si las prácticas con IA realmente mejoran resultados y justificar la inversión de tiempo/esfuerzo.', '["Conocimiento"]'::jsonb, 4, 5);
