-- ============================================================================
-- PREGUNTAS PARA MIEMBROS DE FINANZAS
-- ============================================================================
-- Rol incluido:
--   - Rol ID 20: Miembros de Finanzas (area_id: 5, nivel_id: 4)
-- ============================================================================

-- ============================================================================
-- ROL 20: Miembros de Finanzas
-- ============================================================================

-- ADOPCIÓN - Rol 20
INSERT INTO "public"."preguntas" ("codigo", "section", "bloque", "area_id", "exclusivo_rol_id", "texto", "tipo", "opciones", "locale", "peso", "escala", "scoring", "created_at", "respuesta_correcta", "dimension", "exclusivo_nivel_id", "dificultad") VALUES
('MF-A1', 'Cuestionario', 'Adopción', '5', '20', 'En mi trabajo en finanzas, utilizo herramientas de IA para aclarar conceptos financieros (por ejemplo, que me expliquen en lenguaje simple términos de estados financieros).', 'Multiple Choice (escala Likert A–E)', '["Nunca", "Rara vez (≤ 1/mes)", "Ocasional (2–3/mes)", "Frecuente (semanal)", "Casi siempre"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', now(), null, '["Aplicación", "Inversión"]'::jsonb, 4, 1),

('MF-A2', 'Cuestionario', 'Adopción', '5', '20', 'Uso IA para resumir estados financieros o reportes extensos y entender los puntos clave antes de analizarlos a detalle.', 'Multiple Choice (escala Likert A–E)', '["Nunca", "Rara vez (≤ 1/mes)", "Ocasional (2–3/mes)", "Frecuente (semanal)", "Casi siempre"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', now(), null, '["Productividad", "Inversión", "Aplicación"]'::jsonb, 4, 1),

('MF-A3', 'Cuestionario', 'Adopción', '5', '20', 'Uso IA para detectar posibles errores (celdas inconsistentes, fórmulas sospechosas, montos atípicos) en mis hojas de cálculo financieras.', 'Multiple Choice (escala Likert A–E)', '["Nunca", "Rara vez (≤ 1/mes)", "Ocasional (2–3/mes)", "Frecuente (semanal)", "Casi siempre"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', now(), null, '["Aplicación"]'::jsonb, 4, 1),

('MF-A4', 'Cuestionario', 'Adopción', '5', '20', 'Utilizo IA o herramientas con IA integrada para priorizar las partidas a revisar en conciliaciones o cierres (por riesgo, monto, frecuencia, etc.).', 'Multiple Choice (escala Likert A–E)', '["Nunca", "Rara vez (≤ 1/mes)", "Ocasional (2–3/mes)", "Frecuente (semanal)", "Casi siempre"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', now(), null, '["Aplicación", "Estrategia"]'::jsonb, 4, 1),

('MF-A5', 'Cuestionario', 'Adopción', '5', '20', 'Lidero o co-lidero experimentos de IA en finanzas (pruebas de concepto, pilotos) midiendo impacto en tiempos, errores o insights generados.', 'Multiple Choice (escala Likert A–E)', '["Nunca", "Rara vez (≤ 1/mes)", "Ocasional (2–3/mes)", "Frecuente (semanal)", "Casi siempre"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', now(), null, '["Productividad", "Aplicación"]'::jsonb, 4, 1),

('MF-A6', 'Cuestionario', 'Adopción', '5', '20', 'Utilizo IA para mejorar la redacción de correos o comentarios en reportes financieros (por ejemplo, explicaciones a otras áreas).', 'Multiple Choice (escala Likert A–E)', '["Nunca", "Rara vez (≤ 1/mes)", "Ocasional (2–3/mes)", "Frecuente (semanal)", "Casi siempre"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', now(), null, '["Productividad", "Inversión"]'::jsonb, 4, 1),

('MF-A7', 'Cuestionario', 'Adopción', '5', '20', 'Cuando tengo tablas de gastos o ingresos, pido a la IA que sugiera posibles explicaciones de variaciones que luego reviso con criterio propio.', 'Multiple Choice (escala Likert A–E)', '["Nunca", "Rara vez (≤ 1/mes)", "Ocasional (2–3/mes)", "Frecuente (semanal)", "Casi siempre"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', now(), null, '["Aplicación"]'::jsonb, 4, 2),

('MF-A8', 'Cuestionario', 'Adopción', '5', '20', 'Integro la IA en mi rutina de cierre mensual (por ejemplo, para listar transacciones a revisar, resumir incidencias o preparar comentarios iniciales).', 'Multiple Choice (escala Likert A–E)', '["Nunca", "Rara vez (≤ 1/mes)", "Ocasional (2–3/mes)", "Frecuente (semanal)", "Casi siempre"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', now(), null, '["Aplicación"]'::jsonb, 4, 2),

('MF-A9', 'Cuestionario', 'Adopción', '5', '20', 'He participado en el diseño o ajuste de reglas de un sistema de IA/anomalías en finanzas (por ejemplo, umbrales, variables relevantes).', 'Multiple Choice (escala Likert A–E)', '["Nunca", "Rara vez (≤ 1/mes)", "Ocasional (2–3/mes)", "Frecuente (semanal)", "Casi siempre"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', now(), null, '["Aplicación"]'::jsonb, 4, 2),

('MF-A10', 'Cuestionario', 'Adopción', '5', '20', 'He participado en la definición de métricas para evaluar el éxito de casos de uso de IA (ej. reducción de días de cierre, menor tasa de errores, etc.).', 'Multiple Choice (escala Likert A–E)', '["Nunca", "Rara vez (≤ 1/mes)", "Ocasional (2–3/mes)", "Frecuente (semanal)", "Casi siempre"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', now(), null, '["Productividad", "Aplicación"]'::jsonb, 4, 2),

('MF-A11', 'Cuestionario', 'Adopción', '5', '20', 'Antes de usar IA con datos financieros, reviso si estoy cumpliendo las políticas de confidencialidad de la empresa.', 'Multiple Choice (escala Likert A–E)', '["Nunca", "Rara vez (≤ 1/mes)", "Ocasional (2–3/mes)", "Frecuente (semanal)", "Casi siempre"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', now(), null, '["Aplicación", "Inversión", "Estrategia"]'::jsonb, 4, 2),

('MF-A12', 'Cuestionario', 'Adopción', '5', '20', 'Consulto a IA para preparar borradores de comentarios en reportes para gerencia, y después los ajusto.', 'Multiple Choice (escala Likert A–E)', '["Nunca", "Rara vez (≤ 1/mes)", "Ocasional (2–3/mes)", "Frecuente (semanal)", "Casi siempre"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', now(), null, '["Productividad"]'::jsonb, 4, 2),

('MF-A13', 'Cuestionario', 'Adopción', '5', '20', 'Comparto con mi equipo plantillas de prompts o formatos de uso de IA que me han funcionado para tareas financieras.', 'Multiple Choice (escala Likert A–E)', '["Nunca", "Rara vez (≤ 1/mes)", "Ocasional (2–3/mes)", "Frecuente (semanal)", "Casi siempre"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', now(), null, '["Aplicación"]'::jsonb, 4, 3),

('MF-A14', 'Cuestionario', 'Adopción', '5', '20', 'Documenté junto con otros equipos (TI, Riesgos, Auditoría) cómo se usan las salidas de IA en nuestros procesos financieros.', 'Multiple Choice (escala Likert A–E)', '["Nunca", "Rara vez (≤ 1/mes)", "Ocasional (2–3/mes)", "Frecuente (semanal)", "Casi siempre"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', now(), null, '["Aplicación", "Inversión", "Estrategia"]'::jsonb, 4, 3),

('MF-A15', 'Cuestionario', 'Adopción', '5', '20', 'Comparto activamente buenas prácticas y guías de uso de IA con otros colegas de finanzas, apoyando su curva de aprendizaje.', 'Multiple Choice (escala Likert A–E)', '["Nunca", "Rara vez (≤ 1/mes)", "Ocasional (2–3/mes)", "Frecuente (semanal)", "Casi siempre"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', now(), null, '["Aplicación"]'::jsonb, 4, 3),

('MF-A16', 'Cuestionario', 'Adopción', '5', '20', 'Estoy dispuesto(a) a invertir tiempo en aprender lo básico de IA para aplicar algo en mis tareas (aunque sea de forma muy sencilla).', 'Multiple Choice (escala Likert A–E)', '["Nunca", "Rara vez (≤ 1/mes)", "Ocasional (2–3/mes)", "Frecuente (semanal)", "Casi siempre"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', now(), null, '["Productividad", "Aplicación"]'::jsonb, 4, 3),

('MF-A17', 'Cuestionario', 'Adopción', '5', '20', 'Estoy invirtiendo tiempo en aprender mejores preguntas (“prompts”) para obtener resultados más útiles de la IA en mis tareas financieras.', 'Multiple Choice (escala Likert A–E)', '["Nunca", "Rara vez (≤ 1/mes)", "Ocasional (2–3/mes)", "Frecuente (semanal)", "Casi siempre"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', now(), null, '["Productividad"]'::jsonb, 4, 3),

('MF-A18', 'Cuestionario', 'Adopción', '5', '20', 'He ajustado mi forma de trabajar (por ejemplo, cómo organizo datos o archivos) para que la IA pueda ayudarme mejor.', 'Multiple Choice (escala Likert A–E)', '["Nunca", "Rara vez (≤ 1/mes)", "Ocasional (2–3/mes)", "Frecuente (semanal)", "Casi siempre"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', now(), null, '["Aplicación"]'::jsonb, 4, 3),

('MF-A19', 'Cuestionario', 'Adopción', '5', '20', 'Ajusto mis análisis cuando detecto que un modelo de IA puede estar sobreajustado o reaccionando en exceso a eventos atípicos.', 'Multiple Choice (escala Likert A–E)', '["Nunca", "Rara vez (≤ 1/mes)", "Ocasional (2–3/mes)", "Frecuente (semanal)", "Casi siempre"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', now(), null, '["Aplicación"]'::jsonb, 4, 4),

('MF-A20', 'Cuestionario', 'Adopción', '5', '20', 'Colaboro con equipos de TI/datos para mejorar la calidad de los datos que usan nuestras soluciones de IA financieras.', 'Multiple Choice (escala Likert A–E)', '["Nunca", "Rara vez (≤ 1/mes)", "Ocasional (2–3/mes)", "Frecuente (semanal)", "Casi siempre"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', now(), null, '["Aplicación"]'::jsonb, 4, 4),

('MF-A21', 'Cuestionario', 'Adopción', '5', '20', 'Cuando tengo que preparar un reporte financiero sencillo, considero si la IA podría ayudarme a ordenar ideas o estructurar el texto.', 'Multiple Choice (escala Likert A–E)', '["Nunca", "Rara vez (≤ 1/mes)", "Ocasional (2–3/mes)", "Frecuente (semanal)", "Casi siempre"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', now(), null, '["Inversión"]'::jsonb, 4, 4),

('MF-A22', 'Cuestionario', 'Adopción', '5', '20', 'Participo en conversaciones con mi equipo para proponer tareas específicas donde la IA podría ahorrarnos tiempo (por ejemplo, reclasificación de gastos, explicación de variaciones).', 'Multiple Choice (escala Likert A–E)', '["Nunca", "Rara vez (≤ 1/mes)", "Ocasional (2–3/mes)", "Frecuente (semanal)", "Casi siempre"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', now(), null, '["Productividad", "Aplicación"]'::jsonb, 4, 4),

('MF-A23', 'Cuestionario', 'Adopción', '5', '20', 'Uso IA para simular escenarios simples (ej. “¿qué pasaría si los gastos aumentan 5%?”) basados en datos que yo mismo preparo.', 'Multiple Choice (escala Likert A–E)', '["Nunca", "Rara vez (≤ 1/mes)", "Ocasional (2–3/mes)", "Frecuente (semanal)", "Casi siempre"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', now(), null, '["Aplicación"]'::jsonb, 4, 4),

('MF-A24', 'Cuestionario', 'Adopción', '5', '20', 'Uso IA para simular varios escenarios financieros (por ejemplo, cambios de tipo de cambio, tasas de interés, niveles de gasto) y preparar recomendaciones para gerencia.', 'Multiple Choice (escala Likert A–E)', '["Nunca", "Rara vez (≤ 1/mes)", "Ocasional (2–3/mes)", "Frecuente (semanal)", "Casi siempre"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', now(), null, '["Aplicación", "Inversión"]'::jsonb, 4, 4),

('MF-A25', 'Cuestionario', 'Adopción', '5', '20', 'Cuando detecto problemas de sesgo, errores o riesgos en una solución de IA, los escalo y propongo ajustes en lugar de solo “arreglarlos a mano”.', 'Multiple Choice (escala Likert A–E)', '["Nunca", "Rara vez (≤ 1/mes)", "Ocasional (2–3/mes)", "Frecuente (semanal)", "Casi siempre"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', now(), null, '["Estrategia"]'::jsonb, 4, 5),

('MF-A26', 'Cuestionario', 'Adopción', '5', '20', 'Comento con mis colegas de finanzas sobre posibles usos de IA, aunque todavía no la usemos de forma regular.', 'Multiple Choice (escala Likert A–E)', '["Nunca", "Rara vez (≤ 1/mes)", "Ocasional (2–3/mes)", "Frecuente (semanal)", "Casi siempre"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', now(), null, '["Aplicación"]'::jsonb, 4, 5),

('MF-A27', 'Cuestionario', 'Adopción', '5', '20', 'Tomo en cuenta los riesgos de privacidad y cumplimiento al decidir qué tipo de información comparto con la IA.', 'Multiple Choice (escala Likert A–E)', '["Nunca", "Rara vez (≤ 1/mes)", "Ocasional (2–3/mes)", "Frecuente (semanal)", "Casi siempre"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', now(), null, '["Aplicación", "Estrategia"]'::jsonb, 4, 5),

('MF-A28', 'Cuestionario', 'Adopción', '5', '20', 'Considero explícitamente los riesgos de sesgo o errores de la IA cuando presento resultados o conclusiones a otros.', 'Multiple Choice (escala Likert A–E)', '["Nunca", "Rara vez (≤ 1/mes)", "Ocasional (2–3/mes)", "Frecuente (semanal)", "Casi siempre"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', now(), null, '["Productividad", "Estrategia"]'::jsonb, 4, 5),

('MF-A29', 'Cuestionario', 'Adopción', '5', '20', 'He impulsado activamente cambios de proceso en el equipo de finanzas basados en ahorros de tiempo o mejoras de calidad obtenidos con IA.', 'Multiple Choice (escala Likert A–E)', '["Nunca", "Rara vez (≤ 1/mes)", "Ocasional (2–3/mes)", "Frecuente (semanal)", "Casi siempre"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', now(), null, '["Productividad", "Aplicación"]'::jsonb, 4, 5),

('MF-A30', 'Cuestionario', 'Adopción', '5', '20', 'He ayudado a integrar la IA en procesos clave de finanzas (por ejemplo, forecast, presupuesto, análisis de rentabilidad) de manera repetible, no solo puntual.', 'Multiple Choice (escala Likert A–E)', '["Nunca", "Rara vez (≤ 1/mes)", "Ocasional (2–3/mes)", "Frecuente (semanal)", "Casi siempre"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', now(), null, '["Inversión"]'::jsonb, 4, 5);

-- CONOCIMIENTO - Rol 20
INSERT INTO "public"."preguntas" ("codigo", "section", "bloque", "area_id", "exclusivo_rol_id", "texto", "tipo", "opciones", "locale", "peso", "escala", "scoring", "created_at", "respuesta_correcta", "dimension", "exclusivo_nivel_id", "dificultad") VALUES
('MF-C1', 'Cuestionario', 'Conocimiento', '5', '20', '¿Cuál de las siguientes opciones describe mejor qué es la inteligencia artificial aplicada a finanzas?', 'Multiple Choice (una respuesta)', '["Un sistema que reemplaza completamente a los contadores.", "Tecnologías que analizan datos financieros para automatizar tareas y apoyar la toma de decisiones.", "Un tipo de base de datos tradicional para guardar facturas.", "Un software exclusivo para grandes bancos."]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', now(), 'Tecnologías que analizan datos financieros para automatizar tareas y apoyar la toma de decisiones.', '["Conocimiento", "Aplicación"]'::jsonb, 4, 1),

('MF-C2', 'Cuestionario', 'Conocimiento', '5', '20', '¿Cuál de estas es una buena práctica al usar IA para redactar explicaciones de desviaciones presupuestarias?', 'Multiple Choice (una respuesta)', '["Copiar la respuesta sin revisarla.", "Validar la respuesta contra los datos reales y ajustar el texto según el criterio profesional.", "Pedir que la IA invente cifras para que suene más convincente.", "Usar la misma explicación para todos los reportes sin importar el contexto."]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', now(), 'Validar la respuesta contra los datos reales y ajustar el texto según el criterio profesional.', '["Conocimiento"]'::jsonb, 4, 1),

('MF-C3', 'Cuestionario', 'Conocimiento', '5', '20', '¿Cuál es una forma eficiente de usar IA junto con hojas de cálculo en finanzas?', 'Multiple Choice (una respuesta)', '["Pedir a la IA que cree estados financieros sin datos de entrada.", "Exportar datos a una tabla, explicar el contexto a la IA y pedirle ayuda para encontrar patrones o errores.", "Esconder fórmulas para que nadie entienda el archivo.", "Borrar toda la información sensible antes de analizar."]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', now(), 'Exportar datos a una tabla, explicar el contexto a la IA y pedirle ayuda para encontrar patrones o errores.', '["Conocimiento"]'::jsonb, 4, 1),

('MF-C4', 'Cuestionario', 'Conocimiento', '5', '20', '¿Cuál de estas tareas es más adecuada para un sistema de IA de detección de anomalías?', 'Multiple Choice (una respuesta)', '["Calcular manualmente cada saldo día por día.", "Identificar patrones inusuales de pagos a proveedores respecto de periodos anteriores.", "Imprimir reportes sin revisarlos.", "Eliminar registros con montos altos."]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', now(), 'Identificar patrones inusuales de pagos a proveedores respecto de periodos anteriores.', '["Conocimiento"]'::jsonb, 4, 1),

('MF-C5', 'Cuestionario', 'Conocimiento', '5', '20', '¿Qué se busca al “industrializar” el uso de IA en finanzas?', 'Multiple Choice (una respuesta)', '["Mantener proyectos aislados y experimentales.", "Integrar IA de forma estable en procesos, con gobierno de datos, métricas y responsables claros.", "Usar IA solo cuando hay tiempo libre.", "Evitar medir el impacto para no generar presión."]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', now(), 'Integrar IA de forma estable en procesos, con gobierno de datos, métricas y responsables claros.', '["Conocimiento", "Aplicación"]'::jsonb, 4, 1),

('MF-C6', 'Cuestionario', 'Conocimiento', '5', '20', '¿Cuál es un ejemplo sencillo de uso de IA en el área de cuentas por pagar (AP)?', 'Multiple Choice (una respuesta)', '["Imprimir manualmente todas las facturas para revisarlas.", "Usar IA para extraer datos clave de las facturas y sugerir cuentas contables.", "Guardar las facturas en cajas físicas por año.", "Hacer las conciliaciones solo al final del año."]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', now(), 'Usar IA para extraer datos clave de las facturas y sugerir cuentas contables.', '["Conocimiento", "Aplicación"]'::jsonb, 4, 1),

('MF-C7', 'Cuestionario', 'Conocimiento', '5', '20', '¿Qué ventaja tiene usar IA para clasificar gastos en categorías contables?', 'Multiple Choice (una respuesta)', '["Evitar completamente la participación del equipo de finanzas.", "Acelerar la clasificación propuesta, que luego puede ser revisada por humanos.", "Eliminar la necesidad de cumplir con normas contables.", "Hacer que las auditorías ya no sean necesarias."]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', now(), 'Acelerar la clasificación propuesta, que luego puede ser revisada por humanos.', '["Conocimiento"]'::jsonb, 4, 2),

('MF-C8', 'Cuestionario', 'Conocimiento', '5', '20', '¿Qué ventaja clave aporta la IA en el proceso de cierre contable mensual?', 'Multiple Choice (una respuesta)', '["Permite omitir conciliaciones bancarias.", "Ayuda a identificar errores o anomalías antes de cerrar, reduciendo retrabajos.", "Elimina la necesidad de controles internos.", "Sustituye por completo al equipo contable."]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', now(), 'Ayuda a identificar errores o anomalías antes de cerrar, reduciendo retrabajos.', '["Conocimiento"]'::jsonb, 4, 2),

('MF-C9', 'Cuestionario', 'Conocimiento', '5', '20', 'En un flujo de trabajo de conciliación automática con IA, ¿qué rol suele tener el analista de finanzas?', 'Multiple Choice (una respuesta)', '["Ignorar todas las alertas generadas.", "Revisar las excepciones que la IA marca como posibles errores y tomar decisiones de corrección.", "Borrar transacciones duplicadas sin verificación.", "Desactivar los controles cuando se acercan los cierres."]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', now(), 'Revisar las excepciones que la IA marca como posibles errores y tomar decisiones de corrección.', '["Conocimiento"]'::jsonb, 4, 2),

('MF-C10', 'Cuestionario', 'Conocimiento', '5', '20', '¿Cuál es un indicador clave para evaluar el impacto de IA en un proceso financiero?', 'Multiple Choice (una respuesta)', '["Cantidad de correos enviados al día.", "Horas de trabajo manual ahorradas y reducción de errores versus el proceso anterior.", "Número de presentaciones en PowerPoint.", "Número de chistes generados por la IA."]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', now(), 'Horas de trabajo manual ahorradas y reducción de errores versus el proceso anterior.', '["Conocimiento", "Inversión"]'::jsonb, 4, 2),

('MF-C11', 'Cuestionario', 'Conocimiento', '5', '20', '¿Cuál es una limitación importante de usar IA generativa (como ChatGPT) en finanzas?', 'Multiple Choice (una respuesta)', '["Siempre es más precisa que los analistas humanos.", "No comete errores y no necesita revisión.", "Puede “inventar” información si no se le dan datos claros y verificados.", "Solo se puede usar fuera del horario laboral."]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', now(), 'Puede “inventar” información si no se le dan datos claros y verificados.', '["Conocimiento"]'::jsonb, 4, 2),

('MF-C12', 'Cuestionario', 'Conocimiento', '5', '20', '¿Qué significa “detección de anomalías” en datos financieros con IA?', 'Multiple Choice (una respuesta)', '["Eliminar todas las transacciones pequeñas.", "Buscar patrones repetitivos en correos electrónicos.", "Identificar transacciones inusuales que pueden ser errores o posibles fraudes.", "Ordenar las facturas por fecha."]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', now(), 'Identificar transacciones inusuales que pueden ser errores o posibles fraudes.', '["Conocimiento", "Aplicación", "Inversión"]'::jsonb, 4, 2),

('MF-C13', 'Cuestionario', 'Conocimiento', '5', '20', '¿Qué significa usar IA como “copiloto” en tareas de finanzas?', 'Multiple Choice (una respuesta)', '["Dejar que la IA tome las decisiones finales.", "Usarla como apoyo para sugerir pasos y automatizar partes del trabajo mientras tú mantienes el control.", "Dejar de aprender contabilidad.", "Usarla solo para chatear con colegas."]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', now(), 'Usarla como apoyo para sugerir pasos y automatizar partes del trabajo mientras tú mantienes el control.', '["Conocimiento", "Aplicación"]'::jsonb, 4, 3),

('MF-C14', 'Cuestionario', 'Conocimiento', '5', '20', '¿Qué es importante al usar IA para proyecciones de flujo de caja?', 'Multiple Choice (una respuesta)', '["Usar siempre el mismo modelo sin importar cambios en el negocio.", "Revisar supuestos, horizonte temporal y sensibilidad a diferentes escenarios.", "Confiar solo en datos de hace más de 5 años.", "No documentar los parámetros utilizados."]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', now(), 'Revisar supuestos, horizonte temporal y sensibilidad a diferentes escenarios.', '["Conocimiento"]'::jsonb, 4, 3),

('MF-C15', 'Cuestionario', 'Conocimiento', '5', '20', '¿Qué se entiende por “ciclo de mejora continua” en soluciones de IA en finanzas?', 'Multiple Choice (una respuesta)', '["Implementar y nunca volver a revisar el modelo.", "Revisar periódicamente resultados, ajustar parámetros, datos y reglas según la retroalimentación del negocio.", "Cambiar modelos cada día sin validación.", "Desactivar el sistema cuando hay auditoría."]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', now(), 'Revisar periódicamente resultados, ajustar parámetros, datos y reglas según la retroalimentación del negocio.', '["Conocimiento"]'::jsonb, 4, 3),

('MF-C16', 'Cuestionario', 'Conocimiento', '5', '20', '¿Cuál de estas acciones respeta mejor la confidencialidad de la información financiera al usar IA?', 'Multiple Choice (una respuesta)', '["Copiar estados financieros completos en una herramienta pública sin políticas claras.", "Enviar archivos financieros personales al chat de un amigo.", "Seguir las políticas internas de la empresa sobre qué datos se pueden cargar en herramientas de IA.", "Publicar datos financieros en redes sociales y pedir análisis."]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', now(), 'Seguir las políticas internas de la empresa sobre qué datos se pueden cargar en herramientas de IA.', '["Conocimiento", "Aplicación", "Estrategia"]'::jsonb, 4, 3),

('MF-C17', 'Cuestionario', 'Conocimiento', '5', '20', '¿Qué tipo de dato deberías evitar cargar en una herramienta de IA pública sin protección adicional?', 'Multiple Choice (una respuesta)', '["Tareas genéricas de estudio.", "Información ya publicada en el sitio web de la empresa.", "Datos de clientes con nombre, monto y número de cuenta.", "Explicaciones conceptuales sobre estados financieros."]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', now(), 'Datos de clientes con nombre, monto y número de cuenta.', '["Conocimiento"]'::jsonb, 4, 3),

('MF-C18', 'Cuestionario', 'Conocimiento', '5', '20', 'En un proceso de cuentas por cobrar (AR), ¿cómo puede ayudar la IA?', 'Multiple Choice (una respuesta)', '["Inventando pagos que no existen.", "Agrupando clientes según patrones de pago para priorizar la cobranza.", "Eliminando facturas atrasadas del sistema.", "Cambiando las tasas de interés sin autorización."]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', now(), 'Agrupando clientes según patrones de pago para priorizar la cobranza.', '["Conocimiento"]'::jsonb, 4, 3),

('MF-C19', 'Cuestionario', 'Conocimiento', '5', '20', '¿Cuál es un riesgo al integrar IA a procesos de aprobación de pagos?', 'Multiple Choice (una respuesta)', '["Tener más trazabilidad de decisiones.", "Que las reglas y límites de aprobación no se respeten si se automatizan sin buena configuración.", "Reducir el tiempo de proceso.", "Tener menos errores de tipografía."]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', now(), 'Que las reglas y límites de aprobación no se respeten si se automatizan sin buena configuración.', '["Conocimiento", "Estrategia"]'::jsonb, 4, 4),

('MF-C20', 'Cuestionario', 'Conocimiento', '5', '20', '¿Por qué es relevante la colaboración con otras áreas (TI, Riesgos, Operaciones) en proyectos de IA de finanzas?', 'Multiple Choice (una respuesta)', '["Para que finanzas pierda control sobre los procesos.", "Porque muchos casos de uso cruzan sistemas, datos y procesos que no son solo de finanzas.", "Porque así se reparte la responsabilidad de posibles fallos.", "Porque lo exige la moda."]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', now(), 'Porque muchos casos de uso cruzan sistemas, datos y procesos que no son solo de finanzas.', '["Conocimiento", "Estrategia"]'::jsonb, 4, 4),

('MF-C21', 'Cuestionario', 'Conocimiento', '5', '20', '¿Cuál de estas tareas es más adecuada para ser apoyada por IA en finanzas?', 'Multiple Choice (una respuesta)', '["Aprobar pagos sin revisión humana.", "Generar borradores de explicaciones de variaciones de gastos a partir de tablas de Excel.", "Firmar cheques en nombre del CFO.", "Decidir cambios contables sin criterios contables."]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', now(), 'Generar borradores de explicaciones de variaciones de gastos a partir de tablas de Excel.', '["Conocimiento"]'::jsonb, 4, 4),

('MF-C22', 'Cuestionario', 'Conocimiento', '5', '20', '¿Cuál de estas preguntas a la IA es más útil para apoyar el análisis financiero?', 'Multiple Choice (una respuesta)', '["Haz mi trabajo por mí.", "Escribe un chiste sobre contabilidad.", "Revisa esta tabla de gastos y sugiere posibles razones de las variaciones por centro de costo.", "Dime cualquier cosa sobre economía."]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', now(), 'Revisa esta tabla de gastos y sugiere posibles razones de las variaciones por centro de costo.', '["Conocimiento", "Inversión"]'::jsonb, 4, 4),

('MF-C23', 'Cuestionario', 'Conocimiento', '5', '20', '¿Qué es importante al interpretar recomendaciones de IA en análisis de costos?', 'Multiple Choice (una respuesta)', '["Aceptar todo sin cuestionar.", "Revisar si los supuestos tienen sentido y contrastar con otras fuentes.", "Ignorar los datos de entrada.", "Usar siempre los mismos parámetros sin importar el caso."]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', now(), 'Revisar si los supuestos tienen sentido y contrastar con otras fuentes.', '["Conocimiento", "Inversión"]'::jsonb, 4, 4),

('MF-C24', 'Cuestionario', 'Conocimiento', '5', '20', '¿Qué es “explicabilidad” en modelos de IA aplicados a finanzas?', 'Multiple Choice (una respuesta)', '["La capacidad de la IA para cambiar sus decisiones sin avisar.", "La facilidad para entender por qué el modelo tomó cierta decisión o recomendación.", "La velocidad de procesamiento del modelo.", "La cantidad de datos almacenados."]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', now(), 'La facilidad para entender por qué el modelo tomó cierta decisión o recomendación.', '["Conocimiento", "Aplicación"]'::jsonb, 4, 4),

('MF-C25', 'Cuestionario', 'Conocimiento', '5', '20', '¿Cuál de las siguientes es una aproximación responsable al uso de IA generativa en soportes a decisiones estratégicas financieras?', 'Multiple Choice (una respuesta)', '["Dejar que la IA decida sola el presupuesto anual.", "Usarla para generar escenarios y argumentos, pero validar con modelos financieros estructurados y criterio experto.", "Ignorar los datos y solo usar texto generado por IA.", "Ajustar las respuestas de la IA para que coincidan con lo que la dirección quiere escuchar."]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', now(), 'Usarla para generar escenarios y argumentos, pero validar con modelos financieros estructurados y criterio experto.', '["Conocimiento", "Aplicación"]'::jsonb, 4, 5),

('MF-C26', 'Cuestionario', 'Conocimiento', '5', '20', '¿Qué describe mejor la diferencia entre automatización “tradicional” (ej. macros) e IA?', 'Multiple Choice (una respuesta)', '["No hay diferencia, son exactamente lo mismo.", "La automatización tradicional sigue reglas fijas; la IA aprende patrones a partir de datos.", "La automatización tradicional solo se usa en marketing.", "La IA no necesita datos para funcionar."]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', now(), 'La automatización tradicional sigue reglas fijas; la IA aprende patrones a partir de datos.', '["Conocimiento"]'::jsonb, 4, 5),

('MF-C27', 'Cuestionario', 'Conocimiento', '5', '20', '¿Qué describe mejor el rol del colaborador de finanzas frente a la IA?', 'Multiple Choice (una respuesta)', '["Dejar de pensar y aceptar todo lo que diga la herramienta.", "Ser un “revisor crítico” que valida, corrige y decide cómo usar las salidas de la IA.", "No usar IA porque es solo para TI.", "Compartir datos confidenciales porque “la IA es segura por defecto”."]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', now(), 'Ser un “revisor crítico” que valida, corrige y decide cómo usar las salidas de la IA.', '["Conocimiento"]'::jsonb, 4, 5),

('MF-C28', 'Cuestionario', 'Conocimiento', '5', '20', '¿Por qué es relevante entender de dónde vienen los datos usados por la IA en finanzas?', 'Multiple Choice (una respuesta)', '["Para poder modificarlos sin control.", "Porque la calidad y origen de los datos afectan la confiabilidad de los resultados.", "Porque no es importante, la IA corrige los errores automáticamente.", "Porque así se puede ocultar información."]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', now(), 'Porque la calidad y origen de los datos afectan la confiabilidad de los resultados.', '["Conocimiento", "Aplicación"]'::jsonb, 4, 5),

('MF-C29', 'Cuestionario', 'Conocimiento', '5', '20', '¿Por qué puede ser útil involucrar a TI y Riesgos al implementar nuevas herramientas de IA en finanzas?', 'Multiple Choice (una respuesta)', '["Para que se encarguen de todo y finanzas no opine.", "Para asegurar temas de seguridad, integración con otros sistemas y cumplimiento de políticas.", "Para hacer el proceso más lento sin razón.", "Para evitar documentar los cambios."]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', now(), 'Para asegurar temas de seguridad, integración con otros sistemas y cumplimiento de políticas.', '["Conocimiento", "Aplicación", "Estrategia"]'::jsonb, 4, 5),

('MF-C30', 'Cuestionario', 'Conocimiento', '5', '20', '¿Qué rol puede jugar un “referente de IA en finanzas” a nivel de colaborador?', 'Multiple Choice (una respuesta)', '["Diseñar políticas de IA de toda la compañía sin involucrar a nadie.", "Ser puente entre el equipo de finanzas y especialistas de datos/tecnología, traduciendo necesidades y limitaciones.", "Sustituir al CFO en la definición de la estrategia.", "Certificar modelos sin evaluarlos."]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', now(), 'Ser puente entre el equipo de finanzas y especialistas de datos/tecnología, traduciendo necesidades y limitaciones.', '["Conocimiento"]'::jsonb, 4, 5);
