-- ============================================================================
-- PREGUNTAS PARA GERENCIA MEDIA
-- ============================================================================
-- Rol incluido:
--   - Rol ID 24: Gerencia Media (area_id: 1, nivel_id: 3)
-- ============================================================================

-- ============================================================================
-- ROL 24: Gerencia Media
-- ============================================================================

-- ADOPCIÓN - Rol 24
INSERT INTO "public"."preguntas" ("codigo", "section", "bloque", "area_id", "exclusivo_rol_id", "texto", "tipo", "opciones", "locale", "peso", "escala", "scoring", "created_at", "respuesta_correcta", "dimension", "exclusivo_nivel_id", "dificultad") VALUES
('GEM-A1', 'Cuestionario', 'Adopción', '1', '24', '¿Con qué frecuencia utilizas IA para resumir correos extensos o documentos previos a una reunión?', 'Multiple Choice (escala Likert A–E)', '["Nunca", "Rara vez (≤ 1/mes)", "Ocasional (2–3/mes)", "Frecuente (semanal)", "Muy frecuente (diaria)"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', now(), null, '["Aplicación"]'::jsonb, 3, 1),

('GEM-A2', 'Cuestionario', 'Adopción', '1', '24', '¿Con qué frecuencia pides a una herramienta de IA que te dé ideas iniciales para resolver un problema de tu área (por ejemplo, mejorar un proceso)?', 'Multiple Choice (escala Likert A–E)', '["Nunca", "Rara vez (≤ 1/mes)", "Ocasional (2–3/mes)", "Frecuente (semanal)", "Muy frecuente (diaria)"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', now(), null, '["Aplicación"]'::jsonb, 3, 1),

('GEM-A3', 'Cuestionario', 'Adopción', '1', '24', '¿Con qué frecuencia compartes con tu equipo ejemplos sencillos de cómo podrían usar IA en su trabajo diario?', 'Multiple Choice (escala Likert A–E)', '["Nunca", "Rara vez (≤ 1/mes)", "Ocasional (2–3/mes)", "Frecuente (semanal)", "Muy frecuente (diaria)"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', now(), null, '["Aplicación"]'::jsonb, 3, 1),

('GEM-A4', 'Cuestionario', 'Adopción', '1', '24', '¿Con qué frecuencia revisas críticamente las respuestas de la IA antes de usarlas en una decisión o comunicación formal?', 'Multiple Choice (escala Likert A–E)', '["Nunca", "Rara vez (≤ 1/mes)", "Ocasional (2–3/mes)", "Frecuente (semanal)", "Muy frecuente (diaria)"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', now(), null, '["Aplicación"]'::jsonb, 3, 1),

('GEM-A5', 'Cuestionario', 'Adopción', '1', '24', '¿Con qué frecuencia consideras el tiempo y esfuerzo que podrías ahorrar usando IA versus hacerlo todo manualmente?', 'Multiple Choice (escala Likert A–E)', '["Nunca", "Rara vez (≤ 1/mes)", "Ocasional (2–3/mes)", "Frecuente (semanal)", "Muy frecuente (diaria)"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', now(), null, '["Productividad"]'::jsonb, 3, 1),

('GEM-A6', 'Cuestionario', 'Adopción', '1', '24', '¿Con qué frecuencia comentas con otras áreas (TI, Datos, RRHH) posibles usos de IA para tu área, aunque aún sean ideas iniciales?', 'Multiple Choice (escala Likert A–E)', '["Nunca", "Rara vez (≤ 1/mes)", "Ocasional (2–3/mes)", "Frecuente (semanal)", "Muy frecuente (diaria)"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', now(), null, '["Aplicación"]'::jsonb, 3, 1),

('GEM-A7', 'Cuestionario', 'Adopción', '1', '24', '¿Con qué frecuencia utilizas IA para generar borradores de correos, minutas o presentaciones que luego editas?', 'Multiple Choice (escala Likert A–E)', '["Nunca", "Rara vez (≤ 1/mes)", "Ocasional (2–3/mes)", "Frecuente (semanal)", "Muy frecuente (diaria)"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', now(), null, '["Aplicación"]'::jsonb, 3, 2),

('GEM-A8', 'Cuestionario', 'Adopción', '1', '24', '¿Con qué frecuencia comparas el resultado de la IA con tus propios análisis o los del equipo antes de presentarlo a la dirección?', 'Multiple Choice (escala Likert A–E)', '["Nunca", "Rara vez (≤ 1/mes)", "Ocasional (2–3/mes)", "Frecuente (semanal)", "Muy frecuente (diaria)"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', now(), null, '["Aplicación"]'::jsonb, 3, 2),

('GEM-A9', 'Cuestionario', 'Adopción', '1', '24', '¿Con qué frecuencia invitas a miembros de tu equipo a probar IA en tareas concretas y comentan juntos los resultados?', 'Multiple Choice (escala Likert A–E)', '["Nunca", "Rara vez (≤ 1/mes)", "Ocasional (2–3/mes)", "Frecuente (semanal)", "Muy frecuente (diaria)"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', now(), null, '["Productividad", "Aplicación"]'::jsonb, 3, 2),

('GEM-A10', 'Cuestionario', 'Adopción', '1', '24', '¿Con qué frecuencia revisas las políticas internas (privacidad, seguridad) antes de compartir datos en herramientas de IA?', 'Multiple Choice (escala Likert A–E)', '["Nunca", "Rara vez (≤ 1/mes)", "Ocasional (2–3/mes)", "Frecuente (semanal)", "Muy frecuente (diaria)"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', now(), null, '["Aplicación", "Estrategia"]'::jsonb, 3, 2),

('GEM-A11', 'Cuestionario', 'Adopción', '1', '24', '¿Con qué frecuencia propones pequeños pilotos de IA en tu área (por ejemplo, automatizar una tarea repetitiva) con metas y plazos claros?', 'Multiple Choice (escala Likert A–E)', '["Nunca", "Rara vez (≤ 1/mes)", "Ocasional (2–3/mes)", "Frecuente (semanal)", "Muy frecuente (diaria)"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', now(), null, '["Productividad"]'::jsonb, 3, 2),

('GEM-A12', 'Cuestionario', 'Adopción', '1', '24', '¿Con qué frecuencia compartes con otras gerencias (marketing, operaciones, gobierno, etcétera) aprendizajes sobre el uso de IA?', 'Multiple Choice (escala Likert A–E)', '["Nunca", "Rara vez (≤ 1/mes)", "Ocasional (2–3/mes)", "Frecuente (semanal)", "Muy frecuente (diaria)"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', now(), null, '["Aplicación"]'::jsonb, 3, 2),

('GEM-A13', 'Cuestionario', 'Adopción', '1', '24', '¿Con qué frecuencia usas IA para analizar datos de tu área (tablas, indicadores) y obtener resúmenes o visualizaciones preliminares?', 'Multiple Choice (escala Likert A–E)', '["Nunca", "Rara vez (≤ 1/mes)", "Ocasional (2–3/mes)", "Frecuente (semanal)", "Muy frecuente (diaria)"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', now(), null, '["Aplicación"]'::jsonb, 3, 3),

('GEM-A14', 'Cuestionario', 'Adopción', '1', '24', '¿Con qué frecuencia iteras tus instrucciones o prompts para mejorar la calidad de lo que la IA entrega?', 'Multiple Choice (escala Likert A–E)', '["Nunca", "Rara vez (≤ 1/mes)", "Ocasional (2–3/mes)", "Frecuente (semanal)", "Muy frecuente (diaria)"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', now(), null, '["Aplicación"]'::jsonb, 3, 3),

('GEM-A15', 'Cuestionario', 'Adopción', '1', '24', '¿Con qué frecuencia integras los resultados de IA en tus reportes para la alta dirección, explicando cómo se obtuvieron?', 'Multiple Choice (escala Likert A–E)', '["Nunca", "Rara vez (≤ 1/mes)", "Ocasional (2–3/mes)", "Frecuente (semanal)", "Muy frecuente (diaria)"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', now(), null, '["Productividad"]'::jsonb, 3, 3),

('GEM-A16', 'Cuestionario', 'Adopción', '1', '24', '¿Con qué frecuencia defines junto con tu equipo estándares de uso de IA (cuándo usarla, cuándo no, buenas prácticas)?', 'Multiple Choice (escala Likert A–E)', '["Nunca", "Rara vez (≤ 1/mes)", "Ocasional (2–3/mes)", "Frecuente (semanal)", "Muy frecuente (diaria)"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', now(), null, '["Aplicación"]'::jsonb, 3, 3),

('GEM-A17', 'Cuestionario', 'Adopción', '1', '24', '¿Con qué frecuencia evalúas si el tiempo ahorrado por IA se traduce en mejor servicio, calidad o análisis y no solo en hacer lo mismo más rápido?', 'Multiple Choice (escala Likert A–E)', '["Nunca", "Rara vez (≤ 1/mes)", "Ocasional (2–3/mes)", "Frecuente (semanal)", "Muy frecuente (diaria)"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', now(), null, '["Productividad"]'::jsonb, 3, 3),

('GEM-A18', 'Cuestionario', 'Adopción', '1', '24', '¿Con qué frecuencia consideras aspectos éticos (sesgos, transparencia, privacidad) al decidir dónde sí y dónde no usar IA?', 'Multiple Choice (escala Likert A–E)', '["Nunca", "Rara vez (≤ 1/mes)", "Ocasional (2–3/mes)", "Frecuente (semanal)", "Muy frecuente (diaria)"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', now(), null, '["Estrategia"]'::jsonb, 3, 3),

('GEM-A19', 'Cuestionario', 'Adopción', '1', '24', '¿Con qué frecuencia defines junto con tu equipo procesos estándar donde el uso de IA está claramente integrado (pasos, responsables, controles)?', 'Multiple Choice (escala Likert A–E)', '["Nunca", "Rara vez (≤ 1/mes)", "Ocasional (2–3/mes)", "Frecuente (semanal)", "Muy frecuente (diaria)"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', now(), null, '["Aplicación"]'::jsonb, 3, 4),

('GEM-A20', 'Cuestionario', 'Adopción', '1', '24', '¿Con qué frecuencia promueves y facilitas capacitaciones prácticas para que tu equipo aprenda a usar IA en su rol específico?', 'Multiple Choice (escala Likert A–E)', '["Nunca", "Rara vez (≤ 1/mes)", "Ocasional (2–3/mes)", "Frecuente (semanal)", "Muy frecuente (diaria)"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', now(), null, '["Aplicación"]'::jsonb, 3, 4),

('GEM-A21', 'Cuestionario', 'Adopción', '1', '24', '¿Con qué frecuencia participas en el diseño de políticas de IA (uso responsable, datos, transparencia) para tu área?', 'Multiple Choice (escala Likert A–E)', '["Nunca", "Rara vez (≤ 1/mes)", "Ocasional (2–3/mes)", "Frecuente (semanal)", "Muy frecuente (diaria)"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', now(), null, '["Aplicación"]'::jsonb, 3, 4),

('GEM-A22', 'Cuestionario', 'Adopción', '1', '24', '¿Con qué frecuencia revisas resultados de proyectos de IA con otras áreas (TI, Legal, Finanzas) para ajustar alcance, métricas o presupuesto?', 'Multiple Choice (escala Likert A–E)', '["Nunca", "Rara vez (≤ 1/mes)", "Ocasional (2–3/mes)", "Frecuente (semanal)", "Muy frecuente (diaria)"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', now(), null, '["Productividad", "Inversión"]'::jsonb, 3, 4),

('GEM-A23', 'Cuestionario', 'Adopción', '1', '24', '¿Con qué frecuencia reorientas recursos (tiempo, personas, presupuesto) desde tareas manuales hacia iniciativas potenciadas por IA que generan mayor valor?', 'Multiple Choice (escala Likert A–E)', '["Nunca", "Rara vez (≤ 1/mes)", "Ocasional (2–3/mes)", "Frecuente (semanal)", "Muy frecuente (diaria)"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', now(), null, '["Productividad", "Inversión", "Estrategia"]'::jsonb, 3, 4),

('GEM-A24', 'Cuestionario', 'Adopción', '1', '24', '¿Con qué frecuencia monitoreas y respondes a preocupaciones de tu equipo sobre impacto de la IA en sus roles (miedo a reemplazo, ética, carga de trabajo)?', 'Multiple Choice (escala Likert A–E)', '["Nunca", "Rara vez (≤ 1/mes)", "Ocasional (2–3/mes)", "Frecuente (semanal)", "Muy frecuente (diaria)"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', now(), null, '["Aplicación", "Estrategia"]'::jsonb, 3, 4),

('GEM-A25', 'Cuestionario', 'Adopción', '1', '24', '¿Con qué frecuencia participas activamente en la definición del roadmap de IA de tu área, discutiendo prioridades con la alta dirección y TI?', 'Multiple Choice (escala Likert A–E)', '["Nunca", "Rara vez (≤ 1/mes)", "Ocasional (2–3/mes)", "Frecuente (semanal)", "Muy frecuente (diaria)"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', now(), null, '["Estrategia"]'::jsonb, 3, 5),

('GEM-A26', 'Cuestionario', 'Adopción', '1', '24', '¿Con qué frecuencia revisas el portafolio de proyectos de IA para reorientar inversiones hacia iniciativas con mayor impacto estratégico y social o para el cliente?', 'Multiple Choice (escala Likert A–E)', '["Nunca", "Rara vez (≤ 1/mes)", "Ocasional (2–3/mes)", "Frecuente (semanal)", "Muy frecuente (diaria)"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', now(), null, '["Estrategia"]'::jsonb, 3, 5),

('GEM-A27', 'Cuestionario', 'Adopción', '1', '24', '¿Con qué frecuencia diseñas o patrocinas experimentos transformadores, por ejemplo el rediseño de procesos completos apoyados en IA y no solo la automatización de tareas?', 'Multiple Choice (escala Likert A–E)', '["Nunca", "Rara vez (≤ 1/mes)", "Ocasional (2–3/mes)", "Frecuente (semanal)", "Muy frecuente (diaria)"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', now(), null, '["Aplicación"]'::jsonb, 3, 5),

('GEM-A28', 'Cuestionario', 'Adopción', '1', '24', '¿Con qué frecuencia impulsas cambios en la gestión de talento (perfiles, roles, evaluaciones) para integrar IA de forma sostenible y justa?', 'Multiple Choice (escala Likert A–E)', '["Nunca", "Rara vez (≤ 1/mes)", "Ocasional (2–3/mes)", "Frecuente (semanal)", "Muy frecuente (diaria)"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', now(), null, '["Aplicación"]'::jsonb, 3, 5),

('GEM-A29', 'Cuestionario', 'Adopción', '1', '24', '¿Con qué frecuencia incorporas explícitamente criterios de ética, transparencia y explicabilidad al aprobar proyectos de IA en tu área?', 'Multiple Choice (escala Likert A–E)', '["Nunca", "Rara vez (≤ 1/mes)", "Ocasional (2–3/mes)", "Frecuente (semanal)", "Muy frecuente (diaria)"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', now(), null, '["Estrategia"]'::jsonb, 3, 5),

('GEM-A30', 'Cuestionario', 'Adopción', '1', '24', '¿Con qué frecuencia comunicas hacia arriba y hacia tu equipo historias de impacto (casos de éxito o fracaso) de IA para ajustar la cultura y la estrategia?', 'Multiple Choice (escala Likert A–E)', '["Nunca", "Rara vez (≤ 1/mes)", "Ocasional (2–3/mes)", "Frecuente (semanal)", "Muy frecuente (diaria)"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', now(), null, '["Aplicación", "Estrategia"]'::jsonb, 3, 5);

-- CONOCIMIENTO - Rol 24
INSERT INTO "public"."preguntas" ("codigo", "section", "bloque", "area_id", "exclusivo_rol_id", "texto", "tipo", "opciones", "locale", "peso", "escala", "scoring", "created_at", "respuesta_correcta", "dimension", "exclusivo_nivel_id", "dificultad") VALUES
('GEM-C1', 'Cuestionario', 'Conocimiento', '1', '24', '¿Cuál de las siguientes opciones describe mejor la Inteligencia Artificial (IA) en el contexto de tu organización?', 'Multiple Choice (una respuesta)', '["Un tipo de hardware que hace que las computadoras sean más rápidas.", "Un conjunto de técnicas que permiten a los sistemas aprender de datos y automatizar tareas.", "Un software solo para programadores expertos.", "Una herramienta exclusiva del área de TI."]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', now(), 'Un conjunto de técnicas que permiten a los sistemas aprender de datos y automatizar tareas.', '["Conocimiento"]'::jsonb, 3, 1),

('GEM-C2', 'Cuestionario', 'Conocimiento', '1', '24', '¿Cuál es un ejemplo sencillo de IA generativa que podrías usar como gerente medio?', 'Multiple Choice (una respuesta)', '["Un sistema de fichaje horario tradicional.", "Un asistente que genera borradores de correos y textos a partir de instrucciones.", "Una hoja de cálculo sin fórmulas.", "Un teléfono fijo."]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', now(), 'Un asistente que genera borradores de correos y textos a partir de instrucciones.', '["Conocimiento"]'::jsonb, 3, 1),

('GEM-C3', 'Cuestionario', 'Conocimiento', '1', '24', '¿Cuál es un riesgo básico al usar IA para tomar decisiones de gestión?', 'Multiple Choice (una respuesta)', '["Que todos los resultados sean siempre perfectos.", "Que el modelo pueda contener sesgos y dar recomendaciones injustas.", "Que aumente el tiempo de análisis siempre.", "Que elimine la necesidad de supervisión humana."]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', now(), 'Que el modelo pueda contener sesgos y dar recomendaciones injustas.', '["Conocimiento", "Estrategia"]'::jsonb, 3, 1),

('GEM-C4', 'Cuestionario', 'Conocimiento', '1', '24', '¿Cuál de estos usos de IA impacta directamente en la productividad de un gerente medio?', 'Multiple Choice (una respuesta)', '["Revisar manualmente todos los correos uno por uno.", "Usar IA para resumir documentos largos antes de una reunión.", "Imprimir todos los reportes para leerlos en papel.", "Enviar correos sin asunto."]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', now(), 'Usar IA para resumir documentos largos antes de una reunión.', '["Conocimiento", "Productividad", "Aplicación"]'::jsonb, 3, 1),

('GEM-C5', 'Cuestionario', 'Conocimiento', '1', '24', '¿Cuál afirmación es más correcta sobre el rol de la IA en la estrategia del área?', 'Multiple Choice (una respuesta)', '["La IA reemplaza completamente la planificación del gerente.", "La IA puede aportar insumos, pero la decisión estratégica sigue siendo humana.", "La estrategia de IA solo pertenece a TI.", "La IA solo sirve para tareas administrativas pequeñas."]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', now(), 'La IA puede aportar insumos, pero la decisión estratégica sigue siendo humana.', '["Conocimiento", "Estrategia"]'::jsonb, 3, 1),

('GEM-C6', 'Cuestionario', 'Conocimiento', '1', '24', '¿Cuál es una buena práctica básica al usar IA con datos sensibles (por ejemplo, de personas o ciudadanos)?', 'Multiple Choice (una respuesta)', '["Copiar y pegar toda la base de datos en cualquier herramienta pública.", "Compartir información confidencial sin autorización.", "Respetar políticas de privacidad y consultar a TI/Legal antes de usar datos sensibles.", "No informar al equipo del uso de IA."]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', now(), 'Respetar políticas de privacidad y consultar a TI/Legal antes de usar datos sensibles.', '["Conocimiento", "Aplicación"]'::jsonb, 3, 1),

('GEM-C7', 'Cuestionario', 'Conocimiento', '1', '24', '¿Cuál es una diferencia clave entre IA tradicional y IA generativa?', 'Multiple Choice (una respuesta)', '["La IA tradicional solo funciona en el sector público.", "La IA generativa crea nuevos contenidos (texto, imagen, código) a partir de instrucciones.", "La IA generativa no necesita datos.", "No hay diferencias relevantes."]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', now(), 'La IA generativa crea nuevos contenidos (texto, imagen, código) a partir de instrucciones.', '["Conocimiento"]'::jsonb, 3, 2),

('GEM-C8', 'Cuestionario', 'Conocimiento', '1', '24', '¿Qué uso de IA es más adecuado para un gerente medio en ventas o servicio?', 'Multiple Choice (una respuesta)', '["Generar respuestas automáticas a clientes sin revisión humana.", "Analizar patrones de consultas para identificar motivos frecuentes de contacto.", "Eliminar todo contacto humano con el cliente.", "Enviar spam masivo."]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', now(), 'Analizar patrones de consultas para identificar motivos frecuentes de contacto.', '["Conocimiento", "Aplicación"]'::jsonb, 3, 2),

('GEM-C9', 'Cuestionario', 'Conocimiento', '1', '24', 'En finanzas o contabilidad, ¿qué tarea puede apoyar la IA?', 'Multiple Choice (una respuesta)', '["Aprobar gastos sin supervisión.", "Detectar anomalías en transacciones para apoyar la revisión de fraudes.", "Cambiar normas contables automáticamente.", "Firmar estados financieros."]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', now(), 'Detectar anomalías en transacciones para apoyar la revisión de fraudes.', '["Conocimiento"]'::jsonb, 3, 2),

('GEM-C10', 'Cuestionario', 'Conocimiento', '1', '24', 'En gestión de personas o recursos humanos, ¿qué riesgo debes vigilar al usar IA para prefiltrar candidatos?', 'Multiple Choice (una respuesta)', '["Que la IA reduzca sesgos y discrimine menos.", "Que la IA replique y amplifique sesgos presentes en los datos históricos.", "Que todos los candidatos sean idénticos.", "Que el proceso sea más rápido."]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', now(), 'Que la IA replique y amplifique sesgos presentes en los datos históricos.', '["Conocimiento", "Aplicación", "Estrategia"]'::jsonb, 3, 2),

('GEM-C11', 'Cuestionario', 'Conocimiento', '1', '24', '¿Qué indicador refleja mejor la productividad al usar IA?', 'Multiple Choice (una respuesta)', '["Número de correos enviados.", "Tiempo ahorrado en la elaboración de reportes repetitivos.", "Número de reuniones presenciales.", "Tamaño del equipo."]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', now(), 'Tiempo ahorrado en la elaboración de reportes repetitivos.', '["Conocimiento", "Productividad"]'::jsonb, 3, 2),

('GEM-C12', 'Cuestionario', 'Conocimiento', '1', '24', 'Desde la perspectiva de inversión, ¿qué es una decisión prudente al incorporar IA en tu área?', 'Multiple Choice (una respuesta)', '["Adoptar la herramienta más cara para no quedarse atrás.", "Probar primero pilotos acotados con un problema concreto y medir resultados.", "Comprar muchas licencias sin plan de uso.", "Dejar que cada persona use cualquier herramienta sin guía."]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', now(), 'Probar primero pilotos acotados con un problema concreto y medir resultados.', '["Conocimiento", "Inversión"]'::jsonb, 3, 2),

('GEM-C13', 'Cuestionario', 'Conocimiento', '1', '24', '¿Qué es un prompt en IA generativa?', 'Multiple Choice (una respuesta)', '["El costo mensual de la herramienta.", "La instrucción o mensaje que das a la IA para que genere una respuesta.", "El modelo matemático interno.", "El informe final en PDF."]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', now(), 'La instrucción o mensaje que das a la IA para que genere una respuesta.', '["Conocimiento"]'::jsonb, 3, 3),

('GEM-C14', 'Cuestionario', 'Conocimiento', '1', '24', 'Para mejorar la calidad de un reporte generado con IA sobre indicadores de tu área, ¿qué práctica ayuda más?', 'Multiple Choice (una respuesta)', '["Aceptar el primer resultado sin cambios.", "Dar contexto específico (datos, objetivos, audiencia) en el prompt y pedir iteraciones.", "Pedir solo que sea mejor.", "Esconder información clave a la IA."]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', now(), 'Dar contexto específico (datos, objetivos, audiencia) en el prompt y pedir iteraciones.', '["Conocimiento"]'::jsonb, 3, 3),

('GEM-C15', 'Cuestionario', 'Conocimiento', '1', '24', 'En operaciones o compras, ¿qué uso de IA refleja un enfoque productivo?', 'Multiple Choice (una respuesta)', '["Generar chistes para el equipo.", "Analizar historiales de pedido para identificar patrones de demanda.", "Eliminar la revisión humana de proveedores.", "Gestionar inventarios solo por intuición."]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', now(), 'Analizar historiales de pedido para identificar patrones de demanda.', '["Conocimiento", "Aplicación"]'::jsonb, 3, 3),

('GEM-C16', 'Cuestionario', 'Conocimiento', '1', '24', '¿Cuál es un indicador razonable para evaluar el impacto estratégico de un proyecto de IA?', 'Multiple Choice (una respuesta)', '["Número de reuniones sobre IA.", "Alineación del proyecto con objetivos del plan estratégico del área.", "Cantidad de correos con IA en el asunto.", "Tasa de errores ortográficos."]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', now(), 'Alineación del proyecto con objetivos del plan estratégico del área.', '["Conocimiento", "Estrategia"]'::jsonb, 3, 3),

('GEM-C17', 'Cuestionario', 'Conocimiento', '1', '24', 'En el sector público, ¿qué riesgo surge si se usa IA para priorizar solicitudes ciudadanas sin supervisión?', 'Multiple Choice (una respuesta)', '["Todas las solicitudes recibirán mayor transparencia.", "Podrían generarse decisiones opacas y discriminatorias.", "Se eliminarán los tiempos de espera.", "Se reduce la necesidad de regulación."]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', now(), 'Podrían generarse decisiones opacas y discriminatorias.', '["Conocimiento", "Estrategia"]'::jsonb, 3, 3),

('GEM-C18', 'Cuestionario', 'Conocimiento', '1', '24', 'Desde la perspectiva de inversión, ¿qué decisión muestra madurez en el uso de IA?', 'Multiple Choice (una respuesta)', '["Financiar solo proyectos vistosos para marketing.", "Seleccionar proyectos con casos de negocio claros y métricas de retorno esperadas.", "Evitar toda inversión en capacitación.", "Cambiar de herramienta cada mes."]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', now(), 'Seleccionar proyectos con casos de negocio claros y métricas de retorno esperadas.', '["Conocimiento", "Inversión", "Aplicación"]'::jsonb, 3, 3),

('GEM-C19', 'Cuestionario', 'Conocimiento', '1', '24', '¿Qué significa gobernanza de IA en una organización?', 'Multiple Choice (una respuesta)', '["Solo elegir la marca de la herramienta.", "Conjunto de políticas, roles y controles para usar IA de forma segura, ética y alineada a la estrategia.", "Delegar todo a TI.", "Permitir que cada quien use lo que quiera sin reglas."]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', now(), 'Conjunto de políticas, roles y controles para usar IA de forma segura, ética y alineada a la estrategia.', '["Conocimiento", "Estrategia"]'::jsonb, 3, 4),

('GEM-C20', 'Cuestionario', 'Conocimiento', '1', '24', '¿Qué indicador ayuda a evaluar si la IA realmente empodera al equipo?', 'Multiple Choice (una respuesta)', '["Número de licencias activadas.", "Porcentaje de procesos clave donde el equipo reporta menor carga administrativa y mayor tiempo para tareas de valor.", "Número de correos sobre IA.", "Cantidad de herramientas distintas."]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', now(), 'Porcentaje de procesos clave donde el equipo reporta menor carga administrativa y mayor tiempo para tareas de valor.', '["Conocimiento", "Aplicación"]'::jsonb, 3, 4),

('GEM-C21', 'Cuestionario', 'Conocimiento', '1', '24', 'En un proyecto transversal (ventas, operaciones, gobierno) con IA, ¿qué rol típico tiene la gerencia media?', 'Multiple Choice (una respuesta)', '["Definir sola la arquitectura técnica del modelo.", "Traducir necesidades del negocio a requerimientos claros y acompañar la adopción en primera línea.", "Aprobar facturas únicamente.", "Delegar todo a consultores externos."]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', now(), 'Traducir necesidades del negocio a requerimientos claros y acompañar la adopción en primera línea.', '["Conocimiento"]'::jsonb, 3, 4),

('GEM-C22', 'Cuestionario', 'Conocimiento', '1', '24', '¿Qué es un piloto controlado de IA?', 'Multiple Choice (una respuesta)', '["Uso masivo sin comunicación.", "Prueba acotada en un proceso definido, con métricas claras y tiempo limitado.", "Apagar todos los sistemas antiguos.", "Implementar en toda la organización en un día."]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', now(), 'Prueba acotada en un proceso definido, con métricas claras y tiempo limitado.', '["Conocimiento"]'::jsonb, 3, 4),

('GEM-C23', 'Cuestionario', 'Conocimiento', '1', '24', '¿Qué riesgo aparece si tu equipo depende totalmente de IA para tareas críticas sin planes de contingencia?', 'Multiple Choice (una respuesta)', '["Mayor resiliencia.", "Vulnerabilidad cuando la herramienta falla o cambia de condiciones.", "Reducción de productividad siempre.", "Ningún riesgo importante."]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', now(), 'Vulnerabilidad cuando la herramienta falla o cambia de condiciones.', '["Conocimiento", "Aplicación", "Estrategia"]'::jsonb, 3, 4),

('GEM-C24', 'Cuestionario', 'Conocimiento', '1', '24', 'Desde la perspectiva de inversión, ¿qué indica madurez en la asignación de presupuesto a IA?', 'Multiple Choice (una respuesta)', '["Distribuir presupuesto solo por moda interna.", "Priorizar proyectos donde hay caso de negocio, capacidad de adopción y alineación con la estrategia.", "Solo financiar proyectos vistosos.", "No medir retorno."]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', now(), 'Priorizar proyectos donde hay caso de negocio, capacidad de adopción y alineación con la estrategia.', '["Conocimiento", "Inversión"]'::jsonb, 3, 4),

('GEM-C25', 'Cuestionario', 'Conocimiento', '1', '24', '¿Qué caracteriza a una estrategia de IA bien integrada en la organización?', 'Multiple Choice (una respuesta)', '["Lista de herramientas sin relación con los objetivos.", "Portafolio de iniciativas priorizadas, alineado con la estrategia general y con gobernanza clara.", "Solo un documento de marketing.", "Un único proyecto estrella aislado."]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', now(), 'Portafolio de iniciativas priorizadas, alineado con la estrategia general y con gobernanza clara.', '["Conocimiento", "Estrategia"]'::jsonb, 3, 5),

('GEM-C26', 'Cuestionario', 'Conocimiento', '1', '24', '¿Qué es un enfoque human in the loop en IA?', 'Multiple Choice (una respuesta)', '["IA que funciona sin humanos.", "Humanos revisan, corrigen y deciden sobre las salidas de IA en etapas clave.", "Humanos solo aprueban presupuestos.", "Eliminar supervisión humana."]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', now(), 'Humanos revisan, corrigen y deciden sobre las salidas de IA en etapas clave.', '["Conocimiento"]'::jsonb, 3, 5),

('GEM-C27', 'Cuestionario', 'Conocimiento', '1', '24', 'En proyectos de IA a nivel área o sector público, ¿qué indicador refleja impacto ciudadano o cliente más allá de la eficiencia interna?', 'Multiple Choice (una respuesta)', '["Número de modelos entrenados.", "Mejora en tiempos de respuesta y satisfacción medida por usuarios o ciudadanos.", "Cantidad de servidores comprados.", "Horas de capacitación."]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', now(), 'Mejora en tiempos de respuesta y satisfacción medida por usuarios o ciudadanos.', '["Conocimiento", "Productividad"]'::jsonb, 3, 5),

('GEM-C28', 'Cuestionario', 'Conocimiento', '1', '24', '¿Qué riesgo estratégico surge si la inversión en IA se concentra solo en automatizar tareas existentes?', 'Multiple Choice (una respuesta)', '["Mayor innovación disruptiva.", "Perder oportunidades de reimaginar procesos y modelos de servicio o negocio.", "Reducir la productividad.", "Eliminar la necesidad de talento."]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', now(), 'Perder oportunidades de reimaginar procesos y modelos de servicio o negocio.', '["Conocimiento", "Inversión", "Productividad", "Estrategia"]'::jsonb, 3, 5),

('GEM-C29', 'Cuestionario', 'Conocimiento', '1', '24', '¿Qué rol debe jugar la gerencia media en la priorización del portafolio de proyectos de IA?', 'Multiple Choice (una respuesta)', '["Ninguno, todo es de la alta dirección.", "Proveer casos de uso concretos, estimar impacto, riesgos y capacidad de adopción en su área.", "Solo aprobar presupuestos.", "Solo comunicar decisiones ya tomadas."]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', now(), 'Proveer casos de uso concretos, estimar impacto, riesgos y capacidad de adopción en su área.', '["Conocimiento"]'::jsonb, 3, 5),

('GEM-C30', 'Cuestionario', 'Conocimiento', '1', '24', '¿Qué representa mejor una madurez alta en el uso de IA para productividad y talento?', 'Multiple Choice (una respuesta)', '["Exigir que todos usen IA sin formación.", "Rediseñar roles y competencias, complementando IA con desarrollo de habilidades humanas clave.", "Reducir toda inversión en capacitación humana.", "Evaluar desempeño solo por horas frente a la pantalla."]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', now(), 'Rediseñar roles y competencias, complementando IA con desarrollo de habilidades humanas clave.', '["Conocimiento", "Productividad", "Aplicación"]'::jsonb, 3, 5);
