-- ============================================================================
-- PREGUNTAS PARA DISEÑO/INDUSTRIAS CREATIVAS
-- ============================================================================
-- Rol incluido:
--   - Rol ID 10: Diseño/Industrias Creativas (area_id: 11, nivel_id: 3)
-- ============================================================================

-- ============================================================================
-- ROL 10: Diseño/Industrias Creativas
-- ============================================================================

-- ADOPCIÓN - Rol 10
INSERT INTO "public"."preguntas" ("codigo", "section", "bloque", "area_id", "exclusivo_rol_id", "texto", "tipo", "opciones", "locale", "peso", "escala", "scoring", "created_at", "respuesta_correcta", "dimension", "exclusivo_nivel_id", "dificultad") VALUES
('DIC-A1', 'Cuestionario', 'Adopción', '11', '10', 'Uso herramientas de IA (por ejemplo, remover fondo automático, “generar imagen rápida”) para tareas simples en mis proyectos de diseño.', 'Multiple Choice (escala Likert A–E)', '["Nunca", "Rara vez (≤ 1/mes)", "Ocasional (2–3/mes)", "Frecuente (semanal)", "Muy frecuente (diaria)"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', now(), null, '["Aplicación"]'::jsonb, 3, 1),

('DIC-A2', 'Cuestionario', 'Adopción', '11', '10', 'Genero ideas visuales iniciales (moodboards, estilos, paletas) con apoyo de IA antes de diseñar manualmente.', 'Multiple Choice (escala Likert A–E)', '["Nunca", "Rara vez (≤ 1/mes)", "Ocasional (2–3/mes)", "Frecuente (semanal)", "Muy frecuente (diaria)"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', now(), null, '["Aplicación"]'::jsonb, 3, 1),

('DIC-A3', 'Cuestionario', 'Adopción', '11', '10', 'Ajusto por mi cuenta los prompts o parámetros de las herramientas de IA para acercar el resultado a lo que necesito.', 'Multiple Choice (escala Likert A–E)', '["Nunca", "Rara vez (≤ 1/mes)", "Ocasional (2–3/mes)", "Frecuente (semanal)", "Muy frecuente (diaria)"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', now(), null, '["Aplicación"]'::jsonb, 3, 1),

('DIC-A4', 'Cuestionario', 'Adopción', '11', '10', 'Comparto con compañeros/as de equipo los resultados generados por IA para recibir feedback y decidir qué se puede usar.', 'Multiple Choice (escala Likert A–E)', '["Nunca", "Rara vez (≤ 1/mes)", "Ocasional (2–3/mes)", "Frecuente (semanal)", "Muy frecuente (diaria)"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', now(), null, '["Productividad", "Aplicación"]'::jsonb, 3, 1),

('DIC-A5', 'Cuestionario', 'Adopción', '11', '10', 'Dedico tiempo a explorar las funciones de IA incluidas en las herramientas que ya uso (por ejemplo, IA en Photoshop, Figma, Canva).', 'Multiple Choice (escala Likert A–E)', '["Nunca", "Rara vez (≤ 1/mes)", "Ocasional (2–3/mes)", "Frecuente (semanal)", "Muy frecuente (diaria)"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', now(), null, '["Productividad", "Aplicación"]'::jsonb, 3, 1),

('DIC-A6', 'Cuestionario', 'Adopción', '11', '10', 'Antes de proponer al cliente una imagen generada por IA, pienso en posibles riesgos (derechos de autor, contenido sensible, sesgos).', 'Multiple Choice (escala Likert A–E)', '["Nunca", "Rara vez (≤ 1/mes)", "Ocasional (2–3/mes)", "Frecuente (semanal)", "Muy frecuente (diaria)"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', now(), null, '["Estrategia"]'::jsonb, 3, 1),

('DIC-A7', 'Cuestionario', 'Adopción', '11', '10', 'Uso IA para generar variantes rápidas de una propuesta visual (por ejemplo, cambiar estilos, fondos, encuadres).', 'Multiple Choice (escala Likert A–E)', '["Nunca", "Rara vez (≤ 1/mes)", "Ocasional (2–3/mes)", "Frecuente (semanal)", "Muy frecuente (diaria)"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', now(), null, '["Aplicación"]'::jsonb, 3, 2),

('DIC-A8', 'Cuestionario', 'Adopción', '11', '10', 'Comparo el rendimiento de piezas creadas con apoyo de IA vs. piezas tradicionales (por ejemplo, en engagement o clics).', 'Multiple Choice (escala Likert A–E)', '["Nunca", "Rara vez (≤ 1/mes)", "Ocasional (2–3/mes)", "Frecuente (semanal)", "Muy frecuente (diaria)"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', now(), null, '["Aplicación"]'::jsonb, 3, 2),

('DIC-A9', 'Cuestionario', 'Adopción', '11', '10', 'Ajusto el nivel de detalle de los prompts (estilo, iluminación, encuadre) según el tipo de pieza que necesito.', 'Multiple Choice (escala Likert A–E)', '["Nunca", "Rara vez (≤ 1/mes)", "Ocasional (2–3/mes)", "Frecuente (semanal)", "Muy frecuente (diaria)"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', now(), null, '["Aplicación"]'::jsonb, 3, 2),

('DIC-A10', 'Cuestionario', 'Adopción', '11', '10', 'Colaboro con otros diseñadores para crear y compartir bibliotecas de prompts o plantillas de IA reutilizables.', 'Multiple Choice (escala Likert A–E)', '["Nunca", "Rara vez (≤ 1/mes)", "Ocasional (2–3/mes)", "Frecuente (semanal)", "Muy frecuente (diaria)"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', now(), null, '["Aplicación"]'::jsonb, 3, 2),

('DIC-A11', 'Cuestionario', 'Adopción', '11', '10', 'Aparto tiempo en mi semana para aprender nuevas funciones de IA o probar nuevas herramientas creativas.', 'Multiple Choice (escala Likert A–E)', '["Nunca", "Rara vez (≤ 1/mes)", "Ocasional (2–3/mes)", "Frecuente (semanal)", "Muy frecuente (diaria)"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', now(), null, '["Productividad", "Aplicación"]'::jsonb, 3, 2),

('DIC-A12', 'Cuestionario', 'Adopción', '11', '10', 'Verifico lineamientos internos de la organización (o del cliente) sobre el uso de IA antes de aplicar resultados en piezas finales.', 'Multiple Choice (escala Likert A–E)', '["Nunca", "Rara vez (≤ 1/mes)", "Ocasional (2–3/mes)", "Frecuente (semanal)", "Muy frecuente (diaria)"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', now(), null, '["Productividad", "Aplicación"]'::jsonb, 3, 2),

('DIC-A13', 'Cuestionario', 'Adopción', '11', '10', 'Integro IA en más de una etapa de mi proceso creativo (por ejemplo, ideación, bocetaje, variantes y pequeños ajustes finales).', 'Multiple Choice (escala Likert A–E)', '["Nunca", "Rara vez (≤ 1/mes)", "Ocasional (2–3/mes)", "Frecuente (semanal)", "Muy frecuente (diaria)"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', now(), null, '["Aplicación"]'::jsonb, 3, 3),

('DIC-A14', 'Cuestionario', 'Adopción', '11', '10', 'Analizo con el equipo cómo la IA impacta tiempos de entrega y calidad percibida por el cliente.', 'Multiple Choice (escala Likert A–E)', '["Nunca", "Rara vez (≤ 1/mes)", "Ocasional (2–3/mes)", "Frecuente (semanal)", "Muy frecuente (diaria)"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', now(), null, '["Productividad", "Aplicación"]'::jsonb, 3, 3),

('DIC-A15', 'Cuestionario', 'Adopción', '11', '10', 'Ajusto prompts y parámetros avanzados (por ejemplo, estilo, proporciones, nivel de detalle) para resolver problemas específicos del proyecto.', 'Multiple Choice (escala Likert A–E)', '["Nunca", "Rara vez (≤ 1/mes)", "Ocasional (2–3/mes)", "Frecuente (semanal)", "Muy frecuente (diaria)"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', now(), null, '["Aplicación"]'::jsonb, 3, 3),

('DIC-A16', 'Cuestionario', 'Adopción', '11', '10', 'Trabajo junto con otros roles (copy, marketing, UX research) para definir cómo y cuándo usar IA en una campaña.', 'Multiple Choice (escala Likert A–E)', '["Nunca", "Rara vez (≤ 1/mes)", "Ocasional (2–3/mes)", "Frecuente (semanal)", "Muy frecuente (diaria)"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', now(), null, '["Aplicación"]'::jsonb, 3, 3),

('DIC-A17', 'Cuestionario', 'Adopción', '11', '10', 'Propongo incluir tiempo específico en los proyectos para experimentar con IA y documentar aprendizajes.', 'Multiple Choice (escala Likert A–E)', '["Nunca", "Rara vez (≤ 1/mes)", "Ocasional (2–3/mes)", "Frecuente (semanal)", "Muy frecuente (diaria)"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', now(), null, '["Productividad"]'::jsonb, 3, 3),

('DIC-A18', 'Cuestionario', 'Adopción', '11', '10', 'Identifico y señalo resultados de IA que puedan ser problemáticos éticamente (por ejemplo, estereotipos, desinformación visual).', 'Multiple Choice (escala Likert A–E)', '["Nunca", "Rara vez (≤ 1/mes)", "Ocasional (2–3/mes)", "Frecuente (semanal)", "Muy frecuente (diaria)"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', now(), null, '["Productividad", "Estrategia", "Aplicación"]'::jsonb, 3, 3),

('DIC-A19', 'Cuestionario', 'Adopción', '11', '10', 'Diseño y documento flujos de trabajo (workflow) donde IA y equipo creativo tienen pasos claros y repetibles.', 'Multiple Choice (escala Likert A–E)', '["Nunca", "Rara vez (≤ 1/mes)", "Ocasional (2–3/mes)", "Frecuente (semanal)", "Muy frecuente (diaria)"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', now(), null, '["Aplicación"]'::jsonb, 3, 4),

('DIC-A20', 'Cuestionario', 'Adopción', '11', '10', 'Utilizo IA para generar sistemáticamente distintas versiones de creatividades y luego reviso métricas con el equipo.', 'Multiple Choice (escala Likert A–E)', '["Nunca", "Rara vez (≤ 1/mes)", "Ocasional (2–3/mes)", "Frecuente (semanal)", "Muy frecuente (diaria)"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', now(), null, '["Productividad", "Aplicación"]'::jsonb, 3, 4),

('DIC-A21', 'Cuestionario', 'Adopción', '11', '10', 'Ajusto parámetros avanzados (por ejemplo, “strength”, “guidance”, variación) para lograr resultados más controlados y reproducibles.', 'Multiple Choice (escala Likert A–E)', '["Nunca", "Rara vez (≤ 1/mes)", "Ocasional (2–3/mes)", "Frecuente (semanal)", "Muy frecuente (diaria)"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', now(), null, '["Productividad"]'::jsonb, 3, 4),

('DIC-A22', 'Cuestionario', 'Adopción', '11', '10', 'Coordino con otros compañeros para integrar IA en procesos compartidos (por ejemplo, diseño + vídeo + social media).', 'Multiple Choice (escala Likert A–E)', '["Nunca", "Rara vez (≤ 1/mes)", "Ocasional (2–3/mes)", "Frecuente (semanal)", "Muy frecuente (diaria)"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', now(), null, '["Aplicación"]'::jsonb, 3, 4),

('DIC-A23', 'Cuestionario', 'Adopción', '11', '10', 'Participo activamente en decidir cómo se reparte el tiempo entre experimentación con IA y producción tradicional en los proyectos.', 'Multiple Choice (escala Likert A–E)', '["Nunca", "Rara vez (≤ 1/mes)", "Ocasional (2–3/mes)", "Frecuente (semanal)", "Muy frecuente (diaria)"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', now(), null, '["Productividad"]'::jsonb, 3, 4),

('DIC-A24', 'Cuestionario', 'Adopción', '11', '10', 'Evalúo sistemáticamente si los resultados de IA pueden generar malentendidos o daño a grupos específicos antes de proponérselos al cliente.', 'Multiple Choice (escala Likert A–E)', '["Nunca", "Rara vez (≤ 1/mes)", "Ocasional (2–3/mes)", "Frecuente (semanal)", "Muy frecuente (diaria)"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', now(), null, '["Productividad"]'::jsonb, 3, 4),

('DIC-A25', 'Cuestionario', 'Adopción', '11', '10', 'Lidero (formal o informalmente) iniciativas dentro del equipo para mejorar los flujos de trabajo creativos usando IA.', 'Multiple Choice (escala Likert A–E)', '["Nunca", "Rara vez (≤ 1/mes)", "Ocasional (2–3/mes)", "Frecuente (semanal)", "Muy frecuente (diaria)"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', now(), null, '["Estrategia", "Aplicación"]'::jsonb, 3, 5),

('DIC-A26', 'Cuestionario', 'Adopción', '11', '10', 'Integro datos de rendimiento (por ejemplo, analítica de campañas, métricas de UX) con resultados de IA para orientar decisiones de diseño.', 'Multiple Choice (escala Likert A–E)', '["Nunca", "Rara vez (≤ 1/mes)", "Ocasional (2–3/mes)", "Frecuente (semanal)", "Muy frecuente (diaria)"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', now(), null, '["Productividad", "Aplicación"]'::jsonb, 3, 5),

('DIC-A27', 'Cuestionario', 'Adopción', '11', '10', 'Creo y mantengo sistemas de prompts, estilos y plantillas de IA que otros miembros del equipo pueden reutilizar.', 'Multiple Choice (escala Likert A–E)', '["Nunca", "Rara vez (≤ 1/mes)", "Ocasional (2–3/mes)", "Frecuente (semanal)", "Muy frecuente (diaria)"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', now(), null, '["Aplicación"]'::jsonb, 3, 5),

('DIC-A28', 'Cuestionario', 'Adopción', '11', '10', 'Facilito sesiones con otros roles (marketing, producto, ventas) para explorar cómo la IA puede apoyar mejor los objetivos de negocio.', 'Multiple Choice (escala Likert A–E)', '["Nunca", "Rara vez (≤ 1/mes)", "Ocasional (2–3/mes)", "Frecuente (semanal)", "Muy frecuente (diaria)"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', now(), null, '["Aplicación"]'::jsonb, 3, 5),

('DIC-A29', 'Cuestionario', 'Adopción', '11', '10', 'Participo en decisiones sobre qué herramientas de IA vale la pena adquirir o mantener, aportando argumentos de costo–beneficio.', 'Multiple Choice (escala Likert A–E)', '["Nunca", "Rara vez (≤ 1/mes)", "Ocasional (2–3/mes)", "Frecuente (semanal)", "Muy frecuente (diaria)"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', now(), null, '["Inversión", "Aplicación"]'::jsonb, 3, 5),

('DIC-A30', 'Cuestionario', 'Adopción', '11', '10', 'Promuevo activamente prácticas éticas en el uso de IA (por ejemplo, lineamientos internos, documentación de casos, discusiones con el equipo).', 'Multiple Choice (escala Likert A–E)', '["Nunca", "Rara vez (≤ 1/mes)", "Ocasional (2–3/mes)", "Frecuente (semanal)", "Muy frecuente (diaria)"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', now(), null, '["Estrategia", "Aplicación"]'::jsonb, 3, 5);

-- CONOCIMIENTO - Rol 10
INSERT INTO "public"."preguntas" ("codigo", "section", "bloque", "area_id", "exclusivo_rol_id", "texto", "tipo", "opciones", "locale", "peso", "escala", "scoring", "created_at", "respuesta_correcta", "dimension", "exclusivo_nivel_id", "dificultad") VALUES
('DIC-C1', 'Cuestionario', 'Conocimiento', '11', '10', '¿Cuál de las siguientes opciones describe mejor una herramienta de IA generativa para imágenes en el contexto de diseño?', 'Multiple Choice (una respuesta)', '["Un programa que solo sirve para almacenar archivos de imagen.", "Un sistema que genera o modifica imágenes a partir de texto o imágenes de entrada.", "Una red social para compartir portafolios.", "Un plugin que únicamente convierte imágenes a blanco y negro."]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', now(), 'Un sistema que genera o modifica imágenes a partir de texto o imágenes de entrada.', '["Conocimiento"]'::jsonb, 3, 1),

('DIC-C2', 'Cuestionario', 'Conocimiento', '11', '10', '¿Cuál es un riesgo básico al usar imágenes generadas por IA en proyectos para clientes?', 'Multiple Choice (una respuesta)', '["Que el archivo pese muy poco.", "Que todas las imágenes generadas sean automáticamente únicas y libres de derechos.", "Que pueda haber dudas sobre derechos de autor o licencias de uso.", "Que el cliente no pueda abrir archivos JPG."]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', now(), 'Que pueda haber dudas sobre derechos de autor o licencias de uso.', '["Estrategia", "Conocimiento"]'::jsonb, 3, 1),

('DIC-C3', 'Cuestionario', 'Conocimiento', '11', '10', '¿Cuál de estas acciones es un ejemplo de usar IA para mejorar la productividad en diseño?', 'Multiple Choice (una respuesta)', '["Hacer todos los recortes de fondo manualmente con la pluma.", "Usar una herramienta de IA para remover fondos automáticamente y luego retocar los detalles.", "Dibujar cada icono desde cero, sin reutilizar nada.", "Guardar archivos en carpetas con nombres desordenados."]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', now(), 'Usar una herramienta de IA para remover fondos automáticamente y luego retocar los detalles.', '["Productividad", "Conocimiento"]'::jsonb, 3, 1),

('DIC-C4', 'Cuestionario', 'Conocimiento', '11', '10', 'Al subir imágenes de un cliente a una plataforma de IA en la nube, ¿qué práctica es más adecuada?', 'Multiple Choice (una respuesta)', '["Subir cualquier imagen sin revisar términos de uso.", "Subir solo imágenes internas, sin logotipos ni datos sensibles.", "Revisar políticas de privacidad y, si es necesario, anonimizar o evitar subir material sensible.", "Compartir libremente las imágenes del cliente en foros públicos para probar la herramienta."]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', now(), 'Revisar políticas de privacidad y, si es necesario, anonimizar o evitar subir material sensible.', '["Conocimiento"]'::jsonb, 3, 1),

('DIC-C5', 'Cuestionario', 'Conocimiento', '11', '10', '¿Qué característica hace más efectivo un “prompt” básico al generar imágenes por IA?', 'Multiple Choice (una respuesta)', '["Ser lo más corto posible, aunque sea vago.", "Incluir estilo, encuadre, ambiente y formato deseado.", "Escribirlo en cualquier idioma mezclado.", "Usar solo emojis."]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', now(), 'Incluir estilo, encuadre, ambiente y formato deseado.', '["Conocimiento"]'::jsonb, 3, 1),

('DIC-C6', 'Cuestionario', 'Conocimiento', '11', '10', 'Para usar una imagen generada por IA en una pieza impresa, ¿qué es más importante revisar?', 'Multiple Choice (una respuesta)', '["Que la imagen tenga muchos colores brillantes.", "Que la resolución y el tamaño sean suficientes para impresión sin perder calidad.", "Que la imagen sea cuadrada.", "Que la imagen esté en formato GIF."]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', now(), 'Que la resolución y el tamaño sean suficientes para impresión sin perder calidad.', '["Conocimiento"]'::jsonb, 3, 1),

('DIC-C7', 'Cuestionario', 'Conocimiento', '11', '10', '¿Para qué es más útil combinar IA generativa con tus bocetos hechos a mano?', 'Multiple Choice (una respuesta)', '["Para dejar de dibujar y que la IA haga todo.", "Para explorar variaciones de tus bocetos y encontrar nuevas composiciones o estilos.", "Solo para convertir los bocetos en blanco y negro.", "Para reducir automáticamente el número de capas."]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', now(), 'Para explorar variaciones de tus bocetos y encontrar nuevas composiciones o estilos.', '["Conocimiento"]'::jsonb, 3, 2),

('DIC-C8', 'Cuestionario', 'Conocimiento', '11', '10', '¿Cuál es un uso típico de IA en flujos de redes sociales para marcas?', 'Multiple Choice (una respuesta)', '["Generar copias de seguridad de todos los archivos.", "Crear decenas de adaptaciones de una misma pieza a diferentes formatos y tamaños.", "Bloquear comentarios negativos.", "Calcular el presupuesto de pauta."]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', now(), 'Crear decenas de adaptaciones de una misma pieza a diferentes formatos y tamaños.', '["Aplicación", "Conocimiento"]'::jsonb, 3, 2),

('DIC-C9', 'Cuestionario', 'Conocimiento', '11', '10', '¿Qué describe mejor el rol del diseñador cuando usa IA en el proceso creativo?', 'Multiple Choice (una respuesta)', '["Ser un operador que acepta cualquier resultado que salga.", "Ser un curador que guía, selecciona y edita resultados para cumplir objetivos de marca.", "Ser un espectador que no interviene.", "Ser solo un revisor ortográfico."]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', now(), 'Ser un curador que guía, selecciona y edita resultados para cumplir objetivos de marca.', '["Conocimiento"]'::jsonb, 3, 2),

('DIC-C10', 'Cuestionario', 'Conocimiento', '11', '10', '¿Cuál es una buena práctica al usar IA para propuestas a clientes?', 'Multiple Choice (una respuesta)', '["No mencionar el uso de IA nunca.", "Explicar cómo la IA ayudó a generar opciones rápidas, pero que habrá una fase de refinamiento manual.", "Entregar únicamente las imágenes crudas de la IA.", "Entregar todas las variantes generadas sin filtro."]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', now(), 'Explicar cómo la IA ayudó a generar opciones rápidas, pero que habrá una fase de refinamiento manual.', '["Conocimiento"]'::jsonb, 3, 2),

('DIC-C11', 'Cuestionario', 'Conocimiento', '11', '10', 'En cuanto a costos, ¿qué ventaja típica ofrece la IA en diseño?', 'Multiple Choice (una respuesta)', '["Siempre sustituye todo el presupuesto de diseño.", "Reduce tiempo en tareas repetitivas, lo que puede disminuir horas de producción o acelerar entregables.", "Solo incrementa costos de software.", "Obliga a contratar más diseñadores."]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', now(), 'Reduce tiempo en tareas repetitivas, lo que puede disminuir horas de producción o acelerar entregables.', '["Inversión", "Conocimiento"]'::jsonb, 3, 2),

('DIC-C12', 'Cuestionario', 'Conocimiento', '11', '10', '¿Cuál es un ejemplo de sesgo en resultados de IA que un diseñador debería detectar?', 'Multiple Choice (una respuesta)', '["Imágenes que siempre usan las mismas fuentes tipográficas.", "Representaciones estereotipadas de género, raza o cultura en personajes generados.", "Que la imagen pese menos de 1 MB.", "Que la imagen sea muy colorida."]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', now(), 'Representaciones estereotipadas de género, raza o cultura en personajes generados.', '["Productividad", "Conocimiento"]'::jsonb, 3, 2),

('DIC-C13', 'Cuestionario', 'Conocimiento', '11', '10', '¿Qué ventaja clave tiene usar IA para generar moodboards a partir de descripciones de marca?', 'Multiple Choice (una respuesta)', '["Eliminar la necesidad de investigar referencias.", "Explorar rápidamente múltiples direcciones visuales para luego curarlas manualmente.", "Mantener un solo estilo visual para todas las marcas.", "Evitar hablar con el cliente."]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', now(), 'Explorar rápidamente múltiples direcciones visuales para luego curarlas manualmente.', '["Conocimiento"]'::jsonb, 3, 3),

('DIC-C14', 'Cuestionario', 'Conocimiento', '11', '10', '¿Cuál es una forma adecuada de usar IA para prototipos de interfaces (UI)?', 'Multiple Choice (una respuesta)', '["Dejar que la IA defina la arquitectura de información sin revisión.", "Generar primeras versiones de pantallas y luego ajustarlas en Figma u otra herramienta.", "Usar solo plantillas genéricas sin adaptación.", "Pedir a la IA que escriba el código sin mostrar pantallas."]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', now(), 'Generar primeras versiones de pantallas y luego ajustarlas en Figma u otra herramienta.', '["Conocimiento"]'::jsonb, 3, 3),

('DIC-C15', 'Cuestionario', 'Conocimiento', '11', '10', 'Cuando un modelo de IA genera imágenes muy “parecidas” entre sí, ¿qué ajuste puede ayudar a aumentar la diversidad creativa?', 'Multiple Choice (una respuesta)', '["Usar siempre el mismo prompt.", "Cambiar parámetros de variación o aleatoriedad y variar estilos o referencias culturales.", "Disminuir la resolución.", "Exportar solo en formato PNG."]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', now(), 'Cambiar parámetros de variación o aleatoriedad y variar estilos o referencias culturales.', '["Conocimiento"]'::jsonb, 3, 3),

('DIC-C16', 'Cuestionario', 'Conocimiento', '11', '10', '¿Qué representa mejor una buena integración IA + diseñador en una campaña digital?', 'Multiple Choice (una respuesta)', '["La IA genera todas las piezas y se publican sin revisión.", "El diseñador define el concepto, la IA propone variaciones y el diseñador selecciona y ajusta las piezas finales.", "El cliente selecciona directamente resultados crudos de la IA.", "Solo se usan plantillas pre-hechas sin ajustes."]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', now(), 'El diseñador define el concepto, la IA propone variaciones y el diseñador selecciona y ajusta las piezas finales.', '["Conocimiento"]'::jsonb, 3, 3),

('DIC-C17', 'Cuestionario', 'Conocimiento', '11', '10', 'A nivel de inversión, ¿qué debe considerar un diseñador al proponer el uso de IA al cliente?', 'Multiple Choice (una respuesta)', '["Solo el costo de la herramienta de IA.", "El tiempo de aprendizaje, ajustes, revisión manual y posibles límites de uso comercial.", "Que la IA siempre reduce el tiempo total a la mitad.", "Que ya no se necesita fase de pruebas."]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', now(), 'El tiempo de aprendizaje, ajustes, revisión manual y posibles límites de uso comercial.', '["Inversión", "Aplicación", "Conocimiento"]'::jsonb, 3, 3),

('DIC-C18', 'Cuestionario', 'Conocimiento', '11', '10', '¿Qué acción reduce el riesgo de usar imágenes de IA con contenido sensible?', 'Multiple Choice (una respuesta)', '["No leer políticas de contenido.", "Evitar prompts que involucren minorías o temas delicados y aplicar revisión crítica humana.", "Usar únicamente prompts muy genéricos.", "Subir siempre fotos reales de personas sin permiso."]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', now(), 'Evitar prompts que involucren minorías o temas delicados y aplicar revisión crítica humana.', '["Estrategia", "Conocimiento"]'::jsonb, 3, 3),

('DIC-C19', 'Cuestionario', 'Conocimiento', '11', '10', '¿Qué es un “workflow” de diseño asistido por IA?', 'Multiple Choice (una respuesta)', '["Un único prompt que se usa para todo.", "Una secuencia definida de pasos donde IA y diseñador se alternan para lograr un resultado.", "Un archivo donde se guardan todas las imágenes generadas.", "Un documento legal asociado al proyecto."]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', now(), 'Una secuencia definida de pasos donde IA y diseñador se alternan para lograr un resultado.', '["Conocimiento"]'::jsonb, 3, 4),

('DIC-C20', 'Cuestionario', 'Conocimiento', '11', '10', '¿Cómo puede la IA apoyar en pruebas A/B de creatividades para campañas digitales?', 'Multiple Choice (una respuesta)', '["Generando múltiples variantes visuales para probar rendimientos diferentes.", "Reemplazando al equipo de medios por completo.", "Eliminando la necesidad de métricas.", "Bloqueando usuarios que no hacen clic."]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', now(), 'Generando múltiples variantes visuales para probar rendimientos diferentes.', '["Conocimiento"]'::jsonb, 3, 4),

('DIC-C21', 'Cuestionario', 'Conocimiento', '11', '10', '¿Qué factor es clave para mantener coherencia de marca al usar IA en diferentes piezas?', 'Multiple Choice (una respuesta)', '["Cambiar de estilo en cada prompt.", "Definir y reutilizar guías de estilo, descriptores de marca y restricciones visuales en los prompts.", "Permitir a la IA elegir los colores de forma libre.", "Usar siempre plantillas genéricas sin referencia a la marca."]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', now(), 'Definir y reutilizar guías de estilo, descriptores de marca y restricciones visuales en los prompts.', '["Conocimiento"]'::jsonb, 3, 4),

('DIC-C22', 'Cuestionario', 'Conocimiento', '11', '10', '¿Qué aspecto de inversión debe considerarse al escalar el uso de IA en todo un equipo creativo?', 'Multiple Choice (una respuesta)', '["Solo el costo de licencias de las herramientas.", "Licencias, capacitación, tiempo de experimentación y definición de lineamientos de uso.", "Únicamente el costo de hardware.", "Eliminar todas las otras herramientas de diseño tradicionales."]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', now(), 'Licencias, capacitación, tiempo de experimentación y definición de lineamientos de uso.', '["Inversión", "Aplicación", "Conocimiento"]'::jsonb, 3, 4),

('DIC-C23', 'Cuestionario', 'Conocimiento', '11', '10', 'En términos éticos, ¿qué práctica es adecuada para imágenes de personas generadas por IA en campañas?', 'Multiple Choice (una respuesta)', '["Usarlas sin aclarar que son generadas por IA, sin importar el contexto.", "Revisar contexto, evitar usos engañosos y respetar regulaciones o guías internas.", "No usarlas nunca en ningún caso.", "Mezclar rostros de personas reales sin permiso para obtener nuevas caras."]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', now(), 'Revisar contexto, evitar usos engañosos y respetar regulaciones o guías internas.', '["Conocimiento"]'::jsonb, 3, 4),

('DIC-C24', 'Cuestionario', 'Conocimiento', '11', '10', '¿Cuál es una limitación frecuente de los modelos de IA para diseño que un co-creador avanzado debe anticipar?', 'Multiple Choice (una respuesta)', '["Que siempre generen exactamente lo que el cliente pidió a la primera.", "Errores en detalles finos (tipografía, manos, interfaces) que requieren retoque manual.", "Imposibilidad total de cambiar estilos visuales.", "Que solo funcionen en blanco y negro."]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', now(), 'Errores en detalles finos (tipografía, manos, interfaces) que requieren retoque manual.', '["Conocimiento"]'::jsonb, 3, 4),

('DIC-C25', 'Cuestionario', 'Conocimiento', '11', '10', '¿Qué papel juega la documentación de prompts y workflows en un equipo creativo maduro en IA?', 'Multiple Choice (una respuesta)', '["No es necesaria, cada quien improvisa.", "Permite replicar resultados, compartir buenas prácticas y acelerar el trabajo del equipo.", "Solo sirve para fines legales.", "Solo es útil para programadores y desarrolladores."]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', now(), 'Permite replicar resultados, compartir buenas prácticas y acelerar el trabajo del equipo.', '["Aplicación", "Conocimiento"]'::jsonb, 3, 5),

('DIC-C26', 'Cuestionario', 'Conocimiento', '11', '10', '¿Cómo puede la IA apoyar decisiones estratégicas de diseño más allá de generar imágenes?', 'Multiple Choice (una respuesta)', '["Reemplazando al cliente en la toma de decisiones.", "Analizando feedback de usuarios o rendimiento de piezas para inspirar nuevas direcciones creativas.", "Eliminando la fase de pruebas con usuarios.", "Decidiendo de forma automática el presupuesto de marketing."]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', now(), 'Analizando feedback de usuarios o rendimiento de piezas para inspirar nuevas direcciones creativas.', '["Conocimiento"]'::jsonb, 3, 5),

('DIC-C27', 'Cuestionario', 'Conocimiento', '11', '10', 'En términos de inversión, ¿qué puede justificar el costo adicional de herramientas avanzadas de IA para diseño?', 'Multiple Choice (una respuesta)', '["Que estén de moda en la industria.", "Ahorro de tiempo significativo, aumento de calidad y posibilidad de nuevos servicios creativos.", "Que tengan interfaces complejas y técnicas.", "Que generen archivos muy pesados por defecto."]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', now(), 'Ahorro de tiempo significativo, aumento de calidad y posibilidad de nuevos servicios creativos.', '["Inversión", "Aplicación", "Conocimiento"]'::jsonb, 3, 5),

('DIC-C28', 'Cuestionario', 'Conocimiento', '11', '10', '¿Qué enfoque es más responsable al usar IA para crear conceptos visuales sensibles (por ejemplo, temas sociales)?', 'Multiple Choice (una respuesta)', '["Dejar que la IA decida todo el enfoque visual sin intervención humana.", "Diseñar prompts, revisar los resultados con mirada crítica, incluir voces diversas y, si es necesario, evitar IA en ese tema.", "Usar plantillas genéricas sin pensar en el contexto.", "Ignorar posibles interpretaciones culturales o sociales de las imágenes."]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', now(), 'Diseñar prompts, revisar los resultados con mirada crítica, incluir voces diversas y, si es necesario, evitar IA en ese tema.', '["Conocimiento"]'::jsonb, 3, 5),

('DIC-C29', 'Cuestionario', 'Conocimiento', '11', '10', '¿Qué rol puede tener un diseñador ampliado por IA en su equipo, aun sin ser gerente formal?', 'Multiple Choice (una respuesta)', '["Guardar sus conocimientos para mantener ventaja personal.", "Actuar como referente interno, compartir buenas prácticas y proponer mejoras a los flujos de trabajo.", "Usar IA solo en proyectos personales fuera de la organización.", "Evitar involucrarse en cambios de procesos relacionados con IA."]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', now(), 'Actuar como referente interno, compartir buenas prácticas y proponer mejoras a los flujos de trabajo.', '["Aplicación", "Conocimiento"]'::jsonb, 3, 5),

('DIC-C30', 'Cuestionario', 'Conocimiento', '11', '10', '¿Qué describe mejor una visión sostenible del uso de IA en industrias creativas?', 'Multiple Choice (una respuesta)', '["Sustituir el criterio humano por completo.", "Usar IA como amplificador de creatividad, respetando ética, calidad y valor del trabajo humano.", "Generar la mayor cantidad posible de piezas sin evaluar impacto.", "Usar IA solo por obligación, sin reflexionar sobre su impacto."]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', now(), 'Usar IA como amplificador de creatividad, respetando ética, calidad y valor del trabajo humano.', '["Aplicación", "Conocimiento"]'::jsonb, 3, 5);
