-- AGREGAR PREGUNTAS PARA ROLES 21-26
-- Este script agrega preguntas para los roles operativos y especializados
-- La última pregunta existente es la 292, por lo que comenzamos desde 293

-- ==============================================
-- ROLES QUE NECESITAN PREGUNTAS ESPECÍFICAS
-- ==============================================
--
-- ID 21: Miembros de RRHH (area_id: 6) → exclusivo_rol_id = 21 → preguntas 293-304
-- ID 22: Miembros de Contabilidad (area_id: 7) → exclusivo_rol_id = 22 → preguntas 305-316
-- ID 23: Miembros de Compras (area_id: 8) → exclusivo_rol_id = 23 → preguntas 317-328
-- ID 24: Gerencia Media (area_id: 1) → exclusivo_rol_id = 24 → preguntas 329-340
-- ID 25: Freelancer (area_id: 1) → exclusivo_rol_id = 25 → preguntas 341-352
-- ID 26: Consultor (area_id: 1) → exclusivo_rol_id = 26 → preguntas 353-364

-- ==============================================
-- 1. Miembros de RRHH (ID 21) → exclusivo_rol_id = 21
-- ==============================================

INSERT INTO "public"."preguntas" ("id", "codigo", "section", "bloque", "area_id", "exclusivo_rol_id", "texto", "tipo", "opciones", "locale", "peso", "escala", "scoring", "created_at", "respuesta_correcta") VALUES 
('293', 'A1', 'Cuestionario', 'Adopción', '6', '21', '¿Con qué frecuencia usa Gen-AI para screening inicial de CVs y aplicaciones?', 'Multiple Choice (escala Likert A–E)', '["A) Nunca", "B) Rara vez (≤ 1/mes)", "C) Ocasional (2–3/mes)", "D) Frecuente (semanal)", "E) Muy frecuente (diaria)"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '2025-01-15 10:00:00+00', null),
('294', 'A2', 'Cuestionario', 'Adopción', '6', '21', '¿Con qué frecuencia emplea Gen-AI para redacción de job descriptions y comunicaciones?', 'Multiple Choice (escala Likert A–E)', '["A) Nunca", "B) Rara vez (≤ 1/mes)", "C) Ocasional (2–3/mes)", "D) Frecuente (semanal)", "E) Muy frecuente (diaria)"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '2025-01-15 10:00:00+00', null),
('295', 'A3', 'Cuestionario', 'Adopción', '6', '21', '¿Con qué frecuencia utiliza Gen-AI para coordinación de entrevistas y seguimiento de candidatos?', 'Multiple Choice (escala Likert A–E)', '["A) Nunca", "B) Rara vez (≤ 1/mes)", "C) Ocasional (2–3/mes)", "D) Frecuente (semanal)", "E) Muy frecuente (diaria)"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '2025-01-15 10:00:00+00', null),
('296', 'A4', 'Cuestionario', 'Adopción', '6', '21', '¿Con qué frecuencia integra Gen-AI en onboarding y documentación de empleados?', 'Multiple Choice (escala Likert A–E)', '["A) Nunca", "B) Rara vez (≤ 1/mes)", "C) Ocasional (2–3/mes)", "D) Frecuente (semanal)", "E) Muy frecuente (diaria)"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '2025-01-15 10:00:00+00', null),
('297', 'A5', 'Cuestionario', 'Adopción', '6', '21', '¿Con qué frecuencia aplica Gen-AI para análisis de datos de empleados y reportes?', 'Multiple Choice (escala Likert A–E)', '["A) Nunca", "B) Rara vez (≤ 1/mes)", "C) Ocasional (2–3/mes)", "D) Frecuente (semanal)", "E) Muy frecuente (diaria)"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '2025-01-15 10:00:00+00', null),
('298', 'A6', 'Cuestionario', 'Adopción', '6', '21', '¿Con qué frecuencia usa Gen-AI para gestión de consultas y soporte a empleados?', 'Multiple Choice (escala Likert A–E)', '["A) Nunca", "B) Rara vez (≤ 1/mes)", "C) Ocasional (2–3/mes)", "D) Frecuente (semanal)", "E) Muy frecuente (diaria)"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '2025-01-15 10:00:00+00', null),
('299', 'C1', 'Cuestionario', 'Conocimiento', '6', '21', '¿Cuál es la mejor práctica para usar Gen-AI en screening de CVs?', 'Multiple Choice (una respuesta)', '["A) Automatizar sin revisión", "B) Usar como filtro inicial, validar con criterios humanos y evitar sesgos", "C) Reemplazar revisión humana", "D) Solo para búsqueda de keywords"]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', '2025-01-15 10:00:00+00', 'B) Usar como filtro inicial, validar con criterios humanos y evitar sesgos'),
('300', 'C2', 'Cuestionario', 'Conocimiento', '6', '21', '¿Qué aspecto es más importante en comunicación con candidatos usando Gen-AI?', 'Multiple Choice (una respuesta)', '["A) Velocidad de respuesta', 'B) Personalización, tono apropiado y información precisa", "C) Automatización total", "D) Mensajes genéricos"]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', '2025-01-15 10:00:00+00', 'B) Personalización, tono apropiado y información precisa'),
('301', 'C3', 'Cuestionario', 'Conocimiento', '6', '21', '¿Cómo se debe manejar el onboarding con Gen-AI?', 'Multiple Choice (una respuesta)', '["A) Solo documentación automática", "B) Combinar automatización con toque humano, personalizar experiencia y seguimiento", "C) Sin interacción humana", "D) Solo envío de documentos"]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', '2025-01-15 10:00:00+00', 'B) Combinar automatización con toque humano, personalizar experiencia y seguimiento'),
('302', 'C4', 'Cuestionario', 'Conocimiento', '6', '21', '¿Qué es esencial para el análisis de datos con Gen-AI?', 'Multiple Choice (una respuesta)', '["A) Solo números", "B) Confidencialidad, contexto organizacional y acción sobre insights", "C) Sin validación", "D) Solo automatización"]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', '2025-01-15 10:00:00+00', 'B) Confidencialidad, contexto organizacional y acción sobre insights'),
('303', 'C5', 'Cuestionario', 'Conocimiento', '6', '21', '¿Cómo se debe integrar Gen-AI en tareas diarias de RRHH?', 'Multiple Choice (una respuesta)', '["A) Reemplazar interacción humana", "B) Liberar tiempo para tareas estratégicas, mantener empatía y agregar valor", "C) Solo para tareas administrativas", "D) Sin capacitación"]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', '2025-01-15 10:00:00+00', 'B) Liberar tiempo para tareas estratégicas, mantener empatía y agregar valor'),
('304', 'C6', 'Cuestionario', 'Conocimiento', '6', '21', '¿Qué métrica es más relevante para medir el impacto de Gen-AI en RRHH operativo?', 'Multiple Choice (una respuesta)', '["A) Número de herramientas", "B) Reducción de tiempo de proceso, mejora en experiencia de candidatos y calidad de contratación", "C) Número de CVs procesados", "D) Costo de herramientas"]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', '2025-01-15 10:00:00+00', 'B) Reducción de tiempo de proceso, mejora en experiencia de candidatos y calidad de contratación');

-- ==============================================
-- 2. Miembros de Contabilidad (ID 22) → exclusivo_rol_id = 22
-- ==============================================

INSERT INTO "public"."preguntas" ("id", "codigo", "section", "bloque", "area_id", "exclusivo_rol_id", "texto", "tipo", "opciones", "locale", "peso", "escala", "scoring", "created_at", "respuesta_correcta") VALUES 
('305', 'A1', 'Cuestionario', 'Adopción', '7', '22', '¿Con qué frecuencia usa Gen-AI para registro y clasificación de transacciones?', 'Multiple Choice (escala Likert A–E)', '["A) Nunca", "B) Rara vez (≤ 1/mes)", "C) Ocasional (2–3/mes)", "D) Frecuente (semanal)", "E) Muy frecuente (diaria)"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '2025-01-15 10:00:00+00', null),
('306', 'A2', 'Cuestionario', 'Adopción', '7', '22', '¿Con qué frecuencia emplea Gen-AI para conciliaciones bancarias y validaciones?', 'Multiple Choice (escala Likert A–E)', '["A) Nunca", "B) Rara vez (≤ 1/mes)", "C) Ocasional (2–3/mes)", "D) Frecuente (semanal)", "E) Muy frecuente (diaria)"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '2025-01-15 10:00:00+00', null),
('307', 'A3', 'Cuestionario', 'Adopción', '7', '22', '¿Con qué frecuencia utiliza Gen-AI para generación de reportes contables?', 'Multiple Choice (escala Likert A–E)', '["A) Nunca", "B) Rara vez (≤ 1/mes)", "C) Ocasional (2–3/mes)", "D) Frecuente (semanal)", "E) Muy frecuente (diaria)"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '2025-01-15 10:00:00+00', null),
('308', 'A4', 'Cuestionario', 'Adopción', '7', '22', '¿Con qué frecuencia integra Gen-AI en detección de errores y anomalías?', 'Multiple Choice (escala Likert A–E)', '["A) Nunca", "B) Rara vez (≤ 1/mes)", "C) Ocasional (2–3/mes)", "D) Frecuente (semanal)", "E) Muy frecuente (diaria)"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '2025-01-15 10:00:00+00', null),
('309', 'A5', 'Cuestionario', 'Adopción', '7', '22', '¿Con qué frecuencia aplica Gen-AI para gestión de cuentas por pagar y cobrar?', 'Multiple Choice (escala Likert A–E)', '["A) Nunca", "B) Rara vez (≤ 1/mes)", "C) Ocasional (2–3/mes)", "D) Frecuente (semanal)", "E) Muy frecuente (diaria)"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '2025-01-15 10:00:00+00', null),
('310', 'A6', 'Cuestionario', 'Adopción', '7', '22', '¿Con qué frecuencia usa Gen-AI para preparación de documentación fiscal?', 'Multiple Choice (escala Likert A–E)', '["A) Nunca", "B) Rara vez (≤ 1/mes)", "C) Ocasional (2–3/mes)", "D) Frecuente (semanal)", "E) Muy frecuente (diaria)"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '2025-01-15 10:00:00+00', null),
('311', 'C1', 'Cuestionario', 'Conocimiento', '7', '22', '¿Cuál es la mejor práctica para usar Gen-AI en registro contable?', 'Multiple Choice (una respuesta)', '["A) Confiar sin revisar", "B) Validar cada entrada, mantener trazabilidad y documentar excepciones", "C) Automatizar todo", "D) Sin controles"]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', '2025-01-15 10:00:00+00', 'B) Validar cada entrada, mantener trazabilidad y documentar excepciones'),
('312', 'C2', 'Cuestionario', 'Conocimiento', '7', '22', '¿Qué aspecto es más importante en conciliaciones con Gen-AI?', 'Multiple Choice (una respuesta)', '["A) Velocidad", "B) Exactitud, identificación de discrepancias y resolución oportuna", "C) Automatización completa", "D) Sin revisión"]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', '2025-01-15 10:00:00+00', 'B) Exactitud, identificación de discrepancias y resolución oportuna'),
('313', 'C3', 'Cuestionario', 'Conocimiento', '7', '22', '¿Cómo se debe manejar la detección de errores con Gen-AI?', 'Multiple Choice (una respuesta)', '["A) Corregir automáticamente", "B) Investigar causa raíz, validar con supervisor y documentar correcciones", "C) Ignorar alertas menores", "D) Sin seguimiento"]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', '2025-01-15 10:00:00+00', 'B) Investigar causa raíz, validar con supervisor y documentar correcciones'),
('314', 'C4', 'Cuestionario', 'Conocimiento', '7', '22', '¿Qué es esencial para reportes contables con Gen-AI?', 'Multiple Choice (una respuesta)', '["A) Solo rapidez", "B) Accuracy, cumplimiento de normas contables y revisión de cifras clave", "C) Sin validación", "D) Solo automatización"]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', '2025-01-15 10:00:00+00', 'B) Accuracy, cumplimiento de normas contables y revisión de cifras clave'),
('315', 'C5', 'Cuestionario', 'Conocimiento', '7', '22', '¿Cómo se debe integrar Gen-AI en el trabajo contable diario?', 'Multiple Choice (una respuesta)', '["A) Reemplazar conocimiento contable", "B) Automatizar tareas repetitivas, mantener criterio profesional y agregar valor analítico", "C) Solo para data entry", "D) Sin supervisión"]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', '2025-01-15 10:00:00+00', 'B) Automatizar tareas repetitivas, mantener criterio profesional y agregar valor analítico'),
('316', 'C6', 'Cuestionario', 'Conocimiento', '7', '22', '¿Qué métrica es más relevante para medir el impacto de Gen-AI en contabilidad operativa?', 'Multiple Choice (una respuesta)', '["A) Número de herramientas", "B) Reducción de errores, tiempo de proceso y mejora en accuracy de reportes", "C) Número de transacciones", "D) Velocidad de entrada"]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', '2025-01-15 10:00:00+00', 'B) Reducción de errores, tiempo de proceso y mejora en accuracy de reportes');

-- ==============================================
-- CONTINÚA EN SIGUIENTE ARCHIVO...
-- Roles restantes: 23, 24, 25, 26
-- ==============================================

