-- CORRECCIÓN COMPLETA DEL SISTEMA DE PERFILES Y PREGUNTAS
-- Este archivo corrige todos los problemas: perfiles faltantes, preguntas diferenciadas por nivel jerárquico

-- ==============================================
-- 1. AGREGAR PERFILES FALTANTES A LA TABLA ROLES
-- ==============================================

-- Perfiles de Dirección faltantes
INSERT INTO "public"."roles" ("id", "slug", "nombre", "area_id") VALUES 
('11', 'direccion-ventas', 'Dirección de Ventas', '2'),
('12', 'direccion-operaciones', 'Dirección de Operaciones', '5'),
('13', 'direccion-finanzas', 'Dirección de Finanzas (CFO)', '5'),
('14', 'direccion-rrhh', 'Dirección de RRHH', '6'),
('15', 'direccion-contabilidad', 'Dirección/Jefatura de Contabilidad', '7'),
('16', 'direccion-compras', 'Dirección de Compras / Supply', '8');

-- Perfiles de Miembros faltantes
INSERT INTO "public"."roles" ("id", "slug", "nombre", "area_id") VALUES 
('17', 'miembros-ventas', 'Miembros de Ventas', '2'),
('18', 'miembros-marketing', 'Miembros de Marketing', '3'),
('19', 'miembros-operaciones', 'Miembros de Operaciones', '5'),
('20', 'miembros-finanzas', 'Miembros de Finanzas', '5'),
('21', 'miembros-rrhh', 'Miembros de RRHH', '6'),
('22', 'miembros-contabilidad', 'Miembros de Contabilidad', '7'),
('23', 'miembros-compras', 'Miembros de Compras', '8');

-- Roles especializados faltantes
INSERT INTO "public"."roles" ("id", "slug", "nombre", "area_id") VALUES 
('24', 'gerencia-media', 'Gerencia Media', '1'),
('25', 'freelancer', 'Freelancer', '1'),
('26', 'consultor', 'Consultor', '1');

-- ==============================================
-- 2. LIMPIAR PREGUNTAS EXISTENTES (OPCIONAL)
-- ==============================================
-- Descomenta la siguiente línea si quieres limpiar todas las preguntas existentes
-- 

-- ==============================================
-- 3. PREGUNTAS PARA CEO (exclusivo_rol_id = 1)
-- ==============================================
INSERT INTO "public"."preguntas" ("id", "codigo", "section", "bloque", "area_id", "exclusivo_rol_id", "texto", "tipo", "opciones", "locale", "peso", "escala", "scoring", "created_at", "respuesta_correcta") VALUES 
-- CEO - Adopción (A1-A6)
('1001', 'A1', 'Cuestionario', 'Adopción', '1', '1', '¿Con qué frecuencia impulsa iniciativas de Gen-AI con presupuesto y OKRs explícitos (p. ej., automatización de back-office, copilots comerciales, analytics aumentada)?', 'Multiple Choice (escala Likert A–E)', '["A) Nunca", "B) Rara vez (≤ 1/mes)", "C) Ocasional (2–3/mes)", "D) Frecuente (semanal)", "E) Muy frecuente (diaria)"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '2025-01-15 10:00:00.000000+00', null),
('1002', 'A2', 'Cuestionario', 'Adopción', '1', '1', '¿Con qué frecuencia revisa y decide sobre el portafolio de casos de uso de Gen-AI (priorización por valor/viabilidad, stage-gate)?', 'Multiple Choice (escala Likert A–E)', '["A) Nunca", "B) Rara vez (≤ 1/mes)", "C) Ocasional (2–3/mes)", "D) Frecuente (semanal)", "E) Muy frecuente (diaria)"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '2025-01-15 10:00:00.000000+00', null),
('1003', 'A3', 'Cuestionario', 'Adopción', '1', '1', '¿Con qué frecuencia consulta métricas de valor (ahorros, ingresos, time-to-market, NPS interno) con línea base y responsables?', 'Multiple Choice (escala Likert A–E)', '["A) Nunca", "B) Rara vez (≤ 1/mes)", "C) Ocasional (2–3/mes)", "D) Frecuente (semanal)", "E) Muy frecuente (diaria)"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '2025-01-15 10:00:00.000000+00', null),
('1004', 'A4', 'Cuestionario', 'Adopción', '1', '1', '¿Con qué frecuencia participa en la gobernanza: políticas de uso, guardrails, comité de IA, evaluación de alto riesgo (salud, financiero, contratación, servicios públicos)?', 'Multiple Choice (escala Likert A–E)', '["A) Nunca", "B) Rara vez (≤ 1/mes)", "C) Ocasional (2–3/mes)", "D) Frecuente (semanal)", "E) Muy frecuente (diaria)"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '2025-01-15 10:00:00.000000+00', null),
('1005', 'A5', 'Cuestionario', 'Adopción', '1', '1', '¿Con qué frecuencia aprueba o supervisa controles de datos y cumplimiento locales (p. ej., INAI/AAIP/SIC) y transferencias transfronterizas?', 'Multiple Choice (escala Likert A–E)', '["A) Nunca", "B) Rara vez (≤ 1/mes)", "C) Ocasional (2–3/mes)", "D) Frecuente (semanal)", "E) Muy frecuente (diaria)"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '2025-01-15 10:00:00.000000+00', null),
('1006', 'A6', 'Cuestionario', 'Adopción', '1', '1', '¿Con qué frecuencia financia/monitorea programas de upskilling (prompt-engineering, seguridad, ética) para liderazgo y áreas de negocio?', 'Multiple Choice (escala Likert A–E)', '["A) Nunca", "B) Rara vez (≤ 1/mes)", "C) Ocasional (2–3/mes)", "D) Frecuente (semanal)", "E) Muy frecuente (diaria)"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '2025-01-15 10:00:00.000000+00', null),

-- CEO - Conocimiento (C1-C6)
('1007', 'C1', 'Cuestionario', 'Conocimiento', '1', '1', '¿Cuál es un KPI estratégico adecuado para Gen-AI a nivel CEO?', 'Multiple Choice (una respuesta)', '["A) Número de prompts enviados", "B) Valor capturado contra línea base (ahorro/ingreso/tiempo)", "C) Likes en redes", "D) Cantidad de proveedores"]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', '2025-01-15 10:00:00.000000+00', 'B) Valor capturado contra línea base (ahorro/ingreso/tiempo)'),
('1008', 'C2', 'Cuestionario', 'Conocimiento', '1', '1', '¿Qué práctica valida mejor el ROI en LATAM con presupuestos acotados?', 'Multiple Choice (una respuesta)', '["A) Comprar primero licencias masivas", "B) Pilotos con control A/B y línea base operacional", "C) Esperar a que la competencia publique su ROI", "D) Usar solo encuestas de percepción"]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', '2025-01-15 10:00:00.000000+00', 'B) Pilotos con control A/B y línea base operacional'),
('1009', 'C3', 'Cuestionario', 'Conocimiento', '1', '1', 'Para casos de alto riesgo (crédito, salud, empleo), ¿qué es indispensable?', 'Multiple Choice (una respuesta)', '["A) Delegar todo a IA", "B) Supervisión humana, documentación del caso y evaluación de impacto/explicabilidad", "C) Ocultar el uso de IA", "D) Solo NDAs con proveedores"]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', '2025-01-15 10:00:00.000000+00', 'B) Supervisión humana, documentación del caso y evaluación de impacto/explicabilidad'),
('1010', 'C4', 'Cuestionario', 'Conocimiento', '1', '1', 'En México y región, ¿qué principio debe regir el uso de datos en Gen-AI?', 'Multiple Choice (una respuesta)', '["A) Subir PII a cualquier servicio", "B) Minimización, bases legales claras y salvaguardas en transferencias", "C) Recolección indiscriminada", "D) Reutilizar expedientes sin informar"]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', '2025-01-15 10:00:00.000000+00', 'B) Minimización, bases legales claras y salvaguardas en transferencias'),
('1011', 'C5', 'Cuestionario', 'Conocimiento', '1', '1', '¿Qué enfoque maduro de entrenamiento ejecutivo adopta mejores prácticas?', 'Multiple Choice (una respuesta)', '["A) Taller único", "B) Ruta continua: fundamentos + prompt-ops + riesgos + métricas, con casos locales del sector", "C) Solo comprar cursos genéricos", "D) Aprendizaje informal"]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', '2025-01-15 10:00:00.000000+00', 'B) Ruta continua: fundamentos + prompt-ops + riesgos + métricas, con casos locales del sector'),
('1012', 'C6', 'Cuestionario', 'Conocimiento', '1', '1', 'Cláusula crítica al contratar Gen-AI en LATAM', 'Multiple Choice (una respuesta)', '["A) Look & feel", "B) Propiedad/uso de outputs, seguridad, ubicación/transferencia de datos y SLAs de calidad/soporte", "C) Color del dashboard", "D) Pago en especie"]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', '2025-01-15 10:00:00.000000+00', 'B) Propiedad/uso de outputs, seguridad, ubicación/transferencia de datos y SLAs de calidad/soporte');

-- ==============================================
-- 4. PREGUNTAS PARA CTO/CIO (exclusivo_rol_id = 2)
-- ==============================================
INSERT INTO "public"."preguntas" ("id", "codigo", "section", "bloque", "area_id", "exclusivo_rol_id", "texto", "tipo", "opciones", "locale", "peso", "escala", "scoring", "created_at", "respuesta_correcta") VALUES 
-- CTO - Adopción (A1-A6)
('2001', 'A1', 'Cuestionario', 'Adopción', '9', '2', '¿Con qué frecuencia utiliza asistentes de código para generar/explicar funciones?', 'Multiple Choice (escala Likert A–E)', '["A) Nunca", "B) Rara vez (≤ 1/mes)", "C) Ocasional (2–3/mes)", "D) Frecuente (semanal)", "E) Muy frecuente (diaria)"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '2025-01-15 10:00:00.000000+00', null),
('2002', 'A2', 'Cuestionario', 'Adopción', '9', '2', '¿Con qué frecuencia usa Gen-AI para documentación técnica, refactoring y/o generación de pruebas (unitarias/integración)?', 'Multiple Choice (escala Likert A–E)', '["A) Nunca", "B) Rara vez (≤ 1/mes)", "C) Ocasional (2–3/mes)", "D) Frecuente (semanal)", "E) Muy frecuente (diaria)"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '2025-01-15 10:00:00.000000+00', null),
('2003', 'A3', 'Cuestionario', 'Adopción', '9', '2', '¿Con qué frecuencia emplea Gen-AI en code reviews/PRs (resúmenes, linting guiado, explicación de cambios, commit messages)?', 'Multiple Choice (escala Likert A–E)', '["A) Nunca", "B) Rara vez (≤ 1/mes)", "C) Ocasional (2–3/mes)", "D) Frecuente (semanal)", "E) Muy frecuente (diaria)"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '2025-01-15 10:00:00.000000+00', null),
('2004', 'A4', 'Cuestionario', 'Adopción', '9', '2', '¿Con qué frecuencia integra capacidades LLM en productos o herramientas internas (RAG, embeddings, chatops, agentes, búsqueda semántica)?', 'Multiple Choice (escala Likert A–E)', '["A) Nunca", "B) Rara vez (≤ 1/mes)", "C) Ocasional (2–3/mes)", "D) Frecuente (semanal)", "E) Muy frecuente (diaria)"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '2025-01-15 10:00:00.000000+00', null),
('2005', 'A5', 'Cuestionario', 'Adopción', '9', '2', '¿Con qué frecuencia aplica guardrails y controles de seguridad/privacidad (redacción de secretos, PII, rate-limits, content filters, aislamiento de entornos)?', 'Multiple Choice (escala Likert A–E)', '["A) Nunca", "B) Rara vez (≤ 1/mes)", "C) Ocasional (2–3/mes)", "D) Frecuente (semanal)", "E) Muy frecuente (diaria)"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '2025-01-15 10:00:00.000000+00', null),
('2006', 'A6', 'Cuestionario', 'Adopción', '9', '2', '¿Con qué frecuencia mide valor y calidad de Gen-AI (A/B interno, aceptación, defectos/MTTR, productividad de PRs)?', 'Multiple Choice (escala Likert A–E)', '["A) Nunca", "B) Rara vez (≤ 1/mes)", "C) Ocasional (2–3/mes)", "D) Frecuente (semanal)", "E) Muy frecuente (diaria)"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '2025-01-15 10:00:00.000000+00', null),

-- CTO - Conocimiento (C1-C6)
('2007', 'C1', 'Cuestionario', 'Conocimiento', '9', '2', '¿Qué es la ventana de contexto en un LLM?', 'Multiple Choice (una respuesta)', '["A) Núcleos de CPU", "B) Memoria a largo plazo del usuario", "C) Cantidad de tokens que el modelo puede procesar por turno", "D) Caché de disco"]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', '2025-01-15 10:00:00.000000+00', 'C) Cantidad de tokens que el modelo puede procesar por turno'),
('2008', 'C2', 'Cuestionario', 'Conocimiento', '9', '2', '¿Qué controla principalmente la temperatura en un LLM?', 'Multiple Choice (una respuesta)', '["A) Latencia", "B) Aleatoriedad/diversidad de las salidas", "C) Límite de tokens", "D) Uso de GPU"]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', '2025-01-15 10:00:00.000000+00', 'B) Aleatoriedad/diversidad de las salidas'),
('2009', 'C3', 'Cuestionario', 'Conocimiento', '9', '2', 'Buena práctica para reducir "alucinaciones" en código sugerido por Gen-AI', 'Multiple Choice (una respuesta)', '["A) Aceptar todo y mergear", "B) Revisión humana + pruebas automatizadas + linters y static analysis", "C) Aumentar la temperatura", "D) Cambiar de IDE"]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', '2025-01-15 10:00:00.000000+00', 'B) Revisión humana + pruebas automatizadas + linters y static analysis'),
('2010', 'C4', 'Cuestionario', 'Conocimiento', '9', '2', 'En integración LLM+RAG con fuentes externas, práctica más segura', 'Multiple Choice (una respuesta)', '["A) Ejecutar comandos del modelo sin validación", "B) Tratar al modelo como no confiable, sanitizar entradas/salidas, bloquear funciones peligrosas y validar orígenes", "C) Dar acceso root al conector", "D) Desactivar logging"]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', '2025-01-15 10:00:00.000000+00', 'B) Tratar al modelo como no confiable, sanitizar entradas/salidas, bloquear funciones peligrosas y validar orígenes'),
('2011', 'C5', 'Cuestionario', 'Conocimiento', '9', '2', 'Métrica que mide mejor el impacto del asistente de código', 'Multiple Choice (una respuesta)', '["A) Nº de prompts", "B) A/B: aceptación útil, defectos, retrabajo, lead time y MTTR vs. baseline", "C) Colores del editor", "D) Nº de ramas"]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', '2025-01-15 10:00:00.000000+00', 'B) A/B: aceptación útil, defectos, retrabajo, lead time y MTTR vs. baseline'),
('2012', 'C6', 'Cuestionario', 'Conocimiento', '9', '2', 'Uso de repos internos con Gen-AI en LATAM – práctica adecuada', 'Multiple Choice (una respuesta)', '["A) Subir PII/secrets a servicios públicos", "B) Minimizar/anonimizar datos, escanear secretos y usar entornos privados o on-prem cuando aplique", "C) Compartir código de clientes sin permiso", "D) Deshabilitar controles de acceso"]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', '2025-01-15 10:00:00.000000+00', 'B) Minimizar/anonimizar datos, escanear secretos y usar entornos privados o on-prem cuando aplique');

-- ==============================================
-- 5. PREGUNTAS PARA DIRECCIÓN DE VENTAS (exclusivo_rol_id = 11)
-- ==============================================
INSERT INTO "public"."preguntas" ("id", "codigo", "section", "bloque", "area_id", "exclusivo_rol_id", "texto", "tipo", "opciones", "locale", "peso", "escala", "scoring", "created_at", "respuesta_correcta") VALUES 
-- Dirección de Ventas - Adopción (A1-A6) - ENFOQUE ESTRATÉGICO
('11001', 'A1', 'Cuestionario', 'Adopción', '2', '11', '¿Con qué frecuencia establece estrategias de ventas basadas en insights de Gen-AI para optimizar el pipeline y aumentar la conversión?', 'Multiple Choice (escala Likert A–E)', '["A) Nunca", "B) Rara vez (≤ 1/mes)", "C) Ocasional (2–3/mes)", "D) Frecuente (semanal)", "E) Muy frecuente (diaria)"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '2025-01-15 10:00:00.000000+00', null),
('11002', 'A2', 'Cuestionario', 'Adopción', '2', '11', '¿Con qué frecuencia utiliza Gen-AI para análisis predictivo de ventas y proyecciones de ingresos para la planificación estratégica?', 'Multiple Choice (escala Likert A–E)', '["A) Nunca", "B) Rara vez (≤ 1/mes)", "C) Ocasional (2–3/mes)", "D) Frecuente (semanal)", "E) Muy frecuente (diaria)"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '2025-01-15 10:00:00.000000+00', null),
('11003', 'A3', 'Cuestionario', 'Adopción', '2', '11', '¿Con qué frecuencia implementa políticas y procesos de ventas que integran Gen-AI para mejorar la eficiencia del equipo?', 'Multiple Choice (escala Likert A–E)', '["A) Nunca", "B) Rara vez (≤ 1/mes)", "C) Ocasional (2–3/mes)", "D) Frecuente (semanal)", "E) Muy frecuente (diaria)"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '2025-01-15 10:00:00.000000+00', null),
('11004', 'A4', 'Cuestionario', 'Adopción', '2', '11', '¿Con qué frecuencia utiliza Gen-AI para segmentación estratégica de clientes y desarrollo de estrategias de pricing?', 'Multiple Choice (escala Likert A–E)', '["A) Nunca", "B) Rara vez (≤ 1/mes)", "C) Ocasional (2–3/mes)", "D) Frecuente (semanal)", "E) Muy frecuente (diaria)"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '2025-01-15 10:00:00.000000+00', null),
('11005', 'A5', 'Cuestionario', 'Adopción', '2', '11', '¿Con qué frecuencia supervisa y optimiza el rendimiento del equipo de ventas utilizando métricas y análisis generados por Gen-AI?', 'Multiple Choice (escala Likert A–E)', '["A) Nunca", "B) Rara vez (≤ 1/mes)", "C) Ocasional (2–3/mes)", "D) Frecuente (semanal)", "E) Muy frecuente (diaria)"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '2025-01-15 10:00:00.000000+00', null),
('11006', 'A6', 'Cuestionario', 'Adopción', '2', '11', '¿Con qué frecuencia utiliza Gen-AI para análisis de competencia y desarrollo de estrategias competitivas de ventas?', 'Multiple Choice (escala Likert A–E)', '["A) Nunca", "B) Rara vez (≤ 1/mes)", "C) Ocasional (2–3/mes)", "D) Frecuente (semanal)", "E) Muy frecuente (diaria)"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '2025-01-15 10:00:00.000000+00', null),

-- Dirección de Ventas - Conocimiento (C1-C6) - ENFOQUE ESTRATÉGICO
('11007', 'C1', 'Cuestionario', 'Conocimiento', '2', '11', 'Para un director de ventas, ¿cuál es la métrica más importante para medir el impacto de Gen-AI?', 'Multiple Choice (una respuesta)', '["A) Número de leads generados", "B) Incremento en el valor promedio de venta y reducción del ciclo de ventas", "C) Tiempo de respuesta a emails", "D) Cantidad de reuniones programadas"]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', '2025-01-15 10:00:00.000000+00', 'B) Incremento en el valor promedio de venta y reducción del ciclo de ventas'),
('11008', 'C2', 'Cuestionario', 'Conocimiento', '2', '11', '¿Cuál es la mejor práctica para implementar Gen-AI en la estrategia de ventas de una empresa?', 'Multiple Choice (una respuesta)', '["A) Implementar todas las herramientas a la vez", "B) Comenzar con pilotos específicos, medir resultados y escalar gradualmente", "C) Solo usar para automatizar emails", "D) No implementar nunca"]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', '2025-01-15 10:00:00.000000+00', 'B) Comenzar con pilotos específicos, medir resultados y escalar gradualmente'),
('11009', 'C3', 'Cuestionario', 'Conocimiento', '2', '11', 'Para análisis predictivo de ventas, ¿qué enfoque es más efectivo para un director?', 'Multiple Choice (una respuesta)', '["A) Confiar solo en las predicciones de IA", "B) Combinar datos históricos, tendencias del mercado, feedback del equipo y validación humana", "C) Usar solo datos del último mes", "D) No hacer análisis predictivo"]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', '2025-01-15 10:00:00.000000+00', 'B) Combinar datos históricos, tendencias del mercado, feedback del equipo y validación humana'),
('11010', 'C4', 'Cuestionario', 'Conocimiento', '2', '11', '¿Cómo debe un director de ventas manejar la información confidencial de clientes al usar Gen-AI?', 'Multiple Choice (una respuesta)', '["A) Subir toda la información a servicios públicos", "B) Establecer políticas claras de privacidad, usar entornos seguros y capacitar al equipo", "C) Compartir con la competencia", "D) No usar Gen-AI nunca"]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', '2025-01-15 10:00:00.000000+00', 'B) Establecer políticas claras de privacidad, usar entornos seguros y capacitar al equipo'),
('11011', 'C5', 'Cuestionario', 'Conocimiento', '2', '11', '¿Cuál es la mejor práctica para capacitar a un equipo de ventas en el uso de Gen-AI?', 'Multiple Choice (una respuesta)', '["A) Darles acceso sin capacitación", "B) Proporcionar entrenamiento estructurado, casos de uso específicos y seguimiento continuo", "C) Solo mostrar videos de YouTube", "D) No capacitar nunca"]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', '2025-01-15 10:00:00.000000+00', 'B) Proporcionar entrenamiento estructurado, casos de uso específicos y seguimiento continuo'),
('11012', 'C6', 'Cuestionario', 'Conocimiento', '2', '11', 'Para optimizar el rendimiento del equipo de ventas con Gen-AI, ¿qué es más importante?', 'Multiple Choice (una respuesta)', '["A) Automatizar todo el proceso", "B) Identificar tareas repetitivas para automatizar, mantener supervisión humana en decisiones críticas y medir impacto", "C) No cambiar nada", "D) Solo automatizar emails"]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', '2025-01-15 10:00:00.000000+00', 'B) Identificar tareas repetitivas para automatizar, mantener supervisión humana en decisiones críticas y medir impacto');

-- ==============================================
-- 6. PREGUNTAS PARA MIEMBROS DE VENTAS (exclusivo_rol_id = 17)
-- ==============================================
INSERT INTO "public"."preguntas" ("id", "codigo", "section", "bloque", "area_id", "exclusivo_rol_id", "texto", "tipo", "opciones", "locale", "peso", "escala", "scoring", "created_at", "respuesta_correcta") VALUES 
-- Miembros de Ventas - Adopción (A1-A6) - ENFOQUE OPERATIVO
('17001', 'A1', 'Cuestionario', 'Adopción', '2', '17', '¿Con qué frecuencia utiliza Gen-AI para calificación y scoring de leads (análisis de comportamiento, intención de compra, priorización)?', 'Multiple Choice (escala Likert A–E)', '["A) Nunca", "B) Rara vez (≤ 1/mes)", "C) Ocasional (2–3/mes)", "D) Frecuente (semanal)", "E) Muy frecuente (diaria)"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '2025-01-15 10:00:00.000000+00', null),
('17002', 'A2', 'Cuestionario', 'Adopción', '2', '17', '¿Con qué frecuencia emplea Gen-AI para generar propuestas comerciales, cotizaciones y presentaciones personalizadas?', 'Multiple Choice (escala Likert A–E)', '["A) Nunca", "B) Rara vez (≤ 1/mes)", "C) Ocasional (2–3/mes)", "D) Frecuente (semanal)", "E) Muy frecuente (diaria)"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '2025-01-15 10:00:00.000000+00', null),
('17003', 'A3', 'Cuestionario', 'Adopción', '2', '17', '¿Con qué frecuencia usa Gen-AI para análisis de pipeline de ventas (predicción de cierre, identificación de riesgos, optimización de procesos)?', 'Multiple Choice (escala Likert A–E)', '["A) Nunca", "B) Rara vez (≤ 1/mes)", "C) Ocasional (2–3/mes)", "D) Frecuente (semanal)", "E) Muy frecuente (diaria)"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '2025-01-15 10:00:00.000000+00', null),
('17004', 'A4', 'Cuestionario', 'Adopción', '2', '17', '¿Con qué frecuencia utiliza Gen-AI para redacción de emails comerciales, seguimiento de clientes y gestión de objeciones?', 'Multiple Choice (escala Likert A–E)', '["A) Nunca", "B) Rara vez (≤ 1/mes)", "C) Ocasional (2–3/mes)", "D) Frecuente (semanal)", "E) Muy frecuente (diaria)"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '2025-01-15 10:00:00.000000+00', null),
('17005', 'A5', 'Cuestionario', 'Adopción', '2', '17', '¿Con qué frecuencia emplea Gen-AI para análisis de competencia, investigación de mercado y posicionamiento de productos?', 'Multiple Choice (escala Likert A–E)', '["A) Nunca", "B) Rara vez (≤ 1/mes)", "C) Ocasional (2–3/mes)", "D) Frecuente (semanal)", "E) Muy frecuente (diaria)"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '2025-01-15 10:00:00.000000+00', null),
('17006', 'A6', 'Cuestionario', 'Adopción', '2', '17', '¿Con qué frecuencia integra Gen-AI en reportes de ventas, análisis de performance del equipo y métricas comerciales?', 'Multiple Choice (escala Likert A–E)', '["A) Nunca", "B) Rara vez (≤ 1/mes)", "C) Ocasional (2–3/mes)", "D) Frecuente (semanal)", "E) Muy frecuente (diaria)"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '2025-01-15 10:00:00.000000+00', null),

-- Miembros de Ventas - Conocimiento (C1-C6) - ENFOQUE OPERATIVO
('17007', 'C1', 'Cuestionario', 'Conocimiento', '2', '17', '¿Cuál es la mejor práctica para integrar Gen-AI en un CRM existente?', 'Multiple Choice (una respuesta)', '["A) Reemplazar completamente el CRM", "B) Integración gradual con APIs, automatización de tareas repetitivas y análisis de datos", "C) Usar solo para emails", "D) No integrar nunca"]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', '2025-01-15 10:00:00.000000+00', 'B) Integración gradual con APIs, automatización de tareas repetitivas y análisis de datos'),
('17008', 'C2', 'Cuestionario', 'Conocimiento', '2', '17', '¿Qué métrica es más importante para medir el impacto de Gen-AI en ventas?', 'Multiple Choice (una respuesta)', '["A) Número de prompts enviados", "B) Tiempo de respuesta a leads, tasa de conversión y valor promedio de venta", "C) Likes en LinkedIn", "D) Cantidad de reuniones"]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', '2025-01-15 10:00:00.000000+00', 'B) Tiempo de respuesta a leads, tasa de conversión y valor promedio de venta'),
('17009', 'C3', 'Cuestionario', 'Conocimiento', '2', '17', 'Para personalizar propuestas comerciales con Gen-AI, ¿qué es más importante?', 'Multiple Choice (una respuesta)', '["A) Usar prompts genéricos", "B) Datos específicos del cliente, historial de compras y necesidades identificadas", "C) Copiar de la competencia", "D) No personalizar"]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', '2025-01-15 10:00:00.000000+00', 'B) Datos específicos del cliente, historial de compras y necesidades identificadas'),
('17010', 'C4', 'Cuestionario', 'Conocimiento', '2', '17', '¿Cómo debe manejarse la información confidencial del cliente al usar Gen-AI?', 'Multiple Choice (una respuesta)', '["A) Subir todo a servicios públicos", "B) Minimizar datos sensibles, usar entornos seguros y cumplir con políticas de privacidad", "C) Compartir con la competencia", "D) No usar nunca"]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', '2025-01-15 10:00:00.000000+00', 'B) Minimizar datos sensibles, usar entornos seguros y cumplir con políticas de privacidad'),
('17011', 'C5', 'Cuestionario', 'Conocimiento', '2', '17', 'Para análisis predictivo de ventas con Gen-AI, ¿qué enfoque es más efectivo?', 'Multiple Choice (una respuesta)', '["A) Confiar ciegamente en las predicciones", "B) Combinar datos históricos, tendencias del mercado y validación humana", "C) Usar solo datos de un mes", "D) No hacer análisis predictivo"]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', '2025-01-15 10:00:00.000000+00', 'B) Combinar datos históricos, tendencias del mercado y validación humana'),
('17012', 'C6', 'Cuestionario', 'Conocimiento', '2', '17', '¿Cuál es la mejor práctica para automatizar procesos de ventas con Gen-AI?', 'Multiple Choice (una respuesta)', '["A) Automatizar todo sin supervisión", "B) Automatizar tareas repetitivas, mantener supervisión humana en decisiones críticas y medir resultados", "C) No automatizar nada", "D) Solo automatizar emails"]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', '2025-01-15 10:00:00.000000+00', 'B) Automatizar tareas repetitivas, mantener supervisión humana en decisiones críticas y medir resultados');

-- ==============================================
-- 7. PREGUNTAS PARA EDUCACIÓN/DOCENTES (exclusivo_rol_id = 9)
-- ==============================================
INSERT INTO "public"."preguntas" ("id", "codigo", "section", "bloque", "area_id", "exclusivo_rol_id", "texto", "tipo", "opciones", "locale", "peso", "escala", "scoring", "created_at", "respuesta_correcta") VALUES 
-- Educación/Docentes - Adopción (A1-A6)
('9001', 'A1', 'Cuestionario', 'Adopción', '10', '9', '¿Con qué frecuencia utiliza Gen-AI para crear contenido educativo, materiales didácticos y recursos de aprendizaje?', 'Multiple Choice (escala Likert A–E)', '["A) Nunca", "B) Rara vez (≤ 1/mes)", "C) Ocasional (2–3/mes)", "D) Frecuente (semanal)", "E) Muy frecuente (diaria)"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '2025-01-15 10:00:00.000000+00', null),
('9002', 'A2', 'Cuestionario', 'Adopción', '10', '9', '¿Con qué frecuencia emplea Gen-AI para generar evaluaciones, exámenes y actividades de aprendizaje personalizadas?', 'Multiple Choice (escala Likert A–E)', '["A) Nunca", "B) Rara vez (≤ 1/mes)", "C) Ocasional (2–3/mes)", "D) Frecuente (semanal)", "E) Muy frecuente (diaria)"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '2025-01-15 10:00:00.000000+00', null),
('9003', 'A3', 'Cuestionario', 'Adopción', '10', '9', '¿Con qué frecuencia usa Gen-AI para proporcionar retroalimentación personalizada y tutoría adaptativa a estudiantes?', 'Multiple Choice (escala Likert A–E)', '["A) Nunca", "B) Rara vez (≤ 1/mes)", "C) Ocasional (2–3/mes)", "D) Frecuente (semanal)", "E) Muy frecuente (diaria)"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '2025-01-15 10:00:00.000000+00', null),
('9004', 'A4', 'Cuestionario', 'Adopción', '10', '9', '¿Con qué frecuencia integra Gen-AI en plataformas de aprendizaje para crear experiencias educativas interactivas?', 'Multiple Choice (escala Likert A–E)', '["A) Nunca", "B) Rara vez (≤ 1/mes)", "C) Ocasional (2–3/mes)", "D) Frecuente (semanal)", "E) Muy frecuente (diaria)"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '2025-01-15 10:00:00.000000+00', null),
('9005', 'A5', 'Cuestionario', 'Adopción', '10', '9', '¿Con qué frecuencia utiliza Gen-AI para análisis del progreso estudiantil y identificación de necesidades de apoyo?', 'Multiple Choice (escala Likert A–E)', '["A) Nunca", "B) Rara vez (≤ 1/mes)", "C) Ocasional (2–3/mes)", "D) Frecuente (semanal)", "E) Muy frecuente (diaria)"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '2025-01-15 10:00:00.000000+00', null),
('9006', 'A6', 'Cuestionario', 'Adopción', '10', '9', '¿Con qué frecuencia emplea Gen-AI para investigación educativa, análisis de tendencias pedagógicas y desarrollo de metodologías?', 'Multiple Choice (escala Likert A–E)', '["A) Nunca", "B) Rara vez (≤ 1/mes)", "C) Ocasional (2–3/mes)", "D) Frecuente (semanal)", "E) Muy frecuente (diaria)"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '2025-01-15 10:00:00.000000+00', null),

-- Educación/Docentes - Conocimiento (C1-C6)
('9007', 'C1', 'Cuestionario', 'Conocimiento', '10', '9', '¿Cuál es la mejor práctica para usar Gen-AI en la creación de contenido educativo?', 'Multiple Choice (una respuesta)', '["A) Usar contenido generado sin revisión", "B) Generar contenido base, revisar pedagógicamente, adaptar al nivel del estudiante y validar la precisión", "C) Solo copiar de internet", "D) No usar Gen-AI nunca"]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', '2025-01-15 10:00:00.000000+00', 'B) Generar contenido base, revisar pedagógicamente, adaptar al nivel del estudiante y validar la precisión'),
('9008', 'C2', 'Cuestionario', 'Conocimiento', '10', '9', 'Para evaluaciones generadas por Gen-AI, ¿qué es más importante?', 'Multiple Choice (una respuesta)', '["A) Usar las preguntas tal como las genera", "B) Revisar la validez pedagógica, alinear con objetivos de aprendizaje y adaptar al nivel de los estudiantes", "C) Solo cambiar las respuestas", "D) No generar evaluaciones"]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', '2025-01-15 10:00:00.000000+00', 'B) Revisar la validez pedagógica, alinear con objetivos de aprendizaje y adaptar al nivel de los estudiantes'),
('9009', 'C3', 'Cuestionario', 'Conocimiento', '10', '9', '¿Cómo debe manejarse la privacidad de datos estudiantiles al usar Gen-AI?', 'Multiple Choice (una respuesta)', '["A) Subir toda la información estudiantil", "B) Cumplir con regulaciones de privacidad educativa, anonimizar datos y obtener consentimiento apropiado", "C) Compartir con otros docentes", "D) No usar Gen-AI nunca"]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', '2025-01-15 10:00:00.000000+00', 'B) Cumplir con regulaciones de privacidad educativa, anonimizar datos y obtener consentimiento apropiado'),
('9010', 'C4', 'Cuestionario', 'Conocimiento', '10', '9', '¿Qué métrica es más importante para medir el impacto de Gen-AI en educación?', 'Multiple Choice (una respuesta)', '["A) Número de materiales generados", "B) Mejora en el rendimiento estudiantil, engagement y satisfacción del aprendizaje", "C) Tiempo ahorrado por el docente", "D) Cantidad de estudiantes atendidos"]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', '2025-01-15 10:00:00.000000+00', 'B) Mejora en el rendimiento estudiantil, engagement y satisfacción del aprendizaje'),
('9011', 'C5', 'Cuestionario', 'Conocimiento', '10', '9', 'Para personalización del aprendizaje con Gen-AI, ¿qué enfoque es más efectivo?', 'Multiple Choice (una respuesta)', '["A) Usar el mismo contenido para todos", "B) Adaptar contenido según el estilo de aprendizaje, nivel de conocimiento y necesidades individuales del estudiante", "C) Solo cambiar el tamaño de la letra", "D) No personalizar nunca"]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', '2025-01-15 10:00:00.000000+00', 'B) Adaptar contenido según el estilo de aprendizaje, nivel de conocimiento y necesidades individuales del estudiante'),
('9012', 'C6', 'Cuestionario', 'Conocimiento', '10', '9', '¿Cuál es la mejor práctica para capacitar a docentes en el uso de Gen-AI?', 'Multiple Choice (una respuesta)', '["A) Darles acceso sin capacitación", "B) Proporcionar entrenamiento pedagógico, casos de uso educativos y apoyo continuo", "C) Solo mostrar videos", "D) No capacitar nunca"]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', '2025-01-15 10:00:00.000000+00', 'B) Proporcionar entrenamiento pedagógico, casos de uso educativos y apoyo continuo');

-- ==============================================
-- 8. VERIFICACIÓN FINAL
-- ==============================================
-- Verificar que se insertaron las preguntas correctamente
SELECT 
    exclusivo_rol_id,
    COUNT(*) as total_preguntas,
    COUNT(CASE WHEN bloque = 'Adopción' THEN 1 END) as adopcion,
    COUNT(CASE WHEN bloque = 'Conocimiento' THEN 1 END) as conocimiento
FROM "public"."preguntas" 
WHERE "section" = 'Cuestionario' 
    AND "exclusivo_rol_id" IN (1, 2, 9, 11, 17)
GROUP BY "exclusivo_rol_id"
ORDER BY "exclusivo_rol_id";

-- Verificar que se insertaron los perfiles correctamente
SELECT 
    id,
    slug,
    nombre,
    area_id
FROM "public"."roles" 
WHERE "id" IN (11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26)
ORDER BY "id";
