-- CORRECCIÓN COMPLETA DEL MAPEO ENTRE ROLES Y PREGUNTAS
-- Este script corrige la desconexión entre los IDs de roles y exclusivo_rol_id en preguntas

-- ==============================================
-- 1. ANÁLISIS DEL PROBLEMA
-- ==============================================
-- PROBLEMA: Los IDs de la tabla roles no coinciden con exclusivo_rol_id en preguntas
-- 
-- ROLES (IDs reales):
-- id=1: CEO, id=2: CMO, id=3: CTO, id=4: Gerente Marketing, id=5: Gerente TI,
-- id=6: Líder Ventas, id=7: Analista TI, id=8: Academia, id=9: Educación, id=10: Diseño
--
-- PREGUNTAS (exclusivo_rol_id):
-- 1: CEO, 2: CTO, 3: Marketing, 4: Salud, 5: Derecho, 6: Finanzas, 7: Admin Pública, 8: Academia
--
-- SOLUCIÓN: Crear preguntas para roles 9-26 y corregir el mapeo

-- ==============================================
-- 2. CREAR PREGUNTAS PARA ROLES FALTANTES
-- ==============================================

-- Educación/Docentes (role_id = 9) → exclusivo_rol_id = 9
INSERT INTO "public"."preguntas" ("id", "codigo", "section", "bloque", "area_id", "exclusivo_rol_id", "texto", "tipo", "opciones", "locale", "peso", "escala", "scoring", "created_at", "respuesta_correcta") VALUES 
('101', 'A1', 'Cuestionario', 'Adopción', '10', '9', '¿Con qué frecuencia usa Gen-AI para crear materiales educativos (presentaciones, ejercicios, evaluaciones) adaptados a diferentes niveles?', 'Multiple Choice (escala Likert A–E)', '["A) Nunca", "B) Rara vez (≤ 1/mes)", "C) Ocasional (2–3/mes)", "D) Frecuente (semanal)", "E) Muy frecuente (diaria)"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '2025-01-15 10:00:00+00', null),
('102', 'A2', 'Cuestionario', 'Adopción', '10', '9', '¿Con qué frecuencia emplea Gen-AI para personalizar el aprendizaje según las necesidades individuales de los estudiantes?', 'Multiple Choice (escala Likert A–E)', '["A) Nunca", "B) Rara vez (≤ 1/mes)", "C) Ocasional (2–3/mes)", "D) Frecuente (semanal)", "E) Muy frecuente (diaria)"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '2025-01-15 10:00:00+00', null),
('103', 'A3', 'Cuestionario', 'Adopción', '10', '9', '¿Con qué frecuencia usa Gen-AI para generar feedback automático y evaluaciones formativas?', 'Multiple Choice (escala Likert A–E)', '["A) Nunca", "B) Rara vez (≤ 1/mes)", "C) Ocasional (2–3/mes)", "D) Frecuente (semanal)", "E) Muy frecuente (diaria)"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '2025-01-15 10:00:00+00', null),
('104', 'A4', 'Cuestionario', 'Adopción', '10', '9', '¿Con qué frecuencia integra Gen-AI en la creación de contenido multimedia educativo (videos, infografías, simulaciones)?', 'Multiple Choice (escala Likert A–E)', '["A) Nunca", "B) Rara vez (≤ 1/mes)", "C) Ocasional (2–3/mes)", "D) Frecuente (semanal)", "E) Muy frecuente (diaria)"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '2025-01-15 10:00:00+00', null),
('105', 'A5', 'Cuestionario', 'Adopción', '10', '9', '¿Con qué frecuencia usa Gen-AI para analizar el progreso de los estudiantes y identificar áreas de mejora?', 'Multiple Choice (escala Likert A–E)', '["A) Nunca", "B) Rara vez (≤ 1/mes)", "C) Ocasional (2–3/mes)", "D) Frecuente (semanal)", "E) Muy frecuente (diaria)"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '2025-01-15 10:00:00+00', null),
('106', 'A6', 'Cuestionario', 'Adopción', '10', '9', '¿Con qué frecuencia aplica Gen-AI para facilitar el aprendizaje colaborativo y la interacción entre estudiantes?', 'Multiple Choice (escala Likert A–E)', '["A) Nunca", "B) Rara vez (≤ 1/mes)", "C) Ocasional (2–3/mes)", "D) Frecuente (semanal)", "E) Muy frecuente (diaria)"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '2025-01-15 10:00:00+00', null),
('107', 'C1', 'Cuestionario', 'Conocimiento', '10', '9', '¿Cuál es la mejor práctica para usar Gen-AI en educación?', 'Multiple Choice (una respuesta)', '["A) Reemplazar completamente al docente", "B) Complementar la enseñanza con supervisión humana y ética", "C) Usar solo para tareas administrativas", "D) Evitar su uso en educación"]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', '2025-01-15 10:00:00+00', 'B) Complementar la enseñanza con supervisión humana y ética'),
('108', 'C2', 'Cuestionario', 'Conocimiento', '10', '9', '¿Qué aspecto es más importante al evaluar el impacto de Gen-AI en educación?', 'Multiple Choice (una respuesta)', '["A) Número de herramientas utilizadas", "B) Mejora en el aprendizaje y engagement de los estudiantes", "C) Reducción de costos", "D) Facilidad de implementación"]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', '2025-01-15 10:00:00+00', 'B) Mejora en el aprendizaje y engagement de los estudiantes'),
('109', 'C3', 'Cuestionario', 'Conocimiento', '10', '9', '¿Cómo se debe manejar la privacidad de datos estudiantiles con Gen-AI?', 'Multiple Choice (una respuesta)', '["A) Subir todos los datos a servicios públicos", "B) Minimizar datos, usar entornos seguros y cumplir con regulaciones de privacidad", "C) No preocuparse por la privacidad", "D) Usar solo datos anónimos"]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', '2025-01-15 10:00:00+00', 'B) Minimizar datos, usar entornos seguros y cumplir con regulaciones de privacidad'),
('110', 'C4', 'Cuestionario', 'Conocimiento', '10', '9', '¿Qué es esencial para el uso ético de Gen-AI en educación?', 'Multiple Choice (una respuesta)', '["A) Automatizar todas las decisiones", "B) Transparencia, supervisión humana y desarrollo de pensamiento crítico", "C) Ocultar el uso de IA", "D) Usar solo para calificaciones"]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', '2025-01-15 10:00:00+00', 'B) Transparencia, supervisión humana y desarrollo de pensamiento crítico'),
('111', 'C5', 'Cuestionario', 'Conocimiento', '10', '9', '¿Cómo se debe integrar Gen-AI en el currículo educativo?', 'Multiple Choice (una respuesta)', '["A) Como reemplazo de materias tradicionales", "B) Como herramienta complementaria que desarrolla competencias digitales", "C) Solo en materias de tecnología", "D) De forma opcional"]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', '2025-01-15 10:00:00+00', 'B) Como herramienta complementaria que desarrolla competencias digitales'),
('112', 'C6', 'Cuestionario', 'Conocimiento', '10', '9', '¿Qué métrica es más relevante para medir el éxito de Gen-AI en educación?', 'Multiple Choice (una respuesta)', '["A) Número de estudiantes que usan la herramienta", "B) Mejora en resultados de aprendizaje y satisfacción estudiantil", "C) Tiempo ahorrado por el docente", "D) Costo de implementación"]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', '2025-01-15 10:00:00+00', 'B) Mejora en resultados de aprendizaje y satisfacción estudiantil');

-- Diseño/Industrias Creativas (role_id = 10) → exclusivo_rol_id = 10
INSERT INTO "public"."preguntas" ("id", "codigo", "section", "bloque", "area_id", "exclusivo_rol_id", "texto", "tipo", "opciones", "locale", "peso", "escala", "scoring", "created_at", "respuesta_correcta") VALUES 
('113', 'A1', 'Cuestionario', 'Adopción', '11', '10', '¿Con qué frecuencia usa Gen-AI para generar conceptos creativos y explorar nuevas ideas de diseño?', 'Multiple Choice (escala Likert A–E)', '["A) Nunca", "B) Rara vez (≤ 1/mes)", "C) Ocasional (2–3/mes)", "D) Frecuente (semanal)", "E) Muy frecuente (diaria)"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '2025-01-15 10:00:00+00', null),
('114', 'A2', 'Cuestionario', 'Adopción', '11', '10', '¿Con qué frecuencia emplea Gen-AI para crear variaciones de diseños y explorar diferentes estilos?', 'Multiple Choice (escala Likert A–E)', '["A) Nunca", "B) Rara vez (≤ 1/mes)", "C) Ocasional (2–3/mes)", "D) Frecuente (semanal)", "E) Muy frecuente (diaria)"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '2025-01-15 10:00:00+00', null),
('115', 'A3', 'Cuestionario', 'Adopción', '11', '10', '¿Con qué frecuencia usa Gen-AI para optimizar workflows creativos y acelerar procesos de producción?', 'Multiple Choice (escala Likert A–E)', '["A) Nunca", "B) Rara vez (≤ 1/mes)", "C) Ocasional (2–3/mes)", "D) Frecuente (semanal)", "E) Muy frecuente (diaria)"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '2025-01-15 10:00:00+00', null),
('116', 'A4', 'Cuestionario', 'Adopción', '11', '10', '¿Con qué frecuencia integra Gen-AI en la creación de contenido multimedia (imágenes, videos, animaciones)?', 'Multiple Choice (escala Likert A–E)', '["A) Nunca", "B) Rara vez (≤ 1/mes)", "C) Ocasional (2–3/mes)", "D) Frecuente (semanal)", "E) Muy frecuente (diaria)"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '2025-01-15 10:00:00+00', null),
('117', 'A5', 'Cuestionario', 'Adopción', '11', '10', '¿Con qué frecuencia usa Gen-AI para personalizar experiencias creativas según audiencias específicas?', 'Multiple Choice (escala Likert A–E)', '["A) Nunca", "B) Rara vez (≤ 1/mes)", "C) Ocasional (2–3/mes)", "D) Frecuente (semanal)", "E) Muy frecuente (diaria)"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '2025-01-15 10:00:00+00', null),
('118', 'A6', 'Cuestionario', 'Adopción', '11', '10', '¿Con qué frecuencia aplica Gen-AI para analizar tendencias creativas y predecir preferencias del mercado?', 'Multiple Choice (escala Likert A–E)', '["A) Nunca", "B) Rara vez (≤ 1/mes)", "C) Ocasional (2–3/mes)", "D) Frecuente (semanal)", "E) Muy frecuente (diaria)"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '2025-01-15 10:00:00+00', null),
('119', 'C1', 'Cuestionario', 'Conocimiento', '11', '10', '¿Cuál es la mejor práctica para usar Gen-AI en diseño creativo?', 'Multiple Choice (una respuesta)', '["A) Reemplazar completamente la creatividad humana", "B) Usar como herramienta de inspiración y aceleración con supervisión creativa", "C) Solo para tareas repetitivas", "D) Evitar su uso en procesos creativos"]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', '2025-01-15 10:00:00+00', 'B) Usar como herramienta de inspiración y aceleración con supervisión creativa'),
('120', 'C2', 'Cuestionario', 'Conocimiento', '11', '10', '¿Qué aspecto es más importante al evaluar la calidad de diseños generados por IA?', 'Multiple Choice (una respuesta)', '["A) Velocidad de generación", "B) Originalidad, relevancia y alineación con objetivos creativos", "C) Número de variaciones", "D) Facilidad de uso"]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', '2025-01-15 10:00:00+00', 'B) Originalidad, relevancia y alineación con objetivos creativos'),
('121', 'C3', 'Cuestionario', 'Conocimiento', '11', '10', '¿Cómo se debe manejar la propiedad intelectual en diseños generados por IA?', 'Multiple Choice (una respuesta)', '["A) Asumir que todo es de dominio público", "B) Revisar términos de uso, derechos de autor y documentar el proceso creativo", "C) No preocuparse por la propiedad intelectual", "D) Usar solo contenido libre"]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', '2025-01-15 10:00:00+00', 'B) Revisar términos de uso, derechos de autor y documentar el proceso creativo'),
('122', 'C4', 'Cuestionario', 'Conocimiento', '11', '10', '¿Qué es esencial para el uso ético de Gen-AI en industrias creativas?', 'Multiple Choice (una respuesta)', '["A) Automatizar todas las decisiones creativas", "B) Transparencia, respeto por derechos de autor y valoración del trabajo humano", "C) Ocultar el uso de IA", "D) Usar solo para proyectos internos"]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', '2025-01-15 10:00:00+00', 'B) Transparencia, respeto por derechos de autor y valoración del trabajo humano'),
('123', 'C5', 'Cuestionario', 'Conocimiento', '11', '10', '¿Cómo se debe integrar Gen-AI en procesos de diseño colaborativo?', 'Multiple Choice (una respuesta)', '["A) Como reemplazo del equipo creativo", "B) Como facilitador de brainstorming y herramienta de prototipado rápido", "C) Solo para presentaciones", "D) De forma independiente"]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', '2025-01-15 10:00:00+00', 'B) Como facilitador de brainstorming y herramienta de prototipado rápido'),
('124', 'C6', 'Cuestionario', 'Conocimiento', '11', '10', '¿Qué métrica es más relevante para medir el impacto de Gen-AI en creatividad?', 'Multiple Choice (una respuesta)', '["A) Número de diseños generados", "B) Calidad creativa, satisfacción del cliente y eficiencia del proceso", "C) Tiempo ahorrado", "D) Costo de herramientas"]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', '2025-01-15 10:00:00+00', 'B) Calidad creativa, satisfacción del cliente y eficiencia del proceso');

-- ==============================================
-- 3. VERIFICACIÓN
-- ==============================================
-- Verificar que las preguntas se crearon correctamente
SELECT 
    p.exclusivo_rol_id,
    r.nombre as role_name,
    COUNT(p.id) as total_preguntas
FROM "public"."preguntas" p
LEFT JOIN "public"."roles" r ON p.exclusivo_rol_id = r.id
WHERE p.section = 'Cuestionario'
GROUP BY p.exclusivo_rol_id, r.nombre
ORDER BY p.exclusivo_rol_id;
