-- CORRECCIÓN COMPLETA DEL SISTEMA DE PREGUNTAS
-- Este archivo corrige todos los problemas de mapeo de roles y preguntas

-- ==============================================
-- 1. LIMPIAR PREGUNTAS EXISTENTES (OPCIONAL)
-- ==============================================
-- Descomenta la siguiente línea si quieres limpiar todas las preguntas existentes
-- DELETE FROM "public"."preguntas" WHERE "section" = 'Cuestionario';

-- ==============================================
-- 2. PREGUNTAS PARA CEO (exclusivo_rol_id = 1)
-- ==============================================
INSERT INTO "public"."preguntas" ("id", "codigo", "section", "bloque", "area_id", "exclusivo_rol_id", "texto", "tipo", "opciones", "locale", "peso", "escala", "scoring", "created_at", "respuesta_correcta") VALUES 
-- CEO - Adopción (A1-A6)
('1001', 'A1', 'Cuestionario', 'Adopción', '2', '1', '¿Con qué frecuencia impulsa iniciativas de Gen-AI con presupuesto y OKRs explícitos (p. ej., automatización de back-office, copilots comerciales, analytics aumentada)?', 'Multiple Choice (escala Likert A–E)', '["A) Nunca", "B) Rara vez (≤ 1/mes)", "C) Ocasional (2–3/mes)", "D) Frecuente (semanal)", "E) Muy frecuente (diaria)"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '2025-01-15 10:00:00.000000+00', null),
('1002', 'A2', 'Cuestionario', 'Adopción', '2', '1', '¿Con qué frecuencia revisa y decide sobre el portafolio de casos de uso de Gen-AI (priorización por valor/viabilidad, stage-gate)?', 'Multiple Choice (escala Likert A–E)', '["A) Nunca", "B) Rara vez (≤ 1/mes)", "C) Ocasional (2–3/mes)", "D) Frecuente (semanal)", "E) Muy frecuente (diaria)"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '2025-01-15 10:00:00.000000+00', null),
('1003', 'A3', 'Cuestionario', 'Adopción', '2', '1', '¿Con qué frecuencia consulta métricas de valor (ahorros, ingresos, time-to-market, NPS interno) con línea base y responsables?', 'Multiple Choice (escala Likert A–E)', '["A) Nunca", "B) Rara vez (≤ 1/mes)", "C) Ocasional (2–3/mes)", "D) Frecuente (semanal)", "E) Muy frecuente (diaria)"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '2025-01-15 10:00:00.000000+00', null),
('1004', 'A4', 'Cuestionario', 'Adopción', '2', '1', '¿Con qué frecuencia participa en la gobernanza: políticas de uso, guardrails, comité de IA, evaluación de alto riesgo (salud, financiero, contratación, servicios públicos)?', 'Multiple Choice (escala Likert A–E)', '["A) Nunca", "B) Rara vez (≤ 1/mes)", "C) Ocasional (2–3/mes)", "D) Frecuente (semanal)", "E) Muy frecuente (diaria)"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '2025-01-15 10:00:00.000000+00', null),
('1005', 'A5', 'Cuestionario', 'Adopción', '2', '1', '¿Con qué frecuencia aprueba o supervisa controles de datos y cumplimiento locales (p. ej., INAI/AAIP/SIC) y transferencias transfronterizas?', 'Multiple Choice (escala Likert A–E)', '["A) Nunca", "B) Rara vez (≤ 1/mes)", "C) Ocasional (2–3/mes)", "D) Frecuente (semanal)", "E) Muy frecuente (diaria)"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '2025-01-15 10:00:00.000000+00', null),
('1006', 'A6', 'Cuestionario', 'Adopción', '2', '1', '¿Con qué frecuencia financia/monitorea programas de upskilling (prompt-engineering, seguridad, ética) para liderazgo y áreas de negocio?', 'Multiple Choice (escala Likert A–E)', '["A) Nunca", "B) Rara vez (≤ 1/mes)", "C) Ocasional (2–3/mes)", "D) Frecuente (semanal)", "E) Muy frecuente (diaria)"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '2025-01-15 10:00:00.000000+00', null),

-- CEO - Conocimiento (C1-C6)
('1007', 'C1', 'Cuestionario', 'Conocimiento', '2', '1', '¿Cuál es un KPI estratégico adecuado para Gen-AI a nivel CEO?', 'Multiple Choice (una respuesta)', '["A) Número de prompts enviados", "B) Valor capturado contra línea base (ahorro/ingreso/tiempo)", "C) Likes en redes", "D) Cantidad de proveedores"]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', '2025-01-15 10:00:00.000000+00', 'B) Valor capturado contra línea base (ahorro/ingreso/tiempo)'),
('1008', 'C2', 'Cuestionario', 'Conocimiento', '2', '1', '¿Qué práctica valida mejor el ROI en LATAM con presupuestos acotados?', 'Multiple Choice (una respuesta)', '["A) Comprar primero licencias masivas", "B) Pilotos con control A/B y línea base operacional", "C) Esperar a que la competencia publique su ROI", "D) Usar solo encuestas de percepción"]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', '2025-01-15 10:00:00.000000+00', 'B) Pilotos con control A/B y línea base operacional'),
('1009', 'C3', 'Cuestionario', 'Conocimiento', '2', '1', 'Para casos de alto riesgo (crédito, salud, empleo), ¿qué es indispensable?', 'Multiple Choice (una respuesta)', '["A) Delegar todo a IA", "B) Supervisión humana, documentación del caso y evaluación de impacto/explicabilidad", "C) Ocultar el uso de IA", "D) Solo NDAs con proveedores"]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', '2025-01-15 10:00:00.000000+00', 'B) Supervisión humana, documentación del caso y evaluación de impacto/explicabilidad'),
('1010', 'C4', 'Cuestionario', 'Conocimiento', '2', '1', 'En México y región, ¿qué principio debe regir el uso de datos en Gen-AI?', 'Multiple Choice (una respuesta)', '["A) Subir PII a cualquier servicio", "B) Minimización, bases legales claras y salvaguardas en transferencias", "C) Recolección indiscriminada", "D) Reutilizar expedientes sin informar"]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', '2025-01-15 10:00:00.000000+00', 'B) Minimización, bases legales claras y salvaguardas en transferencias'),
('1011', 'C5', 'Cuestionario', 'Conocimiento', '2', '1', '¿Qué enfoque maduro de entrenamiento ejecutivo adopta mejores prácticas?', 'Multiple Choice (una respuesta)', '["A) Taller único", "B) Ruta continua: fundamentos + prompt-ops + riesgos + métricas, con casos locales del sector", "C) Solo comprar cursos genéricos", "D) Aprendizaje informal"]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', '2025-01-15 10:00:00.000000+00', 'B) Ruta continua: fundamentos + prompt-ops + riesgos + métricas, con casos locales del sector'),
('1012', 'C6', 'Cuestionario', 'Conocimiento', '2', '1', 'Cláusula crítica al contratar Gen-AI en LATAM', 'Multiple Choice (una respuesta)', '["A) Look & feel", "B) Propiedad/uso de outputs, seguridad, ubicación/transferencia de datos y SLAs de calidad/soporte", "C) Color del dashboard", "D) Pago en especie"]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', '2025-01-15 10:00:00.000000+00', 'B) Propiedad/uso de outputs, seguridad, ubicación/transferencia de datos y SLAs de calidad/soporte');

-- ==============================================
-- 3. PREGUNTAS PARA CTO/CIO (exclusivo_rol_id = 2)
-- ==============================================
INSERT INTO "public"."preguntas" ("id", "codigo", "section", "bloque", "area_id", "exclusivo_rol_id", "texto", "tipo", "opciones", "locale", "peso", "escala", "scoring", "created_at", "respuesta_correcta") VALUES 
-- CTO - Adopción (A1-A6)
('2001', 'A1', 'Cuestionario', 'Adopción', '3', '2', '¿Con qué frecuencia utiliza asistentes de código para generar/explicar funciones?', 'Multiple Choice (escala Likert A–E)', '["A) Nunca", "B) Rara vez (≤ 1/mes)", "C) Ocasional (2–3/mes)", "D) Frecuente (semanal)", "E) Muy frecuente (diaria)"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '2025-01-15 10:00:00.000000+00', null),
('2002', 'A2', 'Cuestionario', 'Adopción', '3', '2', '¿Con qué frecuencia usa Gen-AI para documentación técnica, refactoring y/o generación de pruebas (unitarias/integración)?', 'Multiple Choice (escala Likert A–E)', '["A) Nunca", "B) Rara vez (≤ 1/mes)", "C) Ocasional (2–3/mes)", "D) Frecuente (semanal)", "E) Muy frecuente (diaria)"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '2025-01-15 10:00:00.000000+00', null),
('2003', 'A3', 'Cuestionario', 'Adopción', '3', '2', '¿Con qué frecuencia emplea Gen-AI en code reviews/PRs (resúmenes, linting guiado, explicación de cambios, commit messages)?', 'Multiple Choice (escala Likert A–E)', '["A) Nunca", "B) Rara vez (≤ 1/mes)", "C) Ocasional (2–3/mes)", "D) Frecuente (semanal)", "E) Muy frecuente (diaria)"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '2025-01-15 10:00:00.000000+00', null),
('2004', 'A4', 'Cuestionario', 'Adopción', '3', '2', '¿Con qué frecuencia integra capacidades LLM en productos o herramientas internas (RAG, embeddings, chatops, agentes, búsqueda semántica)?', 'Multiple Choice (escala Likert A–E)', '["A) Nunca", "B) Rara vez (≤ 1/mes)", "C) Ocasional (2–3/mes)", "D) Frecuente (semanal)", "E) Muy frecuente (diaria)"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '2025-01-15 10:00:00.000000+00', null),
('2005', 'A5', 'Cuestionario', 'Adopción', '3', '2', '¿Con qué frecuencia aplica guardrails y controles de seguridad/privacidad (redacción de secretos, PII, rate-limits, content filters, aislamiento de entornos)?', 'Multiple Choice (escala Likert A–E)', '["A) Nunca", "B) Rara vez (≤ 1/mes)", "C) Ocasional (2–3/mes)", "D) Frecuente (semanal)", "E) Muy frecuente (diaria)"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '2025-01-15 10:00:00.000000+00', null),
('2006', 'A6', 'Cuestionario', 'Adopción', '3', '2', '¿Con qué frecuencia mide valor y calidad de Gen-AI (A/B interno, aceptación, defectos/MTTR, productividad de PRs)?', 'Multiple Choice (escala Likert A–E)', '["A) Nunca", "B) Rara vez (≤ 1/mes)", "C) Ocasional (2–3/mes)", "D) Frecuente (semanal)", "E) Muy frecuente (diaria)"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '2025-01-15 10:00:00.000000+00', null),

-- CTO - Conocimiento (C1-C6)
('2007', 'C1', 'Cuestionario', 'Conocimiento', '3', '2', '¿Qué es la ventana de contexto en un LLM?', 'Multiple Choice (una respuesta)', '["A) Núcleos de CPU", "B) Memoria a largo plazo del usuario", "C) Cantidad de tokens que el modelo puede procesar por turno", "D) Caché de disco"]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', '2025-01-15 10:00:00.000000+00', 'C) Cantidad de tokens que el modelo puede procesar por turno'),
('2008', 'C2', 'Cuestionario', 'Conocimiento', '3', '2', '¿Qué controla principalmente la temperatura en un LLM?', 'Multiple Choice (una respuesta)', '["A) Latencia", "B) Aleatoriedad/diversidad de las salidas", "C) Límite de tokens", "D) Uso de GPU"]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', '2025-01-15 10:00:00.000000+00', 'B) Aleatoriedad/diversidad de las salidas'),
('2009', 'C3', 'Cuestionario', 'Conocimiento', '3', '2', 'Buena práctica para reducir "alucinaciones" en código sugerido por Gen-AI', 'Multiple Choice (una respuesta)', '["A) Aceptar todo y mergear", "B) Revisión humana + pruebas automatizadas + linters y static analysis", "C) Aumentar la temperatura", "D) Cambiar de IDE"]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', '2025-01-15 10:00:00.000000+00', 'B) Revisión humana + pruebas automatizadas + linters y static analysis'),
('2010', 'C4', 'Cuestionario', 'Conocimiento', '3', '2', 'En integración LLM+RAG con fuentes externas, práctica más segura', 'Multiple Choice (una respuesta)', '["A) Ejecutar comandos del modelo sin validación", "B) Tratar al modelo como no confiable, sanitizar entradas/salidas, bloquear funciones peligrosas y validar orígenes", "C) Dar acceso root al conector", "D) Desactivar logging"]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', '2025-01-15 10:00:00.000000+00', 'B) Tratar al modelo como no confiable, sanitizar entradas/salidas, bloquear funciones peligrosas y validar orígenes'),
('2011', 'C5', 'Cuestionario', 'Conocimiento', '3', '2', 'Métrica que mide mejor el impacto del asistente de código', 'Multiple Choice (una respuesta)', '["A) Nº de prompts", "B) A/B: aceptación útil, defectos, retrabajo, lead time y MTTR vs. baseline", "C) Colores del editor", "D) Nº de ramas"]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', '2025-01-15 10:00:00.000000+00', 'B) A/B: aceptación útil, defectos, retrabajo, lead time y MTTR vs. baseline'),
('2012', 'C6', 'Cuestionario', 'Conocimiento', '3', '2', 'Uso de repos internos con Gen-AI en LATAM – práctica adecuada', 'Multiple Choice (una respuesta)', '["A) Subir PII/secrets a servicios públicos", "B) Minimizar/anonimizar datos, escanear secretos y usar entornos privados o on-prem cuando aplique", "C) Compartir código de clientes sin permiso", "D) Deshabilitar controles de acceso"]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', '2025-01-15 10:00:00.000000+00', 'B) Minimizar/anonimizar datos, escanear secretos y usar entornos privados o on-prem cuando aplique');

-- ==============================================
-- 4. PREGUNTAS PARA MARKETING (exclusivo_rol_id = 3)
-- ==============================================
INSERT INTO "public"."preguntas" ("id", "codigo", "section", "bloque", "area_id", "exclusivo_rol_id", "texto", "tipo", "opciones", "locale", "peso", "escala", "scoring", "created_at", "respuesta_correcta") VALUES 
-- Marketing - Adopción (A1-A6)
('3001', 'A1', 'Cuestionario', 'Adopción', '4', '3', '¿Con qué frecuencia usa Gen-AI para ideación y copy (posts, emails, ads, guiones) con guías de tono de marca?', 'Multiple Choice (escala Likert A–E)', '["A) Nunca", "B) Rara vez (≤ 1/mes)", "C) Ocasional (2–3/mes)", "D) Frecuente (semanal)", "E) Muy frecuente (diaria)"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '2025-01-15 10:00:00.000000+00', null),
('3002', 'A2', 'Cuestionario', 'Adopción', '4', '3', '¿Con qué frecuencia genera activos creativos (imágenes/video/carruseles) o variaciones para A/B con Gen-AI?', 'Multiple Choice (escala Likert A–E)', '["A) Nunca", "B) Rara vez (≤ 1/mes)", "C) Ocasional (2–3/mes)", "D) Frecuente (semanal)", "E) Muy frecuente (diaria)"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '2025-01-15 10:00:00.000000+00', null),
('3003', 'A3', 'Cuestionario', 'Adopción', '4', '3', '¿Con qué frecuencia aplica Gen-AI para localización/transcreación al español regional (MX, AR, CO, CL, etc.)?', 'Multiple Choice (escala Likert A–E)', '["A) Nunca", "B) Rara vez (≤ 1/mes)", "C) Ocasional (2–3/mes)", "D) Frecuente (semanal)", "E) Muy frecuente (diaria)"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '2025-01-15 10:00:00.000000+00', null),
('3004', 'A4', 'Cuestionario', 'Adopción', '4', '3', '¿Con qué frecuencia usa Gen-AI para social listening/insights (resúmenes de sentimiento, temas emergentes)?', 'Multiple Choice (escala Likert A–E)', '["A) Nunca", "B) Rara vez (≤ 1/mes)", "C) Ocasional (2–3/mes)", "D) Frecuente (semanal)", "E) Muy frecuente (diaria)"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '2025-01-15 10:00:00.000000+00', null),
('3005', 'A5', 'Cuestionario', 'Adopción', '4', '3', '¿Con qué frecuencia emplea Gen-AI para personalización (segmentos, mensajes dinámicos) con datos minimizados?', 'Multiple Choice (escala Likert A–E)', '["A) Nunca", "B) Rara vez (≤ 1/mes)", "C) Ocasional (2–3/mes)", "D) Frecuente (semanal)", "E) Muy frecuente (diaria)"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '2025-01-15 10:00:00.000000+00', null),
('3006', 'A6', 'Cuestionario', 'Adopción', '4', '3', '¿Con qué frecuencia integra Gen-AI en medición de performance (resúmenes de campañas, hipótesis, lift y CAC/LTV)?', 'Multiple Choice (escala Likert A–E)', '["A) Nunca", "B) Rara vez (≤ 1/mes)", "C) Ocasional (2–3/mes)", "D) Frecuente (semanal)", "E) Muy frecuente (diaria)"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '2025-01-15 10:00:00.000000+00', null),

-- Marketing - Conocimiento (C1-C6)
('3007', 'C1', 'Cuestionario', 'Conocimiento', '4', '3', 'Práctica que mejora la coherencia del tono de marca', 'Multiple Choice (una respuesta)', '["A) Prompt genérico", "B) Prompt con guía de marca (do/don't), ejemplos y style sheet", "C) Aumentar temperatura", "D) Traducir literal"]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', '2025-01-15 10:00:00.000000+00', 'B) Prompt con guía de marca (do/don't), ejemplos y style sheet'),
('3008', 'C2', 'Cuestionario', 'Conocimiento', '4', '3', 'Para creatividades generadas por IA, aspecto crítico', 'Multiple Choice (una respuesta)', '["A) Todo es libre por defecto", "B) Revisar términos de uso/licencias y derechos sobre outputs para uso comercial", "C) Solo cambiar colores", "D) No registrar evidencia"]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', '2025-01-15 10:00:00.000000+00', 'B) Revisar términos de uso/licencias y derechos sobre outputs para uso comercial'),
('3009', 'C3', 'Cuestionario', 'Conocimiento', '4', '3', 'Personalización con Gen-AI en LATAM – enfoque adecuado', 'Multiple Choice (una respuesta)', '["A) Subir PII sin aviso", "B) Minimización, base legal/consentimiento y controles de transferencia internacional", "C) Usar listas compradas sin revisión", "D) Reutilizar CRM sin opción de baja"]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', '2025-01-15 10:00:00.000000+00', 'B) Minimización, base legal/consentimiento y controles de transferencia internacional'),
('3010', 'C4', 'Cuestionario', 'Conocimiento', '4', '3', 'Qué evalúa mejor el impacto en performance', 'Multiple Choice (una respuesta)', '["A) Nº de prompts", "B) Experimentos A/B y uplift vs. baseline (CTR, CVR, CAC, LTV)", "C) Likes", "D) Tamaño del budget"]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', '2025-01-15 10:00:00.000000+00', 'B) Experimentos A/B y uplift vs. baseline (CTR, CVR, CAC, LTV)'),
('3011', 'C5', 'Cuestionario', 'Conocimiento', '4', '3', 'Para contenido multilingüe en LATAM, práctica recomendada', 'Multiple Choice (una respuesta)', '["A) Traducción literal", "B) Adaptación cultural + validación local + contexto regional", "C) Solo cambiar moneda", "D) Usar solo inglés"]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', '2025-01-15 10:00:00.000000+00', 'B) Adaptación cultural + validación local + contexto regional'),
('3012', 'C6', 'Cuestionario', 'Conocimiento', '4', '3', 'Cláusula crítica al contratar Gen-AI para marketing en LATAM', 'Multiple Choice (una respuesta)', '["A) Color del logo", "B) Propiedad de outputs, uso comercial, derechos de imagen y compliance con regulaciones locales", "C) Solo precio", "D) Tiempo de entrega"]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', '2025-01-15 10:00:00.000000+00', 'B) Propiedad de outputs, uso comercial, derechos de imagen y compliance con regulaciones locales');

-- ==============================================
-- 5. PREGUNTAS PARA VENTAS (exclusivo_rol_id = 6)
-- ==============================================
INSERT INTO "public"."preguntas" ("id", "codigo", "section", "bloque", "area_id", "exclusivo_rol_id", "texto", "tipo", "opciones", "locale", "peso", "escala", "scoring", "created_at", "respuesta_correcta") VALUES 
-- Ventas - Adopción (A1-A6)
('6001', 'A1', 'Cuestionario', 'Adopción', '2', '6', '¿Con qué frecuencia utiliza Gen-AI para calificación y scoring de leads (análisis de comportamiento, intención de compra, priorización)?', 'Multiple Choice (escala Likert A–E)', '["A) Nunca", "B) Rara vez (≤ 1/mes)", "C) Ocasional (2–3/mes)", "D) Frecuente (semanal)", "E) Muy frecuente (diaria)"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '2025-01-15 10:00:00.000000+00', null),
('6002', 'A2', 'Cuestionario', 'Adopción', '2', '6', '¿Con qué frecuencia emplea Gen-AI para generar propuestas comerciales, cotizaciones y presentaciones personalizadas?', 'Multiple Choice (escala Likert A–E)', '["A) Nunca", "B) Rara vez (≤ 1/mes)", "C) Ocasional (2–3/mes)", "D) Frecuente (semanal)", "E) Muy frecuente (diaria)"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '2025-01-15 10:00:00.000000+00', null),
('6003', 'A3', 'Cuestionario', 'Adopción', '2', '6', '¿Con qué frecuencia usa Gen-AI para análisis de pipeline de ventas (predicción de cierre, identificación de riesgos, optimización de procesos)?', 'Multiple Choice (escala Likert A–E)', '["A) Nunca", "B) Rara vez (≤ 1/mes)", "C) Ocasional (2–3/mes)", "D) Frecuente (semanal)", "E) Muy frecuente (diaria)"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '2025-01-15 10:00:00.000000+00', null),
('6004', 'A4', 'Cuestionario', 'Adopción', '2', '6', '¿Con qué frecuencia utiliza Gen-AI para redacción de emails comerciales, seguimiento de clientes y gestión de objeciones?', 'Multiple Choice (escala Likert A–E)', '["A) Nunca", "B) Rara vez (≤ 1/mes)", "C) Ocasional (2–3/mes)", "D) Frecuente (semanal)", "E) Muy frecuente (diaria)"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '2025-01-15 10:00:00.000000+00', null),
('6005', 'A5', 'Cuestionario', 'Adopción', '2', '6', '¿Con qué frecuencia emplea Gen-AI para análisis de competencia, investigación de mercado y posicionamiento de productos?', 'Multiple Choice (escala Likert A–E)', '["A) Nunca", "B) Rara vez (≤ 1/mes)", "C) Ocasional (2–3/mes)", "D) Frecuente (semanal)", "E) Muy frecuente (diaria)"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '2025-01-15 10:00:00.000000+00', null),
('6006', 'A6', 'Cuestionario', 'Adopción', '2', '6', '¿Con qué frecuencia integra Gen-AI en reportes de ventas, análisis de performance del equipo y métricas comerciales?', 'Multiple Choice (escala Likert A–E)', '["A) Nunca", "B) Rara vez (≤ 1/mes)", "C) Ocasional (2–3/mes)", "D) Frecuente (semanal)", "E) Muy frecuente (diaria)"]', 'MX/LATAM', '8.333333', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '{"A": 0, "B": 25, "C": 50, "D": 75, "E": 100}', '2025-01-15 10:00:00.000000+00', null),

-- Ventas - Conocimiento (C1-C6)
('6007', 'C1', 'Cuestionario', 'Conocimiento', '2', '6', '¿Cuál es la mejor práctica para integrar Gen-AI en un CRM existente?', 'Multiple Choice (una respuesta)', '["A) Reemplazar completamente el CRM", "B) Integración gradual con APIs, automatización de tareas repetitivas y análisis de datos", "C) Usar solo para emails", "D) No integrar nunca"]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', '2025-01-15 10:00:00.000000+00', 'B) Integración gradual con APIs, automatización de tareas repetitivas y análisis de datos'),
('6008', 'C2', 'Cuestionario', 'Conocimiento', '2', '6', '¿Qué métrica es más importante para medir el impacto de Gen-AI en ventas?', 'Multiple Choice (una respuesta)', '["A) Número de prompts enviados", "B) Tiempo de respuesta a leads, tasa de conversión y valor promedio de venta", "C) Likes en LinkedIn", "D) Cantidad de reuniones"]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', '2025-01-15 10:00:00.000000+00', 'B) Tiempo de respuesta a leads, tasa de conversión y valor promedio de venta'),
('6009', 'C3', 'Cuestionario', 'Conocimiento', '2', '6', 'Para personalizar propuestas comerciales con Gen-AI, ¿qué es más importante?', 'Multiple Choice (una respuesta)', '["A) Usar prompts genéricos", "B) Datos específicos del cliente, historial de compras y necesidades identificadas", "C) Copiar de la competencia", "D) No personalizar"]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', '2025-01-15 10:00:00.000000+00', 'B) Datos específicos del cliente, historial de compras y necesidades identificadas'),
('6010', 'C4', 'Cuestionario', 'Conocimiento', '2', '6', '¿Cómo debe manejarse la información confidencial del cliente al usar Gen-AI?', 'Multiple Choice (una respuesta)', '["A) Subir todo a servicios públicos", "B) Minimizar datos sensibles, usar entornos seguros y cumplir con políticas de privacidad", "C) Compartir con la competencia", "D) No usar nunca"]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', '2025-01-15 10:00:00.000000+00', 'B) Minimizar datos sensibles, usar entornos seguros y cumplir con políticas de privacidad'),
('6011', 'C5', 'Cuestionario', 'Conocimiento', '2', '6', 'Para análisis predictivo de ventas con Gen-AI, ¿qué enfoque es más efectivo?', 'Multiple Choice (una respuesta)', '["A) Confiar ciegamente en las predicciones", "B) Combinar datos históricos, tendencias del mercado y validación humana", "C) Usar solo datos de un mes", "D) No hacer análisis predictivo"]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', '2025-01-15 10:00:00.000000+00', 'B) Combinar datos históricos, tendencias del mercado y validación humana'),
('6012', 'C6', 'Cuestionario', 'Conocimiento', '2', '6', '¿Cuál es la mejor práctica para automatizar procesos de ventas con Gen-AI?', 'Multiple Choice (una respuesta)', '["A) Automatizar todo sin supervisión", "B) Automatizar tareas repetitivas, mantener supervisión humana en decisiones críticas y medir resultados", "C) No automatizar nada", "D) Solo automatizar emails"]', 'MX/LATAM', '8.333333', null, '{"Correcta": 100, "Incorrecta": 0}', '2025-01-15 10:00:00.000000+00', 'B) Automatizar tareas repetitivas, mantener supervisión humana en decisiones críticas y medir resultados');

-- ==============================================
-- 6. VERIFICACIÓN
-- ==============================================
-- Verificar que se insertaron las preguntas correctamente
SELECT 
    exclusivo_rol_id,
    COUNT(*) as total_preguntas,
    COUNT(CASE WHEN bloque = 'Adopción' THEN 1 END) as adopcion,
    COUNT(CASE WHEN bloque = 'Conocimiento' THEN 1 END) as conocimiento
FROM "public"."preguntas" 
WHERE "section" = 'Cuestionario' 
    AND "exclusivo_rol_id" IN (1, 2, 3, 6)
GROUP BY "exclusivo_rol_id"
ORDER BY "exclusivo_rol_id";
