export const LEGAL_DOCUMENTS = {
  terms: {
    title: 'Términos y Condiciones de Uso',
    icon: 'FileText',
    sections: [
      {
        number: 1,
        title: 'Aceptación de los Términos',
        content:
          'Estos Términos y Condiciones de Uso ("Términos") constituyen un acuerdo legal entre usted ("Usuario", "usted" o "su") y SOFLIA ("nosotros", "nuestro" o "la Plataforma"). Al acceder, utilizar, registrarse o interactuar de cualquier manera con nuestra plataforma de capacitación en inteligencia artificial ubicada en nuestro sitio web (la "Plataforma"), usted acepta estar legalmente vinculado por estos Términos. Si no está de acuerdo con alguno de estos términos, no debe acceder ni utilizar nuestros servicios.',
      },
      {
        number: 2,
        title: 'Descripción del Servicio',
        content: 'SOFLIA es una plataforma educativa B2B que ofrece servicios de capacitación empresarial en inteligencia artificial, incluyendo pero no limitado a:',
        list: [
          'Cursos en línea de inteligencia artificial, machine learning y tecnologías relacionadas',
          'Contenido educativo interactivo, incluyendo videos, lecciones, materiales de estudio y recursos multimedia',
          'Sistema de evaluación y certificaciones verificables',
          'Comunidad de aprendizaje con foros, preguntas y respuestas, y colaboración entre usuarios',
          'Asistente virtual de IA (LIA) para apoyo educativo',
          'Planificador de estudios integrado con calendarios externos',
          'Gestión de equipos y reportes de progreso para organizaciones',
          'Sistema de noticias y artículos educativos',
          'Directorio de aplicaciones de IA',
          'Panel de administración para organizaciones con personalización de marca',
        ],
      },
      {
        number: 3,
        title: 'Elegibilidad y Registro de Cuenta',
        content: 'Para utilizar nuestros servicios, usted debe: (a) ser mayor de edad según las leyes de su jurisdicción (típicamente 18 años o más), (b) tener la capacidad legal para celebrar contratos vinculantes, (c) proporcionar información precisa y completa durante el registro, y (d) mantener la confidencialidad de sus credenciales de cuenta. Usted es responsable de todas las actividades que ocurran bajo su cuenta. Debe notificarnos inmediatamente de cualquier uso no autorizado de su cuenta.',
      },
      {
        number: 4,
        title: 'Uso Aceptable de la Plataforma',
        content: 'Usted acepta utilizar la Plataforma únicamente para fines legales y educativos, y de acuerdo con estos Términos. Específicamente, usted se compromete a:',
        list: [
          'Utilizar la Plataforma solo para su propósito educativo previsto',
          'No intentar acceder a áreas restringidas de la Plataforma o a cuentas de otros usuarios',
          'No realizar ingeniería inversa, descompilar o desensamblar cualquier parte de la Plataforma',
          'No introducir virus, malware, código malicioso o cualquier otro dispositivo dañino',
          'No realizar actividades de scraping, crawling o extracción automatizada de datos sin autorización previa',
          'No utilizar bots, scripts automatizados o sistemas que puedan sobrecargar nuestros servidores',
          'Respetar los derechos de propiedad intelectual de otros usuarios y de la Plataforma',
          'No compartir su cuenta con terceros',
          'No utilizar la Plataforma para actividades ilegales, fraudulentas o que violen derechos de terceros',
        ],
      },
      {
        number: 5,
        title: 'Contenido del Usuario',
        content: 'Usted conserva todos los derechos de propiedad sobre el contenido que cree, publique o comparta en la Plataforma ("Contenido del Usuario"). Sin embargo, al publicar contenido, usted nos otorga una licencia mundial, no exclusiva, libre de regalías, transferible y sublicenciable para usar, reproducir, distribuir, preparar trabajos derivados y mostrar dicho contenido en relación con la Plataforma y nuestros servicios. Usted es responsable de asegurar que su Contenido del Usuario no viole leyes aplicables, derechos de terceros o estos Términos.',
      },
      {
        number: 6,
        title: 'Propiedad Intelectual',
        content: 'Todos los derechos de propiedad intelectual sobre la Plataforma, incluyendo pero no limitado a textos, gráficos, logos, iconos, imágenes, clips de audio y video, software, compilaciones de datos, diseño, estructura y organización de la Plataforma, son propiedad de SOFLIA o de nuestros licenciantes y están protegidos por leyes de derechos de autor, marcas registradas, secretos comerciales y otras leyes de propiedad intelectual. No se otorgan licencias implícitas. Usted no puede reproducir, distribuir, modificar, crear trabajos derivados, mostrar públicamente, realizar públicamente, republicar, descargar, almacenar o transmitir ningún material de la Plataforma sin nuestro permiso previo por escrito.',
      },
      {
        number: 7,
        title: 'Suscripciones y Pagos',
        content: 'Algunos servicios de la Plataforma pueden requerir el pago de tarifas de suscripción. Los precios, términos de facturación y métodos de pago se especificarán durante el proceso de registro. Todas las tarifas son no reembolsables a menos que se indique lo contrario o sea requerido por ley aplicable. Nos reservamos el derecho de modificar nuestras tarifas con aviso previo de al menos 30 días. Las organizaciones que contraten planes Team, Business o Enterprise estarán sujetas a términos de servicio adicionales según el plan seleccionado.',
      },
      {
        number: 8,
        title: 'Integraciones con Calendarios y Servicios de Terceros',
        content: 'La Plataforma ofrece integración opcional con Google Calendar y Microsoft Outlook exclusivamente para optimizar su experiencia de planificación de estudios. Al autorizar esta integración, usted entiende y acepta que: (a) ÚNICAMENTE accedemos a información de disponibilidad (horarios ocupados/libres) y NO al contenido, títulos o detalles de sus eventos personales o de trabajo; (b) Esta información se utiliza exclusivamente para diseñar un plan de estudios personalizado que se adapte a sus horarios disponibles; (c) Ni SOFLIA ni Google/Microsoft recopilan información adicional más allá de lo estrictamente necesario para este propósito; (d) Puede revocar el acceso en cualquier momento desde la configuración de su cuenta.',
      },
      {
        number: 9,
        title: 'Privacidad y Protección de Datos',
        content: 'Su privacidad es importante para nosotros. Nuestro uso de su información personal está gobernado por nuestra Política de Privacidad, que forma parte integral de estos Términos. Al utilizar la Plataforma, usted consiente la recopilación, uso y divulgación de su información personal según se describe en nuestra Política de Privacidad. Cumplimos con la Ley Federal de Protección de Datos Personales en Posesión de los Particulares (LFPDPPP) de México, el Reglamento General de Protección de Datos (GDPR) de la Unión Europea, y otras leyes de protección de datos aplicables en Latinoamérica.',
      },
      {
        number: 10,
        title: 'Modificaciones del Servicio',
        content: 'Nos reservamos el derecho de modificar, suspender, interrumpir o discontinuar cualquier aspecto de la Plataforma en cualquier momento, con o sin previo aviso. Podemos realizar mejoras, cambios o actualizaciones a la Plataforma sin previo aviso. No seremos responsables ante usted ni ante terceros por cualquier modificación, suspensión o interrupción del servicio.',
      },
      {
        number: 11,
        title: 'Terminación',
        content: 'Podemos terminar o suspender su acceso a la Plataforma inmediatamente, sin previo aviso o responsabilidad, por cualquier motivo, incluyendo pero no limitado a una violación de estos Términos. Tras la terminación, su derecho a utilizar la Plataforma cesará inmediatamente. Todas las disposiciones de estos Términos que por su naturaleza deban sobrevivir a la terminación sobrevivirán a la terminación, incluyendo pero no limitado a disposiciones de propiedad, renuncias de garantía, indemnización y limitaciones de responsabilidad.',
      },
      {
        number: 12,
        title: 'Renuncia de Garantías',
        content: 'LA PLATAFORMA SE PROPORCIONA "TAL CUAL" Y "SEGÚN DISPONIBILIDAD" SIN GARANTÍAS DE NINGÚN TIPO, YA SEAN EXPRESAS O IMPLÍCITAS, INCLUYENDO PERO NO LIMITADO A GARANTÍAS IMPLÍCITAS DE COMERCIABILIDAD, IDONEIDAD PARA UN PROPÓSITO PARTICULAR Y NO VIOLACIÓN. NO GARANTIZAMOS QUE LA PLATAFORMA ESTÉ DISPONIBLE DE MANERA ININTERRUMPIDA O LIBRE DE ERRORES, QUE LOS DEFECTOS SERÁN CORREGIDOS, O QUE LA PLATAFORMA O EL SERVIDOR QUE LA HACE DISPONIBLE ESTÉN LIBRES DE VIRUS U OTROS COMPONENTES DAÑINOS.',
      },
      {
        number: 13,
        title: 'Limitación de Responsabilidad',
        content: 'EN NINGÚN CASO SEREMOS RESPONSABLES ANTE USTED O CUALQUIER TERCERO POR DAÑOS INDIRECTOS, INCIDENTALES, ESPECIALES, CONSECUENCIALES O PUNITIVOS, INCLUYENDO PERO NO LIMITADO A PÉRDIDA DE BENEFICIOS, PÉRDIDA DE DATOS, PÉRDIDA DE OPORTUNIDADES COMERCIALES, O DAÑOS A LA REPUTACIÓN, QUE SURJAN DE O ESTÉN RELACIONADOS CON EL USO O LA IMPOSIBILIDAD DE USAR LA PLATAFORMA, INCLUSO SI HEMOS SIDO ADVERTIDOS DE LA POSIBILIDAD DE TALES DAÑOS. NUESTRA RESPONSABILIDAD TOTAL ANTE USTED NO EXCEDERÁ EL MONTO QUE USTED HA PAGADO A NOSOTROS EN LOS ÚLTIMOS 12 MESES.',
      },
      {
        number: 14,
        title: 'Indemnización',
        content: 'Usted acepta indemnizar, defender y mantener indemnes a SOFLIA, sus afiliados, directores, empleados, agentes y licenciantes de y contra todas y cada una de las reclamaciones, daños, obligaciones, pérdidas, responsabilidades, costos o deudas, y gastos (incluidos pero no limitados a honorarios de abogados) que surjan de: (a) su uso e ingreso a la Plataforma, (b) su violación de cualquier término de estos Términos, (c) su violación de cualquier derecho de un tercero, incluidos sin limitación derechos de propiedad intelectual o privacidad, o (d) cualquier reclamación de que su Contenido del Usuario causó daño a un tercero.',
      },
      {
        number: 15,
        title: 'Ley Aplicable y Jurisdicción',
        content: 'Estos Términos se regirán e interpretarán de acuerdo con las leyes de los Estados Unidos Mexicanos, particularmente la Ley Federal de Protección de Datos Personales en Posesión de los Particulares (LFPDPPP) y su Reglamento. Cualquier disputa que surja de o esté relacionada con estos Términos será sometida a la jurisdicción exclusiva de los tribunales competentes de la Ciudad de México, México. Para usuarios de la Unión Europea, también cumplimos con el Reglamento General de Protección de Datos (GDPR). Si alguna disposición de estos Términos se considera inválida o inaplicable, las disposiciones restantes permanecerán en pleno vigor y efecto.',
      },
      {
        number: 16,
        title: 'Disposiciones Generales',
        content: 'Estos Términos constituyen el acuerdo completo entre usted y nosotros respecto del uso de la Plataforma y reemplazan todos los acuerdos, comunicaciones y entendimientos previos. No podemos transferir nuestros derechos u obligaciones bajo estos Términos sin su consentimiento. Usted no puede transferir sus derechos u obligaciones bajo estos Términos sin nuestro consentimiento previo por escrito. Nuestra omisión de hacer cumplir cualquier derecho o disposición de estos Términos no constituirá una renuncia a dicho derecho o disposición.',
      },
      {
        number: 17,
        title: 'Información de Contacto',
        content: 'Si tiene preguntas sobre estos Términos, puede contactarnos a través de nuestro sitio web o enviando un correo electrónico a nuestro equipo de soporte. Nos reservamos el derecho de actualizar estos Términos en cualquier momento. Le notificaremos de cambios materiales mediante un aviso prominente en la Plataforma o por correo electrónico. Su uso continuado de la Plataforma después de dichos cambios constituye su aceptación de los nuevos Términos.',
      },
    ],
  },
  privacy: {
    title: 'Política de Privacidad',
    icon: 'Shield',
    sections: [
      {
        number: 1,
        title: 'Introducción y Alcance',
        content:
          'Esta Política de Privacidad describe cómo SOFLIA ("nosotros", "nuestro" o "la Plataforma") recopila, utiliza, almacena, comparte y protege su información personal cuando utiliza nuestra plataforma de capacitación en inteligencia artificial. Esta política se aplica a todos los usuarios de nuestra Plataforma, incluyendo usuarios individuales y organizaciones. Al utilizar nuestros servicios, usted acepta las prácticas descritas en esta política. Esta Política de Privacidad cumple con la Ley Federal de Protección de Datos Personales en Posesión de los Particulares (LFPDPPP) de México, el Reglamento General de Protección de Datos (GDPR) de la Unión Europea, y demás legislaciones aplicables en Latinoamérica.',
      },
      {
        number: 2,
        title: 'Información que Recopilamos',
        content: 'Recopilamos diferentes tipos de información para proporcionar y mejorar nuestros servicios:',
        list: [
          'Información de Identificación Personal: Nombre completo, dirección de correo electrónico, número de teléfono, nombre de usuario, y cualquier otra información que proporcione voluntariamente durante el registro o al actualizar su perfil',
          'Información de Perfil: Foto de perfil, biografía, ubicación, cargo o rol profesional, y preferencias de privacidad',
          'Información de Autenticación: Credenciales de inicio de sesión (email y contraseña cifrada), tokens de sesión, e información de autenticación social (Google, Microsoft) cuando utiliza estos métodos',
          'Información Académica y de Progreso: Cursos inscritos, lecciones completadas, calificaciones, certificados obtenidos, tiempo de estudio, notas y marcadores, progreso en evaluaciones, habilidades desarrolladas, y estadísticas de aprendizaje',
          'Información de Uso de la Plataforma: Páginas visitadas, tiempo de permanencia, clics, búsquedas realizadas, interacciones con el asistente de IA (LIA), mensajes en comunidades, publicaciones, comentarios, y otras actividades en la plataforma',
          'Información de Dispositivo: Dirección IP, tipo de navegador, sistema operativo, tipo de dispositivo, y cookies',
          'Información de Organización (para usuarios B2B): Si es parte de una organización, recopilamos información sobre su organización, equipo, asignaciones de cursos, reportes de progreso, y configuraciones corporativas',
        ],
      },
      {
        number: 3,
        title: 'Integración con Calendarios - Uso Limitado de Datos',
        content: 'Cuando usted autoriza la integración con Google Calendar o Microsoft Outlook, es importante que comprenda exactamente qué información accedemos y cómo la utilizamos:',
        list: [
          'ÚNICAMENTE accedemos a información de disponibilidad (franjas horarias ocupadas/libres) para diseñar un plan de estudios personalizado que se adapte a sus horarios',
          'NO accedemos, leemos ni almacenamos el contenido, títulos, descripciones, asistentes o cualquier detalle de sus eventos personales o de trabajo',
          'NO almacenamos su información de calendario de forma permanente; solo consultamos disponibilidad en tiempo real cuando usted solicita crear o actualizar su plan de estudios',
          'Ni SOFLIA ni Google ni Microsoft recopilan información adicional de su calendario más allá de lo estrictamente necesario para verificar horarios disponibles',
          'Puede revocar el acceso a su calendario en cualquier momento desde la configuración de su cuenta, sin que esto afecte el resto de funcionalidades de la plataforma',
          'Esta integración cumple con las políticas de uso de datos de Google y Microsoft, así como con la Ley Federal de Protección de Datos Personales en Posesión de los Particulares (LFPDPPP)',
        ],
      },
      {
        number: 4,
        title: 'Cómo Utilizamos su Información',
        content: 'Utilizamos la información recopilada para los siguientes propósitos:',
        list: [
          'Provisión de Servicios: Proporcionar, mantener y mejorar nuestros servicios educativos, procesar registros y transacciones, gestionar su cuenta y autenticación, y entregar contenido personalizado',
          'Personalización: Personalizar su experiencia de aprendizaje, recomendar cursos relevantes, adaptar el contenido a sus necesidades, y crear planes de estudio optimizados según su disponibilidad',
          'Comunicación: Enviar notificaciones sobre su progreso, actualizaciones del curso, recordatorios, mensajes de la comunidad, y comunicaciones importantes del servicio. Puede optar por no recibir comunicaciones de marketing',
          'Análisis y Mejora: Analizar el uso de la plataforma para mejorar nuestros servicios, desarrollar nuevas características, y entender las tendencias de uso',
          'Seguridad: Detectar, prevenir y abordar fraudes, abusos, actividades ilegales, y proteger la seguridad de nuestra plataforma y usuarios',
          'Soporte al Cliente: Responder a sus consultas, proporcionar asistencia técnica, resolver problemas, y mejorar nuestro servicio al cliente',
          'Cumplimiento Legal: Cumplir con obligaciones legales según la LFPDPPP, GDPR y demás normativas aplicables',
          'Reportes para Organizaciones: Para usuarios B2B, generar reportes de progreso y análisis de equipo para administradores de la organización',
        ],
      },
      {
        number: 5,
        title: 'Asistente Virtual LIA',
        content: 'SOFLIA incluye un asistente virtual de inteligencia artificial llamado LIA que utiliza tecnología de Google Gemini. Respecto a LIA:',
        list: [
          'LIA procesa sus consultas para proporcionar asistencia educativa, recomendaciones de cursos y apoyo en su aprendizaje',
          'Las conversaciones con LIA pueden ser almacenadas para mejorar la calidad del servicio y personalizar futuras interacciones',
          'LIA tiene acceso al contexto de su progreso educativo dentro de la plataforma para brindar respuestas relevantes',
          'No compartimos el contenido de sus conversaciones con LIA con terceros para fines publicitarios o de marketing',
          'Puede solicitar la eliminación de su historial de conversaciones con LIA en cualquier momento',
        ],
      },
      {
        number: 6,
        title: 'Base Legal para el Procesamiento',
        content: 'Procesamos su información personal basándonos en las siguientes bases legales conforme a la LFPDPPP (México) y el GDPR (Europa):',
        list: [
          'Consentimiento: Cuando usted ha dado su consentimiento claro para el procesamiento de sus datos personales para uno o más fines específicos',
          'Ejecución de Contrato: Cuando el procesamiento es necesario para la ejecución de un contrato del que usted es parte',
          'Obligación Legal: Cuando el procesamiento es necesario para cumplir con una obligación legal',
          'Intereses Legítimos: Cuando el procesamiento es necesario para nuestros intereses legítimos, excepto cuando dichos intereses estén anulados por sus derechos fundamentales',
        ],
      },
      {
        number: 7,
        title: 'Compartir y Divulgación de Información',
        content: 'No vendemos su información personal. Compartimos información únicamente en las siguientes circunstancias:',
        list: [
          'Proveedores de Servicios: Compartimos información con proveedores de servicios de confianza que nos ayudan a operar nuestra plataforma, incluyendo servicios de almacenamiento en la nube, servicios de email, y procesamiento de pagos. Todos estos proveedores están contractualmente obligados a proteger su información conforme a la LFPDPPP',
          'Integraciones Autorizadas: Si autoriza integraciones (como Google Calendar o Microsoft Calendar), accedemos únicamente a información de disponibilidad según sus permisos explícitos, sin ver el contenido de sus eventos',
          'Organizaciones (B2B): Si es parte de una organización cliente, su información de progreso y actividad puede ser visible para administradores autorizados de su organización',
          'Cumplimiento Legal: Podemos divulgar información si es requerido por ley, orden judicial, o proceso legal según la legislación mexicana o internacional aplicable',
          'Con su Consentimiento: Podemos compartir información en otras circunstancias con su consentimiento explícito',
        ],
      },
      {
        number: 8,
        title: 'Cookies y Tecnologías de Seguimiento',
        content: 'Utilizamos cookies y tecnologías similares para mejorar su experiencia, analizar el uso y personalizar contenido:',
        list: [
          'Cookies Esenciales: Necesarias para el funcionamiento de la plataforma (autenticación, seguridad, sesión)',
          'Cookies de Funcionalidad: Recuerdan sus preferencias y configuraciones (tema claro/oscuro, idioma preferido)',
          'Cookies Analíticas: Nos ayudan a entender cómo los usuarios interactúan con nuestra plataforma. Puede optar por no participar en el seguimiento analítico',
        ],
      },
      {
        number: 9,
        title: 'Seguridad de Datos',
        content: 'Implementamos medidas de seguridad robustas para proteger su información personal:',
        list: [
          'Cifrado: Utilizamos cifrado para datos en tránsito y datos sensibles en reposo',
          'Almacenamiento Seguro: Sus datos se almacenan en servidores seguros con controles de acceso estrictos',
          'Autenticación: Requerimos autenticación segura con contraseñas cifradas y soporte para autenticación social',
          'Control de Acceso: Implementamos controles de acceso basados en roles para garantizar que solo personal autorizado acceda a la información necesaria',
          'Monitoreo: Monitoreamos continuamente nuestros sistemas para detectar y responder a amenazas de seguridad',
        ],
      },
      {
        number: 10,
        title: 'Sus Derechos ARCO (México) y GDPR (Europa)',
        content: 'Conforme a la Ley Federal de Protección de Datos Personales en Posesión de los Particulares (LFPDPPP) de México y el GDPR europeo, usted tiene los siguientes derechos:',
        list: [
          'Derecho de Acceso: Puede solicitar una copia de la información personal que tenemos sobre usted',
          'Derecho de Rectificación: Puede corregir información inexacta o incompleta',
          'Derecho de Cancelación/Eliminación: Puede solicitar que eliminemos su información personal, sujeto a ciertas excepciones legales',
          'Derecho de Oposición: Puede oponerse al procesamiento de su información personal en ciertas circunstancias',
          'Derecho a la Portabilidad de Datos: Puede solicitar que transfiramos sus datos en un formato estructurado',
          'Derecho de Retirar Consentimiento: Si el procesamiento se basa en consentimiento, puede retirarlo en cualquier momento',
          'Para ejercer estos derechos, puede contactarnos a través de los medios indicados en esta política. Responderemos a su solicitud dentro de los plazos establecidos por la ley aplicable (20 días hábiles para LFPDPPP, 30 días para GDPR)',
        ],
      },
      {
        number: 11,
        title: 'Privacidad de Menores',
        content: 'Nuestros servicios no están dirigidos a menores de 18 años. No recopilamos intencionalmente información personal de menores de 18 años sin el consentimiento verificable de los padres o tutores, conforme a la legislación mexicana de protección de menores y el GDPR. Si descubrimos que hemos recopilado información de un menor sin el consentimiento adecuado, tomaremos medidas para eliminar esa información de nuestros servidores.',
      },
      {
        number: 12,
        title: 'Transferencias Internacionales de Datos',
        content: 'Su información puede ser transferida y procesada en países distintos al suyo. Cuando transferimos datos internacionalmente, implementamos salvaguardias apropiadas para garantizar que su información personal reciba un nivel adecuado de protección conforme a la LFPDPPP de México, el GDPR de la Unión Europea, y demás legislaciones aplicables en Latinoamérica.',
      },
      {
        number: 13,
        title: 'Retención de Datos',
        content: 'Conservamos su información personal durante el tiempo necesario para cumplir con los propósitos descritos en esta política, a menos que la ley requiera o permita un período de retención más largo. Cuando ya no necesitemos su información personal, la eliminaremos o anonimizaremos de manera segura. Para cuentas activas, conservamos la información mientras su cuenta esté activa y durante un período razonable después para cumplir con obligaciones legales.',
      },
      {
        number: 14,
        title: 'Cambios a esta Política de Privacidad',
        content: 'Podemos actualizar esta Política de Privacidad periódicamente para reflejar cambios en nuestras prácticas o por razones operativas, legales o regulatorias. Le notificaremos de cambios materiales mediante un aviso prominente en nuestra plataforma o por correo electrónico antes de que los cambios entren en vigor. Su uso continuado de nuestros servicios después de dichos cambios constituye su aceptación de la política revisada.',
      },
      {
        number: 15,
        title: 'Información de Contacto y Ejercicio de Derechos',
        content: 'Si tiene preguntas, inquietudes o solicitudes relacionadas con esta Política de Privacidad o desea ejercer sus derechos ARCO (Acceso, Rectificación, Cancelación y Oposición), puede contactarnos a través de: (a) nuestro sitio web en la sección de contacto, (b) enviando un correo electrónico a nuestro equipo de privacidad. Responderemos a su solicitud dentro de los plazos requeridos por la ley aplicable.',
      },
    ],
  },
  conduct: {
    title: 'Código de Conducta',
    icon: 'Users',
    sections: [
      {
        number: 1,
        title: 'Comportamiento Esperado',
        content: 'Nuestra comunidad se basa en el respeto mutuo, la colaboración y el aprendizaje constructivo. Todos los usuarios deben:',
        list: [
          'Tratar a todos los miembros de la comunidad con respeto, cortesía y dignidad, independientemente de su origen, género, orientación sexual, religión, nivel de experiencia o cualquier otra característica personal',
          'Contribuir de manera constructiva a discusiones, compartir conocimientos de manera útil y participar activamente en el aprendizaje colaborativo',
          'Respetar la propiedad intelectual de otros, citando apropiadamente fuentes y no plagiar contenido',
          'Mantener un ambiente de aprendizaje positivo, constructivo y acogedor para todos',
          'Comunicarse de manera profesional y educada en todos los espacios de la comunidad',
          'Reportar comportamiento inapropiado cuando sea necesario',
        ],
      },
      {
        number: 2,
        title: 'Comportamiento Prohibido',
        content: 'Los siguientes comportamientos están estrictamente prohibidos y pueden resultar en acción disciplinaria inmediata:',
        list: [
          'Acoso, intimidación, discriminación, hostigamiento o comportamiento abusivo hacia otros usuarios',
          'Publicar contenido ofensivo, inapropiado, difamatorio, obsceno, pornográfico, violento o que promueva actividades ilegales',
          'Hacer spam, publicidad no autorizada, o promover productos o servicios sin permiso',
          'Compartir información falsa, engañosa, o desinformación intencional',
          'Suplantar la identidad de otra persona, organización o entidad',
          'Acceder no autorizado a cuentas, sistemas o datos de otros usuarios',
          'Realizar actividades que violen derechos de propiedad intelectual o confidencialidad',
          'Manipular o intentar comprometer la seguridad de la plataforma',
          'Publicar información personal de otros usuarios sin su consentimiento',
          'Cualquier actividad que viole leyes aplicables o regulaciones',
        ],
      },
      {
        number: 3,
        title: 'Consecuencias del Incumplimiento',
        content: 'El incumplimiento de este Código de Conducta puede resultar en acciones disciplinarias, que pueden incluir:',
        list: [
          'Advertencia formal por escrito',
          'Eliminación de contenido inapropiado',
          'Suspensión temporal de la cuenta con duración determinada',
          'Suspensión permanente de la cuenta y prohibición del uso de nuestros servicios',
          'Reporte a autoridades legales si el comportamiento viola leyes aplicables',
          'Medidas legales adicionales según sea necesario para proteger nuestros usuarios y servicios',
        ],
      },
      {
        number: 4,
        title: 'Proceso de Reporte',
        content: 'Si experimenta o presencia comportamiento que viola este Código de Conducta, le animamos a reportarlo de inmediato utilizando las herramientas de reporte en la plataforma o contactando directamente a nuestro equipo de moderación. Todos los reportes serán revisados de manera confidencial y se tomarán medidas apropiadas.',
      },
    ],
  },
};
