export const LEGAL_DOCUMENTS = {
  terms: {
    title: 'TÃ©rminos y Condiciones de Uso',
    icon: 'FileText',
    sections: [
      {
        number: 1,
        title: 'AceptaciÃ³n de los TÃ©rminos',
        content:
          'Estos TÃ©rminos y Condiciones de Uso ("TÃ©rminos") constituyen un acuerdo legal entre usted ("Usuario", "usted" o "su") y SOFLIA ("nosotros", "nuestro" o "la Plataforma"). Al acceder, utilizar, registrarse o interactuar de cualquier manera con nuestra plataforma de capacitaciÃ³n en inteligencia artificial ubicada en nuestro sitio web (la "Plataforma"), usted acepta estar legalmente vinculado por estos TÃ©rminos. Si no estÃ¡ de acuerdo con alguno de estos tÃ©rminos, no debe acceder ni utilizar nuestros servicios.',
      },
      {
        number: 2,
        title: 'DescripciÃ³n del Servicio',
        content: 'SOFLIA es una plataforma educativa B2B que ofrece servicios de capacitaciÃ³n empresarial en inteligencia artificial, incluyendo pero no limitado a:',
        list: [
          'Cursos en lÃ­nea de inteligencia artificial, machine learning y tecnologÃ­as relacionadas',
          'Contenido educativo interactivo, incluyendo videos, lecciones, materiales de estudio y recursos multimedia',
          'Sistema de evaluaciÃ³n y certificaciones verificables',
          'Comunidad de aprendizaje con foros, preguntas y respuestas, y colaboraciÃ³n entre usuarios',
          'Asistente virtual de IA (LIA) para apoyo educativo',
          'Planificador de estudios integrado con calendarios externos',
          'GestiÃ³n de equipos y reportes de progreso para organizaciones',
          'Sistema de noticias y artÃ­culos educativos',
          'Directorio de aplicaciones de IA',
          'Panel de administraciÃ³n para organizaciones con personalizaciÃ³n de marca',
        ],
      },
      {
        number: 3,
        title: 'Elegibilidad y Registro de Cuenta',
        content: 'Para utilizar nuestros servicios, usted debe: (a) ser mayor de edad segÃºn las leyes de su jurisdicciÃ³n (tÃ­picamente 18 aÃ±os o mÃ¡s), (b) tener la capacidad legal para celebrar contratos vinculantes, (c) proporcionar informaciÃ³n precisa y completa durante el registro, y (d) mantener la confidencialidad de sus credenciales de cuenta. Usted es responsable de todas las actividades que ocurran bajo su cuenta. Debe notificarnos inmediatamente de cualquier uso no autorizado de su cuenta.',
      },
      {
        number: 4,
        title: 'Uso Aceptable de la Plataforma',
        content: 'Usted acepta utilizar la Plataforma Ãºnicamente para fines legales y educativos, y de acuerdo con estos TÃ©rminos. EspecÃ­ficamente, usted se compromete a:',
        list: [
          'Utilizar la Plataforma solo para su propÃ³sito educativo previsto',
          'No intentar acceder a Ã¡reas restringidas de la Plataforma o a cuentas de otros usuarios',
          'No realizar ingenierÃ­a inversa, descompilar o desensamblar cualquier parte de la Plataforma',
          'No introducir virus, malware, cÃ³digo malicioso o cualquier otro dispositivo daÃ±ino',
          'No realizar actividades de scraping, crawling o extracciÃ³n automatizada de datos sin autorizaciÃ³n previa',
          'No utilizar bots, scripts automatizados o sistemas que puedan sobrecargar nuestros servidores',
          'Respetar los derechos de propiedad intelectual de otros usuarios y de la Plataforma',
          'No compartir su cuenta con terceros',
          'No utilizar la Plataforma para actividades ilegales, fraudulentas o que violen derechos de terceros',
        ],
      },
      {
        number: 5,
        title: 'Contenido del Usuario',
        content: 'Usted conserva todos los derechos de propiedad sobre el contenido que cree, publique o comparta en la Plataforma ("Contenido del Usuario"). Sin embargo, al publicar contenido, usted nos otorga una licencia mundial, no exclusiva, libre de regalÃ­as, transferible y sublicenciable para usar, reproducir, distribuir, preparar trabajos derivados y mostrar dicho contenido en relaciÃ³n con la Plataforma y nuestros servicios. Usted es responsable de asegurar que su Contenido del Usuario no viole leyes aplicables, derechos de terceros o estos TÃ©rminos.',
      },
      {
        number: 6,
        title: 'Propiedad Intelectual',
        content: 'Todos los derechos de propiedad intelectual sobre la Plataforma, incluyendo pero no limitado a textos, grÃ¡ficos, logos, iconos, imÃ¡genes, clips de audio y video, software, compilaciones de datos, diseÃ±o, estructura y organizaciÃ³n de la Plataforma, son propiedad de SOFLIA o de nuestros licenciantes y estÃ¡n protegidos por leyes de derechos de autor, marcas registradas, secretos comerciales y otras leyes de propiedad intelectual. No se otorgan licencias implÃ­citas. Usted no puede reproducir, distribuir, modificar, crear trabajos derivados, mostrar pÃºblicamente, realizar pÃºblicamente, republicar, descargar, almacenar o transmitir ningÃºn material de la Plataforma sin nuestro permiso previo por escrito.',
      },
      {
        number: 7,
        title: 'Suscripciones y Pagos',
        content: 'Algunos servicios de la Plataforma pueden requerir el pago de tarifas de suscripciÃ³n. Los precios, tÃ©rminos de facturaciÃ³n y mÃ©todos de pago se especificarÃ¡n durante el proceso de registro. Todas las tarifas son no reembolsables a menos que se indique lo contrario o sea requerido por ley aplicable. Nos reservamos el derecho de modificar nuestras tarifas con aviso previo de al menos 30 dÃ­as. Las organizaciones que contraten planes Team, Business o Enterprise estarÃ¡n sujetas a tÃ©rminos de servicio adicionales segÃºn el plan seleccionado.',
      },
      {
        number: 8,
        title: 'Integraciones con Calendarios y Servicios de Terceros',
        content: 'La Plataforma ofrece integraciÃ³n opcional con Google Calendar y Microsoft Outlook exclusivamente para optimizar su experiencia de planificaciÃ³n de estudios. Al autorizar esta integraciÃ³n, usted entiende y acepta que: (a) ÃšNICAMENTE accedemos a informaciÃ³n de disponibilidad (horarios ocupados/libres) y NO al contenido, tÃ­tulos o detalles de sus eventos personales o de trabajo; (b) Esta informaciÃ³n se utiliza exclusivamente para diseÃ±ar un plan de estudios personalizado que se adapte a sus horarios disponibles; (c) Ni SOFLIA ni Google/Microsoft recopilan informaciÃ³n adicional mÃ¡s allÃ¡ de lo estrictamente necesario para este propÃ³sito; (d) Puede revocar el acceso en cualquier momento desde la configuraciÃ³n de su cuenta.',
      },
      {
        number: 9,
        title: 'Privacidad y ProtecciÃ³n de Datos',
        content: 'Su privacidad es importante para nosotros. Nuestro uso de su informaciÃ³n personal estÃ¡ gobernado por nuestra PolÃ­tica de Privacidad, que forma parte integral de estos TÃ©rminos. Al utilizar la Plataforma, usted consiente la recopilaciÃ³n, uso y divulgaciÃ³n de su informaciÃ³n personal segÃºn se describe en nuestra PolÃ­tica de Privacidad. Cumplimos con la Ley Federal de ProtecciÃ³n de Datos Personales en PosesiÃ³n de los Particulares (LFPDPPP) de MÃ©xico, el Reglamento General de ProtecciÃ³n de Datos (GDPR) de la UniÃ³n Europea, y otras leyes de protecciÃ³n de datos aplicables en LatinoamÃ©rica.',
      },
      {
        number: 10,
        title: 'Modificaciones del Servicio',
        content: 'Nos reservamos el derecho de modificar, suspender, interrumpir o discontinuar cualquier aspecto de la Plataforma en cualquier momento, con o sin previo aviso. Podemos realizar mejoras, cambios o actualizaciones a la Plataforma sin previo aviso. No seremos responsables ante usted ni ante terceros por cualquier modificaciÃ³n, suspensiÃ³n o interrupciÃ³n del servicio.',
      },
      {
        number: 11,
        title: 'TerminaciÃ³n',
        content: 'Podemos terminar o suspender su acceso a la Plataforma inmediatamente, sin previo aviso o responsabilidad, por cualquier motivo, incluyendo pero no limitado a una violaciÃ³n de estos TÃ©rminos. Tras la terminaciÃ³n, su derecho a utilizar la Plataforma cesarÃ¡ inmediatamente. Todas las disposiciones de estos TÃ©rminos que por su naturaleza deban sobrevivir a la terminaciÃ³n sobrevivirÃ¡n a la terminaciÃ³n, incluyendo pero no limitado a disposiciones de propiedad, renuncias de garantÃ­a, indemnizaciÃ³n y limitaciones de responsabilidad.',
      },
      {
        number: 12,
        title: 'Renuncia de GarantÃ­as',
        content: 'LA PLATAFORMA SE PROPORCIONA "TAL CUAL" Y "SEGÃšN DISPONIBILIDAD" SIN GARANTÃAS DE NINGÃšN TIPO, YA SEAN EXPRESAS O IMPLÃCITAS, INCLUYENDO PERO NO LIMITADO A GARANTÃAS IMPLÃCITAS DE COMERCIABILIDAD, IDONEIDAD PARA UN PROPÃ“SITO PARTICULAR Y NO VIOLACIÃ“N. NO GARANTIZAMOS QUE LA PLATAFORMA ESTÃ‰ DISPONIBLE DE MANERA ININTERRUMPIDA O LIBRE DE ERRORES, QUE LOS DEFECTOS SERÃN CORREGIDOS, O QUE LA PLATAFORMA O EL SERVIDOR QUE LA HACE DISPONIBLE ESTÃ‰N LIBRES DE VIRUS U OTROS COMPONENTES DAÃ‘INOS.',
      },
      {
        number: 13,
        title: 'LimitaciÃ³n de Responsabilidad',
        content: 'EN NINGÃšN CASO SEREMOS RESPONSABLES ANTE USTED O CUALQUIER TERCERO POR DAÃ‘OS INDIRECTOS, INCIDENTALES, ESPECIALES, CONSECUENCIALES O PUNITIVOS, INCLUYENDO PERO NO LIMITADO A PÃ‰RDIDA DE BENEFICIOS, PÃ‰RDIDA DE DATOS, PÃ‰RDIDA DE OPORTUNIDADES COMERCIALES, O DAÃ‘OS A LA REPUTACIÃ“N, QUE SURJAN DE O ESTÃ‰N RELACIONADOS CON EL USO O LA IMPOSIBILIDAD DE USAR LA PLATAFORMA, INCLUSO SI HEMOS SIDO ADVERTIDOS DE LA POSIBILIDAD DE TALES DAÃ‘OS. NUESTRA RESPONSABILIDAD TOTAL ANTE USTED NO EXCEDERÃ EL MONTO QUE USTED HA PAGADO A NOSOTROS EN LOS ÃšLTIMOS 12 MESES.',
      },
      {
        number: 14,
        title: 'IndemnizaciÃ³n',
        content: 'Usted acepta indemnizar, defender y mantener indemnes a SOFLIA, sus afiliados, directores, empleados, agentes y licenciantes de y contra todas y cada una de las reclamaciones, daÃ±os, obligaciones, pÃ©rdidas, responsabilidades, costos o deudas, y gastos (incluidos pero no limitados a honorarios de abogados) que surjan de: (a) su uso e ingreso a la Plataforma, (b) su violaciÃ³n de cualquier tÃ©rmino de estos TÃ©rminos, (c) su violaciÃ³n de cualquier derecho de un tercero, incluidos sin limitaciÃ³n derechos de propiedad intelectual o privacidad, o (d) cualquier reclamaciÃ³n de que su Contenido del Usuario causÃ³ daÃ±o a un tercero.',
      },
      {
        number: 15,
        title: 'Ley Aplicable y JurisdicciÃ³n',
        content: 'Estos TÃ©rminos se regirÃ¡n e interpretarÃ¡n de acuerdo con las leyes de los Estados Unidos Mexicanos, particularmente la Ley Federal de ProtecciÃ³n de Datos Personales en PosesiÃ³n de los Particulares (LFPDPPP) y su Reglamento. Cualquier disputa que surja de o estÃ© relacionada con estos TÃ©rminos serÃ¡ sometida a la jurisdicciÃ³n exclusiva de los tribunales competentes de la Ciudad de MÃ©xico, MÃ©xico. Para usuarios de la UniÃ³n Europea, tambiÃ©n cumplimos con el Reglamento General de ProtecciÃ³n de Datos (GDPR). Si alguna disposiciÃ³n de estos TÃ©rminos se considera invÃ¡lida o inaplicable, las disposiciones restantes permanecerÃ¡n en pleno vigor y efecto.',
      },
      {
        number: 16,
        title: 'Disposiciones Generales',
        content: 'Estos TÃ©rminos constituyen el acuerdo completo entre usted y nosotros respecto del uso de la Plataforma y reemplazan todos los acuerdos, comunicaciones y entendimientos previos. No podemos transferir nuestros derechos u obligaciones bajo estos TÃ©rminos sin su consentimiento. Usted no puede transferir sus derechos u obligaciones bajo estos TÃ©rminos sin nuestro consentimiento previo por escrito. Nuestra omisiÃ³n de hacer cumplir cualquier derecho o disposiciÃ³n de estos TÃ©rminos no constituirÃ¡ una renuncia a dicho derecho o disposiciÃ³n.',
      },
      {
        number: 17,
        title: 'InformaciÃ³n de Contacto',
        content: 'Si tiene preguntas sobre estos TÃ©rminos, puede contactarnos a travÃ©s de nuestro sitio web o enviando un correo electrÃ³nico a nuestro equipo de soporte. Nos reservamos el derecho de actualizar estos TÃ©rminos en cualquier momento. Le notificaremos de cambios materiales mediante un aviso prominente en la Plataforma o por correo electrÃ³nico. Su uso continuado de la Plataforma despuÃ©s de dichos cambios constituye su aceptaciÃ³n de los nuevos TÃ©rminos.',
      },
    ],
  },
  privacy: {
    title: 'PolÃ­tica de Privacidad',
    icon: 'Shield',
    sections: [
      {
        number: 1,
        title: 'IntroducciÃ³n y Alcance',
        content:
          'Esta PolÃ­tica de Privacidad describe cÃ³mo SOFLIA ("nosotros", "nuestro" o "la Plataforma") recopila, utiliza, almacena, comparte y protege su informaciÃ³n personal cuando utiliza nuestra plataforma de capacitaciÃ³n en inteligencia artificial. Esta polÃ­tica se aplica a todos los usuarios de nuestra Plataforma, incluyendo usuarios individuales y organizaciones. Al utilizar nuestros servicios, usted acepta las prÃ¡cticas descritas en esta polÃ­tica. Esta PolÃ­tica de Privacidad cumple con la Ley Federal de ProtecciÃ³n de Datos Personales en PosesiÃ³n de los Particulares (LFPDPPP) de MÃ©xico, el Reglamento General de ProtecciÃ³n de Datos (GDPR) de la UniÃ³n Europea, y demÃ¡s legislaciones aplicables en LatinoamÃ©rica.',
      },
      {
        number: 2,
        title: 'InformaciÃ³n que Recopilamos',
        content: 'Recopilamos diferentes tipos de informaciÃ³n para proporcionar y mejorar nuestros servicios:',
        list: [
          'InformaciÃ³n de IdentificaciÃ³n Personal: Nombre completo, direcciÃ³n de correo electrÃ³nico, nÃºmero de telÃ©fono, nombre de usuario, y cualquier otra informaciÃ³n que proporcione voluntariamente durante el registro o al actualizar su perfil',
          'InformaciÃ³n de Perfil: Foto de perfil, biografÃ­a, ubicaciÃ³n, cargo o rol profesional, y preferencias de privacidad',
          'InformaciÃ³n de AutenticaciÃ³n: Credenciales de inicio de sesiÃ³n (email y contraseÃ±a cifrada), tokens de sesiÃ³n, e informaciÃ³n de autenticaciÃ³n social (Google, Microsoft) cuando utiliza estos mÃ©todos',
          'InformaciÃ³n AcadÃ©mica y de Progreso: Cursos inscritos, lecciones completadas, calificaciones, certificados obtenidos, tiempo de estudio, notas y marcadores, progreso en evaluaciones, habilidades desarrolladas, y estadÃ­sticas de aprendizaje',
          'InformaciÃ³n de Uso de la Plataforma: PÃ¡ginas visitadas, tiempo de permanencia, clics, bÃºsquedas realizadas, interacciones con el asistente de IA (LIA), mensajes en comunidades, publicaciones, comentarios, y otras actividades en la plataforma',
          'InformaciÃ³n de Dispositivo: DirecciÃ³n IP, tipo de navegador, sistema operativo, tipo de dispositivo, y cookies',
          'InformaciÃ³n de OrganizaciÃ³n (para usuarios B2B): Si es parte de una organizaciÃ³n, recopilamos informaciÃ³n sobre su organizaciÃ³n, equipo, asignaciones de cursos, reportes de progreso, y configuraciones corporativas',
        ],
      },
      {
        number: 3,
        title: 'IntegraciÃ³n con Calendarios - Uso Limitado de Datos',
        content: 'Cuando usted autoriza la integraciÃ³n con Google Calendar o Microsoft Outlook, es importante que comprenda exactamente quÃ© informaciÃ³n accedemos y cÃ³mo la utilizamos:',
        list: [
          'ÃšNICAMENTE accedemos a informaciÃ³n de disponibilidad (franjas horarias ocupadas/libres) para diseÃ±ar un plan de estudios personalizado que se adapte a sus horarios',
          'NO accedemos, leemos ni almacenamos el contenido, tÃ­tulos, descripciones, asistentes o cualquier detalle de sus eventos personales o de trabajo',
          'NO almacenamos su informaciÃ³n de calendario de forma permanente; solo consultamos disponibilidad en tiempo real cuando usted solicita crear o actualizar su plan de estudios',
          'Ni SOFLIA ni Google ni Microsoft recopilan informaciÃ³n adicional de su calendario mÃ¡s allÃ¡ de lo estrictamente necesario para verificar horarios disponibles',
          'Puede revocar el acceso a su calendario en cualquier momento desde la configuraciÃ³n de su cuenta, sin que esto afecte el resto de funcionalidades de la plataforma',
          'Esta integraciÃ³n cumple con las polÃ­ticas de uso de datos de Google y Microsoft, asÃ­ como con la Ley Federal de ProtecciÃ³n de Datos Personales en PosesiÃ³n de los Particulares (LFPDPPP)',
        ],
      },
      {
        number: 4,
        title: 'CÃ³mo Utilizamos su InformaciÃ³n',
        content: 'Utilizamos la informaciÃ³n recopilada para los siguientes propÃ³sitos:',
        list: [
          'ProvisiÃ³n de Servicios: Proporcionar, mantener y mejorar nuestros servicios educativos, procesar registros y transacciones, gestionar su cuenta y autenticaciÃ³n, y entregar contenido personalizado',
          'PersonalizaciÃ³n: Personalizar su experiencia de aprendizaje, recomendar cursos relevantes, adaptar el contenido a sus necesidades, y crear planes de estudio optimizados segÃºn su disponibilidad',
          'ComunicaciÃ³n: Enviar notificaciones sobre su progreso, actualizaciones del curso, recordatorios, mensajes de la comunidad, y comunicaciones importantes del servicio. Puede optar por no recibir comunicaciones de marketing',
          'AnÃ¡lisis y Mejora: Analizar el uso de la plataforma para mejorar nuestros servicios, desarrollar nuevas caracterÃ­sticas, y entender las tendencias de uso',
          'Seguridad: Detectar, prevenir y abordar fraudes, abusos, actividades ilegales, y proteger la seguridad de nuestra plataforma y usuarios',
          'Soporte al Cliente: Responder a sus consultas, proporcionar asistencia tÃ©cnica, resolver problemas, y mejorar nuestro servicio al cliente',
          'Cumplimiento Legal: Cumplir con obligaciones legales segÃºn la LFPDPPP, GDPR y demÃ¡s normativas aplicables',
          'Reportes para Organizaciones: Para usuarios B2B, generar reportes de progreso y anÃ¡lisis de equipo para administradores de la organizaciÃ³n',
        ],
      },
      {
        number: 5,
        title: 'Asistente Virtual LIA',
        content: 'SOFLIA incluye un asistente virtual de inteligencia artificial llamado LIA que utiliza tecnologÃ­a de Google Gemini. Respecto a LIA:',
        list: [
          'LIA procesa sus consultas para proporcionar asistencia educativa, recomendaciones de cursos y apoyo en su aprendizaje',
          'Las conversaciones con LIA pueden ser almacenadas para mejorar la calidad del servicio y personalizar futuras interacciones',
          'LIA tiene acceso al contexto de su progreso educativo dentro de la plataforma para brindar respuestas relevantes',
          'No compartimos el contenido de sus conversaciones con LIA con terceros para fines publicitarios o de marketing',
          'Puede solicitar la eliminaciÃ³n de su historial de conversaciones con LIA en cualquier momento',
        ],
      },
      {
        number: 6,
        title: 'Base Legal para el Procesamiento',
        content: 'Procesamos su informaciÃ³n personal basÃ¡ndonos en las siguientes bases legales conforme a la LFPDPPP (MÃ©xico) y el GDPR (Europa):',
        list: [
          'Consentimiento: Cuando usted ha dado su consentimiento claro para el procesamiento de sus datos personales para uno o mÃ¡s fines especÃ­ficos',
          'EjecuciÃ³n de Contrato: Cuando el procesamiento es necesario para la ejecuciÃ³n de un contrato del que usted es parte',
          'ObligaciÃ³n Legal: Cuando el procesamiento es necesario para cumplir con una obligaciÃ³n legal',
          'Intereses LegÃ­timos: Cuando el procesamiento es necesario para nuestros intereses legÃ­timos, excepto cuando dichos intereses estÃ©n anulados por sus derechos fundamentales',
        ],
      },
      {
        number: 7,
        title: 'Compartir y DivulgaciÃ³n de InformaciÃ³n',
        content: 'No vendemos su informaciÃ³n personal. Compartimos informaciÃ³n Ãºnicamente en las siguientes circunstancias:',
        list: [
          'Proveedores de Servicios: Compartimos informaciÃ³n con proveedores de servicios de confianza que nos ayudan a operar nuestra plataforma, incluyendo servicios de almacenamiento en la nube, servicios de email, y procesamiento de pagos. Todos estos proveedores estÃ¡n contractualmente obligados a proteger su informaciÃ³n conforme a la LFPDPPP',
          'Integraciones Autorizadas: Si autoriza integraciones (como Google Calendar o Microsoft Calendar), accedemos Ãºnicamente a informaciÃ³n de disponibilidad segÃºn sus permisos explÃ­citos, sin ver el contenido de sus eventos',
          'Organizaciones (B2B): Si es parte de una organizaciÃ³n cliente, su informaciÃ³n de progreso y actividad puede ser visible para administradores autorizados de su organizaciÃ³n',
          'Cumplimiento Legal: Podemos divulgar informaciÃ³n si es requerido por ley, orden judicial, o proceso legal segÃºn la legislaciÃ³n mexicana o internacional aplicable',
          'Con su Consentimiento: Podemos compartir informaciÃ³n en otras circunstancias con su consentimiento explÃ­cito',
        ],
      },
      {
        number: 8,
        title: 'Cookies y TecnologÃ­as de Seguimiento',
        content: 'Utilizamos cookies y tecnologÃ­as similares para mejorar su experiencia, analizar el uso y personalizar contenido:',
        list: [
          'Cookies Esenciales: Necesarias para el funcionamiento de la plataforma (autenticaciÃ³n, seguridad, sesiÃ³n)',
          'Cookies de Funcionalidad: Recuerdan sus preferencias y configuraciones (tema claro/oscuro, idioma preferido)',
          'Cookies AnalÃ­ticas: Nos ayudan a entender cÃ³mo los usuarios interactÃºan con nuestra plataforma. Puede optar por no participar en el seguimiento analÃ­tico',
        ],
      },
      {
        number: 9,
        title: 'Seguridad de Datos',
        content: 'Implementamos medidas de seguridad robustas para proteger su informaciÃ³n personal:',
        list: [
          'Cifrado: Utilizamos cifrado para datos en trÃ¡nsito y datos sensibles en reposo',
          'Almacenamiento Seguro: Sus datos se almacenan en servidores seguros con controles de acceso estrictos',
          'AutenticaciÃ³n: Requerimos autenticaciÃ³n segura con contraseÃ±as cifradas y soporte para autenticaciÃ³n social',
          'Control de Acceso: Implementamos controles de acceso basados en roles para garantizar que solo personal autorizado acceda a la informaciÃ³n necesaria',
          'Monitoreo: Monitoreamos continuamente nuestros sistemas para detectar y responder a amenazas de seguridad',
        ],
      },
      {
        number: 10,
        title: 'Sus Derechos ARCO (MÃ©xico) y GDPR (Europa)',
        content: 'Conforme a la Ley Federal de ProtecciÃ³n de Datos Personales en PosesiÃ³n de los Particulares (LFPDPPP) de MÃ©xico y el GDPR europeo, usted tiene los siguientes derechos:',
        list: [
          'Derecho de Acceso: Puede solicitar una copia de la informaciÃ³n personal que tenemos sobre usted',
          'Derecho de RectificaciÃ³n: Puede corregir informaciÃ³n inexacta o incompleta',
          'Derecho de CancelaciÃ³n/EliminaciÃ³n: Puede solicitar que eliminemos su informaciÃ³n personal, sujeto a ciertas excepciones legales',
          'Derecho de OposiciÃ³n: Puede oponerse al procesamiento de su informaciÃ³n personal en ciertas circunstancias',
          'Derecho a la Portabilidad de Datos: Puede solicitar que transfiramos sus datos en un formato estructurado',
          'Derecho de Retirar Consentimiento: Si el procesamiento se basa en consentimiento, puede retirarlo en cualquier momento',
          'Para ejercer estos derechos, puede contactarnos a travÃ©s de los medios indicados en esta polÃ­tica. Responderemos a su solicitud dentro de los plazos establecidos por la ley aplicable (20 dÃ­as hÃ¡biles para LFPDPPP, 30 dÃ­as para GDPR)',
        ],
      },
      {
        number: 11,
        title: 'Privacidad de Menores',
        content: 'Nuestros servicios no estÃ¡n dirigidos a menores de 18 aÃ±os. No recopilamos intencionalmente informaciÃ³n personal de menores de 18 aÃ±os sin el consentimiento verificable de los padres o tutores, conforme a la legislaciÃ³n mexicana de protecciÃ³n de menores y el GDPR. Si descubrimos que hemos recopilado informaciÃ³n de un menor sin el consentimiento adecuado, tomaremos medidas para eliminar esa informaciÃ³n de nuestros servidores.',
      },
      {
        number: 12,
        title: 'Transferencias Internacionales de Datos',
        content: 'Su informaciÃ³n puede ser transferida y procesada en paÃ­ses distintos al suyo. Cuando transferimos datos internacionalmente, implementamos salvaguardias apropiadas para garantizar que su informaciÃ³n personal reciba un nivel adecuado de protecciÃ³n conforme a la LFPDPPP de MÃ©xico, el GDPR de la UniÃ³n Europea, y demÃ¡s legislaciones aplicables en LatinoamÃ©rica.',
      },
      {
        number: 13,
        title: 'RetenciÃ³n de Datos',
        content: 'Conservamos su informaciÃ³n personal durante el tiempo necesario para cumplir con los propÃ³sitos descritos en esta polÃ­tica, a menos que la ley requiera o permita un perÃ­odo de retenciÃ³n mÃ¡s largo. Cuando ya no necesitemos su informaciÃ³n personal, la eliminaremos o anonimizaremos de manera segura. Para cuentas activas, conservamos la informaciÃ³n mientras su cuenta estÃ© activa y durante un perÃ­odo razonable despuÃ©s para cumplir con obligaciones legales.',
      },
      {
        number: 14,
        title: 'Cambios a esta PolÃ­tica de Privacidad',
        content: 'Podemos actualizar esta PolÃ­tica de Privacidad periÃ³dicamente para reflejar cambios en nuestras prÃ¡cticas o por razones operativas, legales o regulatorias. Le notificaremos de cambios materiales mediante un aviso prominente en nuestra plataforma o por correo electrÃ³nico antes de que los cambios entren en vigor. Su uso continuado de nuestros servicios despuÃ©s de dichos cambios constituye su aceptaciÃ³n de la polÃ­tica revisada.',
      },
      {
        number: 15,
        title: 'InformaciÃ³n de Contacto y Ejercicio de Derechos',
        content: 'Si tiene preguntas, inquietudes o solicitudes relacionadas con esta PolÃ­tica de Privacidad o desea ejercer sus derechos ARCO (Acceso, RectificaciÃ³n, CancelaciÃ³n y OposiciÃ³n), puede contactarnos a travÃ©s de: (a) nuestro sitio web en la secciÃ³n de contacto, (b) enviando un correo electrÃ³nico a nuestro equipo de privacidad. Responderemos a su solicitud dentro de los plazos requeridos por la ley aplicable.',
      },
    ],
  },
  conduct: {
    title: 'CÃ³digo de Conducta',
    icon: 'Users',
    sections: [
      {
        number: 1,
        title: 'Comportamiento Esperado',
        content: 'Nuestra comunidad se basa en el respeto mutuo, la colaboraciÃ³n y el aprendizaje constructivo. Todos los usuarios deben:',
        list: [
          'Tratar a todos los miembros de la comunidad con respeto, cortesÃ­a y dignidad, independientemente de su origen, gÃ©nero, orientaciÃ³n sexual, religiÃ³n, nivel de experiencia o cualquier otra caracterÃ­stica personal',
          'Contribuir de manera constructiva a discusiones, compartir conocimientos de manera Ãºtil y participar activamente en el aprendizaje colaborativo',
          'Respetar la propiedad intelectual de otros, citando apropiadamente fuentes y no plagiar contenido',
          'Mantener un ambiente de aprendizaje positivo, constructivo y acogedor para todos',
          'Comunicarse de manera profesional y educada en todos los espacios de la comunidad',
          'Reportar comportamiento inapropiado cuando sea necesario',
        ],
      },
      {
        number: 2,
        title: 'Comportamiento Prohibido',
        content: 'Los siguientes comportamientos estÃ¡n estrictamente prohibidos y pueden resultar en acciÃ³n disciplinaria inmediata:',
        list: [
          'Acoso, intimidaciÃ³n, discriminaciÃ³n, hostigamiento o comportamiento abusivo hacia otros usuarios',
          'Publicar contenido ofensivo, inapropiado, difamatorio, obsceno, pornogrÃ¡fico, violento o que promueva actividades ilegales',
          'Hacer spam, publicidad no autorizada, o promover productos o servicios sin permiso',
          'Compartir informaciÃ³n falsa, engaÃ±osa, o desinformaciÃ³n intencional',
          'Suplantar la identidad de otra persona, organizaciÃ³n o entidad',
          'Acceder no autorizado a cuentas, sistemas o datos de otros usuarios',
          'Realizar actividades que violen derechos de propiedad intelectual o confidencialidad',
          'Manipular o intentar comprometer la seguridad de la plataforma',
          'Publicar informaciÃ³n personal de otros usuarios sin su consentimiento',
          'Cualquier actividad que viole leyes aplicables o regulaciones',
        ],
      },
      {
        number: 3,
        title: 'Consecuencias del Incumplimiento',
        content: 'El incumplimiento de este CÃ³digo de Conducta puede resultar en acciones disciplinarias, que pueden incluir:',
        list: [
          'Advertencia formal por escrito',
          'EliminaciÃ³n de contenido inapropiado',
          'SuspensiÃ³n temporal de la cuenta con duraciÃ³n determinada',
          'SuspensiÃ³n permanente de la cuenta y prohibiciÃ³n del uso de nuestros servicios',
          'Reporte a autoridades legales si el comportamiento viola leyes aplicables',
          'Medidas legales adicionales segÃºn sea necesario para proteger nuestros usuarios y servicios',
        ],
      },
      {
        number: 4,
        title: 'Proceso de Reporte',
        content: 'Si experimenta o presencia comportamiento que viola este CÃ³digo de Conducta, le animamos a reportarlo de inmediato utilizando las herramientas de reporte en la plataforma o contactando directamente a nuestro equipo de moderaciÃ³n. Todos los reportes serÃ¡n revisados de manera confidencial y se tomarÃ¡n medidas apropiadas.',
      },
    ],
  },
};
