export const LEGAL_DOCUMENTS = {
  terms: {
    title: 'Términos y Condiciones de Uso',
    icon: 'FileText',
    sections: [
      {
        number: 1,
        title: 'Aceptación de los Términos',
        content:
          'Estos Términos y Condiciones de Uso ("Términos") constituyen un acuerdo legal entre usted ("Usuario", "usted" o "su") y SOFIA ("nosotros", "nuestro" o "la Plataforma"). Al acceder, utilizar, registrarse o interactuar de cualquier manera con nuestra plataforma de capacitación en inteligencia artificial ubicada en nuestro sitio web (la "Plataforma"), usted acepta estar legalmente vinculado por estos Términos. Si no está de acuerdo con alguno de estos términos, no debe acceder ni utilizar nuestros servicios.',
      },
      {
        number: 2,
        title: 'Descripción del Servicio',
        content: 'SOFIA es una plataforma educativa B2B que ofrece servicios de capacitación empresarial en inteligencia artificial, incluyendo pero no limitado a:',
        list: [
          'Cursos en línea de inteligencia artificial, machine learning y tecnologías relacionadas',
          'Contenido educativo interactivo, incluyendo videos, lecciones, materiales de estudio y recursos multimedia',
          'Sistema de evaluación y certificaciones verificables',
          'Comunidad de aprendizaje con foros, preguntas y respuestas, y colaboración entre usuarios',
          'Asistente virtual de IA (LIA) para apoyo educativo',
          'Planificador de estudios integrado con calendarios externos',
          'Gestión de equipos y reportes de progreso para organizaciones',
          'Sistema de noticias y artículos educativos',
          'Directorio de aplicaciones de IA',
          'Panel de administración para organizaciones con personalización de marca',
        ],
      },
      {
        number: 3,
        title: 'Elegibilidad y Registro de Cuenta',
        content: 'Para utilizar nuestros servicios, usted debe: (a) ser mayor de edad según las leyes de su jurisdicción (típicamente 18 años o más), (b) tener la capacidad legal para celebrar contratos vinculantes, (c) proporcionar información precisa y completa durante el registro, y (d) mantener la confidencialidad de sus credenciales de cuenta. Usted es responsable de todas las actividades que ocurran bajo su cuenta. Debe notificarnos inmediatamente de cualquier uso no autorizado de su cuenta.',
      },
      {
        number: 4,
        title: 'Uso Aceptable de la Plataforma',
        content: 'Usted acepta utilizar la Plataforma únicamente para fines legales y educativos, y de acuerdo con estos Términos. Específicamente, usted se compromete a:',
        list: [
          'Utilizar la Plataforma solo para su propósito educativo previsto',
          'No intentar acceder a áreas restringidas de la Plataforma o a cuentas de otros usuarios',
          'No realizar ingeniería inversa, descompilar o desensamblar cualquier parte de la Plataforma',
          'No introducir virus, malware, código malicioso o cualquier otro dispositivo dañino',
          'No realizar actividades de scraping, crawling o extracción automatizada de datos sin autorización previa',
          'No utilizar bots, scripts automatizados o sistemas que puedan sobrecargar nuestros servidores',
          'Respetar los derechos de propiedad intelectual de otros usuarios y de la Plataforma',
          'No compartir su cuenta con terceros',
          'No utilizar la Plataforma para actividades ilegales, fraudulentas o que violen derechos de terceros',
        ],
      },
      {
        number: 5,
        title: 'Contenido del Usuario',
        content: 'Usted conserva todos los derechos de propiedad sobre el contenido que cree, publique o comparta en la Plataforma ("Contenido del Usuario"). Sin embargo, al publicar contenido, usted nos otorga una licencia mundial, no exclusiva, libre de regalías, transferible y sublicenciable para usar, reproducir, distribuir, preparar trabajos derivados y mostrar dicho contenido en relación con la Plataforma y nuestros servicios. Usted es responsable de asegurar que su Contenido del Usuario no viole leyes aplicables, derechos de terceros o estos Términos.',
      },
      {
        number: 6,
        title: 'Propiedad Intelectual',
        content: 'Todos los derechos de propiedad intelectual sobre la Plataforma, incluyendo pero no limitado a textos, gráficos, logos, iconos, imágenes, clips de audio y video, software, compilaciones de datos, diseño, estructura y organización de la Plataforma, son propiedad de SOFIA o de nuestros licenciantes y están protegidos por leyes de derechos de autor, marcas registradas, secretos comerciales y otras leyes de propiedad intelectual. No se otorgan licencias implícitas. Usted no puede reproducir, distribuir, modificar, crear trabajos derivados, mostrar públicamente, realizar públicamente, republicar, descargar, almacenar o transmitir ningún material de la Plataforma sin nuestro permiso previo por escrito.',
      },
      {
        number: 7,
        title: 'Suscripciones y Pagos',
        content: 'Algunos servicios de la Plataforma pueden requerir el pago de tarifas de suscripción. Los precios, términos de facturación y métodos de pago se especificarán durante el proceso de registro. Todas las tarifas son no reembolsables a menos que se indique lo contrario o sea requerido por ley aplicable. Nos reservamos el derecho de modificar nuestras tarifas con aviso previo de al menos 30 días. Las organizaciones que contraten planes Team, Business o Enterprise estarán sujetas a términos de servicio adicionales según el plan seleccionado.',
      },
      {
        number: 8,
        title: 'Integraciones con Servicios de Terceros',
        content: 'La Plataforma puede integrarse con servicios de terceros, incluyendo Google Calendar, Microsoft Calendar, OpenAI, y otros servicios ("Servicios de Terceros"). Su uso de estos Servicios de Terceros está sujeto a los términos y condiciones de dichos servicios. No somos responsables de la disponibilidad, precisión, contenido, políticas o prácticas de ningún Servicio de Terceros. Cuando usted autoriza el acceso a sus datos de Servicios de Terceros, usted nos otorga permiso para acceder, almacenar y utilizar dichos datos según sea necesario para proporcionar nuestros servicios.',
      },
      {
        number: 9,
        title: 'Privacidad y Protección de Datos',
        content: 'Su privacidad es importante para nosotros. Nuestro uso de su información personal está gobernado por nuestra Política de Privacidad, que forma parte integral de estos Términos. Al utilizar la Plataforma, usted consiente la recopilación, uso y divulgación de su información personal según se describe en nuestra Política de Privacidad. Cumplimos con el Reglamento General de Protección de Datos (GDPR), la Ley de Privacidad del Consumidor de California (CCPA) y otras leyes de protección de datos aplicables.',
      },
      {
        number: 10,
        title: 'Modificaciones del Servicio',
        content: 'Nos reservamos el derecho de modificar, suspender, interrumpir o discontinuar cualquier aspecto de la Plataforma en cualquier momento, con o sin previo aviso. Podemos realizar mejoras, cambios o actualizaciones a la Plataforma sin previo aviso. No seremos responsables ante usted ni ante terceros por cualquier modificación, suspensión o interrupción del servicio.',
      },
      {
        number: 11,
        title: 'Terminación',
        content: 'Podemos terminar o suspender su acceso a la Plataforma inmediatamente, sin previo aviso o responsabilidad, por cualquier motivo, incluyendo pero no limitado a una violación de estos Términos. Tras la terminación, su derecho a utilizar la Plataforma cesará inmediatamente. Todas las disposiciones de estos Términos que por su naturaleza deban sobrevivir a la terminación sobrevivirán a la terminación, incluyendo pero no limitado a disposiciones de propiedad, renuncias de garantía, indemnización y limitaciones de responsabilidad.',
      },
      {
        number: 12,
        title: 'Renuncia de Garantías',
        content: 'LA PLATAFORMA SE PROPORCIONA "TAL CUAL" Y "SEGÚN DISPONIBILIDAD" SIN GARANTÍAS DE NINGÚN TIPO, YA SEAN EXPRESAS O IMPLÍCITAS, INCLUYENDO PERO NO LIMITADO A GARANTÍAS IMPLÍCITAS DE COMERCIABILIDAD, IDONEIDAD PARA UN PROPÓSITO PARTICULAR Y NO VIOLACIÓN. NO GARANTIZAMOS QUE LA PLATAFORMA ESTÉ DISPONIBLE DE MANERA ININTERRUMPIDA O LIBRE DE ERRORES, QUE LOS DEFECTOS SERÁN CORREGIDOS, O QUE LA PLATAFORMA O EL SERVIDOR QUE LA HACE DISPONIBLE ESTÉN LIBRES DE VIRUS U OTROS COMPONENTES DAÑINOS.',
      },
      {
        number: 13,
        title: 'Limitación de Responsabilidad',
        content: 'EN NINGÚN CASO SEREMOS RESPONSABLES ANTE USTED O CUALQUIER TERCERO POR DAÑOS INDIRECTOS, INCIDENTALES, ESPECIALES, CONSECUENCIALES O PUNITIVOS, INCLUYENDO PERO NO LIMITADO A PÉRDIDA DE BENEFICIOS, PÉRDIDA DE DATOS, PÉRDIDA DE OPORTUNIDADES COMERCIALES, O DAÑOS A LA REPUTACIÓN, QUE SURJAN DE O ESTÉN RELACIONADOS CON EL USO O LA IMPOSIBILIDAD DE USAR LA PLATAFORMA, INCLUSO SI HEMOS SIDO ADVERTIDOS DE LA POSIBILIDAD DE TALES DAÑOS. NUESTRA RESPONSABILIDAD TOTAL ANTE USTED NO EXCEDERÁ EL MONTO QUE USTED HA PAGADO A NOSOTROS EN LOS ÚLTIMOS 12 MESES.',
      },
      {
        number: 14,
        title: 'Indemnización',
        content: 'Usted acepta indemnizar, defender y mantener indemnes a SOFIA, sus afiliados, directores, empleados, agentes y licenciantes de y contra todas y cada una de las reclamaciones, daños, obligaciones, pérdidas, responsabilidades, costos o deudas, y gastos (incluidos pero no limitados a honorarios de abogados) que surjan de: (a) su uso e ingreso a la Plataforma, (b) su violación de cualquier término de estos Términos, (c) su violación de cualquier derecho de un tercero, incluidos sin limitación derechos de propiedad intelectual o privacidad, o (d) cualquier reclamación de que su Contenido del Usuario causó daño a un tercero.',
      },
      {
        number: 15,
        title: 'Ley Aplicable y Jurisdicción',
        content: 'Estos Términos se regirán e interpretarán de acuerdo con las leyes de México, sin dar efecto a ningún principio de conflictos de leyes. Cualquier disputa que surja de o esté relacionada con estos Términos será sometida a la jurisdicción exclusiva de los tribunales competentes de la Ciudad de México, México. Si alguna disposición de estos Términos se considera inválida o inaplicable, las disposiciones restantes permanecerán en pleno vigor y efecto.',
      },
      {
        number: 16,
        title: 'Disposiciones Generales',
        content: 'Estos Términos constituyen el acuerdo completo entre usted y nosotros respecto del uso de la Plataforma y reemplazan todos los acuerdos, comunicaciones y entendimientos previos. No podemos transferir nuestros derechos u obligaciones bajo estos Términos sin su consentimiento. Usted no puede transferir sus derechos u obligaciones bajo estos Términos sin nuestro consentimiento previo por escrito. Nuestra omisión de hacer cumplir cualquier derecho o disposición de estos Términos no constituirá una renuncia a dicho derecho o disposición.',
      },
      {
        number: 17,
        title: 'Información de Contacto',
        content: 'Si tiene preguntas sobre estos Términos, puede contactarnos a través de nuestro sitio web o enviando un correo electrónico a nuestro equipo de soporte. Nos reservamos el derecho de actualizar estos Términos en cualquier momento. Le notificaremos de cambios materiales mediante un aviso prominente en la Plataforma o por correo electrónico. Su uso continuado de la Plataforma después de dichos cambios constituye su aceptación de los nuevos Términos.',
      },
    ],
  },
  privacy: {
    title: 'Política de Privacidad',
    icon: 'Shield',
    sections: [
      {
        number: 1,
        title: 'Introducción y Alcance',
        content:
          'Esta Política de Privacidad describe cómo SOFIA ("nosotros", "nuestro" o "la Plataforma") recopila, utiliza, almacena, comparte y protege su información personal cuando utiliza nuestra plataforma de capacitación en inteligencia artificial. Esta política se aplica a todos los usuarios de nuestra Plataforma, incluyendo usuarios individuales y organizaciones. Al utilizar nuestros servicios, usted acepta las prácticas descritas en esta política. Esta Política de Privacidad cumple con el Reglamento General de Protección de Datos (GDPR) de la Unión Europea, la Ley de Privacidad del Consumidor de California (CCPA), y otras leyes de protección de datos aplicables.',
      },
      {
        number: 2,
        title: 'Información que Recopilamos',
        content: 'Recopilamos diferentes tipos de información para proporcionar y mejorar nuestros servicios:',
        list: [
          'Información de Identificación Personal: Nombre completo, dirección de correo electrónico, número de teléfono, nombre de usuario, y cualquier otra información que proporcione voluntariamente durante el registro o al actualizar su perfil',
          'Información de Perfil: Foto de perfil, biografía, ubicación, cargo o rol profesional, enlaces a redes sociales (LinkedIn, GitHub, sitio web personal), currículum vitae, y preferencias de privacidad',
          'Información de Autenticación: Credenciales de inicio de sesión (email y contraseña hasheada), tokens de sesión, información de autenticación de dos factores si está habilitada, e información de autenticación social (Google, Microsoft) cuando utiliza estos métodos',
          'Información Académica y de Progreso: Cursos inscritos, lecciones completadas, calificaciones, certificados obtenidos, tiempo de estudio, notas y marcadores, progreso en evaluaciones, habilidades desarrolladas, y estadísticas de aprendizaje',
          'Información de Uso de la Plataforma: Páginas visitadas, tiempo de permanencia, clics, búsquedas realizadas, interacciones con el asistente de IA (LIA), mensajes en comunidades, publicaciones, comentarios, votos, y otras actividades en la plataforma',
          'Información de Dispositivo y Técnica: Dirección IP, tipo de navegador, sistema operativo, tipo de dispositivo, identificadores de dispositivo, cookies, tecnologías de seguimiento, registros de servidor, y datos de rendimiento de la aplicación (Web Vitals)',
          'Información de Calendario (opcional): Si autoriza la integración, accedemos a información de disponibilidad en su calendario de Google o Microsoft para el planificador de estudios, pero NO leemos el contenido de sus eventos, solo verificamos horarios ocupados',
          'Información de Organización (para usuarios B2B): Si es parte de una organización, recopilamos información sobre su organización, equipo, asignaciones de cursos, reportes de progreso, y configuraciones corporativas',
          'Información de Comunicación: Registro de correos electrónicos enviados, notificaciones push, mensajes de la plataforma, y su interacción con nuestras comunicaciones',
        ],
      },
      {
        number: 3,
        title: 'Cómo Utilizamos su Información',
        content: 'Utilizamos la información recopilada para los siguientes propósitos:',
        list: [
          'Provisión de Servicios: Proporcionar, mantener y mejorar nuestros servicios educativos, procesar registros y transacciones, gestionar su cuenta y autenticación, y entregar contenido personalizado',
          'Personalización: Personalizar su experiencia de aprendizaje, recomendar cursos relevantes, adaptar el contenido a sus necesidades, y crear planes de estudio personalizados',
          'Comunicación: Enviar notificaciones sobre su progreso, actualizaciones del curso, recordatorios, mensajes de la comunidad, y comunicaciones importantes del servicio. Puede optar por no recibir comunicaciones de marketing',
          'Análisis y Mejora: Analizar el uso de la plataforma para mejorar nuestros servicios, realizar investigación y análisis, desarrollar nuevas características, y entender las tendencias de uso',
          'Seguridad y Prevención de Fraude: Detectar, prevenir y abordar fraudes, abusos, actividades ilegales, proteger la seguridad de nuestra plataforma y usuarios, y hacer cumplir nuestros términos de servicio',
          'Soporte al Cliente: Responder a sus consultas, proporcionar asistencia técnica, resolver problemas, y mejorar nuestro servicio al cliente',
          'Cumplimiento Legal: Cumplir con obligaciones legales, responder a solicitudes legales válidas, proteger nuestros derechos legales, y hacer cumplir nuestros términos y condiciones',
          'Reportes para Organizaciones: Para usuarios B2B, generar reportes de progreso, análisis de equipo, y métricas para administradores de la organización',
        ],
      },
      {
        number: 4,
        title: 'Base Legal para el Procesamiento (GDPR)',
        content: 'Para usuarios en la Unión Europea, procesamos su información personal basándonos en las siguientes bases legales:',
        list: [
          'Consentimiento: Cuando usted ha dado su consentimiento claro para el procesamiento de sus datos personales para uno o más fines específicos',
          'Ejecución de Contrato: Cuando el procesamiento es necesario para la ejecución de un contrato del que usted es parte o para tomar medidas a su solicitud antes de celebrar un contrato',
          'Obligación Legal: Cuando el procesamiento es necesario para cumplir con una obligación legal a la que estamos sujetos',
          'Intereses Legítimos: Cuando el procesamiento es necesario para nuestros intereses legítimos o los de un tercero, excepto cuando dichos intereses estén anulados por sus intereses o derechos fundamentales',
        ],
      },
      {
        number: 5,
        title: 'Compartir y Divulgación de Información',
        content: 'No vendemos su información personal. Compartimos información en las siguientes circunstancias:',
        list: [
          'Proveedores de Servicios: Compartimos información con proveedores de servicios de confianza que nos ayudan a operar nuestra plataforma, incluyendo alojamiento en la nube (Supabase), servicios de email, procesamiento de pagos, análisis, y servicios de IA (OpenAI para el asistente LIA, ElevenLabs para síntesis de voz). Todos estos proveedores están contractualmente obligados a proteger su información',
          'Integraciones Autorizadas: Si autoriza integraciones (como Google Calendar o Microsoft Calendar), compartimos la información necesaria según sus permisos explícitos',
          'Organizaciones (B2B): Si es parte de una organización cliente, su información de progreso y actividad puede ser visible para administradores autorizados de su organización',
          'Cumplimiento Legal: Podemos divulgar información si es requerido por ley, orden judicial, proceso legal, o solicitud gubernamental, o para proteger nuestros derechos, propiedad o seguridad',
          'Transferencias Comerciales: En caso de fusión, adquisición, reestructuración, o venta de activos, su información puede ser transferida como parte de esa transacción',
          'Con su Consentimiento: Podemos compartir información en otras circunstancias con su consentimiento explícito',
        ],
      },
      {
        number: 6,
        title: 'Cookies y Tecnologías de Seguimiento',
        content: 'Utilizamos cookies y tecnologías similares para mejorar su experiencia, analizar el uso y personalizar contenido. Tipos de cookies que utilizamos:',
        list: [
          'Cookies Esenciales: Necesarias para el funcionamiento de la plataforma (autenticación, seguridad, sesión)',
          'Cookies de Funcionalidad: Recuerdan sus preferencias y configuraciones (tema, idioma, preferencias de visualización)',
          'Cookies Analíticas: Nos ayudan a entender cómo los usuarios interactúan con nuestra plataforma (Google Analytics, Web Vitals). Puede optar por no participar en el seguimiento analítico',
          'Cookies de Marketing: Utilizadas para mostrar contenido relevante y medir la efectividad de campañas (solo con su consentimiento)',
        ],
      },
      {
        number: 7,
        title: 'Almacenamiento y Seguridad de Datos',
        content: 'Implementamos medidas de seguridad técnicas, administrativas y físicas robustas para proteger su información personal:',
        list: [
          'Cifrado: Utilizamos cifrado SSL/TLS para datos en tránsito y cifrado en reposo para datos sensibles',
          'Almacenamiento Seguro: Sus datos se almacenan en servidores seguros administrados por Supabase (PostgreSQL) con controles de acceso estrictos',
          'Autenticación: Requerimos autenticación segura con contraseñas hasheadas (bcrypt) y soporte para autenticación de dos factores',
          'Control de Acceso: Implementamos controles de acceso basados en roles (RBAC) y políticas de seguridad a nivel de base de datos (RLS - Row Level Security)',
          'Monitoreo: Monitoreamos continuamente nuestros sistemas para detectar y responder a amenazas de seguridad',
          'Retención de Datos: Conservamos su información personal solo durante el tiempo necesario para cumplir con los fines descritos en esta política o según lo requerido por ley',
        ],
      },
      {
        number: 8,
        title: 'Sus Derechos de Privacidad',
        content: 'Dependiendo de su ubicación, usted tiene los siguientes derechos respecto de su información personal:',
        list: [
          'Derecho de Acceso: Puede solicitar una copia de la información personal que tenemos sobre usted',
          'Derecho de Rectificación: Puede corregir información inexacta o incompleta',
          'Derecho al Olvido (Eliminación): Puede solicitar que eliminemos su información personal, sujeto a ciertas excepciones legales',
          'Derecho a la Portabilidad de Datos: Puede solicitar que transfiramos sus datos a otro proveedor de servicios en un formato estructurado',
          'Derecho de Oposición: Puede oponerse al procesamiento de su información personal en ciertas circunstancias',
          'Derecho a Restringir el Procesamiento: Puede solicitar que limitemos cómo procesamos su información',
          'Derecho de Retirar Consentimiento: Si el procesamiento se basa en consentimiento, puede retirarlo en cualquier momento',
          'Derecho de No Ser Objeto de Decisiones Automatizadas: Tiene derecho a no ser objeto de decisiones basadas únicamente en procesamiento automatizado',
        ],
      },
      {
        number: 9,
        title: 'Privacidad de Menores',
        content: 'Nuestros servicios no están dirigidos a menores de 18 años. No recopilamos intencionalmente información personal de menores de 18 años sin el consentimiento verificable de los padres. Si descubrimos que hemos recopilado información de un menor sin el consentimiento adecuado, tomaremos medidas para eliminar esa información de nuestros servidores. Si es padre o tutor y cree que su hijo nos ha proporcionado información personal, contáctenos inmediatamente.',
      },
      {
        number: 10,
        title: 'Transferencias Internacionales de Datos',
        content: 'Su información puede ser transferida y procesada en países distintos al suyo. Cuando transferimos datos desde el Espacio Económico Europeo (EEE) a otros países, implementamos salvaguardias apropiadas, incluyendo Cláusulas Contractuales Tipo aprobadas por la Comisión Europea, para garantizar que su información personal reciba un nivel adecuado de protección según las leyes aplicables.',
      },
      {
        number: 11,
        title: 'Retención de Datos',
        content: 'Conservamos su información personal durante el tiempo necesario para cumplir con los propósitos descritos en esta política, a menos que la ley requiera o permita un período de retención más largo. Cuando ya no necesitemos su información personal, la eliminaremos o anonimizaremos de manera segura. Para cuentas activas, conservamos la información mientras su cuenta esté activa y durante un período razonable después para cumplir con obligaciones legales, resolver disputas y hacer cumplir nuestros acuerdos.',
      },
      {
        number: 12,
        title: 'Enlaces a Sitios de Terceros',
        content: 'Nuestra plataforma puede contener enlaces a sitios web de terceros. No somos responsables de las prácticas de privacidad o el contenido de estos sitios externos. Le recomendamos que revise las políticas de privacidad de cualquier sitio de terceros que visite.',
      },
      {
        number: 13,
        title: 'Cambios a esta Política de Privacidad',
        content: 'Podemos actualizar esta Política de Privacidad periódicamente para reflejar cambios en nuestras prácticas o por razones operativas, legales o regulatorias. Le notificaremos de cambios materiales mediante un aviso prominente en nuestra plataforma o por correo electrónico antes de que los cambios entren en vigor. Su uso continuado de nuestros servicios después de dichos cambios constituye su aceptación de la política revisada.',
      },
      {
        number: 14,
        title: 'Información de Contacto y Ejercicio de Derechos',
        content: 'Si tiene preguntas, inquietudes o solicitudes relacionadas con esta Política de Privacidad o sus derechos de privacidad, puede contactarnos a través de: (a) nuestro sitio web en la sección de contacto, (b) enviando un correo electrónico a nuestro equipo de privacidad. Responderemos a su solicitud dentro de los plazos requeridos por la ley aplicable (típicamente 30 días para GDPR, 45 días para CCPA). Para ejercer sus derechos, puede utilizar las funciones de privacidad en su perfil de cuenta o contactarnos directamente.',
      },
    ],
  },
  conduct: {
    title: 'Código de Conducta',
    icon: 'Users',
    sections: [
      {
        number: 1,
        title: 'Comportamiento Esperado',
        content: 'Nuestra comunidad se basa en el respeto mutuo, la colaboración y el aprendizaje constructivo. Todos los usuarios deben:',
        list: [
          'Tratar a todos los miembros de la comunidad con respeto, cortesía y dignidad, independientemente de su origen, género, orientación sexual, religión, nivel de experiencia o cualquier otra característica personal',
          'Contribuir de manera constructiva a discusiones, compartir conocimientos de manera útil y participar activamente en el aprendizaje colaborativo',
          'Respetar la propiedad intelectual de otros, citando apropiadamente fuentes y no plagiar contenido',
          'Mantener un ambiente de aprendizaje positivo, constructivo y acogedor para todos',
          'Comunicarse de manera profesional y educada en todos los espacios de la comunidad',
          'Reportar comportamiento inapropiado cuando sea necesario',
        ],
      },
      {
        number: 2,
        title: 'Comportamiento Prohibido',
        content: 'Los siguientes comportamientos están estrictamente prohibidos y pueden resultar en acción disciplinaria inmediata:',
        list: [
          'Acoso, intimidación, discriminación, hostigamiento o comportamiento abusivo hacia otros usuarios',
          'Publicar contenido ofensivo, inapropiado, difamatorio, obsceno, pornográfico, violento o que promueva actividades ilegales',
          'Hacer spam, publicidad no autorizada, o promover productos o servicios sin permiso',
          'Compartir información falsa, engañosa, o desinformación intencional',
          'Suplantar la identidad de otra persona, organización o entidad',
          'Acceder no autorizado a cuentas, sistemas o datos de otros usuarios',
          'Realizar actividades que violen derechos de propiedad intelectual o confidencialidad',
          'Manipular, hackear o intentar comprometer la seguridad de la plataforma',
          'Publicar información personal de otros usuarios sin su consentimiento',
          'Cualquier actividad que viole leyes aplicables o regulaciones',
        ],
      },
      {
        number: 3,
        title: 'Consecuencias del Incumplimiento',
        content: 'El incumplimiento de este Código de Conducta puede resultar en acciones disciplinarias, que pueden incluir:',
        list: [
          'Advertencia formal por escrito',
          'Eliminación de contenido inapropiado',
          'Suspensión temporal de la cuenta con duración determinada',
          'Suspensión permanente de la cuenta y prohibición del uso de nuestros servicios',
          'Reporte a autoridades legales si el comportamiento viola leyes aplicables',
          'Medidas legales adicionales según sea necesario para proteger nuestros usuarios y servicios',
        ],
      },
      {
        number: 4,
        title: 'Proceso de Reporte',
        content: 'Si experimenta o presencia comportamiento que viola este Código de Conducta, le animamos a reportarlo de inmediato utilizando las herramientas de reporte en la plataforma o contactando directamente a nuestro equipo de moderación. Todos los reportes serán revisados de manera confidencial y se tomarán medidas apropiadas.',
      },
    ],
  },
};
